### ISSUE TITLE
ISessionManagementService was not recognized

### ISSUE THREAD

**Issue by yfereidouni** [DuendeSoftware/Support#100]
**Which version of Duende IdentityServer are you using?**  5.2.2

**Which version of .NET are you using?** 5.0

**Describe the bug**
Error	CS0246	The type or namespace name 'CompleteBackchannelLoginRequest' could not be found (are you missing a using directive or an assembly reference?)

I wanted to add IdentityServer.UI but after adding pages and wwwroot folder to my project, some of the types are not recognized and faced with reference errors. I think the version of Duende.Identity.Server 5.2.2 is not match with .NET5
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by leastprivilege** [comment]
The latest version of the UI requires IdentityServer v6. 

Any version before that will EOL in December this year, so please use the latest.
