### ISSUE TITLE
RequirePkce = true is not enforcing PKCE

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#1000]
I'm using IDS 6 running on .NET 6, with an ASP.NET 4.8 client.

I've set `RequirePkce` to true in the following:
```
"IdentityServer": {
  "Clients": [
    {
      "Enabled": true,
      "ClientId": "pt-web",
      "ClientName": "PT",
      "ClientSecrets": [ { "Value": "valueHere" } ],
      "RedirectUris": [ "https://127.0.0.1:44300/authentication/callback" ],
      "PostLogoutRedirectUris": [ "https://127.0.0.1:44300/" ],
      "AllowedCorsOrigins": [ "https://127.0.0.1:44300" ],
      "FrontChannelLogoutUri": "https://127.0.0.1:44300/Authentication/ExternalLogout",
      "AllowedGrantTypes": [ "authorization_code", "client_credentials" ],
      "AllowedScopes": [ "openid", "offline_access", "read", "ptpro" ],
      "RequireConsent": false,
      "AllowOfflineAccess": true,
      "AlwaysIncludeUserClaimsInIdToken": true,
      "AllowAccessTokensViaBrowser": true,
      "IdentityTokenLifetime": 36000,
      "AccessTokenLifetime": 36000,
      "AuthorizationCodeLifetime": 3000,
      "RefreshTokenUsage": "ReUse",
      "UpdateAccessTokenClaimsOnRefresh": true,
      "RefreshTokenExpiration": "Sliding",
      "IncludeJwtId": true,
      "AlwaysSendClientClaims": true,
      "RequirePkce": true
    },
}
```
I'm loading this here:

```
var identitySetup =
    services.AddIdentityServer(options =>
        {
            options.LicenseKey = _identityProviderSettings.LicenseKey;
            options.AccessTokenJwtType = "JWT";
            options.EmitStaticAudienceClaim = true;
            options.KeyManagement.Enabled = false;  // Business+ license only
        })
        .AddAppAuthRedirectUriValidator()
        .AddInMemoryClients(_configuration.GetSection("IdentityServer:Clients"))
        .AddInMemoryApiScopes(_configuration.GetSection("IdentityServer:ApiScopes"))
        .AddInMemoryApiResources(_configuration.GetSection("IdentityServer:ApiResources"))
        .AddInMemoryIdentityResources(_configuration.GetSection("IdentityServer:IdentityResources"));
```

My client running ASP.NET 4.8 is not generating any codes for PKCE.

Here's the authorization request:

`https://localhost:44349/connect/authorize?client_id=pt-web&response_type=code&scope=openid+read+offline_access+ptpro&redirect_uri=https%3A%2F%2F127.0.0.1%3A44300%2Fauthentication%2Fcallback&state=%7B%22ReturnUrl%22%3A%22%2F%22%7D`

`https://127.0.0.1:44300/authentication/callback?code=7D33926108662F7CB6D7D01D020FF0963252F169220AE8AE3C8C0E2EFFE32F62-1&scope=openid%20read%20offline_access%20ptpro&state=%7B%22ReturnUrl%22%3A%22%2F%22%7D&session_state=LcDqqYY2NwVPGWh_Q8WtZLFQL19E92RhByTHUgnrlpl.AF310200EA6767ED56EE2510711829AC&iss=https%3A%2F%2Flocalhost%3A44349`

When my client (127.0.0.1:44300) makes the back-channel request, the response from IDS does not contain any errors about there being no `code_verifier`:

![image](https://github.com/DuendeSoftware/Support/assets/13111539/d5a33aa3-706d-464f-9bf4-b103ea5fa2a5)

Why is `"RequirePkce": true` not making IDS enforce PKCE?

Are there any tutorials for generating the `code_verifier` in the client for ASP.NET Framework?

**Comment by AndersAbel** [comment]
The usage of PKCE is validated both at the authorization endpoint and at the token endpoint when the code is used. If the client is properly setup to require PKCE, the authorization request fails if there is no `code_challenge`.

It appears that despite your configuration, the client when used is not set up to require PKCE. To troubleshoot, try injecting IEnumerable<Client> into a page/controller and use a break point to inspect that the client has indeed `RequirePkce=true`.

For the .Net Framework it's best to use the `Microsoft.Owin.Security.OpenIdConnect` client package. It has built in support for Pkce.

**Comment by DavidKlempfner** [comment]
> The usage of PKCE is validated both at the authorization endpoint and at the token endpoint when the code is used. If the client is properly setup to require PKCE, the authorization request fails if there is no `code_challenge`.
> 
> It appears that despite your configuration, the client when used is not set up to require PKCE. To troubleshoot, try injecting IEnumerable into a page/controller and use a break point to inspect that the client has indeed `RequirePkce=true`.
> 
> For the .Net Framework it's best to use the `Microsoft.Owin.Security.OpenIdConnect` client package. It has built in support for Pkce.

Thanks for your suggestion. I can see the value is definitely `false`.
I tried setting other values such as `IncludeJwtId` to the non-default value of `false`, but that is `true` during execution.
It seems as though it might only be an issue with `Boolean`s, because `context.Client.RefreshTokenExpiration` was set to the non-default value of `Sliding`, and this value is coming through:
![image](https://github.com/DuendeSoftware/Support/assets/13111539/6d6e0aa8-14a8-43d4-b2b7-677c7da596d1)


It seems as though these values are

**Comment by DavidKlempfner** [comment]
@AndersAbel I just realised it's because appsettings.Development.json (which had `"RequirePkce": false`) overrides what I had in appsettings.json, so that explains it.
Thanks for your help.

**Comment by DavidKlempfner** [comment]
@AndersAbel I just realised it's because appsettings.Development.json (which had `"RequirePkce": false`) overrides what I had in appsettings.json, so that explains it.
Thanks for your help.
