### ISSUE TITLE
`IdentityServerTools.IssueClientJwtAsync` throws NRE in a context where `HttpContext.Request.` never been set

### ISSUE THREAD

**Issue by FinHorsley** [DuendeSoftware/Support#1003]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
6.0.416

**Describe the bug**

Apologies in advanced if this is because the method is being misused, but calling `IdentityServerTools.IssueClientJwtAsync` before an http request has been made to IdentityServer causes a null reference exception. 

In my scenario, `IdentityServerTools.IssueClientJwtAsync` is being called so that IdSrv can self-generate an API access_token to retrieve data used as part of token generation. However, it's being called before an http request has been made to it (as part of startup event), so the HttpContext is null.

**To Reproduce**
Call `IdentityServerTools.IssueClientJwtAsync` in a context where `IHttpContextAccessor` has never been called. In this scenario, calling it before an http request has been made to IdentityServer (aside from health/liveness probes).

[See             var request = _httpContextAccessor.HttpContext.Request;](https://github.com/DuendeSoftware/IdentityServer/blob/ef64ef16e84881b1eba4b2cf2ffef39e20eb640b/src/IdentityServer/Services/Default/DefaultServerUrls.cs#L32)

Steps to reproduce the behavior.

**Expected behavior**
Think this might be a tricky one, as how else would IdentityServer know what the issuer address is? If this answers my own question(!), is there a way to set this programatically? though seems hacky at this point

**Log output/exception with stacktrace**

```
Object reference not set to an instance of an object.
   at Duende.IdentityServer.Services.DefaultServerUrls.get_Origin() in /_/src/IdentityServer/Services/Default/DefaultServerUrls.cs:line 32
   at Duende.IdentityServer.Extensions.ServerUrlExtensions.GetUnicodeOrigin(IServerUrls urls) in /_/src/IdentityServer/Extensions/ServerUrlExtensions.cs:line 22
   at Duende.IdentityServer.Services.DefaultIssuerNameService.GetCurrentAsync() in /_/src/IdentityServer/Services/Default/DefaultIssuerNameService.cs:line 65
   at Duende.IdentityServer.IdentityServerTools.IssueJwtAsync(Int32 lifetime, IEnumerable`1 claims) in /_/src/IdentityServer/IdentityServerTools.cs:line 51
   at Duende.IdentityServer.IdentityServerToolsExtensions.IssueClientJwtAsync(IdentityServerTools tools, String clientId, Int32 lifetime, IEnumerable`1 scopes, IEnumerable`1 audiences, IEnumerable`1 additionalClaims) in /_/src/IdentityServer/Extensions/IdentityServerToolsExtensions.cs:line 73
```

**Additional context**

Not sure if relevant, but nginx conf forwarded headers 

```
    location / {
      proxy_pass           http://localhost:51634;
      #proxy_pass           http://localhost:5000;

      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection keep-alive;
      proxy_set_header   Host $http_host;
      proxy_cache_bypass $http_upgrade;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
```

**Comment by AndersAbel** [comment]
> Think this might be a tricky one, as how else would IdentityServer know what the issuer address is?
You're right, IdentityServer by default uses the current request to get the issuer address

> is there a way to set this programatically? though seems hacky at this point
The issuer can be set using `IdentityServerOptions.IssuerUri`. If it is set, the `HttpContextAccessor` is never accessed.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go close this issue?

**Comment by lousybyte** [comment]
Having the same issue, and in our case we cannot set the IssuerUri to a static value because our setup involves having the IdP available through 2 sets of URLs, one internal and one external, and we don't want tokens issued using the external URL to have the internal URL issuer value for example, and vice-versa.

Any workaround for this?

**Comment by josephdecock** [comment]
There are other methods on the IdentityServerTools that take an issuer as an argument, so if you know the issuer you want, you could call one of those overloads. Alternatively, you could write a custom IIusserNameService. IdentityServer as a framework can't really know which issuer you intend, but maybe in your circumstances you can apply some custom logic.

**Comment by lousybyte** [comment]
Ended up using the IssueJwtAsync() function and manually created all the claims needed. Thank you!

**Comment by FinHorsley** [comment]
@josephdecock Sorry for the slow response. This was really useful, thanks. Ended up using the lower-level `IssueJwtAsync` function to manually generate claims

**Comment by FinHorsley** [comment]
@AndersAbel just a thought on your comment from earlier, I'm assuming setting the `IdentityServerOptions.IssuerUri` (in our example to external dns) will stop dynamic issuers from working? E.g. if we're running this in k8s, and an internal service makes a request using the internal dns then the validation would fail as it expected the hardcoded external dns instead?

> The issuer can be set using IdentityServerOptions.IssuerUri. If it is set, the HttpContextAccessor is never accessed.

**Comment by AndersAbel** [comment]
I guess the thumbs up means we are done on this issue, I'm closing it. @FinHorsley please feel free to reopen if there are any more questions.

**Comment by FinHorsley** [comment]
Hi @AndersAbel / @josephdecock thanks for all your help. Yep, issue closed 🙂
