### ISSUE TITLE
Identity Server Error with LinkedIn Login

### ISSUE THREAD

**Issue by askme-sg** [DuendeSoftware/Support#1004]
I am using Duende IdentityServer 5.2.4. .NET version 5.

I encounter the error below after attempting to login with LinkedIn. I can reach the LinkedIn login page and consent page.
![image](https://github.com/DuendeSoftware/Support/assets/151731126/991da87b-de7a-4836-89a1-e7a949e2961a)

**To Reproduce**
This is the piece of code we used for integrating with LinkedIn login.
![image](https://github.com/DuendeSoftware/Support/assets/151731126/78bfc449-35d6-476c-aa56-d37fdb511085)

We expect it to redirect back to homepage after login success.

Please advise.

**Comment by AndersAbel** [comment]
Looks like the combination of client id and client secret is invalid. Please validate the settings with LinkedIn.

**Comment by askme-sg** [comment]
> Looks like the combination of client id and client secret is invalid. Please validate the settings with LinkedIn.

I have verified it, is using the correct credentials from LinkedIn Developer Platform for the application.

**Comment by AndersAbel** [comment]
Then something else is wrong in the configuration. The error message indicates that LinkedIn rejects your client, with an error that "Client Authentication Failed". You would need to contact LinkedIn support to get more information/guidance on why they reject your configuration.

**Comment by askme-sg** [comment]
Hi Anders,

Yes, you can close.

Regards,


[cid:2021-synergy-new-logo_email-signature_d0e1fd69-c436-4a35-8be5-649a64c10d0f.png]<https://www.synergyonline.com><https://www.synergyonline.com>              Milan Gross[https://static.wixstatic.com/media/a98213_c5d7d0c40405422ca945860ad6a60aca~mv2.png]<https://www.synergyonline.com/locations>
Principal

Main: +65-6232-2329<tel:+6562322329>
Mobile: +65-9152-1024<tel:+65-9152-1024> or
Chat with me on Teams ***@***.***>
www.synergyonline.com<https://www.synergyonline.com>
Level 40 Ocean Financial Centre. Singapore, 49321
[https://static.wixstatic.com/media/a98213_45f5692796b54e69950ab5f99cf9ac42~mv2.png]<https://www.facebook.com/SynergySince1995> [https://static.wixstatic.com/media/a98213_8763bc7e681b4ee5802048b647e87d0c~mv2.png] <https://www.linkedin.com/company/synergy-corporate-technologies>  [https://static.wixstatic.com/media/a98213_d043a3d51f63418fbb57d6b34ddca95d~mv2.png] <https://twitter.com/SynergySince95>
[https://static.wixstatic.com/media/a98213_42cee4ab03964a1386fd78c7c544ebec~mv2.png] <https://www.synergyonline.com/microsoft-partner>  [https://static.wixstatic.com/media/a98213_38889b8d87194ecfa7551e207b86104c~mv2.png]  <https://www.synergyonline.com/google-partner>

Privacy Policy<https://www.synergyonline.com/privacy-policy>    In The Business Of Making Your Business Better

**Comment by mlaflamme49** [comment]
Hi @askme-sg ,
Did you ever resolve your issue ? I'm experiencing the exact same thing with my LinkedIn integration.
Thanks
