### ISSUE TITLE
Server sessions and sliding expiration best practice question

### ISSUE THREAD

**Issue by PBMikko** [DuendeSoftware/Support#1005]
**Which version of Duende IdentityServer are you using?**
6.3.6
**Which version of .NET are you using?**
6

We are tasked to build web application that user is required to relogin after 45 minutes of inactivity.

I have implemented server side sessions and documentation says. I have set client to allow refresh tokens (AllowOfflineAccess), and set access token lifetime to 5 minutes and refresh token expiration to 0 and refresh token sliding expiration to 45 minutes. I have also set our RP ASP.NET core MVC/razor application authentication cookie ticket expiration to 5 minutes. Also backchannel logout and session expiration notifications has been implemented (took example from sample app).

I have question, are those expiration times too strict? Should they be longer.

We are using IdentityServer with EF. I have problem finding refresh token from database to verify its lifetime. I have checked from PersitentGrants table with it and I cannot find it. I get refresh token from Duende.AccessTokenManagement's IUserTokenManagementService. If I try to check that refresh token with introspect endpoint, I get active: false for anwer. Can you give any pointer what I am doing wrong.

Does IdentityServer have any endpoint where one can check if server side session is still active?

Best Regads and thanks in advance
Mikko

**Comment by AndersAbel** [comment]
5 minutes access token lifetime works, although 10 minutes would work as well and not require as frequent refreshes.

I think that 5 minutes authentication cookie expiration in the client app is too tight. There's a risk that the user will be round-tripped to IdentityServer for login even after a brief period of inactivity.

Refresh token usage doesn't cause the server side session to slide by default. It must be enabled, either globally through `IdentityServerOptions.CoordinateTokensWithUserSession` or on the client through `CoordinateLifetimeWithUserSession`

The refresh tokens are stored in the PersistedGrants table. The introspection endpoint should return that the refresh token is active. If you try validating the refresh token immediately after the login, does it still return active=false?

**Comment by PBMikko** [comment]
Hello,

We have noticed that 5 minutes is too strict.  We have enabled sliding by setting CoordinateLifetimeWithUserSession.

This code returns refresh token active: false immediately after login. Also refresh token is not found from PersistentGrants table. 

```
            var tokens = await _userTokenManagementService.GetAccessTokenAsync(_httpContextAccessor.HttpContext.User);
            using (var client = _httpClientFactory.CreateClient())
            {
                var req = new TokenIntrospectionRequest()
                {
                    Address = "[redacted]/connect/introspect",
                    ClientId = "[redacted]",
                    ClientSecret = "[redacted]",
                    Token = tokens.RefreshToken
                };
                var response = await client.IntrospectTokenAsync(req);
            }

```            
Thanks in advance
Mikko

**Comment by AndersAbel** [comment]
Can you please share the code where you setup the persisted grants store (with any sensitive data such as connection strings redacted)?

**Comment by PBMikko** [comment]
Is this the code you are looking for?

```
        builder.Services
            .AddIdentityServer(options =>
            {
                options.LicenseKey = builder.Configuration["configkey"];
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;

                options.ServerSideSessions.UserDisplayNameClaimType = "email";
                options.ServerSideSessions.RemoveExpiredSessions = true;
                options.ServerSideSessions.RemoveExpiredSessionsFrequency = TimeSpan.FromMinutes(10);
                options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;

                // see https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
                options.EmitStaticAudienceClaim = true;
            })
        .AddServerSideSessions()
        .AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = (b) =>
            {
                b.UseSqlServer(
                    builder.Configuration.GetConnectionString("configkey"),
                    sql => sql.MigrationsAssembly(migrationsAssembly)
                    );
            };
        })
        .AddConfigurationStoreCache()
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = b =>
                b.UseSqlServer(
                        builder.Configuration.GetConnectionString("configkey"),
                        sql => sql.MigrationsAssembly(migrationsAssembly)
                        );
            
            options.EnableTokenCleanup = true;
            options.TokenCleanupInterval = 3600;
        })
        
        .AddAspNetIdentity<ApplicationUser>()
        .AddProfileService<XXXProfileService>();
        
```

**Comment by AndersAbel** [comment]
Yes, that is the code I was looking for. It looks correct to me. I just want to check one thing to be sure: If you have multiple nodes running IdentityServer, are they all using the same database?

I think that the next step in troubleshooting is to enable higher log levels. Can you run this in a development environment with debug level logging enabled? What I would like to see is if the refresh token is written to storage at all and if there's any information on how it is removed.

**Comment by PBMikko** [comment]
We have only one node (no cluster). 

I have it running on dev env with all log levels set to debug. I do not know what to search for and I an hesitent to post log directly here.

Regards,
Mikko

**Comment by PBMikko** [comment]
This is what I found from the log file (and PersistenGrants table). Log have complitely different refresh token that Duende.AccessTokenManagement.OpenIdConnect.IUserTokenManagementService is giving me on RP client app. 

Mikko

**Comment by AndersAbel** [comment]
Please note that the refresh token is not stored in plain text in the database. The actual refresh token is hashed and the hash is stored in the `key` column in the database.

It could also help if you analyze the logs from the call to the introspection endpoint. They should be more clear on why `false` is returned.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go close this issue?
