### ISSUE TITLE
Run Server-side session hosted service in separate demon instance

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#1007]
**Which version of Duende IdentityServer are you using?**
v6.3.3

**Which version of .NET are you using?**
.NET 7

**Describe the question**

Can we run `ServerSideSessionCleanupHost` in the separate demon/hosted/listener service?

We are using multiple instances(pods in kubernetes) of the Identity Server. Also, we are using an Server-side sessions so to we have enabled existing feature of Identity Server to clean up the expired sessions. But we are getting timeout and sometimes deadlocks also when multiple pods tries to executes clean up at same time. 

To avoid such issue we wanted to run separate instance of an IdentityServer in the demon/hosted service with one instance only. So, how we can achieve this behaviour?

**Comment by PratikPatel-Mtech** [comment]
@AndersAbel thanks. 

That could be one solution but it would be difficult/impossible to manage while auto scaling replicas. For example, let's say we kept initial replica counts to 3 and manage to set  `RemoveExpiredSessions` to `true` in only one replica. But now somehow that one pod get scale down then how we enable `RemoveExpiredSessions` other pod because we can do that only on startup.

The best solutions I could think of is that make the ServerSideSession service independent and allow it to register without any dependancy of `AddIdentityServer`.

**Comment by PratikPatel-Mtech** [comment]
@AndersAbel Thanks. Just to confirm we will have to do below configuration in new service, right?

```
services.AddIdentityServer(options =>
                {
                    options.IssuerUri = issuerUri;
                    options.ServerSideSessions.RemoveExpiredSessions = true;
                   // other options 
                })
```

No need to register `app.UseIdentityServer();` middleware, right?

Also, we purchased Identity Server licence. We can use same license for the new instance as well, right?

**Comment by josephdecock** [comment]
> No need to register app.UseIdentityServer(); middleware, right?

That's right. As long as the services are added to the DI container, the cleanup job will run fine, even without identityserver added to the pipeline.

> Also, we purchased Identity Server licence. We can use same license for the new instance as well, right?

Yes, that is fine to do.
