### ISSUE TITLE
Question relating Antiforgery header

### ISSUE THREAD

**Issue by ChienNQuang** [DuendeSoftware/Support#1011]
Hi! Thank you for the awesome library, thanks to it I grasped much of the security concepts and practices.

I want to ask about how exactly does the AntiForgery header works to mitigate cross-origin requests at all. 

Let's say I have https://www.example.com and https://evil.example.com, if an attacker were to compromise the evil subdomain then he could really well construct a CSRF form and put that antiforgery header in that form because the value is static.

If it's possible I'd like to be enlightened on this subject as I am new to application security at all. Thank you in advance!

**Comment by AndersAbel** [comment]
There are two possible ways for an a site to send a cross origin request.

1. Use XmlHttpRequest. This requires a CORS policy to be set up that allows the request. If there is no CORS policy allowing the request, the request will be blocked, so the CSRF header isn't even involved in the security model for this case.
2. Use a hidden iframe, image tag or something similar to make the browser make a cross origin request. This has the advantage that CORS is not required. But, there is no way to control the http headers. So even though or CSRF headers has a simple static value that is well known, there is no way the attacker can even set that simple header. So the request would be blocked.

**Comment by AndersAbel** [comment]
Do you have any further questions on this or can we close the issue?

**Comment by ChienNQuang** [comment]
Thanks for your answer! It really helped!
