### ISSUE TITLE
Update from identity server 4 to Duende Identity Server 6.3.6

### ISSUE THREAD

**Issue by thatdotnetguy** [DuendeSoftware/Support#1012]
**Which version of Duende IdentityServer are you using?**
6.3.6

**Which version of .NET are you using?**
6

I'm migrating from .net core 3.1 and identity server 4 (The project is one of the .net templates circa 2019)..... to .net 6 and duende identity server 6.3.6

Does Duende use the config set up for signing certificate in the appsettings.json? For example:

`"IdentityServer": {
        "Key": {
            "Type": "Store",
            "Name": "CN=myproduct.com.au",
            "StoreLocation": "CurrentUser",
            "StoreName": "My"
        }
 },`

**OR** 

We won't be using automatic key management, so am I meant to be calling both AddSigningCredential and AddValidationKey? (first one for signing tokens and second one for validating them) and the above config can be done away with?

I'd like to retrieve the key from Azure Key Vault. Does it need to be a "key" or "secret" (eg a X509 cert)? These are separate things in Azure Key Vault.

**Comment by AndersAbel** [comment]
The Asp.Net templates that included IdentityServer4 add an extra configuration layer on top of IdentityServer.

We have some background and recommendations in our docs on how to migrate from those templates to Duende.IdentityServer.  https://docs.duendesoftware.com/identityserver/v6/upgrades/spa_to_duende/

**Comment by thatdotnetguy** [comment]
Cheers for the link @AndersAbel... in regards to "The Asp.Net templates that included IdentityServer4 add an extra configuration layer on top of IdentityServer." this equates to even though I've moved / upgraded to Duende Identity Server 6 I don't need to call addsigningcredential myself as it's done under the covers assuming I keep the current architecture (identity server, api and react SPA app all under the one process)?

**Comment by AndersAbel** [comment]
We do recommend that you no longer use the configuration layer from the Asp.Net templates (the Microsoft.AspNetCore.ApiAuthorization.IdentityServer package).

Duende.IdentityServer now supports automatic key management (from the business tier license and up). Please see https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/migration/ for more information on considerations for migrating to use that.

**Comment by thatdotnetguy** [comment]
Thanks @AndersAbel does Microsoft.AspNetCore.ApiAuthorization.IdentityServer have a vulnerability? Currently our dbcontext inherits from ApiAuthorizationDbContext which is obviously in that package.

I'm not sure of the impact of removing that inheritance? Any idea?

Thanks so much for any thoughts, Andy

**Comment by AndersAbel** [comment]
No, there are no known vulnerabilities in the `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` package. The reason that we recommend migrating from it is that supplies a configuration model that has limitations and that the design is built around the assumption that everything runs on the same host.

The `ApiAuthorizationDbContext` derives from Asp.Net Identity's `IdentityDbContext` and then adds properties for the operational stores of IdentityServer. Please note that the operational stores have changed to Duende IdentityServer to now also includes the signing key store.

I think that the best option for you is to change your db context to inherit directly from `IdentityDbContext` (I assume that you are using ASp.Net Identity for user storage). Then use our EF implementation of the operational store to access the operational data.

**Comment by AndersAbel** [comment]
I guess the thumbs up and heart means everything is now fine, so I'm closing this issue. Please feel free to reopen if needed.
