### ISSUE TITLE
Callback Method not being called after  Azure  Entra Id Authentication 

### ISSUE THREAD

**Issue by itsutkarshgoyal** [DuendeSoftware/Support#1015]
**Which version of Duende IdentityServer are you using?**
Identity Server 6
**Which version of .NET are you using?**
.NET 6
**Describe the bug**
After the Authentication with Azure Entra
 I am have configured the azure entra id through openid connect , after the authentication , it gets stuck in redirect uri and callback method does not get called.

![p5](https://github.com/DuendeSoftware/Support/assets/52861039/33b4865f-4ecb-4b57-97b7-846f0c7b9b94)
![p4](https://github.com/DuendeSoftware/Support/assets/52861039/12f24b9e-0974-493b-b5b5-fe5f53a14ea5)
![p2](https://github.com/DuendeSoftware/Support/assets/52861039/c375eb4a-3f08-46b9-9061-a81a5110327c)
![p1](https://github.com/DuendeSoftware/Support/assets/52861039/822d2843-ca38-4106-83af-1d113cf8ebd5)

In logs i get 
Duende.IdentityServer.ResponseHandling.AuthorizeInteractionResponseGenerator: Information: Showing login: User is not authenticated

**Comment by AndersAbel** [comment]
Can you please share the redirect/request steps, including the http status code?

It should be something like this:
* https://idsrv.example.com/connect/authorize 302
* https://idsrv.example.com/Account/Login 200
* https://idsrv.example.com/Account/Challenge 302
* https://login.microsoftonline.com/..... (may be multiple pages, but resulting in a 302 or 200)
* https://idsrv.example.com/signin-oidc
* https://idsrv.example.com/Account/ExternalLoginCallback

**Comment by itsutkarshgoyal** [comment]
![p6](https://github.com/DuendeSoftware/Support/assets/52861039/9427fd1e-9a16-495e-aced-7c1f1145879c)

**Comment by AndersAbel** [comment]
`/signin-oidc` should return a 302 and not a 200. Looking at your configuration I see that you have used the same path for the `SignedOutCallbackPath`. I think that might be the reason. The handler checks if the `SignedOutCallbackPath` matches first and when it does, it never runs the code that reads the incoming response. You can leave the `SignedOutCallbackPath` with the default value which is `/signout-callback-oidc`.

In Entra Id you should also remove the config that allows implicit and hybrid flows. Your client already uses code flow which is the preferred flow.

**Comment by itsutkarshgoyal** [comment]
Thanks for the prompt resolution  , callback is hitting now.

**Comment by AndersAbel** [comment]
That's great news. Can consider this issue solved and go ahead and close it?

**Comment by itsutkarshgoyal** [comment]
had just a follow up question of this , my implemention of callback action method is as follow 
![return](https://github.com/DuendeSoftware/Support/assets/52861039/401b1d68-9db2-4d8d-aef9-7d5dfecd845d)

but after redirection , it is staying on identity server instead of actually redirecting to client url 
the return url is coming as 
"/connect/authorize/callback?client_id=fmprohub-web&redirect_uri=http%3A%2F%2Flocalhost%3A3006%2Fshell%2Fsample&scope=openid&response_type=code&state=HC1mRWBMXL0cq9BD&nonce=kTokQVueWWLc&code_challenge=pKK_tFBAwHbeRhHYoiJpkDBwPtF-uEviBboiwUcw9vc&code_challenge_method=S256"

**Comment by itsutkarshgoyal** [comment]
FYI
![fyi](https://github.com/DuendeSoftware/Support/assets/52861039/5bc528e8-2693-4fb9-981f-540c46ab5231)

**Comment by itsutkarshgoyal** [comment]
seems like location header in callback request is not proper 
![header](https://github.com/DuendeSoftware/Support/assets/52861039/3e8d08a6-bb1b-4f8f-bd51-80727cbe17f3)

**Comment by AndersAbel** [comment]
I cannot really follow what is happening without having the full URLs.

Can you please supply the full URLs and response status codes for each step above?
