### ISSUE TITLE
No way to set PersistedGrantDbContext Store Options

### ISSUE THREAD

**Issue by spyder007** [DuendeSoftware/Support#102]
**Which version of Duende IdentityServer are you using?**
6.1.1
**Which version of .NET are you using?**
6.0
**Describe the bug**

Recent changes to the DbContexts removed constructors which accepted the `StoreOptions` classes, and replaced them with a property to set.  While `ConfigurationDbContext.cs` was properly edited to allow for the `StoreOptions` property to be set, `PersistedGrantDbContext.cs` was not fully edited:  The `private` setter was corrected, but the `StoreOptions` property is listed as protected, not public.

If this is by design, how are we to configure the OperationStoreOptions for that db context?

See [this commit](https://github.com/DuendeSoftware/IdentityServer/commit/26b605fd3baf4254769350b1dcdf5cda0b5af4b8) for details.

**To Reproduce**

Create a `PersistedGrantDbContext` and attempt to set the `DefaultSchema` or any other property in the `OperationalStoreOptions` class.

**Expected behavior**

Able to configure `OperationalStoreOptions` for `PersistedGrantDbContext`

**Comment by brockallen** [comment]
Hmm, not sure why we did protected and not public. So that's all you need is for those to be public?

**Comment by spyder007** [comment]
That's my assumption, yes:  v 5.2.2 allowed for those store options to be passed in via the constructor, but since that is gone, we need to be able to set that external to the libraries.

**Comment by brockallen** [comment]
PR submitted -- will track there. Thanks.
