### ISSUE TITLE
Unable to unprotect the message.State with multiple external 

### ISSUE THREAD

**Issue by suolanik** [DuendeSoftware/Support#1020]
**Which version of Duende IdentityServer are you using?**
Identity Server 6

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
Hi,
I'm have configured the azure AAD through openid connect and after the authentication, its getting this error:
and I'm using multiple external AAD.

Inner Exception Type: System.Exception
Inner Exception: 
Unable to unprotect the message.State.
Inner Source: 
Exception Type: System.Exception
Exception: An error was encountered while handling the remote login.

![image](https://github.com/DuendeSoftware/Support/assets/10888932/9538ee26-3121-4f8f-8e9d-f95562cc54ec)

**Comment by josephdecock** [comment]
@suolanik, looking at this again, I see that you have multiple oidc providers configured and they're all using the same callback path. Different authentication schemes actually use different data protection keys, and the way to ensure that the providers each use the right scheme is to _set the CallbackPath distinctly_ for each one. Sorry I missed that at first!

**Comment by josephdecock** [comment]
One other note - you should set the sign out path and sign out callback path distinctly as well.

**Comment by suolanik** [comment]
Hi, @josephdecock 

I've added data protection and changed the callback, but I'm still getting the error in the prodction enviroment

**Config Duende**
![image](https://github.com/DuendeSoftware/Support/assets/10888932/72875d05-051e-44a6-99e7-16c45af02046)

**Config Entra ID**
![image](https://github.com/DuendeSoftware/Support/assets/10888932/599a20a5-8dd7-47d0-8ef8-40ec4710afde)

**Error**
![image](https://github.com/DuendeSoftware/Support/assets/10888932/13ac2623-277f-4925-a063-ff45c86a412d)

**Comment by suolanik** [comment]
Hi @josephdecock 

Do you have any update on this error?

**Comment by josephdecock** [comment]
Are you certain that each provider really has a unique callback path? Maybe you have multiple external providers that have the same item.SSOCDominio, resulting in a conflict. I would also verify that data protection is working and shared across all instances, separately from this. One way to easily see if that is happening is that the various instances would create distinct signing keys if data protection wasn't configured correctly (and if you have automatic signing keys enabled).

**Comment by suolanik** [comment]
Yes, I have a unique callback path! I have two distinct domain that are a unique column on SQL Server!
I disable automatic signing keys, using a static certificate from azure

[cid:382a33be-939a-4ed7-ac15-39116dc180c9]


obs:  I also commented the multiple external providers code and still got the error "Unable to unprotect the message.State. "

________________________________
De: Joe DeCock ***@***.***>
Enviado: quarta-feira, 6 de dezembro de 2023 16:25
Para: DuendeSoftware/Support ***@***.***>
Cc: suolanik ***@***.***>; Mention ***@***.***>
Assunto: Re: [DuendeSoftware/Support] Unable to unprotect the message.State with multiple external (Issue #1020)


Are you certain that each provider really has a unique callback path? Maybe you have multiple external providers that have the same item.SSOCDominio, resulting in a conflict. I would also verify that data protection is working and shared across all instances, separately from this. One way to easily see if that is happening is that the various instances would create distinct signing keys if data protection wasn't configured correctly (and if you have automatic signing keys enabled).

**Comment by josephdecock** [comment]
One thing that I'm noticing is that in your call to the state data formatter cache you aren't passing any scheme names. The caching is only done to the schemes that you pass in, so right now, that isn't being done at all. It's possible that you have a relatively large amount of state, and somewhere in the redirect chain, the state is being truncated. That would cause the state to then not unprotect successfully. Can you try again, passing the scheme names in?

**Comment by josephdecock** [comment]
> The caching is only done to the schemes that you pass in, so right now, that isn't being done at all

Actually, I looked again and this is incorrect -if you pass no schemes in at all, we default to caching everywhere. I guess I am so in the habit of preferring the explicit scheme names, I forgot about that default.

**Comment by josephdecock** [comment]
If you're able to reproduce the issue easily, a thing you could check would be if the state parameter on the authorize call is being echo'd back to you without any changes in the redirect to the callback path.

**Comment by suolanik** [comment]
Hi, @josephdecock 

This was the solution that solved the problem for me:
I have two applications: 
1st - The aplication that contain the Duende
2nd - The .net mvc

I put data protection in both applications:

Mvc
![image](https://github.com/DuendeSoftware/Support/assets/10888932/7bdd14cb-cbe3-4f99-b9c5-6e96949bb24a)

Duende
![image](https://github.com/DuendeSoftware/Support/assets/10888932/72517a7d-50ba-4012-828e-24b477694fc5)

External config
![image](https://github.com/DuendeSoftware/Support/assets/10888932/fd847a66-5668-4606-9773-823097e55282)

Thanks for helping
=)
