### ISSUE TITLE
Claims Request Parameter - Let the client ask only specific claims

### ISSUE THREAD

**Issue by jonathanantoine** [DuendeSoftware/Support#1026]
**Which version of Duende IdentityServer are you using?**
6.3
**Which version of .NET are you using?**
6
**Describe the bug**

I would like to use the "[claims" Request Parameter from Open Id Connect](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter) and it seems ignored by Identity Server.

I am building a federation gateway and I am trying to let the clients be able to filter out from tokens unecessary claims coming from external authentication providers by asking only the claims they (clients) need.

**To Reproduce**

I send this parameter to the authorize endpoint : 
`claims=%7B%22id_token%22%3A%7B%22email%22%3Anull%2C%22email_verified%22%3Anull%7D%2C%22access_token%22%3A%7B%22email%22%3Anull%2C%22email_verified%22%3Anull%2C%22some_custom_claim%22%3A%7B%22essential%22%3Atrue%7D%7D%2C%22userinfo%22%3A%7B%22email%22%3Anull%2C%22email_verified%22%3Anull%2C%22name%22%3Anull%7D%7D
`

**Expected behavior**
The 'some_custom_claim' is present in the final tokens.

**Comment by jonathanantoine** [comment]
Thanks for your answer.

First of all : I am in a Federation gateway context.

The usage of identity ressource requires that the Identity server knows ahead of time the claims that will be provided by external identity provider to map them to a scope name. This also implies that all the consumers of the Identity server will uses the same scopes names.

I am trying to invert the control and let clients apps blindly gets but still be able to filter out some of them from being added to the final tokens. This is what I was trying to achieve with the claim parameter.

Except using the profile service, is there a way to achieve this ?

Do you have guidance if I had to persist the information between calls ?

Thanks !

**Comment by AndersAbel** [comment]
@jonathanantoine Do you have any more questions on this or can we close the issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.

**Comment by jonathanantoine** [comment]
Thanks for this detailed answer and sorry for not being able to reply sooner. You can close the issue without a doubt even though this feature would be a nice addition.
