### ISSUE TITLE
Encyrpted Email

### ISSUE THREAD

**Issue by nextgenerationtr** [DuendeSoftware/Support#1036]
**Which version of Duende IdentityServer are you using?**
Duende Identity Server v6

**Which version of .NET are you using?**
.NetCore 6

**Describe the situation**
We store the email address encrypted via symmetric key algorithm (i.e. RijndaelSimple). The encrypted email has lower and upper case letters, numbers and special characters (i.e. =,+,/). If we try to store the encrypted email in AspNetUser table, the normalized email column may produce the same result. Hence, it may result in issues. How can we manage this situation in the best way?

**Expected behavior**
Be able to manage encrypted email without the complexities coming from normalized email. 

**Additional context**
Storing email in an encrypted format is important for us for security purposes.

**Comment by josephdecock** [comment]
This question is a little bit out of scope of IdentityServer, as it is really more to do with ASP.NET Identity. That said, we have actually run into related problems in the past where our grant hashes would sometimes collide depending on data store collation configuration. Our solution was to use a hex encoding of the bytes in the hash. Perhaps a similar technique would apply here - encrypt the email using whatever encryption algorithm you like, then take the raw encrypted bytes and encode them as a hex string, and store that.

**Comment by AndersAbel** [comment]
I guess the thumbs upp means this worked, so I'm closing the issue. Please feel free to reopen if needed.
