### ISSUE TITLE
Customize Login UI

### ISSUE THREAD

**Issue by MikeOtown** [DuendeSoftware/Support#104]
**Which version of Duende IdentityServer are you using?**
6.1.0
**Which version of .NET are you using?**
6

I'm attempting to customize the Login UI starting with a Duende Template Application.  My /Pages/Account/Login/Index.cshtml isn't getting rendered. Instead, this is rendered:

![image](https://user-images.githubusercontent.com/18534728/175994560-e318b172-405f-4b09-aaaf-27a0536d2f17.png)

How can I customize the Login UI?

**Comment by brockallen** [comment]
No idea -- that page is the exact file you mention.

**Comment by brockallen** [comment]
A lot: https://docs.duendesoftware.com/identityserver/v6/ui/

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
