### ISSUE TITLE
Asp.net nonce and correlation cookies not unset during silent login when user not already logged into the identity server

### ISSUE THREAD

**Issue by JeroMiya** [DuendeSoftware/Support#1044]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
6.0.25

**Describe the bug**
I'm not sure if this is a bug or a misconfiguration. I'm following the Duende.Bff documentation as far as I can tell. When I set an `iframe` to the `/bff/silent-login` endpoint, the response has two `Set-Cookie` headers for the Asp.Net nonce and correlation cookies. However, if the user is not logged in on the identity server side, it will redirect back from the identity server to the application's `/signin-oidc?error=login_required{**rest of url}` endpoint with the `error` query set to `login_required` indicating that the user is not already logged in. However, the built-in asp.net `/signin-oidc` endpoint doesn't UNSET the nonce and correlation cookies in this request. The browser is sending the nonce/correlation cookies that were set by `/bff/silent-login` previously to the `/signin-oidc` request on redirect, so the cookies aren't blocked - they're just not getting unset.

Because of this, every time the user visits the site, they get new nonce and correlation cookies, until the cookies get too big and the request errors out.

**To Reproduce**

Here's my BFF startup config. Note the main difference between my app and the samples are that my app lives in a subpath and not at the root. For instance, the frontend is at {domain}/app1 and the bff endpoints are at {domain}/app1/bff/**etc...:

```CSharp
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "cookie";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
})
.AddCookie("cookie", options =>
{
    // set session lifetime
    options.ExpireTimeSpan = TimeSpan.FromHours(8);

    // sliding or absolute
    options.SlidingExpiration = false;

    // the "__Secure" prefix is special
    // See: https://www.ietf.org/archive/id/draft-west-cookie-prefixes-05.txt
    // We are using __Secure instead of __Host because
    // the cookie will have a subpath (e.g. {subdomain.domain}/{app-subpath}) and not the root "/"
    options.Cookie.Name = "__Secure-bff";

    // strict SameSite handling
    options.Cookie.SameSite = SameSiteMode.Strict;
})
.AddOpenIdConnect("oidc", options =>
{
    if (isOptions is null)
    {
        throw new InvalidOperationException("Missing IdentityServer config section");
    }

    options.Authority = isOptions.Authority;

    // confidential client using code flow + PKCE
    options.RequireHttpsMetadata = true;
    options.ClientId = isOptions.ClientId;
    options.ClientSecret = isOptions.ClientSecret;
    options.ResponseType = OpenIdConnectResponseType.Code;

    // query response type is compatible with strict SameSite mode
    options.ResponseMode = OpenIdConnectResponseMode.Query;

    // get claims without mappings
    options.MapInboundClaims = false;
    options.GetClaimsFromUserInfoEndpoint = true;

    // save tokens into authentication session
    // to enable automatic token management
    options.SaveTokens = true;

    // request scopes
    options.Scope.Clear();
    options.Scope.Add("openid");
    options.Scope.Add("profile");

    // and refresh token
    options.Scope.Add("offline_access");
});
```

And here is the `silentLogin` function on the frontend:

```Ts
  private silentLogin(s: Session) {
    if (this.userIsAnonymous(s)) {
      console.log('not already logged in, attempting silent login...');
      const timeout = 5000;

      function redirectToLogin() {
        const returnUrl = window.location.pathname + window.location.search + window.location.hash;
        window.location.href = `/app1/bff/login?returnUrl=${returnUrl}`;
      }

      var http = this.http;
      function onMessage(e: any) {
        if (e.data && e.data.source === 'bff-silent-login') {
          window.removeEventListener("message", onMessage);
          if (e.data.isLoggedIn) {
            console.log('silent login succeeded, refreshing');
            window.location.reload();
          } else {
            console.log('silent login failed due to not being logged in, redirecting to identity server login page');
            redirectToLogin();
          }
        }
      }
      window.addEventListener("message", onMessage);

      window.setTimeout(() => {
        window.removeEventListener("message", onMessage);
        console.error('silent login timed out, redirecting to login');
        redirectToLogin();
      }, timeout);

      const iframe = document.createElement('iframe');
      iframe.src = '/app1/bff/silent-login';
      iframe.setAttribute('style', 'width:0px;height:0px');
      document.body.appendChild(iframe);
    }
    return s;
  }
```

Then, keep navigating to the app, and either login and logout or don't login, then navigate back to the app. You'll notice that the nonce and correlation cookies continue to build up.

**Expected behavior**

I'm expecting the nonce and correlation cookies to get unset even if the user is not already logged in, after an unsuccessful silent login as well as a successful one.

Am I missing some configuration? I've tried adjusting the samesite settings on the two cookies, it doesn't make a difference. The cookies don't appear to be blocked, Asp.Net's middleware just refuses to unset them when you're not logged in.

**Additional Context**

- The app lives in a subpath of a domain, instead of at the root `/` path. For example, the root of the app is `{domain}/app1` in this example.
- The identity server lives on the same domain as the app. When debugging locally, I can reproduce the issue where the identity server and the app both live on localhost, but different ports.

**Comment by JeroMiya** [comment]
Closing as this seems to be an issue on the aspnet side:
https://github.com/dotnet/aspnetcore/issues/53048

**Comment by josephdecock** [comment]
Thanks for the update @JeroMiya. I did briefly look at this earlier, and my initial reaction was that this should be fixed in the handler too. It's good that the team is working on it.
