### ISSUE TITLE
redirect_uri starts with "http:" instead of "https:"

### ISSUE THREAD

**Issue by greg-signi** [DuendeSoftware/Support#1046]
Which version of Duende BFF are you using?
2.1.1
Which version of .NET are you using?
6.0

The redirect uri is correct but instead of being appended with "https://" is getting appended with "http://"

`/login ` => `https://my-domain/bff/login?returnUrl=https://localhost:8080`

redirects to.. `https://my-identity-server/open/connect/authorize?client_id=xxxxx&redirect_uri=http%3A%2F%2Fmy-domain%2Fbff%2Fsignin-oidc`

So then my identity server doesn't validate my redirect uri since it starts with "**http://**".. I've tried looking at the logs and following the code inside the Bff but wasn't successfull, any idea what can be misconfigured ?

EDIT: One thing to bear in mind, is that I'm accessing the BFF trough a proxy. K8s and Istio

Just to try it out, I added the "http://..." has a possible redirect, and further down the line I after the login I get an error

```
[40m←[1m←[33mwarn←[39m←[22m←[49m: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.Rg5uK2cvFxpgXhuZ7D2FE449qERGxHVxAyUd1ya6EFg' cookie not found.
←[40m←[32minfo←[39m←[22m←[49m: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[4]
      Error from RemoteAuthentication: Correlation failed..
←[41m←[30mfail←[39m←[22m←[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN08ERD9SRNM", Request id "0HN08ERD9SRNM:00000003": An unhandled exception was thrown by the application.
      System.Exception: An error was encountered while handling the remote login.
       ---> System.Exception: Correlation failed.
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by greg-signi** [comment]
Closing since I found the answer to my issue here https://github.com/DuendeSoftware/Support/issues/787
It was the exact same problems 👍

**Comment by josephdecock** [comment]
Thanks for the update @greg-signi  and for linking to the solution!
