### ISSUE TITLE
Duende.AccessTokenManagement and IDistributedCache

### ISSUE THREAD

**Issue by dominikjeske** [DuendeSoftware/Support#1047]
I have a question about Duende.AccessTokenManagement (all versions). It use IDistributedCache and this is a problem when application is trying to use redis implementation. I would like to use in memory for tokens and redis for other stuff. My current workaround is to register types from Duende.AccessTokenManagement manually 

`
services.TryAddTransient(sp =>   new DistributedClientCredentialsTokenCache(sp.GetRequiredService<MemoryDistributedCache>(), sp.GetRequiredService<IOptions<ClientCredentialsTokenManagementOptions>>(), sp.GetRequiredService<ILogger<DistributedClientCredentialsTokenCache>>()));
`
maybe there is a better way or you could implement it in some other way to prevent problem like this?

**Comment by josephdecock** [comment]
I think long term, we could consider solve this using the new keyed dependencies added in .net 8, but that isn't available on the older versions we still support. For now, your work-around is the best thing to do.

**Comment by dominikjeske** [comment]
Keyed dependencies is exactly what I was thinking of. Thanks for info.
