### ISSUE TITLE
How to customize the log in view?

### ISSUE THREAD

**Issue by obrungot** [DuendeSoftware/Support#1049]
**Which version of Duende IdentityServer are you using?** 6.2.3.

**Which version of .NET are you using?** 7.0

**Describe the bug**
I can't find the .cshtml file for customization the UI for the Duende Log In view.
I've even searched through the entire source for "Use a local account to log in" in order to find it, but it doesn't show up.
For starters I would like to change the language used, but I can't seem to find the actual page to edit.

It's the .../Identity/Account/Login view that I can't seem to find. The index.cshtml under Account/Login is not the same view, and I can't find any LogIn view under Identity/Pages/Account.

**Comment by josephdecock** [comment]
@obrungot do you need anything on this issue? It looks like you opened and then closed it right away.

**Comment by obrungot** [comment]
No, it is resolved.
I found out that the view had to be scaffolded from ASP.Net Identity.

Thanks!

________________________________
Fra: Joe DeCock ***@***.***>
Sendt: mandag 1. januar 2024 23:48
Til: DuendeSoftware/Support ***@***.***>
Kopi: obrungot ***@***.***>; Mention ***@***.***>
Emne: Re: [DuendeSoftware/Support] How to customize the log in view? (Issue #1049)


@obrungot<https://github.com/obrungot> do you need anything on this issue? It looks like you opened and then closed it right away.
