### ISSUE TITLE
Custom IProfileService.IsActiveAsync() and redirect loop

### ISSUE THREAD

**Issue by sevenam** [DuendeSoftware/Support#105]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0

**Describe the bug**
We experience a redirect/login loop when we set the `context.IsActive` flag to false.

We have implemented our custom `IProfileService` and in the `IsActiveAsync()` method we do some custom logic to verify if the user is active or not. When the user is not active,  we set the context.IsActive to false. According to the documentation, this is the way to define that no tokens should be returned: `The flag indicating if the user is allowed to obtain tokens`.
When we set this flag to `false` no tokens are issued (which is great!), but the user experience isn't very good as it goes into a redirect loop and keeps prompting the login for the user.

We currently got around this by also implementing a custom `AuthorizeInteractionResponseGenerator` which made us go a little deeper into this than we really wanted...

In the `AuthorizeInteractionResponseGenerator.ProcessLoginAsync()` method we set the `InteractionResponse` to also contain an Error when the `isActiveCtx.IsActive` is false.

```
        else if (!isActive)
        {
          Logger.LogInformation("Showing error: User does not have access");
          return new InteractionResponse { IsLogin = true, Error = "Sorry, but you do not have access!" };

```

**To Reproduce**
Set IsActive flag to false.

**Expected behavior**
We expected an error to be returned when the `isActiveCtx.IsActive` is set to false.

**Comment by brockallen** [comment]
Can you provide a summary of the HTTP requests (like a fiddler trace or browser network trace) being made starting in the client and thru to IdentityServer and back to the client (if applicable), and indicate in there where the loop begins?

**Comment by sevenam** [comment]
Captured and shared a Fiddler session with you on this.

**Comment by brockallen** [comment]
Sorry, I don't think I have seen this anywhere. Are you still having issues?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
