### ISSUE TITLE
What is/are recommended plugin(s) to use Identity Server as a Service Provider (SAML2)

### ISSUE THREAD

**Issue by kkdeveloper7** [DuendeSoftware/Support#1051]
**Which version of .NET are you using?**
Dotnet6 and Dotnet8

We have a request to integrate of sign in of our existing users with external IdP. We already have Identity server running and works great with authenticating/authorizing our users. 

However, it looks like Identity Server does not support SAML2.0 Protocol. I was wondering if Identity Server team have recommended plugins for this protocol or if anyone used and can recommend plugin that provide flexible extensions and development process for SAML2.0

**Comment by josephdecock** [comment]
You're correct that IdentityServer itself doesn't implement SAML, but there are two good 3rd party options.

1. Our partner RockSolidKnowledge (RSK) sells a proprietary add on to IdentityServer that allows your IdentityServer implementation to act as both a SAML Identity Provider (which allows your client applications to sign in at IdentityServer using SAML instead of OAuth or OIDC) or a SAML Service Provider (which allows your IdentityServer to federate with an external identity provider that only supports SAML). Pricing and documentation and support are all available from RSK [here](https://www.identityserver.com/products/saml2p).

2. The SustainSys.Saml2 open source project is available for free or with a paid support contract. It allows your IdentityServer to act as a SAML SP, but not as a SAML IDP. There are good resources online for Sustainsys, including [documentation ](https://saml2.sustainsys.com/en/v2/)and the github [repo](https://github.com/Sustainsys/Saml2).

**Comment by kkdeveloper7** [comment]
> You're correct that IdentityServer itself doesn't implement SAML, but there are two good 3rd party options.
> 
> 1. Our partner RockSolidKnowledge (RSK) sells a proprietary add on to IdentityServer that allows your IdentityServer implementation to act as both a SAML Identity Provider (which allows your client applications to sign in at IdentityServer using SAML instead of OAuth or OIDC) or a SAML Service Provider (which allows your IdentityServer to federate with an external identity provider that only supports SAML). Pricing and documentation and support are all available from RSK [here](https://www.identityserver.com/products/saml2p).
> 2. The SustainSys.Saml2 open source project is available for free or with a paid support contract. It allows your IdentityServer to act as a SAML SP, but not as a SAML IDP. There are good resources online for Sustainsys, including [documentation ](https://saml2.sustainsys.com/en/v2/)and the github [repo](https://github.com/Sustainsys/Saml2).

Thank you. 
We are looking to be a Service Provider and authenticate against 3rd party, do you think `SustainSys.Saml2` will be enough for us to make assertions?

**Comment by josephdecock** [comment]
Yes, the Sustainsys package supports that scenario. There is a sample maintained by the sustainsys community showing how to use it with identity server here: https://github.com/Sustainsys/KatanaCodeFlow. Even though that sample is using identity server 4, the mechanics haven't changed substantially.

**Comment by kkdeveloper7** [comment]
> Yes, the Sustainsys package supports that scenario. There is a sample maintained by the sustainsys community showing how to use it with identity server here: https://github.com/Sustainsys/KatanaCodeFlow. Even though that sample is using identity server 4, the mechanics haven't changed substantially.

Thank you will definitely go over this implementation. Who would you recommend going forward with if money is not an issue with an integration etc? 
We mostly care to make sure third party packages stay active and they are not been abundant.

**Comment by josephdecock** [comment]
The maintainer of sustainsys is @AndersAbel, who also is on the Duende engineering team. He offers commercial support for sustainsys.

**Comment by AndersAbel** [comment]
@kkdeveloper7 I have no intention to retire the Sustainsys.Saml2 packages. The commercial support model of the Sustainsys packages is a way to ensure that there is funding for development/maintenance and that the library stays around.

Two more samples that might be relevant for the IdentityServer case is https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/AspNetCore for static configuration and https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/DuendeDynamicProviders for usage with the dynamic providers feature.

**Comment by kkdeveloper7** [comment]
> @kkdeveloper7 I have no intention to retire the Sustainsys.Saml2 packages. The commercial support model of the Sustainsys packages is a way to ensure that there is funding for development/maintenance and that the library stays around.
> 
> Two more samples that might be relevant for the IdentityServer case is https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/AspNetCore for static configuration and https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/DuendeDynamicProviders for usage with the dynamic providers feature.

Thank you!
We would want to reach out and set something up probably for someone to come in and check out implementation for SAML as well as Identity Server set up.  How do we reach out for support etc..?

**Comment by josephdecock** [comment]
You can reach Anders for questions about sustain sys commerical support by emailing support@sustainsys.com.

Is there anything else you need, or should we close this issue?

**Comment by kkdeveloper7** [comment]
> anything else you need, or should we close this issue?

Yes, is it possible someone point me to documentation, and not only examples? Their website has configuration for ASP .NET and not for dotnet core.

**Comment by josephdecock** [comment]
I don't think there other resources beyond what has been mentioned already in this thread. The sustainsys docs do point out that instead of using web.config, you should use the Saml2Options class directly in ASP.NET Core, and the samples do show how to do that.

**Comment by AndersAbel** [comment]
@kkdeveloper7 You are right that the Sustainsys.Saml2 docs do not cover how to use the Asp.Net Core version of the library. I'll try to add a section on that. I've opened https://github.com/Sustainsys/Saml2/issues/1440 to track that.
