### ISSUE TITLE
Application not working when deploying with Azure portal

### ISSUE THREAD

**Issue by vkholiya** [DuendeSoftware/Support#1052]
Deunde Identity Server version - 7.0.11

.NET Version - 7

Bug Desciption - After the application is deployed using Azure web app service the complete app is not loading up

We have an application that's using deunde identity server as authentication feature, which is working great while development. But while we are publishing the app to the azure portal so that product team can also test the app then our whole app is not working at all. 

We need your assistance in this regards because there are no errors/issues we are able to see while the deployment process is going or and neither in the application logs in azure portal. 

So right now our most possible issue is due to deunde identity server only.

**Comment by StuFrankish** [comment]
"_Not loading up_" isn't very useful I'm afraid.

There are many "log" type functions and features in the Azure Portal, have you enabled [Log Stream](https://learn.microsoft.com/en-us/azure/container-apps/log-streaming?tabs=bash#view-log-streams-via-the-azure-portal) for the app service and attempted a restart? If so, what is shown?

**Comment by vkholiya** [comment]
No logs are being shown, our application default route is set to login page that deunde identity provides, this is entry point of our application which itself is not loading up. One thing we noticed while application is trying to run up is this warning, 

`_You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us: https://duendesoftware.com/contact_`

**Comment by josephdecock** [comment]
Are you building your application and identity provider as a single host? This has a number of limitations, and our recommended architecture is to deploy identity server in an external host from your applications. We describe this in more detail in our docs [here](https://docs.duendesoftware.com/identityserver/v6/upgrades/spa_to_duende/). 

The licensing warning isn't preventing your system from working. Licenses are required in production use, but not in development and test environments. For this reason, the license system does not disrupt your identity server even if the license is missing. Please see 
https://duendesoftware.com/products/identityserver for licensing details.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by vkholiya** [comment]
We can close the ticket, the issue was not related to licensing.

**Comment by StuFrankish** [comment]
Are you able to explain what it was in relation to so anyone having a similar problem in the future can be helped?

**Comment by vkholiya** [comment]
The issue was with my network configuration setup when I was trying to deploy the app with IIS, I referred to below 3 links for resolving my issue:
https://stackoverflow.com/questions/12106011/system-security-cryptography-cryptographicexception-keyset-does-not-exist (follow the link and generate the certificate) 

https://stackoverflow.com/questions/12106011/system-security-cryptography-cryptographicexception-keyset-does-not-exist 

https://stackoverflow.com/a/21148852/10182352
