### ISSUE TITLE
Using MYSQL database instead of SQLITE

### ISSUE THREAD

**Issue by davidsi02** [DuendeSoftware/Support#1053]
**Which version of Duende IdentityServer are you using?**
6.3.7

**Which version of .NET are you using?**
8.0

**Describe the question**
Is it possible to change the database from SQLite to MySQL? How to do so?

**Additional context**
Tried to do so by using the packages: 
```
<PackageReference Include="MySql.Data.EntityFramework" Version="8.2.0" />
<PackageReference Include="MySql.EntityFrameworkCore" Version="7.0.10" />
```

And changing the `options.UseSQLite("filepath")` to `options.UseMySQL("sqlstring")` ang I get the following error:

> System.MissingMethodException: Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.

**Comment by josephdecock** [comment]
Missing method exceptions suggest to me that there may be some version incompatibles between nuget packages. Try to make sure that everything related to entity framework (maybe there is a designer package) is using the same version.

**Comment by davidsi02** [comment]
@josephdecock 

I'm using all the most recent versions of each package.
I would appreciate if you can take a look and tell me exactly wich versions should I use. 

Thanks.

```
	<PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="6.3.6" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="MySql.Data" Version="8.2.0" />
	<PackageReference Include="MySql.EntityFrameworkCore" Version="7.0.10" />
	<PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
```

**Comment by davidsi02** [comment]
Fixed it. I just needed to downgrade all EF packages to latest MySQL EFCore version :)
