### ISSUE TITLE
Error validating Duende IdentityServer license key

### ISSUE THREAD

**Issue by michelebombardi** [DuendeSoftware/Support#1056]
**Which version of Duende IdentityServer are you using?**
5.2.0

**Which version of .NET are you using?**
6.0

**Describe the bug**
A license validation error is thrown.

**Log output/exception with stacktrace**

```
2024-01-04 17:39 [Aequilibrium] [wn-demo-2] [Fatal] Error validating Duende IdentityServer license key System.ArgumentException: IDX14111: JWT: 'System.String' must have three segments (JWS) or five segments (JWE). {"SourceContext":"Duende.IdentityServer","EnvironmentUserName":"wn-demo-2\\root","ExceptionDetail":{"Type":"System.ArgumentException","HResult":-2147024809,"Message":"IDX14111: JWT: 'System.String' must have three segments (JWS) or five segments (JWE).","Source":null,"ParamName":null},"Application":"Willness Aequilibrium"}
```

**Comment by StuFrankish** [comment]
Where from & how are you loading the license key?
Looking at our own licence, the key file we were provided contains a well-formed JWT string that I can inspect using https://jwt.io/

If you have access to the string, does https://jwt.io/ parse it correctly?

**Comment by michelebombardi** [comment]
Hi @StuFrankish ,
the license key is inside a project folder.
Specifically in my `Startup.cs` I have:

    builder.Services.AddIdentityServer(options =>
    {
        options.LicenseKey = $"Identity/License/{builder.Environment.EnvironmentName.ToLowerInvariant()}/Duende_License.key";

        ...
    })`

And the license is stored at: 

`[project_folder]\Identity\License\[env_to_lower]\Duende_License.key`

I've access to the file and I tried to inspect it with https://jwt.io, it seems to be well-formed:

![image](https://github.com/DuendeSoftware/Support/assets/19502861/4a980f12-cbd6-473e-a615-d9d7002f0508)

**Comment by brockallen** [comment]
The `LicenseKey` property is the actual value contained in the file itself, not the path to the file. If you want the file in some other location other than what we document [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key/#file-system), then you can load it yourself and then set the contents into the `LicenseKey` property. Hope this makes sense.

**Comment by michelebombardi** [comment]
Hi @brockallen ,
Thank you for made that clear.
