### ISSUE TITLE
Question regarding Cookie Expiration in Legacy MVC and WebAPI based App.

### ISSUE THREAD

**Issue by nigelbasel** [DuendeSoftware/Support#1058]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
.NET Framework 4.7.2 Client, .NET 7 Identity Server

**Question**

We have a Legacy .NET Framework ASP.NET MVC/Win Forms Application which we have ported to use Identity Server. The Application Makes AJAX calls to WebAPI Controllers on some of its pages. Once the User Cookie expires, normal pages redirect to the authorization endpoint on Identity Server and the cookie is refreshed. If the cookie expires and a page makes a call to one of the WebAPI controllers, the runtime attempts to redirect to the authorize endpoint, which fails. We understand that this is not the correct model, and that we should be returning a 401 from the api call in this case, but what is not clear is exactly what the front end should then do in response to that 401. We have also considered changing all the api calls to user bearer token authentication, which does work, but are unsure of best practice in regard to refreshing and storing this token.

Some guidance would be appreciated.

**Comment by josephdecock** [comment]
Our recommendation is for the front end to not ever handle tokens directly, and only use the cookie as you are doing now.

When the access token stored in the session expires, the typical way to get a new token is to use a refresh token to make a new token request. The resulting new token should be added to the session and a new session cookie issued.

Our sample implementation [here](https://docs.duendesoftware.com/identityserver/v6/samples/clients/#net-48-clients) shows how this is done in .NET framework.

**Comment by nigelbasel** [comment]
Hi Joseph, thanks for the reply. I have been using that exact sample to try and resolve this issue. The problem we have is when the cookie itself expires, which is why we were considering storing the bearer token on the client. Consider the scenario a user leaves the browser alone for longer than 20 minutes (the default timeout for the asp.net session cookie). If they then return to the browser and carry out an action that results in an ajax call, the middleware will then attempt to redirect the XHR call to the authorize endpoint. The guidance I have previously seen suggests overriding the RedirectToIdentityProvider event to respond with a 401 instead of the 302 to redirect to authorize, which I am able to do. The problem now is what to do on the client to cause a new cookie to be issued so that we can retry the api?

Once again, thanks for the response.

**Comment by nigelbasel** [comment]
Hi Again Joseph, thanks for the response. That makes perfect sense, we will follow your guidance.
