### ISSUE TITLE
Unable to redirect to custom error page when `ICustomAuthorizeRequestValidator.ValidateAsync()` implementation results in error state

### ISSUE THREAD

**Issue by i-jshaw** [DuendeSoftware/Support#1068]
**Which version of Duende IdentityServer are you using?**

6.2.0

**Which version of .NET are you using?**

.NET 6

**Describe the bug**

There doesn't seem to be a way to set a custom error page when `ICustomAuthorizeRequestValidator.ValidateAsync(...)` results in an error state.

Steps to reproduce the behavior.

```csharp
public class CustomAuthorizeRequestValidator : ICustomAuthorizeRequestValidator
{
    public async Task ValidateAsync(CustomAuthorizeRequestValidationContext context)
    {
        context.Result.IsError = true;
        context.Result.Error = "Some error message";
    }
}

// And to wire it up:
// IIdentityServerBuilder.AddCustomAuthorizeRequestValidator<CustomAuthorizeRequestValidator>();
```

**Expected behavior**

Either:
* I can create a custom error page that's used in place of the existing one to generate a more friendly end-user experience
* I can extend/override something, like `AuthorizeResponseGenerator`, that allows for me to evaluate the error and redirect if desired

**Log output/exception with stacktrace**

None

**Additional context**

None

**Comment by AndersAbel** [comment]
No, there is not any built in support for redirecting to a specific error page. The intention is that you would customize the error page from our quick start to suite your needs `IIdentityServerInteractionService.GetErrorContextAsync` returns details about the error. Based on that, you can display a custom page, perform a redirect or any other suitable action.

**Comment by i-jshaw** [comment]
Sounds good. Didn't realize we were using a sample error page. Thanks for pointing me in the correct direction!
