### ISSUE TITLE
Question regarding load balancer

### ISSUE THREAD

**Issue by gjckis** [DuendeSoftware/Support#1069]
I have upgraded my token server to .Net 6 +  Duende 6.3.8 and basic test of password flow is working. 

I would like to make sure that the server is ready to work behind a load balancer.
Below is a part of the Startup code related to the identityserver and I can see data appearing in the DataProtectionKeys table.

**Is there anything else needed in Startup to ensure that identityserver is ready for load balancer?**

            // connectionString comes from config like Data Source=ci-d-sql-1;Initial Catalog=DuendeSoftware;User ID=sts;Password=…;MultipleActiveResultSets=true;App=WebAPI.STS;Encrypt=false;
            // certificate is of type X509Certificate2 and loaded from local store
            services.AddDbContext<DataProtectionKeyContext>(options => 
            {
                options.UseSqlServer(connectionString);
            });

            services.AddDataProtection()
                .SetApplicationName("STS")
                .ProtectKeysWithCertificate(certificate)
                .PersistKeysToDbContext<DataProtectionKeyContext>();                
            
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
                                                            
            services.AddIdentityServer(options =>
                {
                    //options.LicenseKey = "your_license_key";
                    options.KeyManagement.Enabled = true; // default is true
                })
                .AddServerSideSessions()
                .AddSigningCredential(certificate)
                .AddProfileService<ProfileService>()

                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 3600;
                                
                }
            );

**Comment by AndersAbel** [comment]
This looks right. A simple way to validate the setup is to get the discovery document. If it shows the correct URLs, then the forwarded headers are setup correctly. Also open the JWKs link. If the contents are displayed correctly (and are the same) when different hosts process the requests that validates that key storage and data protection is setup correctly.

**Comment by josephdecock** [comment]
Just to supplement this, we have additional documentation on deployment considerations [here](https://docs.duendesoftware.com/identityserver/v7/deployment/). Do have any other questions?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
