### ISSUE TITLE
Question about how redirect_uri is built when calling connect_authorize

### ISSUE THREAD

**Issue by SPDragNDrop** [DuendeSoftware/Support#1070]
**Which version of Duende IdentityServer are you using?**
6.3.3
**Which version of .NET are you using?**
6.0.13
**Describe the bug**
Less of a bug an more of a question.  The redirect_uri in that is in the connect/authorize?client_id=xxxxx&amp;redirect_uri ... where/how is the redirect_uri built?  Is it a combination of the hostheader (X-FORWARDED-HOST) + path to the client's signin-oidc?  I 

**To Reproduce**

N/A

**Expected behavior**

Just trying to understand how the redirect_uri is built.  I would have thought it would have come from the full path in our client list.

**Log output/exception with stacktrace**

N/A

```
data
```

**Additional context**

We are coming back inside via a proxy server thus the (X-FORWARDED-HOST)

**Comment by AndersAbel** [comment]
The redirect URI is built by the client application and included in the requests/redirect to the OpenID Provider (IdentitySever).

Can you provide a bit more details on the redirect URI generated. What is wrong with it?

**Comment by SPDragNDrop** [comment]
Thank you for your response.  I ended up getting this to work and I didn't mean to imply anything was wrong with the redirectUri's I was just trying to understand how they were built.  It seemed like they were built using the host header plus a relative path for "connect/token" perhaps I was just confused.  Late nights.  Thank you again for your reply.
