### ISSUE TITLE
Custom session data

### ISSUE THREAD

**Issue by PBMikko** [DuendeSoftware/Support#1074]
**Which version of Duende IdentityServer are you using?**
6.3.6 

(We will move to v7 when it is RTM)

**Which version of .NET are you using?**
.NET 6

This is not a bug, this is question.

Is it possible to add custom data to server side session (eg. login ip) that could be accessed from ISessionManagementService.QuerySessionsAsync?

I ask this because it is possible to add data to user profile (https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/). We are using IdentityServers EF core for operational data.

Thanks in advance
Mikko

**Comment by AndersAbel** [comment]
The `UserSession` returned form `QuerySessionsAsync` contains the `AuthenticationTicket`. In the `AuthenticationTicket` the `AuthenticationProperties` are available. You can pass in any data to the `AuthenticationProperties` at sign on time..

If your question is rather about possibilities to search/filter on custom data the answer is more complicated.

**Comment by PBMikko** [comment]
Thanks for reply. 
Using AuthenticationProperties would be sufficient to our  needs. We do not need to search by our extra data.

I have yet to figure out, how to access AuthenticationProperties during login flow. We are using ASP.NET Identity integration with possible two factor authenctication. I know there is method on SignInManger.SignInAsync that accepts AuthenticationProperties. On other hand this method does not validate credentials. I could verify user id and password with SignInManger.CheckPasswordSignInAsync and then based on result do SignInAsync with my properties. But if sign in requires two factor authentication with authenticator app, there is no similar method to verify given authenticator code. There is only TwoFactorSignIn method and that does not accept AuthenticationProperties.
