### ISSUE TITLE
Additional Claims

### ISSUE THREAD

**Issue by chrisjasp** [DuendeSoftware/Support#108]
**Which version of Duende BFF are you using?**
1.0.0

**Which version of .NET are you using?**
3.1

Creating a new BFF application using the above version. We also have IdentityServer version 5.2.3 for our Authority. I would like to provide a few additional claims that are unique to our environment on SignIn. Currently, the Login page is in the token server application (IdentityServer) and I am assigning the additional claims to IdentityServerUser and calling SignInAsync with that principal. 
In the BFF I'm expecting to see those claims over on the principal in the CookieAuth OnSigningIn event and they are never there. I'm sure there is a disconnect I'm not understanding there but they are not there. I've also tried to use the AuthenticationProperties for the SignInAsync to propagate that value over to the BFF with no luck. 
How would you suggest getting a claim from the signin in the token over to the principal in the BFF?

**Comment by brockallen** [comment]
> In the BFF I'm expecting to see those claims over on the principal in the CookieAuth OnSigningIn event and they are never there. 

Have you configured the `UserClaims` in the `IdentityScopes` the BFF client is requesting?

https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/identity/
https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

**Comment by chrisjasp** [comment]
I did this previously but I went back through again to see if I missed anything. I do see the claim getting added at the token server, however, the claims are still failing to show up in the BFF side.

**Comment by leastprivilege** [comment]
They might be filtered by the ASP.NET OIDC handler

try

`options.ClaimActions.Clear();`

in the OIDC options.

**Comment by chrisjasp** [comment]
I added the above in the BFF oidc options and it did not change anything. Is there similar client configuration that I need to add on the Identity Server side?

**Comment by leastprivilege** [comment]
No. Then I guess I do not understand the problem.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
