### ISSUE TITLE
Migration Script to version 7.0.0

### ISSUE THREAD

**Issue by MCFHTAGENTS** [DuendeSoftware/Support#1083]
Hi
Just to note that with the update to IdentityServer 7.0.0 the data model change change of data type on ServerSideSessions results a migration script that doesn't work as you need to add steps to drop and recreate the primary key.
I added the two commands front and back of the AlterColumn statement that the EF tools created.

Kind regards
Mark

````
            migrationBuilder.DropPrimaryKey("PK_ServerSideSessions", "ServerSideSessions");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "ServerSideSessions",
                type: "bigint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("SqlServer:Identity", "1, 1")
                .OldAnnotation("SqlServer:Identity", "1, 1");

            migrationBuilder.AddPrimaryKey("PK_ServerSideSessions", "ServerSideSessions", "Id");
````

**Comment by AndersAbel** [comment]
Yes, that's unfortunately something that needs to be added. We've listed it in our [upgrade guide](https://docs.duendesoftware.com/identityserver/v7/upgrades/v6.3_to_v7.0/#duendeidentityserverentityframework) but maybe we should add the information to more places? Is there any other specific place where you looked and expected to find information about it?

**Comment by MCFHTAGENTS** [comment]
Thanks - am sure I read that and maybe missed it. That’s the right place!
Thanks
Mark

Sent from my iPhone

On 28 Jan 2024, at 12:57, Anders Abel ***@***.***> wrote:

﻿

Yes, that's unfortunately something that needs to be added. We've listed it in our upgrade guide<https://docs.duendesoftware.com/identityserver/v7/upgrades/v6.3_to_v7.0/#duendeidentityserverentityframework> but maybe we should add the information to more places? Is there any other specific place where you looked and expected to find information about it?
