### ISSUE TITLE
Create Account Integration option

### ISSUE THREAD

**Issue by vdevc** [DuendeSoftware/Support#1084]
**Which version of Duende IdentityServer are you using?**

7.0

**Which version of .NET are you using?**

8.0

I am trying to integrate account creation in IS. The objective is to support user registration initiated at the OIDC.
I have read in depth issues [#1029](https://github.com/DuendeSoftware/IdentityServer/issues/1029), [#432](https://github.com/DuendeSoftware/IdentityServer/issues/432) as well as pull request [#1153](https://github.com/DuendeSoftware/IdentityServer/pull/1153) and the [post mentioned](https://www.strathweb.com/2022/09/initiating-user-registration-via-openid-connect-with-duende-identity-server/).

Everything is clear how it worls and about current design choices for the solution.

The only question I have is related to how the feature can be activated from a client perspective.
I have an existing sample client which already use `OnRedirectToIdentityProvider` to send a tenant identifier via `acr_values` to IdentityServer.

Based on my understanding to activate the flow it sufficient to 

```csharp
options.Events.OnRedirectToIdentityProvider = ctx => {
    ctx.ProtocolMessage.Prompt = "create";
    return Task.CompletedTask;
};
```

Q1: Is it safe to add the `prompt=create` for every request? 

**Additional context**

My final aim is to customize the login/register flow in order to be like this

<img width="1210" alt="image" src="https://github.com/DuendeSoftware/Support/assets/143489513/301d39b4-5078-44bc-b96c-e10822ba826b">

`Show list of Accounts Page` correspond to to the `prompt=select_account`
`Create Account Page` correspond to to the `prompt=create`

How can i combine these flows together? Any guidance or existing reference?

**Comment by AndersAbel** [comment]
> Q1: Is it safe to add the prompt=create for every request?

If you add it to every request from the client, it means that the user should always register a new account and never log in to an existing account. Is that really what you want?

Baed on your picture, I would do the redirect to IdentityServer much earlier and let the user input the e-mail on an IdentityServer form. I think that would make the flow easier to implement. If you want to ask for the e-mail on the client, I think it is better to use the `login_hint` parameter for the e-mail. Then IdentityServer can lookup the e-mail and show the create or login pages depending on if the user exists or not.

While a solution like this is convenient for the users, it might be abused by an attacker to check if accounts exists. Some kind of rate limiting might be needed.

**Comment by vdevc** [comment]
> If you add it to every request from the client, it means that the user should always register a new account and never log in to an existing account. Is that really what you want?

Nevermind. I wanted to express a different question but, reading it now, it's really more a comic than a question. Sorry.
 
> Baed on your picture, I would do the redirect to IdentityServer much earlier and let the user input the e-mail on an IdentityServer form. I think that would make the flow easier to implement. 

I have slightly changed the flow and effectively made mine your suggestion of anticipating the redirect to IS. This effectively simplify a lot the interactions with IS. I have some other questions that arose from this choice.

1. it is correct to say that in the current scenario there's no need of hitting IS with specific prompts? I mean, as the flow is now fully managed inside IS forms (e.g. a wizard like set of pages) the entire flow can be triggered with a single initial standard  `AuthorizeRequest` with `prompt=login`. Is this correct from your perspective?

2. For the automatic signin at the end of the create account step I am using code like the following
```
    var user = new IdentityServerUser(userId) {
        DisplayName = Input.FullName
    };
    await HttpContext.SignInAsync(isUser);
```
Based on my understanding this should issue the authentication cookie for just created user. Is this correct?

3. when the flow start the first page receive a returnUrl parameter which is the original authorize request url. In this request there's also the url of the client application which requested authorization (e.g. `https://clientapp/signin-oidc`). Shall I redirect to IS or directly to the client application?

Thanks for your suggestions and support :)

**Comment by josephdecock** [comment]
prompt=login is a request from the client application that the user should log in again, even if they already have a session at the OP. In other words, prompt login means that the client application doesn't want the user to have a single sign on experience. I think you probably want to leave out the prompt parameter entirely. 

> Based on my understanding this should issue the authentication cookie for just created user but does not login the user. Is this correct?

Logging in at identity server, issuing the authentication cookie, and starting a session are all synonymous. 

I'm not sure what you mean by "does not login the user", but if you're talking about completing the OIDC flow and starting a session at the client application, you're right in the sense that starting the session at IdentityServer doesn't automatically send an id token back to the client. To do that, you would redirect back to the returnUrl that the IdentityServer middleware includes when it redirects to your UI. You should persist that returnUrl as the user navigates through the registration process, and then redirect to the returnUrl after they have registered. This will complete the OIDC flow, sending an id token back to the client, which will then start a session for the newly created user.

**Comment by vdevc** [comment]
> [...] but if you're talking about completing the OIDC flow and starting a session at the client application, you're right in the sense that starting the session at IdentityServer doesn't automatically send an id token back to the client. 

Yes, the meaning was exactly that one. I had the chance to experiment a bit over the last two weeks and everything works as expected. Thanks a lot for the help.
I think I can close this question now.
