### ISSUE TITLE
Migration guide from Duende IdentityServer v6 to Duende IdentityServer v7

### ISSUE THREAD

**Issue by SangeetAgarwal** [DuendeSoftware/Support#1086]
**Which version of Duende IdentityServer are you using?**
IdentityServer v6

**Which version of .NET are you using?**
net6.0

Wanted to know if there is any guidance for migrating from v6->v7

**Comment by SangeetAgarwal** [comment]
[https://github.com/DuendeSoftware/IdentityServer/releases](https://github.com/DuendeSoftware/IdentityServer/releases) was sufficient.

**Comment by SangeetAgarwal** [comment]
@AndersAbel Thanks! 
We are still on IdentityServer4 v2.1 with the intention to migrate to Duende Identity Server v7.
I see that I can incrementally upgrade from v3.1 all the way to Duende Identity Server v7.

But, I don't see any guide from  IdentityServer4 v2.1 to  IdentityServer4 v3.1. Is there any guidance to migrate to v3.1 from v2.1?

**Comment by AndersAbel** [comment]
That was some years ago... 
As far as I can see from the old release notes there are only minor breaking changes between 2.1 and 3.1. The main difference is the target framework update. I think that just updating the Nuget packages and target framework will do to get up from 2.1 to 3.1.

Note that while it is a good idea to go through the upgrades in the development environment, the production deployment should be one leap from 2.1 to 7.

**Comment by SangeetAgarwal** [comment]
> Note that while it is a good idea to go through the upgrades in the development environment, the production deployment should be one leap from 2.1 to 7.

yes, absolutely, once I have upgraded to 7 locally then plan on deploying to our Azure Dev environment and testing. I'll point a few of our apps on our dev environment to the newly upgraded Identity 7.  If all goes well then I'll move the other apps to Identity 7.

Even in production, I plan on following the same pattern of keeping our existing Identity running along side our newly upgraded Identity 7. And then progressively moving apps from our existing Identity to the new Identity v7.
