### ISSUE TITLE
Sample for deprecated GetSchemeSupportsSignOutAsync in v7.0

### ISSUE THREAD

**Issue by m-gug** [DuendeSoftware/Support#1087]
**Which version of Duende IdentityServer are you using?**
v7.0
**Which version of .NET are you using?**
.NET 8.0
**Describe the bug**
I'm currently in the process of updating to v7.0 and am having problems with the outdated `HttpContext.GetSchemeSupportsSignOutAsync` extension
to replace.

Unfortunately, I can't get any further with the information from the upgrade info and the example projects apparently still use the outdated function.

A short info on how to replace the old code from the starter projects would be great.

To be more precise, it is this block in the `BuildLoogedOutViewModelAsync`:

```
if (idp != null && idp != Duende.IdentityServer.IdentityServerConstants.LocalIdentityProvider)
{
    var providerSupportsSignout = await HttpContext.GetSchemeSupportsSignOutAsync(idp);
    if (providerSupportsSignout)
    {
        if (vm.LogoutId == null)
        {
            // if there's no current logout context, we need to create one
            // this captures necessary info from the current logged in user
            // before we signout and redirect away to the external IdP for signout
            vm.LogoutId = await _interaction.CreateLogoutContextAsync();
        }

        vm.ExternalAuthenticationScheme = idp;
    }
}
```

**Comment by m-gug** [comment]
Ah, I just realized that the function in the samples is already implemented as its own extensions (https://github.com/DuendeSoftware/Samples/blob/a3784de886a88302c832d3257dc352ef0bd241ee/IdentityServer/v7/Configuration/SimpleDcr/IdentityServer/Pages/Extensions.cs# L17)

I assume this is the correct way to migrate?

**Comment by josephdecock** [comment]
Yes, that's correct. It's also what our v7 samples and updated templates (for `dotnet new`) should be doing everywhere - is that not the case?

**Comment by m-gug** [comment]
Yes, the samples already do it that way, I was accidentally looking into the old samples.

**Comment by mr5z** [comment]
> Yes, that's correct. It's also what our v7 samples and updated templates (for `dotnet new`) should be doing everywhere - is that not the case?

I'm using v7.0.8 and this extensions to be removed already [HttpContextExtensions](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/HttpContextExtensions.cs).

I was using the old samples and just trying to migrate them manually. This is the only issue left I currently have.

**Comment by jonathanperis** [comment]
> > Yes, that's correct. It's also what our v7 samples and updated templates (for `dotnet new`) should be doing everywhere - is that not the case?
> 
> I'm using v7.0.8 and this extensions seems to be removed already [HttpContextExtensions](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/HttpContextExtensions.cs).
> 
> I was using the old samples and just trying to migrate them manually. This is the only issue left I currently have.

The same here. Only left this function on my current migration to 7.0.8
