### ISSUE TITLE
Sporadic Errors when scaling to multiple instances

### ISSUE THREAD

**Issue by spyder007** [DuendeSoftware/Support#109]
**Which version of Duende IdentityServer are you using?**
5.2.2
**Which version of .NET are you using?**
6.0.4
**Describe the bug**

We are running IdentityServer in a container on an AKS cluster.  We have implemented distributed caching via Redis and DataProtection via database persistence, but we are still running into issues running multiple containers.  Generally, we get sporadic login/logout failures, but nothing in the log is indicating problems. 

I'm working to gather better logs that might narrow our focus, but are their other known things that should be implemented when attempting to scale IdentityServer across K8 pods (or, even across multiple servers)?

**To Reproduce**

Run identityserver in a container with common dataprotection and distributed caching configured.

**Comment by brockallen** [comment]
> I'm working to gather better logs that might narrow our focus, but are their other known things that should be implemented when attempting to scale IdentityServer across K8 pods (or, even across multiple servers)?

Sorry, what you're describing is pretty vague. We have lots of customers running in scaled out scenarios. The only thing I can point you at is here: https://docs.duendesoftware.com/identityserver/v6/deployment/

More details/logs would be helpful.

**Comment by leastprivilege** [comment]
> Which version of Duende IdentityServer are you using?
5.2.2
Which version of .NET are you using?
6.0.4

These versions are incompatible. Please update to IdentityServer v6 to run on .NET 6.

**Comment by spyder007** [comment]
@brockallen - I'm working on getting better logs, but, unfortunately, we aren't seeing anything in particular.

@leastprivilege we are blocked from upgrading because of some of the changes made to the DBContexts:  We utilize store options to set DbSchema, but those options are not currently available for the PersistedDbGrantContext.  @brockallen  worked on a [PR](https://github.com/DuendeSoftware/IdentityServer/pull/945) to expose them, but until that's released, we are stuck where we are at.

**Comment by brockallen** [comment]
The PR has been merged. We all set on this issue then?

**Comment by spyder007** [comment]
The PR unblocks our update..  Once we get that upgrade processed, we will test further.  Thank you for the updates.
