### ISSUE TITLE
IdentityServer as a Federation Gateway

### ISSUE THREAD

**Issue by ryanbuening** [DuendeSoftware/Support#1090]
Hello. We are currently using Duende IdentityServer as a [Federation Gateway](https://docs.duendesoftware.com/identityserver/v6/ui/federation/) with only one [external auth provider](https://docs.duendesoftware.com/identityserver/v6/ui/login/external/) and our current setup looks somewhat like the following:

```c#
services.AddAuthentication()
	.AddLocalApi()
	.AddJwtBearer("PROD", options =>
	{
	 options.Authority = config.IdentityServerAuthority;
	 options.Audience = "secure-celina-services";
	 options.Events = new JwtBearerEvents()
	 {
		 OnTokenValidated = ctx =>
		 {
			 string? thisUserId = ctx.Principal?.FindFirst(ClaimTypes.NameIdentifier)?.Value;
			 TaggedCelinaUser? thisUser = UserClaimsRoutine.GetUserData(thisUserId);
			 ctx.Request.HttpContext.Items.Add("UserInformation", Newtonsoft.Json.JsonConvert.SerializeObject(thisUser));
			 ClaimsIdentity thisIdentity = UserClaimsRoutine.ProcessUserClaims(thisUser);
			 ctx.Principal?.Identities.First().AddClaims(thisIdentity.Claims);
			 return Task.CompletedTask;
		 },
		 OnAuthenticationFailed = ctx =>
		 {
			 Log.Error("Authentication failed", ctx.Exception);
			 return Task.CompletedTask;
		 }
	 };
	})
	.AddWsFederation("wsfed", "Portal Guard", options =>
	{
	 options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
	 options.Wtrealm = config.WTRealm;
	 options.MetadataAddress = config.MetadataAddress;
	 options.SkipUnrecognizedRequests = true;
	 options.UseTokenLifetime = true;
	 options.Events = new Microsoft.AspNetCore.Authentication.WsFederation.WsFederationEvents()
	 {
		 OnAuthenticationFailed = ctx =>
		 {
			 Log.Error("WSFederation authentication failed", ctx.Exception);
			 return Task.CompletedTask;
		 }
	 };
	});
```

We are now looking into using Azure B2C to use with a new Blazor Server .NET 8 app we are developing, but we need to keep the wsfed integration. I have some questions about this:

1. Is it possible to setup and redirect to external auth providers (B2C) based upon the app/url they are coming from?
2. Does anything extra need setup if we want to make authenticated requests from App B (behind B2C) to App A (behind wsfed) if they are both using IdentityServer as the gateway?
3. Is there anything else to keep in mind when attempting to do this? Any documentation that showcases something similar to what we're trying to do?

I have copied a high level diagram below of what we're trying to achieve. We do have Enterprise support, so if this is something that is more suited towards that avenue, please let me know. Thanks for any assistance.

![image](https://github.com/DuendeSoftware/Support/assets/812974/9b360554-ddad-4f6d-8bb1-f4c8d5a1b24b)

**Comment by josephdecock** [comment]
Closing, as this conversation continued in priority support.
