### ISSUE TITLE
Question: How does Duende IdentityServer support Single Sign On (SSO)

### ISSUE THREAD

**Issue by robert-shattock** [DuendeSoftware/Support#1091]
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**
8

**Describe the bug**
Not a bug, request for info

How does Duende IdentityServer support Single Sign On (SSO) - SSO is not explicitly mentioned anywhere on the site.  

What I think of as SSO is having multiple websites that I operate, and when a user goes to a page requiring an authenticated user they are redirected to an IdentityServer portal to login, after which they are redirected back and can use the website logged in.  The user can visit a 2nd of our websites and would either be automatically logged in or would click login and be redirected to the IdentityServer and straight away redirected back (not quite sure what is normal).  The final scenario is a third party wants to offer their services to our members - expectation is that the third party configures their authentication to use our IdentityServer i.e. our member goes to this third party site and once again would either be automatically logged in or would click login and be redirected to the IdentityServer and straight away redirected back (not quite sure what is normal). 

This talks about the flows I'm thinking of:
https://curity.io/resources/learn/web-client-sso-with-openid-connect/

It sounds like OpenID Connect (OIDC) supports SSO, and Duende IdentityServer support OIDC so I'm assuming the answer is yes, Duende IdentityServer supports SSO - https://docs.duendesoftware.com/identityserver/v7/quickstarts/2_interactive/ (I guess I was just surprised to not read it explicitly mentioned on the docs)

**Comment by josephdecock** [comment]
> It sounds like OpenID Connect (OIDC) supports SSO, and Duende IdentityServer support OIDC so I'm assuming the answer is yes, Duende IdentityServer supports SSO

Correct. The OIDC protocol is designed to accomplish exactly what you're talking about. SSO relies on a session cookie at the identity server host. When clients start the flow by redirecting to the authorize endpoint, IdentityServer checks for that session cookie. If it exists, IdentityServer redirects back to the client immediately, and the flow produces their id and access tokens without the user needing to login again. If the cookie doesn't exist, the user is shown the login page. Logging in creates the session cookie, and subsequent clients get the SSO experience.

**Comment by robert-shattock** [comment]
Thank you @josephdecock for the quick response and explanation.  From a marketing/SEO perspective it wouldn't hurt to have mention of it on the site, even if it was a one liner reference to how OIDC provides this out of the box.  That being said, I can appreciate that whoever is using Duende IdentityServer should probably have enough authentication knowledge to understand that in the first place.  Thanks again.

**Comment by miksh7** [comment]
From marketing purposes, it would be nice if the documentation search by "SSO" would return something.
See e.g. https://medium.com/@pantaanish/configuring-duende-identity-server-on-net-unlock-the-secrets-of-secure-identity-management-cc5ac6f74113
`Single Sign-On (SSO): Duende Identity Server enables seamless SSO across multiple applications and platforms. Once authenticated with Identity Server, users can access other applications without needing to re-enter their credentials.`

Reference to SSO sample(s) would be also greatly appreciated.
