### ISSUE TITLE
Identity Server with Content Security Policy

### ISSUE THREAD

**Issue by daver77** [DuendeSoftware/Support#1092]
**Which version of Duende IdentityServer are you using?**

6.3.8

**Which version of .NET are you using?**

6

**Issue**

We're currently implementing a strong Content Security Policy across our websites and I'm doing Identity Server now. We have a website with .NET Identity authentication integrated with Identity Server.

When I login I am redirected to "/connect/authorize/callback" which then uses inline script to redirect back to the relying party. I use a nonce on the script-src so that inline script is failing due to the CSP.

![image](https://github.com/DuendeSoftware/Support/assets/2369739/c8d516d1-3cac-4ca8-8b7e-6783beca6e7e)

![image](https://github.com/DuendeSoftware/Support/assets/2369739/b4c8a398-98a9-43b9-bfa0-efe30563a581)

What's the best way to fix this? Is there any way I can add the nonce attribute to that script tag?

**Comment by daver77** [comment]
What I did to resolve this was apply my CSP conditionally based on the path, ag

```
app.UseWhen(context => context.Request.Path.StartsWithSegments("/connect"), a =>
    // CSP for IdServer endpoints
);

app.UseWhen(context => !context.Request.Path.StartsWithSegments("/connect"), a =>
    // CSP for pages
);
```

**Comment by josephdecock** [comment]
Glad you solved this, and really appreciate you taking the time to post the details of your answer to avoid [this classic problem ](https://xkcd.com/979/)!
