### ISSUE TITLE
IDP login hint causing failure to redirect after successful login

### ISSUE THREAD

**Issue by serpentheadz** [DuendeSoftware/Support#1095]
**Which version of Duende IdentityServer are you using?**
7.0.0
**Which version of .NET are you using?**
net8.0
**Describe the bug**

When Identity Server is acting as an IDP for an OIDC client, and the client sends an IDP login hint as an acr_value, if that IDP does not exist, identity server will not redirect back to the client after a successful login. The user will be returned to the login page with no errors visible. The user will be successfully logged into identity server but not logged into the client.

**To Reproduce**

Set up an OIDC client to send an auth request to identity server like this:
`https://localhost:5001/connect/authorize?
response_type=code&
client_id={clientId}&
redirect_uri={redirectUri}
&state={state}&
nonce={nonce}&
acr_values=idp%3AthisIDPdoesnotexist
&scope=email%20profile%20openid`

Ensure the IDP `thisIDPdoesnotexist` does not exist on identity server.

Log into the identity server with a valid user.

After submitting a valid username/password the login page should reload with empty fields, and no visible errors. The user will be logged into identity server.

**Expected behavior**

Identity server should redirect the user to the client after successfully logging in, despite the invalid IDP supplied in the ACR values.

Or that an exception similar to the `invalid_client` error is shown when a request is made for an IDP that does not exist.

I think the first option would be preferable. In that case if an IDP is removed from Identity server the client can still login successfully.

**Additional context**

The issue seems to come from here: [AuthorizeInteractionResponseGenerator](https://github.com/IdentityServer/IdentityServer4/blob/4dc10e665f5ede63274427036c25cdc216130eb9/src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs#L170)

```
if (idp != currentIdp)
{
    Logger.LogInformation("Showing login: Current IdP ({currentIdp}) is not the requested IdP ({idp})", currentIdp, idp);
    return new InteractionResponse { IsLogin = true };
}
```

When the IDP is invalid, the value of `currentIdp` is "local".  
When testing without the IDP ACR value (a successful login) the method reaches the final line `return new InteractionResponse();`.

**Comment by josephdecock** [comment]
Thanks for opening this issue. In the short term, you can customize the authorize interaction response generator to return back to the client when the requested idp wasn't used. Longer-term, we'll consider handling this edge case in a future release (see the new issue mentioned above). My initial feeling is it is probably best to have the default behavior here be an error, and have the redirect back to the client anyway behavior be a customization that you would opt-in to.

But again, for now I would customize the generator. You can derive from it and override its ProcessInteractionAsync method. Call the base method in your override to get the default behaviors, but then examine the result. If the the result IsLogin, but the user is authenticated and the idp doesn't match the requested idp, then you can just `return new InteractionResponse()`. That means that the interaction response isn't asking to be redirected to an interactive page (UI at IdentityServer), so you should get sent back to the client.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by serpentheadz** [comment]
Thanks @josephdecock . Happy to close. We ended up adding checks for a valid IDP to an `ICustomAuthorizeRequestValidator`
