### ISSUE TITLE
Identity Server Template Question: Core Identity v. Entity Framework Stores

### ISSUE THREAD

**Issue by dgerding** [DuendeSoftware/Support#1098]
I'm pulling my Duende-based project back out of hibernation as that part of a related project is back on the front burner. 

My naive question is: Assuming I'm intending to use Identity Server to authenticate visitors to our asp.net core hosted site, and to authenticate that same user base using our app, what are the differences between these two template choices? :

![thumbnail_image](https://github.com/DuendeSoftware/Support/assets/523279/b83433fa-1ab3-469c-a1fe-b414b385b3e7)

Can you explain the differences here? Is it something like the first one uses ASP.NET Core Identity classes to describe users and the EF version lets you create user data as entities? Again, sorry in advance for vague understanding so far. It sounds like "Core Identity" would be the most plain vanilla version. 

I'll be using an Azure SQL, rather than SQlite data store, so whichever of these I choose needs to persist user data in Azure SQL DbContext.

Thanks in advance for any guidance.

**Comment by josephdecock** [comment]
There are 3 different types of data that need to be stored in a basic IdentityServer implementation:
- Configuration (e.g., what client applications exist, what scopes can they request)
- Operational data (we call this the persisted grant store, and it includes things like refresh tokens and authorization codes)
- Users (both profile data and credential info, like password hashes)

We provide 2 default implementations for the configuration and operational data stores: an in-memory version, suitable for testing and demos and an entity framework based implementation that can persist the data to any database with an EF provider. The template "with Entity Framework stores" includes this EF based implementation of the configuration and operational stores.

A user store is not directly used by the IdentityServer engine. We rely on a session getting started by the login page, but how the login page validates credentials and the overall login UX are some of the most commonly needed customizations. While we provide a quick start login ui to get started, the login UI is "user code". 

That said, a very common choice for a user store is asp.net identity. We provide a light weight integration with that user store and show how to use it on the login page in the template "with ASP.NET Identity".

Another great resource for getting started is our [QuickStart tutorial series](https://docs.duendesoftware.com/identityserver/v7/quickstarts/1_client_credentials/). It guides you through creating an identity server implementation and shows how to use both the EF stores and asp.net identity integration.

**Comment by dgerding** [comment]
Thanks!
