### ISSUE TITLE
Impersonation in Duende Identity v7

### ISSUE THREAD

**Issue by SangeetAgarwal** [DuendeSoftware/Support#1099]
**Which version of Duende IdentityServer are you using?**
Duende Identity v7

**Which version of .NET are you using?**
net8.0

**Describe the bug**
This isn't a bug but rather I'm looking for guidance for implementing impersonation. I have read [this](https://docs.duendesoftware.com/identityserver/v5/tokens/extension_grants/token_exchange/#impersonation) but was wondering if there is a sample project perhaps that goes a little deeper on how to implement impersonation with Duende Identity v7.

**Additional context**
We've had Identity4 v2.1 on net2.1 in production for quite a few years and are now in the process of upgrading to Deunde Identity v7 and one of the leading motivations for this upgrade was the ability to implement impersonation so any additional information/guidance to help me get started would be very helpful. 
There seems to be very little information available on how to implement impersonation and the only other stackoverflow question I could come across is given [here](https://stackoverflow.com/questions/75395957/user-impersonation-in-duende-identityserver) and it seems the OP is more or less in the same predicament as me. 

Thanks!

**Comment by SangeetAgarwal** [comment]
Closing for now, I see this [stackoverflow answer](https://stackoverflow.com/questions/45549824/identityserver4-how-to-implement-impersonation/60306389#60306389) that might work for us.

**Comment by josephdecock** [comment]
Even though you've already closed this, I would like to add a link to our token exchange [sample](https://docs.duendesoftware.com/identityserver/v7/samples/tokens/#extension-grants-and-token-exchange), which shows how to use token exchange to achieve delegation, impersonation, or some other custom semantic.

**Comment by SangeetAgarwal** [comment]
Thanks @josephdecock, I'll take a look at that sample and will reopen this ticket if I have questions.
