### ISSUE TITLE
PAR (Pushed Authorization Requests) support in BFF library

### ISSUE THREAD

**Issue by raeffs** [DuendeSoftware/Support#1103]
We got PAR running in the BFF with the [example](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v7/Basics/MvcPar/src/ParOidcEvents.cs) provided by inheriting from `Duende.Bff.BffOpenIdConnectEvents` instead of `OpenIdConnectEvents`, but we aren't sure if this recommended.

This is probably depending on changes in ASP.NET core itself, but were wondering if this is something that will be provided out of the box from the BFF library in the meantime?

**Comment by josephdecock** [comment]
Yes, I am currently working on adding support for PAR to the underlying IdentityModel and AccessTokenManagment libraries, and plan to include support for PAR in the next version of the BFF. We also ultimately would like to get support for PAR added to ASP.NET - see [here](https://github.com/dotnet/aspnetcore/issues/51686).
