### ISSUE TITLE
Why is AuthorizationCode.CodeChallenge hashed?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#1106]
I'm using .NET 6 and Identity Server 6.

I was debugging the source code and noticed when using OIDC/AuthZ flow, the PKCE `code_challenge` is being [hashed](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/ResponseHandling/Default/AuthorizeResponseGenerator.cs#L261).

If the `code_challenge` is already the hashed version of the `code_verifier`, what is the point in hashing the `code_challenge`?

Just for reference, when debugging locally, I can see that the `code_challenge` is `1Te0cMuGmg5-riN8MNHIVtjQkKe-PltNdOyxiBtnnvA`, and the hashed version is `xz56AzlvEUP7KYutYt/lTrn3/qMY1qrJ/o7UdlnbYMw=`.

**Comment by josephdecock** [comment]
IdentityServer's threat model assumes that an attacker can gain read only access to the persisted grant store. So, for defense in depth, we avoid storing sensitive or secret values - including code_challenge values - in the store without hashing or data protecting them. 

For the a long time now, the authorization code data where the code_challenge is stored is also by default also data protected, but the pkce implementation predates that feature (and in any event, data protecting the data can be disabled with config). 

Also, not every code challenge value is hashed - you can use a code_challenge_method of plain and have the code_verifier be unhashed. Now it is true that in the code base today, the code_challenge_method is tracked with the code_verifier, so I guess in principal it would be feasible to only do the hashing for code challenges that are plain. But the code challenge is still a secret value, and even if I can't think of anything useful that an attacker would do with it without the code verifier, I still don't want the attacker to have it.
