### ISSUE TITLE
well-known/openid-configuration cannot load 504

### ISSUE THREAD

**Issue by mfnones** [DuendeSoftware/Support#1110]
**Which version of Duende IdentityServer are you using?**
Duende IdentityServer v6.3.0

**Which version of .NET are you using?**
.Net 6

**Describe the bug**

When accessing our spa, it should redirect to Identity Server's login page, but the redirection fails. In console the error get stuck with the .well-known/openid-configuration as 504 Gateway Timeout. This started after upgrading from .Net Core 3.1 with IdentityServer4 to .Net 6 with Duende IdentityServer v6.3.0. Would you have any ideas to what I should check?

**Expected behavior**

Our dev site to properly load and redirected to Login page.

**Additional context**

- The project works locally. This is experienced after deployment to Azure.
- Upgrade to .Net 6 was done with Upgrade Assistant. Upgrade to Duende IdentityServer 6 was done manually by a colleague following the migration document.
![image](https://github.com/DuendeSoftware/Support/assets/65269476/a3c3e5fc-dd03-4ece-8ffc-f2763ca287fd)

**Comment by RolandGuijt** [comment]
One thing to try is to access the .well-known/openid-configuration URL with a browser and see if you see JSON coming back. If that works you know that the application with IdentityServer functions correctly.

Also depending on how you host the application on Azure, it could be that the request timeout setting is a bit tight. That could lead to problems especially when the application needs a cold start.
You can also check the timeout setting on the frontend side in the javascript library you're using to do the request if applicable.

Feel free to post what you find so we can investigate further if needed.

**Comment by mfnones** [comment]
Hi Roland,

Directly accessing it does not return the json but a 504 error. I will try to check the the timeouts you suggested. Thank you!
![image](https://github.com/DuendeSoftware/Support/assets/65269476/c4f3b927-506f-48b5-bbf9-cc6acf81e46a)

**Comment by AndersAbel** [comment]
@mfnones Do you have any updates on this? If the problem is solved we'd like to close the issue.

**Comment by mfnones** [comment]
Hi thank you! Yes I will close this issue. We have identified that this is not due to duende server, but after the upgrade to .net 6, we needed to install the .Net SDK to the Identity container as well which was needed before.
