### ISSUE TITLE
Trigger Manual Renew token in BFF

### ISSUE THREAD

**Issue by wantwi** [DuendeSoftware/Support#1118]
Please how can I trigger a manual refresh token especially when the HttpContext.GetUserAccessTokenAsync() return null  or empty AccessToken

**Comment by RolandGuijt** [comment]
The refresh token is sent together with the access token. There is probably no access token because GetUserAccessTokenAsync returns null so in that case there also wouldn't be a refresh token.

Finding out what causes that may lead to the solution to your problem. Is GetUserAccessTokenAsync always returning null or is this problem happening occasionally?
A great way to find out what's wrong is by looking at and playing around with our [examples for BFF](https://docs.duendesoftware.com/identityserver/v7/samples/bff/).

**Comment by wantwi** [comment]
Thank you for getting back to me.
The  GetUserAccessTokenAsync does not always return null. It happens when the access token expires. I was hoping it could trigger a refresh token before sending the request. If possible, can I trigger a refresh token and retry the request again when GetUserAccessTokenAsync returns null?

**Comment by RolandGuijt** [comment]
First make sure you're actually requesting the refresh token with the offline_access scope. Also the client config in IdentityServer should allow that scope by setting the AllowOfflineAccess property to true.

On the host, when you then use the AddUserAccessTokenHttpClient extension method to get an HttpClient instance with built-in token management the refreshing of the token should happen automatically.
You can also use typed clients. Please see the samples [here](https://docs.duendesoftware.com/identityserver/v7/bff/tokens/).

**Comment by wantwi** [comment]
Thank you for getting back to me.
I want to make a little clarification here. I can get the token using the  GetUserAccessTokenAsync and after about 5 minutes (my token time), I realize the token refreshes and I get a new token. However after the token is refreshed about 3 times, the GetUserAccessTokenAsync  returns null which in that case you said there wouldn't be a refresh token. So I want to know what can cause the GetUserAccessTokenAsync to return null?

**Comment by AndersAbel** [comment]
Are there any more questions to this or can we close the issue?

**Comment by wantwi** [comment]
Not really. I just changed my idp configuration to use Re-useable refresh tokens. Even though it works well, when I leave my app for some time (no interaction on the page)  and refresh my page, I realize the token returns null. so I had to logout and login again. But in all it works.
