### ISSUE TITLE
PersistentGrantDbContext StoreOptions property is Protected

### ISSUE THREAD

**Issue by rmazahreh** [DuendeSoftware/Support#112]
Hi, we are trying to upgrade from IdentityServer4 to Duende version 6.0.0 and we are using  .Net 6. 
We upgraded Duende.IdentityServer.EntityFramework.Storage to version 6.1.1 in order to be able to pass StoreOptions in the data migrations design factory, we could set this property for the ConfigurationDbContext because it's public, however in the PersistentGrantDbContext this property is protected so we couldn't set it. 

We have found a pull request which seems to fix this issue but we are wondering when this fix will be released?

https://github.com/DuendeSoftware/IdentityServer/blob/brock/ef_options_public_setters/src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs

**Comment by brockallen** [comment]
> We have found a pull request which seems to fix this issue but we are wondering when this fix will be released?

I'd say in the next week or two. You can test from our nightly builds to provide feedback: https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds

**Comment by brockallen** [comment]
This was released in a patch last week. Thanks.

**Comment by rmazahreh** [comment]
Great thanks for letting me know!

Sent from my iPhone

On 19 Jul 2022, at 2:03 am, Brock Allen ***@***.***> wrote:

﻿

This was released in a patch last week. Thanks.
