### ISSUE TITLE
Upgrading license key

### ISSUE THREAD

**Issue by aparrans** [DuendeSoftware/Support#1120]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
7

We have received an updated license key for our identity server, from the documentation I am having an issue upgrading it.
https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key/
We have it running on an azure app service but I am unable to find the key in the file system of the host to replace with the new key.
I am not sure the best way to do the update it dynamically so was wanting to avoid this in case I create an issue. 
How am I able to best find the licence key file to change it over?

Thanks
Arran

**Comment by RolandGuijt** [comment]
There are two ways a license key can be used:

- It could be in the content root path of the application. The filename would be Duende_License.key. In deployed state that is the location of the compiled assemblies. When using an Azure App Service a way to look at the file system is to use Kudu (accessible in the Azure portal) to look at the file system.

- It can also be loaded in code when configuring IdentityServer:

```
builder.Services.AddIdentityServer(options =>
{
  options.LicenseKey = "eyJhbG..."; // the contents of the license key file
});
```

When the latter option is used, the file could be loaded from anywhere, including a key vault for instance.

Please check these two possibilities and let me know what you find.

**Comment by AndersAbel** [comment]
@aparrans Did Roland's description solve the problem? If everything is working we'd like to close the issue.

**Comment by aparrans** [comment]
Hi yes I believe we were able to get it working thanks for the assistance
