### ISSUE TITLE
IDP as ExternalProvider

### ISSUE THREAD

**Issue by AlexAlexGoTO** [DuendeSoftware/Support#1121]
Hello, we are about to buy license and start using you library for all our clients, but before we wanted to make some demo, that fit our old(net framework) system. We have next issue:

We want to have our IDP as external provider so when I login in our app through IDP I can access 

`var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync()`

and it works If I use AuthenticationType as DefaultAuthenticationTypes.ExternalCookie

In ExternalLoginCallback I can access 

`await HttpContext.GetOwinContext().Authentication.AuthenticateAsync(DefaultAuthenticationTypes.ExternalCookie);`

but after this we are using 'await SignInManager.ExternalSignInAsync(loginInfo, isPersistent' from 'Microsoft.AspNet.Identity.Owin'

and it calls "AuthenticationManager.SignOut("ExternalCookie", "TwoFactorCookie");" inside that library

Also I'm adding user to UserExternalLogins

So after this situation is next: I'm logged in but I don't have access anymore to 
id_token and access_token.

I'm using OpenidConnect and I have 
SaveTokens = true,

Can you give me advice maybe. should I pre-save id_token and acess_token to database or in memory before I call SignInManager.ExternalSignInAsync or I'm doing something totally wrong? 

Thanks in advance!

EDIT: as a workaround I can override SingIn Method in Owin 2.2.3 

```
public virtual async Task SignInAsync(TUser user, bool isPersistent, bool rememberBrowser)
{
    ClaimsIdentity claimsIdentity = await CreateUserIdentityAsync(user).WithCurrentCulture();
    AuthenticationManager.SignOut("ExternalCookie", "TwoFactorCookie");
    if (rememberBrowser)
    {
        ClaimsIdentity claimsIdentity2 = AuthenticationManager.CreateTwoFactorRememberBrowserIdentity(ConvertIdToString(user.Id));
        AuthenticationManager.SignIn(new AuthenticationProperties
        {
            IsPersistent = isPersistent
        }, claimsIdentity, claimsIdentity2);
    }
    else
    {
        AuthenticationManager.SignIn(new AuthenticationProperties
        {
            IsPersistent = isPersistent
        }, claimsIdentity);
    }
}
```

And add there some custom AuthenticationProperties then it works, any suggestions? Looks like that was fixed in .net core but not in .net framework

**Comment by RolandGuijt** [comment]
Can you elaborate a bit? I'm not sure if I understand your question.
You want to access the id and access token from an external identity provider?

**Comment by AlexAlexGoTO** [comment]
Yes, so in a nutshell, after login with 

`await SignInManager.ExternalSignInAsync(loginInfo, isPersistent);`

I don't have my tokens anymore in AuthenticationProperties
