### ISSUE TITLE
Passwordless Ux: Using email and sms Otps Only?

### ISSUE THREAD

**Issue by dgerding** [DuendeSoftware/Support#1123]
Hi,
I'm using .net 8 with the latest Duende libraries. I've got a site where we _always_ know the email address and sms phone of our users, and don't want them to have to set or use passwords.

I have all the public credentials (email and sms) in aspnet identity format sql store.

```
//create a random pw they never see
 var pw = ShortGuid.Encode(Guid.NewGuid());
 pw = "?@" + pw + "!";

 // create user using already verified email and sms phone
 user = new IdentityUser { UserName = MembershipInvitation.InviteeEmail, Email = MembershipInvitation.InviteeEmail, PhoneNumber = MembershipInvitation.InviteePhoneNumber };
 createUserResult = await _userManager.CreateAsync(user, pw);

```
In this design the user never sees their pw. 

Is there a UX example or something close that would let a use sign in to sight by:

- entering their email and using otp sent to email (?)
- entering phone and using otp sent to text?

I already have emailing and sms hops working on live site - I just need the right Duende example to help my users sign in (very securely) without a text password, using some combination of otp links to text and|or email?

Any help appreciated.

Dave Gerding

**Comment by RolandGuijt** [comment]
First things first: we discourage a scenario where users can login without a password. On top of that using SMS as a MFA method has proven to be unsafe.

Having said that:

The logic that logs a user in is up to you.
The IdentityServer [sample ](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/AspNetIdentity)using [ASP.NET](http://asp.net/) Core Identity has this code in Pages/Account/Login/Index.cshtml.cs to log users in:

var result = await _signInManager.PasswordSignInAsync(Input.Username!, Input.Password!, Input.RememberLogin, lockoutOnFailure: true);

But that can be replaced with a SignInAsync call on HttpContext.

To cater for the otps I would recommend using Identity's built-in 2FA system. The sample doesn't have an example for that but if you create a new (e.g. MVC) [ASP.NET](http://asp.net/) Core application with the "Individual Accounts" authentication option and scaffold out Login.cshtml and LoginWith2fa.cshtml, you'll see how it works.

To set Identity 2FA up with Email and/or texts (be careful with the latter!) please look [here](https://learn.microsoft.com/en-us/aspnet/identity/overview/features-api/two-factor-authentication-using-sms-and-email-with-aspnet-identity).

**Comment by dgerding** [comment]
Thanks. More reading to do.
