### ISSUE TITLE
Front/Back Channel Logout URI - why are they needed?

### ISSUE THREAD

**Issue by samuelwine** [DuendeSoftware/Support#1125]
**Which version of Duende BFF are you using?**
Duende.BFF (2.2.0)

**Which version of .NET are you using?**
.NET 8.0

**Question**
I'm using the DefaultLogoutService as is which contains the following code:
```
// get rid of local cookie first
var signInScheme = await AuthenticationSchemeProvider.GetDefaultSignInSchemeAsync();
await context.SignOutAsync(signInScheme?.Name);
```
Later on it signs out of IdentityServer as well:
```
// trigger idp logout
await context.SignOutAsync(props);
```
Based on the above code which has logged the user out of both the BFF backend as well as the IdentityServer, why is there a need for any further logout to take place through calling either a front or back channel logout uri?

I'm totally new to IdentityServer and auth in general, so I'm probably missing something basic here. I'd be grateful though if you could clarify this for me.

**Comment by samuelwine** [comment]
@RolandGuijt Thanks for this helpful clarification!
So just to be sure, if the user is never going to be logged in to more than one client, there is no need for any further logout - is that right?

**Comment by RolandGuijt** [comment]
Yes. And in that case you also don't need to register front- and backchannel logout URIs.

**Comment by samuelwine** [comment]
Thanks @RolandGuijt

**Comment by RolandGuijt** [comment]
I'd like to come back to my last comment: I would actually register the URIs. 
The reason is that a user might logout at the identity provider instead of at the client. On top of that it's more future proof should you add more clients later.

**Comment by samuelwine** [comment]
@RolandGuijt thinking about it, that makes sense!
Thank you
