### ISSUE TITLE
IdentityServer cookies sent to BFF Host

### ISSUE THREAD

**Issue by samuelwine** [DuendeSoftware/Support#1126]
**Which version of Duende BFF are you using?**
Duende.BFF (2.2.0)

**Which version of .NET are you using?**
.NET 8.0

**Question**
I've noticed that the cookies from both the IdentityServer and the BFF host are sent to both the IdentityServer and the BFF host.

![image](https://github.com/DuendeSoftware/Support/assets/15095510/aaa49e40-1da7-4ffe-a5f8-0cc001967f61)
![image](https://github.com/DuendeSoftware/Support/assets/15095510/d4befbea-6723-44c5-91ae-8607bd7c45bb)

I'm wondering

1.  how that is configured, as I thought that cookies are only sent back to the site and port that issued them originally?
2. why is it necessary that both servers receive all the cookies?

Many thanks!

**Comment by RolandGuijt** [comment]
You're running both applications on localhost. The browser will send cookies to sites running on the same host as where they came from. 

With a URL like https://localhost:3843/ for example, the browser will just see "localhost", that's the host name. So all cookies will be sent that were set by "localhost" earlier ignoring scheme and port.

**Comment by samuelwine** [comment]
@RolandGuijt Thanks for clarifying!
