### ISSUE TITLE
Login management end point parameters

### ISSUE THREAD

**Issue by mlaflamme49** [DuendeSoftware/Support#1129]
**Which version of Duende BFF are you using?**
2.2.0
**Which version of .NET are you using?**
8

Hi,
I was wondering if there was a way to forward query parameters passed to the login management endpoint to the oidc authority. I'm trying to pass the culture.

**Expected behavior**
Calling bff/login?returnUrl=abc&culture=fr-CA would append the &culture=fr-CA to the login page of the oidc authority

Thanks

**Comment by RolandGuijt** [comment]
The OpenIdConnect standard defines a way to pass on culture information to the IdP by using ui_locales.

Here's how to pass that string to the IdP using Microsoft's OpenIdConnect middleware:


```
            services.AddAuthentication(options =>
            {
                ..
                option.AddOpenIdConnect("oidc", options =>
                {
                    options.Events.OnRedirectToIdentityProvider = (c) =>
                    {
                        var context = c.HttpContext;
                        c.ProtocolMessage.UiLocales = "fr-CA";
                        return Task.CompletedTask;
                    };

So you can access the complete httpContext, including query strings, and extract what you need.
The ProtocolMessage object represents the request going to the IdP. As you can see it has the UiLocales property.
