### ISSUE TITLE
We need an IdentityServer listen on two domains (license problem with second issuer ).

### ISSUE THREAD

**Issue by koalabruder** [DuendeSoftware/Support#1134]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
.NET 6.0

**Describe the bug**

Our syslog gives us the following message:
```
Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: https://identity.cn.example.com, https://identity.example.com.
```
We use only one IdentityServer. The IdentityServer listens to two URI's. We need a second URI for some special routing.

**To Reproduce**

To reproduce make your IdentityServer listen on two different domains.

**Expected behavior**

We do not want to have such failure messages

**Log output/exception with stacktrace**

```
Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: https://identity.cn.example.com, https://identity.example.com.
```

**Additional context**

-

**Comment by josephdecock** [comment]
IdentityServer uses the host of incoming requests to infer the issuer, unless you explicitly configure the issuer. If you need multiple issuers, that requires an enterprise license. If you want requests to different domains to always use a single issuer, then configure the IssuerUri. See also: https://docs.duendesoftware.com/identityserver/v7/reference/options/.

**Comment by koalabruder** [comment]
OK. To clarify that. We have a single deployment of the IdentityServer with two issuers. That means we need the enterprise license?

**Comment by josephdecock** [comment]
Yes, that's correct.

**Comment by brockallen** [comment]
If you need to continue the licensing conversation, please send an email to contact@duendesoftware.com.

Thanks.
