### ISSUE TITLE
Question: Scaffolding Templated with EF Support for Identity

### ISSUE THREAD

**Issue by dgerding** [DuendeSoftware/Support#1135]
As I contemplate keeping the Duende-based project "I've updated to running" or creating a clean rebuild using the newest template project, I'm wondering about Scaffolding out the identity pages. My impulse is to "Override all" and get the full mix of scaffolding mix available since I find I wind up needing many or most, but will I be over-writing code the template doesn't expect to be overriden by scaffolding?

I want 2fa support and token auth for api calls back to service, since our site serves pages to authenticated users and api calls to authenticated clients via jwt.

If I create a new Identity Server project with EF support for Identity persistence from the latest template, I have two big questions:

- Are the implications (beside bloat etc...) to scaffolding out _all_ the Identity related pages available?
- Is there an example that will ease going from sqlite to azure sql? We're using azure sql for the identity store and all those bits are up and running in "up and running but old and not complete project." 

Thanks for guidance. 

Dave G

**Comment by josephdecock** [comment]
My usual approach is to begin with our identity server ASP.NET Identity template (`dotnet new isaspid`), separately create a project to scaffold identity, and then copy over only the scaffolded files that I need. Our template knows how to interact with IdentityServer (e.g., redirecting back to the returnUrl to continue a protocol flow), so I'd prefer that over the scaffolded login page. 

As far as using sql server goes, I think you need to do 3 things:
1. Create the schema. You can use EF migrations to do this, which we show in [quickstart 4](https://docs.duendesoftware.com/identityserver/v7/quickstarts/4_ef/)
2. Switch from sqlite to sql server. For this you just need to change the `UseSqlite` call to `UseSqlServer`, which we show in the docs [here](https://docs.duendesoftware.com/identityserver/v7/data/ef/).
3. Migrate your data, if necessary.
