### ISSUE TITLE
Per Tenant Session Expiration Lifetime

### ISSUE THREAD

**Issue by A-Stapleton** [DuendeSoftware/Support#1137]
Duende IdentityServer V7.0.0
.Net 8

We are currently building a new SaaS application that we will be purchasing an Enterprise License for once our evaluation period has passed so hoping to get this (I think last issue) resolved. Everything else is working great so far so thanks for the good work and great product!

We have an app with Server Side Sessions turned on and we are being asked by the business to allow customisation of the session lifetime on a per tenant basis in our multi-tenant SaaS application.

I think (I may well be wrong) that there are 2 parts to this.

**1 Access Tokens**
We will need to allow customisation of the access_token lifetime on a per tenant basis. I think this can be achieved using a custom implementation of `Duende.IdentityServer.Validation.ICustomTokenRequestValidator` where we set the access_token lifetime inside this. (The docs here https://docs.duendesoftware.com/identityserver/v6/tokens/dynamic_validation/ suggest this is feasible so I think I'm comfortable with that?)

**2 Server Side Sessions**
I don't see a way to allow this to be customised on a per tenant basis, I'm not sure from the docs where this is even generated (maybe it's tied into the cookie lifetime) so I'm hoping someone will just say, make a custom one of `XYZ`. 

Is it even possible to allow a tenant to customise session/token lifetime in this way?
Am I even moving in the right direction with the above options?

Any help would be greatly appreciated. 😖

**Comment by josephdecock** [comment]
Yes, using the `ICustomTokenRequestValidator` to set the lifetime per-tenant should work fine.

Similarly, I believe you can control the server-side session expiration by customizing `IServerSideSessionStore.CreateSessionAsync`. If you're using our EF based store implementation, that method is a virtual, so you can manipulate the `Expires` time, and then call the base implementation. I would encourage you to test this in the context of sessions sliding (that is, using the session after more than half its duration has elapsed should extend it by its duration), and verify that coordination behaves how you expect (e.g., using a refresh token should slide the session).

**Comment by A-Stapleton** [comment]
Thanks for the quick reply, I will give that a go and let you know how we get on.

Do you know if changing the Expires time in there will fix up the cookie expiration time as well to prevent that being an issue?

**Comment by A-Stapleton** [comment]
Thanks for the additional info, will give that a go first as it does sound much simpler. Thank you for the additional suggestion. I will report back once we have tried something so others can see the resolution in future :)

**Comment by A-Stapleton** [comment]
Hello, sorry I got pulled on to something else. We do still need to do this but you know how priorities shift 😞 At the moment I should be back on this in the next few weeks, I do intend to post an update once we have proved/disproved this as working so it completes this issue for anyone else looking to do something similar 😄

**Comment by RolandGuijt** [comment]
OK, I'm closing for now but feel free to add a comment when you have your findings.
