### ISSUE TITLE
Possible to use IdentityServer as the IdP for SSO with an external application?

### ISSUE THREAD

**Issue by bsutliffe** [DuendeSoftware/Support#1139]
**Which version of Duende IdentityServer are you using?**
v6, but could upgrade to v7

**Which version of .NET are you using?**
.NET 6

**Question**
Is it possible for IdentityServer to act as the Identity provider for an external application using OIDC?

So the external application would configure their system to use my app as the IdP (which is using IdentityServer).  Users who go to that external application could then choose to log in with SSO, get redirected to my login page, and then redirected back to the external application.

I have it working the other way around already, where my application is using external IdPs for authentication.  So this would be the opposite of that.  I don't see anything in the documentation about how to set this up.

**Comment by RolandGuijt** [comment]
Yes that is possible.

The other IdP must be configured as a client in the IdentityServer IdP. The other IdP can now challenge the IdentityServer IdP and when it gets the callback it should do claims transformation and issue the tokens as normal.

The reason there's no docs on this is that we don't know what that other IdP is running and how it is configured.

**Comment by RolandGuijt** [comment]
Closing this for now but feel free to re-open if you have further questions around this topic.
