### ISSUE TITLE
Functional difference between two methods for handling client credential token management

### ISSUE THREAD

**Issue by aj-scram** [DuendeSoftware/Support#1140]
Was re-reviewing the [Duende.AccessTokenManagement Wiki - Web Apps](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/web-applications) 

And had a question regarding the client credentials flow.

Specifically, is there a functional difference between the following two methods for registering a client:

```
// registers HTTP client that uses the managed client access token
builder.Services.AddClientAccessTokenHttpClient("masterdata.client",
    configureClient: client => { client.BaseAddress = new Uri("https://api.company.com/masterdata/"); 
});
```

VS

```
services.AddClientCredentialsHttpClient("invoices", "invoice.client", client =>
{
    client.BaseAddress = new Uri("https://apis.company.com/invoice/");
});
```

It seems to me that the only real difference is in how the client credentials configuration are pulled for the ClientCredentialsTokenManagementService ?

One pulls from the OpenId configuration options to talk to other services on behalf of the service, but the scopes needed for machine to machine have to be a subset of the user scopes.

Where as the latter method allows us to define completely separate scopes for the machine to machine discussion that has zero connection with the user scopes define in OpenId config

**Comment by RolandGuijt** [comment]
When using AddClientAccessTokenHttpClient an interactive flow is assumed (like Authorization Code) and the access token will be pulled from where it is configured to be stored. 
Commonly SaveTokens is set to true in the OpenID Connect middleware config. In that case it is coming from the authentication cookie.

With AddClientCredentialsHttpClient client credentials flow is assumed which isn't interactive (no user) so getting the token from the cookie doesn't work. Instead a request to the token endpoint of the IdP will get it and it will be cached for subsequent requests.

**Comment by aj-scram** [comment]
Doesn't a AddClientAccessTokenHttpClient still have to reach out to get a new token anyway? Cause the documentation states this being used to do client credentials authentication on behalf of the service, so the web application can talk to other services, ie. machine to machine.

[Of course, the ASP.NET Core web application host could also do machine to machine API calls that are independent of a user. In this case all the token client configuration can be inferred from the OpenID Connect handler configuration. The following registers an HTTP client that uses a client credentials token for outgoing calls:](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/web-applications#:~:text=Of%20course%2C%20the,for%20outgoing%20calls%3A)

The code registers a OpenIdConnectClientAccessTokenHandler as a message delegate. The delegate then calls an extension method defined for the IHttpConteext -> TokenManagementHttpContextExtensions.GetClientAccessTokenAsync

This method has the following code 

```
  public static async Task<ClientCredentialsToken> GetClientAccessTokenAsync(
        this HttpContext httpContext,
        UserTokenRequestParameters? parameters = null,
        CancellationToken cancellationToken = default)
    {
        var service = httpContext.RequestServices.GetRequiredService<IClientCredentialsTokenManagementService>();
        var options = httpContext.RequestServices.GetRequiredService<IOptions<UserTokenManagementOptions>>();
        var schemes = httpContext.RequestServices.GetRequiredService<IAuthenticationSchemeProvider>();

        var schemeName = parameters?.ChallengeScheme ?? options.Value.ChallengeScheme;
        
        if (string.IsNullOrEmpty(schemeName))
        {
            var defaultScheme = await schemes.GetDefaultChallengeSchemeAsync().ConfigureAwait(false);
            ArgumentNullException.ThrowIfNull(defaultScheme);

            schemeName = defaultScheme.Name;
        }

        **return await service.GetAccessTokenAsync(
            OpenIdConnectTokenManagementDefaults.ClientCredentialsClientNamePrefix + schemeName,
            parameters, 
            cancellationToken).ConfigureAwait(false);**
    }
```

And that emphasized bit is basically the same call as a the one ultimately made by AddClientCredentialsHttpClient, since it registers a ClientCredentialsTokenHandler as a delegate and than that calls 

```
    /// <inheritdoc/>
    protected override Task<ClientCredentialsToken> GetAccessTokenAsync(bool forceRenewal, CancellationToken cancellationToken)
    {
        var parameters = new TokenRequestParameters
        {
            ForceRenewal = forceRenewal
        }; 
        return _accessTokenManagementService.GetAccessTokenAsync(_tokenClientName, parameters, cancellationToken);
    }
```

So, they're both calling the IClientCredentialsTokenManagementService to get a client credentials access token and the former is just using a pre-defined token client based on scheme, is my understanding.

**Comment by aj-scram** [comment]
If you could point me to where the 'OpenIdConnectTokenManagementDefaults.ClientCredentialsClientNamePrefix + schemeName' that would help my understanding a bunch. 

Just been digging through the code to better understand how this library works since I've been nominally placed in charge of implementing auth stuff for some new services. 

I have a fairly strong handle on the worker application side of things, but the web one, not so much. We currently don't use the OpenIdConnect side of the library and I'm trying to narrow down how scopes work for the client credentials portion of that.

**Comment by RolandGuijt** [comment]
After some further investigation it turns out I had some misconceptions about this myself.

Both AddUserAccessTokenHttpClient and AddClientAccessTokenHttpClient will use Client Credentials flow.

AddUserAccessTokenHttpClient will infer the configuration of the client from the OpenID Connect middleware configuration.
That's also where OpenIdConnectTokenManagementDefaults.ClientCredentialsClientNamePrefix + schemeName comes from. That is inferred from that config.

With AddClientAccessTokenHttpClient the client configuration has to be done specifically.

In both cases caching is used for the token using DistributedClientCredentialsTokenCache.

I will raise an issue to improve the documentation.

**Comment by RolandGuijt** [comment]
After some further investigation it turns out I had some misconceptions about this myself.

Both AddClientCredentialsHttpClient and AddClientAccessTokenHttpClient will use Client Credentials flow.

AddClientAccessTokenHttpClient will infer the configuration of the client from the OpenID Connect middleware configuration.
That's also where OpenIdConnectTokenManagementDefaults.ClientCredentialsClientNamePrefix + schemeName comes from. The schemeName is the name of the configured OIDC scheme.

With AddClientCredentialsHttpClient the client configuration has to be done specifically for Duende.AccessTokenManagement.

In both cases caching is used for the token using DistributedClientCredentialsTokenCache.

**Comment by RolandGuijt** [comment]
Closing for now but feel free to reopen if there are more questions.
