### ISSUE TITLE
How to override application scopes with rolebased scopes from access token in identity server 4?

### ISSUE THREAD

**Issue by GouthamiSivakoti** [DuendeSoftware/Support#1143]
1.Trying to implement role-based access control (RBAC) to replace existing scopes with role-based scopes in access tokens.

2.The application currently uses scopes "openid", "offline_access", and "managementapi:allowall" for authorization.

3.However, I want to replace these scopes with role-based scopes in access token. Specifically, the role associated with the user only has one scope, which is "managementapi:allowall".

Below is my code

```
context.IssuedClaims.RemoveAll(c => c.Type == "scope");
           foreach (var scope in roleMappedScopes)
           {
               if (allowedScopes.Contains(scope))
               {
                   claims.Add(new Claim("scope", scope));
              }
           }
           context.IssuedClaims = claims;
```

And i tried to add scope directly to IssuesClaim like below.

```
foreach (var scope in roleMappedScopes)
{
    if (allowedScopes.Contains(scope))
    {
        context.IssuedClaims.Add(new Claim("scope", scope));
    }
}
```

But in access token only application scopes are returning to scope claim. How can we map only rolebased scopes to scope claim in access token?
@leastprivilege @brockallen  Please respond asap

**Comment by josephdecock** [comment]
IdentityServer4 is no longer supported. This forum is for users of Duende IdentityServer, so please [get in touch](https://duendesoftware.com/contact) to get a [license](https://duendesoftware.com/products/identityserver#pricing).

That said, the approach that you're describing is not generally recommended. Scopes represent authorization of the _[application itself](https://duendesoftware.com/products/identityserver#pricing)_, not of a user.

More generally, we have documentation on how to customize claims [here](https://docs.duendesoftware.com/identityserver/v7/fundamentals/claims/).

**Comment by GouthamiSivakoti** [comment]
Thanks for responding @josephdecock , To manage user authorizations we created a custom claim called "grantedscope" and not using "scope" claim at all. 
This topic become confusing because some articles saying we should not merge authorizations in identity server and some suggesting to implement authorization using identity server through custom claim. 

[](https://levelup.gitconnected.com/enhancing-application-security-with-role-and-claim-based-authorization-using-duende-identity-server-f00c70e8de0f)

[](https://leastprivilege.com/2016/12/16/identity-vs-permissions/)  

We have a plan to migrate our identity server to duende identity server in couple of weeks. before that we want to get clarify on this topic. Kindly suggest

**Comment by josephdecock** [comment]
I'm not familiar with the first blog that you're linking to, but the second is from [Dominick Baier](https://leastprivilege.com/author/dominickbaier/) who is one of the original authors of IdentityServer and a co-founder of Duende. Even though Dom's blog post is 7 years old now, it is still how we think about permissions and identity. There can be times when it would be appropriate to put role claims into a token - as that post suggests, roles that are inherent to an identity and not application specific, like "doctor" or "nurse" might be a good candidate. If you're going to do that, I would put such roles into a custom claim not the scope. The scope claim has specific semantics in OAuth and special handling in IdentityServer, and you'll just be fighting that if you try to put roles into the scope.

**Comment by josephdecock** [comment]
Anything further needed here, or shall we close the issue?
