### ISSUE TITLE
Bff and refresh tokens

### ISSUE THREAD

**Issue by forrestab** [DuendeSoftware/Support#115]
**Which version of Duende BFF are you using?**
1.2.3

**Which version of .NET are you using?**
6.0

As the title suggests, we are trying to implement refresh tokens with bff and are having a bit of a problem with the "refresh" part. We've added the "offline_access" scope and can see that we get a refresh token in the `TicketReceived` oidc event. But when the access token and user session expires and we make a call to one of our api endpoints the access token is not refreshed.

We've looked through the provided samples and believe we have wired everything up correctly, so we aren't really sure what we are doing wrong. Do we have a misconception that token refresh should happen automatically? Is there a middleware we need to configure or provide that does the refresh?

**Comment by forrestab** [comment]
@leastprivilege we downloaded and tried with the JsBffSample and made the following change (for testing and to slightly mimic our code):

```csharp
.AddCookie("cookie", options =>
{
    //...
    options.ExpireTimeSpan = TimeSpan.FromSeconds(10);
})
```

And what we found is as long as a call is made within the above timespan everything works, we can see the cookie change in the browser when we make a call that is near the expiration time. But when we let it expire, we start seeing 401 responses, but in identity server we can see the session still exists and seems to be fine. On the client we then need to refresh and click the login button in order to get a new access token.

We enabled logs using the below code, but did not see anything in the output related to either library.

```csharp
services.AddLogging(options =>
{
    options.AddFilter("IdentityModel", LogLevel.Debug);
    options.AddFilter("Duende", LogLevel.Debug);
});
```

**Comment by brockallen** [comment]
The tokens (access and refresh) are kept as part of the user's session in the client app. If you set its session to 10m, then it will expire, there will no longer be a session cookie, and those tokens will be gone. So yes, it makes sense that you get a 401 after that. And that session lifetime is separate from the user's session at IdentityServer.

**Comment by leastprivilege** [comment]
So to answer your original question - the access token gets refreshed automatically - but only for as long as you have a valid session in your BFF. By default the refresh token even gets invoked when the session expires (which is typically exactly what you want).

**Comment by forrestab** [comment]
Thanks, looks like its combination of misunderstanding and the lifetime lengths we are testing with.
