### ISSUE TITLE
Recommended scope for Dynamic providers implementation

### ISSUE THREAD

**Issue by laki889** [DuendeSoftware/Support#1151]
Hi everyone. I’m upgrading project I’m working on from IdentityServer4 and .NET Core 3 to Identity Server 7 and .NET 8. 
Also, I’m working on implementation of dynamic providers.

I first implemented JSON storage for dynamic providers and now I’m moving that to EF storage.
I made it work but I have a question.

I created a service (named MyDynamicProvidersStore) which implements the interface required by Rsk.DynamicProviders extension. I created a new table inside already exisitng ApplicationDbContext. It’s important to mention that I’m not using ConfigurarionDbContext at all, since all resources are defined in JSON files (legacy from IS4) and I don’t want to change that.

So, I have a service that I must to register as Singleton because of IAuthenticationSchemeProvider (part of Authentication midllware of .NET) - that component used IAuthenticationProviderStore.
When I did that, services couldn’t start because my ApplicationDbConext (one in which I have custom table for dynamic providers) is registered as scoped service. So, singleton can’t consume scoped.
I overcome this by creating ApplicationDbContext via scoped factory inside MyDynamicProviderStore. Now, services can start, dynamic providers works fine.

Question 1: Is this approach recimmended and valid? Will this create some performance issues?
If this is not ok, can you suggest a better way to do it?

Question 2: How can I introduce caching when using custom table with EF storage for dynamic providers? Will scope factory influence caching?

**Comment by josephdecock** [comment]
Broadly, the idea of a singleton factory that can create scoped contexts is a good one. There are some implementation details to get right, so refer to the microsoft guidance around DI and DBContext lifetimes [here](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#dbcontext-in-dependency-injection-for-aspnet-core).

I'm not as familiar with RSK's extensions, so please check with them about their extension methods. 

IdentityServer itself includes dynamic providers as a feature in our enterprise license. If you were using that feature, and using our EF based implementation of the provider stores, you can add caching with AddIdentityProviderStoreCache - see [here](https://docs.duendesoftware.com/identityserver/v7/data/configuration/#caching-configuration-data).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
