### ISSUE TITLE
Question: What is the recommended way to redirect back to client while preserving the original URL that started the login?

### ISSUE THREAD

**Issue by ldavisCEI** [DuendeSoftware/Support#1153]
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**
8

**Describe the bug**
Not a bug, but a question.

**Example scenario**
1. an unauthenticated user in a client app clicks a link to an area of the site that is restricted.
2. the user is redirected to the Duende IdentityServer
3. the user doesn't have an account so they click a link to create an account back in the client app

**Question**
How do you recommend navigating back to the client app (to create an account or something else) so that it includes the URL they clicked in step 1 above?

**Why this is helpful**
Having the URL the user clicked in step 1 allows the site to continue where they left off before having to create an account, for example.

**Additional context**
Ideally, we wouldn't redirect back to the client app at all but would have the account creation in Duende IdentityServer. We want to avoid this, if possible, to limit the scope of what needs migrated.

**Comment by RolandGuijt** [comment]
You could call DenyAuthorizationAsync on the InteractiveService object. See [here](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v7/Basics/IdentityServer/src/Pages/Account/Login/Index.cshtml.cs) for example.
On the client you can then set an accessdenied path in the oidc configuration e.g.:

options.AccessDeniedPath = "/account/accessdenied";

That path will be called with the returnUrl as a query string.

Note that the new account should eventually be created in the user store that the identity provider uses because else there's no way to login.

**Comment by ldavisCEI** [comment]
Thanks Roland for the help! 

Is there a similar setting for a .NET Framework 4.8 client using Owin?

This works great for a .NET 8 client. You can even change the `options.AccessDeniedPath` at runtime based on the `ErrorDescription` if needed. Here is an example in case it helps someone else.

```
options.Events.OnMessageReceived = context =>
{
	context.Options.AccessDeniedPath = context.ProtocolMessage switch
	{
		{ Error: "access_denied", ErrorDescription: null } => "/account/accessDenied",
		{ Error: "access_denied", ErrorDescription: "no account" } => "/account/registration",
		_ => context.Options.AccessDeniedPath
	};
	return Task.CompletedTask;
};
```

**Comment by RolandGuijt** [comment]
You're welcome and thanks for the addition!

For Owin you could try handling the AuthenticationFailed event described [here](https://learn.microsoft.com/en-us/previous-versions/aspnet/mt180967(v=vs.113)).
I'm closing this for now, but feel free to reopen if you have any further questions.

**Comment by ldavisCEI** [comment]
I'm getting to inside the `AuthenticationFailed` handler in Owin. The problem is I cannot find a property to set that would be similar to `options.AccessDeniedPath` over in .NET 8. 

Which property in `AuthenticationFailed` do I need to set to "/account/accessDenied" or "/account/registration"? Is it a property on [OpenIdConnectAuthenticationOptions](https://learn.microsoft.com/en-us/previous-versions/aspnet/dn800268(v=vs.113))?

**Comment by RolandGuijt** [comment]
You'll have to handle the event and do the redirect yourself as there is no property that is similar.

**Comment by RolandGuijt** [comment]
I did some searching, but there doesn't seem to be a way to get it from the context that is provided by the handler.

**Comment by ldavisCEI** [comment]
Thanks for your help Roland! It is nice to know I'm not overlooking something.
