### ISSUE TITLE
idsrv and idsrv.session cookies blocked on signin-oidc call

### ISSUE THREAD

**Issue by MSDev52** [DuendeSoftware/Support#1156]
**Which version of Duende IdentityServer are you using?**
IdentityServer4.00
**Which version of .NET are you using?**
4.8

**Describe the bug**
idsrv & idsrv.session cookies are blocked on the signin-oidc call:

![BlockedCookies](https://github.com/DuendeSoftware/Support/assets/162382268/4c1660ba-8671-433b-8a82-fdf46546750c)
Using Chrome I am able to authenticate but I find these cookies blocked with the following message:
'The cookie was blocked because it's path was not an exact match for a super directory or the request URL's path.

**To Reproduce**

Place your client and IDS implementation behind a reverse proxy and attempt login.

**Expected behavior**

Cookies expected to be allowed.

**Log output/exception with stacktrace**
Nothing in the log regarding this.
```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
IdentityServer4 is no longer supported. This forum is for users of Duende IdentityServer, so please [get in touch](https://duendesoftware.com/contact) to get a [license](https://duendesoftware.com/products/identityserver#pricing).

Having said that, you can look [here](https://docs.duendesoftware.com/identityserver/v7/deployment/proxies/) to solve problems with proxies.
Also: It looks like IdentityServer's cookies have a specific path set. You can try removing that from your config.

**Comment by RolandGuijt** [comment]
Closing for now. But feel free to re-open if there are more questions.
