### ISSUE TITLE
Extra space after closing </a> tag

### ISSUE THREAD

**Issue by RacerDelux** [DuendeSoftware/Support#1157]
**Which version of Duende.AccessTokenManagement are you using?**
2.1.0

**Which version of .NET are you using?**

.net 8

In the "Web" sample there is an extra space on line 9 of samples/Web/Views/Home/Index.cshtml.

Steps to reproduce the behavior.

No steps required, Rider will complain about the extra space on load.

There should be no syntax errors on project load after pulling it from git.

**Additional context**

The fix is to simply change `<a/ >` to `<a/>` at the end of line 9 in samples/Web/Views/Home/Index.cshtml.

**Comment by brockallen** [comment]
@RolandGuijt Can you investigate and propose a PR to address? Thanks.

**Comment by RolandGuijt** [comment]
I've created a PR. Thanks for reporting this @RacerDelux.

**Comment by RacerDelux** [comment]
Thanks for the speedy fix @RolandGuijt!
