### ISSUE TITLE
What is the best way to pass the language (UI culture) selected by the user to IdentityServer?

### ISSUE THREAD

**Issue by MarSobota** [DuendeSoftware/Support#1159]
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**
8

**Question**

I'm running sample projects (WeatherMVC) and would like to display the login page in IdentityServer in a specific language (chosen by the user in the client application). What are the options for implementing this?

**Comment by RolandGuijt** [comment]
The OpenIdConnect standard defines a way to pass on culture information to the IdP by using ui_locales.

Here's how to pass that string to the IdP using Microsoft's OpenIdConnect middleware:

```
            services.AddAuthentication(options =>
            {
                ..
                option.AddOpenIdConnect("oidc", options =>
                {
                    options.Events.OnRedirectToIdentityProvider = (c) =>
                    {
                        c.ProtocolMessage.UiLocales = "fr-CA";
                        return Task.CompletedTask;
                    };
```

The ProtocolMessage object represents the request going to the IdP. As you can see it has the UiLocales property.

On the IdentityServer side e.g. in the controller responsible for the login GET request, the locale can be extracted by getting the authorization context:

```
        var context = await _interaction.GetAuthorizationContextAsync(returnUrl);
        var uiLocales = context.UiLocales;
```
