### ISSUE TITLE
Open Id Connect Authentication providers not working due to bug in referenced package

### ISSUE THREAD

**Issue by pallesaphe** [DuendeSoftware/Support#1164]
**Which version of Duende IdentityServer are you using?**
7.0.1
**Which version of .NET are you using?**
8.0
**Describe the bug**
When trying to use Open Id Connect Authentication providers like Google and Azure Ad, it fails with the following exception after returning a ChallengeResult:
InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid. 
Version 6 of IdentityServer did not have this problem.

The problem seem to be related to a bug introduces in Microsoft.IdentityMode.Protocols.OpenIdConnect version 7 (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2402), which results in the .well-known/openid-configuration not being deserialized correctly. And since Version 7.0.1 of identity server is build with a reference to Microsoft.AspNetCore.Authentication.OpenIdConnect (8.0.0), which in turn references Microsoft.IdentityMode.Protocols.OpenIdConnect (7.1.2), the bug is introduced. 

Forcing our projekt to use Microsoft.IdentityMode.Protocols.OpenIdConnect 7.4.0 fixed the issue. So IdentityServer should perhaps be build with updated dependencies.

**To Reproduce**

Use AddOpenIdConnect to add providers and try to login. It worked in version 6 of identity server without external packages but not in version 7 due to the referenced package has a bug.

Reference Microsoft.IdentityMode.Protocols.OpenIdConnect version 7.4.0 from the project, and the issue is gone.

**Expected behavior**

**Log output/exception with stacktrace**

```
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationHandler<TOptions>.ChallengeAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in MutualTlsEndpointMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in DynamicSchemeAuthenticationMiddleware.cs
Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in BaseUrlMiddleware.cs
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Additional context**

**Comment by RolandGuijt** [comment]
With SameSite cookies the cookie will only be sent by the browser from the same site the cookie came from. (when using the "lax" setting there is an exception for GET requests)
A "site" here most of the time is the combination of the domain suffix and the part of the domain just before it. For example: [www.duendesoftware.com](http://www.duendesoftware.com/) is the same site as [test.duendesoftware.com](http://test.duendesoftware.com/). Using that logic localhost:4323 is the same site as localhost:1453 so that's why it probably works on a local dev machine.

Let's say the BFF host runs on [bff.somesite.com](http://bff.somesite.com/).
That means that when the BFF host sets the authentication cookie the browser will only send it when the [somesite.com](http://somesite.com/) site is in the browser's address bar.
So to get it to work both the SPA and the BFF host endpoints must be hosted on the same site.

Is that the case in your situation?

It can either be accomplished by embedding a production build of the Angular application in your BFF host or by using a reverse proxy. Since testing in the former could be an issue I personally prefer the latter. A way to do it is to use [Yarp](https://microsoft.github.io/reverse-proxy/). Duende BFF is using that already to handle calls from the SPA to external APIs. It could be a hassle to configure it correctly manually though. To make things easier you can take a look at [SpaYarp](https://github.com/berhir/AspNetCore.SpaYarphttps://github.com/berhir/AspNetCore.SpaYarp).

**Comment by AndersAbel** [comment]
This is an unfortunate effect of how the references to the `Microsoft.IdentityModel` packages are resolved, combined with the fact that those packages must be on the same version even though that is not expressed in the Nuget dependency information.

As a library we only put a minimum version requirement on our dependencies to give the application developers using our library the freedom to use the versions they require. This is also what is generally recommended for library authors to do.

The end result of the discussion in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2402 was that they are looking into ways to give compile time errors/warning if there are version mismatch between different `Microsoft.IdentityModel` packages. I think that that is the right solution - that library needs to handle it's internal version dependency coupling, it's nothing we can do in IdentityServer.

**Comment by AndersAbel** [comment]
We've added some more information on how to diagnose and fix Microsoft.IdentityModel versioning issues to our docs page: https://docs.duendesoftware.com/identityserver/v7/troubleshooting/wilson/

I'm closing this issue now, but if there are any more specific questions please feel free to reopen.
