### ISSUE TITLE
Token flow on behalf of user across multiple clients

### ISSUE THREAD

**Issue by ryanlangton** [DuendeSoftware/Support#1165]
**Which version of Duende IdentityServer are you using?**
6.1.5

**Which version of .NET are you using?**
6

**Describe the bug**
I'm attempting to implement authentication across multiple clients that all need access to the same back end API in the context of a logged in user to do offline work but am running into roadblocks when implementing. We don't want to pass access tokens across system boundaries, yet refresh tokens do not work for different clients.  

System A (API) - the secured data source, System B and C both need access to this API.
System B (UI) - user logs in to system B, get's a token from identity server that gives them access to System A as long as they have an  interactive session. Logged in user triggers the workflow for System C.
System C (back-end) - this system "does the work" at a later time and needs access to System A (API) as if it were the logged in user.

It seems that refresh token's are [not designed to be passed across system boundaries](https://github.com/IdentityServer/IdentityServer4/issues/3446).
When I try to exchange the refresh token for an access token in System C I get an error that the token does not belong to my client.
What is the correct way to design this workflow?

The [TokenExchangeGrantValidator](https://docs.duendesoftware.com/identityserver/v6/tokens/extension_grants/token_exchange/) is failing on these lines of code.

```
var validationResult = await _validator.ValidateAccessTokenAsync(subjectToken);
if (validationResult.IsError)
      return;
```

**Comment by ryanlangton** [comment]
The [TokenExchangeGrantValidator](https://docs.duendesoftware.com/identityserver/v6/tokens/extension_grants/token_exchange/) is failing on these lines of code. I suppose I could edit this out of the exchange, but it seems like that would be violating the intent of the design.

`        var validationResult = await _validator.ValidateAccessTokenAsync(subjectToken);
        if (validationResult.IsError)
            return;
`

**Comment by ryanlangton** [comment]
After more research and testing on this I'm wondering if System C should only have knowledge of the ID of the user, then use client credentials to get a token, followed by a token exchange to impersonate the user. Instead of passing a token from System B -> System C we would only be passing the user ID. Does this sound like a good solution?

**Comment by RolandGuijt** [comment]
Yes. 
The communication from System C to A is a typical case of machine-to-machine communication. [Client credentials](https://docs.duendesoftware.com/identityserver/v7/quickstarts/1_client_credentials/) flow is suitable for that.

With client credentials flow C can obtain an access token for itself and communicate with A.
I assume that C is triggered to do work with some data (read from a queue or something like that). Part of that data could be user data like user id so C knows who initiated the work.
This assumes that C is a trusted system and that the user info it gets can be trusted too.

**Comment by ryanlangton** [comment]
Thank you. I changed the workflow to the client credentials flow and pass the user ID through a message, this works and meets our needs.

**Comment by narbit** [comment]
Just ran across this looking for solution to another issue. I know it's old and closed but wanted to comment that this scenario might be a good candidate for token delegation (on-behalf-of) grant - https://docs.duendesoftware.com/identityserver/v7/tokens/extension_grants/token_exchange/#token-exchange-for-impersonation-and-delegation

Passing user ID separately from the token invites for IDOR vulnerability :)
