### ISSUE TITLE
Class IdentityResourceMapperProfile no longer exists 

### ISSUE THREAD

**Issue by LiparAljaz** [DuendeSoftware/Support#1168]
**Which version of Duende IdentityServer are you using?**
Error happened when we changed/updated our version of Duende(And all NuGets that are from Duende) from 6.2 first to 6.3 and later to 7.0. So current version is 7.0

**Which version of .NET are you using?**
The project has just been upgraded to .NET8

**Describe the bug**
When we were using your previous versions of Duende we were using AutoMapper and we added it in the following way
Duende Version 6.2

File: HostingExtensions

builder is a `WebApplicationBuilder`

Lines:

```csharp
        builder.Services.AddAutoMapper(typeof(AutoMappingProfiles), typeof(IdentityResourceMapperProfile));
```

In this version we were using the class you provided called `IdentityResourceMapperProfile`. This class was in `Duende.IdentityServer.EntityFramework.Mappers;`. 

The contents of the mentioned class were as follows.

```csharp
  // Copyright (c) Duende Software. All rights reserved.
  // See LICENSE in the project root for license information.
   
   
  using System.Collections.Generic;
  using AutoMapper;
   
  namespace Duende.IdentityServer.EntityFramework.Mappers;
   
  /// <summary>
  /// Defines entity/model mapping for identity resources.
  /// </summary>
  /// <seealso cref="AutoMapper.Profile" />
  public class IdentityResourceMapperProfile : Profile
  {
      /// <summary>
      /// <see cref="IdentityResourceMapperProfile"/>
      /// </summary>
      public IdentityResourceMapperProfile()
      {
          CreateMap<Duende.IdentityServer.EntityFramework.Entities.IdentityResourceProperty, KeyValuePair<string, string>>()
              .ReverseMap();
   
          CreateMap<Duende.IdentityServer.EntityFramework.Entities.IdentityResource, Models.IdentityResource>(MemberList.Destination)
              .ConstructUsing(src => new Models.IdentityResource())
              .ReverseMap();
   
          CreateMap<Duende.IdentityServer.EntityFramework.Entities.IdentityResourceClaim, string>()
              .ConstructUsing(x => x.Type)
              .ReverseMap()
              .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src));
      }
  }

```

after the upgrade to Duende version 6.3 and later version 7.0 the beforementioned class simply stopped existing and was never documented nor replaced with something similar. Since we depend on the beforementioned class we would like to know how and/or in what capacity it was replaced.

Before the removal of said class our endpoints for POST/PUT such as  /ApiResource and /ApiScope worked fine. After the update the mapping for said endpoints does not work since the class `IdentityResourceMapperProfile` no longer exist and the new code looks as follows so that the program compiles.

```csharp
        builder.Services.AddAutoMapper(typeof(AutoMappingProfiles));
```

**To Reproduce**

As mentioned the class `IdentityResourceMapperProfile` existed in Duende version 6.2 (.NET6 at the time) and then no longer existed when Duende was upgraded from 6.2 --> 6.3(error first appeared here) --> 7.0. Lines of code provided in "Describe the bug"

**Expected behavior**

Expected our endpoint mappings to be correct but no longer work after the class no longer exists.

**Log output/exception with stacktrace**

```
 "type": "UnhandledSystemException",
  "title": "Missing type map configuration or unsupported mapping.\r\n\r\nMapping types:\r\nApiResource -> ApiResource\r\nDuende.IdentityServer.Models.ApiResource -> Duende.IdentityServer.EntityFramework.Entities.ApiResource",
  "status": 500
```

**Additional context**

When trying to make custom mappings work we managed to  figure out trough debug that when mapping happens id is not mapped from Duende.IdentityServer.EntityFramework.Entities.ApiResource to Duende.IdentityServer.Models.ApiResource

**Comment by RolandGuijt** [comment]
We removed the AutoMapper dependency in recent versions. The class you are mentioning was used internally by IdentityServer and now that the dependency is gone we also removed the class. Allthough the class was public but was not intended to be used outside of the product.
Since your are still using AutoMapper, the way forward is to use mapper classes managed by you and/or your team.
