### ISSUE TITLE
I added some custom claims to the openid, but only one appears in the requested access token, the others don't exist

### ISSUE THREAD

**Issue by SpiritLing** [DuendeSoftware/Support#1169]
**Which version of Duende IdentityServer are you using?**

7.0.0

**Which version of .NET are you using?**

.Net 8

**Describe the bug**

I added some custom claims to the openid, but only one appears in the requested access token, the others don't exist

**To Reproduce**

1. set openid claims to database

![image](https://github.com/DuendeSoftware/Support/assets/26963582/838b3628-5748-4e53-bad2-cb03da72cc66)

2. insert data

![image](https://github.com/DuendeSoftware/Support/assets/26963582/101af6c2-c607-4722-a881-73f4397d9ffc)

3. access token request

![image](https://github.com/DuendeSoftware/Support/assets/26963582/6c7e69a0-bc31-4508-a120-15c3de96e0f6)

**In the end, the only access token that appears is the client_id claim, but nothing else.**

**Comment by SpiritLing** [comment]
@RolandGuijt Thank you for your answer.

The scope of the client's request is: openid profile email phone etc., but as mentioned above, there is no email related information in the access token.

It gives me the impression that even if the request scope contains email, it doesn't exist in the access token.

The problem we're having is that we want to store some customized data in the access token for the gateway to read and use.

> Note that if you need certain claims added to the access token you'll need to add them to the ApiScopeClaims table. Here too adding sub is not needed as this is added automatically.

If I need to implement what I'm saying about storing data in access tokens, should that be handled through ApiScope?

**Comment by RolandGuijt** [comment]
All the claims of the identity scopes (like email, phone etc.) requested will end up in the identity token only, which is requested with the openid scope. 
If you want certain claims (not scopes) added to the access token you should add them to the ApiScopeClaims table I mentioned.
Does that answer your question?

**Comment by SpiritLing** [comment]
@RolandGuijt  Thank you very much for your answer.

This reply has solved my problem, thank you again!😄

**Comment by bomner** [comment]
> openid is a scope reserved to get an identity token which will contain the sub claim. Other claims should go in a different scope.
> 
> I would recommend using the "profile" standard scope for the username using the standard "name" claim. And perhaps a "role" scope for the "is_root" claim.
> 
> Please refer to [this part](https://docs.duendesoftware.com/identityserver/v7/fundamentals/resources/identity/) of the documentation for more information about identity scopes. Note that if you need certain claims added to the access token you'll need to add them to the ApiScopeClaims table. Here too adding sub is not needed as this is added automatically.

If I create a new scope lets call it "UserPermission". Is there a way to use some kind of wildcard to include all user claims? Issue I am having is that user in my application will have more than 50 claims, and we will be always adding new claims with each new feature and actions we create, so updating identity server scope every time we create new claim is not what I would like to do...
