### ISSUE TITLE
Logout doesn't completly end session, login doesn't allow for another user to log in 

### ISSUE THREAD

**Issue by theorska** [DuendeSoftware/Support#117]
**Which version of Duende BFF are you using?**

Duende.BFF 1.1.3

**Which version of .NET are you using?**

6.0

**Describe the bug**

This is not a bug, but probably some misconfiguration on my side. I am using Javascript application with a backend. I initiate a logout to the BFF backend. It redirects to the Identity Provider and returns with a successful login and redirects back to the Javascript page. When I try to log in, the BFF sends the login request to the Identity Provider and logs in the same user that I just logged out, without asking for any user information. My goal is so that another user can log in at this point, but some part of the framework remembers the previous user and doesn't clear up the session completely

**To Reproduce**

Here I will show you my relevant configurations
Client:
```
// JavaScript BFF client
new Client
{
    ClientId = "bff",
    ClientSecrets = "secret",
    AllowedGrantTypes = GrantTypes.Code,

    // where to redirect to after login
    RedirectUris = { redirect_url + "/signin-oidc" },

    //BackChannel
    BackChannelLogoutUri = redirect_url + "/bff/backchannel",
    BackChannelLogoutSessionRequired = true,

    // where to redirect to after logout
    PostLogoutRedirectUris = { redirect_url+ "/signout-callback-oidc" },

    AllowedScopes = new List<string>
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        IdentityServerConstants.StandardScopes.Email,
    },
    AlwaysSendClientClaims = true,
    AlwaysIncludeUserClaimsInIdToken = true,
    UpdateAccessTokenClaimsOnRefresh = true,
}
```

Identity Provider:
```
builder.Services
    .AddIdentityServer(options =>
    {
        options.Events.RaiseErrorEvents = true;
        options.Events.RaiseInformationEvents = true;
        options.Events.RaiseFailureEvents = true;
        options.Events.RaiseSuccessEvents = true;

        // see https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
        options.EmitStaticAudienceClaim = true;
    })
     .AddConfigurationStore(options =>
     {
         options.ConfigureDbContext = b => b.UseMySql(connectionString, serverVersion, sql => sql.MigrationsAssembly(migrationsAssembly));
     })
    .AddOperationalStore(options =>
    {
        options.ConfigureDbContext = b => b.UseMySql(connectionString, serverVersion, sql => sql.MigrationsAssembly(migrationsAssembly));
    })
    .AddAspNetIdentity<ApplicationUser>();
```

BFF configuration:
```
builder.Services.AddBff(options =>
{
    options.EnforceBffMiddleware = true;
    options.BackchannelLogoutAllUserSessions = true;
})
    .AddRemoteApis()
    .AddServerSideSessions();

JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "Cookies";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
})
.AddCookie("Cookies", options =>
{
    options.Events.OnSigningOut = async e =>
    {
        // automatically revoke refresh token at signout time
        await e.HttpContext.RevokeUserRefreshTokenAsync();
    };
})
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = identity_url;
    options.ClientId = "bff";
    options.ClientSecret = "secret";
    options.ResponseType = "code";

    options.SaveTokens = false;
    options.GetClaimsFromUserInfoEndpoint = true;
});
```

**Expected behavior**

The user proceeds to log in. Enters credentials and is forwarded back to the application.
The user initiates logout and it happens successfully.
Another user initiates log in and enters log in credentials and is forwarded to the application.

Current behavior:
The user proceeds to log in. Enters credentials and is forwarded back to the application.
The user initiates logout and it happens successfully.
The second user initiates log in and the previous user is authenticated and the user is now logged in, without seeing the enter credentials form of Identity Provider.

**Log output/exception with stacktrace**

```
data
```

**Additional context**

As I have mentioned this is probably some configuration error from my side, if you need more information to figure it out I am happy to provide it.

**Comment by leastprivilege** [comment]
Can you re-produce that with one of our samples?

e.g.
https://docs.duendesoftware.com/identityserver/v6/samples/bff/#javascript-frontend

?

**Comment by theorska** [comment]
Yes, I will try to re-produce it. In this example https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Quickstarts/6_JS_with_backend it works as expected, I see the login screen after logging out with bob and I can log in with alice.  The current difference between this and my project is ASPNET Identity and persistent storage. I will add these to the quickstart and I will get back to you with the results.
