### ISSUE TITLE
SSL rewrites when using application gateway

### ISSUE THREAD

**Issue by danlarson** [DuendeSoftware/Support#1172]
**Which version of Duende IdentityServer are you using?**
7.0

**Which version of .NET are you using?**
8.0

**Describe the bug**
When fronting IdentityServer hosted in AKS, with ApplicationGateway handling the SSL -- IdentityServer responds with HTTP endpoints in the discovery document. How do I configure this to write the correct URL? 

**To Reproduce**
Host identityserver behing a gateway that handles SSL.
We have an instance running here: https://[auth.dev-zynexmonitoring.com/.well-known/openid-configuration](https://auth.dev-zynexmonitoring.com/.well-known/openid-configuration)

**Expected behavior**
Expected a way to have the disco document know to use https URLs. Perhaps configuration we missed? 

n/a

**Comment by RolandGuijt** [comment]
Most likely this can be solved by adding the ForwardedHeaders middleware. In that way the scheme is preserved.

You can find a detailed explanation [here](https://docs.duendesoftware.com/identityserver/v7/deployment/proxies/).

**Comment by danlarson** [comment]
Thanks Roland! That did it.
