### ISSUE TITLE
Support for PolicyScheme in front of Duende

### ISSUE THREAD

**Issue by staldera** [DuendeSoftware/Support#1173]
**Which version of Duende BFF are you using?**

2.2.0

**Which version of .NET are you using?**

8.0.200

**Describe the bug**

Using a PolicyScheme in front of Duende requires hacky workarrounds. We currently have two authentication schemes on our BFF, one for our users (standard cookie + oidc) and one for machine-to-machine (client credentials). To make this work, we use a PolicyScheme, with a code looking like this:

```
var authenticationBuilder = builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "default";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
});

authenticationBuilder.AddPolicyScheme("default", AuthenticationConstants.DefaultDisplayName, x => x.ForwardDefaultSelector = httpContext =>
{
    return httpContext.SelectAuthenticationScheme("cookies", token =>
    {
        if (token.Audiences.Any(aud => aud.Contains(builder.Configuration.GetRequiredValue<string>("OtherAzureAd:ClientId"), StringComparison.OrdinalIgnoreCase)))
        {
            return "clientcredentials";
        }

        return "cookies";
    });
});

authenticationBuilder
    .AddCookie("cookies", options =>
    {
        options.Cookie.Name = "__Host-WebBff";
        options.Cookie.SameSite = builder.Configuration.EnableSameSiteStrict()
            ? SameSiteMode.Strict
            : SameSiteMode.None;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
    })
    .AddOpenIdConnect("oidc", options =>
    {
        builder.Configuration.Bind("AzureAd", options);
        options.SignInScheme = "cookies";
    });
authenticationBuilder.AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("OtherAzureAd"), jwtBearerScheme: "clientcredentials");
```

First issue we noticed is that this removes server-side sessions, because `PostConfigureApplicationCookieTicketStore` checks if the cookie scheme is the default scheme. This forced us to manually add a copy of the class that doesn't have this check:
```
// This line is required if the DefaultAuthenticateScheme (if provided) or DefaultScheme doesn't match the Cookie scheme name
builder.Services.AddSingleton<IPostConfigureOptions<CookieAuthenticationOptions>, ForcePostConfigureApplicationCookieTicketStore>();
```
Where `ForcePostConfigureApplicationCookieTicketStore` is a copy of `PostConfigureApplicationCookieTicketStore` with this method changed:
`public void PostConfigure(string? name, CookieAuthenticationOptions options) => options.SessionStore = new TicketStoreShim(_httpContextAccessor);`

This could probably be solved by allowing the user to pass the cookie scheme name to `AddServerSideSessions` / `AddEntityFrameworkServerSideSessions`.

Second issue is that the config in `AddAuthentication` is the only way to make sign-out work properly, which is kinda weird to me, and only works because my other scheme doesn't need to support sign-out. I would expect that the following works:
- Set only `DefaultScheme` in `AddAuthentication`
- Use `ForwardChallenge` and `ForwardSignOut` in `AddCookie`, or just set `SignOutScheme` in `AddOpenIdConnect`

Sadly if I do, sign-out doesn't properly work anymore. From my investigations, this is because in order for it to work, both of the following methods need to be called:
- `HandleSignOutAsync` on `CookieAuthenticationHandler` which clears the cookie and session db entry
- `SignOutAsync` on `OpenIdConnectHandler` which asks the user from which account he wants to log out of (important, otherwise, on next page display the app just silently logs in again)
Those are indirectly called by the method `SignOut` on `BffAuthenticationService`, which is called twice per logout (more with redirects, but that's not necessarily a problem), once with scheme `"cookies"` and once with scheme `null`. With forwards, this always results in one being called, but not the other. I'm not really sure how that could be fixed though, because most of the logic is from Microsoft. 

Maybe the way I set this up also isn't the best, and I need some more clever splitting mechanism in my policy scheme, based on which operation (sign in, sign out, challenge, ...) we currently have.

**To Reproduce**

Use the given code with an SPA in front, try to log in and out, see the result.

**Expected behavior**

- Server-side sessions do not require a workarround
- There is a way to properly sign-out without "hard coding" the default sign-out scheme in `AddAuthentication`

**Log output/exception with stacktrace**

None

**Additional context**

None

**Comment by AndersAbel** [comment]
I prefer to describe the role of the BFF on an architectural level as a cookie-to-token transition layer. Technically it is implemented as a revere proxy, but it's main role in an architecture is not to be a generic reverse proxy or API gateway.

I think that the problems you are facing is because you are trying to use the BFF both as a cookie-to-token translation layer, but also let it be a generic API gateway.

My advice is to go back and revisit this on an architectural level. You could either put a separate API gateway for your client-credential clients side by side with the BFF, or let your BFF call your generic API gateway.

**Comment by staldera** [comment]
I'm not sure that's how most people would describe a BFF to be honest. A BFF is more than just a security layer, it's a service that provide endpoints to a frontend.
Simple counter-example, in the GraphQL world, an API gateway is exactly what the BFF is expected to be. It's the case for REST too, if you need to hit an endpoint with different auth schemes, you'd have the same problem. But with REST you can duplicate the endpoint and be done with it, so it's less noticeable.

In that usage, your suggestion basically means we'd have three options:
- Duplicate the BFF/API gateway for each authentication channel, even if they have the same GraphQL schema. That wouldn't make much sense, be it design, effort or maintenance wise, unless the GraphQL schemas becomes different.
- Have 3 services: a cookie-to-token "BFF" as well as a client cred "BFF" which are both in front of our API gateway. That would be doable and a bit more logical design-wise. But seems a bit overkill to me.
- Have a cookie-to-token "BFF" as well as the actual BFF that supports only tokens (users or creds) and also is the API Gateway. Less effort, but then it makes little sense that our standard use-case, where we have the most traffic, goes through the longest route.

Also, it's quite common to have multiple auth schemes side-by-side in .NET, so it's rather surprising to integrate Duende in the .NET authentication/authorization layer, but to be exclusive of other schemes IMHO.

**Comment by AndersAbel** [comment]
A BFF is a Backend For Frontend. It is meant to be a dedicated backend that is only used by one specific frontend application. The BFF should be hosted on the frontend app host to use cookies efficiently and in a secure way. If you have multiple frontend applications you would need multiple BFF instances, one for each frontend.

Option three in your list is the architecture that I would look into. It means the BFF can be a light weight component with a minimum of configuration. Then there's a separate API Gateway. I would not use the term BFF for that component.

**Comment by staldera** [comment]
Thanks for the feedback, we'll look into it
