### ISSUE TITLE
Tool to manage client id/secrets 

### ISSUE THREAD

**Issue by HaroonSaid** [DuendeSoftware/Support#1174]
We are having trouble creating a robust process for updating clients and secrets and distributing the secrets in the clear back to a secret store in AWS.
 
The process typically involves a DBA generating and adding the client and hashed secrets to the tables.
The secret is added to various AWS Secret Managers to ensure the calling application picks up value.  
 
Do you guys have UI-based tools to simplify data creation into Identity Server tables?

**Comment by StuFrankish** [comment]
There are no out-of-the-box UI tools within Identity Server itself.
However, you could look to using the [AdminUI by RSK](https://www.identityserver.com/products/adminui) or implement services and UI of your own to manage client secrets.

**Comment by fkfilip** [comment]
https://github.com/skoruba/Duende.IdentityServer.Admin

**Comment by josephdecock** [comment]
Dominick wrote a blog post a while back to summarize our thoughts on admin ui: https://blog.duendesoftware.com/posts/20220204_admin_ui/. The tl;dr is that we think a customized solution is the best thing to do if you really need a UI for configuring identity server. There are so many protocol options and identity server options, and you probably only use and want to allow configuration of a small subset of them. If you make a UI that lets you change literally anything, in practice that means that there is a big potential to mis-configure the options. 

On the roadmap into the future, we are intending to expand our configuration tooling, based around standards. Back in the 6.3 release, we added support for the dynamic client registration protocol, and in the future we intend to expand that support with dynamic client management support, and possibly other configuration endpoints.

**Comment by StuFrankish** [comment]
I'm not sure how I missed the QuickStart UI sample to be honest.
For the company I work for I wrote an entire client application and set of local APIs within our IdP host to manage things like users and clients with, as Dominick put, a limited subset of required functionality, backed by what I'm sure RSK would consider a misuse of `role` claims paired with policies! 

But maintaining that setup is becoming a bit of a hassle so hosting the management system within Identity Server is the next milestone for us, something I'm beginning to play with alongside WebAuthn for passkey support.

I'd be interested to see how things progress with the future extensibility options.

**Comment by AndersAbel** [comment]
Looks like we have an answer to the question so I'm closing it. Please feel free to reopen if anything more is needed.
