### ISSUE TITLE
Personal access token (PAT) suddenly stop working

### ISSUE THREAD

**Issue by gls-timelogger** [DuendeSoftware/Support#1176]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
.NET 6.0

**Describe the bug**

We have upgraded our IdentityServer4 from v4 to Duende v5. Upon inspecting the PersistedGrants table, we observed changes made to the reference_token type following the upgrade. Notably, the payload in the Data column is now encrypted. However, we've encountered instances where the reference_token suddenly stops working after approximately less than a month, despite being configured to expire in months. We're wondering what could be the possible root cause of the failure.

![image](https://github.com/DuendeSoftware/Support/assets/109647185/1787476f-dcdf-48ac-8d3f-a42589bad959)

**To Reproduce**

We are using the ITokenService.CreateSecurityTokenAsync to generate the reference_token

**Expected behavior**

It should respect the lifetime of the token we specified when generating it.

**Log output/exception with stacktrace**

```
[Error] Duende.IdentityServer.Stores.DefaultReferenceTokenStore: Failed to deserialize JSON from grant store.
System.Security.Cryptography.CryptographicException: The key {xxxxx-xxxx-xxx-xxx-xxxxxxx} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize[T](String json) in /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:line 102
   at Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync(String hashedKey) in /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:line 133
[Error] Duende.IdentityServer.Validation.TokenValidator: Invalid reference token.
TokenValidationLog { ClientId: null, ClientName: null, ValidateLifetime: True, AccessTokenType: "Reference", ExpectedScope: null, TokenHandle: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-1", JwtId: null, Claims: null }
[Information] Duende.IdentityServer.Events.DefaultEventService: TokenIntrospectionSuccessEvent { ApiName: "xxx", IsActive: False, Token: "****D7-1", ClaimTypes: null, TokenScopes: null, Category: "Token", Name: "Token Introspection Success", EventType: Success, Id: 2020, Message: null, ActivityId: "0HN28MFSRFFK4:00000003", TimeStamp: 03/20/2024 08:02:32, ProcessId: 33692, LocalIpAddress: "127.0.0.1", RemoteIpAddress: "::1" }
[Information] Duende.IdentityServer.Endpoints.IntrospectionEndpoint: Success token introspection. Token active: False, for API name: "xxx"
```

**Additional context**

We are consistently encountering JSON deserialization failures in our application logs.

**Comment by AndersAbel** [comment]
This is probably due to missing/incorrect configuration of Data Protection. Please see https://docs.duendesoftware.com/identityserver/v7/deployment/data_protection/ for information.

**Comment by gls-timelogger** [comment]
Thank you for the response. It seems this information should be included in the upgrade steps for transitioning from [IdentityServer4 v4 to Duende v5](https://docs.duendesoftware.com/identityserver/v5/upgrades/is4_v4_to_dis_v5/). Please consider this ticket resolved.
