### ISSUE TITLE
Question: secret limit on clients

### ISSUE THREAD

**Issue by danlarson** [DuendeSoftware/Support#1177]
**Which version of Duende IdentityServer are you using?** 7

**Which version of .NET are you using?** 8

**QUESTION**

Is there a limit to secrets per client? Are there performance limitations in using many secrets (100+) per client? 

We are using a client for medical devices, let's call it a Foo Monitor. Each physical Foo Monitor will have it's own private key emedded on a trust chip. The public key will be uploaded as a secret to the client, which is shared between all Foo Monitors. Is there and upper limit to secrets per clients? Microsoft identity (using Entra) has an upper limit of 500. If we use kids (key ids) on the jwk and jwt header, will that be used efficiently to load the secrets so it doesn't try hundreds of secrets? Any storage considerations, cosmos/nosql vs sql for this scenario? 

We plan on using JWKs and ECDSA signatures.

Thanks!

**Comment by RolandGuijt** [comment]
Apart from the memory and database limitations, there is no hard limit on the number of secrets per client. 

IdentityServer uses registered parsers implementing the ISecretParser interface to figure out the client id and secret of incoming requests. Out of the box there is the BasicAuthenticationSecretParser which uses the http header and the MutualTlsSecretParser for example.

A good place to start investigating how this works is by looking at the [ClientSecretValidator](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Validation/Default/ClientSecretValidator.cs). The default parsers are registered in DI [here](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Core.cs).

It's hard to determine if this mechanism will have a significant performance impact in your situation and on your hardware.
If there are performance problems I would suggest using just the parsers you need, removing the unnecessary ones and/or running performance tests on the parsers to figure out where the bottleneck is and optimize if possible.

One memory and performance issue could be that in the default implementation all client secrets are loaded from the EF store when the client is fetched. See [here](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework.Storage/Stores/ClientStore.cs).
You could reimplement that without the include for ClientSecrets and fetch the relevant secret(s) only (by adding a method to the new ClientStore e.g.). But keep in mind that the architecture with parsers and validators is designed to be a generic solution for many possible types of secrets. So you'll have to be careful not to break things for other secret types.

**Comment by AndersAbel** [comment]
@danlarson Do you have any additional questions or can we go ahead and close this issue?

**Comment by danlarson** [comment]
You can close it, thanks! We did a bit of testing and code spelunking, looks like it's not an issue but it could be optimized.  It does loop through all the secret kids with string compare but that's it as far as performance concerns.
