### ISSUE TITLE
key {009da8d4-6169-4fb8-aa56-534acef5abfb} was not found in the key ring Identity server 6.1

### ISSUE THREAD

**Issue by upadhyayvipul** [DuendeSoftware/Support#118]
I am getting the  exception after upgrading from V4 to 6.1

I have disabled the Automatic key management and adding key using AddSigningCredential in startup

System.Security.Cryptography.CryptographicException: The key {be6b5373-4e0e-4785-8512-e31a6599f251} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in //src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
at Duende.IdentityServer.Services.KeyManagement.KeyManager.b__20_0(SerializedKey x) in //src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435

**Comment by brockallen** [comment]
If you're not using the automatic key management, then do you have any records in the "Keys" table? If so, then you can delete those.

**Comment by upadhyayvipul** [comment]
I don't have a keys table. I am using .NET 6 on Windows so Keys are managed by  .NET CLR itself.

**Comment by brockallen** [comment]
> I am using Oracle to store operational data 

The keys table from the automatic key management is in the operational DB. If it has any records, and if those were created from different machines with different data protection, then this would explain the error. 

Also, keep in mind that data protection needs to be properly configured for IdentityServer (and really any ASP.NET Core web app):  https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by upadhyayvipul** [comment]
I have disabled the the automatic key managment

![image](https://user-images.githubusercontent.com/13015205/178441452-220b3d29-278c-4b10-ab17-3e0abf079d1a.png)

and loading signing key manually 
![image](https://user-images.githubusercontent.com/13015205/178441834-337d54c9-4e60-419c-89d7-e5bea238acf4.png)

do I still need "Keys" table?
Also every time it is searching for different key in Key Ring.

**Comment by brockallen** [comment]
> do I still need "Keys" table?

No -- I was just asking you to check in case you had accidentally run without disabling automatic key management.

 > Also every time it is searching for different key in Key Ring.
 
 What this really sounds like to me is that you don't have data protection configured, so your load balanced servers are somehow not able to unprotect data protected by the other. That's why I thought maybe there was an entry in the keys table prior to you disabling automatic key management, and that record might have been protected by some other data protection key.

**Comment by upadhyayvipul** [comment]
It was a problem with our release. Latest disabled Automatic Key was not deployed and couldn't replicate on local because local has latest code.
Thanks for the quick reply really appreciated
