### ISSUE TITLE
PII of type 'System.String' is hidden

### ISSUE THREAD

**Issue by KristinBethea** [DuendeSoftware/Support#1181]
**Which version of Duende IdentityServer are you using?** Multiple versions, currently upgrading to 7

**Which version of .NET are you using?** .NET 8

**Describe the bug** 
Error message stating
 Unable to obtain configuration from:  PII of type 'System.String' is hidden. 

A clear and concise description of what the bug is.|

When attempting to log into my Kentico website, with which we have Duende integrated, I get this error message, PII of type System.String is hidden. It gives me a link but the link is not helpful.  

**To Reproduce**

Just attempting to run it on my local machine to complete the upgrade

**Log output/exception with stacktrace**

```
Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)
InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
```

**Additional context**

It seems to happen randomly, which  makes it hard to reproduce. Either it happens and I can't work or it stops happening and I rush to get the work / testing done before it happens again.
I'd like to understand what is going on, if it is a bug and if anyone else is having this issue.

**Comment by RolandGuijt** [comment]
The message "PII of type "System.String" is hidden" comes from Microsoft's IdentityModel library used for claims based identity is hiding person identifiable information.

You can make it visible by adding this line of code:
`IdentityModelEventSource.ShowPII = true;`
But I would only recommend this setting when running in development mode.

Having said that the reason you're getting the "Unable to retrieve document" error is probably because of the fact that the discovery document doesn't return the correct JSON.
Can you try if you get back JSON if you access the discovery document with a browser? It is at https://[your identityserver url]/.well-known/openid-configuration .
If that returns JSON consistently there is something going on in the client application. It might not parse the JSON correctly for some reason. If you give me more details about the client we can look into it further in that case.

**Comment by KristinBethea** [comment]
What do you need to know about the client?

This is the JSON which only runs on my local of course 

{
    "issuer": "https://auth.tbg.org.develop",
    "jwks_uri": "https://auth.tbg.org.develop/.well-known/openid-configuration/jwks",
    "authorization_endpoint": "https://auth.tbg.org.develop/connect/authorize",
    "token_endpoint": "https://auth.tbg.org.develop/connect/token",
    "userinfo_endpoint": "https://auth.tbg.org.develop/connect/userinfo",
    "end_session_endpoint": "https://auth.tbg.org.develop/connect/endsession",
    "check_session_iframe": "https://auth.tbg.org.develop/connect/checksession",
    "revocation_endpoint": "https://auth.tbg.org.develop/connect/revocation",
    "introspection_endpoint": "https://auth.tbg.org.develop/connect/introspect",
    "device_authorization_endpoint": "https://auth.tbg.org.develop/connect/deviceauthorization",
    "backchannel_authentication_endpoint": "https://auth.tbg.org.develop/connect/ciba",
    "pushed_authorization_request_endpoint": "https://auth.tbg.org.develop/connect/par",
    "require_pushed_authorization_requests": false,
    "frontchannel_logout_supported": true,
    "frontchannel_logout_session_supported": true,
    "backchannel_logout_supported": true,
    "backchannel_logout_session_supported": true,
    "scopes_supported": [
        "openid",
        "profile",
        "email",
        "offline_access"
    ],
    "claims_supported": [
        "sub",
        "updated_at",
        "locale",
        "zoneinfo",
        "birthdate",
        "gender",
        "website",
        "picture",
        "preferred_username",
        "nickname",
        "middle_name",
        "given_name",
        "family_name",
        "name",
        "profile",
        "email",
        "email_verified"
    ],
    "grant_types_supported": [
        "authorization_code",
        "client_credentials",
        "refresh_token",
        "implicit",
        "password",
        "urn:ietf:params:oauth:grant-type:device_code",
        "urn:openid:params:grant-type:ciba"
    ],
    "response_types_supported": [
        "code",
        "token",
        "id_token",
        "id_token token",
        "code id_token",
        "code token",
        "code id_token token"
    ],
    "response_modes_supported": [
        "form_post",
        "query",
        "fragment"
    ],
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "subject_types_supported": [
        "public"
    ],
    "code_challenge_methods_supported": [
        "plain",
        "S256"
    ],
    "request_parameter_supported": true,
    "request_object_signing_alg_values_supported": [
        "RS256",
        "RS384",
        "RS512",
        "PS256",
        "PS384",
        "PS512",
        "ES256",
        "ES384",
        "ES512",
        "HS256",
        "HS384",
        "HS512"
    ],
    "prompt_values_supported": [
        "none",
        "login",
        "consent",
        "select_account"
    ],
    "authorization_response_iss_parameter_supported": true,
    "backchannel_token_delivery_modes_supported": [
        "poll"
    ],
    "backchannel_user_code_parameter_supported": true,
    "dpop_signing_alg_values_supported": [
        "RS256",
        "RS384",
        "RS512",
        "PS256",
        "PS384",
        "PS512",
        "ES256",
        "ES384",
        "ES512"
    ]
}

**Comment by RolandGuijt** [comment]
OK. Are you saying that when you run locally it works and it doesn't in deployed state?

Regarding the client: what kind of application is it and how have you configured OpenID Connect?
Have you set the boolean I mentioned to true already? That might give you hints about what's going on.

**Comment by KristinBethea** [comment]
It does **not** run locally. I haven't even been able to move it to a deployed state because of all the errors from the upgrade.

I have set the IdentityModelEventSource.ShowPII = true; 
I'll update when I get more information....

I suppose the kind of application is Kentico and I inherited the job so where do I find and how do I share how the OpenID connect is configured?


Thanks for all your help so far!! Truly!! :)

**Comment by RolandGuijt** [comment]
Not familiar with Kentico but it looks like it's using MVC 5 on OWIN.
There should be a startup class with the OpenID configuration.

**Comment by KristinBethea** [comment]
Like this?


```
public class IdpInitialConfig
{
    public static IEnumerable<Client> Clients( IConfiguration configuration )
    {
        var clients = configuration.GetSection( "IDPInitialConfig" ).GetChildren();

        foreach( var client in clients )
        {
            yield return new Client
            {
                ClientId = client.Key,
                ClientName = client.GetValue<string>( "name" ),
                AllowedGrantTypes = GrantTypes.Code,
                ClientSecrets = { new Secret( client.GetValue<string>( "secret" ).Sha256() ) },
                RedirectUris = { client.GetValue<string>("login-redirect") },
                PostLogoutRedirectUris = { client.GetValue<string>("logout-redirect") },
                AllowedScopes = new List<string>
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Email,
                    IdentityServerConstants.StandardScopes.Profile
                }
            };
        }
    }
```

**Comment by RolandGuijt** [comment]
This looks like the client config on the IdentityServer side. I was looking for the config on the client (Kentico) side.
Also, it's not clear to me when you see the JSON of the discovery document and when you don't. If you run locally and access the well known URL with the browser you see it? If so, does it work consistently?

**Comment by KristinBethea** [comment]
It seems that this error happens when the App Pool is not running.
Starting the local App Pool for IDP has worked consistently to fix this error.
I will close this issue. 😊😎
