### ISSUE TITLE
Is it possible to use KeyStore for other types of keys (Key.Use property)

### ISSUE THREAD

**Issue by fplorenzetti** [DuendeSoftware/Support#1182]
**Which version of Duende IdentityServer are you using?**
6.3.8

**Which version of .NET are you using?**
NET 8

**Question**
We are using the feature https://docs.duendesoftware.com/identityserver/v7/fundamentals/keys/ to manage IdentityServer SigningKeys and we would like to use the KeyStore infrastructure to store other types of Keys.

So, is it possible to use other `Key.Use`  type than `Signing` to have keys for different purposes?https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs#L63

We don't want to replace the default implementation for `ISigningKeyStore`, we want to add a new implementation of KeyStore using some kind of identifier

**Comment by RolandGuijt** [comment]
Can you give us a bit more information about what you are trying to do?
The key store is designed to hold signing keys that are used for token verification and end up in the discovery document.
Do you want other keys in the discovery document as well, if so what kind of keys?

**Comment by fplorenzetti** [comment]
We support more than one authentication method using different protocols. One of them is using SAML 2 as a Service Provider. So, we would like to store the certificates for signing SAML requests in the key store.

**Comment by RolandGuijt** [comment]
ISigningKeyStore is our store for loading key material used for signing tokens issued by IdentityServer. It's not designed as a general purpose store for other unrelated key material. 
There's a lot of work involved besides implementing an alternative key store if different protocols have to be supported.
For SAML 2, Rock Solid Knowledge's [SAML product](https://www.identityserver.com/documentation/saml2p/) could be used. It requires a paid license but it will probably save you tons of time doing research and dev work. Not to mention getting it battle tested.

**Comment by fplorenzetti** [comment]
Thanks for the information! I will check the SAML product. I am closing the issue.
