### ISSUE TITLE
Migration signing keys got different kid values

### ISSUE THREAD

**Issue by kamo93** [DuendeSoftware/Support#1185]
**Which version of Duende IdentityServer are you using?**
6
**Which version of .NET are you using?**
net6.0
**Describe the bug**

Not sure if its a bug, but when using `addSigningCredential(certificate, SecurityAlgorithms.RsaSha256)`, I'm getting a different `kid` that I'm getting on the old IDS3 with the same certificate. This will cause that we doing the migration the clients with the old token will not find the `kid`. Right now `kid` value i'm getting is the thumbprint.

**Expected behavior**

I will like the kid to be the same as x5t value not the thumbprint.

**Comment by AndersAbel** [comment]
It is possible to override the automatic kid generation:

```
var key = new X509SecurityKey(certificate);
key.KeyId = "My backwards compatible key id";

ar credential = new SigningCredentials(key, signingAlgorithm);
builder.AddSigningCredential(credential);
```

**Comment by RolandGuijt** [comment]
Does Anders' comment solve the problem? If so, I'd like to close.

**Comment by RolandGuijt** [comment]
Closing for now, but feel free to re-open if something comes up.
