### ISSUE TITLE
Remote API Cookies forwarding

### ISSUE THREAD

**Issue by neman-je** [DuendeSoftware/Support#1187]
**Which version of Duende BFF are you using?**
2.2.0

**Which version of .NET are you using?**
net6.0

**Describe the bug**
I am using BFF and I have a remote API mapped like this: 

```
builder.Services.AddBff().AddRemoteApis();
...
app.MapRemoteBffApiEndpoint("/api", $"{builder.Configuration["ApiURL"]}/api")
    .WithOptionalUserAccessToken();
```
When the frontend SPA sends a request, the .NET app that hosts the BFF receives the request with cookie. When the request is passed on to my remote API, the remote API receives the request without any cookies. 

According to the documentation, I implemented a custom HttpMessageInvokerFactory that implements custom HttpMessageInvoker. Now I started receiving cookie with the request in my RemoteAPI, but it is always the same value. Even if I send a request from the browser that does not have that specific cookie set, I get the cookie that was received in the first call after the app start. 

**To Reproduce**

```
builder.Services.AddSingleton<IHttpMessageInvokerFactory, CookiesForwardingInvokerFactory>();
...
public class CookiesForwardingInvokerFactory : DefaultHttpMessageInvokerFactory
    {
        public override HttpMessageInvoker CreateClient(string localPath)
        {
            if (localPath == "/api")
            {
                var client = Clients.GetOrAdd(localPath, (key) =>
                {
                    var handler = new SocketsHttpHandler
                    {
                        AllowAutoRedirect = false,
                        AutomaticDecompression = DecompressionMethods.None,
                        UseCookies = true, 
                        CookieContainer = new CookieContainer(),
                    };
                    return new HttpMessageInvoker(handler);
                });

                return client;
            }

            return base.CreateClient(localPath);
        }
    }
```

**Expected behavior**
I expect that I every time get the exact value of the cookie that was sent with the request, or no value if there is no cookie in browser. Not the same cookie value always. 

**Log output/exception with stacktrace**

**Additional context**

**Comment by RolandGuijt** [comment]
The purpose BFF host (the application where you call AddBff) is to take care of session management. Part of that is logging in and out. When a user logs in it will take care of the complexities around interacting with the identity provider. When that is done, depending on the flow used, an identity token and an access token are sent to the BFF host.

The BFF host will take the claims in the identity token and create the authentication cookie to send it to the browser. The access token will be stored on the BFF host.
Now when the browser want to access the API it has to do that through the BFF host (accessing /api/.. in your case). The BFF host will check if there is a logged in user (looking for the cookie) and will then forward the request to the API which needs a valid access token. The reason the request has to be done via the BFF Host is that the browser doesn't have the access token, but the BFF host has so it will attach it to the request it sends to the API and the result will be proxied back to the browser.

So the API doesn't need the cookie. That's the whole point of access tokens. With BFF the cookie should only be used between the browser and the BFF host.

For a more detailed explanation, take a look at our BFF [documentation](https://docs.duendesoftware.com/identityserver/v7/bff/) and/or our [samples](https://github.com/DuendeSoftware/BFF/tree/main/samples).

**Comment by neman-je** [comment]
Thank you for a detailed response and explanation @RolandGuijt 

I should have been more precise in describing a problem. I understand how BFF host works and what's the purpose, what I am trying to achieve here is to pass my custom token to the API. So, it is not authentication cookie used by BFF, but a cookie that my application sets and that should be passed to my API as a part of business requirement. 

To describe the situation a bit more, I have a scenario where unauthenticated users can access some pages of my web app. To establish some kind of a session for those users, I send a cookie with unique identifiers to them, and I need to get this cookie with every API request. What I could achieve until now, as I said, is to get a same cookie value every time my API receives a request, no matter which value is actually sent from browser, and if browser has a custom cookie set at all.

**Comment by AndersAbel** [comment]
Thank you for clarifying what you want to achieve.

While it makes perfect sense to have such a cookie in the client browser, I am not sure that it makes as much sense to have that as a cookie in the API call. Could the value instead be passed as part of the payload? Or as a custom headers?

Working with cookies in server-to-server-calls is something I would recommend to avoid. Cookies are useful for browsers because of the built in support for them. But for a client that can be controlled programmatically it is often easier to add data to the payload or add custom headers.

**Comment by RolandGuijt** [comment]
Does Anders' comment resolve the issue for you? If so I'd like to close.

**Comment by neman-je** [comment]
I apologize for delayed response. I spent quite some time trying to implement Anders' proposal because it perfectly makes sense. Unfortunately, I couldn't anyhow make LocalAPI work in my setup, and it was necessary for this implementation so eventually I gave up. 

I have solved the problem by switching to YARP for the reverse proxy functionality. 

You can close the ticket. I really appreciate your support.

**Comment by AndersAbel** [comment]
@neman-je I don't think "switching to YARP" is a bad thing at all. YARP is the proxy engine that is used by the BFF. We even do supply two configuration models. The simple one that configures both YARP and the proxy handling in one step. And the more powerful where you configure YARP yourself and then add token handling as a behaviour to the endpoints where that's needed.
