### ISSUE TITLE
Dynamic Providers and token encryption

### ISSUE THREAD

**Issue by Cephei** [DuendeSoftware/Support#119]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0

**Additional context**

@leastprivilege @brockallen 

My company is soon to be releasing in production our Duende-based solution with dynamic providers for oidc, saml, and wsfed identity providers. We have some customers requesting that we support saml encryption and I thought we may be able to leverage Duende's native `IKeyMaterialService` to support that effort.

As of now, Duende doesn't yet provide a separate abstraction, specifically for encryption certificates, but to achieve our purposes, couldn't we just reuse the `GetSigningCredentialsAsync` as a way to publish a public encryption certificate in our saml metadata for customer IdP's to use, as well as pull the private key from there for decryption purposes (when we receive an encrypted saml authn response)? Are there any concerns we should consider with this approach? It seemed beneficial to reuse Duende's key management so we could take advantage of the rotation features already in-place.

**Comment by Cephei** [comment]
As a service provider, we want to consume encrypted SAML AuthN responses from the identity provider. So their IdP would encrypt the message/assertions with our public key.

**Comment by Cephei** [comment]
Basically it would mean that whenever our certificate rollover occurs for signing outbound JWT tokens, our Dynamic Provider support for encryption would be rotated as well - our customer's identity providers would need to get our new public key via metadata refresh. For now, we just plan to support inbound-federated encrypted tokens with SAML-based IdP's.

**Comment by brockallen** [comment]
Ok, so another follow-up question: Do you plan to get these certs from our automatic key management, or from certs that you're manually configuring?

From a coding perspective, sure it could work that you call `GetSigningCredentialsAsync` and downcast the returned `SigningCredentials` to a `X509SigningCredentials` and then do all the work digging into that from there.

If you're adding the cert manually, then I'd almost suggest doing your own service in DI for this. If you want to use our automatic key management, then you're back to what I said above about working with the `IKeyMaterialService` as a leaky abstraction.
