### ISSUE TITLE
LogIn page for the mvc application

### ISSUE THREAD

**Issue by mysvrmt6** [DuendeSoftware/Support#1192]
**Which version of Duende IdentityServer are you using?**
7
**Which version of .NET are you using?**
.net 8 core
**Describe the bug**
followed the quickstarts from the Duende Software page. 
successfully worked - IdentityServer,API and Client console applications.

so, continued to setup the UI - .NET 8 Core web application.
getting the 404 error as follows: please advise
This localhost page can’t be foundNo webpage was found for the web address: https://localhost:5001/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dweb%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A5002%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%26code_challenge%3DcA75BapeDjtROD5rIY-ulfx4Vq5usII4JFPCHPinLLw%26code_challenge_method%3DS256%26response_mode%3Dform_post%26nonce%3D638475101690735028.NjY3NjJiZTUtOGY1Yi00MmQ0LWJiNjctNzhkMGI0MTlmY2U3ZjZlNzhiNmQtYTNiNS00YmIzLTg1MDktN2M3MzYyMjMzY2Y2%26state%3DCfDJ8J4b-N75LNtOqCHJGGRc8592BgHwC3ZLieOxRJ1eGmG6zmeuMKM0p17_zfrZ4LtJ7seYnfmqxFyoaHY4RmyA4ZH-L11IJMMneaRCqRPbZF0ia9j5tviy9T7R8uwc5yL4NTQ4tVJFuqiHhipBqcnCeW19FWO0a_-HYB-ryNPHe0Afq93W3n-RpASTVGOIU1tRmJou0HYNve34rxL8462tTMYEaUGuTdUn2JXuHounPrQR9g6Q2l073PfJZ-iEozbSsz3vZsvcX7LTVZpG0d4vRgjEyJpNRpJ4isI099ve7f0mO5O3o5dRj2uRpNDX_88sqnzdoQq3sHqjBn3-Dg3aQl4PQk0jxSdcp-6zGyxd5GSt5_5jYJevjwfJWNjgQk0KCA%26x-client-SKU%3DID_NET8_0%26x-client-ver%3D7.1.2.0

**To Reproduce**

Steps to reproduce the behavior.

just followed the quick start steps up to UI application integrations

**Comment by mysvrmt6** [comment]
after careful review, found the missing logic and added.
everything is working as expected.

**Comment by josephdecock** [comment]
Ok, thanks for the update. If there's anything we could add to our quickstart to make it easier to follow, I'd be grateful to hear your feedback!
