### ISSUE TITLE
Add additional parameters when redirecting to /connect/endsession through SignOutResult

### ISSUE THREAD

**Issue by hardy4787** [DuendeSoftware/Support#1193]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
.NET 7

### Describe the issue
Hi, I'm currently implementing logout through the Microsoft.AspNetCore.Mvc.SignOutResult as shown below:
```
await httpContext.SignOutAsync(scheme: IdentityAuthenticationDefaults.DefaultScheme);
var props = new AuthenticationProperties() { RedirectUri = "some_uri" };
props.SetParameter("some_parameter", true);
return new SignOutResult(new[]
{
    IdentityAuthenticationDefaults.ServerAuthenticationScheme
}, props);
```
### Account Controller (Redirect from /connect/endsession)
```
[HttpGet]
public async Task<IActionResult> Logout(string logoutId)
{
    var context = await _interaction.GetLogoutContextAsync(logoutId);
    ...
}
```
However, I can't seem to understand how I can access this data in my controller, since GetLogoutContextAsync doesn't appear to populate this. Any ideas on how I can achieve this? TIA.

### Expected behavior

I want to be able to read parameters of SignOutResult in AccountController

**Additional context**

I was not able to find similar code in quickstart samples

**Comment by josephdecock** [comment]
In your client application, you have to add the custom parameter explicitly to the outgoing redirect. You can do that in the OnRedirectToIdentityProvider event, something like this:
```
                    options.Events.OnRedirectToIdentityProvider = ctx => 
                    {
                        ctx.ProtocolMessage.Parameters.Add("your_custom_param", ctx.Properties.GetParameter("custom_param"));
                        return Task.CompletedTask;
                    };
```

**Comment by RolandGuijt** [comment]
I'm assuming this was the solution for you. Closing for now, but feel free to re-open if you have anything else.
