### ISSUE TITLE
Web.Api authentication fails with IDX10500: Signature validation failed. after net6.0 to net8.0 upgrade

### ISSUE THREAD

**Issue by haraldwolkenfelt** [DuendeSoftware/Support#1197]
"Duende.IdentityServer" Version="6.3.8"
net6.0

I've upgraded a Web.Api application from net6.0 to net8.0, which included the addition or upgrading of following packages:
<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.3" />
<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.5.0" /> 

and now authentication fails: _IDX10500: Signature validation failed. No security keys were provided to validate the signature._
I use the typical setup in my Web.Api, https://docs.duendesoftware.com/identityserver/v7/apis/aspnetcore/jwt/
though I left out `options.TokenValidationParameters.ValidTypes = new[] { "at+jwt" };` since we still emit type="JWT"

While looking for more details of what is going on I hooked up my own options.BackchannelHttpHandler and noticed that before in the net6.0 version there are two calls to the identityserver
1. /.well-known/openid-configuration
2. /.well-known/openid-configuration/jwks
After the Web.Api upgrade to net8.0 the second request is also to /.well-known/openid-configuration (without the /jwks) after which I receive the 'IDX10500: Signature validation failed' error.

Trace information:

info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
      Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
         at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignature(JsonWebToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
         at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignatureAndIssuerSecurityKey(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
         at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateJWSAsync(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
      Bearer was not authenticated. Failure message: IDX10500: Signature validation failed. No security keys were provided to validate the signature.

I've since tried several things to fix it, without success:
- `options.UseSecurityTokenValidators = true;`
- use an Duende.IdentityService upgrade of net6.0 to net8.0 and package upgrade to "Duende.IdentityServer" Version="7.0.3"
- in the Web.Api application create a OpenIdConnectConfiguration via `var configManager = new ConfigurationManager<OpenIdConnectConfiguration>(stsDiscoveryEndpoint, new OpenIdConnectConfigurationRetriever()); `and use that in the  `
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
{
    options.Configuration = config;
`
setup
- I tried to override the `config.JwksUri`

The only thing that helps is the following:
`options.TokenValidationParameters.SignatureValidator = (token, _) => new JsonWebToken(token);`

**Comment by FreeFrags** [comment]
I seem to be encountering the same issue, so please add your solution here if/when you find it. I'll do the same if i find it!

**Comment by FreeFrags** [comment]
I found something interesting, thought i might post it here havent tried it out yet but it seems to be a breaking change in .net 8 
https://github.com/dotnet/aspnetcore/issues/54321#issuecomment-1992613753
@mkArtakMSFT referers to this comment: 
https://github.com/dotnet/aspnetcore/issues/52075#issuecomment-1815025177

**Comment by AndersAbel** [comment]
The `Microsoft.IdentityModel` packages used by the Jwt Bearer handler and the OpenId Connect handler have very strict version requirements, that are unfortunately not enforced by Nuget. All the packages need to be exactly the same version. If not, strange bugs are known to hit.

Please run `dotnet list package --include-transitive | sls "Microsoft.IdentityModel|System.IdentityModel"` (using powershell) in the project directory and verify that all the packages have the same version.

**Comment by haraldwolkenfelt** [comment]
Yes, thank you Anders. With help of the package list I saw that there were links to older versions of Microsoft.IdentityModel.JsonWebTokens and Microsoft.IdentityModel.Protocols.OpenIdConnect.
I managed to solve my issues by directly including
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.5.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.5.1" />

**Comment by FreeFrags** [comment]
Thank you both! This solved my issue too. 

I was looking for a easy way to see why a package was listed as transient and i came across the following tool. thought i might leave a mention here since it might be helpful to others https://github.com/bjorkstromm/depends

**Comment by rhartzell** [comment]
Yes. Thank you. This also solved my problem. The package version mismatch is a killer.

**Comment by lwinch2006** [comment]
I just wanted to comment that it looks like a little bit risky to include `Microsoft.IdentityModel.JsonWebTokens` nuget library explicitly together with `Microsoft.IdentityModel.Protocols.OpenIdConnect` as last one still dependent on old style `System.IdentityModel.Tokens.Jwt`.

For now I try in our solutions to match versions of following libraries if they imported explicitly

```
Microsoft.AspNetCore.Authentication.OpenIdConnect (version x.x)
Microsoft.IdentityModel.Protocols.OpenIdConnect (version x.x)
```

and

```
Microsoft.AspNetCore.Authentication.JwtBearer  (version y.y)
Microsoft.IdentityModel.Protocols.OpenIdConnect (version y.y)
```
and let rest of dependencies loaded implicitly

  
  
  
![Image](https://github.com/user-attachments/assets/e1dc3c86-9a58-42d2-ae1b-2c316cb6b428)
![Image](https://github.com/user-attachments/assets/ecbdbadb-348b-4e7c-aac6-803c11912d94)

**Comment by fgarcia999** [comment]
To create middleware that captures a JWT token, validates its signature using the Jose.JWT library, decodes the payload, modifies fields (e.g., fixes the iat field), and re-signs the token only if the original signature is valid, implement the validation and modification logic within the middleware, and ensure the process is aborted with an appropriate response if the signature validation fails.


---------------------------------------------------------------Startup -------------------------
app.UseRouting();
app.UseMiddleware<JwtTokenFixMiddleware>();
app.UseAuthentication();

app.UseAuthorization();


--------------------------------------- new file -----------------------------

using Jose;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

public class JwtTokenFixMiddleware
{
  private readonly RequestDelegate _next;
  public IConfiguration _configuration;
  public JwtTokenFixMiddleware(RequestDelegate next, IConfiguration config)
  {
    _next = next;
    _configuration = config;
  }

  public async Task InvokeAsync(HttpContext context)
  {
    if (context.Request.Headers.TryGetValue("Authorization", out var authorizationHeader))
    {
      var token = authorizationHeader.ToString().Replace("Bearer ", "");
      try
      {
        string SecretKey = _configuration["Jwt:Key"];
        var payload = JWT.Decode<Dictionary<string, object>>(token, Encoding.UTF8.GetBytes(SecretKey), JwsAlgorithm.HS256);
        if (payload.ContainsKey("iat") && payload["iat"] is string iatString && DateTime.TryParse(iatString, out var iatDateTime))
        {
          **var epochIat = new DateTimeOffset(iatDateTime).ToUnixTimeSeconds();**
          payload["iat"] = epochIat;
        }

        var fixedToken = JWT.Encode(payload, Encoding.UTF8.GetBytes(SecretKey), JwsAlgorithm.HS256);
        context.Request.Headers["Authorization"] = $"Bearer {fixedToken}";

      }
      catch
      {

      }
    }
    await _next(context);
  }
}
