### ISSUE TITLE
Case Specific Client

### ISSUE THREAD

**Issue by Drew806** [DuendeSoftware/Support#1198]
**Which version of Duende IdentityServer are you using?**
Business

**Which version of .NET are you using?**
.NET 7

**Describe the bug**
The client redirects are case-specific for excellent and specific reasons.  However, customers go to our site with the same redirect but in different cases.  For example, https://HOST/admin/clients and https://HOST/Admin/clients.  Given this, I want to update the clientredirecturis table with both versions.  Unfortunately, that table has a unique constraint on the RedirectUri column that is case-specific.  If the redirect compare is going to be case-specific, then the column should also be case unique by case.

**Comment by AndersAbel** [comment]
Our storage implementation does not include any collation/case sensitivity information but relies on the default collation of the database. It is common to have a case insensitive collation on the database level. The way to set the collations and the names of the collations are DB engine dependent. Our Entity Framework code is DB engine independent to allow flexibility. In this case it unfortunately means that we cannot solve this in our general code.

My recommendation is to add a manual migration that sets the collation of the redirect URI column to be case sensitive.

**Comment by Drew806** [comment]
Thank you for the information. We will look into a database solution for
this.

Andrew Laytin

Vice President of Engineering

FormFire

An AgencyBloc Solution

Direct: 216-357-7400 x275

www.agencybloc.com

<https://www.blocbuilder.net/?utm_campaign=BB24&utm_source=24EmailSignature>
