### ISSUE TITLE
Mapping claims from access_token

### ISSUE THREAD

**Issue by ruse01** [DuendeSoftware/Support#1199]
**Which version of Duende BFF are you using?**
2.2.0

**Which version of .NET are you using?**
.net7.0

**Describe the bug**
It's more of a question than a bug. 
We've successfully implemented our first application using BFF. 
The claims have been mapped to the ClaimsPrincipal from the id_token, and I can also access to access_token by calling HttpContext.GetTokenAsync("access_token").  I know that the access token could be also forwarded to a remote API, but we would like to implement some authorization based on the access_token in the BFF application itself. 
My questions are: 
- Is it possible to add/map the claims from the access_token to the ClaimsPrincipal (beside the claims from the id_token)?
- Or is it possible to map the claims from the access_token instead of the id_token to ClaimsPrincipal?

**Additional context**

So far, I've found one workaround, which is to manually extract our custom claim, and add it ClaimsIdentity inside the OnTokenValidated event. However, I'm not sure if this is the right solution, and it only works with JWT, and doesn't with Reference token. 

``` csharp 
options.Events.OnTokenValidated = context =>
{
    var handler = new JwtSecurityTokenHandler();
    var accessToken = handler.ReadJwtToken(context.TokenEndpointResponse?.AccessToken);
    var toolScope = accessToken.Claims.First(t => t.Type.Equals(Constants.CustomScope.Tool));
    var identity = context.Principal?.Identity as ClaimsIdentity;
    identity?.AddClaim(toolScope);
    return Task.CompletedTask;
};

```

**Comment by AndersAbel** [comment]
While it might be technically possible to make the BFF inspect the access token that is not a recommended approach. At login time the OpenID Provider issues and id_token and an access_token. The id_token is meant to be consumed by the client, which is indicated by an `aud` claim with the client_id as the value. The access_token is meant to only be forwarded to APIs to authorize API calls. The contents and format of the access_token is a private implementation detail between the OpenID Provider (also called STS or Authorization Server) and the API. As you've found out the token could be a JWT or a reference token or even something else.

If you want more claims to be accessible to the client application you should add them to the id_token by creating a custom identity resource.

One more thing to consider is that by default IdentityServer do not include the claims in the id_token to reduce the size of the id_token. Instead the client is expected to make a call to the user info endpoint to retrieve the information about the user. In the BFF that behaviour can be enabled by setting the GetClaimsFromUserInfoEndpoint.

**Comment by RolandGuijt** [comment]
@ruse01 Did this ^ clear up things for you? Anything to add? If not I'd like to close this.

**Comment by ruse01** [comment]
Hi,
@AndersAbel, thank your for you answer/suggestion! We'll try to include the custom claim into the id_token. Unfortunately, we didn't have time to investigate it in the last 1-2 weeks.
@RolandGuijt, I'm closing this ticket.
Thank you!
