### ISSUE TITLE
Use join instead of a subquery on Client-AllowedGrantTypes relationship

### ISSUE THREAD

**Issue by VijayKaravadra** [DuendeSoftware/Support#120]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the question**

We're creating a custom implementation to query Client details by Grant type. Please refer to the below EF CORE query.

```
var clients = await _configurationDbContext.Clients
                .Where(x => x.AllowedGrantTypes.Any(x => x.GrantType.Equals(grantType)))
                .Select(x =>
                    new Client
                    {
                        ClientId = x.ClientId
                    })
                .ToListAsync();      
```

I expect it to make a join of Client-AllowedGrantTypes, but a subquery is created instead. I've also tried Include(x => x.AllowedGrantTypes) but still, the same query with the subquery is generated.

If there was AllowedGrantTypes DbSet exposed in the IConfigurationDbContext then I could make a join myself, but it is not exposed in the context.

Please refer to the generated query.

```
Executed DbCommand (334ms) [Parameters=[@__grantType_0='?' (Size = 250)], CommandType='Text', CommandTimeout='30']
      SELECT [c].[ClientId]
      FROM [Clients] AS [c]
      WHERE EXISTS (
          SELECT 1
          FROM [ClientGrantTypes] AS [c0]
          WHERE ([c].[Id] = [c0].[ClientId]) AND ([c0].[GrantType] = @__grantType_0))
```

**Comment by brockallen** [comment]
Do you know if the subquery is worse than a join? For example, did you run both in sql profiler and get the execution plan to show one is better?

**Comment by brockallen** [comment]
Also, this query provides an inner join for me:

```
        var q2 = await (from c in _context.Clients
                 from g in c.AllowedGrantTypes
                 where g.GrantType == "authorization_code"
                 select c.ClientId).ToArrayAsync();

```

SQL:

```
SELECT [c].[ClientId]
FROM [Clients] AS [c]
INNER JOIN [ClientGrantTypes] AS [c0] ON [c].[Id] = [c0].[ClientId]
WHERE [c0].[GrantType] = N'authorization_code'
```

**Comment by VijayKaravadra** [comment]
@brockallen The generated query looks as per the requirement. Thanks for looking into this!
