### ISSUE TITLE
IFrame

### ISSUE THREAD

**Issue by CodingCharlie** [DuendeSoftware/Support#1205]
We have a website site.website.com which redirects to sso.website.com to authenticate and then redirects back to site.website.com with token. This works without any issues. However, want to load site.website.com within an iframe on portal.website.com which does not work. Get SSO page but then won't redirect back to site.website.com. 

What could be causing this?

**Comment by AndersAbel** [comment]
It is considered bad practice from a security point of view to show the login page in an iframe. With an iframe there is no way for the user to see the address where they are actually entering their credentials. To enforce this our template implementation of the login page contains a content security policy that disallows it being hosted in an iframe. Could it be that it is the CSP that blocks the login?

**Comment by RolandGuijt** [comment]
Closing for now, but feel free to re-open if something comes up.
