### ISSUE TITLE
Update access token claims

### ISSUE THREAD

**Issue by bomner** [DuendeSoftware/Support#1208]
**Which version of Duende IdentityServer are you using?**
7.0.0

**Which version of .NET are you using?**
8

This is more of a question that I have.

Once AccessToken and RefrestToken are issued. Is there a way during token AccessToken refresh update claims?

The idea is that Identity Server will issue a token for a user which contains user specific claims however, values for these claims will change. So if administrators change claim value for the user I have a problem. Consider claims as permissions for certain actions User can do within the UI. So if user has CreateRecord claim this means he can send a request to the api to create a new Entity record.

Problem I am facing is that once token is issued all you can do is refresh its expiry date. Using BFF it also change only expiry date, Duende.AccessTokenManagement does not help either however, I guess I need some custom implementation inside Identity server where the claims are also update. 

Reason is that the API endpoints are authorized against this user access token so it needs to be up to date.

I was considering creating a new endpoint inside identity server to retrieve only user claims which I then can use in the Frontend however for the api I would need to authorize endpoint without claims, then get them from the same endpoint and then check if user has access to the resource which seen a little bit wrong in my opinion.

Is there a way to do all this?

BTW this is for blazor interactive website where render happens on a server and client. I have one 8 different clients which share one API to get/update data

**Comment by AndersAbel** [comment]
Once an access token is created the claims in it stays the same and are not updated. When an access token is refreshed using the refresh token flow the default behaviour is to return a copy of the current access token but with updated timestamps. There's a flag `Client.UpdateAccessTokenClaimsOnRefresh` that can be set to regenerate the claims in the access token each time it is refreshed.

That would give you new access token contents every time it is refreshed.

**Comment by RolandGuijt** [comment]
Closing for now but feel free to add if you feel the need to.
