### ISSUE TITLE
Error validating the Duende software license key after upgrading Rsk.WsFederation.DuendeIdentityServer to version 8.0.1

### ISSUE THREAD

**Issue by harmenstoopendaal** [DuendeSoftware/Support#1209]
**Which version of Duende IdentityServer are you using?**
 7.0.4

**Which version of .NET are you using?**
.NET 8.0

**Describe the bug**

After upgrading Rsk.WsFederation.DuendeIdentityServer from version 8.0.0 to version 8.0.1 I get the following error:

 FTL] Error validating the Duende software license key <s:Duende.IdentityServer.License>
Microsoft.IdentityModel.Tokens.SecurityTokenMalformedException: IDX14100: JWT is not well formed, there are no dots (.).
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
 ---> System.MissingMethodException: Method not found: 'Byte[] Microsoft.IdentityModel.Tokens.Base64UrlEncoder.UnsafeDecode(System.ReadOnlyMemory`1<Char>)'.
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken.ReadToken(String encodedJson)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebToken..ctor(String jwtEncodedString)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ReadToken(String token, TokenValidationParameters validationParameters)

The packages used in the Identityserver app:

    <PackageReference Include="DevAttic.ConfigCrypter" Version="1.1.0" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="22.2.5" />
    <PackageReference Include="Duende.IdentityServer" Version="7.0.4" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="7.0.4" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.0.4" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.WsFederation" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Rsk.WsFederation.DuendeIdentityServer" Version="8.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.3.0" />
    <PackageReference Include="Serilog.Expressions" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="6.6.0" />
    <PackageReference Include="TriasMVC.Infrastructure" Version="1.1.1.1723" />
    <PackageReference Include="TriasMVC.WebCommon" Version="1.1.1.1723" />

**Comment by AndersAbel** [comment]
This looks like it could be caused by Microsoft.IdentityModel.* package version mismatch. Please see https://github.com/DuendeSoftware/docs.duendesoftware.com/blob/d99ac7960f62bd82ddbb542ec1416cc37d29f6c5/IdentityServer/v7/docs/content/troubleshooting/wilson.md for guidance (this will be published on the docs site soon, this is a preview link).

**Comment by RolandGuijt** [comment]
Does the thumbs up mean Anders' comment solved your issue?
