### ISSUE TITLE
Duplicate Claims

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#121]
**Which version of Duende BFF are you using?**
1.2.3

**Which version of .NET are you using?**
.NET Core 6 (external API is .NET Framework 4.7.2)

**Describe the bug**
External API generates duplicate claims from the access token

**Additional context**
The user in our web application is being authenticated via Identity Server properly. The client displays authenticated pages. Calls are being made to the external API via the BFF and the token is being attached properly. When the token is validated, it passes all checks. At that point, I believe the API is generating a ClaimsPrincipal from the claims in the token. When we inspect the resulting claims, something like this...

var currentUser = HttpContext.User;
var nameId = currentUser.Claims.SingleOrDefault(claim => claim.Type == ClaimTypes.NameIdentifier);

...it throws an error stating that there are more than one claim with that type. The token look clean, but I am unclear how the type could be duplicated. Tokens generated in our current method do not have this same problem. Any ideas what I might be able to look at to determine cause?

Thanks!!

**Comment by leastprivilege** [comment]
How does the token look like - and how the claims collection?

**Comment by billcunnien** [comment]
The token looks clean - no duplicates. I am unable to debug the external API, so I am unable to see the actual claims on that server. The error is:

Unhandled exception: System.InvalidOperationException: Sequence contains more than one matching element at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

Internally, could the claims creation from the token being doing something unexpected with some value provided in the token?

**Comment by brockallen** [comment]
> Internally, could the claims creation from the token being doing something unexpected with some value provided in the token?

It's possible that you have code running in the API host that could modify the User on the HttpContext, yes.

**Comment by billcunnien** [comment]
The funny thing is that the current token has the NameIdentifier in it; however, it is called "nameid", not "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier" (no idea why!). So, it really isn't the NameIdentifier, then.

I will pursue this.

**Comment by billcunnien** [comment]
Makes no difference. Here is the token from Duende:

{
  "iss": "AAAAAA",
  "nbf": 1657711260,
  "iat": 1657711260,
  "exp": 1657714860,
  "aud": "BBBBBB",
  "scope": [
    "openid",
    "profile",
    "CustomIdentity"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "CCCCCC",
  "sub": "######",
  "auth_time": 1657711259,
  "idp": "local",
  "unique_name": "DDDDDD",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata": "######",
  "role": "EEEEEE",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/expiration": "07/13/2022 11:35:59",
  "nameid": "######",
  "IsActive": "True",
  "ExternalUser": "",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/system": "CCCCCC",
  "sid": "C606DDB1CBE6C59EBCA843DE11B504B6",
  "jti": "15FA0285977DBA833BCE57C08B592E83"
}

Why would the external API read this and generate duplicate NameIdentifier claims?

Here is the token from a working API call:

{
  "unique_name": "DDDDDD",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata": "######",
  "role": "EEEEEE",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/expiration": "07/12/2022 12:23:04",
  "nameid": "######",
  "IsActive": "True",
  "ExternalUser": "",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/system": "CCCCCC",
  "nbf": 1657627684,
  "exp": 1657628584,
  "iat": 1657627684,
  "iss": "AAAAAA",
  "aud": "BBBBBB"
}

Does the claims generation do something with those client artifacts within the Duende token? How do I remove those? There is no need for any client values in the token, just user. Maybe that is where the trouble lies.

Thanks, again.

**Comment by brockallen** [comment]
If you have both "sub" and "nameid" in the token (with the same value), then at your API it might be mapping both those to the same claim type. So I'd wonder why you have it in there twice, as "sub" is the official protocol claim type for the user's unique id. Also, Microsoft's libraries (by default) remap the standard claim types to their constants in the `ClaimTypes` class. You can disable that with `MapClaims` to false on the authentication handler options. Finally, if you can't do any of that, then you can trim the claims when the token is validated via one of the events on the authentication handler options callbacks.

**Comment by billcunnien** [comment]
Super great clue! I changed how the "sub" value was being populated and removed the "nameid" from my claims for the ApiResource. It is working, now. Thanks a ton!
