### ISSUE TITLE
/bff/silent-login fails after an hour

### ISSUE THREAD

**Issue by Stefan-Fredriksson** [DuendeSoftware/Support#1210]
``**Which version of Duende BFF are you using?**
v2.2.0

**Which version of .NET are you using?**
.NET8.0

**Description**
We have an Angular application as front-end and an ASP.NET Core application as back-end. We are trying to keep a user logged in for an extended period of time. To do so we are using silent login, via an iframe as the documentation shows. We have set a refresh token in AdminUI with a sliding expiration of 2 weeks. We are also including offline_access as a scope and have it enabled in AdminUI.

The silent login works fine for about an hour where you can close the browser and open the webpage again to automatically get logged in. After an hour the silent login fails and you have to manually login again.

Does anyone know what might cause this and how to fix it?

**Related code**
```
builder.Services.AddBff().AddRemoteApis();

builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "cookie";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
})
.AddCookie("cookie", options =>
{
    options.ExpireTimeSpan = TimeSpan.FromDays(14);

    options.SlidingExpiration = true;
    options.Cookie.Name = eauthConfig.GetValue<string>("CookieName");
    options.Cookie.SameSite = SameSiteMode.Lax;
})
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = eauthConfig.GetValue<string>("Authority");
    options.ClientId = eauthConfig.GetValue<string>("ClientId");
    options.ClientSecret = eauthConfig.GetValue<string>("ClientSecret");
    options.ResponseType = "code";

    options.GetClaimsFromUserInfoEndpoint = true;
    options.MapInboundClaims = false;
    options.SaveTokens = true;

    options.Scope.Clear();
    var scopes = new List<string>();
    eauthConfig.GetSection("Scope").Bind(scopes);

    foreach (var scope in scopes)
    {
        options.Scope.Add(scope);
    }

    options.TokenValidationParameters = new()
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    };
});

app.UseBff();

app.UseAuthorization();

app.MapBffManagementEndpoints();
app.MapRemoteBffApiEndpoint("/api", apiConfig.GetValue<string>("Url") ?? "")
    .RequireAccessToken();
```

Let me know if I need to provide more information.

Kind regards
Stefan

**Comment by AndersAbel** [comment]
What is the session lifetime set to on IdentityServer? It looks like it expires after one hour. Once the IdentityServer session is expired their is no session to silently log in to. The refresh token lifetime is something else. It could be used to allow the client to continue to run and acquire new access tokens even after the initial session was expired. If you chose to use that mechanism you wouldn't need the silent login.

**Comment by RolandGuijt** [comment]
As Anders noted, please note that the refresh token mechanism is separate from the silent login mechanism. Typically, when you use one, just don't need the other. In a BFF scenario it's fine to use refresh tokens since they are kept on the server and are not exposed to the browser. 
So one option could be to not use the iframe and go with just (re-usable) refresh tokens. More information [here](https://docs.duendesoftware.com/identityserver/v7/bff/tokens/).

Having said that:
Yes, the cookie lifetime is the same as the session lifetime, but looking at the last code your posted, I noticed something else.
The cookie is a SameSite cookie. SameSite cookies are not sent in an iframe regardless of the request type or if they're set to lax or strict. 
The reason is that an iframe is not a top-level browsing context. In other words it's a child browser context. You can read about it in the [specification](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-07#section-5.5).
That's actually one of the reasons IdentityServer's cookie is set to SameSiteModel none by default.
If you still want to go for the silent login method: can you please change this and see if it works?

**Comment by RolandGuijt** [comment]
@Stefan-Fredriksson Did the above comment do the trick for you? If so, I would like to close. If not, feel free to give us an update.

**Comment by Stefan-Fredriksson** [comment]
Sorry for the late response.

I tried changing SameSiteMode to none and it didn't help.

I also tried adding AddUserAccessTokenHttpClient to the bff server like the documentation shows, where I used the address to our IdentityServer as the client.BaseAddress, which didn't help.

I feel like I'm not understanding the process of how to implement the token management entirely.

Say I want to automatically login in the Angular app. Would the process look something like this?
1. Call /bff/user to check if we're logged in, responds that we're not logged in
2. Ask bff to check for an access token using a stored refresh token, how is this done?
3. Call /bff/user again to check if we're logged in

**Comment by RolandGuijt** [comment]
The front-end doesn't know anything about authentication and doesn't have to deal with the complexity of it. That's the beauty of using BFF.

Yes, the front-end will simply try to get the user claims from the BFF and the BFF will basically echo back what is in the encrypted session cookie that can only be read by the BFF, not by the front-end. 
If the front-end gets a 501 back it knows it has to show a login button or something that points to the login page on the BFF. And when the user logs in on the identity provider, it will set a cookie in the browser. The BFF will receive the identity token and set its own session cookie after which it redirects to the SPA which reloads, tries the user endpoint again and now it gets the claims back so it knows the user is authenticated.
This is basically the long version of your 1. and 3.

During the login process the BFF can also request an access token and a request token from the identity provider needed for API access. That will be stored in the BFF. When the front-end wants to do a request to an API, it doesn't have the access token so it has to ask the BFF to do the request for it. That's where the reverse proxy comes in.
Before using the access token our BFF implementation will check if it's still valid and refresh it if necessary using the refresh token if present.
So there's no need for the frontend to do anything with access or refresh tokens directly.

Now for the silent login: that will also check the user endpoint to see if it gets claims back. If not it will try to login silently which means without the user noticing it. That will only work if there is a valid session cookie from the identity provider. The login sequence will still be triggered on the identity provider, but there already is a session cookie so no login page is shown and the tokens are sent to the BFF without the user having to do anything.

Hope that helps.

**Comment by RolandGuijt** [comment]
Was this all clear? Can we close?

**Comment by Stefan-Fredriksson** [comment]
We haven't been able to solve it yet but you've pointed us in the right direction so we'll keep looking into it and hopefully solve it.

I'm closing the issue as we can't come up with anything else to ask.

Thanks for the help!
