### ISSUE TITLE
how to disable single signout in identity server?

### ISSUE THREAD

**Issue by ramu-spec** [DuendeSoftware/Support#1211]
Hi ,

How to disable/enable single sign functionality in identity server. but in my case single sign on working fine but my requirement is need to disable single sign out in identity server.

please help me any changes we are doing for this change in identity server side.

**Comment by AndersAbel** [comment]
If you don't configure any logout endpoints in the clients in IdentityServer there will be no single signout.

You would also have to make sure that your client applications do not initiate a single logout.

Can you describe a bit more in detail what the user would to end up in single logout flow that you do not want?

**Comment by ramu-spec** [comment]
Ok I will  explain clearly 

Example:
login with two application with same user along with same identity server. 
1)first application idle time is 30minutes
2)second application idle time is also same 30minutes.
3)if am working on second application since one hour.but first application idle time is over and its logged out.based on first application loggesd out effect on second application .
if am working on second application its automatically logged out.

so finally i relised first application idle time over so that its logged out and also its removed user session also.so that why second application also logged out.
what is the way for when am working on second application don't log out .how can i handle this scenario?

**Comment by ramu-spec** [comment]
Yes

**Comment by ramu-spec** [comment]
Hi,

SPA(Single Page Application ).
Yes i removed logout endpoints.
Which Configuration you want and i registered two different clients and  hosted those two in different Urls
example:
https://vm-agentapp.azurewebsites.net
https://vm-employeeapp.azurewebsites.net
both clients registered with same identity server.both portals login with same user details
but in agent app idle time is over its automatic logout but still am working in employee app.so agent app automatic logout its impact on employee app.
No right now we are used identity server 6.0 version

**Comment by RolandGuijt** [comment]
Are you using a framework (like Angular, React) for the SPAs? And are you using a javascript auth library, if so which one? Or are you using BFF?
Can you please post the configuration for the two configured clients in IdentityServer?

**Comment by ramu-spec** [comment]
Yes am used framework for SPAs.
First App:
ClientId:"agentlocal",
"ResponseType": "code",
"RedirectUri": "http://vm-agentapp.azurewebsites.net"

First App:
ClientId:"emplocal",
"ResponseType": "code",
"RedirectUri": "http://vm-employeeapp.azurewebsites.net" and scope also passed.

**Comment by AndersAbel** [comment]
This looks like something we would need to look deeper into to be able to help. On the issue tracker here we can answer direct questions and give general high level advice on architectural issues. However it is not a format that works for investigating/troubleshooting an entire environment.

If you want further help we could supply that under our paid remote consulting services, please reach out to contact@duendesoftware.com for details.

I am closing this issue now as I don't think that we will be able to get any further here. If you have any concrete questions, please feel free to open a new issue.

**Comment by josephdecock** [comment]
One other resource to take a look at is our documentation on server side sessions, and in particular our discussion of how to use the server side session to create a global inactivity timer.

Solving that problem can add considerably to the architectural complexity of the solution, depending on exactly what your requirements are. Architectural advice and analysis of requirements that would go along with that is something we do on a consulting basis, as Anders mentioned above. 

My advice is to take a look at our docs first, and see what you think: https://docs.duendesoftware.com/identityserver/v7/ui/server_side_sessions/inactivity_timeout/

As Anders says, if you have specific follow up questions, feel free to open a new issue. And if you need architecture level consulting, please get in touch. Thanks!
