### ISSUE TITLE
Cookie persistence question

### ISSUE THREAD

**Issue by hileyj** [DuendeSoftware/Support#1212]
**Which version of Duende BFF are you using?**
2.0.0

**Which version of .NET are you using?**
.NET 8

**Describe the bug**

Probably not a bug, but a question.
I am using the Duende BFF with a Blazor WASM application. An OIDC/OAuth identity provider is used for sign-in. Initial application setup was mostly based on the BFF Blazor6 sample. Sign-in, local APIs, silent login, and remote API proxying all seem to be working as expected.

The cookies issued by the BFF always seem to be session cookies and are cleared when the browser is closed.
Is this expected behaviour? I have reviewed the [documentation](https://docs.duendesoftware.com/identityserver/v6/bff/session/handlers/) which has an example of the cookie auth options. I have tried changing those to no effect, as far as I can tell.

Any guidance or documentation you can point me to would be appreciated. It may just be a lack of understanding on my part.

Here is the basic auth configuration for the app:
```csharp
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "cookie";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
})
.AddCookie("cookie", options =>
{
    options.Cookie.Name = "__Host-blazor";
    options.Cookie.SameSite = SameSiteMode.Strict;
})
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = oidcSettings.Authority;

    options.ClientId = oidcSettings.ClientId;
    options.ClientSecret = oidcSettings.ClientSecret;
    options.ResponseType = "code";
    options.ResponseMode = "query";

    options.Scope.Clear();
    if (oidcSettings.DefaultScopes != null)
    {
        foreach (string scope in oidcSettings.DefaultScopes)
        {
            options.Scope.Add(scope);
        }
    }

    options.MapInboundClaims = false;
    options.GetClaimsFromUserInfoEndpoint = true;
    options.SaveTokens = true;
    options.ClaimActions.MapAll();
    options.Events = new OpenIdConnectEvents
    {
        OnRedirectToIdentityProvider = (context) =>
        {
            var acrValues = context.Request.Query["acr_values"];
            context.ProtocolMessage.AcrValues = acrValues;
            context.ProtocolMessage.RedirectUri = BffUrlUtilities.GetUpdatedUrl(context.ProtocolMessage.RedirectUri, context.Request.Headers);
            return Task.CompletedTask;
        },
        OnRedirectToIdentityProviderForSignOut = (context) =>
        {
            var acrValues = context.Request.Query["acr_values"];
            context.ProtocolMessage.AcrValues = acrValues;
            context.ProtocolMessage.PostLogoutRedirectUri = BffUrlUtilities.GetUpdatedUrl(context.ProtocolMessage.PostLogoutRedirectUri, context.Request.Headers);
            return Task.CompletedTask;
        },
        OnAccessDenied = (context) =>
        {
            context.Response.Redirect("/");
            context.HandleResponse();
            return Task.CompletedTask;
        },
    };
});
```

**Comment by AndersAbel** [comment]
The Asp.Net Core cookie handler's default behaviour is to use session cookies. If you want a persistent session the easiest is to use the `TicketReceived` event and set the `IsPersistent` flag in the authentication properties.

**Comment by hileyj** [comment]
Thanks, I was starting to gather that was the case from the ASP.NET docs and BFF code. I'm not entirely sure I do want persistent sessions, but was exploring 'Remember Me' type functionality.
