### ISSUE TITLE
Using `AuthorizeInteractionResponseGenerator` for Clientless / Local login

### ISSUE THREAD

**Issue by StuFrankish** [DuendeSoftware/Support#1214]
**Which version of Duende IdentityServer are you using?**
7.0.4

**Which version of .NET are you using?**
8.0.300

**Question**
I've been re-building our Identity Server using the v7.0.4 version of Identity Server and have been working quite extensively with the `IAuthorizeInteractionResponseGenerator` interface to manage required checks & steps when logging in.

While I've had success in getting out of it what we need when authorizing client applications, the Identity Server host itself only goes through the basic username/password login and doesn't trigger the interaction response generator.

Brock pretty much confirmed that was the case here: https://github.com/IdentityServer/IdentityServer4/issues/4747
.. but didn't clarify if there was a way to force Identity Server to authorize itself as it would a client.

So I have a couple of questions to that end.
1. Is it possible to get Identity Server to do that and any pointers you could offer?
2. If not, would the recommendation then be to create a collection of local API's in Identity Server and always use an independent client app for managing one's profile (_updating contact info, managing MFA etc.._) and managing users and client apps.

**Comment by AndersAbel** [comment]
The role of the `IAuthorizeInteractionResponseGenerator` is to validate that all requirements are fulfilled to be able to create a response back to the client application. One of the requirements is that there is a logged in users, another is that any consent required has been granted.

You would use the `IAuthorizeInteractionResponseGenerator` if there is complex logic where different clients have different requirements to allow a response to be generated. One recent example I had was that only the user profile management client would be allowed to get an authorize response if the user profile was not completed. Requests from any other clients would result in the user profile management client being activated.

If you have some steps that you want to be completed before any client can sign in that should be handled in the login flow and not in the `IAuthorizeInteractionResponseGenerator`. To preserve a user's identity while completing the flow you can use a custom cookie scheme.

**Comment by StuFrankish** [comment]
Apologies @AndersAbel, I think I might have explained myself badly here.
I didn't mean to imply that I had replaced the default implementation of `IAuthorizationInteractionResponseGenerator` - I have extended it like so (unfinished as it still is);

```c#
using Duende.IdentityServer;
using Duende.IdentityServer.Configuration;
using Duende.IdentityServer.Models;
using Duende.IdentityServer.ResponseHandling;
using Duende.IdentityServer.Services;
using Duende.IdentityServer.Validation;
using System.Security.Claims;

namespace IdentityServer.Extensions;

public class CustomAuthorizeInteractionResponseGenerator(
    IdentityServerOptions options,
    IClock clock,
    ILogger<CustomAuthorizeInteractionResponseGenerator> logger,
    IConsentService consent,
    IProfileService profile) : AuthorizeInteractionResponseGenerator(options, clock, logger, consent, profile)
{
    private readonly IProfileService _profileService = profile;
    private readonly ILogger<CustomAuthorizeInteractionResponseGenerator> _logger = logger;
    private const string eula_accepted = "eula_accepted";

    protected override async Task<InteractionResponse> ProcessLoginAsync(ValidatedAuthorizeRequest request)
    {
        var result = await base.ProcessLoginAsync(request);
        if (result.IsLogin || result.IsError || result.IsConsent) return result;

        _logger.LogDebug(message: "Handling custom interaction logic");

        var profileDataRequest = new ProfileDataRequestContext {
            Subject = request.Subject,
            Client = request.Client,
            RequestedClaimTypes = [eula_accepted]
        };

        await _profileService.GetProfileDataAsync(profileDataRequest);

        if (MfaRequired(request) && !AuthenticatedWithMfa(request.Subject)) {
            return new InteractionResponse { RedirectUrl = "/Account/Mfa" };
        }

        if (!EulaAccepted(profileDataRequest)) {
            return new InteractionResponse { RedirectUrl = "/eula/accept" };
        }
        
        return result;
    }

    private static bool EulaAccepted(ProfileDataRequestContext profileDataRequestContext)
    {
        return profileDataRequestContext.IssuedClaims.Any(c => c.Type == eula_accepted && !string.IsNullOrWhiteSpace(c.Value));
    }

    private static bool MfaRequired(ValidatedAuthorizeRequest request) =>
        MfaRequestedByClient(request) ||
        UseMfaForUser(request.Subject.Identity.Name);

    private static bool MfaRequestedByClient(ValidatedAuthorizeRequest request)
    {
        return request.AuthenticationContextReferenceClasses.Contains("mfa");
    }

    private static bool UseMfaForUser(string sub)
    {
        // If you have the requirement that some users will always use MFA and
        // others will not, you could implement that here. This might be a user
        // controlled option, or set according to some business logic.

        return sub == "alice";
    }

    private static bool AuthenticatedWithMfa(ClaimsPrincipal user) =>
        user.Claims.Any(c => c.Type == "amr" && c.Value == "mfa");

}
```

What I'd like to do is to run the same authorization flow for a user logging into IdentityServer as a user would have when logging into a client app.

I'm just unsure if there is a way to either tell IdentityServer to treat itself as a client, or whether managing users, clients etc.. should be managed in a separate client app (which would then go through all the required steps during login).

But I was hoping to build it into the IdentityServer host first.

**Comment by brockallen** [comment]
> What I'd like to do is to run the same authorization flow for a user logging into IdentityServer as a user would have when logging into a client app.

The interaction response generator is what tells IdentityServer to get to your login page in the first place. So then you'd be calling into logic that says "do I need to go to the login page" from the login page.

Why not just factor out the common logic into another service and stick it in DI, and then call it from your login page workflow?

**Comment by RolandGuijt** [comment]
@StuFrankish Did Brock's comment help you out? If so I'd like the issue to the closed status.
If not, feel free to add.

**Comment by StuFrankish** [comment]
Hi @RolandGuijt -
For the time being yes, but I'll need to understand more about what Brock meant about the login flow and do some reading.

I'm most likely way over thinking it, but is Brock suggesting removing the logic I've added to the response generator, moving it into DI and adding logic to the login.razor.cs  effectively mimicking what the code in the response generator was doing?

Feels like putting the logic in the login page would make the response generator changes redundant, so I'm not sure why we are then able to extend it. 
In my head why treat logging into the IdP any different from logging into a client unless there's some logic you only want to apply when authorising a client.

**Comment by RolandGuijt** [comment]
As Brock said the purpose of the AuthorizeInteractionResponseGenerator is to determine whether or not the user must log in (or consent). And if you want to deviate from the default logic, the extensibility of it enables you to do so.

But it's not the right place to put in the logic you mentioned. For that no extensibility points of IdentityServer are needed at all. Just create a class with the logic, register it in DI and inject it in the login page of IdentityServer.

I'm closing for now, but feel free to re-open if you have further questions.
