### ISSUE TITLE
Table name casing with EF implementations for operations and configuration stores

### ISSUE THREAD

**Issue by dmontgomery** [DuendeSoftware/Support#1216]
**Which version of Duende IdentityServer are you using?**

7.0.4

**Which version of .NET are you using?**

8.0

**Describe the bug**

Table names for EFCore DbContext implementations for configuration and operation stores expect PascalCase.  PostgreSql forces queries to double-quote table names as a result.  Using the EFCore.NamingConventions solves the problem for column names (thankfully), but the table names seem to be built-into the DbContext classes.

**To Reproduce**

Use PostgreSql 

**Expected behavior**

UseSnakeCaseNamingConventions() should work, or it should be trivial to extend the behavior of the OnModelCreating() in the provided DbContext classes.

```
.AddConfigurationStore(options =>
{
    options.ConfigureDbContext = db => db
        .UseSnakeCaseNamingConvention()
        .UseNpgsql(configurationConnectionString,
            sql => sql.MigrationsAssembly(migrationsAssembly));
})
```

**Actual Behavior**

Every table name is PascalCase, like:

```
CREATE TABLE "PushedAuthorizationRequests" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    reference_value_hash character varying(64) NOT NULL,
    expires_at_utc timestamp with time zone NOT NULL,
    parameters text NOT NULL,
    CONSTRAINT pk_pushed_authorization_requests PRIMARY KEY (id)
);
```

**Comment by AndersAbel** [comment]
It is possible to change the names of the tables using the `ConfigurationStoreOptions` class. But they still need to be set in code.

I've added https://github.com/DuendeSoftware/IdentityServer/issues/1542 as a suggestion on an improvement to allow custom conventions to be used. Please add any feedback there, especially if you have any more insight on how this would affect people in a migration scenario.

**Comment by dmontgomery** [comment]
Thank you.

I did not understand on my first read-through of the `ConfigurationStoreOptions` the table names could be overridden.

**Comment by AndersAbel** [comment]
They can, but you would have to manually override them one by one as the explicit name overrides any convention registered.

We are looking into removing the explicit names to allow the conventions to take effect. We need to be very careful on how to approach it to not break existing installations on upgrade.

**Comment by RolandGuijt** [comment]
Looks like everything is solved for you. Closing but feel free to add if something comes up.
