### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by ramu-spec** [DuendeSoftware/Support#1217]
**Identity server 6.0.1**

** Net 6.0**

**In  two application  login with same user  using identity server but one application  idle time  is over and am working in second application. but first application idle time is over and its logged out.**

**Expected behavior**

i want to log out first application based on second application is there in live or not.

**Comment by AndersAbel** [comment]
It looks like you've opened both this and #1211 which is about the same issue. I'm closing this to keep the discussion in one place.
