### ISSUE TITLE
Guidance wanted for OTEL Metrics with Honeycomb

### ISSUE THREAD

**Issue by michaeldimoudis** [DuendeSoftware/Support#1222]
Hi this isn’t a bug, I’m just wondering if you can guide us in how to write Metrics queries for the latest version of IdentityServer when using Honeycomb. 

We haven’t used Metrics before so if you can provide some starting guidance that would be great. I know you’ve dabbled in Honeycomb as the Telemetry blog has screenshots of Honeycomb. 

We’ve implemented the stable and experimental metrics, as well as the UI metrics. But we are unsure how to structure queries and dashboards in Honeycomb. 

Any advice, even just a quick starting point will be very appreciated if you can.

**Comment by AndersAbel** [comment]
I'm sorry but we cannot provide any specific guidance on how to set up the dashboard or queries in a third party tool.

While we used HoneyComb for some early experiments, we now use Aspire as our sample host for Otel.
