### ISSUE TITLE
How to issue an access_token for an existing session that hasn't had tokens but will now have them?

### ISSUE THREAD

**Issue by zerazobz** [DuendeSoftware/Support#1224]
I had a configuration client + handler that worked only with cookies.
**I have many users already logged with that cookies**

That configuration didn't emit tokens, then I changed the client + handler to achieve that.

```
----- On Identity Server project
    new Client
    {
        // new lines
        AccessTokenType = AccessTokenType.Reference,
        AlwaysIncludeUserClaimsInIdToken = true,
        AllowOfflineAccess = true,
        AllowAccessTokensViaBrowser = true,
        RequirePkce = false
    },

------On Client handler
        options.SaveTokens = true;
        options.ResponseType = "id_token token";

------On Client handler
    private Task TokenValidated(TokenValidatedContext arg)
    {
        // new line
        arg.HttpContext.Items.Add("JwtSecurityTokenUsedToCallWebAPI", arg.SecurityToken as JwtSecurityToken);
        return Task.FromResult(0);
    }
```

After doing that I can retrieve tokens using: `var accessToken = await HttpContext.GetTokenAsync("access_token");` it works but I need to log in the user.

That's the problem, I can't log out and then log in users who are already logged in.
If I call `await HttpContext.GetTokenAsync("access_token");` for an already logged session it will return null.

I tried to call `await HttpContext.SignInAsync(HttpContext.User);` to refresh the session but it didn't work.
What can I do to get "access_token" for those already logged users?

**Comment by RolandGuijt** [comment]
Did this info solve your issue? If so I'd like to close it.
