### ISSUE TITLE
How to change client id / client secret 

### ISSUE THREAD

**Issue by greg-signi** [DuendeSoftware/Support#1226]
**Which version of Duende IdentityServer are you using?**
7.0.4

**Which version of .NET are you using?**
8

How can I switch the clientId/clientSecret ? I've tried to modify it on the `OpenIdConnectEvent.OnRedirectToIdentityProvider` but its still assuming the base client which I registered in the `AddOpenIdConnect`.

I need this because I need to lookup and change clients based on the received host.

**Comment by RolandGuijt** [comment]
That is a question specific to the OpenIdConnect handler which is by Microsoft, so the issue tracker for that would be a good place to ask this question.
Having said that: Dynamic clients are not supported. The only way to do it is to register multiple handlers.

**Comment by greg-signi** [comment]
> The only way to do it is to register multiple handlers.

Thanks for the answer. How would you go about this ?

**Comment by AndersAbel** [comment]
@greg-signi Yes, you can call `.AddOpenIdConnect` multiple times. If you are interacting upstream providers from your IdentityServer you might also want to look into our [Dynamic Providers feature](https://docs.duendesoftware.com/identityserver/v7/ui/login/dynamicproviders/).

**Comment by greg-signi** [comment]
@AndersAbel @RolandGuijt 
And can you give your opinion taking into account the structured of IS, what do you think it makes more sense, `.AddOpenIdConnect` with a different client multiple times for each new app (domain) we want to register, or implement a system of multi tenancy ?

**Comment by greg-signi** [comment]
> If you are interacting upstream providers from your IdentityServer you might also want to look into our [Dynamic Providers feature](https://docs.duendesoftware.com/identityserver/v7/ui/login/dynamicproviders/).

multiple providers we already support 👍
