### ISSUE TITLE
Infinite loop when max_age=0

### ISSUE THREAD

**Issue by pecanw** [DuendeSoftware/Support#1227]
**Versions used**
- Duende IdentityServer 7.0.4
- .NET 8.0

**Describe the bug**

When the authorize endpoint is called with `max_age=0` parameter it is copied to the callback returnUrl. So after successful login the user is redirected to the login page again (with the max_age parameter again in the returnUrl).

**To Reproduce**

Call authorize endpoint with `max_age=0`

**Expected behavior**

User logs-in and max age is not checked on callback.

[Proposed solution - see the pull request](https://github.com/DuendeSoftware/IdentityServer/pull/1544)

**Comment by RolandGuijt** [comment]
This is a duplicate of #1229. Closing this one so please track #1229 going forward.
