### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by schlechtOptimiziert** [DuendeSoftware/Support#1235]
**Which version of Duende IdentityServer are you using?**
idk
**Which version of .NET are you using?**
7
**Describe the bug**
null refference error

**To Reproduce**
https://github.com/schlechtOptimiziert/DockerTest
Is a standard hosted Blazor Program created by vs2022 with minimal settings corrections to make it work.

clone => db setup (README) => "docker compose up" => try access the Site

**Expected behavior**
idk why it is not working.

Would like to dockerize my test program. Not trying to publish the application, only trying to dockerize my Programm for my studies.

**Comment by RolandGuijt** [comment]
It looks like you created this solution using Microsoft's template to create a Blazor Wasm application with authentication. Unfortunately that is not the way IdentityServer should be used and the template has been removed in .NET 8.

We have a [document](https://docs.duendesoftware.com/identityserver/v7/upgrades/spa_to_duende/) that describes the problem and gives some hints on how to proceed. I recommend reading it to understand why the template doesn't work.
Honestly I think the best thing to do after that is to start from scratch.

If all you need is authentication for this one Blazor application with a dedicated API you don't need IdentityServer at all. I would recommend setting up a server application that takes care of logging in and out. This is called the BFF pattern. You can then just use Microsoft's identity cookie mechanism and embed the protected API endpoints in the BFF so they can be accessed with just the cookie. No tokens needed.

I would start with that and maybe at a later stage look at IdentityServer when more applications come in play and/or the API needs to be external.
I've created an example [here](https://github.com/RolandGuijt/ps-reactauth/tree/main/1.Cookies) (my personal GitHub account) that shows you what I mean. It uses React as a front-end but the principle is the same.
Please understand that this all Microsoft, there are no Duende products involved. So we don't support this here.
