### ISSUE TITLE
Presales Contact

### ISSUE THREAD

**Issue by crickardgd** [DuendeSoftware/Support#1239]
I need to talk to a sales rep regarding licensing and presales tech support with some questions regarding external account scenarios.  Is there a number to call?

**Comment by josephdecock** [comment]
Please use our contact form [here](https://duendesoftware.com/contact) and we will be in touch.

**Comment by crickardgd** [comment]
Hi!  I sent a message with that form a week ago and sent an email to "contact@duendesoftware.com" on Thursday.

**Comment by josephdecock** [comment]
Hmm, not sure what happened here...

I had sent an email to crickard@greendotcorp.com (which mostly matches your GitHub user name, so I assume that's you) on April 26. Did I get your email address wrong, or was my email maybe caught in a filter? Subject line: IdentityServer Discussion

**Comment by crickardgd** [comment]
Yes.  That's my correct email address.  I'm getting these GitHub notifications there just fine.

Very strange.  I don't see anything from @duendesoftware in my Junk Email folder, but I do see a bunch of other vendors.  I went ahead and added your domain to my safe senders list.  Can you try again?

**Comment by josephdecock** [comment]
Okay, I just sent another email from joe@duendesoftware.com. Did you get that?

**Comment by josephdecock** [comment]
Closing this as we will continue via email.
