### ISSUE TITLE
Duplicate query string parameters in Authorize causing request to fail, same works for IdSrv4

### ISSUE THREAD

**Issue by pritamsso** [DuendeSoftware/Support#124]
**Which version of Duende IdentityServer are you using?**
6.1
**Which version of .NET are you using?**
6.0

**Describe the bug**

If a authorize query string contains duplicate parameter response_type parameter the request is failing with unsupported_response_type. 

Specifically happening from swagger UI

Same request works in IdSrv4 as code here. https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Extensions/IReadableStringCollectionExtensions.cs#L24 

Considers only first parameter and ignores the other one.

 But the implementation here - https://github.com/pritamsso/DuendeIdentityServer/blob/main/src/IdentityServer/Extensions/IReadableStringCollectionExtensions.cs#L27

adds everything into the NameValueCollection which in further process gets concatenated into single string and validated against the responsetype constants which fails.

**To Reproduce**

Initiate the normal login request to authorize endpoint with duplicate respose_type parameter in query string 

i.e. https:// { Duende IdentityServer 4 Host }/connect/authorize?`response_type=id_token token`&scope=openid profile&nonce=1720e25c-f3c7-4611-80b1-b62b142d2893&&`response_type=token`&client_id=internal-rest-swagger&redirect_uri=https://internal-api.domain.com/swagger/ui/oauth2-redirect.html&state=U2F0IEp1bCAxNiAyMDIyIDA4OjA3OjM5IEdNVC0wNzAwIChQYWNpZmljIERheWxpZ2h0IFRpbWUp&realm=swagger-ui-realm

In this example the response_type keys value in NameValueCollection will be `id_token token,token` which is invalid response type.

**Expected behavior**

**Log output/exception with stacktrace**

**Additional context**

This issue can be addressed by checked if the NameValueCollection already holds the value or not.

**Comment by brockallen** [comment]
Thanks -- we'll be looking into it.

**Comment by brockallen** [comment]
@pritamsso I'd suggest that you fix the client and prevent it from sending dup params. The spec does not allow that -- look at the `invalid_request` error: 

https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1
https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2.1
