### ISSUE TITLE
No Diagnostics in Deployment

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#125]
Duende IS v6
.NET Core 6

I have setup an Azure pipeline to build, publish and deploy the IS to an IIS server. The pipeline runs successfully. The site comes up just fine and the login page is working. After I login then attempt to navigate to diagnostics, I get a 404 error. The page works fine locally. Any ideas what I can look into to determine why this is throwing a 404?

Thanks!

**Comment by brockallen** [comment]
All of the quickstart UI is intended to be a sample and a starting point for you. Once you have it, it's *your* code. Have you looked at that code?

https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI/blob/main/Pages/Diagnostics/Index.cshtml.cs

**Comment by brockallen** [comment]
If you have a look at the logic in that file, it returns 404 if the request is not on the local machine. IOW, it's meant for local testing. But of course, you can change it.

**Comment by billcunnien** [comment]
I see that now. Embarrassing. Thanks for pointing me in the right direction. Sometimes the obvious is too obvious. :)
