### ISSUE TITLE
Prevent concurrent sessions and end all current user sessions

### ISSUE THREAD

**Issue by daver77** [DuendeSoftware/Support#1252]
Hi, we currently have an Enterprise setup with an Id server and ASP.NET Identity authentication rolled into one. We have a 'requirement' that we should not allow concurrent logins for a single user and also end all a users sessions when they reset their password.

As far as I can see I firstly need to enable [Server-Side Sessions](https://docs.duendesoftware.com/identityserver/v7/ui/server_side_sessions/) which I presume will allow me to check for an existing session on login. Using Server-Side Sessions is it possible to revoke all sessions for a user therefore forceably logging them out of all websites?

**Comment by josephdecock** [comment]
Yes, you can revoke server side sessions using the `ISessionManagementService.RevokeSessionsAsync` method. See docs [here](https://docs.duendesoftware.com/identityserver/v7/ui/server_side_sessions/session_management/#terminating-sessions). You can use the same service to query if a session exists during the login process. You probably want to use a [custom AuthorizeInteractionResponseGenerator](https://docs.duendesoftware.com/identityserver/v7/ui/custom) to control the authorization experience.

**Comment by RolandGuijt** [comment]
@daver77 Did Joe's comment solved the issue for you? If so I'd like to close.

**Comment by daver77** [comment]
@RolandGuijt not tried it yet but happy to close it

**Comment by RolandGuijt** [comment]
Ok. Feel free to reopen if you encounter issues.
