### ISSUE TITLE
Teams app authentication with BFF

### ISSUE THREAD

**Issue by chandraarora** [DuendeSoftware/Support#1259]
Hi 

We are running Duende Identity server and it runs perfectly. We are about to publish our software also in teams apps. Teams app has its on library to call oauth server authentication and getting the access token. 

Would it be possible to use bff on teams app? if you have an example it will be a great help to us. 

Thanks
Chandra

**Comment by chandraarora** [comment]
Hi 

I have draw a picture. It is working till successfull authentication but would need help in redirection.

![image](https://github.com/DuendeSoftware/Support/assets/35835798/9324f144-8476-45af-98c2-9ec6864d4f92)
 
Thanks

**Comment by chandraarora** [comment]
Hi

Thank you for your reply

It is Microsoft Teams app which will be published after development is complete.

It is SPA and I would like to use BFF so that authentication is done on server side. I can get the redirect to my api which works fine. I am not able to redirect from api to teams app which is running on localhost:53000 evetually it will be a Ms teams.

How to get back to localhost from bff or from IDP.


***@***.***

**Comment by RolandGuijt** [comment]
I'm confused. When you say API you mean the BFF server application perhaps? I don't see an API in your diagram.

**Comment by chandraarora** [comment]
Yes , API mean is Bff server

**Comment by RolandGuijt** [comment]
The main reason the BFF pattern is used is to move the complexity around authentication from SPA to BFF. When using a BFF the SPA itself doesn't need OAuth support. The BFF will get the identity and access tokens on behalf of the SPA. In addition the access token will not be sent to the SPA but instead it is kept on the BFF. 

So the only thing the SPA has to do really is trigger the login process by calling an endpoint on the BFF (bff/login e.g.). The BFF will then set an identity cookie after verifying and reading the identity token and as mentioned, store the access token. After that it redirects to the SPA which is reloaded. That is the no. 4 on your diagram. 
The cookie is encrypted and only the BFF has the key, so the SPA has to request the user's claims via an endpoint on the BFF (bff/user is the default in Duende BFF).

The flow for your Teams app shouldn't be any different than any other javascript application. If you're unsure how this works in code my suggestion is to check out our [examples](https://github.com/DuendeSoftware/BFF/tree/main/samples) that use vanilla javascript.

**Comment by chandraarora** [comment]
I have issue in redirecting to  "After that it redirects to the SPA which is reloaded"

In the redirection if I set the redirect url to bff then it works but when I set the redirect url of spa  in this case it is localhost:53000/auth-end, then I get error

***@***.***

**Comment by chandraarora** [comment]
Or I am not giving the correct setting in bff to redirect to spa.

When Ido redirect to bff , what settings should I give in bff so that it goes to spa?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chandra Arora
Sent: Monday, May 20, 2024 11:01:45 AM
To: DuendeSoftware/Support ***@***.***>; DuendeSoftware/Support ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [DuendeSoftware/Support] Teams app authentication with BFF (Issue #1259)


I have issue in redirecting to  “After that it redirects to the SPA which is reloaded”



In the redirection if I set the redirect url to bff then it works but when I set the redirect url of spa  in this case it is localhost:53000/auth-end, then I get error



***@***.***

**Comment by RolandGuijt** [comment]
By default Duende BFF will redirect to "/" when login completes, but you can also use another URL. Please look [here](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/login/) for an example.

**Comment by chandraarora** [comment]
Hi Ronald

I have create one more diagram to explain the situation. From teams app we open the window as popup in a new window and cookie and token exchange happens in 2nd window. How we get cookie to  window 1

Thanks
Chandra


***@***.***

**Comment by chandraarora** [comment]
Hi

Please see the docs from Ms teams app

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider

When it is sending request to IDP , it add state parameters in the redirect uri and and it gets the response it callback the teams with these parameters.

Thanks
Chandra
