### ISSUE TITLE
least version 6.1.2 Conflicts with Identity.EntityFrameworkCore version 6.0.7

### ISSUE THREAD

**Issue by neozhu** [DuendeSoftware/Support#126]
![image](https://user-images.githubusercontent.com/1549611/179679499-09566378-b1f8-4929-9b38-7ee1a5ba099d.png)

![image](https://user-images.githubusercontent.com/1549611/179679358-b577dece-c736-4995-a166-b1714cc1174e.png)

System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Method 'get_ServerSideSessions' in type 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`1' from assembly 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer, Version=6.0.7.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'

**Comment by leastprivilege** [comment]
Microsoft's packages are built against an older version of IdentityServer - this would explain the incompatibilities.

https://www.nuget.org/packages/Microsoft.AspNetCore.ApiAuthorization.IdentityServer/6.0.7#dependencies-body-tab

**Comment by neozhu** [comment]
thank you for feedback
