### ISSUE TITLE
Can I apply the duende license in lower environments?

### ISSUE THREAD

**Issue by sudipster** [DuendeSoftware/Support#1262]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
6.0
**Describe the bug**
Just a quick question. We have a business license from Duende for IdentityServer. We have applied to Prod env. I am just wondering if I can apply the same license to other lower environments such as Dev/QA/Staging/etc.. No issues whatsoever. This is just to avoid the repeated license related messages from Duende getting logged to our logging system.
Thanks.

**Comment by RolandGuijt** [comment]
I can confirm this is allowed.
