### ISSUE TITLE
HexEncodingFormatSuffix -1  Why is this appended for hashing the key?

### ISSUE THREAD

**Issue by susan12-web** [DuendeSoftware/Support#1264]
**Which version of Duende IdentityServer are you using?** 6.3.3

**Which version of .NET are you using?**.net 8

**Describe the bug**

While saving the grants of access token generating grant key will be done with below lines  of code : 
 protected async Task<string> CreateHandleAsync()
 {
     return await HandleGenerationService.GenerateAsync() + HexEncodingFormatSuffix;
 }

Could you please let me know why this appending + HexEncodingFormatSuffix; is needed?

Bug :

Due to this append caas harness grant store will return as meesage as below : 

"Unable to fetch grants".

After removing the + HexEncodingFormatSuffix it worked.

Could you please explain the need of this ?

**Comment by AndersAbel** [comment]
The `-1` suffix indicates that a newer storage/encoding format is used for they keys. This is an implementation detail of our store implementation.

If you do write data directly to the store without using our store service you would have to handle the updated storage format that was introduced in Duende IdentityServer v6.

**Comment by josephdecock** [comment]
We go into more detail about this in our docs here: https://docs.duendesoftware.com/identityserver/v7/reference/stores/persisted_grant_store/#key-property

**Comment by RolandGuijt** [comment]
@susan12-web Assuming Anders' and Joe's comments answer your question I'm closing this. If not feel free to reopen.
