### ISSUE TITLE
IdentityServer 6.3.x security vulnerabilities 

### ISSUE THREAD

**Issue by LionelBergen** [DuendeSoftware/Support#1266]
**Which version of Duende IdentityServer are you using?**
6.3.8

**Which version of .NET are you using?**
6

**Describe the bug**

Security Vulnerabilities show up when running `dotnet list package --vulnerable --include-transitive`, for 2 dependencies

**To Reproduce**

Run `dotnet list package --vulnerable --include-transitive` inside `src/IdentityServer`

**Expected behavior**

No vulnerabilities 

**Additional context**

6.3.x is listed as maintained as long as .NET 6.0 is (until November 12, 2024)

**Comment by josephdecock** [comment]
We're going to release a maintenance patch that updates these 2 dependencies with vulnerabilities. In the meantime, you should be able to upgrade the impacted packages explicitly.

**Comment by RolandGuijt** [comment]
Please continue to track this with the issue shown above in the IdentityServer issue tracker. I'm closing this one.
