### ISSUE TITLE
Redirection to Dynamic Providers by domain

### ISSUE THREAD

**Issue by chana-Auerbach** [DuendeSoftware/Support#1278]
Hi,

We are using Duende 7.0.4, .net 8.

We want to use the **Dynamic Providers option** this way - 
Once a user enters his username, we want to redirect him to an SSO Identity Provider according to his domain.
Is there a built-in way to do that with Duende?

Also, we want to add an indication at the Identity provider – if it is in 'Migration Process' mode.

I want to use the **IdentityProvider.Properties** dictionary for this purpose. Is that OK? Or could this field type change to a more limited structure in future versions of Duende?

I appreciate any help you can provide.
Chana

**Comment by RolandGuijt** [comment]
Regarding your first question:
There is no built-in feature but probably it wouldn't be too hard to implement it yourself. If you create the initial login page with just an email address input field and when that's posted you can figure out the right identity provider and challenge the corresponding scheme.

About your second question:
Using that dictionary should be fine. We can't guarantee the structure will never change but right now there are no plans for that.

**Comment by chana-Auerbach** [comment]
Thanks, @RolandGuijt, for your clear response.

**Comment by RolandGuijt** [comment]
You're welcome. Closing this issue but if anything comes up around this issue please reopen.
