### ISSUE TITLE
Is it possible to add the “profile” scope during a refresh_token request?

### ISSUE THREAD

**Issue by hoofmen** [DuendeSoftware/Support#1279]
**Which version of Duende IdentityServer are you using?**
6.1.2
**Which version of .NET are you using?**
6.0.9

I need to include the “profile” scope as an implicit scope in all requests coming from clients. The “profile” scope needs to be included in when users refresh their token even if their initial sign-in did not include the “profile” scope.

Thank you!

**Comment by RolandGuijt** [comment]
That's not possible unfortunately. The access token you'll get back will contain the same scopes as the original access token.
If possible, you could get the access token with the required scope through the authorize endpoint again. When there's still a valid session you can instruct IdentityServer not do display any UI by using the prompt=none parameter.
Please see the authorize endpoint documentation [here](https://docs.duendesoftware.com/identityserver/v7/reference/endpoints/authorize/) for details.

**Comment by RolandGuijt** [comment]
@hoofmen Did my answer clear things up for you? If not, would you like to add to this issue?

**Comment by RolandGuijt** [comment]
Closing this. Feel free to reopen if you have something more around this issue.
