### ISSUE TITLE
Can I create a client on asp.net mvc using .NET Framework 4.7.2 to communicate with IdentityServer via Oauth2?

### ISSUE THREAD

**Issue by tienoho** [DuendeSoftware/Support#1280]
**Which version of Duende BFF are you using?**
IdentityServer 7.0.4
**Which version of .NET are you using?**
.NET Framework 4.7.2
**Describe the bug**

Can I create a client on asp.net mvc using .NET Framework 4.7.2 to communicate with IdentityServer via Oauth2?
If possible, could you please give me a sample?
thank you!!!!

**Comment by RolandGuijt** [comment]
Yes that is possible. Please see our example [here](https://docs.duendesoftware.com/identityserver/v6/samples/clients/) which uses .NET Framework 4.8 but it should work with 4.7.2 as well.

**Comment by RolandGuijt** [comment]
@tienoho Did things work out for you? If so I'd like to close this issue.

**Comment by RolandGuijt** [comment]
Closing this but feel free to reopen and add something if needed.

**Comment by 25Ericcheong** [comment]
Hi @RolandGuijt 

Quick question
If I had
- MVC app (.NET Framework 4.8) [all authentication currently being done through this]
- a SPA app
- Web API (.NET Framework 4.8)
- Other API (.NET 8)
- A newly upcoming Duende Identity Server

And I wanted to ensure that my user is still logged (authenticated) after logging in the first time as they navigate to/from the MVC app to the SPA app with the Duende identity server, would it be feasible? To main the cookie linked to the session managed by the Duende Identity Server? We have a few workarounds but I wanted an opinion and certain things to look out for moving forward

**Comment by AndersAbel** [comment]
@25Ericcheong This issue is since long closed, please open a new issue with your question to ensure we answer it.
