### ISSUE TITLE
Login with multiple clients

### ISSUE THREAD

**Issue by briansade** [DuendeSoftware/Support#1293]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
.Net8

**Describe the bug**
I have two client applications connecting to a single instance of Identity Server. When I click login from one, I am brought to the Login screen of Identity Server and can then log in. If I then go to the other client application and click Login it automatically logs me in as the same person that logged into the first application. 

**To Reproduce**
When I click login from one, I am brought to the Login screen of Identity Server and can then log in. If I then go to the other client application and click Login it automatically logs me in as the same person that logged into the first application. 

**Expected behavior**
I want to get to the Login screen and have to enter credentials every time I hit the Identity Server Login screen.

So my question is this a setting within Identity Server that I can control or where might the issue be? Is my idea an option, that no matter where I am redirected from and if I have logged in before or not I am brought to the login screen and have to enter my credentials.
I dont know if this is doing some kind of Server side sessions or if it is cookies. Anyway thanks in advance for the help.

**Comment by AndersAbel** [comment]
IdentityServer is designed to provide *single sign on* out of the box, where users can use multiple applications and only have to sign in once.

If you want to ensure that a user has re-entered their credentials every time they access a new application that can be controlled in a couple of ways:
* Set the [`UserSsoLifetime`](https://docs.duendesoftware.com/identityserver/v7/reference/models/client/#authentication--session-management) to a short value (a few seconds, zero might cause timing issues).
* Set `prompt=login` in the query string on the redirect from the client to IdentityServer. This behaviour must be validated on the client side when processing the login by checking the `auth_time` claim.

This works well if you want the user to enter their credentials for the *same user account*. If they would login as *a different user* that would overwrite the existing session and break any possibilities to do single logout for those.

If you want the sessions of the two applications to be completely independent you can have IdentityServer listen to two different host names and make each client use one host name each. (Note that this counts as another deployment of IdentityServer from a licensing perspective). This would also cause any access tokens issued from IdentityServer to have different issuer values. Downstream APIs must be adjusted to handle that.

**Comment by briansade** [comment]
Thank you
