### ISSUE TITLE
SQL Server script to update from 6.3 to 7.0

### ISSUE THREAD

**Issue by daver77** [DuendeSoftware/Support#1299]
Hi, our company uses Redgate SQL Change Automation for database source control, we don't use EF migrations. Currently I need to update our IdServer from 6.3 to 7.0, previously I have used the Quickstarts to seed a new database then use a SQL data conmpare tool to generate a migration script but the quickstarts seem to be using SqlLite now.

Is there a SQL Server script anywhere to make that easier for me?

**Comment by AndersAbel** [comment]
We do script out fresh database creation for SQL Server from the EF Migrations tooling at https://github.com/DuendeSoftware/IdentityServer/tree/main/migrations/IdentityServerDb/Migrations To get the right script for each version, please check the git tag.

**Comment by daver77** [comment]
Perfect, thank you!

**Comment by RolandGuijt** [comment]
@daver77 Closing the issue because it seems resolved for you. Feel free to reopen if anything else comes up.
