### ISSUE TITLE
License issues when running site on a load balancer

### ISSUE THREAD

**Issue by davidgspie** [DuendeSoftware/Support#1300]
Running IS6 on .NET 6

We have our site load balanced and with a full license from Duende - However, we're constantly getting an error in the logs

Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: ["https://ourcompany.org:443","https://ourcompany.org"]

I know there's a subtle distinction between https://ourcompany.org:443 and https://ourcompany.org, but is IdentityServer really seeing them as 2 different sites?

**Comment by davidgspie** [comment]
I should add that we get the error message around 2 times a second.

**Comment by RolandGuijt** [comment]
When an [IssuerUri](https://docs.duendesoftware.com/identityserver/v6/reference/options/#main) is not set in IdentityServer's options it is inferred from the incoming requests from clients.
A possible solution to this could be to check the authority URLs clients use and make sure they are consistent. The OIDC spec is requiring that the incoming authority URL is an exact match. And the URL with the port number is not an exact match with the one without.

Alternatively you can set the mentioned IssuerUri in the options to force a fixed issuer URL. The inference mechanism will then be disabled.

**Comment by RolandGuijt** [comment]
@davidgspie Does the thumbs up mean you've solved the issue? Would you like to add anything? If not I'd like to close this issue.

**Comment by RolandGuijt** [comment]
Closing for now. Feel free to reopen if there's anything to add.
