### ISSUE TITLE
Successful validation for non existing ResourceIndicators

### ISSUE THREAD

**Issue by Mendroch** [DuendeSoftware/Support#1305]
**Which version of Duende IdentityServer are you using?**

v7

**Which version of .NET are you using?**

.NET 8

**Describe the bug**

We are seeking to enable successful validation for ResourceIndicators that are syntactically valid, but do not exist. Unfortunately, the current documentation does not provide a solution for this particular scenario.

As a workaround, we have implemented an overridden method that clears the ResourceIndicators list. However, we are interested in exploring if there is a more efficient or recommended solution to address this issue.

Additionally, we would appreciate guidance on how to successfully validate ResourceIndicators that do not conform to the expected syntax.
```
public class CustomResourceValidator : DefaultResourceValidator
{
    public MediusResourceValidator(IResourceStore store, IScopeParser scopeParser, ILogger<DefaultResourceValidator> logger)
        : base(store, scopeParser, logger)
    {}

    public override async Task<ResourceValidationResult> ValidateRequestedResourcesAsync(ResourceValidationRequest request)
    {
        var newRequest = new ResourceValidationRequest
        {
            Client = request.Client,
            Scopes = request.Scopes,
            ResourceIndicators = []
        };
        return await base.ValidateRequestedResourcesAsync(newRequest);
    }
}

----------
    
identityServerBuilder.Services
    .AddTransient<IResourceValidator, CustomResourceValidator>();
```
**To Reproduce**

-
**Expected behavior**

Successful validation for scenarios described in guidance.

**Log output/exception with stacktrace**

-

**Additional context**

-

**Comment by AndersAbel** [comment]
To me this looks like working against how IdentityServer is designed. I guess this means that you have some kind of dynamic resources? The right way to implement that would be to create a custom `IResourceStore` that can handle the dynamic resources.

**Comment by RolandGuijt** [comment]
@Mendroch Has this issue been resolved for you? If so I would like to close it.

**Comment by Mendroch** [comment]
Our case is that we are migrating from IdentityServer3 to IdentityServer7, and we need to be backwards compatible with current calls. We noticed that some calls which are made contains resource parameter which seems not be validated in IdentityServer3 and started being validated in IdentityServer7. At the moment we found workaroud but we were wondering if there is a possibility to turn off this validation on code level.
 
If this is not possible we will continue with our current workaround, if you have any suggestions I'd be happy to hear them.

**Comment by AndersAbel** [comment]
@Mendroch can you please add more context? IdentityServer3 was a completely different product and the validation logic is rewritten.

I would not recommend turning off any of the built i validation, but rather try to create a custom `IResourceStore` that can handle the dynamic resources.

**Comment by RolandGuijt** [comment]
Closing this issue for now but feel free to add anything if needed.
