### ISSUE TITLE
Setting the redirect URIs

### ISSUE THREAD

**Issue by Simkiw** [DuendeSoftware/Support#131]
Hi,

I've seen in a few projects involving identity server, including the identity server quickstarts, the same redirect uri: **myApp/signin-oidc**

1. Is it a standard? Like, this is how it has been decided to be set?
2. Does the client app need to do anything about it? Like, create a specific endpoint? Because, again, in the examples apps I took a look at, I haven't seen any endpoint configured at **myApp/signin-oidc**

In that case, I could be configuring identity server 4 with any endpoint I want such as **myApp/redirect-somewhere** without having to define an endpoint like I would for a **"get rest api"** 

I hope I have been clear in the description.
Thank you

**Comment by brockallen** [comment]
> Is it a standard? Like, this is how it has been decided to be set?

It's simply the default callback path used by the Microsoft OIDC handler in ASP.NET Core.

**Comment by Simkiw** [comment]
Oh ok.

I must have missed the information. It's good to know or at least, i find it interesting to know how it works behind the scenes.

Thanks for enlightening me on this mistery.
