### ISSUE TITLE
federation/thirdparty/signin giving invalid device_id_missing

### ISSUE THREAD

**Issue by Rahul21199** [DuendeSoftware/Support#1310]
**Which version of Duende BFF are you using?**
6.3

**Which version of .NET are you using?**
8

the sigin endpoint throwing the following error. what could the reason and any possible solution

Message contains error: '"{
  \"code\": \"device_id_missing\",
  \"domain\": \"auth\"
}"', error_description: '"error_description is null"', error_uri: '"error_uri is null"', status code '400'.

**Comment by RolandGuijt** [comment]
We need more information to help you out.
It doesn't seem the error message is originating from BFF or from any standard flow at the identity provider. Please tell us more about your architecture: the type of frontend, which identity provider and where federation/thirdparty/signin could refer to. Is that an external identity provider perhaps?
Also: is there any code you're executing when a signin occurs where we should know about?

**Comment by RolandGuijt** [comment]
@Rahul21199 Did you manage to get this resolved? If so I'd like to close the issue.

**Comment by RolandGuijt** [comment]
Closing this for now but feel free to add to it if something comes up.
