### ISSUE TITLE
Identity server support for API developed in .Net Framework

### ISSUE THREAD

**Issue by PrabuLK** [DuendeSoftware/Support#1313]
**Which version of Duende IdentityServer are you using?**
Identity server 4

**Which version of .NET are you using?**
.Net Framework 4.8

**Describe the bug**
Unable to install the package for JWTBearer

We have a API developed in .Net Framework we need to install the package for JWTBearer for authentication.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
IdentityServer 4 is out of support but we have a full example with a .NET Framework webforms and API application that use IdentityServer 6 [here](https://github.com/DuendeSoftware/Samples/tree/f0f75acc37f58dcd9efb4bef08d6762192fc56c5/various/clients/Owin).

**Comment by RolandGuijt** [comment]
Closing this issue but feel free to add something.
