### ISSUE TITLE
[Question] How to "manually" check if user already logout from identity server?

### ISSUE THREAD

**Issue by ktutnik** [DuendeSoftware/Support#1322]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
v7

**Question**
We are planning to use [Server Side Session](https://docs.duendesoftware.com/identityserver/v7/data/operational/sessions/) and be able to logout user session from other device. Everything was fine until one of our old application (ASP.NET MVC 4.0) which maintain its own session, the application used identity server to login and after the login successfull it maintain the session itself using `FormsAuthentication.SetAuthCookie`. So removing server side session for this application wont make the user log out, because the application totaly disconnected with the Identity Server.

Im thinking of a way to "intercept" the request from Global.asax for each request, but the problem is how do I "manually" check if the current user already logout from the identity server.

**Comment by RolandGuijt** [comment]
@ktutnik Did my comment put you on the right track? If so I'd like to close this issue.

**Comment by RolandGuijt** [comment]
Closing this issue assuming my comment helped. Feel free to reopen if you'd like to add anything.
