### ISSUE TITLE
MFA verifytfa page shows login information including password in plaintext.

### ISSUE THREAD

**Issue by ChrisBHammond** [DuendeSoftware/Support#1324]
**Which version of Duende IdentityServer are you using?**
6.0.4.0
**Which version of .NET are you using?**
.Net 6

**Describe the bug**
With MFA on, after logging in you are sent to another page asking for the MFA code. In the URL of this page you can see the users login and password in clear text. 
For example. "/identity/verifytfa?Username=Chris@Mycompany.com&Password=PasswordInPlainText&ReturnUrl=%2Fconnect...."

**Expected behavior**
I would expect that the login information not be shown. 

I think we are missing a setting somewhere, but we are unsure of what. Any help would be greatly appreciated.

**Comment by StuFrankish** [comment]
Hey there @ChrisBHammond 👋
Duende IdentityServer doesn't implement MFA out the box - it's considered the responsibility of the hosting application during the interactive login process.

Where did you get your MFA implementation from?

**Comment by RolandGuijt** [comment]
@ChrisBHammond StuFrankish is correct here. Do you need any further assistance with this?

**Comment by RolandGuijt** [comment]
Closing this issue. Feel free to add if this turns out to be something IdentityServer related after all.
