### ISSUE TITLE
Custom error page when user is not active

### ISSUE THREAD

**Issue by consulting-dev** [DuendeSoftware/Support#1327]
Using Duende.IdentityServer 7 with .NET8.

We have an application which relies on Azure AD login. In the backend we synchronize users from Azure AD to our database.
Then after login in Azure AD we use IProfileService implementation to validate if user is enabled and active in the application.

Sometimes it happens that user can login in AzureAD, but IProfileService.IsActiveAsync sets context.IsActive = false;

This causes the issue that user is redirected back to AzureAD without giving any information what happened. In such a case AzureAD detects that user is already logged in - and redirects it back to return url without any login screen (so we get a redirect loop, which finally ends in "Login failed").

Is there any possibility in such situation to redirect user to custom error page?

**Comment by RolandGuijt** [comment]
Yes, the best place to do it is in the external login callback method, after the external identity is read from the cookie set by the external identity provider (using `AuthenticateAsync`). If you determine if the user is active there it should be easy to redirect to any page you want.

**Comment by consulting-dev** [comment]
Oh, totally missed that part.
Works like a charm. Thank you very much!
