### ISSUE TITLE
BffApi Attribute

### ISSUE THREAD

**Issue by SriramaDanturthi** [DuendeSoftware/Support#133]
**Which version of Duende BFF are you using?**
1.2.3
**Which version of .NET are you using?**
6.0
**Describe the bug**
if we add BffApi Attribute to local api endpoints we are not getting the Claims from the cookie authentication the claimsidentity from httpcontext is always unauthenticated.  the way we are trying to do is trying to inject httpcontextaccessor into to the service layer ang read the claims from the injected httpcontextaccessor.httpcontext.principal.claims we are always getting 0 claims if we add BffApi Attribute to that end point. Is there any way to over come this drawback by using bffApi attribute on locaal api endpoints ? or  Is that intended to use only with external api's ?

**Comment by leastprivilege** [comment]
Hi, 

this works and the BffApi attribute is unrelated to authentication state. Please check our samples and see if you can replicate this behavior.

https://docs.duendesoftware.com/identityserver/v6/samples/bff/
