### ISSUE TITLE
Add acr_values_supported to discovery document

### ISSUE THREAD

**Issue by fplorenzetti** [DuendeSoftware/Support#1331]
**Which version of Duende IdentityServer are you using?**
7.0.5

**Which version of .NET are you using?**
8.0

We are using the acr_values "idp:name_of_idp" to bypass the home realm discovery as described in the [documentation](https://docs.duendesoftware.com/identityserver/v7/reference/endpoints/authorize/). 

Is it possible to add the acr_values_supported to the discovery document https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata?

**Comment by RolandGuijt** [comment]
Yes that is possible. 
On the IdentityServer options object there is a Discovery object with a CustomEntries property that is a dictionary:

`options.Discovery.CustomEntries = new Dictionary<string, object> { { "acr_values_supported", new[] { "idp" } } };`

While this might change in future releases right now this is the easiest way.
