### ISSUE TITLE
Use multiple issuers when validating token for local API authentication

### ISSUE THREAD

**Issue by bgarel** [DuendeSoftware/Support#134]
**Which version of Duende IdentityServer are you using?**
6.0.4

**Which version of .NET are you using?**
6.0

**Question**
I'm changing the domain of my identity server site, from https://identity.mycompany.fr to https://identity.mycompany.net.
In order to not disturb my existing client apps and users, I would like to validate the access token provided by either identity.mycompany.fr or identity.mycompany.net (multiple issuers).

On the REST API client site, I can do it by using :
.AddJwtBearer(options =>
                ...
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidIssuers = new[] { newidentityUrl, previousIdentityUrl  }
                    };

On the IdentityServer site, I use .AddLocalApiAuthentication() to protect my local API hosted in the identityserver site. But I can't configure multiple issuers like in my REST client app.

Is there a way to configure multiple issuers in the local api authentication of IdentityServer ?

Regards,

**Comment by leastprivilege** [comment]
Local APIs pick up the currently configured issuer. 

Another option would be to hard-code the issuer name in the IdentityServerOptions.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
