### ISSUE TITLE
OpenId Connect provision within existing websites

### ISSUE THREAD

**Issue by DanielNewmanUK** [DuendeSoftware/Support#1340]
**Which version of Duende IdentityServer are you using?**
IdentityServer3

**Which version of .NET are you using?**
.Net Framework 4.8

**Describe the bug**

This is a question rather than a bug. 

We wish to utilise IdentityServer so that it will allow our applications to act as an OpenID Connect provider. We see lots of examples to do this using ASP.Net Identity or Entity Framework but in our case, we are using system.web.security.membership or a custom authentication scheme. 

How can we configure IdentityServer to use our existing authentication approaches? I saw a reference to adding custom stores, but there weren't any examples as to how to do this.

Thank you

**Expected behavior**

We are wanting our users to login to our applications using their existing methods. We then want to redirect our users to another application, which will authenticate this user based on the first application's logged in user. 

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
I'm sorry but IdentityServer3 has been out of support for a while now. 
But having said that: Microsoft's membership has a lot of shortcomings that doesn't make it suitable for an identity provider. But there is an [example](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot) with [MembershipReboot](https://github.com/brockallen/BrockAllen.MembershipReboot) that tried to overcome these problems.

**Comment by AndersAbel** [comment]
@DanielNewmanUK Just for the record, IdentityServer4 is also out of support. The only supported versions are Duende.IdentityServer 6.x and 7.x.
