### ISSUE TITLE
Third-party cookies

### ISSUE THREAD

**Issue by Birte-Teal** [DuendeSoftware/Support#1341]
**Which version of Duende IdentityServer are you using?**
7.0.6

**Which version of .NET are you using?**
.net 8

**Describe the bug**

We get third-party cookie warning on localhost.

![image](https://github.com/user-attachments/assets/f2eb6dbc-70dd-414f-b874-d7c67d148841)

Is this going to be a problem?

**Comment by RolandGuijt** [comment]
@Birte-Teal Did my comment help you? If so can we close the issue?

**Comment by RolandGuijt** [comment]
Closing for now, but feel free to reopen if needed.
