### ISSUE TITLE
Recommended Usage with SpaProxy

### ISSUE THREAD

**Issue by JeremyEastham** [DuendeSoftware/Support#135]
**Which version of Duende IdentityServer are you using?**

5.2.0+1c3f1fadb0fa7a4bea3f4a6f7028cbfcff3b9918

**Which version of .NET are you using?**

6.0.5

**Describe the bug**

I am currently working on an API server with an Angular frontend. During development, the Angular Development Server runs on `https://localhost:443` and the .NET API server runs on `https://localhost:442`. The Angular Development Server proxies all `/api` requests to the API server's root path.

When I add an external OAuth Provider using `AddOAuth`, I can specify a `CallbackPath` to change the `redirect_uri` URL parameter during the authentication flow. However, this path is relative to the API server and there is no obvious way to set the `redirect_uri` to `https://localhost:443/...`, since the API server's base path is `https://localhost:442`. I would like to have my URL paths remain consistent between development and production, so it would be beneficial to add a `RedirectURI` property to `OAuthOptions` that is an absolute URL to allow configuration with development proxy setups.

Since this proxy approach is now [Microsoft's recommended way](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#improved-single-page-app-spa-templates) to develop SPAs, the process for using IdentityServer with this setup should be streamlined in some way.

**Comment by leastprivilege** [comment]
We have a sample here: 

https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/ReactBffSample

it is not Angular - but React. They use the same front-end proxy approach. You need to white-list the redirect URI.

https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/BFF/ReactBffSample/src/FrontendHost/ClientApp/src/setupProxy.js#L10

**Comment by JeremyEastham** [comment]
Thank you, but this approach does not solve my issue. I am already using a proxy to redirect `/app/**` on my development server to `/` on my API/authentication server. The issue is that I want to use the development server's address as a base for the `redirect_uri` instead of the API/authentication server's address. This demo does not include an external OAuth provider sign-in flow.

Here is my current proxy configuration:
```js
// Angular proxy.conf.js proxy configuration file

const { env } = require( "process" )

const target = "https://localhost:442"; // Development API/authentication server URL

const PROXY_CONFIG = [
    {
        context: [
            "/api"
        ],
        pathRewrite: {
            "^/api": ""
        },
        target:  target,
        secure:  false, // true won't work with self-signed ssl certificate
        changeOrigin: true,
        ws: true,
        headers: {
            Connection: "Keep-Alive"
        }
    }
]

module.exports = PROXY_CONFIG
```

Here is my current server-side configuration:
```cs
// Abridged .NET 6 Program.cs using minimal APIs

//...

var builder = WebApplication.CreateBuilder( args );

//...

builder.Services.AddAuthentication()
       .AddOAuth( "discord", discord =>
        {
            discord.Scope.Add( "identify" );
            discord.Scope.Add( "email" );
            discord.SignInScheme          = IdentityServerConstants.ExternalCookieAuthenticationScheme;
            discord.AuthorizationEndpoint = "https://discord.com/api/oauth2/authorize";
            discord.TokenEndpoint         = "https://discord.com/api/oauth2/token";
            discord.ClientId              = "<client id>";
            discord.ClientSecret          = "<client secret>";
            discord.CallbackPath          = "/signin-discord";  // This line refers to https://localhost:442/signin-discord
            discord.SaveTokens            = true;               // I want it to refer to https://localhost:443/api/signin-discord
        } )
       .AddIdentityServerJwt();

builder.Services.AddIdentityServer()
       .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

//...

var app = builder.Build();

//...

app.UseAuthentication();
app.UseIdentityServer();
app.UseAuthorization();

//...

app.Run();
```

**Note:** Currently, I get stuck in a redirect loop after I approve access with the external OAuth provider (Discord), with no console output. Please let me know how I can fix my login flow.

**Comment by leastprivilege** [comment]
> This demo does not include an external OAuth provider sign-in flow.

It does - that's the `signin-oidc` path - that's the redirect URI. it's relative.

I do not see where you add the `signin-discord` to you dev proxy?

maybe this helps:
https://github.com/marleypowell/DuendeSamples/tree/marley/angular-sample/IdentityServer/v6/BFF/AngularBffSample

In particular:
https://github.com/marleypowell/DuendeSamples/blob/marley/angular-sample/IdentityServer/v6/BFF/AngularBffSample/FrontendHost/ClientApp/proxy.conf.js#L9-L16

**Comment by JeremyEastham** [comment]
The reason that `/signin-discord` is not in my proxy config is because it is not currently being proxied. `/signin-discord` currently refers to a path **on the API server** during development. I am looking for a way to use the **Angular development server's address** as a base for the callback, so that I can use the proxy to send the request to the API server. If I make this change, the callback path would be `/api/signin-discord` on the client server and would be proxied to `/signin-discord` on the API server during development.

I *could* leave this setup alone, but I would need to wrap every relative path on the server in a method that prepends `/api` to every path *only in production*. I could also just not use the `/api` prefix for API calls, but this would clutter the root path in production, taking paths that could potentially belong to frontend pages rather than backend API calls (ex: `/login`, `/link-account`, `/user`, etc).

Another benefit to the approach that I am attempting is that I would not have to alter my proxy config every time I add an API endpoint, since every path that starts with `/api` is being proxied with my current config.

Is there some sort of global configuration that houses the base path used to construct callback URLs?

**Comment by leastprivilege** [comment]
I am re-reading your original question, and now it is unclear to me how this is even related to IdentityServer?

I have shown you a canonical example: React front-end -> dev proxy -> asp.net host -> identityserver

This is how it is intended to be used - beyond that would be a question for Microsoft on how to use their SpaProxy.

**Comment by JeremyEastham** [comment]
I believe that I have fixed my problem:
```cs
app.UsePathBase( new PathString( "/api" ) );
app.MapControllerRoute( "default", "/{controller}/{action=Index}/{id?}" );

app.UsePathBase( new PathString( "/" ) );
app.UseStaticFiles();
app.MapFallbackToFile( "index.html" );
```

The above code makes all of my controllers available under `/api`, meaning that I can leave my proxy configuration alone. During development, the Angular development server proxies all API requests correctly, and in production, non-API requests fallback to `index.html` or static files. Thus, my URLs are consistent between development and production. This eliminates the need for me to change the callback URL (or edit any IdentityServer configurations), since a call to `/api/**` on `https://localhost:442`, `https://localhost:443`, or `https://mywebsite.com` should all achieve the same result.

Thanks for your assistance!
