### ISSUE TITLE
Update to 6.1.2 error : frame-ancestors

### ISSUE THREAD

**Issue by louisbouchard** [DuendeSoftware/Support#136]
Hello.

My Blazor Web Ass works fine localy.  Since I move to v6.1.2 (work fine before that) and pusblish to my server I got this issue 👍 

Refused to frame 'https://.....' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

VM69:2762 
        
       crbug/1173575, non-JS module files deprecated.

Any Idea

**Comment by brockallen** [comment]
What URL is that? I'm guessing the authorize endpoint? I can't think of anything related to that header that changed recently.

**Comment by brockallen** [comment]
Any update on this?

**Comment by louisbouchard** [comment]
You right Allen,

Now everything works #1

In SecurityHeadersAttribute.cs file I change this line 👍 

var csp = "default-src 'self'; object-src 'none'; frame-ancestors 'none'; sandbox allow-forms allow-same-origin allow-scripts; base-uri 'self';";

for this one

 var csp = "default-src 'self'; object-src 'none'; frame-ancestors 'self' *.mydomain.com; sandbox allow-forms allow-same-origin allow-scripts; base-uri 'self';";

And I have to put the right endpoints in thiose tables in the identityserver databases:

dbo.ClientCorsOrigins 
dbo.ClientPostLogoutRedirectUris 
dbo.ClientRedirectUris 

Hope it's can help
