### ISSUE TITLE
Why refresh token is having multiple access token in duende idp server version 7.0.5?

### ISSUE THREAD

**Issue by susan12-web** [DuendeSoftware/Support#1363]
**Which version of Duende IdentityServer are you using?** idp 7.0.5

**Which version of .NET are you using?** .net 8

**Describe the bug**

    /// <summary>
    /// Gets or sets the resource indicator specific access token.
    /// </summary>
    /// <value>
    /// The access token.
    /// </value>
    public Dictionary<string, Token> AccessTokens { get; set; } = new Dictionary<string, Token>();

Could you please let me know the use cases for making the above accesstoken as Dictionary in below file? 

    namespace Duende.IdentityServer.Models;

    /// <summary>
    /// Models a refresh token.
    /// </summary>
    public class RefreshToken

**Comment by RolandGuijt** [comment]
Refresh tokens could be configured to be used multiple times. This can be used by confidential clients and prevents the possible loss of a new refresh token due to network anomalies. 
Please see the documentation [here](https://docs.duendesoftware.com/identityserver/v7/tokens/refresh/#avoid-rotation).

**Comment by josephdecock** [comment]
It's also possible for a client to request authorization with multiple resource indicators and then use their refresh token with each specific resource indicator to get distinct token that are intended to be sent to different resources. This is useful when there is a trust boundary between resources.

**Comment by josephdecock** [comment]
See https://docs.duendesoftware.com/identityserver/v7/fundamentals/resources/isolation/#requesting-access-to-multiple-resources

**Comment by susan12-web** [comment]
thanks a lot for above information

**Comment by susan12-web** [comment]
Is the backward compatibility with IdentityServer 4 taken care by duende  got error as : 

System.Text.Json.JsonException: 'The JSON value could not be converted to Duende.IdentityServer.Models.AccessTokenType. Path: $.AccessToken.AccessTokenType | LineNumber: 0 | BytePositionInLine: 2835.'

But in duende its an enum as below : 


  /// <summary>
  /// Gets or sets the type of access token of the client
  /// </summary>
  /// <value>
  /// The access token type specified by the client.
  /// </value>
  public AccessTokenType AccessTokenType { get; set; }
  
  
  For the idp 4 version do we have to do a conversion as below for deserializing : 
  
  // To backward compatibility with IdentityServer 4:
                    //    if (jsonObj["Version"] == Common.Constants.Grants.IdentityServer4VersionValue)
                    //    {
                    //        jsonObj["AccessToken"]["AccessTokenType"] = (int)AccessTokenType.Reference;
                    //        string output = Newtonsoft.Json.JsonConvert.SerializeObject(jsonObj, Newtonsoft.Json.Formatting.Indented);
                    //        return Serializer.Deserialize<OpenBankingRefreshToken>(output);
                    //    }

**Comment by RolandGuijt** [comment]
@susan12-web This seems to be a new topic for this issue. It seems similar to [this issue](https://github.com/DuendeSoftware/Support/issues/1237) you raised a while ago. Can you please reopen that?

Closing this one for now but feel free to reopen if you have more questions about the refresh token topic.
