### ISSUE TITLE
Can I be logged into the OP, and have it send the token direct to the RP?

### ISSUE THREAD

**Issue by DanielNewmanUK** [DuendeSoftware/Support#1366]
This is clearly a question on the fundamentals of OIDC, and not so much your software. However, I'm hoping you can help.

As the title states, I want to send either a token to the RP and have it validate the token, or I want to send a command to the RP so it knows which OP to use. 

The use-case in question would be for an RP having multiple OIDC OPs configured. I want my user to be already logged into the OP, and for them to navigate to the RP and be authorized. I don't want the user to initiate an OIDC token request from within the RP. Can this be automated in some way?

All documentation states that it's the RP which initiates the process. I wish for the OP to initiate the process, as you can from an SSO IdP.

Many thanks

**Comment by RolandGuijt** [comment]
OIDC is designed around the principle that the RP initiates a token request.
For what you are referring to as "SSO IdP" this also is the case. It's just a normal OP with multiple RPs configured. When RP A initiates user authentication a session cookie is set which is then recognized when RP B authenticates in the same browser skipping login. But the RP still initiates the process.

Multiple OPs per RP aren't directly supported. But OPs can be a federation gateway and have [external identity providers](https://docs.duendesoftware.com/identityserver/v7/ui/login/external/) configured. Determining the best IdP for the user is called Home Realm Discovery. Users could be given the choice where to login (OP local account or external IdP) on the login screen for example. Or if the requirement is that certain RPs should always use a specific IdP (users don't get to choose) this can be done using the idp parameter on acr_values. We have a doc page on that [here](https://docs.duendesoftware.com/identityserver/v7/ui/federation/) with more possibilities to do Home Realm Discovery.

**Comment by DanielNewmanUK** [comment]
I've just seen within the Federation gateway link that "the client application can give a hint to the gateway via a custom protocol parameter of IdentityServer’s built-in support for the idp parameter on acr_values." This sounds perfect. I will investigate this option.

**Comment by AndersAbel** [comment]
OpenID Connect requires all login flows to be initiated from the client (RP) to be able to implement proper cross site request forgery protection on the login flow. To give the user the experience of Idp-initiated flow there is a section in the OIDC spec that describes how an OpenID Provider can redirect to a client and instruct the client to initiate the login flow, see https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin

**Comment by RolandGuijt** [comment]
I'm closing this issue for now. If something comes up please add to it.

**Comment by DanielNewmanUK** [comment]
@AndersAbel is there support for the Third Party initiated login within your library? Thank you

@RolandGuijt I was not present last week to respond to your closure request. Can you reopen this issue please?

**Comment by DanielNewmanUK** [comment]
@AndersAbel thank you for the response. I can see that you have added the InitiateLoginUrl parameter to the Client (https://docs.duendesoftware.com/identityserver/v7/reference/models/client/#third-party-initiated-login) but how does this work within your library? How can I initiate a login request from the OP? Many thanks

**Comment by AndersAbel** [comment]
Initiating the login from the OP would be part of a custom UI. We provide the configuration on the client object for convenience, but the actual implementation would have to be done by custom code in your UI.
