### ISSUE TITLE
How to add client certificate for SSL protocol when using AddClientCredentialsTokenManagement

### ISSUE THREAD

**Issue by arslanakhtar61** [DuendeSoftware/Support#1367]
`builder.Services.AddClientCredentialsTokenManagement()

    .AddClient("vendor.client", client =>
    {
        client.TokenEndpoint = "";
        client.ClientId = "";
        client.ClientSecret = "";
        client.ClientCredentialStyle = ClientCredentialStyle.PostBody;
        client.Parameters.Add("audience", "");
        // How to add X509Certificate for ssl mutual tls when calling for access token?
    });
`

**Comment by RolandGuijt** [comment]
It isn't supported directly like that but it should be possible:

The main thing that is needed is to attach the client's certificate to the HttpClient via the SocketsHttpHandler. AccessTokenManagement doesn't do that automatically for you. We have a [sample](https://github.com/DuendeSoftware/Samples/blob/9b7fdf7d2a4e7a3efb205ab9bf61d10a57f189ba/IdentityServer/v7/MTLS/ClientCredentials/Program.cs#L51) of mTLS that doesn't use AccessTokenManagement.

By configuring IHttpClientHandler like [this](https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory#using-ihttpclientfactory-together-with-socketshttphandler) you should be able to get it to work:

```
.AddClient("vendor.client", client =>
{
   ..
}).ConfigurePrimaryHttpMessageHandler( ... );
```

**Comment by RolandGuijt** [comment]
If this answered your question I would like to close the issue. If not feel free to add a comment.

**Comment by RolandGuijt** [comment]
Closing for now, but feel free to reopen if anything comes up.
