### ISSUE TITLE
Cannot find clients created using DCR in DB

### ISSUE THREAD

**Issue by mdighe10** [DuendeSoftware/Support#1368]
**Which version of Duende IdentityServer are you using?**: 7

**Which version of .NET are you using?**: 8.0

**Describe the bug**: Configuration API gives success with Client ID and secret but not able to find those clients in DB.

I have configured Configuration API as mentioned in Quickstarts for DCR flow. It is hosted in separate project and not in the same ID Server. I am also using RSK AdminUI with ID Server.

After calling Configuration API to register new Client, it gives me success response with Client ID and Secret. But when I checked in the SQL DB, I was not able to see any new client being created, same I checked in the AdminUI and no new client could be seen.

**To Reproduce**

Steps to reproduce the behavior.
Follow steps from this documentation.
https://docs.duendesoftware.com/identityserver/v7/configuration/dcr/
**Expected behavior**
There is no error but in the DB I don't see newly created client.
I wanted to see new Client in SQL DB and its properties.
**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
I just did some experiments and the feature does seem to work as normal. Is there any indication on what's wrong in the logs?
Also, could you please run [the sample code](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v7/Configuration/Permissions) and see if that works. If it does you can maybe determine what's wrong by comparing the code to yours.
Please report back when you find any specifics so we can investigate further.

**Comment by RolandGuijt** [comment]
@mdighe10 Is this still an issue for you? If so please feel free to answer my questions. If not, I would like to close this issue.
