### ISSUE TITLE
Consider making ValidateExtensionGrantRequestAsync virtual

### ISSUE THREAD

**Issue by jasonliao-cb** [DuendeSoftware/Support#1369]
https://github.com/DuendeSoftware/IdentityServer/blob/e9860c6488f90e8fbc11a4452b9dd111dbfae933/src/IdentityServer/Validation/Default/TokenRequestValidator.cs#L981
Could you tell me what this function is? Can we make it overridable if it is used for extended grant types? we have an on-behalf-of grant type but it always generates a refresh_token and we would like to remove the offline_access scope when the request comes.

**Comment by RolandGuijt** [comment]
Looks like your question was answered. Closing this issue for now but feel free to reopen if you would like to add something.
