### ISSUE TITLE
Third Party Cookie and Identity Server 

### ISSUE THREAD

**Issue by kkdeveloper7** [DuendeSoftware/Support#1380]
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**
8

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

**Additional context**

According to google, in 2024 Q4 Third party cookies will be phased out, perhaps this will be extended [here](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct#:~:text=Chrome%20plans%20to%20ramp%20up,UK%27s%20Competition%20and%20Markets%20Authority). I noticed that after login, Identity Server drops 2 cookies

1. idsrv
2. idsrv.session (this cookie is dropping with SameSite=None; Secure)

Since one of the cookies is dropped with SameSite=None, are we going to be affected by this? Anything we need to do going forward?

**Comment by RolandGuijt** [comment]
Google had the intention to do this but they decided to not implement the plan. See [here](https://www.theverge.com/2024/7/22/24203893/google-cookie-tracking-prompt-ad-targeting-privacy-sandbox).

For context: The idsrv.session cookie is required by the OIDC session management spec for JS/SPA clients and it implements [this spec](https://openid.net/specs/openid-connect-session-1_0.html#ChangeNotification).

**Comment by RolandGuijt** [comment]
@kkdeveloper7 Did this answer your question? If not please add to this issue. If not I'd like to close it.

**Comment by kkdeveloper7** [comment]
> @kkdeveloper7 Did this answer your question? If not please add to this issue. If not I'd like to close it.

yes, thank you!
