### ISSUE TITLE
Support for multiple dynamic identity providers with the same scheme

### ISSUE THREAD

**Issue by niranjan-k-p** [DuendeSoftware/Support#1383]
**Which version of Duende IdentityServer are you using?**
v5 (upgrading to v7 soon)
**Which version of .NET are you using?**
.net 5(upgrading to 8 soon)
**Describe the bug**
(Not a bug, but a question)
We are implementing dynamic identity providers, which requires us to support identity providers with the same scheme but different authority url(and different client id). What I understand from Duende documentation is that the scheme is unique. Can you confirm that this understanding is correct? 

To get around the problem with unique schemes in the identity store, we implemented a custom identity store with a custom implementation for GetBySchemeAsync. Although this may help partially, the external identity provider resolution during Challenge fails. 

Is this something that is supported in v7? Is there some documentation that we can refer to implement this behavior the correct way? 
**To Reproduce**
An example: 
We have 2 clients that need external identity provider support, both these clients use Microsoft entra as their Idp but I can resolve only 1 "entra" scheme in the identity store. 

Let me know your thoughts. Thanks!

**Comment by AndersAbel** [comment]
The Duende dynamic providers feature is built around the assumption that each provider is a separate authentication scheme. If you want the display name to be the same, please use the display name property for that, but you need distinct schemes for each provider.

Our dynamic providers solution is designed around the assumption that the configuration for each scheme name is static. The dynamic providers feature is designed to scale even with thousands of external providers registered.

Closing this issue as it's already been addressed through another support channel.
