### ISSUE TITLE
ChangePasswordAsync issue with same email and diffrance tanant- either give user as input 

### ISSUE THREAD

**Issue by alijkdkar** [DuendeSoftware/Support#1386]
**Which version of Duende IdentityServer are you using?**
7.0.5
**Which version of .NET are you using?**
.net 8
**Describe the bug**
in change password method (ChangePasswordAsync) with  diffrance tenant either method get user clearly as input but throw error that "Sequence contains more than one element"

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
The method `ChangePasswordAsync` is not part of IdentityServer. IdentityServer doesn't have a built-in user store (except for a very simple in-memory one for demo purposes). You're probably using ASP.NET Core Identity which does have `ChangePasswordAsync`.

Having said that:
To solve the issue I would take a look at the source code for the method. It seems that when the user is retrieved (probably using the user id) the `First` or `Single` Linq method is used and in your database there are multiple users that match the query.

Unfortunately this is all we can offer in this issue tracker. Please open an issue on the ASP.NET Core Identity issue tracker if you need further discussing of the issue.

**Comment by RolandGuijt** [comment]
I'm closing this issue for now. If you have any additional comments about our products in relation to this issue feel free to reopen and add to it.
