### ISSUE TITLE
Question about AccessTokenManagement 

### ISSUE THREAD

**Issue by auslavs** [DuendeSoftware/Support#1388]
**Which version of Duende.AccessTokenManagement are you using?**
3.0.0

**Which version of .NET are you using?**
.NET 8

This is a bit of a strange request, but it is possible change the Header that the Bearer token is stored in?

We have a use case where we would like to add a prefix the Authorization header.

**Comment by RolandGuijt** [comment]
No that is not possible. Reason is that the header should be in the format the [spec](https://www.rfc-editor.org/rfc/rfc6750#section-2.1) dictates.

What are you trying to do? Maybe we can provide a solution in another way?

**Comment by auslavs** [comment]
Thanks for the response and that makes perfect sense that you don't allow it.

We have a strange case where we need to send two access tokens in one request.
I understand that this is not advised, and we have managed the risks in other ways.

After a bit of research it should be straightforward to achieve with a custom DelegatingHandler.
