### ISSUE TITLE
intermittent invalid grant type for desktop app client

### ISSUE THREAD

**Issue by aaron-0** [DuendeSoftware/Support#139]
IdentityServer v6.04
.NET 6.0.301

We are receiving intermittent issues when one of our desktop app clients tries to log in. We have received the error 6 times in the last 7 days, with 1331 successful logins for that client.

There error message in our logs is:
`Invalid grant type for client: authorization_code
{
	"ClientId": "desktop",
	"ClientName": "desktop client",
	"RedirectUri": http://localhost/winforms.client,
	"AllowedRedirectUris": [
		http://localhost/winforms.client
	],
	"SubjectId": "anonymous",
	"ResponseType": "code",
	"ResponseMode": "query",
	"GrantType": "authorization_code",
	"RequestedScopes": "",
	"State": "***",
	"PromptMode": "",
	"Raw": {
		"response_type": "code",
		"nonce": "***",
		"state": "***",
		"code_challenge": "***",
		"code_challenge_method": "S256",
		"client_id": "desktop",
		"scope": "openid profile offline_access somescope",
		"redirect_uri": http://localhost/winforms.client
	}
}`

Authorize URL in our logs: https://www.domain.com/identity/connect/authorize?response_type=code id_token&nonce=***&state=***&code_challenge=***&code_challenge_method=S256&client_id=desktop&scope=openid profile offline_access somescope&redirect_uri=http%3A%2F%2Flocalhost%2Fwinforms.client

The client is a winforms desktop client with details:
Id: desktop
Allowed grants: hybrid
Allowed urls: http://localhost/winforms.client

I have turned on Information level logging for our dev environment, and this is a log entry for a successful login by me:

`Token request validation success, {
	"ClientId": "desktop",
	"ClientName": "desktop client",
	"GrantType": "authorization_code",
	"AuthorizationCode": "****37-1",
	"RefreshToken": "********",
	"Raw": {
		"grant_type": "authorization_code",
		"code": "***",
		"redirect_uri": "http://localhost/winforms.client",
		"code_verifier": "***",
		"client_id": "desktop"
	}
}`

Authorize URL in our logs: https://dev.domain.com/identity/connect/authorize?response_type=code id_token&nonce=***&state=***&code_challenge=***&code_challenge_method=S256&client_id=desktop&scope=openid profile offline_access somescope&redirect_uri=http%3A%2F%2Flocalhost%2Fwinforms.client

Any ideas on why this client would be intermittently getting this error? Please let me know if there is further information I could provide.

**Comment by leastprivilege** [comment]
The only thing that stands out is - your allowed grant type is set to hybrid - but `code` is used on the authorize request.

Try setting the allowed grant type to code as well.

**Comment by aaron-0** [comment]
Thanks for the reply. I'll try adding `code` and see if that resolves the issue.
I'll also start a conversation about migrating to a new client which is authorization_code + pkce rather than hybrid.

**Comment by brockallen** [comment]
Any update on this?

**Comment by aaron-0** [comment]
I have changed our configuration for that client to:
`"AllowedGrantTypes": [ "hybrid", "code" ]`
So far, I have seen no errors in our logs. It will take a few more days to confirm.

I ran into this while playing with the configuration:
`DisallowGrantTypeCombination(GrantType.AuthorizationCode, GrantType.Hybrid, grantTypes);`
Not sure if the config I have specified poses a risk?

I've also created a new client, which is authorization_code + pkce.  But migration will take a while due to software being installed on customer computers.

**Comment by brockallen** [comment]
That's intended to protect against downgrade attacks where an attacker could pass just "token" and get back the tokens on the front channel, thus bypassing the protection of the back channel.

**Comment by aaron-0** [comment]
It doesn't look like the workaround has helped, we just received the same error. I can't try "AllowedGrantTypes": [ "hybrid", "authorization_code" ] as that is blocked.

I think my best way forward is going to be to encourage the client application to roll out with an updated client and encourage customers to upgrade if they get the error.

**Comment by brockallen** [comment]
Yes, sounds like the best approach, and then you can deprecate/remove the old client config hopefully soon.
