### ISSUE TITLE
Feature Request: Additional Cache Control Directives for Discovery Endpoints

### ISSUE THREAD

**Issue by pcappaert** [DuendeSoftware/Support#1399]
The `DiscoveryOptions` class has a property `ResponseCacheInterval` that when set will populate the max-age directive of the Cache-Control header. There are other directive for this header that would be useful to be able to configure. In particular I am interested in the stale-if-error directive. The directive would allow proxies to continue to serve the discovery endpoints from a stale cache when the origin is unavailable. This would allow us to maintain a higher uptime for the discovery endpoints.

**Comment by RolandGuijt** [comment]
I'm transferring this to the IdentityServer repository so the feature will be considered.
In the meantime it should be possible to create a custom middleware that inserts the desired headers.

**Comment by RolandGuijt** [comment]
Please track this issue from there from now on as I'm closing this support issue.
