### ISSUE TITLE
How to process the access to the resourses with 2FA-privilege via IdentityServer?

### ISSUE THREAD

**Issue by denhat** [DuendeSoftware/Support#14]
**Which version of Duende IdentityServer are you using?**
Duende IdentityServer 6.0.4

**Which version of .NET are you using?**
.NET 6

In our solution we have cases when a user must additionally authenticate himself with OTP (2-factor auth) to get access to some API-endpoints of our web service.
The flow is:
1. User visits the page requiring additional OTP-authentication.
2. The client checks if OTP is required and if yes - redirects the user to /authorize (since user hasn't been authenticated with OTP yet).
3. Identity Server redirects the user to OTP-authentication page. User provides an OTP received from some provider. 
4. After 2FA-authentication is done successfully the user is redirected to the page he visited on the first step. 
5. When session ends (e.g. browser is closed) the user's OTP-authentication must be revoked.
6. Also we are planning to limit this OTP-session of a user with 15 min. So after 15min has passed the user must authenticate himself with OTP again.

We couldn't find any option of implementing that with IdentityServer lib. 
We tried to used "**acr_values**" parameter to send "**otp**" value - to let IdentityServer know that the user has to authenticate with OTP (see https://openid.net/specs/openid-connect-core-1_0.html#:~:text=the%20OP%27s%20discretion.-,acr_values,-OPTIONAL.%20Requested%20Authentication).
We implemented custom **AuthorizeInteractionResponseGenerator** (**ProcessLoginAsync** method) to redirect user to 2FA-page when /authorize request (step 3):
```
protected override async Task<InteractionResponse> ProcessLoginAsync(ValidatedAuthorizeRequest request)
{
    var response = await base.ProcessLoginAsync(request);
    if (response.IsConsent || response.IsLogin || response.IsError || response.IsRedirect)
        return response;

    var acrValues = request.GetAcrValues() ?? Array.Empty<string>();
    if (acrValues.Contains(OidcConstants.AuthenticationMethods.OneTimePassword))
    {
        Logger.LogDebug("2FA_REQUIRED_FLOW: Redirect to Set-2FA-page");

        var returnUrl = $"{Configuration.BaseUrl}/connect/authorize/callback"
            .AddQueryString(OidcConstants.AuthorizeRequest.ResponseType, request.ResponseType)
            .AddQueryString(OidcConstants.AuthorizeRequest.ClientId, request.ClientId)
            .AddQueryString(OidcConstants.AuthorizeRequest.State, request.State)
            .AddQueryString(OidcConstants.AuthorizeRequest.RedirectUri, request.RedirectUri)
            .AddQueryString(OidcConstants.AuthorizeRequest.Scope, string.Join(' ', request.RequestedScopes))
            .AddQueryString(OidcConstants.AuthorizeRequest.Nonce, request.Nonce)
            .AddQueryString(OidcConstants.AuthorizeRequest.CodeChallenge, request.CodeChallenge)
            .AddQueryString(OidcConstants.AuthorizeRequest.CodeChallengeMethod, request.CodeChallengeMethod);

        //request.RemoveAcrValue(OidcConstants.AuthenticationMethods.OneTimePassword);
        return new InteractionResponse { RedirectUrl = $"/Account/Require2fa?userName={request.Subject.Identity.Name}&returnUrl={HttpUtility.UrlEncode(returnUrl)}" };
    }

    return new InteractionResponse();
}
```
Also we implemented **ICustomTokenRequestValidator** to set "**otp**" value in "**amr**"-claim in tokens:
```
public Task ValidateAsync(CustomTokenRequestValidationContext context)
{
	var request = context.Result.ValidatedRequest;
	var identity = request.Subject.Identity as ClaimsIdentity;
	if (request.Subject.IsAuthenticated())
	{
		var user = _users.FindByUsername(identity.Name);
		if (user != null && user.AuthenticatedWith2Fa)
		{
			identity.AddClaim(new Claim(JwtClaimTypes.AuthenticationMethod, OidcConstants.AuthenticationMethods.OneTimePassword));
		}
	}

	return Task.CompletedTask;
}
```
However, when a token is requested we need to know if a user is OTP-authenticated (user.AuthenticatedWith2Fa flag here) to set "amr" claim in the token properly. So we have to **store this information in DB which is not correct** - if the user authenticates in another browser/device the system behaves like if he has already been OTP-authenticated but he hasn't.
Besides, we still don't have a possibility to limit the time of an OTP-session (in our app we use refresh token as a user-session, so it should be active for 8 hours which is longer than OTP-session).

Are there any options to implement that flow properly at present? Or maybe you're planning to implement this feature in the future? 
Thanks.

**Comment by brockallen** [comment]
Normally you maintain "amr" claims related to how the user authenticated in the user's authentication session, which is to say in the cookie. So as the user performs these additional steps to login, your UI can re-issue the call to SignInAsync with the additional "amr" claim. That's what our helper does internally: https://github.com/DuendeSoftware/IdentityServer/blob/6a45df770da336604801bddca593a902f1ccb802/src/IdentityServer/IdentityServerUser.cs#L70

You'd then include these as necessary in the profile service (not sure if you really need `ICustomTokenRequestValidator`). 

And yes, you do want to add your acr_values check/logic to the `AuthorizeInteractionResponseGenerator` to trigger the UI if the current user's session does not have the claims you're expecting (otherwise you'll get SSO, which I'm sure you ran into).

**Comment by denhat** [comment]
Thanks for the quick answer!

However, I missed some details in my description - there is a problem with suggested solution because we have **clients on the domains differ from IS-domain** (at least three domains involved).
As a result, we cannot use Cookie-session (iframe is not safe - we use refresh token as a user-session). Custom session-manager is not an option for us. So, the point is that when refreshing tokens we need to get information that a user is authenticated with OTP. Currently we store this information in DB (our implementation of ProfileService works with DB). 

According to the above the question is like **how can we manage cross-origin user-sessions via IdentityServer (add/remove some custom session-information and work with it)?**

**Comment by brockallen** [comment]
> According to the above the question is like how can we manage cross-origin user-sessions via IdentityServer (add/remove some custom session-information and work with it)?

I am not following how your OTP requirement is related to corss-domain and iframes. But for token renewal and front-channel logout, you are correct -- browsers are breaking how things work cross-domain. This is why we have seen customers move to the [BFF Architecture](https://docs.duendesoftware.com/identityserver/v6/bff/).

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
