### ISSUE TITLE
Logging out from Identity Server is not Triggering Backchannel Logout

### ISSUE THREAD

**Issue by SriramaDanturthi** [DuendeSoftware/Support#141]
**Which version of Duende IdentityServer are you using?**
6.1.2
**Which version of .NET are you using?**
6.0
**Describe the bug**
When the use is trying to log out from the identity server instead of logging out from the application it is not notifying the connected apps about the back channel logout is triggered

Note: We are using Quick Start UI and did not made any changes in the ui

enabled these two options in sts
options.ServerSideSessions.RemoveExpiredSessions = true;
options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;

**To Reproduce**
login to any application and go to identity server and hit the logout button. it will log the user out from the application but the application is not redirected to login where as if the application triggered the logout it will be redirected to login page.
Steps to reproduce the behavior.

**Expected behavior**

Application should be redirected to login.

**Comment by brockallen** [comment]
By default, the Microsoft OIDC handler does not implement the back channel logout endpoint, so you need to implement that yourself in the client (or use our BFF back channel logout feature). Also, the client config in IdentityServer needs to be configured by settings the `BackChannelLogoutUri`:

https://docs.duendesoftware.com/identityserver/v6/reference/models/client/#authentication--session-management

Have you done those two things?

We have a sample that shows it working: https://docs.duendesoftware.com/identityserver/v6/samples/basics/#mvc-client-with-back-channel-logout-notifications

**Comment by SriramaDanturthi** [comment]
I have implemented these and its working fine if we initiate logout from client application. where as if we logout from sts its not triggering . and from serversidesessions page its working fine aswell. only thing not working is when we hit on logout on the sts side its not triggering back channel logout

**Comment by brockallen** [comment]
Hmm... does your logout page look any different than the sample I linked above? I know that works from our quickstart UI code.

**Comment by brockallen** [comment]
Any update on this?
