### ISSUE TITLE
Use example.com subdomains instead of "real" domain names

### ISSUE THREAD

**Issue by wenz** [DuendeSoftware/Support#1411]
The sample code is referring to "real" domain names such as alice.com, bob.com, and email.com. I would propose to change that to, say, alice.example.com, bob.example.com, and example.com to make crystal-clear that these really are examples. Just imagine one of those domains (especially the first two) gets cybersquatted.

I've filed (and fixed) a similar issue in the `Samples` repository: https://github.com/DuendeSoftware/Samples/issues/209

**Comment by wenz** [comment]
Pull request: https://github.com/DuendeSoftware/BFF/pull/202

(Please move the issue to the `BFF` repo.)

**Comment by RolandGuijt** [comment]
Can't move the issue but PR was approved and merged. Closing the issue. Thanks!
