### ISSUE TITLE
IdentityServer unhandled exception that logs db credentials

### ISSUE THREAD

**Issue by gunnars04** [DuendeSoftware/Support#1412]
**Which version of Duende BFF are you using?**
6.3.10
**Which version of .NET are you using?**
.net 6
**Describe the bug**
IdentityServer unhandled exception that logs db credentials

**To Reproduce**
Happens randomly
Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**
{ "Level": "ERROR", "Date": "2024-09-19T10:20:26.8935421Z", "Logger": "Microsoft.EntityFrameworkCore.Database.Connection", "Message": "An error occurred using the connection to database '*my db*' on server '*my azure sql database server*'.", "Application": "*my identityserver*", "CallSite": "Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log", "Thread": "10" }
{ "Exception": {"Type":"System.Threading.Tasks.TaskCanceledException", "Task":{"Id":1, "Status":"Canceled", "IsCanceled":true, "IsCompleted":true, "IsCompletedSuccessfully":false, "CreationOptions":"None", "AsyncState":{"StatisticsEnabled":false, "ConnectionString" * my sql connection strings get ouputted with sql user/pass*
```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
It looks like this error is coming from Entity Framework and it happens when an operation is cancelled. It isn't specific to BFF.

Things to try:
- Check if the [logging of sensitive data](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/simple-logging#sensitive-data) is enabled
- Switch to a lower log level for Entity Framework

If that doesn't work please post an issue on the Entity Framework issue tracker.

**Comment by RolandGuijt** [comment]
@gunnars04 Did my suggestions help you out? If so I would like to close the issue.

**Comment by gunnars04** [comment]
@RolandGuijt 
No I'm not using anywhere: EnableSensitiveDataLogging
If you're suggesting I do something like this, it would not solve the problem:

My log level is the following in appsettings.json

  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Error"
    }
  },

What are you suggesting? I don't wan't to supress all EF errors if that's what you mean.

**Comment by gunnars04** [comment]
@RolandGuijt 
If I look at the error more closely (deeper into the error).
"Level": "ERROR", "Date": "2024-10-03T08:20:56.4979187Z", "Logger": "Microsoft.EntityFrameworkCore.Query", "Message": "An exception occurred while iterating over the results of a query for context type 'Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext'.

Other error (seperate from the one above) but at the exact time:
```
Logger: Microsoft.EntityFrameworkCore.Database.Connection
Message: An error occurred using the connection to database '[mydbname]' on server '[myserver].
```

**Comment by RolandGuijt** [comment]
Entity Framework Core is throwing this error if an operation was cancelled. The logging behavior of Entity Framework is not related to any of our products, so I'm closing this issue. 

I'm not suggesting to suppress any errors. Instead I would recommend you ask this question on the Entity Framework issue tracker as mentioned earlier or contact Azure SQL support.
You could also take a look at [filtering](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#filter-function) the logs.
