### ISSUE TITLE
ClientCredentialsTokenHandler doesn't work with Apigee due to use of token_type for auth scheme

### ISSUE THREAD

**Issue by rhyscooper** [DuendeSoftware/Support#1413]
Which version of Duende.AccessTokenManagement are you using?
Duende.AccessTokenManagement 3.0.0

Which version of .NET are you using?
net8.0

The ClientCredentialsTokenHandler from Duende.AccessTokenManagement doesn't work with Apigee's oauth 2.0 bearer token implementation due to the token_type being returned being "BearerToken" instead of "Bearer". "BearerToken" is invalid for use as an auth header scheme, therefore all api requests fail with 401. It's clear that Apigee is non-compliant (https://docs.apigee.com/api-platform/reference/policies/oauthv2-policy#non-rfc-compliant-behavior), however as we are consuming someone else's API, we don't control this. 

This is similar to the closed issue reported https://github.com/DuendeSoftware/Duende.AccessTokenManagement/issues/38, however that is purely related to case sensitivity of token_type rather than an entirely different token_type being returned from the token api.

It would be useful to be able to override the scheme in the ClientCredentialsClient config and use that instead of the value returned as the token_type.

**Comment by leastprivilege** [comment]
Where in the code do you see `BearerToken` added to the header?

**Comment by rhyscooper** [comment]
Unfortunately "BearerToken" is returned as the "token_type" from Apigee oauth api

https://docs.apigee.com/api-platform/reference/policies/oauthv2-policy#non-rfc-compliant-behavior

**Comment by leastprivilege** [comment]
That is unfortunate indeed.

From a spec point of view we should only accept `Bearer` or `DPoP` - this wouldn't work with Apigee either. Did you open an issue with them to ask why they are using a proprietary token type?

**Comment by rhyscooper** [comment]
I haven't as yet, I was hoping we could resolve this on our end as we're not in control of the API that we're consuming. The issue arose because we upgraded the AccessTokenManagement library from version 1 to 3. Version 1 was fine because it was hardcoded to Bearer, but now that it's taking the token_type as the scheme, it means we can't upgrade the package. Apigee are clearly aware that it's not standards compliant and have provided a workaround, but I'm not confident that our customer will update their API as it's been working "fine" up until now.

**Comment by RolandGuijt** [comment]
@rhyscooper Do you have any additional questions for us regarding this issue? If not I'd like to close it.
