### ISSUE TITLE
Upgrading from IdentityServer v6.2 to v6.3 causes invalid request related to proof of possession

### ISSUE THREAD

**Issue by brkmover** [DuendeSoftware/Support#1414]
**Which version of Duende IdentityServer are you using?**
v6.2.5

**Which version of .NET are you using?**
net6.0

**Describe the bug**
When upgrading to v6.3 we experience that suddenly when calling the `connect/token` endpoint, with a refresh token, we receive the following error.

```
{
    "error": "invalid_request",
    "error_description": "Proof of possession can't be used on subsequent token requests unless used when requesting the initial refresh token."
}
```

**To Reproduce**
Steps to reproduce the behavior.

We call the `connect/token` endpoint with the following first.

```
{
    "client_id":"abc",
    "client_secret":"{{_client_secret}}",
    "scope":"openid profile email organization-selection offline_access",
    "grant_type":"password",
    "username":"johndoe@example.com",
    "password":"123456789"
}
```

Then we make a call to our own custom endpoint, see the code here https://gist.github.com/brkmover/57350b1afe450f3d83ff35f25d40aab5. Note, this code works in v6.2 but not in v6.3.

Using the refresh token from the above custom code in the gist we make another call to the connect endpoint as follows.

```
{
    "client_id":"abc",
    "client_secret":"{{_client_secret}}",
    "grant_type":"refresh_token",
    "refresh_token":"{{_refresh_token}}"
}
```

This now results in the PoP error.

**Expected behavior**

Retrieving a valid token using the generated refresh token.

**Additional context**

We are using the Starter edition license.

**Comment by josephdecock** [comment]
Hi, sorry to keep you waiting!

This error is logged when token validation sees that a refresh token record was created without any proof-of-possession info (no a null `ProofType`), but then a subsequent request tried to use proof-of-possession. This check was added in 6.3 when we added support for RFC 9449 (DPoP), but the logic could apply to the older mTLS proof of possession as well. 

I suspect that you are using mTLS. If so, when you create the refresh token, you should set the `ProofType` of the creation request  to `ProofType,ClientCertificate` instead of `ProofType.None`.

**Comment by brkmover** [comment]
Hi,

Thanks for the suggestion, it worked.

Just to understand it better, if we use a certificate in our API's does that implicitly mean that it's used as proof-of-possession?

**Comment by josephdecock** [comment]
Yes - If you've configured your client to authenticate via mtls as described [here](https://docs.duendesoftware.com/identityserver/v7/tokens/authentication/mtls/), then the tokens produced for that client [will be bound](https://docs.duendesoftware.com/identityserver/v7/tokens/pop/mtls/) to the client's tls certificate thumbprint.

**Comment by RolandGuijt** [comment]
@brkmover Are there additional questions we can help you with around this issue? If not I'd like to close this issue.

**Comment by RolandGuijt** [comment]
Closing this issue for now. But feel free to add to it if you have additional questions.

**Comment by brkmover** [comment]
Sorry for not getting back to you in time but thanks for your assistance
