### ISSUE TITLE
Exploring Identity Server with local users

### ISSUE THREAD

**Issue by AdrianPell** [DuendeSoftware/Support#1420]
**Which version of Duende IdentityServer are you using?**

v7

**Which version of .NET are you using?**

.NET 8

**Describe the bug**

Not really a bug - but the template for IS use with ASP.NET Identity only contains Login and Logout pages. I'm not planning on exclusively using external logins, so that means I'll need the usual set of pages - Register, Forgot Password, etc. etc. - all of which are in the standard ASP.NET Identity templates for .NET 8.

**To Reproduce**

Use the template ...

**Expected behavior**

Is the template only supposed to be an example - albeit one that includes examples of most IS features? I see the instructions for adding IS to an existing ASP.NET Core project with Identity, but this seems to miss some of the features of IS.

What's the best way to proceed? Start from that template and add the pages and other things I'll probably need, or start from an existing ASP.NET Core project (maybe even Blazor Server) and add the IS bits you document, and then other items as needed?

Thanks for any advice!

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AdrianPell** [comment]
I think I may have answered my questions by reading some of the closed issues - sorry for the false report!

**Comment by josephdecock** [comment]
Glad you're making progress! You might also find our QuickStart guide series useful: https://docs.duendesoftware.com/identityserver/v7/quickstarts/.
