### ISSUE TITLE
ParameterizedScopeParser service not called in UserInfo

### ISSUE THREAD

**Issue by porya0ras** [DuendeSoftware/Support#1424]
**Which version of Duende IdentityServer are you using?**
7

**Which version of .NET are you using?**
8

**Describe the bug**

why ParameterizedScopeParser  service was not call in Userinfo and i cant access these scopes in my ProfileService.
but in generate token its fine and i can controll in generate id_token

**Expected behavior**

It seems that in IUserInfoResponseGenerator and in the ProcessAsync function, at the stage where validatedResources is performed, the resourceValidatror service should be used, not a local function, because the ParameterizedScopeParser service is no longer called.

**Comment by porya0ras** [comment]
![2024-09-26 15_35_11-Careberry AdminUI (Running) - Microsoft Visual Studio](https://github.com/user-attachments/assets/99cd1c20-5705-45bb-b962-ce826408fb66)

**Comment by RolandGuijt** [comment]
Can you please tell us why you need that service in the UserInfo endpoint?

**Comment by RolandGuijt** [comment]
@porya0ras Would you like to follow up on this? Please do so. If not I'll close the issue.

**Comment by RolandGuijt** [comment]
Closing for now but please add a comment if needed.
