### ISSUE TITLE
Log Error for Device Code flow `Device authorization error` duplication in log message

### ISSUE THREAD

**Issue by kushal-banik-hyland** [DuendeSoftware/Support#1425]
**Which version of Duende IdentityServer are you using?**
v7.0.6

**Which version of .NET are you using?**
DotNet 8.0

**Describe the bug**
Getting Duplicate in message for `error` and `errorDescriptions` while those could be different

`Device authorization error: invalid_client:invalid_client` , Getting same value for logError and logDescription

**To Reproduce**
Configure any invalid client or anything to produce device code error

Steps to reproduce the behavior.

**Expected behavior**
`Device authorization error: invalid_client : -no message-`

**Additional context**
There is a bug in the line 125 https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Endpoints/DeviceAuthorizationEndpoint.cs#L125

**Comment by RolandGuijt** [comment]
Thanks for reporting this!
I have created an [issue](https://github.com/DuendeSoftware/IdentityServer/issues/1613) in identityServer's repository so that this can be fixed. Please track the issue from there from now on.
