### ISSUE TITLE
Unknown error crashing the application

### ISSUE THREAD

**Issue by ankabra** [DuendeSoftware/Support#1426]
**Which version of Duende IdentityServer are you using?**
7.0.5
**Which version of .NET are you using?**
.net 8.0
**Describe the bug**
Application getting crashed due to key not found error logged in exception tracking system.
System.Security.Cryptography.CryptographicException: The key {30e9e57d-2560-4305-9ba2-36926540c765} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
Microsoft.EntityFrameworkCore.Database.Command
info
04:52:53.249
Executed DbCommand (1ms) [Parameters=[@__key_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [p].[Id], [p].[ClientId], [p].[ConsumedTime], [p].[CreationTime], [p].[Data], [p].[Description], [p].[Expiration], [p].[Key], [p].[SessionId], [p].[SubjectId], [p].[Type]
FROM [PersistedGrants] AS [p]
WHERE [p].[Key] = @__key_0

This exception is causing application crashes.
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
This error indicates that you need to configure ASP.NET's data protection feature. Please see [here](https://docs.duendesoftware.com/identityserver/v7/deployment/data_protection/) in our documentation for a full guide.
