### ISSUE TITLE
Refresh token expiration time

### ISSUE THREAD

**Issue by parasdaftary** [DuendeSoftware/Support#1427]
**Which version of Duende.AccessTokenManagement are you using?**

Duende identity server 6.3.10 (for development)

**Which version of .NET are you using?**

.net core 6.0

**Describe the bug**

Refresh token expires in one hour approximately the expected behaviour that it should be valid for AbsoluteRefreshTokenLifetime which is 30 days

Provided client config  

AccessTokenLifetime = 3600,
AbsoluteRefreshTokenLifetime = 2592000,
RefreshTokenUsage = TokenUsage.OneTimeOnly,
RefreshTokenExpiration = TokenExpiration.Absolute,
UpdateAccessTokenClaimsOnRefresh = true,

I am not sure if this is a bug or configuration issue but when getting new access token with refresh token it is giving error as invalid_grant after some time probabaly after one hour, the expected behaviour is to get successful response that should include new access token, new expiresIn and new refreshToken. According to documentation and client config the refresh token should be valid for 30 days. If it is less than one hour the refresh token is able to get new access token if it is more than one hour it throws invalid_grant error.

**To Reproduce**

1) Generate code using authorization_code grant
2) Get access token and refresh token using code generated from authorization_code grant
3) Get new access token using refresh_token grant after one hour using refresh token it returns error as invalid_grant

Steps to reproduce the behavior.

**Expected behavior**

The expected behaviour is to get successful response that should include new access token, new expiresIn and new refreshToken. According to documentation and client config the refresh token should be valid for 30 days. 

**Log output/exception with stacktrace**

invalid_grant

```
data
```

**Additional context**

Please let us know if we need to provide more information from our side. Please let us know application changes if needed.

**Comment by AndersAbel** [comment]
Do you get any error messages logged? Whenever IdentityServer returns an `invalid_grant` error it should also write a more detailed error message to the logs.

**Comment by RolandGuijt** [comment]
@parasdaftary Would you like to follow up on this by answering Anders' question? If not I'd like to close the issue.

**Comment by parasdaftary** [comment]
Hi @AndersAbel and @RolandGuijt I have found a work around in application configuration which allows refresh token validity to be extended for specified time.  Please close this issue.

**Comment by jkkbuddika** [comment]
@parasdaftary We experience a similar issue. Can you explain what you had to do to resolve this issue? Thanks in advance!

**Comment by jkkbuddika** [comment]
@AndersAbel Your [comment](https://github.com/DuendeSoftware/Support/issues/1401#issuecomment-2358252209) here helped us resolve the issue. Thank you! We modified configuration so that `RefreshTokenUsage` is set to `0`, and that resolved the issue for us.
