### ISSUE TITLE
FallbackPolicy unsupported for BFF endpoints

### ISSUE THREAD

**Issue by grant-curve** [DuendeSoftware/Support#143]
**Which version of Duende BFF are you using?**
Happening on main branch

**Which version of .NET are you using?**
net6.0

**Describe the bug**

We are using BFF and would like to add a FallbackPolicy to our authorization, however we're not getting behavior we expect when trying to access an invalid url. Without a fallback policy, hitting an undefined url returns the expected 404 response, however with a fallback policy a 500 is returned. When this happens, the ArgumentNullException is being thrown in BffAuthorizationMiddlewareResultHandler because endpoint is null.

**To Reproduce**

Open the Duende.BFF solution, and build/run the JS6 project. Then access https://localhost:5002/something in the browser. You should get a 404 page.

Go back to the code solution. Add the following to ConfigureServices in JS6/Startup.cs

```
services.AddAuthorization(options =>
    {
        options.FallbackPolicy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();
    });
```

Rebuild/rerun and again try to access https://localhost:5002/something
This time it is a 500 error with an exception page:

```
ArgumentNullException: Value cannot be null. (Parameter 'endpoint')
Duende.Bff.BffAuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in BffAuthorizationMiddlewareResultHandler.cs
+
            if (endpoint == null) throw new ArgumentNullException(nameof(endpoint));
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Duende.Bff.Endpoints.BffMiddleware.Invoke(HttpContext context) in BffMiddleware.cs
+
            await _next(context);
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Expected behavior**

404 is returned for invalid endpoints with or without FallbackPolicy

**Log output/exception with stacktrace**

```
[14:18:59 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null. (Parameter 'endpoint')
   at Duende.Bff.BffAuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in /home/grant/public_html/BFF/src/Duende.Bff/Endpoints/BffAuthorizationMiddlewareResultHandler.cs:line 34
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Duende.Bff.Endpoints.BffMiddleware.Invoke(HttpContext context) in /home/grant/public_html/BFF/src/Duende.Bff/BffMiddleware.cs:line 50
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by brockallen** [comment]
PR submitted to fix, so I'll close this issue. Thanks for the report.

**Comment by brockallen** [comment]
BTW, with a fallback policy, you won't get 404 -- you will get a Challenge, which is a 302, right?
