### ISSUE TITLE
Server hangs out trying to obtain openid-configuration

### ISSUE THREAD

**Issue by JoseMPersichini** [DuendeSoftware/Support#1438]
**Which version of Duende IdentityServer are you using?**
6.3.10

**Which version of .NET are you using?**
8.0

**Describe the bug**
We have developed and deployed our Auth Server which is using the described version of Duende. Sometimes, the auth server don't answer to the /.well-known/openid-configuration request. It keeps loading forever.

If you go to another URL like /Account/Login (which will handle the user login) will work perfectly. But for some reason the configuration is not returned.

We tried to understand when this happen or how to reproduce the issue, but we couldn't. It happens randomly.

The app is distributed using an Azure App Service and we also don't have any error in the logs.

To solve the issue, we restart the Azure App Service. After that, it works again.

**Comment by JoseMPersichini** [comment]
Thanks @sanket-mistry-jm , I'm trying to upgrade the mentioned packages now.

**Comment by RolandGuijt** [comment]
@JoseMPersichini Did it work for you? If so I'd like to close this issue.

**Comment by JoseMPersichini** [comment]
@RolandGuijt I applied the change and for now it is working. It didn't happen again. But since it is a random issue, I'm not sure if it will be solved forever.

So I'm closing the issue and if it happens again I'll reopen it. Thanks!
