### ISSUE TITLE
Issue with using ForwardedHeaders and Azure API Management Services

### ISSUE THREAD

**Issue by daveops1** [DuendeSoftware/Support#144]
Hi there,

I have hosted IdentityServer on Azure App Services as a backend managed by API Management Services.

I have recently upgraded to IdentityServer v5 from v4 and it appears that the hostnames in the discovery document only show the internal hosting name from Azure App Services, even though ForwardedHeaders have been configured in startup.cs as mentioned in previous GitHub issues here.  This works in the previous version (v4) using this method.  I found that by adding `context.Request.Host = new HostString(_config["identityHost"]);` it will show the correct APIM host I specify in appconfig, in the discovery document, hence allowing identity server to function properly.  I am doing the following in startup.cs as advised in documentation

```
var forwardOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
                RequireHeaderSymmetry = false
            };

            forwardOptions.KnownNetworks.Clear();
            forwardOptions.KnownProxies.Clear();

            // ref: https://github.com/aspnet/Docs/issues/2384
            app.UseForwardedHeaders(forwardOptions);
```

I would appreciate any insight into why it seems to be no longer working for this particular version or what I need to be doing differently.  Please let me know if there is any additional information I can provide.

Thank you very much for your time and assistance!

**Comment by daveops1** [comment]
The startup.cs code utilizing this code segment had remain unchanged from "IdentityServer4" Version="2.3.2" package, using a netcore2.0. app, where it was working with the forwarded headers.  It has now been upgraded to "Duende.IdentityServer" Version="5.2.0" using netcore3.1 app when this stopped working, only showing the internal hostnames.  Is it possible this could be an issue with 3.1?  Thank you very much for the advice and I'll certainly continue digging.  I understand these forwarded headers are what identityserver looks at to obtain the correct proxy hostname vs. internal hostname.

**Comment by brockallen** [comment]
>  Is it possible this could be an issue with 3.1?

That I do not know, thus my suggestion to setup a separate simple app to test.

**Comment by brockallen** [comment]
Any update on this?

**Comment by daveops1** [comment]
Thanks for the follow up!  I can see from our other .net core apps, that the headers are indeed coming over (as well as our Identity Server app service by viewing the tracing from APIM).  I ended up using the workaround to "force" setting the identity host so the identity packages are able to generate the correct openid endpoint urls...`context.Request.Host = new HostString(_config["identityHost"]);`.  I still want to find root cause of this.  For creating a sample app (for which I can post code here for others to try as well), does this include setting up a bare-bones identity server scaffolding (I can probably obtain that from your samples repository) and put that also behind an APIM instance?  I'm thinking that would be best way to test/debug.  I was also thinking of finding that bit of code the identity server uses to store the headers into the path and debug that way as well.  Will continue to keep this thread updated with my findings.

**Comment by brockallen** [comment]
This is our abstraction for reading the request host: https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Services/Default/DefaultServerUrls.cs

And then it's used in several places when we need to know the host/origin.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by daveops1** [comment]
We can go ahead and close...if I have any additional findings, I can open a new support ticket or update this one.  For now, we are using the workaround mentioned above in this ticket.  If I find anything further that can provide insights, I will post my findings.
________________________________
