### ISSUE TITLE
ConsumedTime not set on refreshtokens

### ISSUE THREAD

**Issue by ZealousCynic** [DuendeSoftware/Support#1440]
Hello, in the proccess of upgrading IdentityServer, we have noticed that ConsumedTime in the PersistedGrantsStore no longer appears to be given a value when refreshing an access token using a refresh token.

**Which version of Duende IdentityServer are you using?**

6.3.10

**Which version of .NET are you using?**

.NET6

**Describe the bug**

ConsumedTime does not get set for RefreshTokens on use after upgrade.

**To Reproduce**

We have configured a client like so:

        new Client()
            {
                ClientId = "CLIENTID",
                AllowedScopes = {"openid", "profile", "email"},
                AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
                RequireClientSecret = true,
                AllowOfflineAccess = true,
                ClientSecrets = new List<Secret>()
                    {
                        new Secret("SECRETVALUE".Sha256())
                    },
                UpdateAccessTokenClaimsOnRefresh = true,
                AccessTokenLifetime = 60 * 60,
                AbsoluteRefreshTokenLifetime = 0,
                RefreshTokenExpiration = TokenExpiration.Sliding,
                SlidingRefreshTokenLifetime = 60 * 60 * 24 * 30,
                RefreshTokenUsage = TokenUsage.OneTimeOnly
            }

The Operational Store has been configured like so:

                .AddOperationalStore<DBCONTEXT>(options =>
                {
                    options.EnableTokenCleanup = true;
                    options.ConsumedTokenCleanupDelay = 3600;
                    options.RemoveConsumedTokens = true;
                })

IdentityServer has DeleteOneTimeOnlyRefreshTokensOnUse = false like so:

            services.AddIdentityServer(options =>
                {

                    options.PersistentGrants.DeleteOneTimeOnlyRefreshTokensOnUse = false;

                })

**Expected behavior**

For OneTimeUse RefreshTokens to be marked as consumed upon use.

**Comment by ZealousCynic** [comment]
Hi,

The upgrade is from 6.2.5 to 6.3.10.

**Comment by brkmover** [comment]
Hi Duende men, any updates, ideas or hints? 😊

**Comment by RolandGuijt** [comment]
I tried to reproduce this using the version of IdentityServer you indicated with the supplied settings. I couldn't reproduce the issue.

Are there any customizations to IdentityServer in place that could cause this?

**Comment by ZealousCynic** [comment]
Hello,

It turned out to be an issue with the environment, not IdentityServer. We've resolved it successfully on our end, but thank you very much for looking into it on your end as well.

**Comment by dopeydwerg** [comment]
I'm running into the same issue as described above. Could you please tell me how you resolved this?

**Comment by ZealousCynic** [comment]
> I'm running into the same issue as described above. Could you please tell me how you resolved this?

A 2nd service had access to the datastore, and was reading and writing to it. We removed this, restoring exclusive access to IdentityServer.
