### ISSUE TITLE
`ClientConfigurationStore` depends on `ConfigurationDbContext` instead of the `IConfigurationDbContext` interface

### ISSUE THREAD

**Issue by aurecchia** [DuendeSoftware/Support#1444]
Hi folks 👋 

**Which version of Duende IdentityServer are you using?**

7.0.7

**Which version of .NET are you using?**

SDK 8.0.300

**Describe the bug**

Not exactly a bug, more an inconvenience. We added the configuration API to our instance of IdentityServer (shared host setup), and we had dependency injection issues with the `ClientConfigurationStore`. 

We have a custom implementation of `ConfigurationDbContext` that inherits from the Duende one to customize the `OnModelCreatingMethod`. Our custom type is registered in DI instead of the built-in one. The [`ClientConfigurationStore` depends on the concrete type from Duende](https://github.com/DuendeSoftware/IdentityServer/blob/ee72df1198233290834826dfe63408bf34a94a27/src/Configuration.EntityFramework/ClientConfigurationStore.cs#L39). This means that we cannot just call `.AddClientConfigurationStore()` like shown in the documentation, but have to provide our own implementation of the `ClientConfigurationStore`.

Is there a reason why the dependency is on the `ConfigurationDbContext` class instead of [the `IConfigurationDbContext` interface](https://github.com/DuendeSoftware/IdentityServer/blob/ee72df1198233290834826dfe63408bf34a94a27/src/EntityFramework.Storage/Interfaces/IConfigurationDbContext.cs#L17)?

I wanted to understand if this was done deliberately before opening a PR.

**To Reproduce**

- Inherit from `ConfigurationDbContext` and register the custom implementation
- Register the `ClientConfigurationStore` using `.AddClientConfigurationStore()`

An error will be thrown when the `ClientConfigurationStore` is first instantiated or when DI scope validation runs.

**Expected behavior**

It should be possible to use the built-in `ClientConfigurationStore` with custom `ConfigurationDbContext` and [using the provided configuration extensions](https://github.com/DuendeSoftware/IdentityServer/blob/ee72df1198233290834826dfe63408bf34a94a27/src/Configuration.EntityFramework/ServiceCollectionExtensions.cs#L23).

Let me know if you require additional details or I can help in any other way.

**Comment by AndersAbel** [comment]
The pattern typically used for `DbContext registrations is to use a concrete type and not an interface in the DI registration.

Even though our `ClientConfigurationStore` depends on the `ConfigurationDbContext` and not an interface, it is possible to register a derived type as the implementation type for the `ConfigurationDbContext` type in DI:

```
builder.Services.AddDbContext<ConfigurationDbContext, DerivedConfigurationDbContext>(options =>
{
  //...
});
```

**Comment by AndersAbel** [comment]
It looks like our code does not work that well with a custom configuration context.

For now, you can add a workaround by registering your own implementation class with the ConfigurationDbContext service registration:

```
services.AddScoped<ConfigurationDbContext>(svcs => 
  svcs.GetRequiredService<MyDerivedConfigurationDbContext>());
```
