### ISSUE TITLE
Precedence of license file vs configuration provider propery

### ISSUE THREAD

**Issue by JustTest2017** [DuendeSoftware/Support#1446]
**Which version of Duende IdentityServer are you using?**
7.0.6

**Which version of .NET are you using?**
 .NET 8

Question:
Lets say i have a valid Duende_License.key file set in the ContentRootPath and I also have a valid value set in the Startup configuration:
```c#
builder.Services.AddIdentityServer(options =>
{
    options.LicenseKey = "eyJhbG..."; // valid license key value
});
``` 

Which one takes precedence over the other?

**Comment by StuFrankish** [comment]
You'd normally choose one or the other when applying the license, but if you were to set both, the license key in code (in your Startup configuration) will take priority over the file in ContentRootPath.

See: [LicenseValidator.cs#L45](https://github.com/DuendeSoftware/IdentityServer/blob/ee72df1198233290834826dfe63408bf34a94a27/src/Configuration/Licensing/LicenseValidator.cs#L45)

```csharp
protected void Initialize(ILoggerFactory loggerFactory, string productName, string key)
{
    Logger = loggerFactory.CreateLogger($"Duende.{productName}.License");

    key ??= LoadFromFile();
    License = ValidateKey(key);
   
    ErrorLog = LogToError;
    WarningLog = LogToWarning;
    InformationLog = LogToInformation;
    DebugLog = LogToDebug;
}
```

However, I'd recommend setting up an environment variable and using configured Options to retrieve the value and set it dynamically.
That way you can update the key without having to redeploy the host application - a simple restart will do.

For example (and this is highly abridged for brevity), in my setup I use Options classes to load configuration settings on startup.

appsettings.json _(or `ApplicationKeys__IdentityServer` in my deployed Azure environment)_
```json
{
  "ApplicationKeys": {
    "IdentityServer": "<YourKeyValueHere>"
  }
}
```

Options class:
```csharp
public class ApplicationKeys
{
    public string IdentityServer { get; set; } = string.Empty;
}
```

Configuration:
```csharp
public static void AddAndConfigureIdentityServer(this WebApplicationBuilder builder)
{
    // Get an instance of ApplicationKeys populated with configuration data
    var applicationKeys = builder.GetCustomOptionsConfiguration<ApplicationKeys>(ConfigurationSections.ApplicationKeys);

    builder.Services.AddIdentityServer(options =>
    {
        options.LicenseKey = applicationKeys.IdentityServer;
    });
}
```

`GetCustomOptionsConfiguration` is a custom extension I've written so you'll need to use your own method to bind the configuration.

Hope that helps 😊

**Comment by JustTest2017** [comment]
Thank you for the detailed and clear answer :)
