### ISSUE TITLE
Accessing refresh token expire time

### ISSUE THREAD

**Issue by mukul-a** [DuendeSoftware/Support#1449]
**Which version of Duende IdentityServer are you using?**
Identity Server 4

**Which version of .NET are you using?**
.net 6 (may be upgrading to 8 soon)

**Describe the bug**

Its not a bug, however apparently a security feature of identity server where we can access the refresh token itself however not its expire time from client. Wanted to check if there is a known work around to achieve the same, or if this can be considered as an enhancement.

**To Reproduce**

Setup an identity server and try to request the refresh token expire time from the client.

**Comment by RolandGuijt** [comment]
The refresh token itself doesn't contain that data. It is just a reference to the data stored in the persisted grants store. Typically the lifetime of the refresh token is longer than that of the access token so the client only needs to know the lifetime of the access token (which it *can* access).

Why do you need to know the refresh token lifetime on a client?

**Comment by mukul-a** [comment]
There is a scenario in our front-end app, where we have implemented the silent token refresh. Here we want to give a prior warning to the user, a few minutes before the refresh token is about to expire so that user will have a chance to save any unsaved changes before they may lose it (as they will be kicked back to the login screen after that to log back in).

**Comment by RolandGuijt** [comment]
As mentioned, the token itself doesn't contain the expiration info. The only way to do it is with a call to introspection endpoint at the Identity Provider.
However, IdentityServer 4 doesn't support this unfortunately and since it is out of support it won't be added.

The [docs for v7](https://docs.duendesoftware.com/identityserver/v7/reference/endpoints/introspection/) don't mention support for refresh tokens but I've created [this PR](https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/534) which I expect to merge soon.

**Comment by AndersAbel** [comment]
@mukul-a did you have any success by using introspection to get the lifetime of the refresh token?

**Comment by mukul-a** [comment]
@AndersAbel From what I understood, we can not get the lifetime, but can only check if the token it still valid or not using the introspection endpoint. It seems like there is not way to achieve this, hence this has been put on halt now.

**Comment by mukul-a** [comment]
@AndersAbel Thanks for that piece of information, I believe we will be able to achieve our use case with this. If we face any issue while implementing the same, we can reach out to you guys later for that. Closing this issue for now.
