### ISSUE TITLE
How to store refresh token on server, not in cookie.

### ISSUE THREAD

**Issue by paviad** [DuendeSoftware/Support#145]
**Which version of Duende IdentityServer are you using?**
I cloned it and using commit number 6ccd07cd59a32e16ed25a375c1b62a67ae59fc13

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
**To Reproduce**
**Expected behavior**
**Log output/exception with stacktrace**

This is a question, not a bug, so forgive me for skipping the above 4 points。

A refresh token is a long lived item, it is stored in a cookie by this library, is that a good, secure, practice? Is there a library supported way to save the refresh token on the server instead (apart from implementing my own `IUserTokenStore`)?

Thanks!

**Comment by brockallen** [comment]
> A refresh token is a long lived item, it is stored in a cookie by this library, is that a good, secure, practice

Refresh tokens in IdentityServer are stored in the persisted grant store: https://docs.duendesoftware.com/identityserver/v6/data/operational/grants/

You might really be asking about client-side? In ASP.NET Core, the cookie authentication handler establishes the session in the client and by default any tokens are stored as part of that session, and by default that data is stored in the cookie itself, yes. The cookie is data protected, so it's safe. 

If you'd like to store that cookie data server-side instead, you can implement server-side sessions with the ticket store extensibility point from Microsoft's cookie authentication handler. If you're using our BFF library, we have implemented this for you: https://docs.duendesoftware.com/identityserver/v6/bff/session/server_side_sessions/

**Comment by paviad** [comment]
Sorry, I was not clear - I am talking about the refresh token obtained from an external login provider, and persisted by this library.

**Comment by brockallen** [comment]
That's not something we do. That's code you would need to write as part of that external login workflow.

**Comment by paviad** [comment]
I think I am beginning to understand. If I want to avoid using the cookie, I should:

1. Modify the external login flow to store the token information in my db, based on some key that I do store in the cookie.
2. Implement my own `IUserTokenStore` that uses fetches the key from the cookie, and then retrieves the token information from the db.

Am I right?

**Comment by brockallen** [comment]
2: IUserTokenStore is from our access token management library, yes? So yes, you could use that to load the tokens from your custom store in step 1.
