### ISSUE TITLE
BFF To handle more than one client

### ISSUE THREAD

**Issue by raniaahmedlink** [DuendeSoftware/Support#1452]
**Which version of Duende BFF are you using?** 7

**Which version of .NET are you using?** 8

We currently have an IdentityServer7 project in operation and are looking to modify it to implement a Backend for Frontend (BFF) architecture. I noticed that you created a separate BFF project for each client. However, we would like to develop a single BFF project to manage multiple clients. Could you please assist us with this? 
and I want an example of client angular application which hosted in another domain of BFF

**Comment by RolandGuijt** [comment]
At the moment our BFF library is meant as a companion for *one* particular front-end application. It doesn't have the capability to manage cookies and tokens for multiple SPAs.

About your question asking for the example: [This](https://github.com/RolandGuijt/ps-angularauth/tree/main/2.OpenIdConnect) might be what you're looking for.

**Comment by AndersAbel** [comment]
@raniaahmedlink Do you have any further questions on this? If not, I'd like to close the issue.
