### ISSUE TITLE
Rsk.Saml.License.InvalidLicenseException: License Invalid

### ISSUE THREAD

**Issue by jgc2023** [DuendeSoftware/Support#1454]
**Which version of Duende IdentityServer are you using?** --Starting IdentityServer4 version 4.1.

**Which version of .NET are you using?**--.net core 3.1
**Describe the bug**--Rsk.Saml.License.InvalidLicenseException: License Invalid

A clear and concise description of what the bug is.--Rsk.Saml.License.InvalidLicenseException: License Invalid

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
The product that is generating the error, Rsk.Saml, isn't ours. Please contact Rsk to solve the license issue.
