### ISSUE TITLE
Redirecting to an error page when attempting to connect from a Web Form application to the Duende Identity Server.

### ISSUE THREAD

**Issue by geetzkrish** [DuendeSoftware/Support#1455]
**Which version of Duende IdentityServer are you using?**
5.2.0

**Which version of .NET are you using?**
4.8

**Describe the bug**
We have added all the required information in the **Clients** tables of Identity Server and updated the client application's startup page accordingly. However, it is redirecting to the Home/Error page without even showing the login page. 

We have added all the required information in the Client tables of Identity Server and updated the client application's startup page accordingly. However, it is redirecting to the Home/Error page without even showing the login page. 

Seems like it’s failing the validation.

**To Reproduce**

Steps to reproduce the behavior.

We have customized identity server code. Additionally, we created a sample webform application and added the required information in the startup class of the webform application. All the values in the webform application's startup file match those in the identity server's client tables. 

1. Run the Duende Identity Server on localhost.
2. Run the sample web form application.
3. This will redirect to the error page, hitting the Home/Error method.
**Expected behavior**

When the web form application is run and there is no active session, the Identity Server should display the login page. After a successful login, it should redirect to the client application.

**Log output/exception with stacktrace**

```
data
```
![Image](https://github.com/user-attachments/assets/508aa48a-6616-4e45-adc2-12d7e2c7cdb4)
![Image](https://github.com/user-attachments/assets/baca1c41-2a5a-468a-b994-3c945b18500a)
**Additional context**

**Comment by RolandGuijt** [comment]
Looking at your configuration it looks like the client is not allowed to use the authorization code flow.
Please adjust your `ClientGrantTypes` table and add a column for client 1 with the GrantType `authorization_code`.

If that doesn't do the trick please take a look at the logs and let us know if we can help with what's in there.

**Comment by geetzkrish** [comment]
> Looking at your configuration it looks like the client is not allowed to use the authorization code flow. Please adjust your `ClientGrantTypes` table and add a column for client 1 with the GrantType `authorization_code`.
> 
> If that doesn't do the trick please take a look at the logs and let us know if we can help with what's in there.

Oh, that worked! We were stuck there, but you saved us. Thank you so much!
