### ISSUE TITLE
Need windows based automatic login (SSO) using duende identity provider internally federate to azure ad

### ISSUE THREAD

**Issue by sundars1210** [DuendeSoftware/Support#1456]
**Duende.IdentityServer --version 7.0.7**

**.Net Core 8.0**

**Requirement:**

We have two .Net Core 8.0 Applications and will deploy them in two different AWS environments(AWS environments are not domain-joined). 
 
In both applications, we will use Duende idp which will internally federate to Azure ad. 
Our requirement is:
1. The user will log in to their system using the Azure AD credential
2. After system login, if they try to access any of the applications, it should not ask for login again. It should automatically log into the application using SSO.

Kindly let us know if the above requirement is feasible using Duende idp internally federated to Azure ad.

**Comment by josephdecock** [comment]
Yes, federation like this is a common scenario that IdentityServer supports. [Here](https://docs.duendesoftware.com/identityserver/v7/ui/login/external/) is a good place to read more in our docs.

**Comment by AndersAbel** [comment]
@sundars1210 Did the docs Joe linked to answer your question? Can we close this issue?
