### ISSUE TITLE
BFF Correlation failed exceptions

### ISSUE THREAD

**Issue by JeroenBer** [DuendeSoftware/Support#146]
The BFF software sometimes gives "correlation failed" exceptions when not expected. 

I can be easily reproduced:
- Use the BFF sample application at https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/JsBffSample

There are 2 repo paths, 

First:
1) Login using bob / bob
2) Navigate back to the login page
3) Login again with credentials bob / bob => Exception

Second:
1) Make sure you are logged out
2)  Goto login page
3) Wait 30 minutes before entering credentials
4) Login using bob/bob => Exception

Is there any way to prevent these exceptions ?

**Comment by JeroenBer** [comment]
Sorry we didn't have time yet, we need to finish some more important stuff first.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
