### ISSUE TITLE
How to keep SSO session alive?

### ISSUE THREAD

**Issue by JaysonTaiCelo** [DuendeSoftware/Support#1461]
**Which version of Duende IdentityServer are you using?**
`6.1.8`

**Which version of .NET are you using?**
.NET6

**Question**
I am looking to implement SSO onto an authentication server with IdentityServer and AspNet Identity. My current setup I have IdentityServer on domain `login.xxx.com` and two clients running on `app1.xxx.com` and `app2.xxx.com` respectively. I would like if a user on `app1.xxx.com` has already authenticate with `login.xxx.com` they do not need to resupply login credentials while authenticating for `app2.xxx.com`. I understand that the user session is maintained with `.AspNetCore.Identity.Application` and `idsrv.session` cookies on the auth server domain (`login.xxx.com`). My questions are

1. How would the `.AspNetCore.Identity.Application` and `idsrv.session` cookies "stay alive" perpetually to keep the user authenticated to the auth server as the user interacts with `app1.xxx.com` or `app2.xxx.com` and when the browser is terminated?
2. After following quickstart 1-7 on https://docs.duendesoftware.com/identityserver/v6/quickstarts/. I see `.AspNetCore.Identity.Application` and `idsrv.session` cookies are set to have "Session" expiries (as shown below), these are erased when the browser is exited. 
![Image](https://github.com/user-attachments/assets/c8a435ee-d49f-423c-ac64-17376dfde33d)
I have tried to set an expiry for the cookies with the following, but it still results in the two cookies having "Session" expiries as shown above.
```
        builder.Services
            .AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;

                // see https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
                options.EmitStaticAudienceClaim = true;
                options.Authentication.CookieSlidingExpiration = true;
                options.Authentication.CookieLifetime = TimeSpan.FromHours(8);
            })
            .AddInMemoryIdentityResources(Config.IdentityResources)
            .AddInMemoryApiScopes(Config.ApiScopes)
            .AddInMemoryClients(Config.Clients)
            .AddAspNetIdentity<ApplicationUser>()
            .AddProfileService<CustomProfileService>();
```
I have been stuck on this for a number of days, any assistance would be greatly appreciated.

**Comment by AndersAbel** [comment]
The switch to using persistent cookies is done on a per-session basis, so the setting is not in the cookie options. It can be changed in the login page through the `RememberLogin` property, please see

https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI.AspNetIdentity/blob/61d6f586c2ee4e959610e7ad3cf1769883222e9d/Pages/Account/Login/Index.cshtml.cs#L100

In our default implementation, `RememberLogin` is controlled by a checkbox. But you can of course set it strict to `true` if you want that for all users.

**Comment by RolandGuijt** [comment]
Closing this issue for now but feel free to add a comment if the need arises.
