### ISSUE TITLE
MultiTenancy with AspNetIdentity and IdentityServer

### ISSUE THREAD

**Issue by gilm0079** [DuendeSoftware/Support#147]
There are many posts on the internet dating back 10+ years discussing that AspNetCoreIdentity can be extended for MultiTenancy, but no one seems to have a working sample of how to implement it. All the posts sound great in theory, but I'm struggling with runtime errors related to DI and DbContext mismatches surrounding custom entities that extend the AspNetCoreIdentity user and roles. The extended entities inherit from the IdentityUser<TKey>, IdentityRole<TKey> classes so they are not completely custom entities. I've tried extending the IdentityErrorDescriber, IUserStore, IRoleStore, IUserRoleStore, UserManager, RoleManager, SignInManager, ClaimsPrincipalFactory. Getting tenancy to work with AspNetCoreIdentity  seems like the toughest part. I have OpenID setup to pass tenancy via the acr_values and that seems to work fine. I need to finish parsing querystrings, headers, claims, hostnames in a middleware to setup the request scope tenancy. I've been looking at the Finbuckle MultiTenant project for this. There will also need to be extensions done with the IdentityServer razor pages to handle multi tenant user management and a failback page for when a tenant is not parsed for a request.

I'm posting here to see if anyone in the community or DuendeSoftware has or is willing to put together a working sample for IdentityServer with multi tenancy. I'm more than willing to contribute to doing what I can to make this possible. Let me know what Duende's stance is on a multi tenant implementation if you can. I'll keep plugging away on my side with creating a solution that extendes for tenancy. Thanks everyone.

**Comment by gilm0079** [comment]
@brockallen No updates. I wasn't making any progress getting multi-tenancy to work and pivoted to Blazor in the meantime until we need to come back to the multi-tenancy. 

The issues we were having had to do with crafting custom tenancy classes for IdentityErrorDescriber, RoleManager, RoleStore, SignInManager, UserClaimsPrincipalFactory, UserManager and UserStore. This allowed us to extend the user/role stores to accommodate for tenancy separation in the DB and tenancy separation in the managers. All the issues seemed to be around the TUser T type on the Stores. We had our own T typed entity model which inherited from the Microsoft.AspNetCore.Identity.IdentityUser<TKey>. In our case TKey was a Guid. Entity Framework didn't seem to like us using CustomUser<Guid>. The DbContext kept complaining about CustomUser and CustomUser<Guid> not being the same thing. We couldn't figure out why EF was seeing the type as CustomUser<Guid>. We tried making a CustomUser class that inherited the CustomUser<Guid> class, but implemented the Guid TKey then EF would be fine with that but it would break code other places. I tried to mark some of the TKey exposed classes with [NotMapped] to keep EF's fingers off from trying to map the class as well, but no luck.

I don't think much changed since this issue was posted. I understand that AspNetIdentity is not a Duende thing. MS seems to assume IdentityServer is their official IdP. The implementation of both AspNetIdentity and IdentityServer seems so intertwined that I would probably get the same response from them that a tenancy implementation is out of their scope as well.

Documentation online from people attempting tenancy with AspNetIdentity and IdentityServer seems slim so at this point I'm just holding out to see if someone posts a working sample of a tenancy implementation before I circle back to this. If nothing has changed closer to the end of the year I may try to fork your samples and create a Tenancy sample as a proof. We would be looking for a Identity Server utilizing AspNetIdentity DB, tenancy FK columns added to AspNetIdentity, AspNetRoles, Clients, Identity Resources, ApiScopes, ApiResources. Tenants table added. Custom IdentityErrorDescriber, RoleManager, RoleStore, SignInManager, UserClaimsPrincipalFactory, UserManager and UserStore classes. TKey be a Guid.

When we get that far I can keep you posted especially if we fork the samples. A fully flushed out tenancy implementation may be a nice addition.

**Comment by brockallen** [comment]
> The implementation of both AspNetIdentity and IdentityServer seems so intertwined

Well, we provided some guidance/opinion on that here: https://docs.duendesoftware.com/identityserver/v6/upgrades/spa_to_duende/

> We would be looking for a Identity Server utilizing AspNetIdentity DB, tenancy FK columns added to AspNetIdentity, AspNetRoles, Clients, Identity Resources, ApiScopes, ApiResources. Tenants table added.

Is it just the users that live in different tenants, or do your client apps and scopes also exist per-tenant? Those are two different types of tenancy in my mind.

**Comment by gilm0079** [comment]
Thanks. Yes. I've been through that page and the quick start guides for asp.net core identity. https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/

At the very least we need users to be separated by tenant, but ultimately we'd like the other tables mentioned to be separated by tenant so that, for example, a tenant admin for one tenant can only see/assign roles for their specific tenant. Or in the case of clients tenant admins can only see/edit clients they have ownership of. Yes, from an auth perspective, tenancy here is probably two different things. The users tenancy is consumed in the SignInManager/UserManager. Management of the DB tables though would be tough if the AspNetUsers table was the only thing we cared to apply a tenancy relationship to.

**Comment by brockallen** [comment]
Hi @gilm0079. So what do you want to do with this open issue? Is there more to be done/added, or should something else be discussed here, or more action to be done elsewhere?

**Comment by wynnytsky** [comment]
> Is it just the users that live in different tenants, or do your client apps and scopes also exist per-tenant? Those are two different types of tenancy in my mind.

I didn't make custom managers, but I'm happy to say that Blazor Server worked great with this...
```
public class AppIdentityDbContext : IdentityDbContext
	<
		AppIdentityUser,
		AppIdentityRole,
		Guid,
		IdentityUserClaim<Guid>,
		AppIdentityUserRole,
		IdentityUserLogin<Guid>,
		IdentityRoleClaim<Guid>,
		IdentityUserToken<Guid>
	>
```

One minor hickup was that the scaffolded cshtml+controllers in Duende needed .ToString() added after references to my guid key in a number of places.

AddOpenIdConnect() requires a clientId so I have all users linked to a single clientId and each user has a "tenant" record in the AspNetUserClaims table.

But now I've added a separate API project that will only implement AddJwtBearer(), but I have no plan on how those incoming requests can be made tenant aware.  I suppose I can add a service account for each tenant and users would use those credentials and GrantType.Password for pulling an access token from my authority, though this grant will soon be deprecated.

Assuming GrantType.Password is off the table, my only thought is to create a clientId for each tenant, and each tenant will have a record in ClientClaims that will inject the "tenant" claim into the ClaimsPrinciple.  Going this way means I will continue using my global clientId for OIDC apps, and then the individual [tenant] clientIds will only be used for requests sent to my API project.

**Comment by brockallen** [comment]
I linked this thread to our issue tracking this request, so I'll close this issue for now.
