### ISSUE TITLE
UserSessionEntity PK should be a Guid

### ISSUE THREAD

**Issue by Odonno** [DuendeSoftware/Support#1476]
**Which version of Duende BFF are you using?**

2.2.0

**Which version of .NET are you using?**

.NET 8

**Feature request**

I can see that the `UserSessionEntity` stores data with a `BIGINT` primary key with autoincrement. It seems fine like that but if the application hits too many created sessions, it can fail to create new session at some point when overflowing the maximum `Id` key.

A `Guid` PK with interval cleanup should never experience this issue.

**Comment by AndersAbel** [comment]
A `BIGINT` Supports numbers up to 9E18. Considering there are about 8E9 people in the world, that gives about 1E9 possible sessions per human being. If every single human being would start a new session every second for 24 hours a day, that would still give us nearly 32 years before the `BIGINT` would overflow. To me that looks enough (with a good margin). Do you have any other numbers backing up the risk of the counter overflowing.

**Comment by Odonno** [comment]
I suppose it's good enough.
