### ISSUE TITLE
"KEY" value is not update after RefreshToken Operation

### ISSUE THREAD

**Issue by sc-ketanbhavsar** [DuendeSoftware/Support#1477]
**Which version of Duende IdentityServer are you using?** 7.0.8

**Which version of .NET are you using?** 8.0 

**Describe the bug**
After calling UpdateRefreshTokenAsync method, The Key is not updating. Duende IdentityServer 6.3.8 has no issue. But, as we migrate 7.0.8, the Application is not throw any error but the Database-> PersistedGrants-> "Key" col is not update. 

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by RolandGuijt** [comment]
In IdentityServer 7 there was a change in the default client configuration settings concerning refresh tokens. The default for  'RefreshTokenUsage' is now OneTimeOnly. In IdentityServer 6 is was ReUse. That means when you call the `UpdateRefreshTokenAsync` method leaving the setting to the default, a new token will be created.

Can you please check you client configuration and change back to ReUse if needed? If you have the config in code it would look like this:

`RefreshTokenUsage = TokenUsage.ReUse`

More information on why we chose to change this is [here](https://blog.duendesoftware.com/posts/20240405_refresh_token_reuse/).

**Comment by RolandGuijt** [comment]
Can you tell me the client's configuration setting for `RefreshTokenUsage`?

In IdentityServer 7 there was a [change](https://blog.duendesoftware.com/posts/20240405_refresh_token_reuse/) in the default client configuration settings concerning refresh tokens. The default for  'RefreshTokenUsage' is now ReUse. In IdentityServer 6 is was OneTimeOnly. Maybe this has something to do with the change in behavior you're seeing.

**Comment by RolandGuijt** [comment]
@sc-ketanbhavsar Would you like to follow up on this? If not I'd like to close the issue.

**Comment by RolandGuijt** [comment]
Closing this issue for now but please feel free to add to it if needed.
