### ISSUE TITLE
Redirect URI with brackets in query string not valid

### ISSUE THREAD

**Issue by valdian** [DuendeSoftware/Support#148]
**Which version of Duende IdentityServer are you using?**
6.1.1

**Which version of .NET are you using?**
6.0

**Describe the bug**
One of our clients has a redirect URI which contains brackets in the query string. After we upgraded from version 4.1.2 to version 6.1.1, users cannot log in from this client.

**To Reproduce**
1. Create a client with authorization code grant type and a redirect URI containing brackets in the query string, e.g. "https://test-client.com?connect[action]=login"
2. Initiate login from this client (i.e. do a browser redirect to /connect/authorize?redirect_uri=https%3A%2F%2Ftest-client.com%3Fconnect%5Baction%5D%3Dlogin&...)
3. Authorization request validation fails because of the redirect URI (see validation in [AuthorizeRequestValidator](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Validation/Default/AuthorizeRequestValidator.cs#L347))

**Expected behavior**
A redirect URI with brackets in the query string is a valid URI, and the user can log in to Identity Server from this client.

**Log output/exception with stacktrace**
```
2022-08-08 14:30:45.707 +02:00 [Debug] "test-client" found in database: True
2022-08-08 14:30:45.712 +02:00 [Debug] client configuration validation for client "test-client" succeeded.
2022-08-08 14:30:45.730 +02:00 [Error] malformed redirect_uri: "https://test-client.com?connect[action]=login"
AuthorizeRequestValidationLog { ClientId: "test-client", ClientName: "test-client", RedirectUri: null, AllowedRedirectUris: ["https://test-client.com?connect[action]=login"], SubjectId: "8b3ca1a2-983c-44f6-bb59-b7688eed360b", ResponseType: null, ResponseMode: null, GrantType: null, RequestedScopes: "", State: null, UiLocales: null, Nonce: null, AuthenticationContextReferenceClasses: null, DisplayMode: null, PromptMode: "", MaxAge: null, LoginHint: null, SessionId: null, Raw: [("redirect_uri": "https://test-client.com?connect[action]=login"), ("response_type": "code"), ("scope": "openid profile test-api"), ("response_mode": "query"), ("nonce": "87bc293c-3105-437a-a298-e5994843d9c1"), ("client_id": "test-client"), ("state": "123456")] }
2022-08-08 14:30:45.737 +02:00 [Error] Request validation failed
2022-08-08 14:30:45.740 +02:00 [Information] AuthorizeRequestValidationLog { ClientId: "test-client", ClientName: "test-client", RedirectUri: null, AllowedRedirectUris: ["https://test-client.com?connect[action]=login"], SubjectId: "8b3ca1a2-983c-44f6-bb59-b7688eed360b", ResponseType: null, ResponseMode: null, GrantType: null, RequestedScopes: "", State: null, UiLocales: null, Nonce: null, AuthenticationContextReferenceClasses: null, DisplayMode: null, PromptMode: "", MaxAge: null, LoginHint: null, SessionId: null, Raw: [("redirect_uri": "https://test-client.com?connect[action]=login"), ("response_type": "code"), ("scope": "openid profile test-api"), ("response_mode": "query"), ("nonce": "87bc293c-3105-437a-a298-e5994843d9c1"), ("client_id": "test-client"), ("state": "123456")] }
```

**Additional context**
The validation of the redirect URI in an authorization request was changed in the [pull request 389](https://github.com/DuendeSoftware/IdentityServer/pull/389). I understand the need for this change, but I suggest doing it another way so that a redirect URI with brackets in the query string is still valid.

Also, the OAuth specification does not require such a strict redirect URI validation; see [redirection endpoint section](https://www.rfc-editor.org/rfc/rfc6749.html#section-3.1.2).

I created a [pull request](https://github.com/DuendeSoftware/IdentityServer/pull/1000) with a proposed solution.

**Comment by brockallen** [comment]
We used to have something like the PR suggests, but found that URIs like "file://" would then be allowed, which we think is dangerous, and that's why we switched to `Uri.IsWellFormedUriString`. Do you know why `Uri.IsWellFormedUriString` isn't allowing the square brackets? Another idea/question -- if you encode the [ and ] in the query, does that work (both in the IsWellFormedUriString validation, as well as inside of IdentityServer in our redirect URI validation, and in the actual redirect)?

**Comment by valdian** [comment]
> We used to have something like the PR suggests, but found that URIs like "file://" would then be allowed, which we think is dangerous, and that's why we switched to `Uri.IsWellFormedUriString`.

I compared the results of your original implementation, your current implementation, my original suggestion and my new suggestion:
1. You used to have (before [#389](https://github.com/DuendeSoftware/IdentityServer/pull/389)):
`if (!Uri.TryCreate(redirectUri, UriKind.Absolute, out _))`

|| windows | linux |
|-|-|-|
| "/relative/path" | true | false |
| "file://callback.html" | false | false |
| "https://server.net?x[action]=login" | false | false |

2. Now you have:
`if (!Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute))`

|| windows | linux |
|-|-|-|
| "/relative/path" | true | true |
| "file://callback.html" | false | false |
| "https://server.net?x[action]=login" | true | true |

3. My original suggestion was:
`if (!Uri.TryCreate(redirectUri, UriKind.RelativeOrAbsolute, out var uri) || !uri.IsAbsoluteUri)`

|| windows | linux |
|-|-|-|
| "/relative/path" | true | true |
| "file://callback.html" | false | false |
| "https://server.net?x[action]=login" | false | false |

4. Another possible solution:
`if (!Uri.TryCreate(redirectUri, UriKind.Absolute, out var uri) || uri.IsFile)`

|| windows | linux |
|-|-|-|
| "/relative/path" | true | true |
| "file://callback.html" | true | true |
| "https://server.net?x[action]=login" | false | false |

According to the PR ([#389](https://github.com/DuendeSoftware/IdentityServer/pull/389)), the problem was that relative URIs are accepted as absolute ones and turned into `file://` URIs in Linux. The problem is also solved with my original solution (point 3). But you are right that it does accept redirect URIs starting with `file://`. But they are also accepted by your current implementation (point 2). So if we want to solve both cases, what about going for the solution from point 4?

> Do you know why `Uri.IsWellFormedUriString` isn't allowing the square brackets? 

The method does the validation according to the [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.2) for which square brackets are reserved characters.

> Another idea/question -- if you encode the [ and ] in the query, does that work (both in the IsWellFormedUriString validation, as well as inside of IdentityServer in our redirect URI validation, and in the actual redirect)?

The client is not maintained by us but by an external partner. When we noticed this issue, I asked them whether they could change the redirect URI, and they said no. So the only way of escaping the square brackets would be to add a middleware to our Identity Server app for it. It would escape the square brackets before the request is handled by the authorization endpoint and then unescape the redirect URI in the location header before the authorization response is returned. It could work if I change the redirect URI in the client configuration to the escaped one. But I do not like this idea very much.

**Comment by brockallen** [comment]
I actually like your approach in 4. We'll discuss. Thanks!

**Comment by brockallen** [comment]
Also, I think for whatever we do, I think it'd be a good idea to add a unit test that shows the test cases you have above.

**Comment by valdian** [comment]
I do not know how open to pull requests from external contributors you are now, but I enhanced my pull request.

**Comment by brockallen** [comment]
I proposed a new PR for this. Please have a look. Thanks.

**Comment by brockallen** [comment]
@valdian The patch has been released.
