### ISSUE TITLE
No response for Community License renewal

### ISSUE THREAD

**Issue by sebasnabas** [DuendeSoftware/Support#1490]
**Describe the bug**

Hi,
I'd like to renew our Community License (F&M Werkzeug- und Maschinenbau GmbH).
To do that I've filled out the contact form on your website https://duendesoftware.com/contact 2 times now over the last 3 weeks, but I haven't heard back.

Is there something I missed?

Kind regards

**Comment by damianh** [comment]
Hi @sebasnabas, I've has a look at our internal system and the last message we received from you via the contact form was 11/20/23. We'll investigate if there is an issue on our side. In the mean time could you email contact(at)duendesoftware.com directly please. Sorry for any inconvenience.
