### ISSUE TITLE
upgrade package Duende.IdentityServer.EntityFramework

### ISSUE THREAD

**Issue by Birte-Teal** [DuendeSoftware/Support#1495]
**Which version of Duende IdentityServer are you using?**
7.0.6

**Which version of .NET are you using?**
.net 8

**Describe the question**

Hello, we wanted to upgrade the Duende.IdentityServer.EntityFramework package.
However we see that the [7.1.0-preview.1](https://www.nuget.org/packages/Duende.IdentityServer.EntityFramework/7.1.0-preview.1) is deprecated.
Does this mean that the "normal" [7.0.8](https://www.nuget.org/packages/Duende.IdentityServer.EntityFramework/7.0.8) package is/will be deprecated too?

**Comment by damianh** [comment]
@Birte-Teal The deprecation flag for `7.1.0-preview.1` was accidental. It's been unflagged.

**Comment by RolandGuijt** [comment]
@Birte-Teal Would you like to add anything to this issue or can it be closed?
