### ISSUE TITLE
Question about configuring authentication cookies lifetime (and other settings)

### ISSUE THREAD

**Issue by mobinseven** [DuendeSoftware/Support#1496]
### Which version of Duende IdentityServer are you using?
7.0.8

### Which version of .NET are you using?
8.0

### Describe the issue

I have two hosts running on two different domains. One host authenticates users for the other external one. The authentication process works perfectly.

What I need to be done next is to increase the lifetime of the issued cookie for the external host. I have already customized the authentication host cookie lifetime(MaxAge) using `ConfigureApplicationCookie`. On every new session, the external host always redirects user to get authenticated. Because the user is already logged in the main authentication domain (the user already has an identity cookie) the user  gets instantly redirected to the external domain authenticated, until the session is ended.

#### `AddIdentityServer` cookie settings
1. Configure one host to authenticate users for the other using `Duende.IdentityServer 7.0.8`.
1. Customize the authentication cookie settings using `AddIdentityServer` and set `options.Authentication.CookieLifetime`.
1. Authenticate a user and check the cookie settings in the browser.

**Result**
This breaks authentication in the main host without even solving the problem. The authentication cookie gets cleared instantly after logging into the main host.

#### `ConfigureExternalCookie` cookie settings
1. Same as previous but this time using `options.ExpireTimeSpan` of `ConfigureExternalCookie`.
1. Authenticate a user and check the cookie settings in the browser.

**Result**
No change in behaviour.

### Expected behavior
The customized authentication cookie settings, such as `CookieLifetime`, should be applied to the cookie issued to the user's browser in the external host.

**Comment by mobinseven** [comment]
> Can you please indicate if the below is correct?


yes, sir.

> * You have two identity provider applications on separate hosts, both running IdentityServer

No. Two separate hosts on two different domains. one identity provider (which have its own front-end including login forms, profile management, etc.). The other one is a mere front-end which requires authorized access and is a client for the identity provider (I called this one 'the external one').

> * One is configured as an external identity provider for the other

yes.
> * You want to extend the session cookie lifetime for the external one

I want to extend the lifetime of the cookies issued to the client users. The lifetime of the cookies issued to the identity provider itself are correctly customized.

Sorry for ambiguity in the problem statement. And thank you for your help.

**Comment by RolandGuijt** [comment]
Thanks for the clarification.

In your scenario the browser will have two session cookies after a user successfully logs in:
- One set by IdentityServer
- One set by the client

If I understand correctly you want to extend the lifetime of the latter one. The lifetime of that is by default tied to the lifetime of the browser session but it can be changed. The adjustment has to take place in the **client's** code:

```
builder.Services.AddAuthentication(..)
    .AddCookie(options =>
    {
        options.Cookie.Expiration = TimeSpan.FromDays(30);
    })
    ..
```

**Comment by mobinseven** [comment]
Thank you, sir. That was just what I needed.
