### ISSUE TITLE
Is there any builtin feature available to track user login details?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#150]
**Which version of Duende IdentityServer are you using?**

6.1.0

**Which version of .NET are you using?**

.NET 6

**Describe the question**

We have a requirement to track login details, like login failure, success, logout success, login/logout time, IP address and more information.

So, is there any inbuilt feature or service which can fulfil our requirements?

**Comment by brockallen** [comment]
This would be done with our "Events": https://docs.duendesoftware.com/identityserver/v6/diagnostics/events/
