### ISSUE TITLE
New Licence Key required!

### ISSUE THREAD

**Issue by ISchunk** [DuendeSoftware/Support#1502]
we need new licence key via mail? can you please check

copied from the prev.  mail

Duende Enterprise (Standard) License Key #3999 for Siemens AG Nuremberg

Hi Siemens AG Nuremberg,

Please find the attached license key for Enterprise (Standard) with serial number 3999. 
License Details: unlimited deployments, 1-year license, valid to: 11/30/2024, priority support, 2 escalations (1500 USD each additional), unlimited clients

By accessing the Duende IdentityServer code and using this license key, you are agreeing to the following licensing terms:
https://duendesoftware.com/license
If you do not agree to these terms, do not use this license key or the Duende IdentityServer code.

See here for information on how to load the license key:
https://docs.duendesoftware.com/identityserver/v7/fundamentals/license_key

The license is valid from 10/19/2023 to 11/30/2024. We will contact you three months before expiration to start the renewal process.

If you run into any problems, please open a support issue in our support forum:
https://github.com/DuendeSoftware

You also have access to Priority Support. Please use the below email address to open private support issues:
[priority@duendesoftware.com](mailto:priority@duendesoftware.com)

The email address has a guaranteed response time of 2 business days.

See here for our priority support agreement:
https://duendesoftware.com/license/PrioritySupportLicense.pdf

thanks!
———
Duende Software
.....

**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by ISchunk** [comment]
the new licence for 1 year already ordered (from SoftwareOne), but the mail with key is missing. We need support , very urgent!
you can contact me: Igor.Schunk@siemens.com or Omid.Zaman@evosoft.com

**Comment by leastprivilege** [comment]
Hi, 

thanks!

Please use sales@duendesoftware.com for license related issues. I have forwarded your request.

**Comment by ISchunk** [comment]
OK, i hope Sales Team will response asap. 

Dear Sales Team,

We need urgent support and the new key (until now not provided)!

Thanks! Igor
