### ISSUE TITLE
License warning for number of issuers when the only difference is the protocol but same FQDN.

### ISSUE THREAD

**Issue by pregress** [DuendeSoftware/Support#1503]
**Which version of Duende IdentityServer are you using?**
7.0.8
**Which version of .NET are you using?**
8

**Describe the bug**

When running identity server, we sometimes receive this warning: 

> Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: https://samedomain.com, http://samedomain.com. This might be due to your server being accessed via different URLs or a direct IP and/or you have reverse proxy or a gateway involved. This suggests a network infrastructure configuration problem, or you are deliberately hosting multiple URLs and require an upgraded license

Our identity solution is hosted on azure websites, with enforce https and we also return hsts / Strict-Transport-Security headers.
We noticed this as someone was running security scanner / crawler against our identity site.

I don't think this should be flagged as a license violation, as the only difference is the protocol. HTTPS vs HTTPS 

**To Reproduce**
1. Run identity on azure web apps, with enforced https
2. Make sure the hsts header is returned
3. Try to request a token over https
4. Try to request a token over http (results in a redirect)
5. License violation is logged.

**Expected behavior**

No warning when the only difference is the protocol.

**Log output/exception with stacktrace**

```
Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: https://samedomain.com, http://samedomain.com. This might be due to your server being accessed via different URLs or a direct IP and/or you have reverse proxy or a gateway involved. This suggests a network infrastructure configuration problem, or you are deliberately hosting multiple URLs and require an upgraded license
```

**Additional context**

N/A

**Comment by RolandGuijt** [comment]
Do you have the HttpsRedirect middleware in the pipeline of the application? Please add that if needed and if it's already there please check if it is present before all other middleware.
Please report back with your findings so we can investigate further if needed.

**Comment by pregress** [comment]
Moved hsts to be the first middleware, seems to be resolved. If not I'll reopen it.
