### ISSUE TITLE
Is there an option to modify the OIDC discovery endpoint `JsonSerializerOptions`?

### ISSUE THREAD

**Issue by BrunoBlanes** [DuendeSoftware/Support#1505]
**Which version of Duende IdentityServer are you using?**
v7.0.8

**Which version of .NET are you using?**
.NET 9.0.100

I've been able to achieve this through the use of my own implementation of the `IHttpResponseWriter<DiscoveryDocumentResult>` and `WriteJsonAsync` extension that takes in a `JsonSerializerOption` parameter.

```csharp
public static async Task WriteJsonAsync(this HttpResponse response, object o, JsonSerializerOptions options)
{
	var json = JsonSerializer.Serialize(o, options);
	await response.WriteJsonAsync(json);
}
```

However, that means I no longer have this like of code in my extension:

```csharp
using var activity = Tracing.BasicActivitySource.StartActivity("WriteJson");
```

I did see that the `DynamicClientRegistrationResponseGenerator` has a property which allows changing the serialization settings, but it doesn't seem to apply to the discovery endpoint.

**Comment by RolandGuijt** [comment]
Can you please tell us why you want to change the options? With that info I can better investigate a possible solution for you.

As a side note: .NET 9 and IdentityServer 7.0.x is not a supported combination. The upcoming 7.1 will be .NET 9 compatible.

**Comment by BrunoBlanes** [comment]
I am going to be honest, it's just so I have the option to pretty print it, but since than I turned to the browser for doing just that. 

I am aware that NET 9 isn't supported on this version, but thanks for the warning.

**Comment by RolandGuijt** [comment]
@BrunoBlanes :-) So is it OK to close this issue?

**Comment by BrunoBlanes** [comment]
I guess so, sorry to bother. 😅
