### ISSUE TITLE
Upgrading to BFF 3.0.0-preview.2 packages

### ISSUE THREAD

**Issue by mrob1600** [DuendeSoftware/Support#1508]
Currently using BFF version 2.2.0

Using .NET 9

When trying to upgrade the BFF packages to 3.0.0-preview.2 I get the following error:
"Unable to find package Duende.Bff.Shared. No packages exist with this id in source(s): NuGet"

The upgrade fails. 

To reproduce, try and upgrade from BFF 2.2.0 packages to 3.0.0-preview.2

Packages should update successfully.

**Comment by damianh** [comment]
Hi, yes that package appears broken. `Duende.Bff.Shared` no longer exists in v3.x. We'll push another preview up to address this. Thanks!

**Comment by damianh** [comment]
[Updated packages pushed](https://www.nuget.org/packages/Duende.BFF/3.0.0-preview.3#dependencies-body-tab).
