### ISSUE TITLE
Duende ignoring requests for community license renewal

### ISSUE THREAD

**Issue by papaja** [DuendeSoftware/Support#1509]
Sorry to write here, but for over a year Duende is ignoring requests for Community license renewal/extension. I fulfill all the requirements but I don't get even a reply.

Hoping here someone can clarify situation.

**Comment by brockallen** [comment]
Hello @papaja -- 

Did you submit your request via our [community edition contact form](https://duendesoftware.com/contact?Reason=2)? 

Thanks.

**Comment by papaja** [comment]
Yes, of course.

**Comment by brockallen** [comment]
Ok, sorry about that! Please send a mail directly to: communityedition@duendesoftware.com and we'll get you sorted.

Thanks.

**Comment by RolandGuijt** [comment]
@papaja Has this worked out for you?

**Comment by papaja** [comment]
I've sent an email and got reply that states "We will respond to your request within 10 business days." That hasn't passed yet so I have yet to see how it ends :)

**Comment by RolandGuijt** [comment]
@papaja According to my data you should have received a reply. I'm closing this issue for now. If you have further questions/remarks please let us know via email.
