### ISSUE TITLE
NopUserSessionStoreCleanup is never registered in DI

### ISSUE THREAD

**Issue by ArturDorochowicz** [DuendeSoftware/Support#151]
**Which version of Duende BFF are you using?**
2.0.0-preview2

**Which version of .NET are you using?**
net6.0

**Describe the bug**
This is a really minor thing. There's `NopUserSessionStoreCleanup` in the source code, but it's never registered.

When I use the following options together: `EnableSessionCleanup=true` and `AddServerSideSessions()` (in memory), I'm getting error messages from `SessionCleanupHost` here:
https://github.com/DuendeSoftware/BFF/blob/70310cb32684767ac09cdf089cc27a1fde6c0c2a/src/Duende.Bff/SessionManagement/SessionCleanupHost.cs#L109-L122

Maybe register `NopUserSessionStoreCleanup` in DI inside `AddServerSideSessions`?

**To Reproduce**

```csharp
services.AddBff(options => options.EnableSessionCleanup = true)
   .AddServerSideSessions();
```

**Expected behavior**

I expect no errors to be logged from `SessionCleanupHost`.

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by ArturDorochowicz** [comment]
There's an unrelated code style issue in the Duende.Bff.EntityFramework project, I think. I'm too lazy to file another issue.

You have a `BffBuilderExtensions` class there which is in `Duende.Bff.EntityFramework` namespace. Such things are typically in `Microsoft.Extensions.DependencyInjection` namespace or something like that. For instance, I see that you use `Microsoft.AspNetCore.Builder` for `BffBuilder` which is the type that contains `AddServerSideSessions`;

**Comment by brockallen** [comment]
Hi @ArturDorochowicz --

> When I use the following options together: EnableSessionCleanup=true and AddServerSideSessions() (in memory),

So that's not really a combination that's intended. The in-mem server side sessions is really meant for testing, and not really for anything in prod, and thus, as such, there's not a real expectation that you'd be wanting to cleanup those expired sessions.

> I'm getting error messages from SessionCleanupHost here:

Ah, right -- likely because there's no IUserSessionStoreCleanup in DI. 

The comment is possibly helpful here:

```
    /// <summary>
    /// Indicates if expired server side sessions should be cleaned up.
    /// This requires an implementation of IUserSessionStoreCleanup to be registered in the DI system.
    /// </summary>
    public bool EnableSessionCleanup { get; set; }
```

I think what I'd prefer to do is 1) remove the `NopUserSessionStoreCleanup` because it's not used (nor helpful I think), and 2) have some better error for this scenario, perhaps reminding you that you need a IUserSessionStoreCleanup (likely from the EF component).

Thoughts?

**Comment by brockallen** [comment]
> You have a BffBuilderExtensions class there which is in Duende.Bff.EntityFramework namespace. Such things are typically in Microsoft.Extensions.DependencyInjection namespace or something like that. 

Fair point -- I fixed this for our v2.0 release: https://github.com/DuendeSoftware/BFF/pull/128/commits/a1a7244c4c5231d7bc4f75bc94a9a23d8a5112b5

**Comment by ArturDorochowicz** [comment]
> So that's not really a combination that's intended. The in-mem server side sessions is really meant for testing, and not really for anything in prod, and thus, as such, there's not a real expectation that you'd be wanting to cleanup those expired sessions.

Sure, understood. I do enable this for development only and for prod I configure the EF db version. I just set  EnableSessionCleanup to true unconditionally. That's how I discovered the problem. I can of course set this depending on the environment as well.   

> I think what I'd prefer to do is 1) remove the NopUserSessionStoreCleanup because it's not used (nor helpful I think), and 2) have some better error for this scenario, perhaps reminding you that you need a IUserSessionStoreCleanup (likely from the EF component).

Sorry, I should've included the existing message. It says "Exception deleting expired sessions: No service for type 'Duende.Bff.IUserSessionStoreCleanup' has been registered". That's quite clear already, I think. No need to complicate the code on my account.

I submitted this not because it was somehow problematic or confusing. The issue was very clear. I just thought that you maybe missed the registration by accident, given the class existed. I'm completely fine with whatever you decide.

**Comment by brockallen** [comment]
Well, there's a PR -- have a look and see if there's anything alarming or objectionable?

**Comment by ArturDorochowicz** [comment]
LGTM, left one comment.
