### ISSUE TITLE
IAsyncDisposable SigningKeyStore causes problems during token expiration

### ISSUE THREAD

**Issue by gallup-ceciliabrewer** [DuendeSoftware/Support#1513]
**Which version of Duende IdentityServer are you using?**
IdentityServer 7.0.6

**Which version of .NET are you using?**
.NET 8

**Describe the bug**
We have a need to asynchronously dispose our SigningKeyStore, but the service scope used in ServerSideSessionCleanupHost is synchronous, despite ServerSideSessionCleanupHost.RunAsync being `async`, meaning that SigningKeyStore can only be IDisposable. This causes exceptions when ServerSideSessionCleanupHost runs.

**To Reproduce**

Configure IdentityServer with server-side sessions and a SigningKeyStore that implements IAsyncDisposable.

**Expected behavior**

It seems like it should be possible to use asynchronously disposed services in IdentityServer.

**Log output/exception with stacktrace**

```
System.InvalidOperationException: 'IdentityServer.Identity.Stores.SigningKeyStore' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServerSideSessionCleanupHost.RunAsync(CancellationToken cancellationToken) in /_/src/IdentityServer/Hosting/ServerSideSessionCleanupHost.cs:line 152 
```

**Comment by AndersAbel** [comment]
Thanks for raising this issue.

To me it looks like the cleanup host code has roots which are older than the `CreateAsyncScope()` method. So at the time of writing that code, it was correct. It looks like we should update to use `CreateAsyncScope()` instead.

**Comment by gallup-ceciliabrewer** [comment]
That all makes sense, totally understandable, we'll be watching for a fix for it when you can get to it.

**Comment by RolandGuijt** [comment]
@gallup-ceciliabrewer Anders has created an issue on our internal backlog so it can be triaged.
Therefore I'm closing this support issue for now, but should you have any additional remarks regarding this, please free to add them.
