### ISSUE TITLE
Question: Options for dealing with bad refresh tokens? 

### ISSUE THREAD

**Issue by ArturDorochowicz** [DuendeSoftware/Support#153]
**Which version of Duende BFF are you using?**
1.2.2

**Which version of .NET are you using?**
net6.0

**Question**

What are the options for dealing with bad refresh token?

Let's say that the refresh token becomes somehow invalid before the authentication session on the BFF host ends. This may happen because the refresh token has expired or has been revoked at the Identity Provider.

What I see in my limited testing is that BFF will continue to try to refresh the access token when doing remote api requests (Yarp), which in this scenario will continue to fail and the client will keep receiving 401 responses. The session appears unrecoverable - the access token is expired, the refresh token is of no use.  

My question is how to deal with such situation in code? In general terms, it seems to me that the only option is to force the user to authenticate again in order to get a new set of tokens. But I can't seem to find any kind of event or something to detect this situation and react to it. I suspect there's something obvious that I totally missed.

Maybe an alternative is to do nothing on the server side and let whoever calls into the BFF host (e.g. browser SPA app) detect that they are getting too many 401 responses and deal with that by e.g. triggering a logout.

**Comment by brockallen** [comment]
Given that the app layer knows the BFF is doing its job, if there's a 401 from the API it means the user needs to login again (which is different than triggering logout - something I'd not recommend).

**Comment by ArturDorochowicz** [comment]
Ok, that makes sense. Thank you.
