### ISSUE TITLE
Errors refreshing access token on BFF

### ISSUE THREAD

**Issue by JeroenBer** [DuendeSoftware/Support#154]
**Which version of Duende BFF are you using?**
1.2.1

**Which version of .NET are you using?**
6.0.3

**Describe the bug**
We sometimes get stuck in an error situation using the BFF that the user cannot get out of. The calls to our backend API's return 401. After investigation it seems that the BFF cannot refresh the access token. The following logmessages are visible, when the problem starts:

> Error refreshing access token. Error = invalid_grant

The following request will then always log:

> Access token is missing. token type: 'User'

Our frontend queries: "/bff/user" which returns the User is OK, so the frontend thinks we are still properly logged in.

Our frontend is an Angular SPA and for some page transitions it does a few simultaneous requests to the Backend. After more investigation the problem is probably caused by the fact that for the BFF Client we configured RefreshTokenUsage to OneTimeOnly (the default) which may be causing problems if multiple request are simulatenously trying to refresh the access token. 

**To Reproduce**

- Create a SPA that does multiple simultaneous requests
- Set BFF Client RefreshTokenUsage in Identityserver to OneTimeOnly (default)
- Set BFF Client AccessTokenLifetime to 60 seconds
- Start SPA Frontend and refresh after 3 minutes

**Expected behavior**

- Not sure, is it expected behaviour that BFF doesn't always work with RefreshTokenUsage OneTimeOnly ? I imagine it would be pretty hard to make this work properly. So the solution might be to always use RefreshTokenUsage "ReUse". This might not be so bad since this refreshtoken has less risk of getting exposed since it's not known to the frontend ?

- Is it expected behaviour that /bff/user return OK after refreshing the token has failed ? It might be better to have it return 401 then ? It probably depends on the cause of not being able to refresh the access token. The invalid grant will never be solved, a temporary network error might be resolved later.

**Additional context**

Frontend Angular SPA with simultaneous requests.

**Comment by brockallen** [comment]
>  the problem is probably caused by the fact that for the BFF Client we configured RefreshTokenUsage to OneTimeOnly (the default) which may be causing problems if multiple request are simulatenously trying to refresh the access token

Yes, using ReUse for that setting is fine for the BFF given that the client stores the token securely and it requires a client secret to renew. 

We should update our docs to include this note. // @leastprivilege @josephdecock

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
