### ISSUE TITLE
Refresh Token With every refresh page

### ISSUE THREAD

**Issue by MonaElHaj** [DuendeSoftware/Support#157]
Hi 
I'm using the Duendy Identity server in my app (asp.net core 5)
, add my app as a client in the type authorization code with some API resource
user login in correct way and return with the proper access token.

the problem is with every request or refreshes page, hitting in IDP Project then returning again to re-authnticate
Why?

**Comment by brockallen** [comment]
> the problem is with every request or refreshes page, hitting in IDP Project then returning again to re-authnticate

Not sure -- you'd have to debug why your client app is not properly establishing its own session based on the OIDC results from your IdentityServer. If you're working in .NET for the client, I'd suggest getting our samples to work:

https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
