### ISSUE TITLE
Sign in of User from external Authenitcation

### ISSUE THREAD

**Issue by jawaharrajan-investx** [DuendeSoftware/Support#158]
**Which version of Duende IdentityServer are you using?**

5.0

**Which version of .NET are you using?**

5.0

**Describe the bug**
N/A

We are signing in a user via IDP initiated SAML Authentication, so we just have a AssertionConsumerService end point the client sends the SAML Assertion to. We are acting as the ServiceProvider.

We validate the Assertion that it is valid and good.
How do we sign the the user to our IDentity server.
Do we call ::

`var claims = new Claim[] {
    new Claim("sub", "unique_id_for_your_user")
};
var identity = new ClaimsIdentity(claims, "pwd");
var user = new ClaimsPrincipal(identity);

await HttpContext.SignInAsync(user);`

1- So for the sub can I assign a new GUID as the ID?

2 - is pwd the password, as they are an external user authenticated by the external Authentication Provider we do not have their password  - do we need to have them in our system too with a default password ?

3- can we just do this:
`var user = new IdentityServerUser("unique_id_for_your_user")
{
    DisplayName = user.Username
};

await HttpContext.SignInAsync(user);`

So right now we have the assertion end point on our Duende IdentityServer , so can we redirect to the the Service application the client wants to access? OR does the AssertionConsumeService end point need to be on the service Application and we redirect them to the IdentityServer to get signed in (Create a session.

Because if we re-direct from the IdentityServer the user object in the Service application will not know about the user.

**Comment by brockallen** [comment]
We document many of those things here: https://docs.duendesoftware.com/identityserver/v6/ui/login/external

But how you map from the external IdP to the identity in your IdentityServer is ultimately up to your own design and architecture. Normally you use the identifier from the external user in the external IdP and map to a record in your IdentityServer, and thus a unique id that you control.

**Comment by jawaharrajan-investx** [comment]
Hi  Brock
Yes we are mapping the Id from the External IDP to a user in our own database.
Once we do that, We need to sign them in to Identity Server so that the user has an Access token to be able to use other resources that are authorized by Identity server.



in my start-up on  our MVC client I have

`                .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
                {
                    options = identityConfigClientSide.SetIdentityOptions(options);
                    options.Events.OnRedirectToIdentityProvider = async n =>
                })
                .AddOpenIdConnect("saml2","SAMLUSers", opt =>
                {
                    opt.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                });`
                
                
Then the SAML AssertionConsumerService endpoint after we verify the user we have
var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);

But we get this errror:
No authentication handler is registered for the scheme 'idsrv.external'. The registered schemes are: saml2, Cookies, OpenIdConnect, Identity.External. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("idsrv.external",...)?

We need to somehow redirect to Identity and sign them in so they have an Access token


Thanks

**Comment by brockallen** [comment]
> in my start-up on our MVC client I have
```
.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options => { options = identityConfigClientSide.SetIdentityOptions(options); options.Events.OnRedirectToIdentityProvider = async n => }) .AddOpenIdConnect("saml2","SAMLUSers", opt => { opt.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme; });
```

The MVC client is not the host that uses the `IdentityServerConstants.ExternalCookieAuthenticationScheme`, so I think you might have some things confused (unless I'm confused about the code you have pasted above). 

Did you follow the quickstart tutorial that shows how to handle external authentication?

https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/#add-support-for-external-authentication

**Comment by jawaharrajan-investx** [comment]
Hi Brock
Thanks for your suggestions
I have followed the tutorial, it is very straight forward .
However, in our case we have a customer that wants access to our MVC application with single - sigin on initiated by them.

Our MVC app is protected by Duende Identity Server and our regular customers all  login in via the MVC app and are authorized by Duende Identity Server, this works very well for us.

This particular Customer who wants single sign-on  initiated by them, they will send us a SAML Assertion to an ACS end point.

We have the end point on out MVC app so that we can then re-route Identity to do a sign in and get an access Token

If we have the end-point on the Identity Server (the challenge essentially) then if we route them back to the MVC after sgin  (As per the tutorial with the External Authentication  flow) the MVC app will not have a context awareness of the user.

So in our main MVC app entry point where we have an [Authorize] attribute, the MVC User will not be aware of the user coming from Identity as it was not initiated from the MVC App
I know this may seem confusing, hence my several questions about how to make this approach work

**Comment by brockallen** [comment]
Ah, they want IdP initiated login? I see.

Well, you will have to design your SAML plumbing in IdentityServer to know how to handle that. So the SAML component you use might have an event or something for that, you would handle it, and then once you have issued the local session at IdentityServer, somehow know what OIDC client to send the user to. And then that client app would initiate its normal OIDC flow (as OIDC doesn't support IdP initiated login).

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
