### ISSUE TITLE
Pushed Authorization Requests (PAR)

### ISSUE THREAD

**Issue by michaeldimoudis** [DuendeSoftware/Support#16]
**Which version of Duende IdentityServer are you using?**
5.2.4 (will upgrade to 6 soon)

**Which version of .NET are you using?**
.NET 5

**Describe the bug**

I haven't seen any documentation around this, so just wondering if there are plans to add PAR support to Duende Identity Server?

**To Reproduce**

n/a

**Expected behavior**

n/a

**Log output/exception with stacktrace**

n/a

**Additional context**

PAR was briefly mentioned here https://leastprivilege.com/2020/02/04/hardening-openid-connect-oauth-authorize-requests-and-responses/

**Comment by brockallen** [comment]
We have an [open issue](https://github.com/DuendeSoftware/IdentityServer/issues/40) for it, but it's not yet implemented. Unsure if we'll get it in for 6.1 or if we'll have to push it to 6.2.

**Comment by michaeldimoudis** [comment]
Thanks for the update. No pressing need for it, just a NTH atm.
