### ISSUE TITLE
Silent Renew Failing

### ISSUE THREAD

**Issue by edleatherbury** [DuendeSoftware/Support#160]
Which version of Duende IdentityServer are you using?
5.2.4

Which version of .NET are you using?
5.0

We recently migrated from IdentityServer4 (3.1.2) to Duende 5.2.4. All core functionality works fine. We notice that silent renew is sporadically failing, however. Regardless of the `AccessTokenLifetime` value, calls to silent renew start failing between 30-60 minutes after initial login. Enabled debug and got this after about 45 minutes and numerous successful silent renews:

<img width="719" alt="Screen Shot 2022-08-15 at 12 16 36 PM" src="https://user-images.githubusercontent.com/1591298/184674386-1e1b3f8c-95e7-4e5b-a785-455dfa85214c.png">

Our issue is very similar to the following:

- https://github.com/IdentityModel/oidc-client-js/issues/766
- https://github.com/IdentityModel/oidc-client-js/issues/911

In both of those posts the solution was to add `services.AddAuthentication(x => x.DefaultAuthenticateScheme = IdentityServer4.IdentityServerConstants.DefaultCookieAuthenticationScheme);` after `services.AddIdentityServer(...)`. 

We added that code and got past the 60 minute window. We thought we were in the clear, but are still seeing auto-logout and errors after several hours. Here is one example of an error:

<img width="665" alt="Screen Shot 2022-08-15 at 9 08 43 AM" src="https://user-images.githubusercontent.com/1591298/184674570-8c2d0613-bd89-45ce-b51d-e052f7d2aed0.png">

Please note that we have _not_ added or enabled `CookieSlidingExpiration` in Startup. Could that be the cause?

Finally, [this post](https://github.com/IdentityModel/oidc-client-js/issues/1199) describes in great detail the same issue we are seeing. For that user the ultimate fix was upgrading to a later version of IdentityServer. Could it be that Duende 5.2.4 has the same issue that IdentityServer 4.0.4 had?

**Comment by brockallen** [comment]
> Please note that we have not added or enabled CookieSlidingExpiration in Startup. Could that be the cause?

Silent renew from the JS uses the session cookie from the OP in an iframe to obtain the new access tokens (assuming you're not using refresh tokens/offline_access). So yes, the cookie expiring would explain it.

**Comment by edleatherbury** [comment]
Thanks for that. Couple of follow-up questions:

- One of our apps has `automaticSilentRenew: false`, but silent renew is still called. Any idea why? I found the same question asked [here](https://github.com/IdentityModel/oidc-client-js/issues/1181), but I don't see where we're using your answer regarding `querySessionStatus`.
- [Duende docs](https://docs.duendesoftware.com/identityserver/v5/ui/login/session/#cookie-handler-configuration) seem to indicate that `DefaultCookieAuthenticationScheme` is the default for the session. If it is the default, why does it need to be explicitly added in Startup?

**Comment by brockallen** [comment]
> One of our apps has automaticSilentRenew: false, but silent renew is still called. Any idea why

There is an API to trigger this explicitly as well. Also, it might be due to the check session logic which uses querySessionStatus.

> Duende docs seem to indicate that DefaultCookieAuthenticationScheme is the default for the session. If it is the default, why does it need to be explicitly added in Startup?

We register it by default in our AddIdentityServer, but you can always use your own.
