### ISSUE TITLE
No matching item in store for key

### ISSUE THREAD

**Issue by MansoorJafari9** [DuendeSoftware/Support#161]
Hi
After we want to login  .we have this error for session key like
 No matching item in store for key  `51OIUYA6D8672E45A987459876D058B392B935576744E31E0A28783322116655`
and we don't have any idea for resolve this. please help.

**Comment by brockallen** [comment]
It sounds like you have configured server-side sessions. Have you configured a server-side store for those?

**Comment by MansoorJafari9** [comment]
Yes we configure service-side session, but we don't configure store for those 
 `    .AddServerSideSessions()
     .AddAspNetIdentity<ApplicationUser>()`

**Comment by brockallen** [comment]
You will need to configure a server-side store for the server-side session data:

https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/#enabling-server-side-sessions

**Comment by MansoorJafari9** [comment]
![image](https://user-images.githubusercontent.com/52848663/185126163-0aea847c-f125-4410-a160-08737d02688c.png)

you can see that we set configuration in program.cs

Do I need to configure `AddServerSideSessionStore` in program.cs

**Comment by MansoorJafari9** [comment]
@brockallen 

we only get this error for a few of users

**Comment by brockallen** [comment]
Ok, so yes it looks like you have a store -- that's good.

This is a very strange error -- it would only happen if on the same HTTP request the server side session can be validated, then later on that same request is needs to be updated in the store and now the record is missing. So there's something strange going on. Let me look into it a bit.

**Comment by brockallen** [comment]
> we only get this error for a few of users

Is there any pattern or behavior about these users that you can tell is different? For example, are  they logging in again with a current session (perhaps as a different user), or any other unusual patterns?

**Comment by brockallen** [comment]
Hmm... could it be related to this issue: https://github.com/dotnet/aspnetcore/issues/41516

**Comment by MansoorJafari9** [comment]
I can login with user like alex in a system but I can't login this user(alex) in another system has error No matching item in store for key

> 

I can login with user like alex in a system but I can't login this user(alex) in another system 
because I have an  error  `No matching item in store for key  `

**Comment by brockallen** [comment]
It's unclear what's happening to trigger this scenario, but given the guidance from [here](https://github.com/dotnet/aspnetcore/issues/41516#issuecomment-1178076544) it seems that code should be more defensive so a PR has been submitted to not fail in this scenario, and instead create the server-side record for the session.

**Comment by brockallen** [comment]
A patch has been pushed to NuGet -- sorry this one was a bit slow getting out.
