### ISSUE TITLE
how to get Access Token after SAML2 Authentication

### ISSUE THREAD

**Issue by jawaharrajan-investx** [DuendeSoftware/Support#162]
**Which version of Duende IdentityServer are you using?**
5.0

**Which version of .NET are you using?**
5.0

**Describe the bug**
Not a bug a question on interacting with SAML2 IPD

We are getting a SAML2 Assertion to our Identity Server
We Process the SAML Response Assertion and are able to :

Create a session: await saml2AuthnResponse.CreateSession(HttpContext, claimsTransform: (claimsPrincipal) => ClaimsTransform.Transform(claimsPrincipal));

            HttpContext.User = new ClaimsPrincipal(saml2AuthnResponse.ClaimsIdentity);
            var auth = HttpContext.User.Identity.IsAuthenticated;

the User is authenticated but missing the sub (even though I add it manuall in the ClaimsTransform method (above)

So I am not able to signIn to Duende IdentityServer with :
await HttpContext.SignInAsync(HttpContext.User, props);  as the sub is missing

If I do this:
                        var isuser = new IdentityServerUser(user.SubjectId)
                        {
                            DisplayName = user.Username,
                        };
                        await HttpContext.SignInAsync(isuser, props);
                        
it is successful, After this when I redirect to our MVC application the Access_Token is not present (I thougt that SignAsync would generate an accesstoken

Hence, I was asking how I can add an Access token , because in our MVC application we have an Authorize attribute on the entry point where we re-direct and this looking for an AccessToken
      
      Any ideas or help is appreciated

**Comment by brockallen** [comment]
Signing the user in, and getting a token back to your client are two different steps, and while one is needed before the other, problems with them would be two unrelated things. I'd suggest first getting your user signed in. 

When doing external authentication (like SAML), that's simply a substitute for the user using a local password. So in short, you use that to verify their identity. Once you've done that, then you establish the local session the same way regardless of how they authenticated. 

See this page on how to do that: https://docs.duendesoftware.com/identityserver/v6/ui/login/session/

Once you have that, then if you still have an issue with the access token, open a new issue.

**Comment by jawaharrajan-investx** [comment]
Hi Brock
I am able to Authenticate the external user from the SAML Assertion I receive.
I am able to create a Session then, I am also able to SignIn the User as a new Principal on the Identity Server.
But when I try to retrieve the access_token I do not get one
So can I set one manually that the Identity Server will accept.

Or do I have to reach back to the SAML IDP to get the Token or should they send it as part of the Assertion

Do I need to have this in my Identity Startup:

`services.AddAuthentication()
    .AddOpenIdConnect("AAD", "Employee Login", options =>
    {
        options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

        // other options omitted
    });`
    
    
The only issue I see here is that the external Athentication is not OpenIDConnet - does that matter ?

**Comment by brockallen** [comment]
>  But when I try to retrieve the access_token I do not get one

What have you done and/or configured in your client to obtain one? And what have you configured in IdentityServer to model your scopes and configure the client to receive one?

> Or do I have to reach back to the SAML IDP to get the Token or should they send it as part of the Assertion

Your SAML IdP is completely unrelated to this. As I mentioned before, an external IdP is just a substitute for a local username/password. The access token acquisition in a client is a different step and happens after the user is logged in.

**Comment by jawaharrajan-investx** [comment]
Hi Brock
So this is what we are doing
Startup class in our MVC Client and IDP (Duende Identity Server 5.0)
(named CLient_Startup and IDP_Startup to make it easier to attach here (I have removed some Dependency Injection classes to keep it a little easier to look at


[Client_Startup.txt](https://github.com/DuendeSoftware/Support/files/9374673/Client_Startup.txt)
[IDP_Startup.txt](https://github.com/DuendeSoftware/Support/files/9374693/IDP_Startup.txt)

For our NON SAML users once we do some internal verification of the user, this is how we sign them in :

`                    
TestUserStore _users;
UserAccount _tempUser = new();
_users = new TestUserStore(_tempUser.getUsers());

var claims = new List<Claim>
                        {
                            new Claim(JwtClaimTypes.Name, userValidated.UserName),
                            new Claim(JwtClaimTypes.GivenName, userValidated.FirstName),
                            new Claim(JwtClaimTypes.FamilyName, userValidated.LastName),
                            new Claim(JwtClaimTypes.Email, userValidated.EmailAddress),
                            new Claim(JwtClaimTypes.EmailVerified, userValidated.EmailConfirmed.ToString(), ClaimValueTypes.Boolean),
                            new Claim("account_type",userValidated.AccountType),
                            new Claim("account_id",userValidated.Id.ToString()),
                            new Claim("country",userValidated.CountryCode),
                            new Claim("company",userValidated.CompanyName),
                            new Claim("company_id",userValidated.CompanyId.ToString()),
                            //new Claim("role_id", string.Join(",",userValidated.Roles.Select(x => x.ToString()).ToList()))
                           //new Claim(JwtClaimTypes.Role, "admin")
                         };
                    _users.AutoProvisionUser(null, userValidated.Id.ToString(), claims);

                    var user = _users.FindByUsername(userValidated.UserName);
                    if (user != null)
                    {
                        await _events.RaiseAsync(new UserLoginSuccessEvent(user.Username, user.SubjectId, user.Username, clientId: context?.Client.ClientId));

                        // only set explicit expiration here if user chooses "remember me". 
                        // otherwise we rely upon expiration configured in cookie middleware.
                        AuthenticationProperties props = null;
                        if (AccountOptions.AllowRememberLogin && model.RememberLogin)
                        {
                            props = new AuthenticationProperties
                            {
                                IsPersistent = true,
                                ExpiresUtc = DateTimeOffset.UtcNow.Add(AccountOptions.RememberMeLoginDuration)
                            };
                        };

                        // issue authentication cookie with subject ID and username
                        var isuser = new IdentityServerUser(user.SubjectId)
                        {
                            DisplayName = user.Username
                        };
                        await HttpContext.SignInAsync(isuser, props);`

and this works fine, we can get the access_token when we need by this:

`            var accessToken = await _httpContextAccessor
                .HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);`

You can see that we have added some SAML code using the ITfoxtec SAML2 library 

once we process the SAML Assertion, and it is valid, we follow the same code as above and sign them in 

But when we try to get the access_token, it is null

We have tried having the SAML Assertion end point on both the  IDP and the MVC clinet but still cannot get an assigned Token after we sign the user 

await HttpContext.SignInAsync(isuser, props);

thanks

**Comment by brockallen** [comment]
> `TestUserStore`

You realize this class is just for testing, and isn't meant to be used as a real store for user data (mainly since it's all just an in-memory store)? Maybe you do, so just checking.

> and this works fine, we can get the access_token when we need by this:
> var accessToken = await _httpContextAccessor .HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);
> But when we try to get the access_token, it is null

Where is this code? In the client, or in your IdentityServer code somewhere? If it's in your IdentityServer, then it makes sense because the SAML protocol doesn't produce access tokens (that's only an OAuth/OIDC concept).

**Comment by jawaharrajan-investx** [comment]
Hi Brock,
Thanks for your reply
OK we are using the Teststore to add the user we are just about to Authenticate --> what you are saying is this is only an in Memory store, and we should really be using a real db store 

This line of code is always used in the Client app (the resource) to get the token for the current user
`var accessToken = await _httpContextAccessor .HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);`

Are you saying that it should not be on the client app, then how would we get the User token, would it be available as part of the User Principal object, I do not see it ?

**Comment by brockallen** [comment]
>  OK we are using the Teststore to add the user we are just about to Authenticate --> what you are saying is this is only an in Memory store, and we should really be using a real db store

Yes -- this is something that you should design and think about the state that's being processed. Also, keep in mind you want to issue a consistent sub claim for the external user, thus a mapping DB table of some sort is common here.

https://docs.duendesoftware.com/identityserver/v6/ui/login/external/

> This line of code is always used in the Client app (the resource) to get the token for the current user

The client app, or the API (which is commonly called the resource)?
