### ISSUE TITLE
Does Duende IdentityServer have an API end point for Authorization

### ISSUE THREAD

**Issue by jawaharrajan-investx** [DuendeSoftware/Support#165]
**Which version of Duende IdentityServer are you using?**
5.0
**Which version of .NET are you using?**
5.0
** Question** 
Is there an End point on the Duende IdentityServer that can be called directly skipping the Login page and pass in the credentials and Http Context, so Identity can return to the client app, just like in the regular flow when authorizing via IdentityServer

**Comment by brockallen** [comment]
Resource owner password flow is supported, but not recommended. 

https://docs.duendesoftware.com/identityserver/v6/tokens/password_grant/

**Comment by jawaharrajan-investx** [comment]
Hi Brock
we just need to sign in the User without the login screen, so could we call:

`GET /connect/authorize?
    client_id=client1&
    scope=openid email api1&
    response_type=id_token token&
    redirect_uri=https://myapp/callback&
    state=abc&
    nonce=xyz
    prompt none `
    
    then we can handle this with some custom code in the Account Controller in Identity
    
    
    Can we actually write a custom API or controller in Identity Server to handle clients that we want to authorize without a login 
    page , then re-direct back to our application so they have session in Identity and an access token

**Comment by brockallen** [comment]
That's now how the OIDC protocol is designed to work.

On a side note, we have an up coming training session would covers so many of these kinds of protocol concepts: https://duendesoftware.com/training/iac#register. It might worthwhile to attend.
