### ISSUE TITLE
Token endpoint returning "invalid_request" when the request body has form-data

### ISSUE THREAD

**Issue by bijub114** [DuendeSoftware/Support#168]
**Which version of Duende IdentityServer are you using?** 6.1.4

**Which version of .NET are you using?** .net 6

**Describe the bug**
The connect/token endpoint is returning an "invalid_request" when the request body is of type form-data (Content-Type=multipart/form-data). Is this some kind of restriction in IdentityServer6? This used to work in IdentityServer4.
It works if I use x-www-form-urlencoded, but I don't think we should send the client_id and client_secret to server as querystring.

**To Reproduce**
Here is the curl to reproduce the issue.
`curl --location --request POST 'https://localhost:5001/connect/token' \
--form 'client_id="client"' \
--form 'client_secret="secret"' \
--form 'grant_type="client_credentials"' \
--form 'scope="api1"'`

**Expected behavior**

 Token endpoint to work if the request body is of type form-data. 

**Log output/exception with stacktrace**

`[18:10:28 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP POST /connect/token responded 200 in 6211.9939 ms

[18:11:47 Debug] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv was not authenticated.

[18:11:47 Debug] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv was not authenticated.

[18:11:47 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Request path /connect/token matched to endpoint type Token

[18:11:47 Debug] Duende.IdentityServer.Hosting.EndpointRouter
Endpoint enabled: Token, successfully created handler: Duende.IdentityServer.Endpoints.TokenEndpoint

[18:11:47 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.TokenEndpoint for /connect/token

[18:11:47 Warning] Duende.IdentityServer.Endpoints.TokenEndpoint
Invalid HTTP request for token endpoint

[18:11:47 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP POST /connect/token responded 400 in 26.2595 ms`

**Additional context**

None.

**Comment by brockallen** [comment]
Multi-part form data is not what the spec allows for. It must be application/x-www-form-urlencoded.

https://www.rfc-editor.org/rfc/rfc6749.html#section-3.2

**Comment by bijub114** [comment]
Ok. Thanks for the spec, Brock!
