### ISSUE TITLE
Securing a SPA by Identityserver 6 before first load in .NET 6

### ISSUE THREAD

**Issue by RajaSomu783** [DuendeSoftware/Support#169]
**Which version of Duende IdentityServer are you using?**
 v6
**Which version of .NET are you using?**
.net6 - (Angular +.net6 spa template in visual studio 2022 and Authentication parameter none)

I am trying to implement authentication server using Identity Server 6 and trying to use this to authenticate multiple SPA applications with different domains. I have tested with .NET 3.1 and Identity server 4 and I can redirect to login page of the authentication server when accessing the spa for the first time but same thing is not working in .NET 6 and Identity Server 6. Spa is loading with home page initially without redirecting to login page and when I access the resource with [Authorize] attribute I am getting 200 status with login url as a response but it is not redirecting to login page.

I have followed this on [https://stackoverflow.com/questions/50225898/securing-a-spa-by-authorization-server-before-first-load?rq=1](url)  but could not make it work with the latest versions. So far the code looks as below on SPA angular app.

`using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Serilog;

Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();

Log.Information("Starting up");

try
{
    var builder = WebApplication.CreateBuilder(args);

    builder.Host.UseSerilog((ctx, lc) => lc
        .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}")
        .Enrich.FromLogContext()
        .ReadFrom.Configuration(ctx.Configuration));

    // Add services to the container.

    builder.Services.AddControllersWithViews();

    builder.Services.AddAuthentication(authenticationOptions =>
    {
        authenticationOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        authenticationOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    })
        .AddCookie("cookie")
        .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, openIdConnectOptions =>
        {
            openIdConnectOptions.Authority = builder.Configuration["InteractiveServiceSettings:AuthorityUrl"];
            openIdConnectOptions.ClientId = builder.Configuration["InteractiveServiceSettings:ClientId"];
            openIdConnectOptions.ClientSecret = builder.Configuration["InteractiveServiceSettings:ClientSecret"];
            openIdConnectOptions.Scope.Add(builder.Configuration["InteractiveServiceSettings:Scopes:0"]);
            openIdConnectOptions.GetClaimsFromUserInfoEndpoint = true;
            openIdConnectOptions.ResponseType = "code";
            openIdConnectOptions.SaveTokens = true;
            openIdConnectOptions.UsePkce = true;
            openIdConnectOptions.ResponseMode = "query";
            openIdConnectOptions.RequireHttpsMetadata = false;
            
        });

    builder.Services.AddAuthorization();

    var app = builder.Build();

    // Configure the HTTP request pipeline.
    if (!app.Environment.IsDevelopment())
    {
        // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
        app.UseHsts();
    }

    app.UseHttpsRedirection();
    app.UseStaticFiles();
    app.UseRouting();
    app.UseAuthentication();

    app.UseAuthorization();
    app.UseCors("AllowAll");
    app.Use(async (context, next) =>
    {
        if (!(context.User.Identity.IsAuthenticated && context.Request.Path != "/signin-oidc"))
        {
            await context.ChallengeAsync(OpenIdConnectDefaults.AuthenticationScheme);
        }
        else
        {
            await next();
        }
    });

   
    //app.UseEndpoints(endpoints =>
    //{
    //    endpoints.MapControllers();
    //    //fallback to SPA
    //    //endpoints.MapFallbackToFile("index.html");
    //    endpoints.MapFallback(CreateRequestDelegate(endpoints, "index.html"));
    //    //local function
    //    RequestDelegate CreateRequestDelegate(IEndpointRouteBuilder endpoints, string filePath)
    //    {
    //        var app = endpoints.CreateApplicationBuilder();
    //        //Use Cookie authentication to secure angular index.html file
    //        app.Use(async (context, next) =>
    //        {
    //            bool isAuth = false;
    //            //TODO: run logic to check authentication
    //            //....

    //            if (!isAuth)
    //            {
    //                await context.ChallengeAsync(OpenIdConnectDefaults.AuthenticationScheme);
    //            }
    //            else
    //            {
    //                await next.Invoke();
    //            }

    //        });
    //        //to SPA index.html
    //        app.Use(next => context =>
    //        {
    //            context.Request.Path = "/" + filePath;
    //            // Set endpoint to null so the static files middleware will handle the request.
    //            context.SetEndpoint(null);
    //            return next(context);
    //        });
    //        app.UseStaticFiles();
    //        return app.Build();
    //    }
    //});
    
    app.MapControllerRoute(
    name: "default",
    pattern: "{controller}/{action=Index}/{id?}");

    app.MapFallbackToFile("index.html");

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Unhandled exception");
}
finally
{
    Log.Information("Shut down complete");
    Log.CloseAndFlush();
}
`

**Comment by leastprivilege** [comment]
So your question is really about ASP.NET Core authorization system?

If you want to put a "global" authentication requirement on an ASP.NET Core application you would use a fall back policy, something like:

```cs
services.AddAuthorization(options =>
{   
   // policy used e.g. for [Authorize] without arguments
   options.DefaultPolicy = new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build();

  // global policy for all endpoints that do not specify a policy
  options.FallbackPolicy = options.DefaultPolicy;
});
```

**Comment by RajaSomu783** [comment]
Hi @leastprivilege ,
Many thanks for your reply.

Yes it is a problem with the  .NET 6 and unfortunately it didn't work what you have suggested.  As I mentioned in the initial post, I would like to show login page from identity server 6 rather than home page from SPA application. The problem is I don't know exactly how to redirect to login page by modifying the middlewares of the SPA application in .net6. I have used below code in .NET CORE 3.1 to show login page before loading the spa application and it works but same thing is not working in .NET 6.

`  app.Use(async (context, next) =>
            {
                if (!context.User.Identity.IsAuthenticated)
                {
                    await context.ChallengeAsync("oidc");
                }
                else
                {
                    await next();
                }
            });

            app.UseSpa(spa =>
            {
                // To learn more about options for serving an Angular SPA from ASP.NET Core,
                // see https://go.microsoft.com/fwlink/?linkid=864501

                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.UseAngularCliServer(npmScript: "start");
                }
            });`

**Comment by RajaSomu783** [comment]
Hi @brockallen or @leastprivilege ,

Apologies asking again without waiting for your response.
Could you please let me know if you have any update on this ?
Thanks

**Comment by brockallen** [comment]
If you want an anonymous request to trigger the OIDC login workflow, then you don't want your static file middleware earlier than your authentication/authorization middleware, right?

**Comment by RajaSomu783** [comment]
Yes, I would like to show login page from Identity server.

**Comment by brockallen** [comment]
I'm not sure then -- also, I don't see why your custom middleware approach above would not work in ASP.NET Core (except that it's also running after the static files).

**Comment by RajaSomu783** [comment]
Okay, I am not really sure why it is not working in .NET6 . I am getting 200 response with login url to identity server when I tried to access the resource.
Would you mind if I ask you one last question, do you have any sample with Angular /React+.net6 spa template in visual studio?

![image](https://user-images.githubusercontent.com/111736502/186475322-759a2a51-07aa-454e-90d2-b57c1aec56d3.png)

**Comment by brockallen** [comment]
Is that an Ajax request? Looks like it's getting redirected to IdentityServer, so your redirect is working? But you don't want that redirect for Ajax requests -- you want a 401 instead.

**Comment by RajaSomu783** [comment]
Yes,  it is a standard request made using httpclient (as below)library in angular.  I would like to redirect to IdentityServer login page when anonymous request  trying to access the resource or before loading actual spa home page like it is happening in .NET CORE 3.1.  I have been trying to use status code page (UseStatusCodePages) middleware but none of them working. It would be great if you have any working samples  in .net6.

`http.get<WeatherForecast[]>(baseUrl + 'weatherforecast').subscribe(result => {
      this.forecasts = result;
    }, error => console.error(error));`

**Comment by brockallen** [comment]
If the call is an Ajax request and the user is anonymous the response can't be a redirect to a HTML page. It looks like this is what's happening. Rather, the response should be a 401 and your JS logic would check for this status code and then redirect the top level window to the UI endpoint that triggers the OIDC login request/redirect workflow.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by RajaSomu783** [comment]
Yes we can close this. It looks like either problem with the .NET6 or I am missing something on .NET 6 side. I have been implementing on Frontend using 'angular-auth-oidc-client' and I can redirect to Identity server without any issues.
