### ISSUE TITLE
Third-party cookies getting blocked

### ISSUE THREAD

**Issue by CobusKruger** [DuendeSoftware/Support#17]
**Which version of Duende IdentityServer are you using?**

IdentityServer4

**Which version of .NET are you using?**

.NET 6

**Describe the bug**

All major browser makers are clamping down on third-party cookies. After recent Chrome updates, several of our users have their third-party cookies blocked. We have an Angular 13 SPA connection to IdentityServer4, authenticating through Azure AD.

**To Reproduce**

Sign into IdentityServer4 instance, connecting to Azure AD

**Expected behavior**

Since we're using JWT authentication, I don't expect there to be cookies at all.

**Additional context**

I'm struggling to see why the cookies are even needed when authentication happens using JWT. Isn't there a way to avoid its use?

**Comment by brockallen** [comment]
Yes, this is something beyond our control. This is why we have seen customers moving to the [BFF Architecture](https://docs.duendesoftware.com/identityserver/v6/bff/overview/).
