### ISSUE TITLE
HOw to create client with JWK sets?? and how to get the client token??

### ISSUE THREAD

**Issue by shoaibismailAppify** [DuendeSoftware/Support#170]
i can see these explanation on duende website.. i need to know how after creating such client how to get its token??? and 
does its client id is itself a token??? 
var client = new Client
{
    ClientId = "client.jwt",

    ClientSecrets =
    {
        new Secret
        {
            // base64 encoded X.509 certificate
            Type = IdentityServerConstants.SecretTypes.X509CertificateBase64,

            Value = "MIID...xBXQ="
        }
        new Secret
        {
            // JWK formatted RSA key
            Type = IdentityServerConstants.SecretTypes.JsonWebKey,

            Value = "{'e':'AQAB','kid':'Zz...GEA','kty':'RSA','n':'wWw...etgKw'}"
        }
    },

    AllowedGrantTypes = GrantTypes.ClientCredentials,
    AllowedScopes = { "api1", "api2" }
};

**Comment by shoaibismailAppify** [comment]
@leastprivilege  can you please guide???

**Comment by brockallen** [comment]
Here is our sample that shows using the client JWT for authentication:

https://docs.duendesoftware.com/identityserver/v6/samples/basics/#jwt-based-client-authentication

**Comment by shoaibismailAppify** [comment]
@brockallen yeah i have gone through these docs already
actually need to know about this 
 new Secret
    {
        // base64 encoded X.509 certificate
        Type = IdentityServerConstants.SecretTypes.X509CertificateBase64,

        Value = "MIID...xBXQ="
    }
    
    how can i get this base64 encoded X.509 certificate to register my client... and one more thing do we need both base64 encoded X.509 certificate and JWK formatted RSA key???

**Comment by shoaibismailAppify** [comment]
actually i have a client app which ask me to register itself with my identity server with following keys
{
  "keys": [
    {
      "kty": "EC",
      "crv": "P-384",
      "x": "JQKTsV6PT5Szf4QtDA1qrs0EJ1pbimQmM2SKvzOlIAqlph3h1OHmZ2i7MXahIF2C",
      "y": "bRWWQRJBgDa6CTgwofYrHjVGcO-A7WNEnu4oJA5OUJPPPpczgx1g2NsfinK-D2Rw",
      "use": "sig",
      "key_ops": [
        "verify"
      ],
      "ext": true,
      "kid": "4b49a739d1eb115b3225f4cf9beb6d1b",
      "alg": "ES384"
    },
    {
      "kty": "RSA",
      "alg": "RS384",
      "n": "vjbIzTqiY8K8zApeNng5ekNNIxJfXAue9BjoMrZ9Qy9m7yIA-tf6muEupEXWhq70tC7vIGLqJJ4O8m7yiH8H2qklX2mCAMg3xG3nbykY2X7JXtW9P8VIdG0sAMt5aZQnUGCgSS3n0qaooGn2LUlTGIR88Qi-4Nrao9_3Ki3UCiICeCiAE224jGCg0OlQU6qj2gEB3o-DWJFlG_dz1y-Mxo5ivaeM0vWuodjDrp-aiabJcSF_dx26sdC9dZdBKXFDq0t19I9S9AyGpGDJwzGRtWHY6LsskNHLvo8Zb5AsJ9eRZKpnh30SYBZI9WHtzU85M9WQqdScR69Vyp-6Uhfbvw",
      "e": "AQAB",
      "use": "sig",
      "key_ops": [
        "verify"
      ],
      "ext": true,
      "kid": "b41528b6f37a9500edb8a905a595bdd7"
    }
  ]
}

so i am confused where this scenario fits in with client credential work flow... i am new to it can you please guide??
@leastprivilege @brockallen

**Comment by brockallen** [comment]
This C# snippet would create a JWK:

```
var key = new RsaSecurityKey(RSA.Create(2048));
var jwk = JsonWebKeyConverter.ConvertFromRSASecurityKey(key);
jwk.Alg = "RS256";
```

**Comment by shoaibismailAppify** [comment]
and we need both of these??
or one would be enough
 new Secret
    {
        // base64 encoded X.509 certificate
        Type = IdentityServerConstants.SecretTypes.X509CertificateBase64,

        Value = "MIID...xBXQ="
    }
    new Secret
    {
        // JWK formatted RSA key
        Type = IdentityServerConstants.SecretTypes.JsonWebKey,

        Value = "{'e':'AQAB','kid':'Zz...GEA','kty':'RSA','n':'wWw...etgKw'}"
    }

**Comment by brockallen** [comment]
Nope, just one or the other. I think I had a sample PS script for creating self-signed certs... here: https://gist.github.com/brockallen/c11e4494a60303dd1c44754b978979c8

**Comment by shoaibismailAppify** [comment]
i tried with both..
my client app is calling this end point  /connect/token with these parameters 
client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzM4NCIsImtpZCI6IjRiNDlhNzM5ZDFlYjExNWIzMjI1ZjRjZjliZWI2ZDFiIn0.eyJpc3MiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpGVXpNNE5DSXNJbXRwWkNJNklqUmlORGxoTnpNNVpERmxZakV4TldJek1qSTFaalJqWmpsaVpXSTJaREZpSW4wLmV5SnBjM01pT2lKcGJtWmxjbTV2VTNsemRHVnRRMnhwWlc1MElpd2ljM1ZpSWpvaWFXNW1aWEp1YjFONWMzUmxiVU5zYVdWdWRDSXNJbUYxWkNJNkltaDBkSEJ6T2k4dmFXRnRMbVYwYUdsNmJ5NWpiMjB2WTI5dWJtVmpkQzkwYjJ0bGJpSXNJbVY0Y0NJNk1UWTJNVEkyTkRZeE15d2lhblJwSWpvaU16Z3dNVFl4TVRObE9UZzFNMlpqTnpVeU9HSTVZV0l4TUdKak9EYzJZelZpWlRNeVpERmtPV0U1TWpsaE5tTmpPRGMxTkdNM09EazFaVGswWkRFNU5DSjkuNWN4TXQ3OW1KaXRuNEZyMm11THNkMVFJQ2lYcjhkTnZXd09IaWdzRmlrWmpQU0pSRl8wam54MTg4Uk9IVDlmN2VnLWFMRkFpd0p3ZVB3T21lZVg0YVdyTGZJTXd6WkYzQ3hmU2JNeXZnSTJ0andGMFN5cFgybU9YbDBQNkh0QUUiLCJzdWIiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpGVXpNNE5DSXNJbXRwWkNJNklqUmlORGxoTnpNNVpERmxZakV4TldJek1qSTFaalJqWmpsaVpXSTJaREZpSW4wLmV5SnBjM01pT2lKcGJtWmxjbTV2VTNsemRHVnRRMnhwWlc1MElpd2ljM1ZpSWpvaWFXNW1aWEp1YjFONWMzUmxiVU5zYVdWdWRDSXNJbUYxWkNJNkltaDBkSEJ6T2k4dmFXRnRMbVYwYUdsNmJ5NWpiMjB2WTI5dWJtVmpkQzkwYjJ0bGJpSXNJbVY0Y0NJNk1UWTJNVEkyTkRZeE15d2lhblJwSWpvaU16Z3dNVFl4TVRObE9UZzFNMlpqTnpVeU9HSTVZV0l4TUdKak9EYzJZelZpWlRNeVpERmtPV0U1TWpsaE5tTmpPRGMxTkdNM09EazFaVGswWkRFNU5DSjkuNWN4TXQ3OW1KaXRuNEZyMm11THNkMVFJQ2lYcjhkTnZXd09IaWdzRmlrWmpQU0pSRl8wam54MTg4Uk9IVDlmN2VnLWFMRkFpd0p3ZVB3T21lZVg0YVdyTGZJTXd6WkYzQ3hmU2JNeXZnSTJ0andGMFN5cFgybU9YbDBQNkh0QUUiLCJhdWQiOiJodHRwczovL2lhbS5ldGhpem8uY29tL2Nvbm5lY3QvdG9rZW4iLCJleHAiOjE2NjEyNjUxNzUsImp0aSI6ImRkYjIyZjQxMDkyYTY0NDlmOWNiYjQ4NzgyY2QxZmI0MGQyZWQ1Nzc4NjdjNTM0ZWVhMjU2NGU3NmZkNWMxMzYifQ.m-nWIEKV1sv6zxX72jaq5L12Owixl-nxFYfOkINGyUPx-qZH2uJYUQC-iKJedpJRUZGyzyqWK1OelYu-Ze1w38gwMss1xGQ50esom6xd8dYyz6-XYhT45F7uDfiySDLx&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&grant_type=client_credentials&scope=system%2F%2A.read

but its says  invalid client..
when i see logs on identity server side it say

Invalid HTTP request for token endpoint    No client identifier found

**Comment by brockallen** [comment]
Your iss and sub claims look wrong to me

![image](https://user-images.githubusercontent.com/649492/186223649-034d9b03-b6a9-4764-be17-a28ea2d0d57c.png)

**Comment by shoaibismailAppify** [comment]
![image](https://user-images.githubusercontent.com/107938257/186226399-ba0b4195-991c-4238-b0cd-576d946b34fd.png)

its not even working with this way.....

**Comment by brockallen** [comment]
This is what our sample has:

![image](https://user-images.githubusercontent.com/649492/186227085-18dc89da-9435-4e70-bc07-ec0d778c3e44.png)

**Comment by shoaibismailAppify** [comment]
@brockallen  is this something related to  .AddDeveloperSigningCredential(false)

i am using the same for both dev and prod Env...
do i need to have AddSigningCredential in prod ??

if yes how to get certificate for this???

My client App Inferno Server just say resgister with keys provided above..
can you please list down the steps may be i am missing a minor thing???
@leastprivilege ???

**Comment by brockallen** [comment]
>  is this something related to .AddDeveloperSigningCredential(false)

This API is used to add a signing credential for IdentityServer itself to sign tokens for when you're doing local development or testing and don't want to bother with a more formal signging credential (since you're just doing local dev/testing). It's unrelated to credentials clients use to authenticate to IdentityServer. 

>  do i need to have AddSigningCredential in prod

Absolutely: https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/

**Comment by shoaibismailAppify** [comment]
as my client App already provided two keys.. i think i can use any of them...
so those key should be injected and used in my startup???
i should disable automatic key management and inject my client provided key???
like this???
var builder = services.AddIdentityServer(options =>
{  
    options.KeyManagement.Enabled = false;
});

var key = LoadKeyFromVault();
builder.AddSigningCredential(key, SecurityAlgorithms.RsaSha256);

and similarly create client with same key  provided by my client
like this 
new Secret
    {
        // JWK formatted RSA key
        Type = IdentityServerConstants.SecretTypes.JsonWebKey,

        Value = "{client App provided key}"
    }
    and i will be good to go??? am i??

**Comment by brockallen** [comment]
> as my client App already provided two keys.. i think i can use any of them...

Yes, for client authentication.

>  so those key should be injected and used in my startup???

Those will be configured as part of the Client configuration, however you do that: https://docs.duendesoftware.com/identityserver/v6/data/configuration/

>  i should disable automatic key management and inject my client provided key???

As I mentioned above, the signing credentials used by IdentityServer are unrelated to the credentials a client uses to authenticate. This seems to be a point you're confused on, or I am not understanding what you're trying to do.

As for your IdentityServer signing credential, it looks like above you might be using key vault, so that works and then yes you'd disable automatic key management.

**Comment by shoaibismailAppify** [comment]
let me explain you my scenario we have FHIR APIs Identity server is used for authentication and stuff... we testing tool called inferno here is the link https://inferno.healthit.gov/
inferno says to register inferno as a Client app do  as explained in Picture below.


![image](https://user-images.githubusercontent.com/107938257/186463607-065f8182-d44b-407e-a878-79f801e34b4d.png)
  the URL in the pic for JWK set is 
  https://inferno.healthit.gov/suites/custom/g10_certification/.well-known/jwks.json
  
  for this flow i am using a GrantTypes.ClientCredentials, with keys provided in above link....
  
   this is the whole story i am stuck in

**Comment by brockallen** [comment]
So you need to configure their client in your IdentityServer?

**Comment by shoaibismailAppify** [comment]
yes

**Comment by brockallen** [comment]
Ok, I see. 

So first so you're aware -- this is unrelated to the IdentityServer signing credentials. 

So that JSON URL is the client's public keys, and it's an array. So you'd have to take each one of those and add them into the IdentityServer's config for that client. Each one of those would be added as a distinct secret, For example, if you did the config as code/in-memory, it might look like this:

```
new Client
{
    ClientId = "client.jwt",
    ClientSecrets =
    {
        new Secret
        {
            Type = IdentityServerConstants.SecretTypes.JsonWebKey,
            Value =
                @"
                {
                      'kty': 'EC',
                      'crv': 'P-384',
                      'x': 'JQKTsV6PT5Szf4QtDA1qrs0EJ1pbimQmM2SKvzOlIAqlph3h1OHmZ2i7MXahIF2C',
                      'y': 'bRWWQRJBgDa6CTgwofYrHjVGcO-A7WNEnu4oJA5OUJPPPpczgx1g2NsfinK-D2Rw',
                      'use': 'sig',
                      'key_ops': [
                        'verify'
                      ],
                      'ext': true,
                      'kid': '4b49a739d1eb115b3225f4cf9beb6d1b',
                      'alg': 'ES384'
                    }"
      },
      new Secret
      {
          Type = IdentityServerConstants.SecretTypes.JsonWebKey,
          Value =
              @"
              {
                    'kty': 'RSA',
                    'alg': 'RS384',
                    'n': 'vjbIzTqiY8K8zApeNng5ekNNIxJfXAue9BjoMrZ9Qy9m7yIA-tf6muEupEXWhq70tC7vIGLqJJ4O8m7yiH8H2qklX2mCAMg3xG3nbykY2X7JXtW9P8VIdG0sAMt5aZQnUGCgSS3n0qaooGn2LUlTGIR88Qi-4Nrao9_3Ki3UCiICeCiAE224jGCg0OlQU6qj2gEB3o-DWJFlG_dz1y-Mxo5ivaeM0vWuodjDrp-aiabJcSF_dx26sdC9dZdBKXFDq0t19I9S9AyGpGDJwzGRtWHY6LsskNHLvo8Zb5AsJ9eRZKpnh30SYBZI9WHtzU85M9WQqdScR69Vyp-6Uhfbvw',
                    'e': 'AQAB',
                    'use': 'sig',
                    'key_ops': [
                      'verify'
                    ],
                    'ext': true,
                    'kid': 'b41528b6f37a9500edb8a905a595bdd7'
                  }"
        },
    },
    AllowedGrantTypes = GrantTypes.ClientCredentials,
    AllowedScopes = { "resource1.scope1", "resource2.scope1" }
},
```

Also, to support client JWTs, you also need in your IdentityServer startup:

```
services.AddIdentityServer()
   .AddJwtBearerClientAuthentication()
   ...
```

**Comment by shoaibismailAppify** [comment]
let me try with it

**Comment by shoaibismailAppify** [comment]
@brockallen  thanks man its working now...
 .AddJwtBearerClientAuthentication() this was missing in my startup
