### ISSUE TITLE
User/Role management with IdentityServer+BFF+SPA

### ISSUE THREAD

**Issue by tLXvGt** [DuendeSoftware/Support#171]
### Which version of Duende IdentityServer are you using?
6.1.0

### Which version of .NET are you using?
.NET 6

### Question

I am following Quickstarts from official docs, I have just finished all of them with the final JavaScriptClient project that uses BFF and IdentityServer. I managed to create auth flow and some authorized controllers content, so far so good. However, I encountered problems when it comes to user management.

My use case is a SPA that provides content for users, but only some of them (Creators) can edit it. Additionally I would like to have some kind of user management page for Admins that will allow them to promote and demote other users as Creators. In a traditional app I would have `DbContext`/`UserManager` that would be protected by Admin role access so I can generally modify users however I want. This seems to be complicated with BFF+IdentityServer setup, because users database is in IdentityServer project while BFF project has no access to that DbContext. I tried to reference IdentityServer project and inject `UserManager` from there, but it requires transplanting half of the Identity to BFF project (which I guess misses the whole point?).

What is the official, preferred way of modifying Users and Roles with IdentityServer being a separate service?

**Comment by brockallen** [comment]
User and role management are beyond the scope of the IdentityServer product. That's entirely up to your identity management library and how you want to design those things, typically very contingent on your architecture and requirements.

**Comment by tLXvGt** [comment]
Thank you, this issue can be closed.
