### ISSUE TITLE
Your license for Duende IdentityServer only permits 1 number of issuers

### ISSUE THREAD

**Issue by eddie-mofokeng** [DuendeSoftware/Support#173]
We are currently using Azure App Service to deploy Identity Server. We have set up a custom domain from cloudflare which we use for our service. It does not look like there's a way to disable the public url that comes with app service so we're looking for a way around the following error we get : 

`Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: ["https://*****.org","https://**********.azurewebsites.net"].`

Any help will be appreciated thanks.

**Comment by brockallen** [comment]
It sounds like something is making a request to the non-official host name of your IdentityServer. What could that be?

**Comment by eddie-mofokeng** [comment]
Seems to be the health check endpoint for the app service

**Comment by brockallen** [comment]
Do you configure that, and if so can you set it to the public host name or some other non-OIDC endpoint?

**Comment by eddie-mofokeng** [comment]
I can only configure the path, but yes I have changed it to a non-OIDC path and haven't have the error coming up. We are looking at doing a redirect though, we don't want the the *.azurewebsites.net to be accessible. Thanks.
