### ISSUE TITLE
duende vs keycloak load test

### ISSUE THREAD

**Issue by A-Yavari** [DuendeSoftware/Support#174]
Our company business line needs to handle Thousands of users log ins at the same time, and the performance is very important and critical to us. 
We set a benchmark between two majore sso technologies called duende and keycloak. We used the same server and  the following software technologies used in each sample applications :
In the sample application with duende We used. Net 6, c# and sql server, and in the keycloak sample application we used postgresql  as a database and spring security and java. 
And we used jmeter as the load test tools on both sample applications. 

The result of the comparison was disappointing,,,, the keycloak sample application can produce 500 tokens per second but the duende sample application can  produce 300 tokens per second.
 We are wondering are there any special configurations or settings that we missed at the duende framework?? Have we done something wrong? How we can improve the performance of the duende based sample application.
Any help and suggestions would be highly appreciated.

**Comment by brockallen** [comment]
Can you elaborate on which protocol flows you're testing? Are they the same in both tests?

**Comment by A-Yavari** [comment]
> Can you elaborate on which protocol flows you're testing? Are they the same in both tests?

Thank you for your attention, 
with the same flows.
Both flows are passwords

**Comment by brockallen** [comment]
>  Both flows are passwords

Resource owner password flow? Or do you mean client credential flow?

**Comment by A-Yavari** [comment]
> >  Both flows are passwords
> 
> 
> 
> Resource owner password flow? Or do you mean client credential flow?

Yes, Resource owner password flow

**Comment by A-Yavari** [comment]
--And this my configuration--
internal static WebApplicationBuilder ConfigureIdentityServer(this WebApplicationBuilder builder)
    {        
        var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");       

        builder.Services.AddIdentityServer(options =>
        {            
            options.Authentication.CoordinateClientLifetimesWithUserSession = true;
            options.ServerSideSessions.UserDisplayNameClaimType = JwtClaimTypes.Name;
            options.ServerSideSessions.RemoveExpiredSessions = true;
            options.ServerSideSessions.RemoveExpiredSessionsFrequency = TimeSpan.FromSeconds(10);
            options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;            
        })
            .AddAspNetIdentity<ApplicationUser>()
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString);
            })
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString);
                options.EnableTokenCleanup = true;
                options.RemoveConsumedTokens = true;
                options.TokenCleanupInterval = 1000;
                //options.TokenCleanupBatchSize = 200;
            })
            .AddConfigurationStoreCache();
        return builder;
    }

**Comment by brockallen** [comment]
Do you know if keycloak's refresh tokens are store server-side or are they self-contained? 

In IdentityServer they are stored server-side, which allows for revocation.

https://docs.duendesoftware.com/identityserver/v6/data/operational/grants/

Also, they are stored with data protection for GDPR/CCPA, but if you have a solution for that (e.g. the DB is configured to encrypt at rest) then you can disable this which will reduce some of that overhead:

https://docs.duendesoftware.com/identityserver/v6/reference/options/#persistentgrants

**Comment by A-Yavari** [comment]
> Do you know if keycloak's refresh tokens are store server-side or are they self-contained? 
> 
> 
> 
> In IdentityServer they are stored server-side, which allows for revocation.
> 
> 
> 
> https://docs.duendesoftware.com/identityserver/v6/data/operational/grants/
> 
> 
> 
> Also, they are stored with data protection for GDPR/CCPA, but if you have a solution for that (e.g. the DB is configured to encrypt at rest) then you can disable this which will reduce some of that overhead:
> 
> 
> 
> https://docs.duendesoftware.com/identityserver/v6/reference/options/#persistentgrants
> 
> 
> 
> Finally, all of our stores are pluggable extensibility points, so if you would prefer to handle some of these things differently or better tuned for your scenario, you can because we are a framework (and not a full blown IAM).

Thank you so much for getting back to me and your great solution. I reviewed the documents and will follow the instructions then will return the results to you.🌷

**Comment by A-Yavari** [comment]
@brockallen 

Thank you very much for your help
The performance of the program increased by at least 50% with the document that you introduced, I noticed only one problem when I use TestUser, the performance is excellent, which is normal, but when I use ApplicationUser and read the information from SQL server, the performance decreases a lot. Is there any way for caching the Applicationuser?

**Comment by brockallen** [comment]
>  but when I use ApplicationUser and read the information from SQL server, the performance decreases a lot. Is there any way for caching the Applicationuser?

That's all from Microsoft's ASP.NET Identity, not from IdenityServer. We don't control any of that -- that would be your code/logic.

**Comment by A-Yavari** [comment]
@brockallen I really appreciate your advice, your help was useful for me. Best Regards
