### ISSUE TITLE
[Question] Concurrency for key management

### ISSUE THREAD

**Issue by marcindruzgala** [DuendeSoftware/Support#176]
**Which version of Duende IdentityServer are you using?**
6.1.4

**Which version of .NET are you using?**
6.x

**Question**

I was investigating a bit how key management works, especially for scenarios where we have multiple instances of our IdP running in production. One of the developers in our team asked how is concurrency handled in scenarios where we have  > 1 of instances of Duende Server running and keys have to be rotated.

So I did a bit of investigation and I found `KeyManager` and a method `GetAllKeysInternalAsync`. In that method (line 138) if rotation is required you're acquiring lock before you continue:

```c#
// need to create new key, but another thread might have already so acquiring lock.
if (false == await _newKeyLock.LockAsync((int)_options.Caching.CacheLockTimeout.TotalMilliseconds))
``` 

The implementation of `IConcurrencyLock<KeyManager>` is acquiring 'local' lock by using `SemaphoreSlim` class which is fine if we have just one instance of the service running but it won't work for multiple instances.

So my question is: should we provide an implementation of `IConcurrencyLock<T>` that acquires distributed lock or is there something else in code that I haven't found or...is there something else you'd recommend?

**Comment by brockallen** [comment]
That lock is meant to protect against concurrent threads in the current host process from creating new keys at the same time. I support in theory you could replace it with a distributed lock. But to be honest, if you have multiple nodes that each happen to create new keys at the same time, it's ok -- the workflow allows for this and handles it.

**Comment by marcindruzgala** [comment]
Alright, that makes sense. Thanks for the answer!
