### ISSUE TITLE
Identity Server login not working in chrome

### ISSUE THREAD

**Issue by devarajuvraju** [DuendeSoftware/Support#177]
**Which version of Duende IdentityServer are you using?**
IdentityServer4 4.1.2 

**Which version of .NET are you using?**
.Net Core 6 and .Net framework 4.6.1

**Describe the bug**
Users are not able to login using identity server when trying to chrome. In firefox, it is working fine. This is happening only on servers. Locally we can see, it is working fine for both browsers.

Bug is about users having issue login via identity server in chrome browser in servers.
Chrome version - Version 104.0.5112.102
Firefox version - 104.0 (64-bit)

**To Reproduce**
User same chrome version and try to login via identity server in servers.

Steps to reproduce the behavior.
Use chrome and login via identity server and see if we able to login and cookies are storing correctly.

**Expected behavior**
Users should be able to login successfully and redirect to redirecturl

Users succesfully logged in and land in landing page.

**Log output/exception with stacktrace**
Owin stack trace is shown below : 

)Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationMiddleware Error: 0 : Exception occurred while processing message: 
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.Convert.FromBase64String(String s)
   at SMA.Web.Startup.RetrieveCodeVerifier(MessageReceivedNotification`2 arg) in D:\BuildAgent\work\37d290dfeae8495f\Project Root\Web\App_Start\Startup.Auth.cs:line 200
   at SMA.Web.Startup.<ProcessMessageReceived>d__6.MoveNext() in D:\BuildAgent\work\37d290dfeae8495f\Project Root\Web\App_Start\Startup.Auth.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__11.MoveNext(

```
data
```

**Additional context**
We guess this might be something to do with cookies since in servers, we can see cookies fine in firefox but not on chrome.

**Comment by brockallen** [comment]
This sounds like it might have something to do with SameSite cookies and cookies issued by the server being rejected by the browser due to invalid combination of SameSite and host settings. Are you using HTTPS?

**Comment by devarajuvraju** [comment]
Hi @brockallen thanks for reply. Yes, both identity server and client app (load balancer) is using https. 

Code we using for cookie policy is shown below :

 ```
app.UseCookiePolicy(new CookiePolicyOptions
            {
                HttpOnly = HttpOnlyPolicy.None,
                MinimumSameSitePolicy = SameSiteMode.None,
                Secure = CookieSecurePolicy.Always
            });
```

Any help on this would be really appreciated.

**Comment by brockallen** [comment]
I bet if you look in your Chrome developer tools on the HTTP traffic in the details for the HTTP response that sets the cookie, you will see a little yellow warning icon on the set-cookie line that tells you what Chrome did not like about the cookie. My guess, if I'm reading the above correctly, is that you might be missing the HTTP only flag... but to be fair, I don't recall exactly how the cookie policy affects cookies with the right config (I'd have to go review it). In my solutions, I always set each cookie config explicitly and I don't use the cookie policy stuff.

**Comment by devarajuvraju** [comment]
Hi @brockallen thank you very much for quick reply. I will check this and get back to you with my findings. Appreciate your help on this!

**Comment by devarajuvraju** [comment]
Hi @brockallen you were right. I can see yellow warning on my response cookie saying set-cookie header was blocked because it had the SameSite=None attribute but did not have the secure attribute error. 

I am not able to resolve this in my code. Could you please send some code snippet if you have any of how I can resolve this? or any link which has solution would be good as well. Thank you

**Comment by brockallen** [comment]
You would have to change how you issue/configure the cookie. That's something you'd check the Microsoft/ASP.NET docs for.

**Comment by devarajuvraju** [comment]
Thank you very much @brockallen  for your help!
