### ISSUE TITLE
User is not authenticated when calling IdentityServer as BFF remote api

### ISSUE THREAD

**Issue by tLXvGt** [DuendeSoftware/Support#179]
### Which version of Duende BFF are you using?
6.1.0

### Which version of .NET are you using?
.NET 6.0

### Question
I have finished all Quickstart projects and I am looking for ways to manage Roles.

I have 3 projects: `JavaScriptClient`, `IdentityServer`, `Api` (all from quickstarts). I am using BFF in `JavaScriptClient` project, I can call local APIs and remote `Api` APIs. Now I am trying to also call `IdentityServer` as a remote API, however it always fails (user is not authenticated).

I noticed that `Api` project has bearer authentication:
```csharp
builder.Services.AddAuthentication("Bearer")
    .AddJwtBearer("Bearer", opt =>
    {
        opt.Authority = "https://localhost:5001";
        opt.TokenValidationParameters = new() { ValidateAudience = false };
    });
```

Whereas `IdentityServer` has `.AddIdentityServer()` that calls `.AddAuthentication()` deep inside which may affect that bearer auth? I tried to copy that code above from `Api` to `IdentityServer` project and it has no effects. I also tried `.AddIdentityServer().AddJwtBearerClientAuthentication()`, did not help.

Is there a way to authenticate a remote call from `JavaScriptClient` that uses BFF?

**Comment by brockallen** [comment]
> I have finished all Quickstart projects and I am looking for ways to manage Roles.

Great -- have a look here on how to configure what claims go where (id_token vs access_token):

https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

As for why your API is failing, there's not really enough info here for me to help.

**Comment by tLXvGt** [comment]
Thank you for the answer. I have managed to map roles from IdentityServer so I can use them with `[Authorize(Roles = "")]` attribute and `User.IsInRole("")`. Regarding my API question - forgive me for lack of details, I will try to explain myself a bit better.

I am using JavaScriptClient project exactly as in Quickstarts. It uses BFF:

```cs
builder.Services.AddBff()
    .AddRemoteApis();

JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
builder.Services
    .AddAuthentication(opt =>
    {
        opt.DefaultScheme = "Cookies";
        opt.DefaultChallengeScheme = "oidc";
        opt.DefaultSignOutScheme = "oidc";
    })
    .AddCookie("Cookies")
    .AddOpenIdConnect("oidc", opt =>
    {
        opt.Authority = "https://localhost:5001";

        opt.ClientId = "bff";
        opt.ClientSecret = "secret";

        opt.ResponseType = "code";
        opt.Scope.Add("api1");
        opt.Scope.Add("roles");
        opt.ClaimActions.MapJsonKey("http://schemas.microsoft.com/ws/2008/06/identity/claims/role", "role", "role");
        opt.SaveTokens = true;
        opt.GetClaimsFromUserInfoEndpoint = true;
    });
```
It uses remote BFF API endpoint that points to Api project. Here I wanted to add IdentityServer as BFF API endpoint exactly how Api is added:

```cs
app.UseRouting();
app.UseAuthentication();
app.UseBff();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapBffManagementEndpoints();

    endpoints.MapControllers()
        .AsBffApiEndpoint();

    endpoints.MapRemoteBffApiEndpoint("/auth", "https://localhost:5001") // 5001 is IdentityServer project
        .RequireAccessToken();

    endpoints.MapRemoteBffApiEndpoint("/remote", "https://localhost:5002") // 5002 is Api project
        .RequireAccessToken();

    endpoints.MapFallbackToFile("/index.html");
});
```

Here is my problem. I am trying to call two identical endpoints, one is in Api and the second in IdentityServer. They don't have `[Authorize]` attribute yet, I am just trying to check user claims:
```cs
[Route("identity-server")]
public class AuthController : ControllerBase
{
    [HttpGet]
    public IActionResult TetsMethod()
    {
        return new JsonResult(new
        {
            message = "This is IdentityServer project.",
            isAuthenticated = User.IsAuthenticated(),
            claims = User.Claims.Select(e => new { e.Type, e.Value })
        });
    }
}
```
Here I get different results for those endpoints

![isauth](https://user-images.githubusercontent.com/17731173/187070554-f5f6225b-c512-4819-a827-4cd6e0ccd4ca.gif)

Api project is configured exactly as in Quickstart, it only uses `.AddAuthentication()`:
```cs
builder.Services.AddAuthentication("Bearer")
    .AddJwtBearer("Bearer", opt =>
    {
        opt.Authority = "https://localhost:5001";

        opt.TokenValidationParameters = new()
        {
            ValidateAudience = false
        };
    });
```

Which works great (as shown). I tried to copy this code to IdentityServer project (right after `.AddIdentityServer()` call), however it doesn't help. User is not authenticated. Is there something obvious that I misconfigured or forgot to add?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
