### ISSUE TITLE
Can you customize the name of the endpoints and the discovery document?

### ISSUE THREAD

**Issue by tibiiorcdw** [DuendeSoftware/Support#18]
I have a use case where I would like to mirror the endpoints with another IDP vendor. Is there a way to customize the endpoint URIs and also to match the generated discovery document to match it?

**Comment by brockallen** [comment]
Sorry, this question was missed somehow. 

I don't think we expose any options to change those. @leastprivilege -- any thoughts on this?

**Comment by leastprivilege** [comment]
No we don't.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
