### ISSUE TITLE
[Question]When implementing a custom scope parser, ClientID is unavailable

### ISSUE THREAD

**Issue by bcbeatty** [DuendeSoftware/Support#180]
I'm currently working on an implementation of custom Scope Parser. I'm interested if there is an existing way to get the current requests clientId and the allowed scopes in that method?

Use Case: if a user app sends patient/*.read scope. Instead of returning patient/*.read I want to return what * represents as individual claims on the consent confirmation

instead of 
![image](https://user-images.githubusercontent.com/1178347/186775094-0b69a815-eba5-4a78-b44c-c0a2d889edca.png)

I want to do this
![image](https://user-images.githubusercontent.com/1178347/186775216-3640e7b2-da03-4bb4-bf3e-9c07bede1e4f.png)

**Comment by brockallen** [comment]
> Use Case: if a user app sends patient/.read scope. Instead of returning patient/.read I want to return what * represents as individual claims on the consent confirmation

You can get the client id and the requested scopes on the consent page when using the [IIdentityServerInteractionService](https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/) -- the GetAuthorizationContextAsync API will return that info so you can build the UI the way you need/wan to.

HTH

**Comment by ognjen1992** [comment]
Yes, that's okay when we are working with controllers. Still, in this case, we are implementing custom IScopeParser to add some corresponding scopes if the wildcard scope is present in the requested ones, so we would need to get clientID in IScopedParser's method ParseScopeValues to get all allowed API scopes for current clientID.

**Comment by brockallen** [comment]
I see. Currently that's not possible and I'm not sure the scope parser is the right place anyway (it's not designed to do client-specific logic). But you can add custom validation logic (where all that info is available) in either the authorize request validator, and/or the token request validator. 

https://docs.duendesoftware.com/identityserver/v6/reference/validators/

**Comment by brockallen** [comment]
We updated the docs for validators a bit since yesterday, FYI -- mainly just added that the authorize request validator exists. HTH, thanks.
