### ISSUE TITLE
SlidingRefreshTokenLifeTime  not beeing respected

### ISSUE THREAD

**Issue by olivier-voutat** [DuendeSoftware/Support#182]
**Which version of Duende IdentityServer are you using?**
Version 6.0.4

**Which version of .NET are you using?**
dotnet core 6.0

**Describe the bug**
SlidingRefreshTokenLifeTime not beeing respected. IDP continues to issue new tokens even after SlidingRefreshTokenLifeTime is reached.

**To Reproduce**
Created session from IDP and redirected to web application (React App).
Waited the SlidingRefreshTokenLifeTime to be reached (in our case 30 minutes).
Try to refresh the client web application.
Still logged in and can see that a new token was issued (stored in local storage).

**Expected behavior**
To be redirected to IDP because no valid access token.

**Additional context**

Our configuration for the client web application:

AccessTokenLifetime = 60 * 10, // 10 mins 
AllowPlainTextPkce = false, 
AllowOfflineAccess = true, // for refresh tokens 
AllowAccessTokensViaBrowser = false, 
EnableLocalLogin = true, 
AuthorizationCodeLifetime = 60 * 5, // 5 mins 
AbsoluteRefreshTokenLifetime = 60 * 60 * 4, // 4 hours, Max session time 
SlidingRefreshTokenLifetime = 60 * 30, // 30 mins, Max idle time 
RefreshTokenUsage = TokenUsage.OneTimeOnly,
RefreshTokenExpiration = TokenExpiration.Sliding, 
UpdateAccessTokenClaimsOnRefresh = false,
AccessTokenType = AccessTokenType.Jwt,
IncludeJwtId = false,
AlwaysSendClientClaims = true,
AlwaysIncludeUserClaimsInIdToken = false, 
RequireConsent = false, 
RequirePkce = true, // Enable PKCE (authorization code flow only) 
RequireClientSecret = false

**Comment by brockallen** [comment]
What flow are you using and what client side library do you use in the react app for the protocol (oidc-client or BFF)?

**Comment by olivier-voutat** [comment]
npm package "oidc-client": "^1.11.5"

don't get what you mean by "What flow". When we access the client web app, it checks if there is a valid token. If not, it redirects to the IDP for authentication, which redirects to the client web app.

cheers

**Comment by brockallen** [comment]
I'm trying to determine if the client app you're building does a redirect at all back to the token server's ~/authorize endpoint (either in the top/main window, or in an iframe) and that's why you're getting an update token in the SPA. Or if the refresh token is what's really being used for renewal and if there's a flaw in the logic around the sliding expiration. We do have unit tests for that logic in IdentityServer, so we'd have to understand why those don't reproduce what you describe.

**Comment by olivier-voutat** [comment]
We have a React Web App, an IDP web site and a web api which trust the tokens issued by the IDP.

But all the "trust" configuration, must me done in IDP, no? Or should the web api be configured for the Sliding to work ?

**Comment by brockallen** [comment]
> Or should the web api be configured for the Sliding to work ?

The Web API only validates access tokens, and doesn't work with the refresh token, so that's unrelated to the refresh token sliding feature.

**Comment by olivier-voutat** [comment]
What extra information can I give you to help find the source of the problem ?

**Comment by brockallen** [comment]
I just tested it with our "ConsoleResourceOwnerFlowRefreshToken" here: https://github.com/DuendeSoftware/IdentityServer/tree/main/clients/src/ConsoleResourceOwnerFlowRefreshToken

And I changed the "roclient" settings from here: https://github.com/DuendeSoftware/IdentityServer/blob/main/hosts/Configuration/ClientsConsole.cs#L147

to be:

```
                RefreshTokenUsage = TokenUsage.OneTimeOnly,
                AbsoluteRefreshTokenLifetime = 60,
                SlidingRefreshTokenLifetime = 10,
                RefreshTokenExpiration = TokenExpiration.Sliding

```

And tested it. I saw that if I keep requesting tokens within 10 seconds, I got a new access token until 60 seconds at which point the absolute expiration prevented more tokens. And I also tested not renewing until after 10 seconds (but before 60) and it failed.

So from that, it seems to be working properly. 

As I said before, it might be that your SPA is redirecting the user back to the ~/authorize endpoint and the session cookie is allowing the SPA to obtain new access and refresh tokens. But it's hard for me to tell until unless we have more diagnostic info from debugging.

**Comment by olivier-voutat** [comment]
For the cookie we set it like this. Funny stuff is that when I look in our production environnement, the Expires / Max-Age field shows session and not a time.

    public static readonly TimeSpan SsoCookieLifetime = TimeSpan.FromHours(2);
    
    private async Task IssueIdpAuthCookie(IdentityServerUser user)
    {
        var props = new AuthenticationProperties { ExpiresUtc = DateTimeOffset.UtcNow.Add(IdentityServerConfig.SsoCookieLifetime) };
        await HttpContext.SignInAsync(user, props);
    }

**Comment by olivier-voutat** [comment]
Well, after a lot of research (and the help of an external, since the internal who knew IdentityServer left), the truth is that we have in the client a renewal every 5 minutes with a setInterval... sorry for the time lost... :(

**Comment by brockallen** [comment]
On an ancillary note, it's generally considered bad practice to use refresh tokens in SPAs:

https://blog.duendesoftware.com/posts/20210326_bff/
