### ISSUE TITLE
Append query params to RedirectUri?

### ISSUE THREAD

**Issue by bruceharrison1984** [DuendeSoftware/Support#186]
**Which version of Duende IdentityServer are you using?**
6.0.2

**Which version of .NET are you using?**
.net 6

**Describe the bug**

We are using Duende to implement the SMART on FHIR standard, and one of the requirements is the ability to pass a `launch` parameter through the authentication process, and have it echo'd back out on the end of the RedirectUri.

https://build.fhir.org/ig/HL7/smart-app-launch/app-launch.html#for-example

Basically, an additional `launch` query parameter is passed to the initial `authorize` endpoint. Normal login occurs, and if login is successful, the `launch` query parameter should be added to the resulting JWT (easy), as well as appended to the final redirect url back to the client page. Is there any guidance on this?

Most of the available interface give access to the `RedirectUri` in some fashion, but none seem to offer any way to _change_ it during an anuthorization_code request flow.

**Comment by brockallen** [comment]
Is this part of the FHIR spec? Normally something like that is managed via the `state` param to the authorize endpoint.

**Comment by bruceharrison1984** [comment]
@brockallen You are correct. After racking my brain for what seemed like forever, I realized the value is just echo'd via the external EHR mechanism, not the identity provider (Duende). So there's no reason to actually do _anything_.

As per internet meta, as soon as I post the question I figured out the solution.

Thank you for the speedy reply though, and great job on Duende.
