### ISSUE TITLE
BasicAuthenticationSecretParser performs client ID and secret length checks on the URL encoded string

### ISSUE THREAD

**Issue by alan-flare** [DuendeSoftware/Support#187]
**Which version of Duende IdentityServer are you using?**

6.1.2

**Which version of .NET are you using?**

6

**Describe the bug**

The `BasicAuthenticationSecretParser` performs client ID and secret length checks on the URL encoded string. This is inconsistent with the `PostBodySecretParser`.

We noticed this as we are using IdentityModel and have upgraded to use IdentityModel v6. There was a recent change introduced in v6 to send client credentials on the authorization header as the default - and not in the post body. https://github.com/IdentityModel/IdentityModel/pull/429.

We started seeing `Client secret exceeds maximum length.` errors when the client credentials style is set to authorization header (default). We have a workaround to use post body instead.

**To Reproduce**

1. Set values for Client secret and ID so that its URL encoded length exceeds the original length
2. Can use InputLengthRestrictions defaults or set accordingly so that URL encoded client secret and ID exceeds the restricted length
3. Using IdentityModel, perform a client credentials token request where client credentials style is set to authorization header

**Expected behavior**

Should not encounter a `Client secret exceeds maximum length.` error when Client secret and ID values are within length restrictions when client credentials style is authorization header.

**Log output/exception with stacktrace**

```
Client secret exceeds maximum length.
No client identifier found
```

**Additional context**

This also exists in https://github.com/IdentityServer/IdentityServer4

**Comment by brockallen** [comment]
Ok, I see what you're saying here (we would need to do the same thing for client_id). But I think the idea with the input length restrictions is more about checking the length on the raw value before we do any processing to it. If we were to decide it, then we're processing the value prior to checking to see if a very large value had been submitted. This is the DOS attack we're trying to prevent.

**Comment by brockallen** [comment]
Hi @alan-flare  -- anything to add here?

**Comment by alan-flare** [comment]
Hi Brock, thank you for your investigation and response 👍 

As a workaround, we'll continue with using post body credentials style and/or bump up the `InputLengthRestrictions` options on our end so that our existing clients can also have the option of using authorization header credentials style without the need to update their secrets.

Thanks again, closing my query.
