### ISSUE TITLE
Key error: IS inserting multiple keys lead to key errors after restarts

### ISSUE THREAD

**Issue by Stra1ghter** [DuendeSoftware/Support#188]
**Which version of Duende IdentityServer are you using?**
6.1.1
**Which version of .NET are you using?**
net6.0
**Describe the bug**
We have a similar bug like [the key error](https://github.com/DuendeSoftware/Support/issues/183), but I think we have setup everything correctly. Find the log outupt below.

We have DPAPI configured and store the DP key locally in the filesystem.
```
  services.AddDataProtection()
          .SetApplicationName("Auth")
          .PersistKeysToFileSystem(new DirectoryInfo(@"C:\" + AppInfo.AppName));
```

We use a central db for storing the configuration and operational store.
What I have figured out so far is that the error happens when IdentityServer is restarted, then it does not know which key is the correct one from the keys table.

It seems like we have old keys in the keys table, but the only system that has ever been connected to the db is IdentityServer.

The question from my point is: is there some way to configure IS that it does not add multiple keys that lead to errors after a restart?

After truncating the table and restarting IS, IS creates only one key and we don't receive the error anymore. I could not figure out when IS is inserting new keys. 

**To Reproduce**
1. Setup IS with DP API, a sample client and stores, add multiple keys.
2. Try to authenticate your client after a restart of IS.

**Expected behavior**
I expect the automatic key management feature to manage keys in a way that don't lead to errors.
If IS' automatic key management feature creates new keys, this mustn't lead to errors when we restart IS.

**Log output/exception with stacktrace**

```
Error unprotecting key with kid "xxx".
The key {xzy} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
CryptographicExceptionMicrosoft.AspNetCore.DataProtection   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```

**Comment by brockallen** [comment]
Now that you've cleared the table and have the one key, I'd be curious if you get new, erroneous keys in the future? If not, then it seems to be all working, and then somehow you had stale data in the keys table (I guess?). 

Also, though, storing the DP keys on the filesystem only works if you have a single node, and you're not load balancing. Are you only running a single node/instance?

> The question from my point is: is there some way to configure IS that it does not add multiple keys that lead to errors after a restart?

Hmm, we don't have that as a feature, really, since the invalid key internally is treated as if there are no keys, and part of the job of the automatic key management is to make new keys as needed (and rotate them).

**Comment by Stra1ghter** [comment]
Hi @brockallen,
I will monitor this. I really don't understand why IS created the keys in the first place. I couldn't reproduce when IS decides to create a new key. Maybe it has just been the automatic key management feature.

What happens when the automatic key management creates a new key (say 90 days in the future). Then we have two keys in the table. After a restart, we will see the same error logs again, right? How is this supposed to be handled?

From what I have seen, IS seems to try all existing keys after a restart and logs an error if any single one cannot be used to verify the signature of a given token?

We only run one node atm. We will switch to Redis / a db setup in case we need to scale out to multiple nodes in the future. I couldn't see any cookie auth errors, so I guess the DPAPI setup works.

**Comment by brockallen** [comment]
All the keys are read so that it can show them all in the discovery document. And yes, after ~75 days a new key will be created so that it will be ready on day 90, and it will be protected with the current DP key.

**Comment by Stra1ghter** [comment]
@brockallen aaaah! I think the keys were IS-generated before we had setup DP API. I didn't know that the actual key will be protected with the DP key. (My wrong impression was that the DP API is used for signing tokens / the signature check) This really helped me out. Thank you!
