### ISSUE TITLE
How to make multi session protection on a client ?

### ISSUE THREAD

**Issue by atlangaudeau** [DuendeSoftware/Support#190]
**Question**
Hello everyone !

I build a platform to allow loging/logout in my desktop applications.
So now I want to lock users at only one connection per client.
If the user login I want to logout of his last connection to prevent multi-authentification.
How can I do that? with session management?

**Which version of Duende IdentityServer are you using?**
Duende v6.1.5

**Which version of .NET are you using?**
.NET v5.0

**Comment by brockallen** [comment]
If you are using [server-side sessions](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/) then you could build that additional logic on top.

**Comment by atlangaudeau** [comment]
Yeah, but I must buy the Bussiness edition, or can I implement it in another way?

**Comment by brockallen** [comment]
You would have to implement all of that yourself.
