### ISSUE TITLE
Azure App Service integration

### ISSUE THREAD

**Issue by rofr** [DuendeSoftware/Support#197]
Azure App Service has a built in Authentication module that can integrate with an OIDC IDP.

The module will take care of sign in and will then attach validated user info and tokens as headers to the request. I really like the idea of not having to have any of regular middleware in the application itself, especially since we are running .NET Framework now and will be transitioning to .NET 6 later.

I tried a quick experiment using demo.duendesoftware.com as IDP but am getting an Error: invalid_request for request id: 0HMKCPR3PNRGQ:00000011

I pointed to the metadata endpoint and and used the interactive.confidential.short client described at https://demo.duendesoftware.com/

Here is the app in case anyone wants to see what's going on:
https://pfnadmin.azurewebsites.net

Any advice is appreciated!

**Comment by brockallen** [comment]
Not sure -- you might have to clone the repo for the demo IdentityServer and run it locally to capture the logs.

**Comment by rofr** [comment]
Turns out the Azure App Service OIDC implementation doesn't use PKCE.

**Comment by brockallen** [comment]
> Turns out the Azure App Service OIDC implementation doesn't use PKCE.

Hrumpf. And unfortunate.

**Comment by rofr** [comment]
I have a working configuration now with a frontend web app that talks to a backend api, both hosted on Azure App Service. One huge quirk was that clientid and secret are mandatory fields in the configuration UI. This is a bit odd as the backend api is just a protected resource and not really a client, it only needs to validate and extract claims from the access token. Turns out you need to supply the audience in the clientid field and any random value as the secret.
