### ISSUE TITLE
How to get session_state in the response?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#198]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0

**Describe the question**
We have to implement [OpenID Connect — Session Management](https://openid.net/specs/openid-connect-session-1_0.html#OPiframe) which requires a session_state parameter. So, how can we get the session_state parameter in the token response?

Do we need to change any client configuration?

**Comment by brockallen** [comment]
The spec you linked says where it's available to your client app:

```
7.1.1.  Registry Contents

    Parameter name: session_state
    Parameter usage location: Authorization Response, Access Token Response
    Change controller: OpenID Foundation Artifact Binding Working Group - openid-specs-ab@lists.openid.net
    Specification document(s): [Section 2](https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions) of this document
    Related information: None
```

**Comment by PratikPatel-Mtech** [comment]
Thanks, @brockallen. It is really helpful. We can get session_state on the /callback page in the query string.
