### ISSUE TITLE
Device Flow doesn't support PKCE

### ISSUE THREAD

**Issue by lemonlion** [DuendeSoftware/Support#200]
**Which version of Duende IdentityServer are you using?**
IdentityModel 6.0.0

**Which version of .NET are you using?**
.Net 6

**Describe the bug**

I was under the impression that flows other than the Client Credentials flow should always use _both_ client secret and PKCE, including  for Device Flow.  See for example [this implementation of Device Flow](https://developers.navigraph.com/docs/authentication/device-authorization) which appears to be using client_secret, code_challenge and code_challenge_method in the device authorisation request and code_verifier in the token request.

In IdentityServer, the DeviceAuthorizationRequest object doesn't appear to take code_challenge & code_challenge_method as first class parameters (eg there is no property on the DeviceAuthorizationRequest  called 'CodeChallenge').  Likewise DeviceTokenRequest doesn't take code_verifier as a first class parameter.  Furthermore when the values are introduced as part of the Parameters collection, they appear to be ignored (i.e., even when supplied with an incorrect code_verifier in the second call, the token response is successful, even though my Authorisation Server has 'RequirePkce' set to true for the "tvDevice" client).

**To Reproduce**

1) Make device authorisation request with PKCE values in the Parameters.
```
var startAuthorisationResponse = await client.RequestDeviceAuthorizationAsync(new DeviceAuthorizationRequest
            {
                Address = disco.DeviceAuthorizationEndpoint,
                ClientId = "tvDevice",
                ClientSecret = "secret",
                Parameters = new Parameters
                {
                    { OidcConstants.AuthorizeRequest.CodeChallenge, codeChallenge },
                    { OidcConstants.AuthorizeRequest.CodeChallengeMethod, OidcConstants.CodeChallengeMethods.Sha256 }
                }
            })
```
2) Login on external device
3) Make device device token request with incorrect code_verifier in the Parameters
```
var tokenResponse = await client.RequestDeviceTokenAsync(new DeviceTokenRequest
        {
            Address = disco.TokenEndpoint,
            ClientId = "tvDevice",
            ClientSecret = "secret",
            DeviceCode = myDeviceCode,
            Parameters = new Parameters()
            {
                new(OidcConstants.TokenRequest.CodeVerifier,  "incorrectCodeVerifier")
            }
        });
```
**Expected behavior**

A) Failure of the above token response (as the supplied code_verifier was incorrect)
B) The ability to put PKCE values directly into the request as strongly typed properties, rather than having to use the Parameters collection with constants.

**Comment by brockallen** [comment]
PKCE is about protecting the authorization code from interception by an attacker when it's being returned to the client from the OAuth authorization endpoint via the browser. The name of the RFC is "proof key for [authorization] code exchange".

In the device flow there is no authorization code returned to the client in the browser, thus nothing to intercept, thus no attack to thwart. I'm not sure why that example uses it -- perhaps you could ask them?

Also, I've not seen any OAuth RFC (such as the "best practices" spec) that suggest it should be used in device flow. Have you found any such recommendations?

Finally, the device flow spec was published 4 years after the PKCE spec, so if it was intended to be used with device flow I think they would have included it in their RFC.

**Comment by lemonlion** [comment]
Ok great - thanks for the clarification! :)
