### ISSUE TITLE
Is there any way to revalidates the user on Authorize request for logged in user?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#204]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
v6.0

**Describe the question**
Normally, in the Identity Provider, if a user is already logged in with one client and tries to log in with the other client in the same browser, then it won't ask for credentials and completes the OAuth 2.0 code flow and generates the new token.

There are some scenarios where the user should be re-validated based on some conditions per client(it may require additional database calls). And prevent token generation for that client if it does not meet the criteria.

The one option I could think of is the login=propt argument, but then it will always ask for the credentials and someone may temper the URL and generate the token. 

So, is there any feature or workaround available to re-authenticate or authorize the user?

**Comment by brockallen** [comment]
Yep, have a look at  the `IAuthorizeInteractionResponseGenerator` -- you'd derive from our `AuthorizeInteractionResponseGenerator` base and override one of the appropriate virtuals.
