### ISSUE TITLE
Reference token revocation

### ISSUE THREAD

**Issue by TheDusty01** [DuendeSoftware/Support#205]
**Which version of Duende IdentityServer are you using?**
5.2.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
According to https://docs.duendesoftware.com/identityserver/v5/data/operational/grants/:
> The presence of the record in the store without a ConsumedTime and while still within the Expiration represents the validity of the grant. Setting either of these two values, or removing the record from the store effectively revokes the grant.

However setting those values of a record or even removing the record via the ``IPersistedGrantService`` or ``IPersistedGrantStore`` doesn't revoke the grant.

If the client tries to access the page again it just creates a new grant instead of logging the user out.

**To Reproduce**
Setup:
1. Create a new Blazor WASM ASP.NET Core hosted app with individual user accounts
2. Remove the JWT stuff
3. Add the following:
```cs
builder.Services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
    {
        foreach (var client in options.Clients)
        {
            client.AccessTokenType = AccessTokenType.Reference;
        }
    });

builder.Services.AddAuthentication()
    .AddOAuth2Introspection(options =>
    {
        options.ClientId = "YourClientId";
    });
```
Test:
1. Start the project and login
2. Remove the grant either programmatically or by hand
3. Refresh the page in the browser

**Expected behavior**
The client should get logged out.

**Additional context**
Not sure if this is expected behavior but the docs clearly say the opposite and I can't manage to find a way to log the user out.

**Comment by brockallen** [comment]
That's likely because the client also have a refresh token. You don't have to issue the client a refresh token, but if you do and you don't want to to get new access tokens you'd need to revoke it as well.

**Comment by TheDusty01** [comment]
```cs
builder.Services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
    {
        foreach (var client in options.Clients)
        {
            client.AccessTokenType = AccessTokenType.Reference;
            client.AllowOfflineAccess = false;     // Should disable refresh tokens?
        }
    });

builder.Services.AddAuthentication()
    .AddOAuth2Introspection(options =>
    {
        options.ClientId = "TheClientId";
        options.SaveToken = true;    // Setting this to false will result in the reference token not getting stored in the DB
    });
    ```
    
So I have that, what would I need to add to disable refresh tokens?
And wouldn't refresh tokens be stored in the DB as a persisted grant since I only have the reference token stored.

**Comment by brockallen** [comment]
The `AllowOfflineAccess` is what controls access to refresh tokens (requested via the `offline_access` scope as defined in the OIDC spec).

>  And wouldn't refresh tokens be stored in the DB as a persisted grant since I only have the reference token stored.

And correct -- then you should not see refresh tokens in the grant store, just reference tokens.

**Comment by TheDusty01** [comment]
I just debugged through the code and found out that when I refresh the site it requests a new reference token via an authorization code.
Do you have any idea why or rather how I could disable this behavior and successfully revoke tokens?

That's the value of the oidc session key (``oidc.user:https://localhost:7199:TheClientId``), not sure if this helps:
```json
{
    "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MTk5IiwibmJmIjoxNjYzMDEzNTE1LCJpYXQiOjE2NjMwMTM1MTUsImV4cCI6MTY2MzAxMzgxNSwiYXVkIjoiRHVzdHlTb2x1dGlvbnMuUnVzdC5SZW1vdGVBZG1pbi5DbGllbnQiLCJhbXIiOlsicHdkIl0sImF0X2hhc2giOiJTUklIVldXNlR3QlNrUll1aWtlV053Iiwic2lkIjoiRkIxQ0NEOEIwNjI1MTU2RkFDODg3NTMxMTFENTM1MzQiLCJzdWIiOiI2OWI5OWIyYS01Y2RkLTQ5MzYtOTFiMC0xZmVmYWFlNDVjNzkiLCJhdXRoX3RpbWUiOjE2NjMwMTM1MTMsImlkcCI6ImxvY2FsIn0.H4GUpyFVacad02mBGeqS9lms3ulh8unpBLMHfvRylfxcZ2I5lv7fNAyljFbBmoOCp0tQvsYIaEGupRSLN2nDevChVbVvKI43m2Et7c-YoXYaYDPN-Y7I0UC0d1PpDM0k4yyxP74m8mIZqseKYwoOzqWV1BWPxPARkDaat8ggydtTjPdREtQfxuRWA_B_aEXuhBE6era9t4_HDi9pPir08PbLgn1OZRMB9557TREtGisi-JFupsUOJWXeSx8J1lKebWk96fzlnUeoS-RbQ6jFs47dxwJV1Vaiihg9EORLGBQRjPK1FKIn0zt1_yfMTN_NNvagqU_0BxJV1uLISrSyVg",
    "session_state": "ojbJWdFsoz3upjiRDh6m3DdFFF30pNhzopQKmgDceU8.843556E4C18A4D8F0151BDD2DF5A6126",
    "access_token": "22962E2BC1BAD977FD470F21D458CC5C59D2BC5CC6DBCE61B673768CED04ABF7",
    "token_type": "Bearer",
    "scope": "openid profile",
    "profile": {
        "amr": [
            "pwd"
        ],
        "sid": "FB1CCD8B0625156FAC88753111D53534",
        "sub": "69b99b2a-5cdd-4936-91b0-1fefaae45c79",
        "auth_time": 1663013513,
        "idp": "local",
        "preferred_username": "Admin1@admin.com",
        "name": "Admin1@admin.com"
    },
    "expires_at": 1663017115
}
```

**Comment by brockallen** [comment]
> I just debugged through the code and found out that when I refresh the site it requests a new reference token via an authorization code.

Sure, and that's allowed because the user's browser has an authentication cookie for IdentityServer (which is how SSO works).

I feel like you're getting lost in the weeds on how to do something, but maybe it's better to understand what you want to do -- what's the real requirement?

**Comment by TheDusty01** [comment]
Thanks for the help and explanation so far.

The SSO thing makes kind of sense to me (not an auth expert at all) but does it not destroy the purpose of the reference tokens? Couldn't you use JWTs instead then?

My users should have access to the app for a limited amount of time but this time frame is not known at the time of registering and or logging in. It also varies on a per user basis.
So JWTs won't work here as I'd need to modify the expiration date issueing.
So I basically need a way to logout my Blazor WASM client from the server by "revoking the grant" I guess.

I always used IdentityServer as it so easy to use and thought this would be quite simple or am I missing smth?

**Comment by brockallen** [comment]
> The SSO thing makes kind of sense to me (not an auth expert at all) but does it not destroy the purpose of the reference tokens? Couldn't you use JWTs instead then?

This all just depends on the use cases you have and what your requirements and threat model are. For example, you could use reference tokens fro a mobile client and that might be the right tool for that scenario, but normal JWTs for your web app.

> My users should have access to the app for a limited amount of time but this time frame is not known at the time of registering and or logging in. It also varies on a per user basis.

There might be many ways to do this, not just by expiring the access token. It could be logic in the client app, could be in your API, it could be using our [centralized session management](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/), or another idea could be in `IsActive` on the [profile service](https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/). It also might need to be some combination of those, as well. But you'd have to design it that also works with SSO and the user's session cookie. 

So you will have to design this all with all of these building blocks.

**Comment by TheDusty01** [comment]
Got it, thanks for the help.

> This all just depends on the use cases you have and what your requirements and threat model are. For example, you could use reference tokens fro a mobile client and that might be the right tool for that scenario, but normal JWTs for your web app.
Just for my clarification if you don't mind explaining:
If you have both a mobile and a web app and one of them uses JWTs and the other one reference tokens what would be the advantage of reference tokens if you can't effectively revoke them? I don't understand the purpose

**Comment by brockallen** [comment]
> Just for my clarification if you don't mind explaining:
> If you have both a mobile and a web app and one of them uses JWTs and the other one reference tokens what would be the advantage of reference tokens if you can't effectively revoke them? I don't understand the purpose

Well, those are 2 different clients each with different threat models based on the nature of the app. So, you might want to have different configuration for each of them (e.g. access token type). And for the mobile, you can revoke the reference access token in the scenario where the mobile is lost/stolen.

**Comment by TheDusty01** [comment]
> Well, those are 2 different clients each with different threat models based on the nature of the app. So, you might want to have different configuration for each of them (e.g. access token type). And for the mobile, you can revoke the reference access token in the scenario where the mobile is lost/stolen.

Well but you have seen my configuration, deleting/modifying the expiration date does nothing and as you saw I didn't use have refresh tokens enabled 😅

Anyways another topic if you don't mind.
Are there any examples on how to use IdentityServer as a centralized authentication provider, similiar to auth0?

**So I'd have 4 projects** (in reality there're also Domain, Infrastructre etc. projects but for the sake of this example I wanna keep it simple):
- MyProject.BlazorClient
- MyProject.HostApi
- MyProject.Shared (would contain Models, DBContext etc.)
- MyProject.Authentication.Api (should basically act like auth0 and manage authentication)

**Use case:**
I would like to have a centralized authentication API like ``accounts.myproject.tld`` which could be used for other services on that domain like ``service1.myproject.tld`` and ``service2.myproject.tld`` without the need of 2 separate authentication providers. So like I said, basically a "self hosted auth0".

**Questions:**
1. Are there any examples/tutorials/references of this available?
2. How can I secure my HostApi with the authentication server?
3. How can I implement authentication with this pattern in blazor?
Do I need to configure the Blazor WASM app to use one API for authentication and another one for data retrieval? If so, how?

I'd be more than happy to buy a license for IdentityServer if that's something easy to accomplish with it

**Comment by brockallen** [comment]
>  Are there any examples on how to use IdentityServer as a centralized authentication provider

That's the whole purpose of it. Just by virtue of using it, and designing the client apps to trust it you are doing SSO with a centralized OIDC provider. As for the actual identity management library you use, that's up to you and by design an extensibility point: 

https://blog.duendesoftware.com/posts/20210520_custom_ui/
https://docs.duendesoftware.com/identityserver/v6/ui/

Many people do choose ASP.NET Identity. So if you want an API on that, then you'd build it yourself.

**Comment by brockallen** [comment]
> I'd be more than happy to buy a license for IdentityServer if that's something easy to accomplish with it

Feel free to contact us for more questions: https://duendesoftware.com/contact

**Comment by TheDusty01** [comment]
Thanks a lot again, you really helped me out!
