### ISSUE TITLE
What are the possible values for the token_type filed in the token response?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#206]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
v6.0

**Describe the question**

I could see `Bearer` in the response.  What are the possible values for the token_tyoe filed in the token response? Would it be possible to remove the token_type field from the response?

**Comment by leastprivilege** [comment]
No - it is part of the spec.

**Comment by PratikPatel-Mtech** [comment]
@leastprivilege Thanks. What are the possible values for the token_type filed in the token response?

**Comment by leastprivilege** [comment]
depends on the token type. Bearer is practically speaking the only one right now.
