### ISSUE TITLE
Why does the client.UpdateAccessTokenClaimsOnRefresh default to false?

### ISSUE THREAD

**Issue by PureKrome** [DuendeSoftware/Support#208]
**Which version of Duende IdentityServer are you using?**
5.2.3

**Which version of .NET are you using?**
NET3.1

**Describe the ~bug~ question**

Why does the `client.UpdateAccessTokenClaimsOnRefresh` default to `false` ?

Context: We just noticed that when we generated a new idToken and accessToken using a refreshToken, they were all generated but a claim (which should -not- have been there) was found to exist in the accessToken. The idToken was ok (the claim was not there, which is correct).

So after stepping through the Duende code (gotta love it when the pdb symbols work! :chef-kiss:) I finally found the setting, which was false.

Then I found the docs about it here: https://docs.duendesoftware.com/identityserver/v5/reference/models/client/#refresh-token

And finally, the comment in the code:

![image](https://user-images.githubusercontent.com/899878/189904662-36ce11e3-adb4-4489-b9b7-b507dd2121c2.png)

More Context: We have some custom claims we manually add to the token(s) via override the `CreateAccessTokenAsync` and `CreateIdentityTokenAsync` methods on an inheritted `DefaultTokenService` class.

Thank you kindly.

**Comment by leastprivilege** [comment]
For most cases a refreshed token is an exact copy of the original token just with a new lifetime. This is the cheapest way to get a refresh token.

If you need updated claims (which will be more expensive) - turn this feature on.

**Comment by PureKrome** [comment]
> This is the cheapest way to get a refresh token.

Thanks @leastprivilege - so it's `false` by default because it's a performance reason/decision. Great! Was scared there was some unique, edge case reason or something else.

Cheers! Closing this now :) Thanks for the prompt reply - really appreciated it. 👏🏻
