### ISSUE TITLE
increase performance

### ISSUE THREAD

**Issue by A-Yavari** [DuendeSoftware/Support#209]
Do you think cache level 2 can increase our performance in pkce flow? What would you suggest to increase performance, I mean only for user information when we use aspidentity?

**We use Last version of Duende.identityserver with .net6**

**Comment by A-Yavari** [comment]
> This is highly dependent on your protocol flows and use cases. What specific aspects have you measured and found to be too slow?

I mean second level cache that locates between orm and identity server and our queries get cached by it
**
https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor **

In this case The application locates between ORM and Identity server and we can cache data by redis

When I use your test users that you don't suggest them on production get a very good throughout (using Jmeter and k6 testing tools) but once I connect it to aspIdentity the throughput get decreased drastically.

**Comment by brockallen** [comment]
> I mean second level cache that locates between orm and identity server and our queries get cached by it

We have support for caching data in IdentityServer: https://docs.duendesoftware.com/identityserver/v6/data/configuration/#caching-configuration-data

> When I use your test users that you don't suggest them on production get a very good throughout (using Jmeter and k6 testing tools) but once I connect it to aspIdentity the throughput get decreased drastically.

That's ASP.NET Identity, so I can't help you with that. You'd have to investigate what's slow about it and possibly ask Microsoft for help there.

**Comment by A-Yavari** [comment]
> > I mean second level cache that locates between orm and identity server and our queries get cached by it
> 
> 
> 
> We have support for caching data in IdentityServer: https://docs.duendesoftware.com/identityserver/v6/data/configuration/#caching-configuration-data
> 
> 
> 
> > When I use your test users that you don't suggest them on production get a very good throughout (using Jmeter and k6 testing tools) but once I connect it to aspIdentity the throughput get decreased drastically.
> 
> 
> 
> That's ASP.NET Identity, so I can't help you with that. You'd have to investigate what's slow about it and possibly ask Microsoft for help there.

If I read the data from the database with ado.net and give it to your testuser, what problem will I face later?

**Comment by brockallen** [comment]
TestUser is just a in-memory object model to simulate users, but it's not a substitute for a real identity management system. And by design, this is an extensibility point for IdentityServer: 

https://blog.duendesoftware.com/posts/20210520_custom_ui/

https://docs.duendesoftware.com/identityserver/v6/ui/

**Comment by A-Yavari** [comment]
Thank you a lot for your kind and helpful advice, I really appreciate that because you helped me a lot and wish you the best
