### ISSUE TITLE
IdentityServer 5 ICorsPolicyService implementaon(IsOriginAllowedAsync) not being called while executing a client request

### ISSUE THREAD

**Issue by asteradi** [DuendeSoftware/Support#21]
**Which version of Duende IdentityServer are you using?**
  Duende.IdentityServer 5.2.3
  
**Which version of .NET are you using?**
  .Net 6

**Describe the bug**

We have implemented the OAUTH Auth code flow using the Duende.IdentityServer framework. We have given are custom implemention for IClientStore, IResourceStore and ICorsPolicyService. Everything is working as expected except, the IsOriginAllowedAsync method of the ICorsPolicyService implementation is never getting called. We have registered it in DI and IdentityService registration section

**To Reproduce**
 
 -Create a new IdentityServer implementation using .Net6
  -Create custom implementation for  IClientStore, IResourceStore and ICorsPolicyService and register it with identity server.
  -Create a basic user login flow implementation.
  -Create the configuration data like client, apiResource, scope, User etc.
  -Execute the Authorisation code flow using the registered client and add a debugger in IsOriginAllowedAsync in 
   ICorsPolicyService implementation

**Expected behavior**
  
- IsOriginAllowedAsync is called and validated the client cors origin against our custom logic.

**Log output/exception with stacktrace**
  NA

**Additional context**
  NA

**Comment by leastprivilege** [comment]
CORS is a mechanism that is only revelant if you call IdentityServer endpoints from the Browser, specifically JavaScript AJAX calls.

Otherwise it is not being used.

**Comment by asteradi** [comment]
I am calling it from an MVC application view, it should be relevant in this, right?

**Comment by leastprivilege** [comment]
Do you do your call in JavaScript? Or are you using the ASP.NET authentication handler?

**Comment by asteradi** [comment]
Not using Javascript, We are using ASP.NET authentication handler.

**Comment by leastprivilege** [comment]
OK - then CORS is not in the picture at all.
