### ISSUE TITLE
Non String Claim

### ISSUE THREAD

**Issue by btwyford** [DuendeSoftware/Support#210]
Is it possible to allow non string claim values? I would like to be able to support integers and JSON objects.

**Comment by leastprivilege** [comment]
Yes. You have to set the claim value type when constructing the claim.

e.g.

`ClaimValueTypes.Integer`
or
`ClaimValueTypes.Json`

**Comment by btwyford** [comment]
Thanks for your fast reply. Can you provide some guidance on how the claimvaluetype can be set inside your framework.

**Comment by leastprivilege** [comment]
Well - whenever you want to emit a claim, you need to create an object of type `Claim` - this is were you use this parameter. Most common at signin time - or in the profile service.

https://docs.duendesoftware.com/identityserver/v6/ui/login/session/
https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/

**Comment by btwyford** [comment]
I created a custom profile service and everything works! thanks for your help.
