### ISSUE TITLE
identity server omits path based routing from discovery document when using AGIC and AKS 

### ISSUE THREAD

**Issue by theCorb1nator** [DuendeSoftware/Support#215]
**Which version of Duende IdentityServer are you using?**
6.0.4

**Which version of .NET are you using?**
6.0

**Describe the bug**
Using azure application gateway ingress controller (AGIC) with path based routing to map 

`https://myservice.mydomain.co.uk/auth/.well-known/openid-configuration`  to `{podIp}/.well-known/openid-configuration`

the forwarding works as expected and i can access the discovery document. the issue is the urls all omit the `/auth` so any service reading the discovery document fails to auth as the urls are all incorrect 

I have inserted code to enabled header forwarding in the application 

```
var forwardOptions = new ForwardedHeadersOptions
{
   ForwardedHeaders = ForwardedHeaders.All
};

forwardOptions.KnownNetworks.Clear();
forwardOptions.KnownProxies.Clear();
```

but this does not work, it only forwards the protocol of https

I have spoken with microsoft who have shared the AGIC access logs and it looks as if the header being forwarded to IDServer is the requestUri and not originalRequestUri (see below) 

![image](https://user-images.githubusercontent.com/10990837/190616414-eb4bab56-a4be-45df-b973-0a40d57cd185.png)

**To Reproduce**

Create a simple IDServer .net 6.0 application
Host this within an AKS cluster
Setup AGIC with path based routing from `/auth` to pod running IDServer app 
Access discovery document via URL 
See that the urls omit `/auth` 

**Expected behavior**

Urls in discovery document present with `/auth`

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
IdentityServer is just using what the current request has. So this needs to be set dynamically based on the upstream infrastructure. Normally the forwarded headers middleware does this properly. I will say I'm no expert on reverse proxies, but I think sometimes different vendors use different headers (IIRC, there's only convention and no standard). So you might need to configure something for the specific header. All this really does is set the Request.BasePath anyway, so it might be that easy to do it manually in your IdentityServer host instead.

**Comment by theCorb1nator** [comment]
Thanks for the reply @brockallen. i assumed that was the case, i have requested support from the microsoft AKS team to see if they are aware of any extra configuration required. In terms of setting this manually in the IdServer host. How is this done? 

i tried something like this 

```
app.Map("/auth", coreApp =>
            {
                coreApp.UseIdentityServer(options);
            });
```

This returned the URLs in the disco document with `/auth` but the actual public url had to be `/auth/auth` in order to access the document

**Comment by kkapratwar** [comment]
I could resolve this issue by adding `app.UsePathBase("/auth");` to `startup.cs` before `app.UseRouting();` 

The URL will look like this:
https://myservice.mydomain.co.uk/auth/auth/.well-known/openid-configuration

![image](https://user-images.githubusercontent.com/21107107/190996235-3ac57354-f6fc-459a-ab6b-c90449d3904d.png)

The `/auth` prefix is completely optional for the endpoints, even if you don't put the `/auth` the API endpoints will work as is.

Referred from this link: 
https://andrewlock.net/using-pathbase-with-dotnet-6-webapplicationbuilder/

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by theCorb1nator** [comment]
Yep happy for you to close
