### ISSUE TITLE
Blazor BFF behind reverse proxy with subpath

### ISSUE THREAD

**Issue by DomienVDH** [DuendeSoftware/Support#217]
**Which version of Duende BFF are you using?**
1.2.2

**Which version of .NET are you using?**
.net6.0

**Describe the bug**
I have a blazor wasm application using the bff. I use KeyCloak as an identityProvider. This all runs in containers in docker behind a reverse proxy (traefik). We use subpaths, the blazor wasm uses https://mainlink/blazorwasm and when logging in it should redirect to https://mainlink/auth
Everything behind the proxy uses http.

As a test when i'm running te bff not in a container and using HTTPS everything works fine, i get redirected to the identity provider, and end up with a cookie in the browser.
But when the bff running in the container uses http the redirect to Keycloak doesn't work. 

What we see in the logging which is different after the 401 bff user slide:
```
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      Request starting HTTP/1.1 GET http://localhost:8300/vpnmanagement/service-worker.js - -
      The file /service-worker.js was not modified
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[8]
      Handled. Status code: 304 File: /service-worker.js
```

Is there something i'm missing here are is this an issue in the bff code?

Any help is appreciated!

Domien

**Comment by brockallen** [comment]
To be honest, once you initiate the OIDC request to your IdP then you're just in the Microsoft OIDC handler code to the IdP. So whatever is the problem is between those two moving parts, and not really our BFF layer. To solve this, you could just build a basic ASP.NET app with OIDC to your IdP and test that (without the BFF) -- that way you can figure out those building blocks before you add more layers, if that makes sense.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by DomienVDH** [comment]
I haven't been able to figure it out yet. But i believe you if you say it is not a problem in the BFF layer. So yes, you can close this.

**Comment by brockallen** [comment]
I'd suggest just creating a simple app without the BFF that just does the OIDC workflow and set that up in your container and get that working. Given that this initial aspect isn't working, all the other moving parts you likely have in there is noise from you figuring out what's not working.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by DomienVDH** [comment]
Yes, you can close.
