### ISSUE TITLE
How do Secure Blazor Server-Side With Identity Server

### ISSUE THREAD

**Issue by imprathamesh** [DuendeSoftware/Support#218]
How do I secure blazor Server-Side with IS4 ?
I already project of is4, so now I just to make it secure with is4. When I click on login it should be redirect to IS4 project to authenticate me. both project have different url. So It return with access token and other scope too .

**Comment by brockallen** [comment]
Sorry, this support forum is for Duende IdentityServer. IdentityServer4 is essentially out of support.

Having said that, the answer is just like any other server-side client (e.g. like any other ASP.NET app).
