### ISSUE TITLE
Column 'UserCode' in table 'DeviceCodes' is of a type that is invalid for use as a key column in an index. 

### ISSUE THREAD

**Issue by sckid1108** [DuendeSoftware/Support#22]
**Which version of Duende IdentityServer are you using?**
Identity Server 6

**Which version of .NET are you using?**
6.0

**Describe the bug**
Column 'UserCode' in table 'DeviceCodes' is of a type that is invalid for use as a key column in an index. 
When trying to SEED an SQL Server database.

**To Reproduce**
Create IdentityServer from template
Change SQLLite connector to SQLServer (point at your local machine db)
Run using /seed
Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
I just tried (I'm on Windows), but could not repo. 

```
C:\demos\test>dotnet new isef
The template "Duende IdentityServer with Entity Framework Stores" was created successfully.

Processing post-creation actions...
Template is configured to run the following action:
Actual command: dotnet run /seed
Do you want to run this action [Y(yes)|N(no)]?
y
Running command 'dotnet run /seed'...
Command succeeded.


C:\demos\test>
```

Can you provide more details?

**Comment by sckid1108** [comment]
I think i did not run dotnet run with '/seed'

if you do not update the generated SQL for the migrations you get the error
i described.


Michael Margolese
Principal Engineer
Tenuvah Designs
http://www.tenuvahdesigns.com
Phone: (424) 288-9585

**Comment by brockallen** [comment]
Ah, I see now. Yes, you're right I didn't use /seed, but then I didn't notice you changed to SqlServer. The issue, I think, is that the migrations that ship are for Sqlite only. You'd need to re-build the DB with new migrations, as those are provider specific.
