### ISSUE TITLE
Generate an access token for WebApi with only necessary user claims

### ISSUE THREAD

**Issue by Indeedornot** [DuendeSoftware/Support#220]
**Which version of Duende IdentityServer are you using?**
6.1.5

**Which version of .NET are you using?**
.net 6

I have an identity server 4 setup, mvc client and web api. 

I am trying to generate an access token for api calls from mvc client with less information. So for example instead of sending an access token with all claims, i would only send an access token with role claim (including api scope of course)

I have tried to use ClientCredentials grant, however failed due to it acting on behalf of the client and its inability to pass claims.
I have looked into tokenexchange, backchannel token and resource password owner grant, which I do not believe would be the right fit.
I have searched and found that Im left only with Authorization Code flow left.

How should I continue in such case? 

Should I reuse the code from original authentication of my mvc client? If so how should i go about accessing it to make a request for a new token?
Should i ask for another authorization?

Or maybe there's another way to do that? Maybe something like removing unnecessary claims from an access token?

**Comment by brockallen** [comment]
The specs are centered around scopes as the mechanism to express what resources and claims are being requested, we model those with our resources object models:

https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/

So to help you down this path, is the client app interactive or not (IOW, is there a human using it), and then where do you care about the claims -- in the UI or in the API? This will help us model your scenario.

**Comment by Indeedornot** [comment]
> The specs are centered around scopes as the mechanism to express what resources and claims are being requested, we model those with our resources object models:
> 
> https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/

I have read the docs and have had a "roles" identity resource setup

> So to help you down this path, is the client app interactive or not (IOW, is there a human using it), are the claims (e.g. roles) the client app's claims or the user's, and then where do you care about the claims -- in the UI or in the API? This will help us model your scenario.

Interactive MVC Authorization Code client.

User claims like roles, username, but without passing unnecessary information like for example email.

In webapi 

Which email is necessary for my MVC client for certain displays, it is not needed by web API and would not like to pass it around.

As a side note:

I am currently tinkering around with IdentityServerTools and trying to use this however I do not have an idea whether this is right approach since there doesn't seem to be dedicated endpoint and my MVC client is unable to use it since it requires IKeyStorage, added in AddIdentityServer(), so its usage would require me to create my own endpoint on the ID server.

**Comment by brockallen** [comment]
> I have read the docs and have had a "roles" identity resource setup

Identity Resource is when you want the claim for the front-end client app. If you really want the claim in the API, then you'd want to add that user claim to the ApiScope.

> User claims like roles, username, but without passing unnecessary information like for example email.

You only get the extra claim you ask for in the identity and/or API scope. For example, `profile` is a predefined identity resource to request many common claims. If you don't want those, then don't request it or allow the client to request it.

**Comment by Indeedornot** [comment]
> > I have read the docs and have had a "roles" identity resource setup
> 
> Identity Resource is when you want the claim for the front-end client app. If you really want the claim in the API, then you'd want to add that user claim to the ApiScope.

I might have not explained it clear enough - I did have it already set up both in Api scope and as Identity Resource
-Identity Resource for my MVC client to recieve it as a claim
-WebApi to also recieve it

```cs
  public static readonly ApiScope ApiScope = new() {
    Name = "APIScope",
    DisplayName = "API Scope",
    Description = "Scope used to access the API",
    UserClaims = {JwtClaimTypes.Role}
  };````

```cs
  public static IEnumerable<IdentityResource> IdentityResources =>
    new IdentityResource[] {
      new IdentityResources.OpenId(),
      new IdentityResources.Profile(),
      Scopes.Roles
    };

  public static IEnumerable<ApiScope> ApiScopes =>
    new[] {Scopes.ApiScope};
```

> > User claims like roles, username, but without passing unnecessary information like for example email.
> 
> You only get the extra claim you ask for in the identity and/or API scope. For example, `profile` is a predefined identity resource to request many common claims. If you don't want those, then don't request it or allow the client to request it.

Yes, however as mentioned in the original message - My MVC client gets a token with a lot of information, so by reusing that access token I would also have to send all of the information that is stored on it. 
And I do not know how to generate a new access token with different scopes than the ones that were used to authenticate the MVC client (Other than ClientCredentials which would not include claims due to it being Machine-Machine)

**Comment by brockallen** [comment]
> Yes, however as mentioned in the original message - My MVC client gets a token with a lot of information which is required for the MVC client, so by reusing that access token I would also have to send all of the information that is stored on it - which is not necessary for WebApi.

Maybe it's easier if you show the entire token payload(s) so we can understand better?

This might be where we have confusion, but maybe you know all this already so apologies if you already do. The MVC client should be getting two tokens: an id_token and an access_token. The access_token should be the one you use to call the API (not the id_token).

**Comment by brockallen** [comment]
Hi. I can't quite tell -- are you all set on this issue?

**Comment by Indeedornot** [comment]
> Hi. I can't quite tell -- are you all set on this issue?

Nope. Earlier you have asked me to provide you with my token payload. 
> Maybe it's easier if you show the entire token payload(s) so we can understand better?

And I did in form of linking my project repository, pointing to a place where im trying to configure new token generation and sharing my configuration.

And after sharing my payload I waited for some response regarding it

**Comment by Indeedornot** [comment]
Oh, apologies.
Hopefully I understand what is to be pasted correctly

Program.cs
```cs
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

    services.AddAuthentication(
        options => {
          options.DefaultScheme = "Cookies";
          options.DefaultChallengeScheme = "oidc";
        }
      )
      .AddCookie("Cookies")
      .AddOpenIdConnect(
        "oidc",
        options => {
          options.Authority = SharedProject.IpAddresses.IdentityServer;

          options.ClientId = "MVCID";
          options.ClientSecret = "MVCSecret";
          options.ResponseType = "code";
          options.ResponseMode = "query";
          options.UsePkce = true;

          //TODO: Look into scope based authorization for certain pages
          options.Scope.Add(Scopes.ApiScope.Name);
          options.Scope.Add(IdentityServerConstants.StandardScopes.OpenId);
          options.Scope.Add(IdentityServerConstants.StandardScopes.Profile);
          options.GetClaimsFromUserInfoEndpoint = true;
          options.MapInboundClaims = true;

          options.Scope.Add(Scopes.Roles.Name);
          options.ClaimActions.MapUniqueJsonKey(JwtClaimTypes.Role, JwtClaimTypes.Role);
          options.TokenValidationParameters = new TokenValidationParameters {
            NameClaimType = JwtClaimTypes.Name,
            RoleClaimType = JwtClaimTypes.Role
          };
          //options.ClaimActions.MapUniqueJsonKey("name", "name");

          options.SignedOutRedirectUri = $"{SharedProject.IpAddresses.MVCServer}/signout-callback-oidc";

          options.SaveTokens = true;
        }
      );
```

Startup (ID4)
```cs
    builder.Services.AddDbContext<ApplicationDbContext>(options =>
      options.UseSqlite($"Data Source={dbPath};"));

    builder.Services.AddIdentity<ApplicationUser, IdentityRole>()
      .AddEntityFrameworkStores<ApplicationDbContext>()
      .AddDefaultTokenProviders();

    builder.Services
      .AddIdentityServer(options => {
        options.Events.RaiseErrorEvents = true;
        options.Events.RaiseInformationEvents = true;
        options.Events.RaiseFailureEvents = true;
        options.Events.RaiseSuccessEvents = true;

        // see https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
        options.EmitStaticAudienceClaim = true;
      })
      .AddInMemoryIdentityResources(Config.IdentityResources)
      .AddInMemoryApiScopes(Config.ApiScopes)
      .AddInMemoryClients(Config.Clients)
      .AddInMemoryApiResources(Config.ApiResources)
      .AddAspNetIdentity<ApplicationUser>()
      .AddProfileService<IdentityProfileService>();

    builder.Services.AddAuthentication();
```

Token got using `HttpContext.GetTokenAsync("access_token")` after [JWT](Jwt.Io)
```
{
  "iss": "https://localhost:5001",
  "nbf": 1663702609,
  "iat": 1663702609,
  "exp": 1663706209,
  "aud": "https://localhost:5001/resources",
  "scope": [
    "openid",
    "profile",
    "APIScope",
    "roles"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "MVCID",
  "sub": "0d5fadaa-bce6-4c4f-867c-6173908732dd",
  "auth_time": 1663702608,
  "idp": "local",
  "email": "BobSmith@email.com",
  "AspNet.Identity.SecurityStamp": "F25UFLWF676FCV3KLTVVUPJXNSUOPPLH",
  "name": "Bob Smith",
  "given_name": "Bob",
  "family_name": "Smith",
  "website": "https://bob.com",
  "location": "somewhere",
  "role": "Admin",
  "preferred_username": "bob",
  "email_verified": true,
  "sid": "3295CE7DD32F2E62C8DA12E5BF2921EE",
  "jti": "B9734FDC3BD9935EA19867286A5E516D"
}```

Wanted result to use to send to api

```
{
  "iss": "https://localhost:5001",
  "nbf": 1663702609,
  "iat": 1663702609,
  "exp": 1663706209,
  "aud": "https://localhost:5001/resources",
  "scope": [
    "openid",
    "APIScope",
    "roles"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "MVCID",
  "sub": "0d5fadaa-bce6-4c4f-867c-6173908732dd",
  "auth_time": 1663702608,
  "idp": "local",
  "email": "BobSmith@email.com",
  "AspNet.Identity.SecurityStamp": "F25UFLWF676FCV3KLTVVUPJXNSUOPPLH",
  "role": "Admin",
  "sid": "3295CE7DD32F2E62C8DA12E5BF2921EE",
  "jti": "B9734FDC3BD9935EA19867286A5E516D"
}
```
or something similiar, basically extract only the needed data into a new access token

**Comment by brockallen** [comment]
Yea, it does look like in the above access token you have a lot more claims that you've configured via the `ApiScope`. So the only thing I can imagine is that you have an `IProfileService` that's adding too many claims -- IOW, it's not respecting the requested claim types on the ProfileDataRequestContext in GetProfileDataAsync.

https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/#duendeidentityservermodelsprofiledatarequestcontext

**Comment by Indeedornot** [comment]
> Yea, it does look like in the above access token you have a lot more claims that you've configured via the `ApiScope`. So the only thing I can imagine is that you have an `IProfileService` that's adding too many claims -- IOW, it's not respecting the requested claim types on the ProfileDataRequestContext in GetProfileDataAsync.
> 
> https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/#duendeidentityservermodelsprofiledatarequestcontext

Oh, you are quite right

My previous IProfileService implementation

```cs
  public async Task GetProfileDataAsync(ProfileDataRequestContext context) {
    string sub = context.Subject.GetSubjectId();
    var user = await _userManager.FindByIdAsync(sub);
    if (user == null) throw new ArgumentException($"User with subjectId: {sub} not found");

    var principal = await _claimsFactory.CreateAsync(user);
    var claims = principal.Claims.ToList();

    context.IssuedClaims = claims;
  }
```

My current implementation
```cs
  public async Task GetProfileDataAsync(ProfileDataRequestContext context) {
    string sub = context.Subject.GetSubjectId();
    var user = await _userManager.FindByIdAsync(sub);
    if (user == null) throw new ArgumentException($"User with subjectId: {sub} not found");

    var principal = await _claimsFactory.CreateAsync(user);
    if (principal == null) throw new Exception("ClaimsFactory failed to create a principal");

    context.AddRequestedClaims(principal.Claims);
  }
```

and the token upon resetting cookies

```json
{
  "iss": "https://localhost:5001",
  "nbf": 1664203808,
  "iat": 1664203808,
  "exp": 1664207408,
  "aud": "https://localhost:5001/resources",
  "scope": [
    "openid",
    "profile",
    "APIScope",
    "roles"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "MVCID",
  "sub": "0d5fadaa-bce6-4c4f-867c-6173908732dd",
  "auth_time": 1664203807,
  "idp": "local",
  "role": "Admin",
  "sid": "0894656F243CB9A3894DEE1BF7EAADF6",
  "jti": "2793A612005AE1A2D2BA5D087B13CDA3"
}
```

As such I believe It achieves what I've wanted, although still, having scope "profile" where I don't need it seems odd.

Thank you so much for your help, you've helped me a ton. I'll leave the issue for you to close, as to hear whether you have any feedback on the current setup. As just because its working, doesn't mean it is definitely written properly.

**Comment by brockallen** [comment]
Yep, AddRequestedClaims is the trick.
