### ISSUE TITLE
Issuing access token in the Identity server and making request from it to the FHIR server to get available patients for the current user

### ISSUE THREAD

**Issue by ognjen1992** [DuendeSoftware/Support#223]
Hi,
Currently, I'm working on functionality for getting all available patients for the current user from the FHIR server and showing him a selector to pick one of the patients. How can I issue an access token for that user to myself to make a valid request from the identity server to connect to the FHIR server?

Use case:
User app (Identity server) shows a login window, after successful login user gets a table of patients available for that user (pulled from the FHIR server with request fhirapi/Patient) and picks one of those patients.

**Comment by leastprivilege** [comment]
I do not know anything about FHIR, but this

> How can I issue an access token for that user to myself

sounds like it could be solved with this:

https://docs.duendesoftware.com/identityserver/v6/tokens/internal/
