### ISSUE TITLE
User roles not available for Identity Server API middleware

### ISSUE THREAD

**Issue by zzstuzor** [DuendeSoftware/Support#225]
Hello, 

I've got some middleware to help filter out users who aren't in a certain role. For this particular case I can't depend on the standard
UseAuthorization middleware. However in my middleware when I call ClaimsPrincipal.IsInRole("x") it fails on the identity server. Meanwhile the same middleware succeeds on my other API services.

Why wouldn't the role be available for local API requests at the Identity Server? Has this got something to do with the LocalApi.PolicyName, perhaps it's not including role claims or something like that? 

Thanks in advance.

**Comment by brockallen** [comment]
IsInRole is an abstraction over the User.Claims collection. It might be easier to use that directly. Also, if you do need to use IsInRole, then there's a config setting called "RoleClaimType" that configures the behavior is IsInRole.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by zzstuzor** [comment]
Haven't had a chance to check yet. But sure we can close for now if I can
reopen it later.

Thanks for your support!

**Comment by zzstuzor** [comment]
@brockallen I tried this out but it looks like the roles are not being added to the claims. They're added when I call from a different API service, but they're simply not there when calling against the identity server API. Any idea why?

**Comment by brockallen** [comment]
Did you look at the raw access token in a tool like https://jwt.ms?

**Comment by zzstuzor** [comment]
Sorry I had it wrong, it's not for an API request - the middleware looks for a certain string in the route ('/swagger') and checks if the user is in a certain role. My auth scheme is using OIDC and a cookie. Is it possible to get the raw access token from the cookie? The same exact scenario works for other services, just not locally on the identity server. Why would the claims not be present in the cookie for the identity server but be available to other clients?

**Comment by brockallen** [comment]
If you want the claim in the client then you'd want to put it on one of the IdentityResource scopes that the client is requesting.
