### ISSUE TITLE
OpenID Connect Session Management: iframe is always returning a change state?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#226]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
v6.0.5

**Describe the question**

We have one client in build in the Next.Js and using a next-auth authentication package. We are implementing session management using [OpenID specification](https://openid.net/specs/openid-connect-session-1_0.html). 

But the iframe is always returning a `changed` state which results in the authentication loop.

Does it require any change in the identity provider or client configuration? Could you please provide a solution to this problem? 

**Expected behaviour**

The state should be `unchanged` until the user is logged in to the browser.

**Additional context**

https://openid.net/specs/openid-connect-session-1_0.html

**Comment by leastprivilege** [comment]
This is probably due to your browser not sending the authentication cookie in the hidden iframe. This mechanism is broken since more and more browsers are moving to that new model.

**Comment by leastprivilege** [comment]
see here: https://youtu.be/xzRhabmlc8M

**Comment by brockallen** [comment]
All set on this issue -- can we close?
