### ISSUE TITLE
What are the equivalents of the AddInMemory<foo> APIs for a persistent storage?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#227]
**Which version of Duende BFF are you using?**
Community

**Which version of .NET are you using?**
6.0

**Describe the bug**

What are the equivalents of the following in-memory APIs? I would use these for integration testing but need the real persistent storage if that's what it does.

            .AddInMemoryIdentityResources(Config.IdentityResources)
            .AddInMemoryApiScopes(Config.ApiScopes)
            .AddInMemoryClients(Config.Clients)

AddInMemory<foo> leads to https://docs.duendesoftware.com/identityserver/v6/quickstarts/4_ef/ which leads to https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/ which mentions:

"At this point, you no longer need the old IdentityServer project and can remove it from the solution."

That's where the confusion is. Is the following code snippet valid fo ASP.Net Core Identity with Duende Identity Server?

```
.AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = b => b.UseSqlite(connectionString,
                sql => sql.MigrationsAssembly(migrationsAssembly));
        })
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = b => b.UseSqlite(connectionString,
                sql => sql.MigrationsAssembly(migrationsAssembly));
        })
```
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
We have a whole section in the docs on this topic: https://docs.duendesoftware.com/identityserver/v6/data/

**Comment by khteh** [comment]
What's the minimum config and operational data stores to start with? I don't need any `Custom` store. Thanks.

**Comment by brockallen** [comment]
We have a quickstart that shows how that would be configured: https://docs.duendesoftware.com/identityserver/v6/quickstarts/4_ef/

**Comment by khteh** [comment]
Yes, I can see that it has `AddConfigurationStore` and `AddOperationalStore` but what you shared earlier contains more of them which includes things like caching and other stuff which only shows the APIs used with `YourCustomClient<foo>`. How to benefit from those APIs when we don't need / have any customization?

**Comment by khteh** [comment]
It is not clear to me which of the `AddInMemory<foo>` serves as cache or only used for testing purposes and if so, what are the equivalent of those in the context of persistent store without cutomization? For example:
```
AddInMemoryIdentityResources(identityResources)
.AddInMemoryApiScopes(apiScopes)
.AddInMemoryClients(clients)
```

**Comment by brockallen** [comment]
Well, the in-memory store can be used for testing, but some people use them in production as well based on what makes sense for their scenario. We're a framework that allows you to do what you want/need based on your requirements. I think you should determine where it makes sense for you to store your config data, and then if you do choose a database/store, then add caching on it if it helps your performance.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
