### ISSUE TITLE
How to issue some user claims depending on the client?

### ISSUE THREAD

**Issue by Duke4848** [DuendeSoftware/Support#228]
**Which version of Duende IdentityServer are you using?**

5

**Which version of .NET are you using?**

.NET 6

**Additional context**

I would like to be able to issue a phone_number claim xor email claim depending on what is required by the client. 
I understand that I can add a claim to identity token in `ProfileService`, however how to configure the client in the db so I will be able to check what is required by a client in the profile service?

**Comment by brockallen** [comment]
This is what scopes and the resource object model are for: https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/

**Comment by Duke4848** [comment]
Thanks Brock figured it out by now, I have additional question, if I can't issue a claim (it is allowed but I am missing user data, for example user didn't fill phone number) what is the best practice, should I somehow do a redirect in a ProfileService, issue identity token with a missing claim  and let the client handle it?

**Comment by brockallen** [comment]
basically once your app has the user's `sub` (subject ID) claim value, then sure -- you can make all the (custom) API calls you want a lookup anything else.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
