### ISSUE TITLE
Just would like a confirmation on my understanding of front-channel and back-channel logout

### ISSUE THREAD

**Issue by HansKindberg** [DuendeSoftware/Support#229]
**Which version of Duende IdentityServer are you using?**: 5.2.4

**Which version of .NET are you using?**: net 5

I just would like to know if I understand this correctly. It is about front-channel and back-channel logout.

The note here https://docs.duendesoftware.com/identityserver/v6/ui/logout/notification/#notifying-clients-that-the-user-has-signed-out says:

_Both the front-channel and JS-based notifications make use of cookies in iframes. If your architecture spans multiple sites, this will not work reliable. We recommend using back-channel notifications in this case. See the supported specifications page for links to the relevant documents._

**If my architecture has an IdentityServer at idp.domain-1.com and has clients at client-1.domain-2.com, client-2.domain-2.com then I guess my architecture spans multiple sites?**

To get front-channel to work with above clients I can get it to work by setting the CookieAuthenticationOptions.Cookie.SameSite = SameSiteMode.None at the client. Got it here: https://joonasw.net/view/aad-single-sign-out-in-asp-net-core. **But I guess that is an unsecure solution?**

**Therefore using back-channel in a "architecture spans multiple sites" scenario is the best solution?**

**Comment by brockallen** [comment]
Site has a strict meaning -- it's an apex domain, so TLD+1. For example foo.com vs bar.com are different sites. Subdomains under an apex domain are considered same-site to one another.

**Comment by HansKindberg** [comment]
Ok. In my scenario we then span multiple sites.

And to handle front-channel logout, in my scenario, by setting "CookieAuthenticationOptions.Cookie.SameSite = SameSiteMode.None" at the clients cookie-authentication configuration. **Is that unsecure or not?**

**Comment by HansKindberg** [comment]
@brockallen 
Thank your very much.
