### ISSUE TITLE
C# library to handle Acess token and refresh token ? (Scenario : Protecting API with Client Credential Flow)

### ISSUE THREAD

**Issue by riaadh** [DuendeSoftware/Support#23]
Hello, 
I am using identity server to protect my APIs (server to server communication).
Is there a c# client library that handles all the calls under the hood (access token, refresh token, and expiration) 
so i don't need to do this every time i have to call the api 

```
var tokenResponse = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
{
    Address = disco.TokenEndpoint,

    ClientId = "client",
    ClientSecret = "secret",
    Scope = "api1"
});


```
and just do something like this 

```
var apiClient = new IdentityserverHttpClient();

var response = await apiClient.GetAsync(myProtectedApiUrl);
```

Thank your for your help.

**Comment by brockallen** [comment]
We recommend: https://identitymodel.readthedocs.io/en/latest/

Also, you don't use refresh tokens if you're just doing server-to-server with client credentials flow. Just re-issue the original client credentials request to obtain a new access token.

**Comment by riaadh** [comment]
> We recommend: https://identitymodel.readthedocs.io/en/latest/
> 
> Also, you don't use refresh tokens if you're just doing server-to-server with client credentials flow. Just re-issue the original client credentials request to obtain a new access token.

thank you that's exactly what i was looking for.
