### ISSUE TITLE
Introspect endpoint authentication failure

### ISSUE THREAD

**Issue by Fezzer** [DuendeSoftware/Support#231]
**Which version of Duende IdentityServer are you using?**
6.1.5

**Which version of .NET are you using?**
6

**Describe the bug**
I am trying to implement PATs as shown in your sample. I have it all working locally but when I host the IdentityServer as a webservice in Azure calls to the introspection endpoint fail saying "Invalid API secret". I am using the same secret and hash values locally and in the Azure hosted instance. I must be missing something somewhere but, for the life of me, I can see what it is!

I have attached screenshots of the API Resouces and the log of the error.

Local API Resource
<img width="853" alt="APIResource Local" src="https://user-images.githubusercontent.com/9000553/192341967-15246330-a250-4ed2-b188-6da24edab3f3.png">

Azure API Resource
<img width="858" alt="APIResource Azure" src="https://user-images.githubusercontent.com/9000553/192341975-604075e2-cb50-437f-85c9-24649e5bba17.png">

Error
<img width="1175" alt="IntrospectionError" src="https://user-images.githubusercontent.com/9000553/192343402-53f25cbe-ac95-4601-8c66-9192006ec849.png">

**Comment by brockallen** [comment]
Hmm... I'd almost like to some logging of a hash of the secret locally vs in azure to really ensure the same value is making it to IdentityServer. Would there be anything in your azure infrastructure that's possibly filtering the secret (possibly like a WAF because it has odd characters in it)?

**Comment by Fezzer** [comment]
I did wonder if the hash could be different between the local and Azure environments so I put an endpoint in the IdentityServer to return the hash of a string passed to it. It gave me the same value in both instances, the same value that is set in the secrets. I can't see that there would be anything in our Azure infrastructure that would be filtering the secret. We don't have anything that complex in there, just app services, functions and SQL databases.

**Comment by brockallen** [comment]
Hmm, then maybe it's the value loaded from the store? So I'd log that hash to compare vs local. If that's not it, then the only other thing I can suggest is to override the secret validator, put your version in DI, and emit more logs.

**Comment by Fezzer** [comment]
🤦‍♂️There was an errant tab after "SharedSecret" in the Azure data. How embarrassing is that? I’m going to go and have a serious word with myself now…

Thank you for your suggestions.
