### ISSUE TITLE
How to add specific claims to the ID Token

### ISSUE THREAD

**Issue by btwyford** [DuendeSoftware/Support#232]
Hi,

We want to be able to add specific Claims to the ID Token.

Currently only "acr" is added, looking into the code this is undertaken by the GetOptionalClaims method of the DefaultClaimsService.

Is it possible to override this behaviour?

Thanks.

**Comment by brockallen** [comment]
Add as UserClaims to the IdentityResource scopes the client is requesting: https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/identity/, and then ensure your profile service is adding them: https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/#user-claims

**Comment by btwyford** [comment]
The issue is that when an access token is requested the context.RequestedClaimTypes are null.

Then setting context.IssuedClaims to a specific claim only adds it to the access token and not the ID token.

How do we control which claims go into the ID token?

If I set AlwaysIncludeUserClaimsInIdToken = true then all claims appear in the ID token.

**Comment by btwyford** [comment]
I have even tried using a custom ICustomTokenRequestValidator class, but that fails to add anything to the tokens.

**Comment by brockallen** [comment]
Claims to be delivered to the client via id_token and userinfo endpoint are controlled with the `IdentityResource`s, and claims to be delivered to the API via the access token are controlled with the `ApiScope`s.

https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/

I wonder if your client is not making the request to the user info endpoint? Is it ASP.NET client? If so, then enable `GetClaimsFromuserInfo` on the OIDC options in the client.

**Comment by brockallen** [comment]
Any update here?

**Comment by btwyford** [comment]
I solved the issue by:

1. Setting AlwaysIncludeUserClaimsInIdToken = true
2. Using the following code in my custom profile service:

switch (context.Caller)
            {
                case IdentityServerConstants.ProfileDataCallers.ClaimsProviderAccessToken:
                case IdentityServerConstants.ProfileDataCallers.ClaimsProviderIdentityToken:
                    foreach (var claimName in ReferenceData.IDTokenMandatoryClaims)
                    {
                        var claim = user.MyClaims.Find(c => c.Type == claimName);

                        if (claim != null) {
                            // Only attempt to add if the User has a matching claim
                            context.IssuedClaims.Add(claim);
                        }
                    }
                    
                    break;
                default:
                    context.AddRequestedClaims(user.MyClaims);
                    break;
            }

Note that my claims are a virtual collection of attributes persisted in the user database.
