### ISSUE TITLE
Reference token is no longer, and ApiSecrets table is no longer available after upgrade

### ISSUE THREAD

**Issue by hubaozhang2017** [DuendeSoftware/Support#233]
**Which version of Duende IdentityServer are you using?**
6.0
**Which version of .NET are you using?**
6.0
**Describe the bug**
We are using Reference token, and found the function is no longer working after upgrading IDS from 3.0 to 6.0. The ApiSecrets table is no longer there.

**To Reproduce**

Steps to reproduce the behavior.
We defined the following in out api startup file:

```

                      services.AddAuthentication(options =>
			{
				// Identity made Cookie authentication the default.
				// However, we want JWT Bearer Auth to be the default.
				options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
				options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
			})
			.AddIdentityServerAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme,
			jwtOptions =>
			{
	
			},
			referenceOptions =>
			{
				// oauth2 introspection options
				referenceOptions.Authority = Configuration.GetSection("IdentityServerUrl").Value;
				referenceOptions.ClientId = "api";
				referenceOptions.ClientSecret = "scopeSecret";
			});

```
**Expected behavior**

Then, we tested in postman with valid reference token. We could call our api methods correctly before upgrade from IdentityServer4 to Duende IdentityServer. With the upgrade, the reference token is no longer although jwt token still works.

**Log output/exception with stacktrace**

**Additional context**

**Comment by brockallen** [comment]
In IdentityServer4 between v3 and v4 there was a change in the configuration object model. The ApiSecrets table was reworked to be the ApiResourceSecrets table.

**Comment by hubaozhang2017** [comment]
@brockallen The problem is that we can get a reference token, and we get an error msg when calling our api method:

`The API key is invalid or expired`

Do you have an example for reference token?

**Comment by brockallen** [comment]
What do the IdentityServer logs say when you make the introspection request? Also, debug level logs give more info, so it might provide more help.

**Comment by brockallen** [comment]
And yes, we have a sample here: https://docs.duendesoftware.com/identityserver/v6/samples/basics/#introspection--reference-tokens

**Comment by hubaozhang2017** [comment]
@brockallen  I made some changes in api codes:

`
services.AddAuthentication("token")

    // JWT tokens
    .AddJwtBearer("token", options =>
    {
        options.Authority = Constants.Authority;
        options.Audience = "resource1";

        options.TokenValidationParameters.ValidTypes = new[] { "at+jwt" };

        // if token does not contain a dot, it is a reference token
        options.ForwardDefaultSelector = Selector.ForwardReferenceToken("introspection");
    })

    // reference tokens
    .AddOAuth2Introspection("introspection", options =>
    {
        options.Authority = Constants.Authority;

        options.ClientId = "resource1";
        options.ClientSecret = "secret";
    });
`
It seems better.  However, the call from postman returns the following error msg:

`
You are not allowed to use this API
`
I really don't where to put a break point to know what was wrong in IdentityServer. My expression is that Api calls IdentityServer doesn't like.

**Comment by brockallen** [comment]
>  I really don't where to put a break point to know what was wrong in IdentityServer. My expression is that Api calls IdentityServer , and the identityserver issued the error message.

This is why I suggested you enable debug level logging in your IdentityServer -- you will get all kinds of useful logging messages to let you know what's happening.

**Comment by hubaozhang2017** [comment]
@brockallen  I think I figured out the problem. Thank you.

**Comment by brockallen** [comment]
Can you share what it was?

**Comment by hubaozhang2017** [comment]
@brockallen  
After the code changes in API using Selector.ForwardReferenceToken("introspection"), the code worked. 
The error message was from our own codes.
