### ISSUE TITLE
How to prompt user for additional info if I can't issue a certain claim?

### ISSUE THREAD

**Issue by Duke4848** [DuendeSoftware/Support#234]
**Which version of Duende IdentityServer are you using?**

Duende (5)

**Which version of .NET are you using?**
 
.NET 6

I have a scenario when I want add claims in GetProfileDataAsync(ProfileDataRequestContext context) in ProfileService. These claims are required for a **particular client** only, not all of them. However the user haven't filled required info beforehand, let's say it's phone number.

What should I do at this moment? What is best practice? Should I somehow fail issuing token in GetProfileDataAsync and redirect a user to page where the user is being asked for missing phone number? But in order to associate that new phone number with his account first I need to issue the token anyway so the user is authenticated to be able to fill missing data and then somehow reissue the token.

What is the best practice?

**Comment by brockallen** [comment]
I think `GetProfileDataAsync` is too late to decide to prompt the user, because it's called from a variety of workflows.

You'd need to determine that you need that data when you have the user in an interactive workflow, and that'd be on your login page. In the login page you can use the interaction service to find out what client is making the request and then adjust the workflow to prompt the user for the additional data.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by Duke4848** [comment]
> All set on this issue -- can we close?

Yes, please, thank for an advice. I will try to approach the issue next week.

**Comment by Duke4848** [comment]
@brockallen 
Sadly the documentation is very short. Do you have any samples how to implement such Authorize Interaction Response Generator ? In the meantime I'll read Duende code around that subject. Thank you.

**Comment by brockallen** [comment]
Here's the basic workflow:

The Authorize Interaction Response Generator allows you to override the SSO behavior based on some logic in the authorize endpoint request. You'd then redirect either to the login page or a custom page where you'd need to detect what needs to be prompted. The data the user provides you would then need to be stored somewhere (either in the session by calling SignInAsync or in some database, depending on the lifetime of this data). The once the custom workflow completes and redirects to the returnUrl then your custom profile service should be able to add this custom data into issued tokens.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
