### ISSUE TITLE
Identity server 4 - Open web page inside Native app (Android and IOS)

### ISSUE THREAD

**Issue by KaranBodhani** [DuendeSoftware/Support#235]
I have 2 client applications registered with Identity server 4 and in web browser it works perfectly and even SSO is working fine.

Now I have to open the same web application in mobile but inside Native application.

So we have created on native application inside it. We will open a web page inside the web view.

It should work as follows.
1. Mobile native applications will have their own UI (Android and IOS) - This should get connected to ID4 and get the authentication. (Tried to get JWT token  via Connect/token endpoint)
2. After login, when a user tries to open a web page it should get logged-in automatically. In the web page it should not show the Login page on the web view again.
3. Now say the user has not accessed the application for 2 days and on the 3rd day mobile native should be logged in and when the user opens the web page in view it should also get logged in automatically.

Same should happen with IOS.

Any technical leads on how to achieve this or any sample would help.

**Comment by brockallen** [comment]
> We will open a web page inside the web view.

This is not the recommendation. Rather, the external/system browser should be used: https://datatracker.ietf.org/doc/html/rfc8252#section-6

Also, this forum is for supporting Duende IdentityServer. IdentityServer4 is essentially end of life:

https://github.com/IdentityServer/IdentityServer4/#important-update
