### ISSUE TITLE
Exposing a BFF API to a machine client

### ISSUE THREAD

**Issue by ajohnson-hpd** [DuendeSoftware/Support#236]
**Which version of Duende BFF are you using?**
1.2.3
**Which version of .NET are you using?**
6
**Describe the bug**

I am creating an app where the front-end uses BFF, but that also needs to expose the API to a machine client. The default setup for BFF is to use strict same site cookies and to use anti-forgery tokens, and I want to keep both of these security measures in place for the browser client. However, these security measures make it impossible (as far as I can tell) to expose this same API to machine clients. Is it possible for me to change these security settings based on the clientID? I want the web client to use same site cookies and the anti-forgery token, but I want the machine client to be a little more open.
To get around this issue I can create two different endpoints for the same API, one for the web client and one for the machine client, but this seams like an awkward setup.

**Comment by brockallen** [comment]
> I am creating an app where the front-end uses BFF, but that also needs to expose the API to a machine client. 

The API would not be in the BFF them, and instead it would be a "remote API" as we describe in our docs: https://docs.duendesoftware.com/identityserver/v6/bff/apis/remote/. In short, it's an API that needs to be called with an access token given the variety of callers. 

Any API in the BFF itself is not a general purpose API and will use the user's cookie in the browser to authenticate. That's what we call a "local API": https://docs.duendesoftware.com/identityserver/v6/bff/apis/local/

**Comment by ajohnson-hpd** [comment]
After following your links it looks like the normal practice would be for me to create a remote API, and then have the BFF local API forward its request to this remote API. If that is the case then I believe you answered my question.

**Comment by brockallen** [comment]
> After following your links it looks like the normal practice would be for me to create a remote API, and then have the BFF local API forward its request to this remote API.

Yep, and if you don't need the remote API then you don't need it (e.g. if all you have is the SPA calling it and then it'd just be a local API). But in your above scenario now that you have 2 diff apps that need to share the API, then it'll now require an access token, so it will be a remote API (using the BFF terminology).
