### ISSUE TITLE
Blazor Server-Side Login with Identity Server

### ISSUE THREAD

**Issue by imprathamesh** [DuendeSoftware/Support#239]
**Which version of Duende IdentityServer are you using?**
6.1,5

**Which version of .NET are you using?**
ASP NET 6

**Describe the bug**
How do I make login Settings for blazor Server-Side Project ? I tried to add code as same asp.net core project but its not working. When I redirect to authorize profile.razor page it should be redirect to identity server project to login but it will not redirect and show error string not found. 

I don't want to secure full app like If I visit any page so it will automatically redirect me to login page. Only Authorize Specified razor pages.

Please help me with this issue?

**Comment by brockallen** [comment]
Hi -- There are several things you're asking for at once here. I will try to tease them out:

> How do I make login Settings for blazor Server-Side Project

I'm not following what you need here. Do you need help with setting up the server-side sessions DB? Or do you need to know how to setup the BFF client in your IdentityServer?

> When I redirect to authorize profile.razor page it should be redirect to identity server project to login but it will not redirect and show error string not found.

What's the error string?

> I don't want to secure full app like If I visit any page so it will automatically redirect me to login page. Only Authorize Specified razor pages.

This should not be a problem -- you'd just add the normal authorization guards on those pages like any other blazr app.

**Comment by brockallen** [comment]
Any update here?

**Comment by imprathamesh** [comment]
The issue is in my code. The oidc is not generating the auth url to identity server project. 
It's fixed now. 

issue not making any sense you can delete it if you want
