### ISSUE TITLE
Missing user claims and roles

### ISSUE THREAD

**Issue by karol-exthand** [DuendeSoftware/Support#24]
**Which version of Duende IdentityServer are you using?**
Identity Server 6

**Which version of .NET are you using?**
6

**Describe the bug**
I am not getting roles and claims for the identity user while using authorization_code grant type with the web app.

**To Reproduce**

Steps to reproduce the behavior.

I added new user withs some custom claim (like name) and roles(like member of admin),

```
alice = new IdentityUser
                {
                    UserName = "alice",
                    Email = "AliceSmith@email.com",
                    EmailConfirmed = true,
                };
                var result = userMgr.CreateAsync(alice, "Pass123$").Result;
                if (!result.Succeeded)
                {
                    throw new Exception(result.Errors.First().Description);
                }

                result = userMgr.AddClaimsAsync(alice, new Claim[]
                {
          new Claim(JwtClaimTypes.Name, "Alice Smith"),
          new Claim(JwtClaimTypes.GivenName, "Alice"),
          new Claim(JwtClaimTypes.FamilyName, "Smith"),
          new Claim(JwtClaimTypes.WebSite, "http://alice.com"),
                }).Result;
                if (!result.Succeeded)
                {
                    throw new Exception(result.Errors.First().Description);
                }
                _ = userMgr.AddToRoleAsync(alice, member.Name).Result;
```
I added  IdentityResource and scopes to reflect those new information.

 ```
public static IEnumerable<IdentityResource> IdentityResources =>
            new IdentityResource[]
            {
            new IdentityResources.OpenId(),
            new IdentityResources.Profile(),
            new IdentityResource("roles", "User role(s)", new List<string> { JwtClaimTypes.Role }),
            new IdentityResource("name", "User name", new List<string> { "name" })
            };

.
.
.
 AllowedScopes = { StandardScopes.OpenId, StandardScopes.Profile, StandardScopes.Email, StandardScopes.Phone, "name", "roles"},
```

EDIT:
When I authenticate with this user, token contains custom claims, but they do not show in the claim principal.

**Comment by brockallen** [comment]
> When I authenticate with this user, token doesn't include any custom claims.

The claims returns depends on the scopes requested, so make sure your "roles" and "name" scopes are requested by the client. Then ensure that the client us using the access token and requesting the claims from the userinfo endpoint.

Also, if you're using ASP.NET Core's OIDC handler, then you need to tell it to not filter the returned claims, by changing the claim mappings: https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/

Also, in your IdentityServer make sure you have the ASP.NET Identity integration enabled: https://docs.duendesoftware.com/identityserver/v6/aspnet_identity/, or implement your own IProfileService: https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

**Comment by karol-exthand** [comment]
@brockallen 
I do include the roles and name in my startup and I map them, if that is what you mean:

```
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "cookie";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("cookie")
            .AddOpenIdConnect("oidc", options =>
            {
                options.Authority = Configuration["InteractiveServiceSettings:AuthorityUrl"];
                options.ClientId = Configuration["InteractiveServiceSettings:ClientId"];
                options.ClientSecret = Configuration["InteractiveServiceSettings:ClientSecret"];

                options.ResponseType = "code";
                options.UsePkce = true;
                options.ResponseMode = "query";

                options.Scope.Add(Configuration["InteractiveServiceSettings:Scopes:0"]);
                options.Scope.Add("name");
                options.Scope.Add("roles");
                options.ClaimActions.MapUniqueJsonKey("role", "role");
                options.ClaimActions.MapUniqueJsonKey("name", "name");
                options.SaveTokens = true;
                options.Events = new Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectEvents
                {
                    OnTokenResponseReceived = async ctx =>
                    {
                        string test = "test";
                    }
                };
            });
```

Also, I didn't make myself clear. The actual raw JWT contains all requested claims, but they don't show up in the claim principal.

I am surely missing something trivial here, but I don't know what.

**Comment by brockallen** [comment]
Are you sure they're in the id_token? Also, I don't see the config for "GetClaimsFromUserInfoEndpoint" set.

**Comment by karol-exthand** [comment]
That's it. I had to put GetClaimsFromUserInfoEndpoint = true, which is odd because it should be true by default according to the documentation.

But my role is not represented as a role. I mean, this policy works:
```
options.AddPolicy("MemberRole",
                     policy => policy.RequireClaim("role", "Member"));
```

but this doesn't:
```
options.AddPolicy("MemberRole",
                     policy => policy.RequireRole("Member"));
```

Is there a way to make the 2nd work?

**Comment by brockallen** [comment]
You're missing the role claim type setting: https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Basics/MvcBasic/src/Startup.cs#L64

**Comment by karol-exthand** [comment]
Yes, that does it. Thanks
