### ISSUE TITLE
Example of startup for ServerSideSessions stored in SQL Server

### ISSUE THREAD

**Issue by glenndorr-ntracts** [DuendeSoftware/Support#240]
Duende IdentityServer 6.1.5
 .NET 6.0

I'm wanting to add server side sessions. All is good with the in memory version. I would like to now store them in SQL for the reasons in your documentation. I have already added the ServerSideSessions table and am having trouble finding an example or documentation to have them start to be written there.

Thank you

**Comment by brockallen** [comment]
That is part of the operational data: https://docs.duendesoftware.com/identityserver/v6/data/operational/

**Comment by brockallen** [comment]
Yea, when you use our "AddOperationalStore" from the EF package then it wires up those stores, but you also do need AddServerSideSessions() on our fluent config API.

https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/#enabling-server-side-sessions

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
