### ISSUE TITLE
Identity Server breaks when attempting to re-create the database.

### ISSUE THREAD

**Issue by MartinBelton-gov** [DuendeSoftware/Support#241]
**Which version of Duende BFF are you using?**
Using Identity Server 6

**Which version of .NET are you using?**
Version 6

**Describe the bug**
Somehow I managed to get Identity Server 6 working with a C# client following the official video using entity framework and SqlLite and Asp.Net Identity,

I then decided that I needed to reseed the database. So I deleted the sqlLite database files, ran update database (migrations command) on each of the database contexts, reseed the database. Then I tried to login in from the client and get an error message.
I think the error message said there was an incorrect returnUrl

Steps to reproduce the behavior.
1. Run the template isinmem.
2. Convert the code to use Asp.Net Identity and an SqlLite database

At this point Client appears to be OK and is able to login.

3. Delete Database
4. Run update database
dotnet ef database update -c PersistedGrantDbContext
dotnet ef database update -c ConfigurationDbContext
dotnet ef database update -c ApplicationDbContext

5. Run the Server /seed argument to reseed the database 
6. remove /seed argument start the server up
7. Attempt to Login and you find it is broken! 

**Expected behavior**
It should be working as before allowing the client to log in.

Why is this happening? What am I missing?

**Comment by MartinBelton-gov** [comment]
Hi,

Does this help:

[image: image.png]

[image: image.png]

It is quite easy to recreate.

Regards,

Martin Belton

**Comment by brockallen** [comment]
![image](https://user-images.githubusercontent.com/649492/193833443-a8c4c3a2-febd-459e-8461-829fa8434113.png)

Not so much :)

**Comment by brockallen** [comment]
Any update here?

**Comment by MartinBelton-gov** [comment]
I was expecting you to give me an update! :-)

**Comment by brockallen** [comment]
I never got a good screen shot from you (see above).

**Comment by MartinBelton-gov** [comment]
All you have to do to replicate the error is:

1. Create a project from Duende Template.
2. Follow this video: https://www.youtube.com/watch?v=eLRGlnGGUQs

Hopefully you are able to log in at this stage from your client Razor Pages
App.

3. Delete the database.
4. Recreate the database using:
dotnet ef database update -c PersistedGrantDbContext
dotnet ef database update -c ConfigurationDbContext
dotnet ef database update -c ApplicationDbContext

Then try to log in from your client application.and it fails!
Will not even show you the login form.

I am not using Identity Server any more, we have switched to an alternate
solution.
If you can fix the problem, great, would love know the fix.
If not, well so be it.

**Comment by brockallen** [comment]
To test quickly, I just did that with both the *isef* and *isaspid* templates. It worked for me.

As for that video, if I get time I'll watch it (it's not a video from Duende, so I'm unsure what it shows). I'm guessing there's some problem in some of the steps creating the EF migrations if it's starting with the *isinmem* template. Likely just some EF issue, though.

**Comment by MartinBelton-gov** [comment]
Nothing here suggests that the issue is actually fixed

**Comment by josephdecock** [comment]
This was closed because we were unable to reproduce the issue, and because you said you were no longer using IdentityServer. We pretty routinely recreate these databases for our own internal testing without issue.
