### ISSUE TITLE
Server-side session removed from DB earlier than expiration time

### ISSUE THREAD

**Issue by LilitHakobyan** [DuendeSoftware/Support#245]
I am using IdentityServer 6.1.1 .
The project is .NET 6.

In IdentityServerOptions options, i have this config 
` options.Authentication.CookieLifetime = TimeSpan.FromMinutes(15);`
and I am using Identity Server provided cookie handler.
Also, I have server-side sessions enabled which store the sessions in SQL server DB.

After the user login, it created the server-side session and stores the DB as expected.

As you can see I have set the expiration time as 15 min.

The problem is that it was removed from DB approximately 5 min ago from the creation.

Is this expected behavior or there is something wrong with the settings?

Thanks

**Comment by brockallen** [comment]
Do you see log entries in your IdentityServer saying that the server-side session DB records were being deleted?

**Comment by LilitHakobyan** [comment]
Found the issue in my code. Thanks for the replay.
