### ISSUE TITLE
Support passing ForwarderRequestConfig when mapping ApiEndpoint

### ISSUE THREAD

**Issue by quangtrinh-spce** [DuendeSoftware/Support#246]
**BFF 1.2.3**

**.NET 6.0**

**This is not a bug, just feature request**
As in my project, we have to call to external web services, which can lead to a long-running task in back-end. Front-end need to wait for that (this is the requirement).

Due to default 100 seconds timeout of HttpForwarder, the client always get 504 after 100 seconds passed.

I made a workaround to pass ```ForwarderRequestConfig``` object when mapping instead of using ```ForwarderRequestConfig.Empty```
```
var forwardConfig = new ForwarderRequestConfig
{
    ActivityTimeout = TimeSpan.FromSeconds(requestTimeoutInSeconds),
};
await forwarder.SendAsync(context, apiAddress, httpClient, forwardConfig, transformer);
```

Should we make this being official by allowing users to pass ```ForwarderRequestConfig``` object when call ```MapRemoteBffApiEndpoint```?

**Comment by brockallen** [comment]
I think our approach has been that once you need to start to configure behaviors from the reverse proxy layer, then it's better if you don't use our very thin layer on top of YARP and instead code that yourselves with all the tweaking you need/want to do based on your situation. We have a sample on using the lower level YARP configuration: https://docs.duendesoftware.com/identityserver/v6/samples/bff/#yarp-integration
