### ISSUE TITLE
profile service picking up claims added to the usermanager

### ISSUE THREAD

**Issue by dobestar** [DuendeSoftware/Support#247]
We are using Idenetity Server 6.0.4, on .net 6.

I have overridden the profile service in our IdentityServer so we have control over the claims that are included in the tokens.

I have a scenario where when after user logs in, if they don’t have a ‘name’ claim then we add it to the list of claims with usermanager.AddClaimAsync.

However this is not getting picked up in the ProfileDataRequestContext that is sent to the profile service, unless that claim exists AT THE POINT of logging in. 

Is there a way that this claim can be included in the ProfileDataRequestContext that is sent to the profile service if it has been added after login?

**Comment by brockallen** [comment]
This is the classic problem of the tokens your client app gets back being a snapshot of the user's data. So you have two options: 1) have the user login again, or 2) have your client app re-trigger the userinfo endpoint.
