### ISSUE TITLE
Identity server with electron app

### ISSUE THREAD

**Issue by damikun** [DuendeSoftware/Support#248]
Hi

Is there a workeround to run identity servrer without https? i know since V5/V6 it is required but if i have electron app that host identityserver under the hoood i cannot install electron app with selfsigned certs... 

Running electron with https is ok in case im cominicating with remote servers.. But since all work is in-process im bit lost if there is proper way to solve this..

Electron use chromium engine under the hood so it behaves as browser...

Thx for tips...

**Comment by brockallen** [comment]
You're installing a local app and embedding IdentityServer in it? That's highly unusual. 

In any event, you control the ASP.NET Core host that contains IdentityServer, so you can control all of those things.

**Comment by damikun** [comment]
> You're installing a local app and embedding IdentityServer in it? That's highly unusual. 
> 
> 
> 
> In any event, you control the ASP.NET Core host that contains IdentityServer, so you can control all of those things. Where are you getting errors about HTTPS?

Yeah the app can use embedded identity server in case no remote is provided.. reason is to make it work without remote api in case testing or local ussage the idea was to keep api equal just switch between local/remote.. im out of office now will ping you back with concrete error place..

**Comment by brockallen** [comment]
Any update?

**Comment by damikun** [comment]
Sorry for late answer i overeide the .net https cfg and it seems to work... thx ..
