### ISSUE TITLE
IdentityTokenLifetime not working or how to add JWT token access for customers' API calls

### ISSUE THREAD

**Issue by oriolqc** [DuendeSoftware/Support#249]
Hello,

We are building a SaaS and we selected Identity Server for Identity Management.

We have a SPA that is authenticating to our IS with code flow. Everything goes fine.

We wanted now to provide an "API Key" to our customers to allow them call our API.

We thought we could provide the generated JWT token, changing the lifetime to 1 year.

However, we realized that the generated JWT token expires very soon, so we tried to change IdentityTokenLifetime to expand the token lifetime. The idea was to provide a JWT token for 1 year.

IdentityTokenLifetime is set by default to 5 minutes, it allows 3600 seconds but if you try for example 1 day it doesn't work. Not to say 1 year as it was our objective.

Is it a bug of IdentityTokenLifetime or are we missusing Identity Server?

Of course in this scenario adding more "clients" it's not an option, as the number of clients is huge and unknown in advance (every customer can use it).

Thanks a lot,

**Comment by brockallen** [comment]
> We wanted now to provide an "API Key" to our customers to allow them call our API.
> We thought we could provide the generated JWT token, changing the lifetime to 1 year.

Have you looked at our PAT sample?

https://docs.duendesoftware.com/identityserver/v6/samples/tokens/#personal-access-tokens-pat

> IdentityTokenLifetime is set by default to 5 minutes, it allows 3600 seconds but if you try for example 1 day it doesn't work. Not to say 1 year as it was our objective.

Identity tokens are not used to call APIs -- access tokens are.

**Comment by oriolqc** [comment]
Hi, we changed to access tokens. Now we have tokens that last for 3600 seconds.

How can we set up tokens that last for 1 year?

**Comment by brockallen** [comment]
> How can we set up tokens that last for 1 year?

There is an *AccessTokenLifetime* setting on the *Client* for that. Having said that, are you sure you want that? Refresh tokens are the official mechanism for long lived access without irrevocable access tokens.
