### ISSUE TITLE
Does Duende Software provide any admin portal for managing IdentityServer configuration?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#25]
**Which version of Duende IdentityServer are you using?**
v6.0.4

**Which version of .NET are you using?**
.NET 6

**Question**

Does Duende Software provide any admin portal for managing IdentityServer configuration?

We found [Admin UI](https://www.identityserver.com/products/adminui) which provides such features. But it's not owned by Duende Software. Do you recommend it? Is it aligned with the Duende Identity Server version releases?

**Comment by leastprivilege** [comment]
Hi, 

we wrote down our thoughts here:
https://blog.duendesoftware.com/posts/20220204_admin_ui/

But yes - the AdminUI from RSK does work fine with Duende IdentityServer.
