### ISSUE TITLE
How to redirect from front-end app to external identityserver endpoint?

### ISSUE THREAD

**Issue by dobestar** [DuendeSoftware/Support#250]
Using identityserver 6.0.4 with .net 6 on a Blazor server app.

The iD server is established and running fine.

I am now trying to test a separate Web API authorization (on .net 6). Having gone through the Quickstarts on the duende docs, I am having trouble getting the Blazor app to redirect to my authority endpoint when not authorized. 

I have set the builder.services.addAuthentication() with options detailing authority etc. e.g.

```
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "Cookies";
    options.DefaultChallengeScheme = "oidc";
}).AddCookie("Cookies")
    .AddOpenIdConnect("oidc", options =>
    {
        options.Authority = "https://localhost:44333";

        options.ClientId = "test";
        options.ResponseType = "code";
        options.ResponseMode = "query";
        options.SaveTokens = true;

        options.Scope.Clear();
        options.Scope.Add("openid");
        options.Scope.Add("profile");
        options.Scope.Add("offline_access");
        options.GetClaimsFromUserInfoEndpoint = true;
    });
```

All the examples I can find show manual navigation to the login endpoint in the same app, e.g. account/login - hpow can I trigger a redirect to the endpoint as specified in the Program.cs, with all the correct query parameters etc?

**Comment by brockallen** [comment]
>     options.DefaultChallengeScheme = "oidc";

The above line is what tells your ASP.NET Core app which authentication handler you want to handle calls to Challenge (that's the API that's calls server-side to get a user logged in). That's the official way in ASP.NET Core to cause that to happen. When you use [Authorize] on endpoints, then that internally calls Challenge which then triggers the OIDC workflow to the authorize endpoint. 

So I'm not sure where in your app you're looking to do this, but look at the HttpContext.ChallengeAsync API -- that would be what you call to trigger it yourself.

HTH
