### ISSUE TITLE
How is this implemented on react native?

### ISSUE THREAD

**Issue by Jonatthu** [DuendeSoftware/Support#252]
I want to know or to see a sample using react native since all that is talking about is protecting SPA or Blazor applications but does not go through the use case of a native app specially using react native (expo).

Does react native (ios, android) apps need BFF with cookie auth session instead of token with PCKE? Or our native apps can keep using OpenID and OAuth2 specs without Duende BFF ?

**Comment by Jonatthu** [comment]
Based on https://reactnative.dev/docs/security#authentication-and-deep-linking
OAuth2 PKCE is still the recommended way to work with react native applications since they have a SecureStorage that works like localStorage in the browser but this actually is encrypted.

The strategy based on this would be that on web you must use Duende.BFF for maximum security but for the native apps you can still use OAuth2 PKCE storing the JWT token into SecureStorage and using it on the headers.

Is this a good conclusion? @brockallen  @leastprivilege

**Comment by brockallen** [comment]
I don't know much about React native, but if it's for building a native app for mobile then it falls under the category of a native app and RFC8252 applies:

https://datatracker.ietf.org/doc/html/rfc8252

What it says is that you should use code flow + PKCE, and use the system browser to get the user logged in. There's a reference/sample implementation for JS apps here:

https://github.com/openid/appAuth-JS

**Comment by brockallen** [comment]
Oh and yes -- since it's not a web app that you're building, then the BFF approach/library is not applicable.

**Comment by Jonatthu** [comment]
Thanks good to know!
