### ISSUE TITLE
can't successfully use gateway federation

### ISSUE THREAD

**Issue by Simkiw** [DuendeSoftware/Support#253]
Duende IdentityServer: 4.1.1

.Net 5

**Context**  
I followed the guide in the official docs, showing how to implement identity server as a federation gateway.  
I do get my external IdP relying on OIDC and **it does redirect me to that provider where I log in.**  
However, on the way back to my page, **it throws an exception: Unable to unprotect the message.State**.

**To Reproduce**
I'm not using kubernetes, or azure. Just my machine: a web app, identity server acting as a gateway to other IdPs (cIAM for example)

my client startup:
```
services.AddAuthentication(options =>
                                       {
                                           options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                                           options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                                       })
                    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
                    .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
                                      {
                                          // options.MetadataAddress = Configuration["CiamIdp:DiscoveryDoc"];
                                          options.Authority    = Configuration["Is4Idp:Authority"];
                                          options.ClientId     = Configuration["Is4Idp:ClientId"];
                                          options.ClientSecret = Configuration["Is4Idp:ClientSecret"];

                                          options.ResponseType = "code";
                                          options.UsePkce      = false;
```

As for identity server:
```
services.AddAuthentication()
                    .AddOpenIdConnect("oidc", "cIAM", options =>
                                                      {
                                                          options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                                                          options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                                                          options.SaveTokens = true;
                                                          
                                                          options.MetadataAddress = Configuration["CiamIdp:DiscoveryDoc"];
                                                          options.ClientId     = Configuration["CiamIdp:ClientId"];
                                                          options.ClientSecret = Configuration["CiamIdp:ClientSecret"];
                                                          options.ResponseType = "code";
                                                          options.UsePkce      = false;
                                                          options.SignedOutRedirectUri =  Configuration["CiamIdp:SignedOutRedirectUri"];
                                                          options.Events = new OpenIdConnectEvents
                                                          {
                                                              OnRedirectToIdentityProvider = context =>
                                                              {
                                                                  context.ProtocolMessage.SetParameter("app", "IandT");
                                                                  return Task.FromResult(0);
                                                              }
                                                          };
                                                      });
```
If I use the same IdP config directly on my client (without identity server), it works fine.  
I read stuff on the net, tried to check out the DataProtection, but ... that only helps when using multiple instances of the web app client. At this point, I'm a bit lost.  Any help, I would appreciate.  
Thank you.

**Expected behavior**
Make my app authenticate to the external idp via identity server.

**Log output/exception with stacktrace**

```
 Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\SESA646353\Documents\MoBe\Dev\Tutorials\IdentityServer4\PocIS4Ocelot\IdmsPoC\IdentityServer
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      Showing login: User is not authenticated

```

**Additional context**

The external IdP uses an extra parameters "app". And I might have accidently launched another web app, however, when authenticating, it asks me if i want to keep the old session or use this new one. For me that's just a detail, my goal is to make my app authenticate to the external idp via identity server.

**Comment by brockallen** [comment]
>  However, on the way back to my page, it throws an exception: Unable to unprotect the message.State.

Do you have a callstack for that? Also, do you have more than one external IdP?

**Comment by Simkiw** [comment]
This is what I have in the stacktrace:
And above is just the basic thing (application running on localhost
>info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\directoryToMyApp
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Unable to unprotect the message.State.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

And no, I'm just using one external IdP which I named cIAM.  
I'm gonna try using another Identity Server instead of my cIAM and see if I get the same behavior though.

**Comment by Simkiw** [comment]
I might have found the problem, but a confirmation would be very welcome:  
Must the external IdP redirect to identity server (my federation gateway) instead of my app?  

Because, when I tried using identity server as my external IdP, the first thing it didn't like was the redirect uri. I had to point it to the federation gateway and only then it worked. When I think about it, it sounds logical but I thought it could be redirecting to my app directly without having to go to the federation gateway before. If this case is also possible, could you tell me what am I missing? (the more i think about it though, the more it doesn't make sense in terms of oidc/oauth protocol)

Anyway, let me know about it. Thanks

**Comment by Simkiw** [comment]
Yeah. The redirect uri were the problem. Too bad the error wasn't as explicit as it was when using is4 as the external idp.  
I'm closing the issue. Thank you @brockallen

**Comment by brockallen** [comment]
Yea, that error is from the Microsoft OIDC handler. It can't process the result, and the step it failed on was the state processing.

**Comment by Simkiw** [comment]
If I may ask, @brockallen  
I was naive to think it would magically happen but .. no. I do lose any information related to the external idp :)  
By any chance, could you point me to any direction helping me achieve that?  

Like once authenticated to the external idp, keep some information regarding the user from the external id token ... in the id token that will be issued from the federation gateway.  

I have some thoughts, but there is no consistency in them : overwrite is4 middleware that will access the http context, retrieve the id token and assign some of its values to the new id token.  (I don't know where to start from actually)

**Comment by brockallen** [comment]
Yes, that's the right place to do application specific logic after the user has been authenticated from the external IdP.

**Comment by Simkiw** [comment]
Hmmm ..  
Ok, it appears there is something I'm missing. While debugging the code, I do see all the original claims at the **ExternalController** (coming from the external id token), however, I don't see where they get overwritten?  
Like, where I can add claims to my id/access token that is4 will issue later on.   

(I thought the new is4 claims will be added at the external controller, after getting the external token.)

**Comment by brockallen** [comment]
>  Like, where I can add claims to my id/access token that is4 will issue later on.

The rough workflow is: user comes to login, triggers external IdP, callback returns from external IdP and issues external cookie with claims from external IdP, the external controller callback runs and uses claims from external cookie to issue main cookie (and delete external cookie), and then redirects to returnUrl back into IdentityServer to complete the protocol workflow, IdentityServer uses the main auth cookie to know who user is and then calls into the profile service to gather claims for the tokens, and then tokens are delivered back to client.

**Comment by Simkiw** [comment]
Yes, that I understood, or I think I understood :)

And I think my issue is the "the identity server user" which is created without my initial claims.  

```
// issue authentication cookie for user
            var isuser = new IdentityServerUser(user.SubjectId)
            {
                DisplayName = user.Username,
                IdentityProvider = provider,
                AdditionalClaims = additionalLocalClaims
            };
            
            await HttpContext.SignInAsync(isuser, localSignInProps);
```

And when I try to pass in a new claimsPrincipal (which contains the necessary claims) instead of the **isuser**, I get an exception:  
 *SignInAsync when principal.Identity.IsAuthenticated is false is not allowed when AuthenticationOptions.RequireAuthenticatedSignIn is true*  

I'm looking it up and see what's going on.

**Comment by brockallen** [comment]
> And I think my issue is the "the identity server user" which is created without my initial claims.

The claims you use here at the claim you need at user login time (which will likely be fewer claims than you need in the client app or API). It's just to capture stuff to identity the user and how they logged in. Those claims are then an input later to the profile service when claims need to be added into tokens. Normally the profile service looks anything else from the database.

>  SignInAsync when principal.Identity.IsAuthenticated is false is not allowed when AuthenticationOptions.RequireAuthenticatedSignIn is true

That's likely because you didn't use the ctor for ClaimsIdentity that accepts the authentication type (e.g. "password"). You need to pass a non-null value for authentication type for the *IsAuthenticated* to be true. That's an unfortunate behavior from how MS coded that class.

**Comment by Simkiw** [comment]
>That's likely because you didn't use the ctor for ClaimsIdentity that accepts the authentication type (e.g. "password").

Yes, for these, I had to try out different values, one of them was "password" :) (but it didn't change anything, as you already know)

>The claims you use here at the claim you need at user login time (which will likely be fewer claims than you need in the client app or API). It's just to capture stuff to identity the user and how they logged in. Those claims are then an input later to the profile service when claims need to be added into tokens. Normally the profile service looks anything else from the database.

Although, you are confirming the tests I've been runnning. Because no matter what I do, I end up with the same set of claims. I tried manipulating the additional claims of the **IdentityServerUser** object, I also passed in a new **ClaimsPrincipal** instance instead.

>Those claims are then an input later to the profile service when claims need to be added into tokens.

And yes, thank you for the additional information. It made me send a request to the userinfo endpoint and see what it looks like: **I do find the original identity claims (from the external idp)**.  

With that being said, I think i got the information I needed. I just used the identity server original code, with identity server user instance, cause otherwise, I got some error "user with subject id ABC marked as inactive."

Too bad, I can't explicitly change the claims at the moment the id token is issued. Maybe in the future, or perhaps I missed a detail. Anyway, thank you @brockallen

**Comment by Simkiw** [comment]
**Ps**: does the same logic apply to access tokens? If the external idp issues a jwt, can I actually look up the claims and scopes it has sent back? Or even append some identity server scopes (coming from the federation gateway) to them? According to my understanding, it's a yes through this line of code for example :   
`externalResult.Properties.GetTokenValue("access_token")`, where `external result is type of AuthenticateResult`

**Comment by brockallen** [comment]
> Too bad, I can't explicitly change the claims at the moment the id token is issued.
> Ps: does the same logic apply to access tokens?

Yes you can -- the profile service is the extensibility point that allows that when IdentityServer creates tokens for your clients.

https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

> If the external idp issues a jwt, can I actually look up the claims and scopes it has sent back? 

That's between your code and the external IdP, so possibly?
