### ISSUE TITLE
Relationship between KeyManagement and TokenLifetime?

### ISSUE THREAD

**Issue by epoyraz** [DuendeSoftware/Support#255]
Hi Everyone,

we are using Duende.IdentityServer and are so far happy customers :)
The Use-Case we have is our mobile Apps (Brezelkönig, k kiosk and avec) 

Currently, we are facing one problem:
Ocassionally, users are getting logged out after some time, usually after a couple of weeks.

The AccessTokens have a Lifetime of **12 hours** and the refreshtokens are valid for **12 months**.

This is what i see in the Identityserver Logs:
`Error unprotecting key with kid "E7FBE98786A90171BBCCC1938600AEBC"`

With following exception:

```
System.Security.Cryptography.CryptographicException: The key {b68fa9ea-94a3-4250-bd58-b12cb7aeb6c4} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```

Indeed, the kid on the IDP is different:
https://login.brezelkoenig.ch/.well-known/openid-configuration/jwks

We use the automatic key rotation, without any changes to the key management options.
I suspect, that we need to set the:
- RotationInterval
- PropagationTime
- RetentionDuration

accordingly. But i am not sure which values to set, as i am not understanding the relationship of the KeyManagement and (Refresh) TokenLifetime.
I read the documentation about the Key Management: https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/

Accoding to my understanding the key with `E7FBE98786A90171BBCCC1938600AEBC` rotated and therefore is not available anymore and the refresh token does not work anymore. Am i right?
Which values would you suggest to setup the key management correctly?

**Comment by brockallen** [comment]
That error sounds more like you have not configured the ASP.NET Data Protection feature: https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by epoyraz** [comment]
I did setup Dataprotection, but the keys are saved in GCP Storage using Google.Cloud.AspNetCore.DataProtection.Storage.

Additionally, I still have these entries my "key" table on the database:
<img width="1112" alt="Screenshot 2022-10-06 at 20 15 21" src="https://user-images.githubusercontent.com/1207226/194377067-459dfd4c-c056-4639-b9f3-7067389f67c3.png">

The second entry is equivalent to the kid in https://login.brezelkoenig.ch/.well-known/openid-configuration/jwks and the first entry (E7FBE98786A90171BBCCC1938600AEBC) is the missing one.

I have 2 questions:
1. Why does https://login.brezelkoenig.ch/.well-known/openid-configuration/jwks contain only one entry?
2. Can i use Automatic Key Rotation with DataProtection setup in GCP?

**Comment by brockallen** [comment]
> I did setup Dataprotection, but the keys are saved in GCP Storage using Google.Cloud.AspNetCore.DataProtection.Storage.

Then I'm not sure why you get the data protection error "Error unprotecting key with kid "E7FBE98786A90171BBCCC1938600AEBC"". Is it possible that records in that table were populated from staging or pre-prod (meaning some other host not using the same DP keys as your prod server)?

> Why does https://login.brezelkoenig.ch/.well-known/openid-configuration/jwks contain only one entry?

Possibly because you're not yet approaching the window where a new signing key needs to be created.

> Can i use Automatic Key Rotation with DataProtection setup in GCP?

Yes, in fact DP must be configured for all those features listed on the link I provided earlier. How it's configured/stored is a detail and so I assume your use of GCP is done correctly.

**Comment by epoyraz** [comment]
> Then I'm not sure why you get the data protection error "Error unprotecting key with kid "E7FBE98786A90171BBCCC1938600AEBC"". Is it possible that records in that table were populated from staging or pre-prod (meaning some other host not using the same DP keys as your prod server)?

Did i understand this correctly: If i setup DataProtection with the Cloud Azure/GCP correctly, then the `keys` table shouldn't be populated at all?
I truncated the keys table (in our staging enviorement) and it got populated with a new key after a login.

> Possibly because you're not yet approaching the window where a new signing key needs to be created.
I set the RetentionDuration to 270 days expecting to see the other (previous key: `E7FBE98786A90171BBCCC1938600AEBC`) 
`options.KeyManagement.RetentionDuration = TimeSpan.FromDays(270);`
it didn't have any effect.

> Yes, in fact DP must be configured for all those features listed on the link I provided earlier. How it's configured/stored is a detail and so I assume your use of GCP is done correctly.

I don't do anything differently than here (official documentation):
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/7c54362fc1215ea7ba5b9a2bc43112208e5d8471/appengine/flexible/AntiForgery/Startup.cs#L54

I can also see that there are keys in Google Cloud Storage

**Comment by brockallen** [comment]
> then the keys table shouldn't be populated at all?

The keys table is for the signing keys -- those are different than the DP keys.
