### ISSUE TITLE
Get clients from database

### ISSUE THREAD

**Issue by golrokhka** [DuendeSoftware/Support#258]
Hello,

I have a question about Duende authentication. I have been using config.cs for storing my clients and other configuration.
Today, I migrated them to a database instead of in the Config class. I did it and all is okay but I want to get rid of Config.cs
and read configs directly from the database but I don't know how I can access the ConfigureDbContext and its entities.
I assume I should make some changes to the program.cs like below but couldn't figure out what I should use instead of those commented lines.
```
builder.Services.AddIdentityServer()
 .AddConfigurationStore(options =>
 {
    options.ConfigureDbContext = b => b.UseSqlServer(connectionString,
        sql => sql.MigrationsAssembly(migrationsAssembly));
})
.AddOperationalStore(options =>
{
    options.ConfigureDbContext = b => b.UseSqlServer(connectionString,
        sql => sql.MigrationsAssembly(migrationsAssembly));
})
//.AddInMemoryIdentityResources(Config.IdentityResources)
//.AddInMemoryApiScopes(Config.ApiScopes)
//.AddInMemoryClients(Config.Clients)
.AddMyUserStore();
```

Could you please help me with this matter?
Thanks,
Goli

**Comment by brockallen** [comment]
> but I don't know how I can access the ConfigureDbContext and its entities.

You can just use the DbContext if you have a custom need to read/write that data. We sort of do that from our EF template to seed the database: https://github.com/DuendeSoftware/IdentityServer.Templates/blob/main/src/IdentityServerEntityFramework/SeedData.cs, but that's only a "cheap" way to get the data into the DB. We also use them in our sample admin UI here: https://github.com/DuendeSoftware/IdentityServer.Templates/tree/main/src/IdentityServerEntityFramework/Pages/Admin

**Comment by golrokhka** [comment]
Thanks for the response.
I created a custom DbContext that inherits from ConfigurationDbContext so I can also use the entities from that database. In creating that I noticed a possible bug that I created a ticket for.

**Comment by brockallen** [comment]
> In making that I noticed a possible bug so I created a ticket.

Was there a new issue somewhere, or did I miss something?

**Comment by golrokhka** [comment]
This is the error I was talking about: https://github.com/DuendeSoftware/Support/issues/276
I'll close this thread.
Thanks!
