### ISSUE TITLE
IdentityServer3

### ISSUE THREAD

**Issue by EncodedViking** [DuendeSoftware/Support#26]
I've got 2 questions. 

My company had a decent sized exodus of senior architects and developers recently. A half dozen of their most knowledgeable guys left en-mass. I got hired in the aftermath, and their OIDC implementation has landed in my lap. It's a bit of a nightmare. Based on IdentityServer3(I think), and looks to largely be dated from 2015 time frame based on the versions of numerous key assemblies in the source code. Numerous custom components involved. 77,000 lines of code. Couple freaky bugs that I'm having a hard time even finding resources for online. *sigh*

I'm smart enough to know that old security software is dangerous because it frequently doesn't have the ability to withstand modern threats. But I'm not knowledgeable enough on OIDC to know what exact threats we are presently vulnerable to. I've been buried in the world of DOD digital certificate auth for the last 15 years, and until recently only understood OIDC from a pretty high level. I'd like to suggest to my employer that they begin posturing themselves for an upgrade to our OIDC software. And will probably recommend they use your new stuff. So there is potential money in this for you guys. If you could give me a couple high level points regarding vulnerabilities to use in a pitch to my superiors, that would be helpful. Perhaps rough number of threats we are vulnerable to and what the top 3 are?

Second question. I'm following a pluralsight course to begin my path of learning how to implement my own idp, and it uses IdentityServer4. Just got my angular app to authenticate with my idp for the first time last night! Wahoo! I read a blog post belonging to one of you guys recently and it indicated that you took your project from open source to a for/profit product. A move I whole heartedly approve of. I'm good at what I do and I don't do it for free. So I don't expect others to either. But I'm a little confused now. Is the IdentityServer/IdentityServer4 repo the one I should be learning? Or DuendeSoftware/IdentityServer? Are they the same?

Thanks for your time.

**Comment by leastprivilege** [comment]
> Perhaps rough number of threats we are vulnerable to and what the top 3 are?

I do not have that data. But IdentityServer3 targets Katana 3 (the underlying web framework from Microsoft) which is also not supported anymore since a couple of years (IOW - no security patches). The even pre-dates SameSite cookies.

> But I'm a little confused now. Is the IdentityServer/IdentityServer4 repo the one I should be learning? Or DuendeSoftware/IdentityServer?

Duende is the place to be. Use this as a learning starting point:
https://docs.duendesoftware.com/identityserver/v6/quickstarts/

**Comment by brockallen** [comment]
Something else I'd recommend would be our training course: 

https://duendesoftware.com/training/identityaccesscontrol

It's the biggest bang for your buck in term of learning OIDC and OAuth2.

**Comment by EncodedViking** [comment]
Does the training course come with long term access to training videos? Because 2 days is far too little time for me to absorb this level of information by listening to lectures alone, even if a lab is involved. I learn by doing, investigating, reading and getting my hands dirty. And there's not enough time in 2 days for me to fully use and retain all the concepts you are covering. In fact. You'd be able to serve more people if you had a video option for your training. The in person course is great. But it's expensive because your time is personally required. You'll be able to serve more people if you had a video option. And the inherent economies of scale will allow you to charge less money for the product. More value to your customers, less required of you. Just a thought.

**Comment by brockallen** [comment]
Understood, and we have some things in the works. But for right now, that's the best we have.

**Comment by EncodedViking** [comment]
That'll do donkey. Thanks for the feedback.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
