### ISSUE TITLE
Can not redirect to client application after logged out from WS fedartion and stays on ADFS signout page

### ISSUE THREAD

**Issue by RajaSomu783** [DuendeSoftware/Support#260]
**Which version of Duende IdentityServer are you using?**
6.0.0
**Which version of .NET are you using?**
.NET 6 with ASP.NET Identity
**Describe the bug**

Hi,
I have been using WsFederation to authenticate users and I can redirect to client app after logged in and when logged out the request stays on ADFS sign out page showing successfully signed out but couldn't redirect to client app. I can redirect to client app after logged out when using local account authentication. 

I have been debugging the code and found that **identityServerOptions.UserInteraction.LogoutUrl** is coming as "/Account/Logout"  and WsFederation.RedirectContext.ProtocolMessage.Wreply is coming as **https://localhost:5001/Account/Logout/LoggedOut?logoutId=CfDJ8Lxxxxxxx** and could not match absolute path in the '**if**' condition and if I hardcoded the **LogoutUrl** as /Account/Logout/LoggedOut in the condition then I can redirect to client application. Could you please let me know where exactly I had to change the LogoutUrl rather than hardcoding. 

Couldn't  redirect with below code from **WsFedConfigureOptions** file from samples

`if (uri.AbsolutePath.EndsWith(identityServerOptions.UserInteraction.LogoutUrl, StringComparison.OrdinalIgnoreCase) && uri.Query.Contains(identityServerOptions.UserInteraction.LogoutIdParameter + "="))
                    {
                        url += uri.Query;
                    }
                    else
                    {
                        // empty value to trigger logic in OnRemoteFailure below
                        url += "?" + identityServerOptions.UserInteraction.LogoutIdParameter + "=";
                    }`

I can redirect to client app by hard coding logout url 

`if (uri.AbsolutePath.EndsWith("/Account/Logout/LoggedOut", StringComparison.OrdinalIgnoreCase) && uri.Query.Contains(identityServerOptions.UserInteraction.LogoutIdParameter + "="))
                    {
                        url += uri.Query;
                    }
                    else
                    {
                        // empty value to trigger logic in OnRemoteFailure below
                        url += "?" + identityServerOptions.UserInteraction.LogoutIdParameter + "=";
                    }`

I tried to assign logout url in the startup file of identity server options but nothing works for me. And also in both cases code is calling **OnRemoteFailure**  event and I can see only failure message as **No Message**.
Thanks in advance.

**Comment by brockallen** [comment]
> I have been using WsFederation to authenticate users and I can redirect to client app after logged in and when logged out the request stays on ADFS sign out page showing successfully signed out but couldn't redirect to client app.

IIRC this is a long standing problem with how the Ws-Fed handler from Microsoft was designed, and how ADFS works. ADFS needs the reply to URI to be the base address under the original reply to URI at login time, but the Microsoft WsFed handler doens't do this. It uses whatever URL the current request in the app is from.

So in the sample I think you're referring it's trying to re-write the reply to address to be the base address, but there is state that needs to be preserved (the LogoutIdParameter), so it's trying to work that in.

> I can redirect to client app by hard coding logout url

I'm not sure why that's working, or if it's the right thing. Can you check that the `identityServerOptions.UserInteraction.LogoutUrl` is the right value to begin with?

**Comment by RajaSomu783** [comment]
Thanks  Brock for the reply. I have  checked  again  the **identityServerOptions.UserInteraction.LogoutUrl** and it starts with leading  '/' (/Account/Logout).  I am not sure how  it is set up  in the identity server and I didn't assign that manually. I don't  have any knowledge in Razor pages.  Could you please let me know where it is  coming  from?

I have been  testing with the samples you provided for WsFedration and  with out hardcoding logout url ( ** /Account/Logout/LoggedOut**), client couldn't redirect to  mvc client. tbh i don't  know  why it is working and I have  no knowledge about  this. I just did to pass the  if condition upon debugging the code. As I said in my previous the 
code is  always calling OnRemoteFailure event and I can see only failure message as 'No Message'.

**Comment by brockallen** [comment]
`identityServerOptions.UserInteraction.LogoutUrl` is set dynamically based on what your cookie authentication handler is set to. You can set it explicitly and that will take precedence, but then you have the cookie handler to also sync with it.

As for the logout, again, that's a strange thing with ADFS. What I'd suggest is to build a stand-alone sample without IdentityServer that only does Ws-Fed to your ADFS and get that all working exactly the way you need. Once you do, then you can transpose that onto your IdentityServer solution.
