### ISSUE TITLE
How to get information such as user's avatar through BFF

### ISSUE THREAD

**Issue by qq1176914912** [DuendeSoftware/Support#263]
/bff/user gets the values as shown in the figure by default. Can I get the user address through /bff/use?
![image](https://user-images.githubusercontent.com/79817742/194843539-6cfabc99-d1dc-4160-94b8-43fb021da4f2.png)
Something similar to getting /connect/userinfo

**Comment by leastprivilege** [comment]
The `/user` endpoint shows the contents of the session. 

This content is sourced by the id_token and some other information by default. If you want specific claims in there, you need to request them via the OIDC `scope` parameter.

**Comment by qq1176914912** [comment]
Use this kind of [https://github.com/DuendeSoftware/Samples/issues/85#issuecomment-1273423711](url)

**Comment by qq1176914912** [comment]
This method is feasible. https://github.com/DuendeSoftware/Samples/issues/85#issuecomment-1273423711
![image](https://user-images.githubusercontent.com/79817742/194979147-47804bf9-c26a-4582-8360-2026ff58b5e2.png)

**Comment by qq1176914912** [comment]
This method is feasible.https://github.com/DuendeSoftware/Samples/issues/85#issuecomment-1273423711
![image](https://user-images.githubusercontent.com/79817742/194979339-85a77302-4019-4294-97f7-dd58e4bca347.png)
![image](https://user-images.githubusercontent.com/79817742/194979353-d7476b22-38b0-42c0-a347-79908256ac84.png)

**Comment by qq1176914912** [comment]
> The `/user` endpoint shows the contents of the session.
> 
> This content is sourced by the id_token and some other information by default. If you want specific claims in there, you need to request them via the OIDC `scope` parameter.
I set these, but it didn't work. Maybe I set them wrong, but this method can be used successfully.https://github.com/DuendeSoftware/Support/issues/263#issuecomment-1273984875
