### ISSUE TITLE
Is there a way to customize the authorization_code expiry?

### ISSUE THREAD

**Issue by PureKrome** [DuendeSoftware/Support#265]
**Which version of Duende IdentityServer are you using?**
5.2.3

**Which version of .NET are you using?**
NET3.1

**Describe the ~bug~ question**

Hi 👋🏻 

quick question - is it possible to programmatically configure the `expiry time` of an `authorization_code` grant?

When I check the grant store, I noticed it's a 5 min expiry.

If we want to change this programmatically (under some specific circumstances, we might want to SHORTEN this time) .. is this possible? This value would **not** be a constant (e.g. make the expiry 1 minute after it was created) .. but a variable time based on some logic ... per request to generate an `auth_code`.

Cheers!

**Comment by brockallen** [comment]
It's a property *AuthorizationCodeLifetime* on the client: https://docs.duendesoftware.com/identityserver/v6/reference/models/client/#token, and it is copied over onto the *AuthorizationCode* stored in the grant store. You could possibly override our default *AuthorizeResponseGenerator* and override *CreateCodeAsync* to tweak that value once the base does its creation.
