### ISSUE TITLE
IdentityServer, BFF, and Blazor Server

### ISSUE THREAD

**Issue by elliottgresham** [DuendeSoftware/Support#268]
IdentityServer Version: 6.1.6
BFF Version: 2.0.0-preview.4
.NET Version: .NET 6

Hi,

I am developing an IdentityServer application, and a separate Blazor Server application. The client in IdentityServer is configured as per the below:

```
new Client
{
    ClientId = "interactive.confidential",
    ClientName = "Interactive client (Code with PKCE)",

    RedirectUris = { "https://localhost:5003/signin-oidc" },
    PostLogoutRedirectUris = { "https://localhost:5003/signout-callback-oidc" },
    BackChannelLogoutUri = "https://localhost:5003/bff/backchannel",

    ClientSecrets = { new Secret("secret".Sha256()) },

    AllowedGrantTypes = GrantTypes.CodeAndClientCredentials,
    AllowedScopes = AllScopes,

    AllowOfflineAccess = true,
    RefreshTokenUsage = TokenUsage.ReUse,
    RefreshTokenExpiration = TokenExpiration.Sliding
}
```

IdentityServer is registered on the Blazor Server side as:

```
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = "https://localhost:5001";

    options.ClientId = "interactive.confidential";
    options.ClientSecret = "secret";
    options.ResponseType = "code";
    options.ResponseMode = "query";

    options.Scope.Clear();
    options.Scope.Add("openid");
    options.Scope.Add("profile");
    options.Scope.Add("api");
    options.Scope.Add("offline_access");

    options.MapInboundClaims = false;
    options.GetClaimsFromUserInfoEndpoint = true;
    options.SaveTokens = true;
})
```

BFF is registered as:

```
.AddBff(options =>
{
    options.AnonymousSessionResponse = Duende.Bff.AnonymousSessionResponse.Response200;
    options.ManagementBasePath = "/bff";
})
.AddServerSideSessions();
```

`UseBff`, `MapBffManagementEndpoints`, and `AsBffApiEndpoint` are also called.

Clicking the login link (`/bff/login`) within the Blazor Server application, takes me to the IdentityServer application, where I can login. On successful login, I am returned back to the Blazor Server application, where I am logged in. Great, it works really nicely!

However, I am having an issue with the `bff/user?slide=false` endpoint. When I send a request to this endpoint, it indicates that the user is not logged in - I get the following message in the logs:

> User endpoint indicates the user is not logged in, using status code 200

Please note, I have registered the 'anti forgery handler'. I'm sure this is working as expected, because when I remove this, I receive the following message in the logs:

> Anti-forgery validation failed. local path: '/bff/user'

I have been through the quick start guides and checked the samples - I am sure I am missing something really simple, but I wonder if you could advise and shed some light on what I am doing wrong and how I can resolve this.

Do you have any working v6 Blazor Server BFF samples? I can see the v6 Blazor WASM samples and the v5 Blazor Server, which I have used but to not avail.

I look forward to hearing from you.

**Comment by brockallen** [comment]
The BFF library isn't really appropriate for Blazor Server, as all UI events/calls are already happening on the server.

**Comment by elliottgresham** [comment]
If you have multiple browser tabs open with Blazor Server, then you could log out in one browser tab, but still be able to click around the application in the other browser tabs and logged in. Similarly, you could logout of IdentityServer, but still be logged into the Blazor Server application.

I was hoping to poll 'bff/user' to check the authentication state, and then reload the page as and when appropriate to log the user out.

As suggested, I'll try the MVC style approach, and look at implementing back-channel log out, and checking the authentication state differently.

Thanks.

**Comment by jkdba** [comment]
BFF may not appropriate for Blazor Server however, Server-Side Sessions for Blazor Server would be tremendously useful.

It could remove the need to store auth tokens in cookies, and all the other benefits of server-side sessions, along with solving many of op's requirements.
