### ISSUE TITLE
Multiple Issuer Error in 4.0.0-16

### ISSUE THREAD

**Issue by sethyukna** [DuendeSoftware/Support#269]
**Which version of Duende IdentityServer are you using?**
4.0.0-16

**Which version of .NET are you using?**
.net core 6

**Describe the bug**
We are seeing the following error in our logs which we are having trouble tracking down.  We've checked all of our application settings and none are using http:// when referencing our identity server.  This honestly doesn't seem like an error to me as it's the same subdomain just over SSL.

At this point I'm wondering if this error is somehow cached, and needs to be manually updated.

Any information anyone can provide would be great.

**To Reproduce**

Unsure exactly where it's coming from.

**Expected behavior**

We should not see this error.

**Log output/exception with stacktrace**

```
Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: ["https://[subdomain].azurewebsites.net", "http://[subdomain].azurewebsites.net"].
```

**Additional context**

**Comment by sethyukna** [comment]
Thanks for that response @brockallen.  We still are unable to identity from where the http schema is being used.  That being said I do have a follow up question.  

It's pretty obvious what the issue is, however, how long will this error persist?  For example, if 2 weeks ago, we had some requests using http for 1 day.  We would first see the multiple issue error 2 weeks ago.   Jump to today, assuming we've removed the calls over http, would we still be seeing the multiple issuer error?  Will  it go away without manual intervention?

Thanks for the help!

**Comment by brockallen** [comment]
I think once we internally have counted more requests for different issuers than the license allows, we'd log that error on any further requests that use the issuer (which would be a lot). Are you saying the last time you saw it was more than 2 weeks ago?

**Comment by sethyukna** [comment]
What I'm saying is because we cannot find the client causing the issue, I'm wondering if the issue occurred by accident, and the error message is cached.  Maybe a developer misconfigured their environment to point at our prod ID server, hit http, and then realized it was prod, and changed it back.  Now b/c we have had 1 hit to http in the past, all of our https requests throw an error as well.

Are you saying however, that the error would only be thrown on the 2nd issuer?  For example, if https was first used, and then http was used (lets assume by accident), that the error would ONLY be thrown on requests using http?

Thanks again for the help.

**Comment by sethyukna** [comment]
@brockallen - any thoughts on my previous comment?  Thanks!


> What I'm saying is because we cannot find the client causing the issue, I'm wondering if the issue occurred by accident, and the error message is cached. Maybe a developer misconfigured their environment to point at our prod ID server, hit http, and then realized it was prod, and changed it back. Now b/c we have had 1 hit to http in the past, all of our https requests throw an error as well.
> 
> Are you saying however, that the error would only be thrown on the 2nd issuer? For example, if https was first used, and then http was used (lets assume by accident), that the error would ONLY be thrown on requests using http?
> 
> Thanks again for the help.

**Comment by sethyukna** [comment]
Thank you for the help.  We rebooted our identity server and the error has gone away.
