### ISSUE TITLE
How to get Duende IdentityServer working with AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by absta** [DuendeSoftware/Support#27]
Hi, I'm facing some challenges when deploying a basic sample in-memory identity server (*slightly modified) to AWS Elastic Beanstalk.

**Version**
I'm using Duende.IdentityServer 6.04 running on .NET 6

**The issue**
When running locally everything works perfectly. However, when deployed to elastic beanstalk I can no longer login via the web page. I suspect this may have something to do with the fact that my .well-known/openid-configuration is not returning https?

![image](https://user-images.githubusercontent.com/3491517/162488453-76855c2c-425d-4267-8bbf-80f2038a5653.png)

The [https://identity.accommodation.co.uk/connect/token](url) endpoint works fine and returns a bearer token as expected

The modifications I have made are an attempt to handle the forwarded headers (see code snippet below)
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages();
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.RequireHeaderSymmetry = false;
});

builder.Services.AddIdentityServer(options =>
{
    options.Events.RaiseErrorEvents = true;
    options.Events.RaiseInformationEvents = true;
    options.Events.RaiseFailureEvents = true;
    options.Events.RaiseSuccessEvents = true;

    options.EmitStaticAudienceClaim = true;
}).AddTestUsers(TestUsers.Users)
    .AddInMemoryClients(Config.Clients)
    .AddInMemoryApiResources(Config.ApiResources)
    .AddInMemoryApiScopes(Config.ApiScopes)
    .AddInMemoryIdentityResources(Config.IdentityResources);

var app = builder.Build();

app.UseForwardedHeaders();
app.UseHsts();
app.UseHttpsRedirection();
app.UseIdentityServer();

app.UseStaticFiles();
app.UseRouting();   

app.UseAuthorization();
app.MapRazorPages().RequireAuthorization();

app.Run();
```

I have configured the AWS application load balancer to which the DNS is pointing, to forward to the single ec2 instance the identity server is deployed on (see image below)

![image](https://user-images.githubusercontent.com/3491517/162489691-57d4e5fe-1423-4ec9-a2b9-86da743db9b3.png)

**To Reproduce**
Upload the attached deploy_bunde.zip to a new environment and observe the behaviour
OR
navigate to [https://identity.accommodation.co.uk](url) and click on the **here** link as highlighted in red below 
(username and pwd are both alice)

![image](https://user-images.githubusercontent.com/3491517/162490044-88e7e817-d208-4b0c-a87a-f00e0f8aa865.png)

Thanks for looking :-)

[deploy_bundle.zip](https://github.com/DuendeSoftware/Support/files/8454029/deploy_bundle.zip)

**Comment by brockallen** [comment]
Sounds like HTTPS is offloaded somewhere else, so you'd need something like this:

https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
