### ISSUE TITLE
Windows Login with LocalLogin as Fallback

### ISSUE THREAD

**Issue by FalkWinkler** [DuendeSoftware/Support#271]
We use the identityserver with Windows Authentication and as fallback the local login. This occurs when no login data is assigned to the Windows account. There will be no buttons with the external schemes are displayed.
I redirect to the login with an extra parameter fallback=true. The problem is the Windows user is logged in and when I login with LocalLogin it works but the AntiforgeryToken fails because it was created with the Windows user.
Does anyone have an idea how I can solve this?

**Comment by brockallen** [comment]
I'm not sure the problem you're running into, but anti-forgery is a general ASP.NET feature, and not specific to Duende IdentityServer. I'd suggest opening a question with Microsoft to explain what you're trying to do with anti-forgery.

**Comment by FalkWinkler** [comment]
I know that this is not a specific identity server problem. I know what the problem is, I am looking for a solution.
Our identityserver is configured to do only windows authentication.
Workflow:
- Windows Login
- I notice that there is no account in our userstore.
- but the Windows login itself was successful and the Windows user is logged in
- now I make a redirect to the LocalLogin with an additional parameter fallback=true
- but the Windows user is still logged in and when GET to Account/Login a new antiforgery token is created, when creating the token the logged in Windows user is used, so my redirect doesn't work properly
- a new challenge must be triggered, but there I lose my additional parameter fallbak=true

So I am looking for a solution to trigger a new challenge without loosing my addional parameter fallback=true

**Comment by brockallen** [comment]
> but the Windows user is still logged in and when GET to Account/Login a new antiforgery token is created, when creating the token the logged in Windows user is used, so my redirect doesn't work properly

Perhaps disable automatic authentication:

https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/UserInteraction/WindowsAuthentication/IIS/IdentityServer/src/Startup.cs#L29

**Comment by FalkWinkler** [comment]
Hi, think that was the solution.
