### ISSUE TITLE
IdentityServer and webclient in same site

### ISSUE THREAD

**Issue by liselotte123** [DuendeSoftware/Support#274]
Duende IdentityServer: 6
.NET 6.0

We have the identityserver and the webclient in the same project running under the same url.
It works and we can authenticate against the identityserver when trying to access pages in the web that needs authorization.

We now noticed that we don't get any accesstoken from the httpcontext for our webclient. We tried by calling:
HttpContext.AuthenticateAsync().Result.Properties.Items but it contains no accesstoken.
There is also no cookie "AspNetCore.Cookies" in the browser for the webclient as there is for other webclients that run outside of our project.

In the configuration in program.cs we have the following code:

builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "Cookies";
    options.DefaultChallengeScheme = "oidc";
})
    .AddCookie("Cookies")
    .AddOpenIdConnect("oidc", options =>
    {
        options.Authority = "https://localhost:7091";

        options.ClientId = "web";
        options.ClientSecret = "secret";
        options.ResponseType = "code";

        options.SaveTokens = true;

        options.Scope.Clear();
        options.Scope.Add("openid");
        options.Scope.Add("profile");

        options.GetClaimsFromUserInfoEndpoint = true;
    });

and the webclient is configured like this:
new Client
            {
                ClientId = "web",
                ClientSecrets = { new Secret("secret".Sha256()) },

                AllowedGrantTypes = GrantTypes.Code,
                    
                // where to redirect to after login
                RedirectUris = { "https://localhost:7091/signin-oidc" },

                // where to redirect to after logout
                PostLogoutRedirectUris = { "https://localhost:7091/signout-callback-oidc" },

                AllowOfflineAccess = true,

                AllowedScopes = new List<string>
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile
                }
            }

Is it something that we are missing or is there an other way to get the accesstoken?
(We need to have this in our claims to access it from another web built in older .net version)

**Comment by brockallen** [comment]
```
    options.Scope.Clear();
    options.Scope.Add("openid");
    options.Scope.Add("profile");
```

I don't see any API scopes in here, thus no access token. 

https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_scopes/

**Comment by liselotte123** [comment]
I now tried and added:
     options.Scope.Add("apiscope");
and defined "apiscope" as:
   new ApiScope("apiscope", "My Api scope",  new List<string>{"email", "name", "sub"})
but still no cookie or accesstoken

**Comment by brockallen** [comment]
You'd then need to configure your OIDC options to save those tokens.

**Comment by liselotte123** [comment]
I have this: 
options.SaveTokens = true;
or do you mean some other configuration?

**Comment by brockallen** [comment]
Yes, that's the one I meant. But at this point, I'm not sure what's not working. I will say it's very unusual that you want the OIDC in the IdentityServer host. There's really not much point since the cookie in IdentityServer is sufficient for authentication, and that's normally why you'd add OIDC in a client app. 

Another angle to try is to remove the OIDC client in the same host in IdentityServer and instead manually generate an access token for the user. We have an API that can generate an access token for a user that we show in this sample:

https://docs.duendesoftware.com/identityserver/v6/samples/tokens/#personal-access-tokens-pat

This would then also avoid any renewal issues that normally come up with the client and OIDC server are separate (which is the norm),

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
