### ISSUE TITLE
Bug in DeviceFlowCodes entity

### ISSUE THREAD

**Issue by golrokhka** [DuendeSoftware/Support#276]
I'm using Duende 6.1.6 / .net6.0
The bug is Id is missing from the DeviceFlowCodes entity. I had to ignore that entity in my "OnModelCreating" method to pass it.

**Comment by brockallen** [comment]
What `Id`? I think we define a PK based on the other columns.

**Comment by golrokhka** [comment]
Sorry! my bad! The error was something else. The error was complaining that the DeviceFlowCodes entity doesn't have a PK so I had to add the following code to ignore the issue.
![image](https://user-images.githubusercontent.com/26719832/197273272-d1ed7d1b-061e-46ea-a9de-da74c1aba291.png)

**Comment by brockallen** [comment]
We already have a PK defined, unless you're doing something else:

https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework.Storage/Extensions/ModelBuilderExtensions.cs#L187

**Comment by brockallen** [comment]
Any update on this?

**Comment by golrokhka** [comment]
I've been busy with other issues the last couple of days. I'll be back to it in the next few days and keep you updated.

**Comment by josephdecock** [comment]
Any update on this?

**Comment by golrokhka** [comment]
Hi,

Just wanted to let you know I couldn't reproduce the issue after updating
Duende packages.

Thanks,
Goli
