### ISSUE TITLE
'sub' claim missing in access token for m2m clients (RFC9068)

### ISSUE THREAD

**Issue by gekiss** [DuendeSoftware/Support#277]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0

**Describe the bug**
The ([Duende server documentation](https://docs.duendesoftware.com/identityserver/v6/overview/specs/)) confirms that is support JWT Profile for OAuth 2.0 Access Tokens ([RFC 9068](https://datatracker.ietf.org/doc/html/rfc9068)).

According ([RFC 9068-section-2.2](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2)) in access token must be present 'sub' claim.

**To Reproduce**
Run Duende IdentityServer
```
dotnet new -i Duende.IdentityServer.Templates
dotnet new isinmem
dotnet run
```
Send HTTP request
```
POST /connect/token HTTP/1.1
Host: localhost:5001
Content-Type: application/x-www-form-urlencoded
Content-Length: 101

grant_type=client_credentials&client_id=m2m.client&client_secret=511536EF-F270-4058-80CA-1C89C192F69A
```
Decode access_token
```JSON
{
  "iss": "https://localhost:5001/",
  "nbf": 1665774178,
  "iat": 1665774178,
  "exp": 1665777778,
  "aud": "https://localhost:5001/resources",
  "scope": [
    "scope1"
  ],
  "client_id": "m2m.client",
  "jti": "1D736303BBF4AFCA27BC661E307F697B"
}
```

**Expected behavior**

```JSON
{
  "iss": "https://localhost:5001/",
  "nbf": 1665774178,
  "iat": 1665774178,
  "exp": 1665777778,
  "aud": "https://localhost:5001/resources",
  "scope": [
    "scope1"
  ],
  "client_id": "m2m.client",
  "sub": "m2m.client",
  "jti": "1D736303BBF4AFCA27BC661E307F697B"
}
```

**Comment by leastprivilege** [comment]
By default we only issue sub claims if an end-user is involved.

If you want to issue that claims to a M2M client you need to do 2 things

* add a sub claim to the client definition
* set the claims prefix to an empty value on the client definition

https://docs.duendesoftware.com/identityserver/v6/reference/models/client/#token

**Comment by gekiss** [comment]
Thanks for the answer. 
Using a claims of the client is a suitable solution.
