### ISSUE TITLE
Claims added to profile not in JWT

### ISSUE THREAD

**Issue by bgoodearl** [DuendeSoftware/Support#279]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
6.0 for Identity Server app, 3.1 for client web app, but migrating to 6.0 ASAP

**Describe the bug**

We are adding claims to the profile but cannot find information about how to ensure some of those claims
also show up in the JWT.

**Additional context**

```C#
//IdSvr6 app code:
public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
	if (context.RequestedClaimTypes.Any())
	{
		var dbUserInfo = _userRepository.GetDbUserByIdentifier(context.Subject.GetSubjectId(), false, context.Client.ClientId);
		if (dbUserInfo != null)
		{
			var claimsFromDb = new List<Claim>();
			//... claims added to list based on data in database
			context.IssuedClaims.AddRange(claimsFromDb);
		}
	}
	return Task.CompletedTask;
}

//Client side code:
public void ConfigureServices(IServiceCollection services)
{
	//... code omitted for brevity
	IdentityServerOptions idSverSettings = Configuration.GetSection("IdentityServer").Get<IdentityServerOptions>();
	services.AddAuthentication(options =>
		{
			options.DefaultScheme = "Cookies";
			options.DefaultChallengeScheme = "oidc";
		})
			.AddCookie("Cookies", options =>
			{
				options.Cookie.Name = authCookieName;
				if (!string.IsNullOrWhiteSpace(authCookiePath))
				{
					options.Cookie.Path = authCookiePath;
				}
				options.ExpireTimeSpan = TimeSpan.FromMinutes(cookieMinutes.Value);
			})
			.AddJwtBearer(options =>
			{
				options.Authority = idSverSettings.Authority;
				options.TokenValidationParameters.ValidateAudience = false;
				options.Events = new Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerEvents
				{
					OnAuthenticationFailed = JwtBearerEventHandlers.OnAuthenticationFailedHandler
				};
			})
			.AddOpenIdConnect("oidc", options =>
			{
				options.Authority = idSverSettings.Authority;

				options.ClientId = idSverSettings.ClientId;
				options.ClientSecret = idSverSettings.ClientSecret;
				options.ResponseType = idSverSettings.ResponseType;

				options.SaveTokens = true;

				options.Scope.Clear();
				options.Scope.Add("openid");
				options.Scope.Add("profile");
				options.Scope.Add("role");
				options.Scope.Add("user");
				options.Scope.Add("offline_access");

				// role is an array and is special
				options.ClaimActions.MapAllExcept("role");

				options.ClaimActions.MapJsonKey("role", "role");

				options.TokenValidationParameters = new TokenValidationParameters
				{
					NameClaimType = "name",
					RoleClaimType = "role"
				};

				options.GetClaimsFromUserInfoEndpoint = true;
			});
	}	
	//... code omitted for brevity
}

//Client app controller code
protected async Task<string> GetApiTokenAsync()
{
	if (HttpContext != null)
	{
		string accessToken = await HttpContext.GetTokenAsync("access_token");
		if (!string.IsNullOrWhiteSpace(accessToken))
		{
			Logger.LogWarning("GetApiTokenAsync - no access_token token found in claims");
		}
		return accessToken;
	}
	return string.Empty;
}


public async Task<IActionResult> TokenTest()
{
	string apiUrlRoot = GetApiUrlRoot();
	string identityApiUrl = $"{apiUrlRoot}/identity";
	var client = new HttpClient();
	string accessToken = await GetApiTokenAsync();
	client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
	var content = await client.GetStringAsync(identityApiUrl);
	//content contains list of claims from token
	TokenInfoResult tokenInfoResult = JsonConvert.DeserializeObject<TokenInfoResult>(content);
	return View(tokenInfoResult);
}
```

**Comment by brockallen** [comment]
Do you have user claims configured for your ApiScope?

https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_scopes/#adding-user-claims

Do you see `GetProfileDataAsync` getting involved ever with the claims you've defined in your ApiScope?

**Comment by bgoodearl** [comment]
We do not have user claims configured.
We do see GetProfileDataAsync being called twice - once with ClaimsProviderAccessToken as the caller and once with UserInfoEndpoint as the caller.
We're using EF with IdSvr, so we've been looking at what's in the database.
We did find out by experimentation that if we added the name of one of the claims we're looking for from the claims we added from the database to the ApiScopeClaims table, then the test for context.RequestedClaimTypes.Any() in GetProfileDataAsync is true, so we're adding claims to the context.
And I'm now looking into using context.RequestedClaimTypes to determine which of the claims from the database to add to the context.
Is adding claim names to the ApiScopeClaims table the right way to go here?

**Comment by brockallen** [comment]
> We do not have user claims configured.

Adding a UserClaim to the ApiScope is what tells IdentityServer that a certain claim type is desired in the access token. Then in the profile service that claim type is passed and the implementation can look it up for the user (if it has it).

>  Is adding claim names to the ApiScopeClaims table the right way to go here?

The claim type you want needs to be in the *UserClaims* collection: https://docs.duendesoftware.com/identityserver/v6/reference/models/api_scope/#duendeidentityservermodelsapiscope

And yes, if that's loaded from the EF layer then that'd be in the *ApiScopeClaims* table.

>  Is there documentation on how to add to ApiScopeClaims via code?

In what way? Like via some admin tool? We have some thoughts on that here:

https://blog.duendesoftware.com/posts/20220204_admin_ui/

But in our newest EF template we do have a "poor-man's" admin UI to edit ApiScopes and the user claims.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
