### ISSUE TITLE
Data Store - Support for write operations

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#28]
**Additional context**

@leastprivilege 

Some months ago we had short call over Teams and you mentioned that you plan to extend Data Stores to support write operations. 
The context was an implementation of Dynamic Client Registration, which would required write operation on the Client Store.

If I remmember correctly, you told me that this will be supported in Q1 this year. 
Can you please tell me if this is still on the Roadmap?

Best regards,
Novak

**Comment by leastprivilege** [comment]
It is still on the roadmap - but delayed to later this year.

Did you the basic client/scope admin features we added to the EF template. It's pretty straightforward if it is OK to program against the database directly. At least for the time being.

https://blog.duendesoftware.com/posts/20220204_admin_ui/

**Comment by No1e** [comment]
Thank you for the answer. Yes sure I can do that by my self, it is straghtforward. I just wanted to check if you plan to release that feature soon, so that I can avoid implementing that.
