### ISSUE TITLE
PostLogoutRedirectUri is always null

### ISSUE THREAD

**Issue by johannasvovu** [DuendeSoftware/Support#282]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
6.0

**Describe the bug**
I have an application with multiple external providers. Login flow works as expected but not logout. I send a `/connect/endsession` redirect to the server from my javascript client with a valid `id_token_hint` parameter as well as a `post_logout_redirect_uri`  that matches the client configuration. I see the request come in in my logs and it looks fine to me. I can also see this log from the `EndSessionRequestValidator`: 
![image](https://user-images.githubusercontent.com/89024418/196452708-e09b9afe-5a34-4365-ba62-1c258135b3ac.png)
There I can see that my `post_logout_redirect_uri` parameter has value but `PostLogoutUri` does not.

The logout page is called after `/connect/endsession` and if I call `GetLogoutContextAsync` with the logoutId provided to the `OnGet` function the result shows that `PostLogoutRedirectUri` is null.
![image](https://user-images.githubusercontent.com/89024418/196454031-07809445-4ecc-48a7-95e6-3c22bde1e46c.png)

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

I would expect the `PostLogoutRedirectUri` parameter to have the same value as the value that was passed into the `/connect/endsession` as `post_logout_redirect_uri` and the user would then be redirected to that location.

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
Do you have warning level logs enabled? If there's a post_logout_redirect_uri passed, but it's NULL then I'd expect to see a warning indicating it's invalid.

**Comment by johannasvovu** [comment]
I didn´t. Once I changed the minimum level I saw the warning you mentioned and found the error. Thanks!

**Comment by apetrut** [comment]
@johannasvovu I have a similar issue:
![image](https://github.com/DuendeSoftware/Support/assets/13006228/fca83164-3eff-4f4d-b66e-804f41663893)

Can you indicate how you solved it?

I should mention that I set the value: https://subdomain.domain.com in both Redirect URIs and Post Logout Redirect URIs sections in Admin UI.
