### ISSUE TITLE
Unexpected CPU load while consuming Dynamic IdP feature with custom IIdentityProviderStore

### ISSUE THREAD

**Issue by mike-mcfarland** [DuendeSoftware/Support#285]
**Which version of Duende IdentityServer are you using?**

6.1.7

**Which version of .NET are you using?**

6.0.9

**Describe the bug**

When using the dynamic identity provider feature we are experiencing an unexpected and significant increase in CPU load that causes server performance to degrade across all of its concerns (REST API handlers, outbound network calls etc., long authorization times (exceeding 90 seconds in some cases)). When our application is put into a mode where it consumes a static authentication scheme, the increase in CPU load is not observed.

The increase in CPU load appears to be tied specifically to some aspect of the IIdentityProviderStore and even with a memory based implementation of the IIdentityProviderStore interface, injected as a singleton, the increased CPU load is observed. Any insight you can provide into related issues and the invocation pattern on this interface may prove helpful as we actively troubleshoot this integration in our test environments.

**To Reproduce**

Exercise the dynamic identity provider feature with 50-100 users authenticating concurrently and continuously, from different domains (i.e. different authentication schemes tied to different identity provider configurations) using a singleton-injected implementation of IIdentityProviderStore that retrieves scheme names and by scheme name either directly from memory (hardcoded) or via cache-hit (in memory). The longer this test runs the higher the CPU load, even though the number of dynamic identity provider configurations is not increasing; the end-effect is degraded performance including increasingly delayed authorization flows.

**Expected behavior**

The IIdentityProviderStore enumeration of scheme names and lookup by scheme name is expected to have a fixed CPU load that does not increase over time. There are only three schemes loaded in our test, so retrieval of the scheme names is not expected to introduce significant CPU load (we return a pre-computed cached enumerable that contains the most recent collection of scheme names) and retrieval by scheme name is expected to be a log(N) retrieval from a .NET Dictionary keyed by scheme name where the dictionary contains only three key value pairs. No aspect of this workflow is expected to introduce significant CPU overhead from our perspective.

**Log output/exception with stacktrace**

```
N/A
```

**Additional context**

**Comment by brockallen** [comment]
Hi @mike-mcfarland. Do you have caching enabled for the identity provider store? By default, the model data is loaded from the store for every request, which then goes into building the OIDC options. So it might make sense to set a cache value for some reasonable time:

https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders/#store-and-configuration-data

https://docs.duendesoftware.com/identityserver/v6/reference/options/#caching

**Comment by mike-mcfarland** [comment]
We make extensive use of caching, but we are doing so from inside our custom IIdentityProviderStore implementation. Our rationale was that we do not know if IS6 pre-fetches IDP configuration ahead of next user authorization request(s), or will the user be subjected to a cache reload time if their authentication route involves a scheme that has expired from the IS6 identity provider cache.

Our implementation of IIdentityProviderStore performs a periodic background refresh of provider configuration from our persistent data store, and pre-computes an IEnumerable<IdentityProviderName> and Dictionary<string, IdentityProvider> so that it can respond to invocations of:

GetAllSchemeNames( )

and

GetByScheme(name)

without incurring any CPU or network overhead. We thought we were insulating ourselves from any unknowns inside the IS6 caching mechanism, but it sounds like we should look into wrapping our IIdentityProviderStore inside the Caching provider store and adding at least some small cache duration atop our own.

Does IS6 do background pre-fetching into its identity provider cache? Or just-in-time / lazy loading on cache miss?

**Comment by brockallen** [comment]
Yea, if our caching is not enabled then the OIDC options are re-created each time, and that causes the discovery document to be reloaded, etc. So there's a lot going on in the MS OIDC plumbing. Our caching then lets the provider data mapped into the OIDC options to be cached and re-used by the OIDC handler. 

As for when we load -- it's all lazy load as needed. Now, that's not to say your cache still isn't useful. But maybe configure our cache time as a low(er) number sitting on your (likely more sophisticated) cache.

**Comment by mike-mcfarland** [comment]
Thank you for your timely feedback, this helps explain what we were observing.

Are there any enhancement tickets already existing in this area? I understand that lazy loading may be more efficient from an overall system perspective, especially if there are many identity providers with many discovery documents to fetch and they're not all actively in use, but we need to hide these kinds of routing delays from the user as much as possible at login time (without a-priori knowledge about who is about to try and log in and which dynamic IDP that user should be routed to).

**Comment by mike-mcfarland** [comment]
> Thank you for your timely feedback, this helps explain what we were observing.
> 
> Are there any enhancement tickets already existing in this area? I understand that lazy loading may be more efficient from an overall system perspective, especially if there are many identity providers with many discovery documents to fetch and they're not all actively in use, but we need to hide these kinds of routing delays from the user as much as possible at login time (without a-priori knowledge about who is about to try and log in and which dynamic IDP that user should be routed to).

We can use the IS6 cache for now, but if I understood correctly, this will still put the retrieval of the discovery document and related downstream OIDC configuration processing in line (i.e. sequential) with user login, thus exposing our end user to any related delays.

**Comment by brockallen** [comment]
As discussed, it turns out the issue had to do with the Microsoft JWT handler and some bug in version 6.10 of their library. Apparently it was fixed in 6.12, and also working correctly in 6.24. Will close this issue now. Thanks!
