### ISSUE TITLE
calling signout from another razor client with Layout.cshtml and has not any cs file and cannot inject logout model to it 

### ISSUE THREAD

**Issue by HODACDWS** [DuendeSoftware/Support#287]
**Which version of Duende IdentityServer are you using? 5.2.4

**Which version of .NET are you using?5
calling signout from another razor client with Layout.cshtml and has not any cs file and cannot inject logout model to it 
Details : 
I need full steps with configuration settings in both client and identity server api 
and I am saving url logout Redirect in IDP database based on client id 
I tried to call it by get action logout directly but it give logoutid = null

**Comment by brockallen** [comment]
A client app uses the OIDC end session endpoint to initiate logout. Usually your client OIDC library provides a helper API (e.g. SignOutAsync on the HttpContext in ASP.NET):

https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/end_session/

Once IdentityServer receives this proper OIDC end session request, it will redirect the user to the logout workflow described here:

https://docs.duendesoftware.com/identityserver/v6/ui/logout/

**Comment by HODACDWS** [comment]
And how to set calling redirect page for my client from database since logoutid is return null on calling

Sent from Android device

On Oct 24, 2022 6:21 PM, Brock Allen ***@***.***> wrote:

A client app uses the OIDC end session endpoint to initiate logout. Usually your client OIDC library provides a helper API (e.g. SignOutAsync on the HttpContext in ASP.NET):

https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/end_session/

Once IdentityServer receives this proper OIDC end session request, it will redirect the user to the logout workflow described here:

https://docs.duendesoftware.com/identityserver/v6/ui/logout/

**Comment by brockallen** [comment]
> And how to set calling redirect page for my client from database since logoutid is return null on calling

I'm not sure why it's null -- did the client send both id_token_hint and a valid post_logout_redirect_uri? If you think they did, then check the IdentityServer debug level logs to see what it says about them.

**Comment by HODACDWS** [comment]
How to set them in client

Sent from Android device

On Oct 24, 2022 10:09 PM, Brock Allen ***@***.***> wrote:

And how to set calling redirect page for my client from database since logoutid is return null on calling

I'm not sure why it's null -- did the client send both id_token_hint and a valid post_logout_redirect_uri? If you think they did, then check the IdentityServer debug level logs to see what it says about them.

**Comment by brockallen** [comment]
> How to set them in client

It depends on your client framework. I'll assume you use .NET Core -- we have our quickstart which shows setting these things up:

https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/

**Comment by HODACDWS** [comment]
I could compose a url for logout with correct taken hint since it calls Logout on calling it , but logoutid = null ,although TOKEN_ID_HINT
Is sent
Ex :
Href =https://localhost:44336/connect/endsession?id_token_hint=... &post_logout_redirect_uri=https://localhost:44386/Account/login<https://localhost:44336/connect/endsession?id_token_hint=...%20&post_logout_redirect_uri=https://localhost:44386/Account/login>
I need to know how to send logout id correctly and never get null on calling for it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by HODACDWS** [comment]
This is my way for calling from razor
var accessToken =  ViewContext.HttpContext.GetTokenAsync("id_token").Result.ToString();//ViewContext.HttpContext.().Result.ToString();
                                                        var Url = "https://localhost:44336/connect/endsession?id_token_hint=" + accessToken + "&post_logout_redirect_uri=https://localhost:44386/Account/login";

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Hoda El ***@***.***>
Sent: Tuesday, October 25, 2022 10:07 AM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [DuendeSoftware/Support] calling signout from another razor client with Layout.cshtml and has not any cs file and cannot inject logout model to it (Issue #287)

I could compose a url for logout with correct taken hint since it calls Logout on calling it , but logoutid = null ,although TOKEN_ID_HINT
Is sent
Ex :
Href =https://localhost:44336/connect/endsession?id_token_hint=... &post_logout_redirect_uri=https://localhost:44386/Account/login<https://localhost:44336/connect/endsession?id_token_hint=...%20&post_logout_redirect_uri=https://localhost:44386/Account/login>
I need to know how to send logout id correctly and never get null on calling for it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by HODACDWS** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
From: Hoda El Kholy ***@***.***>
Sent: Tuesday, October 25, 2022 10:11:16 AM
To: DuendeSoftware/Support ***@***.***>; DuendeSoftware/Support ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [DuendeSoftware/Support] calling signout from another razor client with Layout.cshtml and has not any cs file and cannot inject logout model to it (Issue #287)


This is my way for calling from razor

var accessToken =  ViewContext.HttpContext.GetTokenAsync("id_token").Result.ToString();//ViewContext.HttpContext.().Result.ToString();

                                                        var Url = "https://localhost:44336/connect/endsession?id_token_hint=" + accessToken + "&post_logout_redirect_uri=https://localhost:44386/Account/login";



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows



From: Hoda El ***@***.***>
Sent: Tuesday, October 25, 2022 10:07 AM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [DuendeSoftware/Support] calling signout from another razor client with Layout.cshtml and has not any cs file and cannot inject logout model to it (Issue #287)



I could compose a url for logout with correct taken hint since it calls Logout on calling it , but logoutid = null ,although TOKEN_ID_HINT

Is sent

Ex :

Href =https://localhost:44336/connect/endsession?id_token_hint=... &post_logout_redirect_uri=https://localhost:44386/Account/login<https://localhost:44336/connect/endsession?id_token_hint=...%20&post_logout_redirect_uri=https://localhost:44386/Account/login>

I need to know how to send logout id correctly and never get null on calling for it



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by HODACDWS** [comment]
now after long trials . it reads PostLogoutRedirectUri  from database which is 
https://localhost:44386/signout-callback-oidc 
but it displayed as Black page it does not redirect to login

**Comment by brockallen** [comment]
> it reads PostLogoutRedirectUri from database which is
https://localhost:44386/signout-callback-oidc

Yes, this is the default used by the Microsoft OIDC handler in the client app. And you should not need to create the URL and redirect yourself -- that is done by the Microsoft code in your client app when you call SignOutAsync passing the scheme of the OIDC handler you have configured in the client app. These are features of the Microsoft framework for your client app using OIDC. I'd encourage you to read up on their docs and samples on how to use them. And linked above we have a quickstart that walks you through using it with IdentityServer. 

>  but it displayed as Black page it does not redirect to login

There needs to be code written on this page, as per our docs: https://docs.duendesoftware.com/identityserver/v6/ui/logout/

Please read thru those to understand all the moving parts -- logout is complicated. Also, we have a sample UI for this, so I'd encourage you to compare it working to the code you have:

https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI
or
https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI.AspNetIdentity

**Comment by josephdecock** [comment]
I'm closing this thread as it appears to be answered and hasn't seen activity in a week. If you need more help feel free to reopen this issue or create a new issue. Thanks!
