### ISSUE TITLE
Does KeyManagement work in a distributed system?

### ISSUE THREAD

**Issue by kikaragyozov** [DuendeSoftware/Support#288]
The following lines of code don't seem to fare well in a distributed system.
https://github.com/DuendeSoftware/IdentityServer/blob/420b08c412b8bbdd7e4034087bcccb01d61ff65e/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs#L159-L184

Am I missing something, or it's entirely possible that you end up creating multiple keys in your database or worse - end up having miss-aligned caches with your other nodes?

Later in the code, the nodes make consensus on using the oldest created key, but what happens with the other created keys?

**Comment by kikaragyozov** [comment]
> > The following lines of code don't seem to fare well in a distributed system.
> 
> There is a store that's used to share: https://docs.duendesoftware.com/identityserver/v6/data/operational/keys/
> 
> > Am I missing something, or it's entirely possible that you end up creating multiple keys in your database or worse - end up having miss-aligned caches with your other nodes?
> 
> This is why there's a delay with the _PropagationTime_ value (typically something like 2 weeks) to using the keys: https://docs.duendesoftware.com/identityserver/v6/reference/options/#key-management

The current implementation allows multiple servers to write to the database in the event they are racing, and then you have logic to ignore any of the newly created keys. I believe there is also code that later uses those created keys from the races, instead of trying to write to the store again?

Wouldn't it be much more simpler to code and maintain if you used the database's transaction functionality to mitigate the race to begin with, effectively never making more keys than needed and having to deal with anything else that comes as a side-effect to that?

You really only need to specify a time constraint which is supplied by your code to the database upon key creation, which specifies the amount of time needed since the last inserted key, in order for the key you're trying to insert to succeed?

**Comment by brockallen** [comment]
> The current implementation allows multiple servers to write to the database in the event they are racing

Yes, but given that we're just a framework and don't control the hosting, it's not easy for us to provide an all-encompassing solution. This is mitigated by the fact that it's perfectly fine to have multiple signing keys, and they are not put into use for some time. 

> Wouldn't it be much more simpler to code and maintain if you used the database's transaction functionality

Similar to the above, we abstract our stores and don't know what DB is being used. If you think there's something we could improve at our abstraction level to solve this, then we'd encourage that feedback. But if this is a more immediate problem for you, then I'd suggest you taking over the store implementation and control the behavior in the way that you need to.

**Comment by josephdecock** [comment]
I'm closing this thread as it appears to be answered and hasn't seen activity in a week. If you need more help feel free to reopen this issue or create a new issue. Thanks!
