### ISSUE TITLE
Examples for Desktop application authenticating via Browser

### ISSUE THREAD

**Issue by zzstuzor** [DuendeSoftware/Support#289]
Are there any examples of a desktop (e.g. WPF) application launching a browser to authenticate the user and then getting the authentication result back from the browser after success, or after it is closed?

Trying to implement SSO from my application so it can launch browser pages and have them use the existing cookies

**Comment by leastprivilege** [comment]
Have a look here:

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples
