### ISSUE TITLE
When do we need to refresh the cached discovery document response at the Client end?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#293]
**Which version of Duende IdentityServer are you using?**
v6.1.5

**Which version of .NET are you using?**
.NET 6

**Describe the question**
We will start caching the discovery document response at the client/services end. This point made me think about when we need to refresh the cache. Not sure when and how the response of the discovery document changes. 

Is there any document available to understand the discovery document changes? or could you please list and explain the scenarios where the Discovery document response modify?

**Additional context**

We are following the Identity model [document](https://identitymodel.readthedocs.io/en/latest/client/discovery.html#caching-the-discovery-document) to implement caching.

**Comment by leastprivilege** [comment]
The most common reason it might change would be rotation/update of keys.

**Comment by PratikPatel-Mtech** [comment]
@leastprivilege Thanks! Are there any reasons?

Also, for the key - we are using [Static Key configuration](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/#static-key-configuration) with the certificate and disabled key rotation. So, in our case, the key will be changed when the certificate changes, right?

**Comment by leastprivilege** [comment]
Right - but for security reasons keys should be regularly rotated.
