### ISSUE TITLE
Unable to use Redis Cache with Identity Server 6

### ISSUE THREAD

**Issue by Saldash** [DuendeSoftware/Support#295]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
.Net 6

**Describe the bug**
I'm unable to add Redis caching to `AddIdentityServer()` after upgrading from Identity Server 4 to Identity Server 6 as there don't appear to be any extensions able to provide it.

**Additional context**
I've upgraded an Identity Server 4 project to the latest version provided by Duende. Our previous version allowed us to add Redis cache to support operational data store and session store.
These options apparently don't exist in the latest version from Duende and the documentation page simply says coming soon.

How can I return to adding Redis support for our implementation so that we can leverage elastic cloud infrastructure where multiple instances of the application may be running.

Old version allowed us to use;
```c#
services.AddIdentityServer()
   .AddOperationalStore(options => {
      options.RedisConnectionString = Configuration.GetConnectionString("Redis");
      options.Db = 1;
   })
   .AddRedisCaching(options => {
       options.RedisConnectionString = Configuration.GetConnectionString("Redis");
       options.KeyPrefix = "custom_prefix";
   })
   .AddSigningCredential(new X509Certificate2(Path.Combine(HostingEnvironment.WebRootPath, "secretauth.pfx"), "secret_key"))
   .AddUserStore() // Custom User Store
   .AddResourceStore<CustomResourceStore>()
   .AddClientStore<CustomClientStore>();
```
The latest version, we can only seem to set;
```c#
services.AddIdentityServer(options =>
{
    options.LicenseKey = Configuration.GetValue<string>(key: "Duende.IdentityServer:licenseKey");
})
.AddSigningCredential(new X509Certificate2(Path.Combine(HostingEnvironment.WebRootPath, "secretauth.pfx"), "secret_key"))
.AddUserStore() // Custom User Store
.AddClientStore<CustomClientStore>()
.AddResourceStore<CustomResourceStore>();
```

**Comment by Polymeta** [comment]
If I recall correctly, the redis caching of operational data was not native in v4, but got added through a NuGet package, namely this one https://github.com/AliBazzi/IdentityServer4.Contrib.RedisStore - but it seems like it went stale and has not been brought up to speed with either v5 or v6.

I'm in the same boat as you are: I would like to migrate to v6, but currently we store our operational data in a redis cache.

Are they any plans to support operational data in a cache? Are there any plans for NuGet extensions to easily implement the behavior of the above package into v6? - I feel like it would be a step back for us to move from redis for operational data to the database.

**Comment by josephdecock** [comment]
> If I recall correctly, the redis caching of operational data was not native in v4

Correct, redis caching was never built in to IdentityServer.

> Are they any plans to support operational data in a cache? Are there any plans for NuGet extensions to easily implement the behavior of the above package into v6? - I feel like it would be a step back for us to move from redis for operational data to the database.

Operational data can be stored in whatever data store you like. To do so, you will need to implement the [IPersistedGrantStore ](https://docs.duendesoftware.com/identityserver/v6/reference/stores/persisted_grant_store/) interface (basically everyone needs this), and possibly the IServerSideSessionStore interface (only needed if you are using server side sessions) and the IDeviceFlowStore interface (only needed if you are using the device flow). IdentityServer ships with an EntityFramework implementation of all the data stores that can be used with any database that EF supports. There aren't any plans to add an officially supported Redis implementation of the stores.

FWIW, I've seen good results with storing operational data in Microsoft SQL, postgres, and others. But, if you want to use Redis go for it - the interfaces that you need to implement are pretty small.
