### ISSUE TITLE
Duende.AccessTokenManagement Support for refresh_token Grant Type

### ISSUE THREAD

**Issue by ritasker** [DuendeSoftware/Support#296]
I have started to use Duende.AccessTokenManagement to manage the tokens for a 3rd party API I am using.

My service initially stores an access token using the authorization_code grant type. Once the token has expired, using the ClientCredentialsTokenHandler, a request for a new token is made. Unfortunately, the request fails with an invalid grant type error because the API only supports regenerating access tokens using refresh tokens.

Is support for refresh tokens on the roadmap?

**Comment by josephdecock** [comment]
Refresh tokens are supported for user access tokens. Take a look at the docs for user access tokens [here](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/Customizing-User-Token-Management).
