### ISSUE TITLE
AccessTokenManagement handle refresh failures

### ISSUE THREAD

**Issue by natelaff** [DuendeSoftware/Support#297]
I brought this up previously in [IdentityModel ](https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/209) but it still pops up. Every so often, this library will refresh an already consumed refresh token, causing the refresh to fail. I do have custom logic in my IdentityServer that allows within 60 seconds if it's already been consumed, but the issue still pops up. So, the origin of that is a different topic... I am still at a loss of how to gracefully handle this.

Once I get into this state, the web app does not trigger reauthentication and I start getting some gnarly errors and your options are to clear cookies or go incognito.

It would seem like, in [here](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/blob/dffdd48f0c532a9db237d069f329ffb3c274a99f/src/Duende.AccessTokenManagement.OpenIdConnect/TokenManagementHttpContextExtensions.cs#L34) there should be some ability to optionally reject principal and sign out and challenge since its the only place to check for refresh token failure and have HttpContext access.

Am I over complicating this? I know from the previous referenced issue the stance is "Check for the 401" which I agree with, but doing that in a centralized place to check specifically for refresh token failure is not working out.

**Comment by brockallen** [comment]
Can you put a message handler on the HTTP client factory/HttpClient instances and do this yourself? That way it keeps our library still a bare bones framework and you still get the behavior you're looking for?

**Comment by natelaff** [comment]
Would it make sense to add the ability to add a handler just for the Oidc work and stay off of the API clients? this would allow asp.net core to handle the usual stuff, but we could register a handler to just deal with what happens in the auth chain?

**Comment by brockallen** [comment]
>  this library will refresh an already consumed refresh token

BTW, you know you should probably mark that client as allowing re-usable refresh tokens. It's a confidential client, the tokens are stored/protected properly (at least by default), and so it's totally reasonable to do it that way.

**Comment by natelaff** [comment]
Yes, I use the http client factory. I definitely get the wanting to keep this framework clean, there is just no way that I have found which allows for handling when the refresh fails. Its not like it just returns null and gracefully reauthenticates, it throws exceptions.

In a project without this package, you would handle the OnValidatePrincipal in CookieAuthenticationEvents (where you would handle the whole renew process) and if that refresh fails, you can log out and clean up and make them do it again. Doing anything gracefully with this package isn't possible without catching exceptions on any API call. Not ideal.

That's what I'm trying to help solve, unless I'm just totally missing something. When IS throws a 401 because the refresh failed, all hell breaks loose.

But on the same token (no pun intended) it's good to know I can just allow reusable in this situation, but I still feel like I've uncovered an issue here ;)

**Comment by brockallen** [comment]
> Its not like it just returns null and gracefully reauthenticates, it throws exceptions.

What throws exceptions? Do you have a call stack so we can better understand?

> there is just no way that I have found which allows for handling when the refresh fails

I guess the question is -- if the refresh fails, what's the action to take? I've been assuming the answer is to cause a Challenge to happen in the BFF so the response is a redirect to the token server. But that can't happen in an Ajax call from the JS to the BFF/remote API, because the Challenge would trigger a redirect on the ajax call and that won't work. You need the 401 to reavel all the way back to whatever UI layer, and then have a different request from the browser's top windows so that the redirect can work to the token server (more specifically the authorize endpoint). 

Maybe I'm missing something about what you're doing that doesn't line up with what I'm thinking in my head.

**Comment by natelaff** [comment]
Yes I suppose you're right on the Ajax-- I'm using it in MVC context so I guess I didn't consider that. The exceptions don't come from this package, its a result of things no longer being able to authenticate and it just unravels. That's where I mentioned you'd have to catch the 401 on every single API call.

It's really I suppose more of an ASP.NET Core issue than this package, but because I can solve it in ASP.NET Core WITHOUT this package (at least on the MVC side... Blazor and other types of apps I don't really know how all that auth works), it makes it seem like a weak spot here that I am trying to help solve. But maybe there is just no answer other than to not use this in my MVC app, which is a shame. I have just struggled with this one pain point since its inception.

The only thing I can possibly think to do is allow for an inner HttpClientFactory that you can catch these response codes and handle it appropriately in the app, but I get if that's not something you'd want to accept a PR on (assuming my theory is even correct)

**Comment by brockallen** [comment]
Yea, I think you should handle this sort of situation at the app level, given that it's an app specific decision how to handle. Thanks though for the conversation on the topic.
