### ISSUE TITLE
Duende BFF with angular working fine on localhost when deployed on subdirectory IIS bff/user unauthorized

### ISSUE THREAD

**Issue by ashrafalngar4** [DuendeSoftware/Support#298]
**Which version of Duende BFF are you using? latest version**

**Which version of .NET are you using? .net 6**

**Duende BFF with angular working fine on localhost when deployed on subdirectory IIS bff/user unauthorized but when deploye on root no problem happen **

A clear and concise description of what the bug is. this is startup

namespace TestBff
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            // In production, the Angular files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/dist";
            });

            var builder = services.AddReverseProxy()
                .AddTransforms<AccessTokenTransformProvider>();

            
            services.AddControllers();
            services.AddBff(options =>
            {
             
            }).AddEntityFrameworkServerSideSessions(options =>
                {
                    options.UseSqlServer("");
                }).AddRemoteApis();

            services.AddScoped<ILoggerBuilder, LoggerBuilder>();
     
            services.AddUserAccessTokenHttpClient("test", configureClient: client =>
            {
                //This is the address of the Mono API
                client.BaseAddress = new Uri($"http://localhost/sub/");
            });

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "cookie";
                options.DefaultChallengeScheme = "oidc";
                options.DefaultSignOutScheme = "oidc";
            })
               .AddCookie("cookie", options =>
               {
                   options.Cookie.Name = "__Host-bff";
                   options.Cookie.SameSite = SameSiteMode.Strict;
               })
               .AddOpenIdConnect("oidc", options =>
               {
                   options.Authority = "";
                   options.ClientId = "";
                   options.ClientSecret = "";
                   options.ResponseType = "code";
                   options.ResponseMode = "query";

                   options.GetClaimsFromUserInfoEndpoint = true;
                   options.MapInboundClaims = false;
                   options.SaveTokens = true;
                   options.AuthenticationMethod = OpenIdConnectRedirectBehavior.FormPost;

                   options.Scope.Clear();
                   options.Scope.Add("openid");
                   options.Scope.Add("profile");
                   options.Scope.Add("");
                   options.Scope.Add("offline_access");

                   options.TokenValidationParameters = new()
                   {
                       NameClaimType = "name",
                       RoleClaimType = "role"
                   };
               });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            var forwardingOptions = new ForwardedHeadersOptions()
            {
                ForwardedHeaders = ForwardedHeaders.All
            };

            forwardingOptions.KnownNetworks.Clear();
            forwardingOptions.KnownProxies.Clear();

            app.UseForwardedHeaders(forwardingOptions);

             
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            //app.UseHttpsRedirection();
            app.UseStaticFiles();
            if (!env.IsDevelopment())
            {
                app.UseSpaStaticFiles();
            }

            app.UseRouting();
            app.UseAuthentication();
            app.UseBff();

            app.UseAuthorization();

            app.UseMiddleware<LoggingMiddleware>();
            app.UseMiddleware<ExceptionMiddleware>();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapBffManagementEndpoints();

                endpoints.MapBffReverseProxy();

                // which is equivalent to
                endpoints.MapReverseProxy()
                    .AsBffApiEndpoint();

                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller}/{action=Index}/{id?}").AllowAnonymous();

            });

            app.UseSpa(spa =>
            {
             

                spa.Options.SourcePath = "ClientApp";
             
                if (env.IsDevelopment())
                {
                    spa.UseAngularCliServer(npmScript: "start");
                }
            });

        }
    }
}

**Comment by josephdecock** [comment]
When you get the unauthenticated result, is the __Host-bff cookie being included in the HTTP request?

**Comment by brockallen** [comment]
Oh, __Host cookies can't be used in a path, IIRC. Only at the root. Check the browser's error console to see if it's complaining about that.

**Comment by ashrafalngar4** [comment]
> When you get the unauthenticated result, is the __Host-bff cookie being included in the HTTP request?

No. _Host-bff cookie not included. also i note that cookie not created

**Comment by josephdecock** [comment]
Cookies prefixed with __host have a bunch of rules enforced by modern browsers, including (as Brock mentions above) that they not set a path attribute other than the root path. Since you're deploying to a subdirectory, probably your auth cookie's path is being set to that subdirectory, which conflicts with the __host prefix.

I would try explicitly setting the cookie path attribute of the cookie to "/" (`options.Cookie.Path = "/"`). Off the top of my head, I don't remember if that option will be overridden in this scenario, but if it doesn't work, just go ahead and remove the __path prefix from the cookie name.
