### ISSUE TITLE
PersistedGrants table data

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#299]
Hello everybody,
after a certain period of time (for example a month) is it possible to permanently delete expired articles? is there an automatic function that takes care of this cleaning and that allows you to set data retention criteria?

**Comment by josephdecock** [comment]
You can configure IdentityServer to automatically clean up grants with the `EnableTokenCleanup`, `TokenCleanupInterval`, and `TokenCleanupBatchSize `options. We show an example in the docs [here](https://docs.duendesoftware.com/identityserver/v6/data/ef/#operational-store).

If enabled, the token cleanup job will be run periodically and delete all _expired_ grants.

Some grants are one time use, and are marked as consumed after they are used. Token cleanup can delete grants that are consumed but not yet expired as well by setting the `RemoveConsumedTokens` flag.

If you have complex data retention criteria, you'll need to write custom code to describe those criteria, and run them periodically yourself. You could look at our [TokenCleanupHost ](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework/TokenCleanupHost.cs) for an example of how to set up an `IHostedService` (replacing our logic with your own criteria).

Some relevant docs are here:
- [Grant Expiration And Consumption](https://docs.duendesoftware.com/identityserver/v6/data/operational/grants/#grant-expiration-and-consumption)
- [Operational Store Options](https://docs.duendesoftware.com/identityserver/v6/data/ef/#operationalstoreoptions)

**Comment by pampua84** [comment]
Thank you very much for the prompt reply.
