### ISSUE TITLE
BFF - Possible to host BFF and UI separately?

### ISSUE THREAD

**Issue by janssensjeroen** [DuendeSoftware/Support#30]
Is it possible to host the BFF and UI separately? So we could host the UI on app.mydomain.com and the BFF on bff.mydomain.com. I think I can answer this question myself. I don't think it is possible, since the DefaultLoginService for example checks whether the return url is a local url and throws an exception when it is not local. But why is this?

**Comment by leastprivilege** [comment]
The default behavior is for protecting against open redirector attacks.

If you need more custom behavior you can override the login service.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
