### ISSUE TITLE
Refresh token expiration sliding lifetime

### ISSUE THREAD

**Issue by tomas877** [DuendeSoftware/Support#300]
Hello,
i have a client refresh token configured as follows:
```
                    RefreshTokenUsage = TokenUsage.ReUse,
                    RefreshTokenExpiration=TokenExpiration.Sliding,
                    SlidingRefreshTokenLifetime = 3600,
                    UpdateAccessTokenClaimsOnRefresh = true,
```
Also I have configured 
```
options.EnableTokenCleanup = true;                    
options.TokenCleanupInterval = 30;
```

When I log in a refresh token is created with creation_time T1 and expiration T1+ 1 hour (in UTC) and is persisted in DB persisted_grants table. 

After 30 second it cleans this token up. Why is that?

**Comment by josephdecock** [comment]
Do you have the RemoveConsumedTokens flag set? Is the token that gets cleaned up marked as Consumed in the database (that is, if you query the PersistedGrants table before the cleanup job runs, is the Consumed column non null?)

**Comment by tomas877** [comment]
Yes I have `options.RemoveConsumedTokens=true`

Consumed column remain null whole time. I just made a quick test. I did login procedure at 9:49:07 (czech prague timezone) which generate refresh token with
![image](https://user-images.githubusercontent.com/225507/199680270-71ad21cc-8be8-4528-a548-ece478f790b7.png)
After 30 seconds (which is my actual tokenCleanupInterval) this token is removed from persisted grants table.

**Comment by josephdecock** [comment]
I'm noticing that the creation time in the database is 8:47, yet you said you logged in at 9:47. Can you please double check the time stamps?

**Comment by josephdecock** [comment]
Sorry, I got confused by the times because your timezone is so close to UTC. IdentityServer does use UTC for its timestamps, and the cleanup job filters for expired tokens [using utc](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework.Storage/TokenCleanup/TokenCleanupService.cs#L132). I'll continue investigating.

**Comment by josephdecock** [comment]
One way this could be happening is if there is significant clock skew between your web and database servers. The exact behavior is going to be platform specific, but in my tests using Microsoft SQL, here's what I'm seeing:

The tokens get created in memory with their timestamp set on the web server with whatever the web server's clock says is utc now, and then the token is persisted to the database with that timestamp.

The cleanup job on the other hand makes a query that gets translated by EF into a query that includes the GETUTCDATE sql function:

```
SELECT TOP(@__p_0) [p].[Id], [p].[ClientId], [p].[ConsumedTime], [p].[CreationTime], [p].[Data], [p].[Description], [p].[Expiration], [p].[Key], [p].[SessionId], [p].[SubjectId], [p].[Type]
FROM [PersistedGrants] AS [p]

-- NOTE the SQL Function!
WHERE [p].[Expiration] < GETUTCDATE()

ORDER BY [p].[Expiration
```

So, if GETUTCDATE is returning inaccurate values on your sql server, the cleanup job will destroy records it shouldn't.

**Comment by tomas877** [comment]
I am using Oracle DB so I am unable to use GETUTCDATE SQL function. What is the code for Oracle altarnative? I can use 
`SELECT SYS_EXTRACT_UTC(SYSTIMESTAMP)UTC_SYS, SYSTIMESTAMP FROM DUAL;` which is returning
![image](https://user-images.githubusercontent.com/225507/199916425-3170c8f8-aca3-4b6a-9496-30cdd19b5b0c.png)
It looks correctly to me.

**Comment by josephdecock** [comment]
I don't know the specifics of what the Oracle EF provider generates, but you can tell EF to log the queries it generates and find out that way. You want to log Microsoft.EntityFrameworkCore.Database.Command at the information level. In serilog, that looks like this:
```
 builder.Host.UseSerilog((ctx, lc) => lc
        // Other serilog config omitted
        .MinimumLevel.Override("Microsoft.EntityFrameworkCore.Database.Command", LogEventLevel.Information))
```

**Comment by josephdecock** [comment]
Any update on this?

**Comment by tomas877** [comment]
Yes, I do some log digging and found out:
On first screen shot you can see that at 10:58:56 there was and sql command inserting token into db with CREATION_TIME 9:58:56 and EXPIRATION 10:58:56
![image](https://user-images.githubusercontent.com/225507/201639423-78d505c6-74e8-4103-a173-a932962d2e3d.png)

After that on 10:59:22 there is a select  selecting all tokens that has expiration before actual SYSTIMESTAMP which at that point is 10:59:22. 
![2](https://user-images.githubusercontent.com/225507/201643593-73150748-c9e3-4dff-b75a-326686716f76.PNG)

Its state is than changed to deleted:
![3](https://user-images.githubusercontent.com/225507/201644066-a2d5ca29-2281-4901-bc20-f1c6af354e70.PNG)

And delete from is executed:
![4](https://user-images.githubusercontent.com/225507/201644025-f3470fda-5f53-487a-86bd-e1f4604203b9.PNG)

Its state is finally changed to detached:
![5](https://user-images.githubusercontent.com/225507/201644168-2f5c2280-2cca-477b-a621-c4285c94a8e3.PNG)

So there is some issue it timestamp generating.

**Comment by tomas877** [comment]
No, last progress was obtaining the logs I shared in previous reply. Now I am not sure what are my possibilities to be able to investigate more to find the problem and solution.

**Comment by brockallen** [comment]
Since we can't repro this and I don't think there's anything we are able to do on this right now, we're going to close. If you have more info so we can take action, please let us know.
