### ISSUE TITLE
Unclear how to setup token delegation with BFF

### ISSUE THREAD

**Issue by eugene-rebedailo** [DuendeSoftware/Support#301]
**Which version of Duende BFF are you using?**
v6 (Nuget package v.1.2.3)

**Which version of .NET are you using?**
NET6

**Describe the bug**
This is mostly a question and not a bug.

There are no samples in the documentation or sample code on github that shows how to setup token delegation when using remote APIs HTTP forwarder.

```.MapRemoteBffApiEndpoint(...)``` can be configured to require access token of types ```User``` or ```Client``` but it is not really clear how the internals works with token exchange. I am able to propagate the User token that is acquired by using the sign-in process, but most of my remote APIs require acquisition of a delegated token based on the User token. Is there an additional extension point where I could plug in the token exchange?

**Comment by josephdecock** [comment]
The HTTP forwarder in the BFF is really designed with simplicity in mind. When you have more complex requirements (like token delegation), you need to [drop down into the YARP layer](https://docs.duendesoftware.com/identityserver/v6/bff/apis/yarp/). Then you can use YARP's [extension mechanisms](https://microsoft.github.io/reverse-proxy/articles/transforms.html) to do the token exchange. One thing to keep in mind is that you probably don't want to do token exchange on every request, so you'll want to consider caching of the exchanged tokens as well. 

In a future version of BFF, we will consider adding more extension points, such as the ability to describe programmatically how tokens should be acquired.

**Comment by Sen-Gupta** [comment]
I have hit this issue as well. Blazor WASM hosted, .Net 7.

We have a blazor hosted app, on www.mysite.com
The client connects to a hosted signalr application, signalr.mysite.com.


The client needs to connect SignalR client and it needs access token to build the connection.

We are getting IAccessTokerProvider as null in Dependency Injection.

 hubConnection = new HubConnectionBuilder()
             .WithUrl(NavigationManager.ToAbsoluteUri("/messageshub"), options =>
             {
                 options.AccessTokenProvider = async () =>
                 {
                     **var accessTokenResult = await tokenProvider.RequestAccessToken();**
                     accessTokenResult.TryGetToken(out var accessToken);
                     return accessToken.Value;
                 };
             })
            .Build();

Is there a way, we can get token while using Bff?

**Comment by Sen-Gupta** [comment]
Does this help?

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L38-L57

**Comment by josephdecock** [comment]
@Sen-Gupta - I don't think that this issue is the same as the delegation that is being described originally. The main design idea of the BFF pattern is to not expose tokens to the front end javascript. What you want to do instead is authenticate via the cookie. If you need more help, please open a separate issue - that helps us keep track of things and makes it easier for other folks to find answers. Thanks!
