### ISSUE TITLE
Getting 401 with valid sessions

### ISSUE THREAD

**Issue by LilitHakobyan** [DuendeSoftware/Support#303]
IdentityServer 6.1.1 and Duende BFF 1.2.3 with YARP 1.2.3 .
Projects are .NET6, Web UI with BFF host, Identity server, and API.

Sessions expiration is configured for 15 minutes in both the Identity server and BFF, and for both server-side sessions is configured.
and options.Authentication.CoordinateClientLifetimesWithUserSession = true;
In UI host using YARP reverse proxy to be able to call remote API and have using .WithAccessToken(TokenType.User) to pass the access token to api.
Based on the user activity calling connect/userinfo endpoint which is extending both Identity and user sessions.

Getting 401 when calling to API after 15 minutes of user activity during which the user fills some data but not calling to API (but I can detect that the user is active and I am calling connect/userinfo which extends both sessions ) .

How is possible to get 401 when both sessions are not expired?
Is it possible that sessions renewal doesn't renew the access token?
Do I need to do other configurations for token management?

**Comment by josephdecock** [comment]
In development mode, there is a diagnostics endpoint - `GET /bff/diagnostics` that will show your tokens. When you get into the state where you get the 401, try going there and then look at the token (paste it into http://jwt.ms) to see if the claims make sense (especially timeouts).

Also, can you describe how it is that you're making calls to the connect/userinfo endpoint?

**Comment by LilitHakobyan** [comment]
In development mode, this flow working as expected,  at this moment I am not sure what kind of trick I need to do to have /bff/diagnostics in the installed version.

The Web UI is written in React so from react calling BFF_BASE_PATH/connect/userinfo and in the UI host have YARP configurations which gets the call removes BFF_BASE_PATH prefix (WithTransformPathRemovePrefix(prefix: BFF_BASE_PATH)),  adds the token  (.WithAccessToken(TokenType.User)) and forwards it to the Identity server.

Is there a better way to extend both sessions through bff ? 
Before I did call bff/user?slide= true but this is not always guaranteed session extend for both sides.

**Comment by josephdecock** [comment]
The diagnostics endpoint is enabled when ASPNET_ENV is set to Development. Just a note, I would be cautious about turning it on in a production system, because it undoes most of the security benefits of the BFF (malicious script can get at tokens by making requests to the diagnostics endpoint).

**Comment by LilitHakobyan** [comment]
Got it, thanks.
Can you please respond to my other question about the session extend?

**Comment by josephdecock** [comment]
We have a page in our docs on this topic here: https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/. In general, I think your approach seems like it will work, but sometimes a simpler approach can also work, where you slide the identity server session when tokens are refreshed.

**Comment by LilitHakobyan** [comment]
Thank you, closing this question at this moment, will open it if there will be new details.

**Comment by LilitHakobyan** [comment]
The problem that caused this kind of behavior was related to the self-signed certificate case.

So we had a configuration for a self-signed certificate
` 
options.BackchannelHttpHandler = new HttpClientHandler
                        {
                            ServerCertificateCustomValidationCallback = (_, _, _, _) => true
                        };
` 
and because of this, we were able to get a token from the token endpoint, but the token refresh didn't work because as I got from the BFF code base it uses  Backchannel for refresh and not BackchannelHttpHandler,
so added 
`
services.AddHttpClient(AccessTokenManagementDefaults.BackChannelHttpClientName, _ => { })
.ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler
                {
                    ClientCertificateOptions = ClientCertificateOption.Manual,
                    ServerCertificateCustomValidationCallback = (_, _, _, _) => true
                });
`

Hope this will help those who will have this kind of problem in the future.
