### ISSUE TITLE
tenant passed in the acr_values not getting auto-populated

### ISSUE THREAD

**Issue by VijayKaravadra** [DuendeSoftware/Support#307]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0.5

**Question**
As described in [the docs](https://docs.duendesoftware.com/identityserver/v6/ui/login/session/#well-known-claims-issued-from-the-login-page), the tenant passed in the acr_values should be auto-populated. But, it's not being populated. Do we need to populate it manually?

**Comment by josephdecock** [comment]
What value are you sending in the acr_values parameter?

**Comment by VijayKaravadra** [comment]
> What value are you sending in the acr_values parameter?

I'm setting tenant to "uc" string value.

**Comment by josephdecock** [comment]
I just want to double check that the acr values are formatted correctly. Is the parameter value being set to idp:uc? Have you set IdentityProviderRestrictions on your client? See our docs on how that setting here: https://docs.duendesoftware.com/identityserver/v6/reference/models/client/

**Comment by josephdecock** [comment]
Any update on this?

**Comment by VijayKaravadra** [comment]
@josephdecock I didn't get a chance to check this, closing this for now. I'll check the things shared by you and reopen the ticket if needed. Thanks!
