### ISSUE TITLE
System.OutOfMemoryExceptions after update from IdentityServer4 v3 to IdentityServer v6

### ISSUE THREAD

**Issue by TdvxDanBlumenfeld** [DuendeSoftware/Support#308]
**Which version of Duende IdentityServer are you using?**
IdentityServer 6

**Which version of .NET are you using?**
.NET6.0 ASP.NET App Service, hosted in Azure

**Describe the bug**
Crashes and exceptions in a test environment after updating from IdentityServer4 v3.1.2 to IdentityServer 6, using the published [migration guides](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v3_to_dis_v6/) from v3 to v4 and v4 to v6

**Details**
Previously .NET Core 3.1, using IdentityServer4 v3.1.2
Databases upgraded using the SQL scripts extracted from the Entity Framework conversions from IdentityServer v3 to v4, then v4 to v6
Minimal source code updates for new namespaces and changed method signatures
Deployed to test environment 10/13/2022

After the update occurred, we're seeing infrequent service crashes (possibly infrequent because it's a low-volume test system), and frequent HTTP 500s

App Service Crashes
=====================
10/14 System.OutOfMemoryException
10/17 System.OutOfMemoryException
10/18 System.OutOfMemoryException
10/18 System.OutOfMemoryException
10/19 System.OutOfMemoryException
10/24 System.OutOfMemoryException
11/01 System.OutOfMemoryException
11/02 System.OutOfMemoryException
11/02 System.OutOfMemoryException
11/02 System.OutOfMemoryException
   *Call stack details vary slightly, but all appear to be in System.Threading.Thread.StartCallback() or System.Threading.Tasks.TaskExceptionHolder.Finalize()
See the attached crash dumps for details: [AzureAppServiceCrashDumps.zip](https://github.com/DuendeSoftware/Support/files/9929901/AzureAppServiceCrashDumps.zip)

App Service Exceptions
======================
Over the course of one day, 600 HTTP 500 requests out of 24,000 total (~2.5%), all of which seemed to be due to System.OutOfMemoryExceptions. Many of the failed requests are calls to a HealthCheck method, which does nothing other than return an OK()...however, calls to meaningful endpoints (such as Login) exhibit the same behavior.

At no point does the memory usage (average memory working set, memory working set, and private bytes) ever go above 300MB, and is fairly stable around 200MB. There are also no spikes in memory that correspond with the crashes or the exceptions, so I wonder if the OutOfMemoryException is accurate.

**Additional context**
Aside from namespace and minor method signature changes, the only significant code changes were in the addition of a TelemetryConfiguration instance to an AppInsightsEventSink class, and changes to the Startup.cs. See the attached diff screenshots for details.
![AppInsightsEventSink_DIFF](https://user-images.githubusercontent.com/104084456/199743717-0152c3d9-1e14-4dd7-b3d1-525905c22c18.png)
![Startup_DIFF](https://user-images.githubusercontent.com/104084456/199744139-20021e32-3768-48f4-84c9-5e217c8194b5.png)

**Comment by TdvxDanBlumenfeld** [comment]
(As an aside: I inherited the prior working system recently, but had no involvement in it until the need for the upgrade to v6 became apparent; nor do I have any experience with IdentityServer or related technologies and standards. So I apologize in advance if I lack some of the fundamental knowledge that would make this problem easier to diagnose)

**Comment by TdvxDanBlumenfeld** [comment]
System.IdentityModel.Tokens.Jwt has been updated to latest stable; AppInsights was already updated. I'll let the test service run for the next day or so and review the results.

Thanks for the suggestion, @josephdecock

**Comment by TdvxDanBlumenfeld** [comment]
I'm sorry to say that, after updating System.IdentityModel.Tokens.Jwt, we're still seeing the same errors in the same proportions in the test service.

**Comment by josephdecock** [comment]
Ok, thanks for giving that a try and for the detailed report. We'll do some more investigation and get back to you.

**Comment by josephdecock** [comment]
@TdvxDanBlumenfeld, I think the best way forward is for you to reproduce the issue while collecting memory usage information, and then use that to determine where memory is leaking - it could be IdentityServer, but it also could be ASP.NET, EF, your code, or some other dependency. Microsoft has good documentation on how to collect memory usage counters, generate memory dumps, and analyze the results [here](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak).

**Comment by josephdecock** [comment]
Any updates on this?

**Comment by josephdecock** [comment]
I'm going to close this issue for now, but if you are able to provide more detailed memory usage info, please feel free to reopen.
