### ISSUE TITLE
Deploy to Internet Information Services (IIS)

### ISSUE THREAD

**Issue by daniel06142** [DuendeSoftware/Support#309]
**Which version of Duende IdentityServer are you using?** 6

**Which version of .NET are you using?** .NET 6

Hi,

I have deployed the following applications to IIS (on same server):

- My identity server
- An MVC application

I can successfully navigate to the home page of the MVC application as I am not requiring authentication here.
When I try to navigate to a page that does require authentication, I am successfully redirected to identity server for login.
However after login, when I am redirected back to the MVC application, it doesn't redirect me back to the page I originally tried to access. Instead it redirects me back to the home page. When I try to navigate to the page that I had originally tried to access (i.e. the page that does require authentication), I am redirected to the home page again.

From the MVC application it looks like the user was not logged in from identity server. To check for this I navigated to my identity server and it is indicating the correct user as logged in.
Therefore it looks like identity server is not sending anything back to the MVC application to indicate a successful login, which would explain why when I try to access the page that does require authentication, it doesn't work.

**All of what I have described above does not happen when running identity server and mvc application on localhost, it works perfectly in that case**

**Please note as well:** The MVC application and Identity Server are both deployed to same server, currently the server is not setup to allow for https. Therefore the OpenIdConnect authority link uses http and also the client RedirectUris and PostlogoutRedirectUris use http as well. Whereas when running locally all links are using https, I am not sure if this would have an impact.

The server I am referring to will be setup to allow for https but this is out of my control and have to wait for now.

In the MVC application where I am adding OpendIdConnect I am setting the following to false:
options.RequireHttpsMetadata = false;

Many Thanks in advance

Daniel

**Comment by josephdecock** [comment]
One thing that might be going on here is that the session cookies (both IdentityServer's and/or the application's) might be rejected by the browser if their name is prefixed with __host. That name prefix tells the browser to enforce a bunch of rules, including that the cookie path can't be set to anything other than the root. If you're deploying multiple sites to IIS at different paths, the cookie path can get set automatically to the site path, which conflicts with the __host restriction.

**Comment by daniel06142** [comment]
Hi @josephdecock 

Thank you for timely response again.

How do I resolve the _host prefixing issue?

Kind Regards

Daniel

**Comment by daniel06142** [comment]
So I checked the cookies in chrome by pressing f12 and navigating to the Application tab.

There were no cookies present for MVC application.

The following cookies where present for the Idenitity Server application. (The names are not prefixed with _host)

<img width="171" alt="image" src="https://user-images.githubusercontent.com/117294241/200006872-fadcc963-f11f-4b35-923f-b2a29804cdce.png">

**Comment by josephdecock** [comment]
The absence of the MVC application's cookie is the smoking gun that you should focus on. Watch the network traffic during a handshake. You should see a callback into your MVC application, and its response will attempt to set the auth cookie. Your dev tools will often be able to tell you why the auth cookie was rejected. There also might be warnings on the developer console.

**Comment by daniel06142** [comment]
Hi @josephdecock ,

This has now been resolved.
It was the fact that we didn't have https setup on the server.
An SSL certificate has been added and its all working now.

I am not sure as to why it wouldn't work with http, does identity server only work with https?

What do you need in order for it to work via http? (Just for reference and improve my knowledge on identity server)
