### ISSUE TITLE
Access Token Validation in .Net Framework 4.8/OWIN based projects

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#31]
@leastprivilege 

we have two projects with hard dependencies on other 3rd party libraries, that we can not replace, and the vendors of those libraries will stay of .Net Framework 4.8 for a quite while. So, we have to stay on .Net Framework 4.8 and OWIN on those projects.

Can you give me recommendation which NuGet package should we use in those projects to be able to validate access tokens, that is compatible with Duende Identity Server, something like IdentityServer3.AccessTokenValidation?

Thank you and best regards,
Novak

**Comment by leastprivilege** [comment]
Katana ships with a JWT authentication middleware. That's what I would use - make sure to upgrade to their latest 4.x versions.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by No1e** [comment]
Thank you very much!
