### ISSUE TITLE
Refresh token option - UpdateAccessTokenClaimsOnRefresh - does not refresh access token claims

### ISSUE THREAD

**Issue by andreuwz** [DuendeSoftware/Support#312]
**Which version of Duende IdentityServer are you using?**
6.1.7
**Which version of .NET are you using?**
.NET 6.0
**Describe the bug**
UpdateAccessTokenClaimsOnRefresh  = true does not refresh newly created access token claims.
UpdateAccessTokenClaimsOnRefresh  = true does not refresh newly created access token claims.
Here is a snippet of my Client configuration:
new Client
           {
            ClientId = "AngularClient",
            UpdateAccessTokenClaimsOnRefresh = true,
            AccessTokenLifetime = 60,
            AllowOfflineAccess = true,
            AbsoluteRefreshTokenLifetime = 259200,
            RefreshTokenUsage = TokenUsage.ReUse,
            AllowedCorsOrigins = new []
            {
                "http://localhost:4200",
                "https://localhost:7193"
            }
For example If I Issue a token with  claims, for User X, then I update his  claims  in a separate http request from the Db and after this use the refresh token with the option to issue new access token for User X with updated claims - the refresh token produces access token with claims without updating them.
If I manually create another access token - then the claims are properly extracted from the Db, converted into claims and put into the token. But, as I said, this process does not happen with refresh token.
I am relatively new to IS4, so maybe I am missing something.    

I tried experimenting with Refresh token lifetime- I experimented with  OneTimeOnly, because I thought - hm If I use the ReUse option the refresh token is stored with the access token as a pair, thus using the ReUsed refresh token will call the same access token. But, again no difference if it is OneTimeOnly or ReUse.     
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**
Update the access token claims
Update the access token claims
**Log output/exception with stacktrace**

```
data
```

**Additional context**

Maybe there is another condition or option I should enable in order to make it work?

**Comment by andreuwz** [comment]
Not really.
I am using the simplest configuration possible. Maybe it is needed to implement one of these interfaces in order for this to work?
If you want any additional code I will provide it.

**Comment by josephdecock** [comment]
Which claims where you expecting would be updated, and how are they getting into your tokens when you issue them without refresh?

**Comment by andreuwz** [comment]
`
internal class PasswordValidator : IResourceOwnerPasswordValidator
    {
        private readonly IIdentityRepository identityRepository;

        public PasswordValidator(IIdentityRepository identityRepository)
        {
            this.identityRepository = identityRepository;
        }
        public async Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
        {

            User user = await identityRepository.FindByNameAsync(context.UserName);

            List<string> roles = await identityRepository.GetUserRolesAsync(user);
            List<Claim> userClaims = new List<Claim>();

            userClaims.Add(new Claim("Id", user.Id));
            userClaims.Add(new Claim(ClaimTypes.Name, user.UserName));
            userClaims.Add(new Claim("Balance", user.Balance.ToString()));

            foreach (var role in roles)
            {
                userClaims.Add(new Claim(ClaimTypes.Role, role));
            }

            if (roles.Contains("MasterAdmin"))
            {
                userClaims.Add(new Claim("MasterAdmin", "true"));
            }

            if (roles.Contains("Administrator"))
            {
                userClaims.Add(new Claim("Administrator", "true"));
            }

            if (roles.Contains("RegularUser"))
            {
                userClaims.Add(new Claim("RegularUser", "true"));
            }

            context.Result = new GrantValidationResult(subject: user.Id, authenticationMethod: "password", claims: userClaims);
        }
    }
`

This is how I issue a brand new access token.
I use ASP.NET Identity to find my user, then extract certain params, which are inserted as claims.
Currently I put the roles in 2 different ways, because I am testing something, so don't let that bother you.

Other than that, my updated claims are extracted from the DB. For example the Balance or Role claim values should be extracted from the Db.
And in my front end app - I store the refresh token and access token within an encrypted cookie. When I pass them back to the back end I check if the access token is expired. If it is - then use the refresh token with the option to update the claims, to issue new access token. If it is not expired - use the already created access token.
And as you can see the user has Role/ Balance claim. These values are susceptible of change. 
The problem is, as I said, that when the user's balance and roles values are updated in the db and when his access token expires, the refresh token only updated the expiration, not the claims.

**Comment by andreuwz** [comment]
`
public async Task<TokenModel> IssueIdentityToken(string username, string password)
        {
            var client = clientFactory.CreateClient();
            var getIdentityTokenUrl = "https://localhost:7268/connect/token";

            var tokenAccessParams = new List<KeyValuePair<string, string>>();

            tokenAccessParams.Add(new KeyValuePair<string, string>("grant_type", "password"));
            tokenAccessParams.Add(new KeyValuePair<string, string>("username", username));
            tokenAccessParams.Add(new KeyValuePair<string, string>("password", password));
            tokenAccessParams.Add(new KeyValuePair<string, string>("client_id", "AngularClient"));
            tokenAccessParams.Add(new KeyValuePair<string, string>("client_secret", "Arhs!"));
            tokenAccessParams.Add(new KeyValuePair<string, string>("scope", " offline_access Identity.API Catalogue.API Cart.API"));

            using (client)
            {
                var request = await client.PostAsync(getIdentityTokenUrl, new FormUrlEncodedContent(tokenAccessParams));
                var response = await request.Content.ReadAsStringAsync();

                return await GetFormattedAndSecuredJson(response);
            }
        }
`
This is the initial access token issuing method.

**Comment by andreuwz** [comment]
I implemented a separate ProfileService class and registered it as this `.AddProfileService<ProfileService>()`;
This is the concrete implementation:

`
internal class ProfileService : IProfileService
    {
        public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            context.IssuedClaims.AddRange(context.Subject.Claims);
        }

        public async Task IsActiveAsync(IsActiveContext context)
        {
            context.IsActive = true;
        }
    }
`

Still, the claims are not updated.

**Comment by josephdecock** [comment]
Your resource owner password validator code only runs the first time because the validation that token requests go through is determined by the grant type. You're on the right track with the profile service though - that _will_ be invoked when you refresh, so you can set new claims there. See our [docs](https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/) for more details.

In your initial request, you are using the password grant type, so the request is validated by a `ResourceOwnerPasswordValidator`. In subsequent requests, you are using the refresh grant type so the request is validated by an `IRefreshTokenService`. Even though the original token was issued by a password grant, that's not relevant here, because the protocol parameters don't say how the refresh token was obtained. All they say is that you want to _use_ the refresh token.

**Comment by andreuwz** [comment]
Thank you. I made custom implementation of the method public async Task GetProfileDataAsync(ProfileDataRequestContext context) and I fixed my problem.

Can you advise again on one last thing - I want to change my grant type to ClientCredentials, since I do not need to validate against username/ password (using grant type ResourceOwnerPassword).

I changed my implementation to the following:

Issuing access token body:
` var getIdentityTokenUrl = "https://localhost:7268/connect/token";

            var tokenAccessParams = new List<KeyValuePair<string, string>>();          
            tokenAccessParams.Add(new KeyValuePair<string, string>("client_id", "AngularClient"));
            tokenAccessParams.Add(new KeyValuePair<string, string>("client_secret", "Arhs!"));
           tokenAccessParams.Add(new KeyValuePair<string, string>("grant_type", "client_credentials"));
            tokenAccessParams.Add(new KeyValuePair<string, string>("scope", " offline_access Identity.API Catalogue.API Cart.API"));`
            
Configuration:
`public static IEnumerable<Client> Clients => new List<Client>
        {
           new Client
           {
            ClientId = "AngularClient",
            AccessTokenLifetime = 30,
            AllowOfflineAccess = true,
            AbsoluteRefreshTokenLifetime = 259200,
            RefreshTokenUsage = TokenUsage.ReUse,
            UpdateAccessTokenClaimsOnRefresh = true,
            AllowedCorsOrigins = new []
            {
                "http://localhost:4200",
                "https://localhost:7193"
            },
 
            // no interactive user, use the clientid/secret for authentication
            AllowedGrantTypes = GrantTypes.ClientCredentials,
 
            // secret for authentication
            ClientSecrets =
            {
                new Secret("Arhs!".Sha256())
            },
 
            // scopes that client has access to
            AllowedScopes = { "Identity.API", "offline_access", "Catalogue.API", "Roles", "Cart.API" }
           }
        };

          public static IEnumerable<ApiScope> ApiScopes => new List<ApiScope>
          {
                new ApiScope("Identity.API", "Identity.API", new string[]{"Id", ClaimTypes.Name, "Balance",ClaimTypes.Role, "MasterAdmin", "Administrator", "RegularUser"}),
                new ApiScope("offline_access", "RefereshToken"),
                new ApiScope("Catalogue.API", "Catalogue.API", new string[]{"Id", ClaimTypes.Name, "Balance",ClaimTypes.Role, "MasterAdmin", "Administrator", "RegularUser"}),
                new ApiScope("Cart.API","Cart.API", new string[]{"Id", ClaimTypes.Name, "Balance",ClaimTypes.Role, "MasterAdmin", "Administrator", "RegularUser"})
          };`

And also the Client, the Scopes are registered in the Program.cs file (all is the same as the previous config). For some reason I get invalid scope all the time. No sure what is the reason behind this. Can you give me hints?

**Comment by josephdecock** [comment]
Glad to hear that the original issue is solved!

As for your second error, take a look at identity server's logs when you get the invalid scope. They should tell you exactly why the scope is invalid.

**Comment by andreuwz** [comment]
Thank you for the fast response. I will check what is the problem.
