### ISSUE TITLE
Add cancellation error on cancel.

### ISSUE THREAD

**Issue by btwyford** [DuendeSoftware/Support#314]
Hi, is it possible to extend the DenyAuthorizationAsync method to add a custom error?

I need to be able to return an error of authentication_cancelled when the user clicks cancel.

Thanks.

**Comment by brockallen** [comment]
We've always used access_denied, as that's in the spec and the closest error code that indicates that semantic.

**Comment by josephdecock** [comment]
Yes, and this is probably not something you'll be able to extend easily, because the representation of errors is an enum that captures all the spec-compliant errors.

**Comment by btwyford** [comment]
Great, thanks for your reply, I expected that answer :)
