### ISSUE TITLE
Configure BFF and IdentityServer with SPA on develop

### ISSUE THREAD

**Issue by gundogduhasan** [DuendeSoftware/Support#316]
Hi, 
Since this issue is closed https://github.com/DuendeSoftware/IdentityServer/issues/428 
I open a new similar issue. Sorry if i did something wrong.

I have the similar issue. I am using angular for SPA. Here is my configs;
BFF backend runs on http://localhost:50771

` services.Configure<AuthConfig>((Configuration.GetSection("IdentityServerSettings")));

            var authConfig = Configuration.GetSection("IdentityServerSettings").Get<AuthConfig>();

            services.AddAuthorization();
            services.AddBff();
            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "cookie";
                options.DefaultChallengeScheme = "oidc";
                options.DefaultSignOutScheme = "oidc";
            })
             .AddCookie("cookie", options =>
             {
                 // set session lifetime
                 options.ExpireTimeSpan = TimeSpan.FromHours(8);

                 // sliding or absolute
                 options.SlidingExpiration = false;

                 // host prefixed cookie name
                 options.Cookie.Name = "__Host-spa";

                 // strict SameSite handling
                 options.Cookie.SameSite = SameSiteMode.Strict;
             })
             .AddOpenIdConnect("oidc", options =>
             {
                 options.RequireHttpsMetadata = false;
                 options.Authority = authConfig.AuthorityUrl;
                 options.ClientId = "<spa-client-id>";
                 options.ClientSecret = "<spa-client-secret>";
                 options.ResponseType = "code";
                 
                 // query response type is compatible with strict SameSite mode
                 options.ResponseMode = "query";

                 // get claims without mappings
                 options.MapInboundClaims = false;

                 options.Scope.Add("role");
                 options.Scope.Add("openid");
                 options.Scope.Add("profile");
                 options.Scope.Add("<bff-api>");
                 options.Scope.Add("offline_access");
                 options.SaveTokens = true;
                 options.GetClaimsFromUserInfoEndpoint = true;
             });`
Configure part
`
 app.UseRouting();

            //app.UseCors("AllCors");
            app.UseAuthentication();

            app.UseBff();

            app.UseAuthorization();

            app.UseMiddleware<ExceptionLogMiddleware>();

            app.UseEndpoints(endpoints =>
            {
                var defaultBatchHandler = new DefaultODataBatchHandler();
                defaultBatchHandler.MessageQuotas.MaxOperationsPerChangeset = 10;

                endpoints.Expand().Select().Filter().OrderBy().Count().MaxTop(null);
                endpoints.MapODataRoute(
                    routeName: "<odata-route>",
                    routePrefix: "<odata-route>",
                    model: GetEdmModel(),
                    batchHandler: defaultBatchHandler
                    ).MapBffManagementEndpoints();
            });
`
BFF's spa project runs on localhost:4400,BFF's backend project runs on localhost:50771, identityserver works on localhost:5200
When i start request to 'bff/user' end point before login it's returns '401' as should be. But when i start request to 'bff/login' end point i am getting this error on debug 
'CORS request made for path: /connect/authorize from origin: http://localhost:4400 but was ignored because path was not for an allowed IdentityServer CORS endpoint'

The request address is
 '
http://localhost:5200/connect/authorize?client_id='spa-client-id'&redirect_uri=http%3A%2F%2Flocalhost%3A50771%2Fsignin-oidc&response_type=code&scope=openid%20profile%20role%20'bff-api'%20offline_access&code_challenge=nqs20wRFlZ2eX7MPb1_t34_H8R02oon1VJvLrGR1kjI&code_challenge_method=S256&nonce=638034982051904330.NGMwMTUzNTUtNDQ0YS00MGQwLTkwYzUtZGJmNDAxM2Q3ZTVhNWQwZTExODUtYzFlYi00N2YyLTg4MTktNmRiMDBjZjRkYTA1&state=CfDJ8GjV4rteP2NCot0f0GPOVye47BXEDQodgxffDNy8XlDUynAyesJ-Tk1NTQeGgQRanpbJIm9GLH4z-FGwrXfjmic0BAWbGGOW43uLv_npat1bOqvM7ETxfGdFBT5zvN7WZIB0WDldXJy8LPImCZNvIfjZj0PGvpdrqPLbRrs8hAhKwCtHTAsggmD2U8eUl7zsmkIexo4WUcgU8vMisUdwNE6yCTPUhAeDw8xiuqrvl6u_rlHerqiRCe_qH2JEQ7A2ygjWNZsJMngZ0VZrQYh4uLoKbHvbsqI4AfPu_GVf6vJzultmP1IRSVaP8mVopGxwVvzJP9q50rYLxPpKLG0FH15I8JqZqye1Ju3WDDNnqDF8gSwe1f_kmKuNhf-ak1RBKA&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.0.0
'
as you can see redirect uri in the request address is 'localhost:50771/signin-oidc' this address is BFF's api address. But my spa client redirect uri is 'localhost:4400/signin-oidc'.

My question is my SPA client address and BFF's backend address most be same address(as port, as domain)? I am already using identity server 4 with implict flow but since implict flow does not secure any more i have to upgrade to bff. But my backend project and spa runs on different sub domains  on production, and different ports on development. Soo long story short are my addresses(spa and backend) can be different while using BFF? If it's can be done, what am i missing? Many thanks for your help.

Best regards.

**Comment by damikun** [comment]
Maybe just your BFF does not have valid CORS list configured... Check that first if all domains are in CORS list in .net configurtaion...

**Comment by gundogduhasan** [comment]
Thank you very much your quick respose. I added all origins my backend like this;

-ConfigureServices part

            ```
services.AddCors(options =>
            {
                options.AddPolicy("AllCors",
                                  builder =>
                                  {
                                      builder.WithOrigins(new string[] { "http://localhost:5200", "http://localhost:50771", "http://localhost:4400" }) // the origin order is identity server, backend, spa
                                            .AllowAnyMethod()
                                            .AllowAnyHeader();
                                  });
            });
```

-Configure part
`app.UseCors("AllCors");`

But still i am getting same  cors error. I also added these origins IdentityServer database 'ClientCorsOrigins' table. But still same error.

**Comment by damikun** [comment]
By identtiyserver database you mean this in identityserver configurtaion ?

```
            // This is IdentityServer part
            serviceCollection.AddSingleton<ICorsPolicyService>((container) =>
            {
                var logger = container.GetRequiredService<ILogger<DefaultCorsPolicyService>>();

                return new DefaultCorsPolicyService(logger)
                {
                    AllowedOrigins = allowed_origins //List
                    //AllowAll = true
                };
            });
```

**Comment by gundogduhasan** [comment]
No. I am not using cors provider on identity server project. By identity server database mean is created by ef. ClientCorsOrigins table on of them. By the way currently i am working local devolopment environment right now. Here is a screen shot of my network tab. Maybe it's could help.
![network-tab](https://user-images.githubusercontent.com/28599201/200563128-c077cdee-2012-4fac-9533-72d0cce5023f.png)

I will try these configs you said and let you know. Many thanks.

**Comment by gundogduhasan** [comment]
I tried these configs and still same error as screen shot i just send

**Comment by damikun** [comment]
One more important think do you send with all requests from frontend the  X-CSRF' = 1  in header?

```
    headers: {
          "Content-Type": "application/json",
          'X-CSRF': '1'
        },
```

**Comment by gundogduhasan** [comment]
Yes. I already use these headers. Except content type, but i just added that too but still same error. Do you have any idea about BFF addresses can be different? Like backend site localhost:50771, and SPA(frontend) site localhost:4400. I am not asking a wrong question right? I just want to be sure.

**Comment by damikun** [comment]
Htw why you use http insted https? because secured cooky by identity server can be transfered only using https... just for info i saw all your requests are http...

**Comment by gundogduhasan** [comment]
I added `AllowCredentials()` to cors. Unfortunately nothing change. Interesting thing is in the login authorize address (with the error in screen shot) "redirect_uri" parameter is localhost:50771/signin-oidc which is my BFF's backend address. Should be localhost:4400/signin-oidc? Because that is my client address.

I am using http right now. I will try https instead http and let you know. Many thanks.

**Comment by gundogduhasan** [comment]
I changed SecurePolicy with CookieSecurePolicy.None just for testing to allow http requests but still same error. I think my problem's  answer is arround the "redirect_uri" parameter. Like i said my previous comment. But i don't know what it is.

**Comment by brockallen** [comment]
CORS is not the issue here, and generally you'd not have CORS enabled when using the BFF pattern. The design is that the SPA code (meaning any JS) and the backend for the SPA are all from the same logical host, secured by an authentication cookie issued by the BFF host.

You're fighting against this principle by splitting them into two separate hosts.

I'm sure there are different ways to do your local development, but from the browser's perspective you need to make the app seems like the same one. I'd think you'd need to do some sort of reverse proxy to make this work, and then have it know which traffic should be handled by the static file host for the SPA assets, and then the other traffic should be sent to the BFF host.

**Comment by gundogduhasan** [comment]
I am just asking for double check. Using BFF pattern like this backend localhost:50771, SPA localhost:4400 is wrong. Still if i want to use like this i have to use reverse proxy. This is for development environment. In production these addresses become api.project.com for backend, prod.project.com for frontend. Same thing, i have to use reverse proxy to accomplish that. Did i understand correctly?

**Comment by brockallen** [comment]
The BFF is meant to be a single server-side host for your SPA assets, as well as the code that manages the OIDC protocol requests and the session management with an authentication cookie.

A remote API is the host (separate from the BFF) that accepts access tokens for authentication, and you would have this if you have many different apps that needed to call the API, like the SPA/BFF, but also other web apps, possibly mobile apps, and/or another service somewhere calling the API as a server-to-server.

If you don't need other apps beyond the SPA calling the API, then you don't really need the API separate accepting access tokens. You can just have the API co-hosted with the BFF host and there are no access tokens involved. Your BFF host could still use OIDC to get the user logged in, but the Ajax calls from the SPA/JS to the backend would be using the cookie. 

You still have your development time problem of wanting to split the host for the SPA/JS assets separate from the backend that does OIDC and session management. I don't have a good solution for you other than some reverse proxy either separate from both, or one of the hosts being the reverse proxy to the other. I think the Visual Templates use the latter approach.

**Comment by gundogduhasan** [comment]
Please excuse my insistence. I am really trying to understand and find the best solutions. 

Currently I have an api with this address api.project.com.
And I have a SPA product.project.com with his address.

As I understand your comment I have two options.

Option one;
I have to combine these two project same on domain like product.project.com. API and SPA must be on the same address.

Option two;
Still, If I want to use api and spa separated, I have to use reverse proxy to accomplish this. 

Again so sorry my insistence. Many thanks for your replies.

**Comment by brockallen** [comment]
Let's start here:

> Currently I have an api with this address api.project.com.

How many apps need to call this API? If it's only one (the SPA) then I don't know why you need it to be hosted separate from the SPA. Maybe there's a reason, but you will have to think about why you're doing that.

**Comment by gundogduhasan** [comment]
Right now I have one spa app. But very close future there are be mobile apps and other spa apps

**Comment by brockallen** [comment]
> Right now I have one spa app. But very close future there are be mobile apps and other spa apps. Also some other business related reasons I need to separate api.

Ok, this then tells me that you do need the API hosted separate and it should accept access tokens for authentication. 

So the the next question is on your SPA and BFF host. Logically the SPA and BFF are in the same host, and the BFF pattern (and our BFF library) will help allow the SPA to call thru the BFF host and ultimately call the remote API (in the separate host) with an access token. 

But you mentioned about something about wanting to host them separate from one another for development. If you do this, then you'll have 3 hosts in dev: SPA, BFF, and API. But given the way the BFF library and architecture work, the BFF and SPA are meant to be in the same host. So if you want them to be separate then you have to use some reverse proxy to make them work together as if they are the same host.  That's what I tried to explain above.

**Comment by brockallen** [comment]
This is where I think you will need to figure it out for your working environment. I don't know how SPA developers like to code/host these days... I was just letting you know/understand the server-side mechanics needed to achieve what you wanted to.

**Comment by gundogduhasan** [comment]
Many many thanks for your replies. Its really helpful. I really wonder your opinion for very slightly new solution for my issue.

As a third option;

Can I consider my api.project.com as a remote api? And adding whole different new back end my spa. And doing all my old requests over my spa api  to api.project.com

**Comment by brockallen** [comment]
> Can I consider my api.project.com as a remote api?

yes, that API host is what we called a "remote API" in our BFF docs.

**Comment by gundogduhasan** [comment]
@brockallen I am really appreciate your helps. Thank you very much.

**Comment by brockallen** [comment]
No problem. We'll close this now. If you find a good setup for what you're trying to do, feel free to follow up here later on.
