### ISSUE TITLE
Why there is no `AddScopeStore`?

### ISSUE THREAD

**Issue by arisliang** [DuendeSoftware/Support#317]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
6.0

For in-memory version, there're both `AddInMemoryApiResources`, `AddInMemoryApiScopes`.

But for the store version, there's only `AddResourceStore`, but no corresponding `AddScopeStore`. Is there any reason for not having it?

**Comment by josephdecock** [comment]
The resource store is responsible for api resources, identity resources, and scopes. 

The in memory configuration get convenience methods for each of those, but the more general abstraction works on all of them.
