### ISSUE TITLE
RFC 6750 client_id is missing or too long error?

### ISSUE THREAD

**Issue by tomfanara** [DuendeSoftware/Support#319]
**Which version of Duende IdentityServer are you using?**

6.1.7

**Which version of .NET are you using?**

.Net 6.0

**Describe the bug**

When using RFC 6750 2.1.1 Authorization Request Header Field and a GET method using http://myidentityserver/connect/authorize as in the example

     GET /resource HTTP/1.1
     Host: server.example.com
     Authorization: Bearer mF_9.B5f-4.1JqM

I get the following errors in my logs

[03:36:42 Information] Microsoft.AspNetCore.Hosting.Diagnostics
Request starting HTTP/1.1 GET http://alegeushandsonsession4identity/connect/authorize - -

[03:36:42 Information] Duende.IdentityServer.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.AuthorizeEndpoint for /connect/authorize

[03:36:42 Error] Duende.IdentityServer.Validation.AuthorizeRequestValidator
client_id is missing or too long
{"ClientId": null, "ClientName": null, "RedirectUri": null, "AllowedRedirectUris": null, "SubjectId": "anonymous", "ResponseType": null, "ResponseMode": null, "GrantType": null, "RequestedScopes": "", "State": null, "UiLocales": null, "Nonce": null, "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "", "MaxAge": null, "LoginHint": null, "SessionId": null, "Raw": {}, "$type": "AuthorizeRequestValidationLog"}

[03:36:42 Error] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
Request validation failed

[03:36:42 Information] Duende.IdentityServer.Endpoints.AuthorizeEndpoint
{"ClientId": null, "ClientName": null, "RedirectUri": null, "AllowedRedirectUris": null, "SubjectId": "anonymous", "ResponseType": null, "ResponseMode": null, "GrantType": null, "RequestedScopes": "", "State": null, "UiLocales": null, "Nonce": null, "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "", "MaxAge": null, "LoginHint": null, "SessionId": null, "Raw": {}, "$type": "AuthorizeRequestValidationLog"}

[03:36:42 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /connect/authorize responded 302 in 1.4458 ms

[03:36:42 Information] Microsoft.AspNetCore.Hosting.Diagnostics
Request finished HTTP/1.1 GET http://alegeushandsonsession4identity/connect/authorize - - - 302 0 - 28.5934ms

Using Azure APIM API Gateway inbound policy wanting to protect a backend endpoint I have the following markup

	<send-request mode="new" response-variable-name="tokenstate" timeout="20" ignore-error="true">
		<set-url>http://alegeushandsonsession4identity/connect/authorize</set-url>
		<set-method>GET</set-method>
		<set-header name="Authorization" exists-action="override">
			<value>@($"Bearer {(string)context.Variables["token"]}")</value>
		</set-header>		
	</send-request>

Steps to reproduce the behavior.

1. Create a API in Azure APIM API Gateway
2. Add an operation as a get
3. Add an in bound policy as shown above 
4. Get a token from Duende and add it as a bearer token and send it to the gateway
5. Observe the Duende logs

Should get a response as per RFC 6750

     HTTP/1.1 401 Unauthorized
     WWW-Authenticate: Bearer realm="example"

I would expect if authorized to receive an http 200 code 

```
data
```

**Additional context**

**Comment by brockallen** [comment]
Maybe dup of this: https://github.com/DuendeSoftware/Support/issues/257?

**Comment by josephdecock** [comment]
The errors in the logs indicate that you're not sending any of the parameters that the authorize endpoint expects, and your apim configuration seems to be making a call to identity server's authorize endpoint.

> Should get a response as per RFC 6750
> 
>>  HTTP/1.1 401 Unauthorized
>>  WWW-Authenticate: Bearer realm="example"
> 

> Get a token from Duende and add it as a bearer token and send it to the gateway

This doesn't apply  to the /authorize endpoint. /authorize isn't a protected resource that requires authentication, it is used as part of various flows to obtain tokens.

**Comment by josephdecock** [comment]
I believe there was a followup question asked here: https://github.com/DuendeSoftware/Support/issues/328, so I'm closing this.

**Comment by tomfanara** [comment]
Thank you I think this gives us insight, a solution and yes APIM does have a built in JWT Validation form so we will go that route! Sorry for the lack of clarity but we are getting better at the vocabulary!

Sent from my iPhone

On Nov 16, 2022, at 3:37 PM, Joe DeCock ***@***.***> wrote:

﻿

Closed #319<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDuendeSoftware%2FSupport%2Fissues%2F319&data=05%7C01%7C%7C7a15fcdb4a364c86011108dac81ab916%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638042314341248746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X2yEboqzRtnuKrOmmQwXaAuTWRfqvuZ1awev1UjGbCc%3D&reserved=0> as completed.

**Comment by josephdecock** [comment]
Great, thanks!
