### ISSUE TITLE
Is there any way to expose an array of strings with a single array element as a claim value in the JWT token?

### ISSUE THREAD

**Issue by VijayKaravadra** [DuendeSoftware/Support#32]
**Which version of Duende IdentityServer are you using?**
v6.0.4

**Which version of .NET are you using?**
.NET 6

**Question**

Is there any way to expose an array of strings with a single array element as a claim value in the JWT token?

**Additional context**

1. We're able to achieve this using adding multiple claims with the same key of "role".
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022,
  "role": ["role1", "role2", "role3"]
}

2. When it has a single element then, is there any way to get this type of output same as standard claims like scope and amr?
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022,
  "amr": [
    "pwd"
  ],
  "scope": [
    "scope1"
  ]
  "role": [
   "role1"
  ]
}

**Comment by leastprivilege** [comment]
try adding the claim like this

```cs
new Claim("role", "[ 'role1' ]", IdentityServerConstants.ClaimValueTypes.Json);
```

**Comment by VijayKaravadra** [comment]
Thanks, @leastprivilege! It worked. 

However we needed to use - new Claim("role", "[ \"role1\" ]", IdentityServerConstants.ClaimValueTypes.Json);

Alternate solution -

new Claim("role", JsonSerializer.Serialize(user.Roles), IdentityServerConstants.ClaimValueTypes.Json);
