### ISSUE TITLE
about dependencies with Microsoft.AspNetCore.Identity.EntityFrameworkCore

### ISSUE THREAD

**Issue by neozhu** [DuendeSoftware/Support#322]
as I know, the dependencies are Microsoft.AspNetCore.Identity.EntityFrameworkCore(ver 6-7) -> Duende.IdentityServer ->  AutoMapper(<12 not support latest version 12)

The current .net 6 or .net7 cannot use the latest version with Microsoft.AspNetCore.Identity.EntityFrameworkCore  , it's working on  Duende.IdentityServer(6.0.4) and AutoMapper(11.0.1)

Can anyone give a solution

**Comment by josephdecock** [comment]
Can you please clarify this question? It sounds like you're having a dependency problem, but I'm not following what the issue is, sorry.

**Comment by neozhu** [comment]
Duende.IdentityServer depends on AutoMapper ver >=11 <12 , now as we know the AutoMapper  latest version is 12.0.0.
I want to upgrade AutoMapper to ver 12.0.0. 
My suggestion is it's better to remove this dependency (automapper)

**Comment by josephdecock** [comment]
We are moving up to version 12 of AutoMapper in the 6.2 release, which is coming very soon - we just published a release candidate last week. Check it out!

**Comment by neozhu** [comment]
thank you
