### ISSUE TITLE
How to handle Unauthorized Request => Redirect loop

### ISSUE THREAD

**Issue by cliffi30** [DuendeSoftware/Support#323]
We came across a problem using OAuth and OpenIdConnect to restrict authorization for an authenticated user on our .net 4.8 client. The User is authenticated successful after logging in on the identity server. He is then redirected to the client application (net4.8), all works fine. However on the client we add (or don't add) client specific claims to the identity of the user, depending if he meets some criteria. The problem happens if we use the standard Authorize(Role = "XY") attribute on a controller and if the user doesn't belong to that role.
In such a case the user is being redirected back to the identity server and then ends up in a loop as the identity server confirms his authentication and redirects to the client again which in return will redirect to the identity server again...until the browser complains that there are too many redirects. 

We managed to overcome the problem by using a custom attribute witch implements the standard AuthorizationAttribute and overriding the HandleUnauthorizedRequest method.

`protected override void HandleUnauthorizedRequest(AuthorizationContext filterContext)
        {
            base.HandleUnauthorizedRequest(filterContext);
            Console.WriteLine(filterContext.HttpContext.Request.IsAuthenticated);

            if (filterContext.HttpContext.Request.IsAuthenticated)
            {
                filterContext.Result =
                    new RedirectToRouteResult(new RouteValueDictionary(new
                        { controller = "Error", action = "NotAuthorized", area = string.Empty }));
            }
            else
            {
                base.HandleUnauthorizedRequest(filterContext);
            }
        }`

My question therefore: Is this the standard and recommended way of handling this kind of situation. It seems odd that the standard solution ends up in an endless loop just because the user is not authorized on a specific controller despite the fact that he is authenticated. One would assume that the user is being redirected to the error page or a standard 401 page. Thanks for your sharing your thoughts on this.

**Comment by josephdecock** [comment]
Hi there,
What you've done looks correct to me. The OWIN authentication abstractions don't make a good distinction between authorization failures when the user is signed in or not. In ASP.NET Core, the authentication system has changed to represent those two states with methods to Forbid and Challenge, but back here in OWIN, we don't get that.
