### ISSUE TITLE
PostgresException: 42P01: relation "IdentityProviders" does not exist POSITION: 54

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#326]
**Which version of Duende IdentityServer are you using?**
Community

**Which version of .NET are you using?**
6.0

**Describe the bug**
Bump into this error and exception on line `var dyanmicSchemes = (await _identityProviderStore.GetAllSchemeNamesAsync())`. 

```
        var iservice = service.AddIdentityServer(options =>
        {
            options.Events.RaiseErrorEvents = true;
            options.Events.RaiseInformationEvents = true;
            options.Events.RaiseFailureEvents = true;
            options.Events.RaiseSuccessEvents = true;
            // see https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/
            options.EmitStaticAudienceClaim = true;
        });
        if (!useInMemoryDB)
        {
            service.AddDbContextPool<MyIAMDbContext>(options => options.UseNpgsql(configuration.GetConnectionString("Default")))
                    .AddDbContextPool<MyDbContext>(options => options.UseNpgsql(configuration.GetConnectionString("Default")));
            iservice.AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseNpgsql(configuration.GetConnectionString("Default"));
                }).AddConfigurationStoreCache()
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseNpgsql(configuration.GetConnectionString("Default"));
                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 3600; // interval in seconds (default is 3600)
                })
                .AddInMemoryCaching();
        }
        iservice.AddInMemoryIdentityResources(identityResources)
                .AddInMemoryApiScopes(apiScopes)
                .AddInMemoryClients(clients)
                .AddAspNetIdentity<MyUser>();
```

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by khteh** [comment]
No existing system. We have been using `UseInMemoryDatabase` with ASP.Net Core Identity. Just switched to PostgreSQL yesterday and saw this exception. What tables are missing?

**Comment by brockallen** [comment]
When you use the in-memory stores, there are warnings that inform you that you will need a persistent store for some of these things. We then have docs explaining what is needed: 

https://docs.duendesoftware.com/identityserver/v6/data/
https://docs.duendesoftware.com/identityserver/v6/data/ef/

**Comment by khteh** [comment]
I see `ConfigurationDb` and `PersistedGrantDb` in the migrations folder of `IdentityServer` project. However, I don't find in the docs how these 2 `DbContext`s are added to the DI so that I can create the same migrations again?

**Comment by josephdecock** [comment]
Take a look at the docs [here](https://docs.duendesoftware.com/identityserver/v6/data/ef/).

>For storing [configuration data](https://docs.duendesoftware.com/identityserver/v6/data/configuration/), then the configuration store can be used. This support provides implementations of the IClientStore, IResourceStore, IIdentityProviderStore, and the ICorsPolicyService extensibility points. These implementations use a DbContext-derived class called ConfigurationDbContext to model the tables in the database.
>
>To use the configuration store support, use the AddConfigurationStore extension method after the call to AddIdentityServer


>For storing [operational data](https://docs.duendesoftware.com/identityserver/v6/data/operational/) then the operational store can be used. This support provides implementations of the IPersistedGrantStore, IDeviceFlowStore, IServerSideSessionStore, and ISigningKeyStore extensibility points. The implementation uses a DbContext-derived class called PersistedGrantDbContext to model the table in the database.
>
>To use the operational store support, use the AddOperationalStore extension method after the call to AddIdentityServer

**Comment by khteh** [comment]
That's exactly what I do. See my original post.

**Comment by josephdecock** [comment]
The db contexts are registered when you call `AddConfigurationStore` and `AddOperationalStore`.

**Comment by khteh** [comment]
How do I add the initial migrations of these 2 dbcontexts?

**Comment by josephdecock** [comment]
We have a tutorial quickstart on using IdentityServer with EF [here](https://docs.duendesoftware.com/identityserver/v6/quickstarts/4_ef/).

**Comment by khteh** [comment]
How often does the schema change? How are we know that we need to create new migrations and update the DB?
