### ISSUE TITLE
How to manage refresh token updating from IDS v3 to Duende v6

### ISSUE THREAD

**Issue by vulcanik** [DuendeSoftware/Support#329]
Hello, I'm trying to update my application from IdentityServer 3 to 4.1.2 and then to Duende.IdentityServer 6 (.NET 6).
The problem I'm facing is releated to Refresh Tokens, even if the migration of the db works correctly (all the data are kept in the PersistedGrant table with the new columns) when I use the application soon after the update I am logged out and forced to login.
Login then works perfectly, new tokens are created but this means that - when I'll update in production my app - all the users are forced to login again. Is it possible to manage this scenario in some way? I want to update my IDS during the night avoiding users to login again in the morning.

**Comment by josephdecock** [comment]
This sounds like a problem with either your signing keys or data protection keys. Are you using automatic key management? Something like this:
```
var builder = services.AddIdentityServer(options =>
{
    options.KeyManagement.Enabled = false;
});
```

How are your data proectection keys configured?

**Comment by josephdecock** [comment]
Thanks, also, do you see any exceptions or errors logged from IdentityServer when refreshing fails? Could you please turn up the log level to debug, and share logs here? Thanks!

**Comment by josephdecock** [comment]
Any update on this?

**Comment by vulcanik** [comment]
Sorry to answer you late, I just forgot to update the thread.
The solution was to create a Console application able to read existing data on a v3 model, pass the values in a v6 model and save it again on db. A real migration tool. That worked.
