### ISSUE TITLE
How to configure dynamic oidc identity provider for Asp.Net Core Identity external callback

### ISSUE THREAD

**Issue by skoruba** [DuendeSoftware/Support#336]
**Which version of Duende IdentityServer are you using?**

6.1.2

**Which version of .NET are you using?**

6

**Describe the bug**

I cannot find a way how to properly configure dynamic OIDC provider in my DB and keep working it with my Asp.Net Core Identity external provider callback.

**To Reproduce**

I have tried to register new OIDC provider in my DB like this:

```
{
Scheme: "duende",
DisplayName: "Duende IS",
Type: "oidc",
Properties: {"Authority":"https://demo.duendesoftware.com","ClientId":"login", "Scope":"openid profile"}
}
```

In the ```AccountController``` is method called ```ExternalLoginCallback``` and there is used method from Asp.Net Core Identity [SignInManager.GetExternalLoginInfoAsync()](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L651). This method returns always null and I do not know why.

I have also tried to use static middleware like this and this works correctly.

```
builder.AddOpenIdConnect("duende", options =>
            {
                options.Authority = "https://demo.duendesoftware.com";
                options.ClientId = "login";
            });
```

Any idea please what is missing in my oidc provider in the db definition?

**Comment by josephdecock** [comment]
We have a sample of dynamic providers [here](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/UserInteraction/DynamicProviders) which might help.

When you define dynamic providers, I would expect that you retrieve the providers [using the `IIdentityProviderStore`](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/UserInteraction/DynamicProviders/IdentityServerHost/Pages/Account/Login/Index.cshtml.cs#L201).

**Comment by skoruba** [comment]
Thank you for the links. I am using `IIdentityProviderStore` but there is something what I missed in my oidc provider in the db, becaase it does not work. I cannot figure out what is missing. Any idea @brockallen? Thanks!

**Comment by josephdecock** [comment]
If your database query isn't returning a provider, you could look at the queries to understand why they aren't producing results. If you're using EntityFramework and serilog, you could log queries with something like this:

builder.Host.UseSerilog((ctx, lc) => lc
        // Other serilog config omitted
        .MinimumLevel.Override("Microsoft.EntityFrameworkCore.Database.Command", LogEventLevel.Information))

**Comment by skoruba** [comment]
Sorry, I was not clear, `IIdentityProviderStore` returns correct set of dynamic providers from the db, but the oidc flow after challenging the specific provider has been failed - [SignInManager.GetExternalLoginInfoAsync](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L651) - always returns null.

**Comment by josephdecock** [comment]
GetEternalLoginInfoAsync is probably returning null because it is expecting that the eternal login creates a cookie using the cookie auth scheme named `IdentityConstants.ExternalScheme`. So, when you sign in with your dynamic provider, you want to set the login scheme to `IdentityConstants.ExternalScheme`. 

I came upon a related issue on the ASP.NET Core Identity repo [here](https://github.com/dotnet/aspnetcore/issues/29772) that you may find interesting.

**Comment by skoruba** [comment]
I have already used `IdentityConstants.ExternalScheme` in the configuration of IdentityServer for dynamic providers - unfortunately it is still not working.

**Comment by skoruba** [comment]
I think there is some mapping issue, the method `GetExternalLoginInfoAsync` is looking for claim:
`var providerKey = auth.Principal.FindFirstValue("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")`
With default oidc dynamic definition claims do not have prefix `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/`.
I got these claims: 
![image](https://user-images.githubusercontent.com/35664089/202701408-edc18cff-4c29-4bf6-a981-0ddd45ed2482.png)

With default OpenIdConnect middleware - 
```
authenticationBuilder.AddOpenIdConnect("duendejan", options =>
            {
                options.Authority = "https://demo.duendesoftware.com";
                options.ClientId = "login";
            });
```
 I got these claims:
![image](https://user-images.githubusercontent.com/35664089/202701614-99faf88e-f9df-411c-ac60-49282baadc88.png)

Do you know @josephdecock what is required to set up for oidc dynamic provider if I want to get claims according to second screenshot?

Thanks!

**Comment by skoruba** [comment]
I have found it - it was property `context.AuthenticationOptions.MapInboundClaims = true`.
Thanks!
