### ISSUE TITLE
External Authentication With ADFS

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#340]
Hi! I'm trying to add an ADFS server as external authentication. Unlike the Google one in the quickstart examples I haven't found any extension helper methods to do this. I've used the following code from the duendesoft demo to try it:

        builder.Services.AddAuthentication()
            .AddOpenIdConnect("oidc", "ADFS", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                options.SaveTokens = true;

                options.Authority = "https://uktest.local/adfs/";
                options.ClientId = "Xxx.Yyy.Localhost";
                options.ClientSecret = "sdfsdfsdf";
                options.ResponseType = "code";
                options.Resource = "76e6347c-16cb-403b-a176-1850a8d57d2a";
                options.MetadataAddress = "https://uktest.local/adfs/.well-known/openid-configuration";

                options.TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role"
                };
            });

But when I click the button the page I receive on the ADFS server states:

 An error occurred. Contact your administrator for more information.
Error details

    Activity ID: 10adc5b4-6754-47c7-6702-0080030000ec
    Relying party: Localhost Xxx Yyy Secured by ADFS - Web Application
    Error details: MSIS9224: Received invalid OAuth authorization request. The received 'redirect_uri' parameter is not a valid registered redirect URI for the client identifier: 'Xxx.Yyy.Localhost'. Received redirect_uri: 'https://localhost/salesportalidentity/signin-oidc'.
    Node name: bbdcbecc-b3c9-42cb-b728-35d2dfa96ef0
    Error time: Thu, 17 Nov 2022 11:49:49 GMT
    Cookie: enabled
    User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

The client id is correct, I've proved it by modifying it and getting the appropriate error. I've added that redirect uri it complains about both with and without a trailing slash to the client entry in ADFS but no luck.

![image](https://user-images.githubusercontent.com/3273917/202440376-82263d17-ab3f-44b5-89fb-66cfc4701b51.png)

Any ideas on what could be wrong here? Do you have any examples of adding ADFS as an external authenticator I can use?

**Comment by josephdecock** [comment]
Sorry, we don't have an ASFS sample, but can you try using the 76e6347... guid as your client id?

```
options.ClientId = "76e6..."
```

**Comment by nhumby** [comment]
Hi @brockallen. Apologies for not responding yet, I've been prioritised with stabilising the IdentityServer6 implementation which is so far performing well. Thank you for the advice and clarification, I will give that a try.

**Comment by josephdecock** [comment]
Sounds good. I'll close this issue, but feel free to open a new issue if you need to.
