### ISSUE TITLE
How to avoid serving SPA before being authenticated.

### ISSUE THREAD

**Issue by mschaefer-gresham** [DuendeSoftware/Support#342]
Thank you for all your contributions. 

This is a general question about the BFF pattern. In your [template](https://damienbod.com/2021/12/06/blazor-wasm-hosted-in-asp-net-core-templates-with-azure-b2c-and-azure-ad-authentication-using-backend-for-frontend-bff/), and in several related examples based on the BFF pattern (see [yarp-auth-proxy](https://github.com/manfredsteyer/yarp-auth-proxy) and I could site others), the approach people seem to use is a variation of this (taken from Duende website):

```
function login() {
    window.location = "/bff/login";
}

function logout() {
    if (userClaims) {
        var logoutUrl = userClaims.find(claim => claim.type === 'bff:logout_url').value;
        window.location = logoutUrl;
    }
    else {
        window.location = "/bff/logout";
    }
}

```
There is a "userinfo" endpoint in the BFF that is used by the SPA to determine whether it should route to the /bff/login endpoint in the BFF. 

But this requires the SPA to be loaded into the browser. 

What if you don't want to load the SPA at all before the user authenicates? 

Can the BFF immediately redirect the user to login before ever returning any resource to the browser? Perhaps adding middleware along these lines:

```
app.Use(async (context, next) =>
{
    if (context.User?.Identity?.IsAuthenticated != true)
    {
        await context.ChallengeAsync();
    }
    else
    {
        await next();
    }
});
```

I've tried without success. 

Is your approach the only way this can work? Your thoughts would be appreciated.

**Comment by josephdecock** [comment]
I don't think in general you want to use middleware like this, because it makes it impossible to have any pages that are anonymous.

You might consider using lazy loading in your spa so that you don't load the majority of its code unless the user is authenticated. The exact technique for that is going to depend on your spa's architecture of course.
