### ISSUE TITLE
JWT generated has Invalid Signature in JWT.IO

### ISSUE THREAD

**Issue by tomfanara** [DuendeSoftware/Support#343]
**Which version of Duende IdentityServer are you using?**

6.1.7

**Which version of .NET are you using?**

.NET 6

**Describe the bug**

Maybe I am mis-using the tool but when I run myidentityserver/connect/token POST I get a token returned and I paste into jWT.IO and get Invalid Signature. 

**To Reproduce**

I am using Automatic Key Management in Duende and see the keys generated to file

run myidentityserver/connect/token POST and get the jwt

Paste following token in JWT.IO

eyJhbGciOiJSUzI1NiIsImtpZCI6IkVGMTE5RDk1QjU4NkQzQjREM0QzMUMwMUY2OEMwRDNFIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vYWxlZ2V1c2hhbmRzb25zZXNzaW9uNGlkZW50aXR5IiwibmJmIjoxNjY4OTU5NTYxLCJpYXQiOjE2Njg5NTk1NjEsImV4cCI6MTY2ODk2MzE2MSwic2NvcGUiOlsiYXBpMSJdLCJjbGllbnRfaWQiOiJjbGllbnQiLCJqdGkiOiIzNTYyMTVFQTBBNEI2NzEzMEJFNzVBRDdCM0MwQUUwMCJ9.c9P6SuC9zFbkQ24rHNQKrgezD-DGIc90O5ySenWz7UhgCaUr-3tvb7Stim7fyC5F5lpY07cBF08FAxokq0mAKJml1VWJdo4x6oPl68QLXliJgEXOIpklZjqKCfFOaeid8l9SDHEwQ3TCnwQKosi58LOO74hI6MlgLaV_9Kuri-lZB76qqaG8KGLT6IxDNBa_SQeHIO3Sut215qTIkO4gL6yH78Bw-QRVLgy7pfExs6vIWpD96l6KcE2XfdsvpJzEQ_2GVHHcl8zzLAu2mQCR3caaPAq6Zvd8pk76ul7nbgVgEs5R1kF6muCfx69ORbDX9foqOa4bZg72CV-eAC684g

**Expected behavior**

To be validated with it showing the validation keys for header and payload

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
That site can't validate your token unless you also let it know what the signing keys are. But to be honest, that site is mainly useful for simply decoding the payload and looking at the claims therein, not actually validating the token. What matters more is the API endpoint that you're calling and it will/should validate the token against the keys your token server has.

**Comment by tomfanara** [comment]
Hi thanks for the quick response. I am using Automatic Key Generation so I want to let it know the signing keys in JWT.IO. Do I get them from the files I see in my VS projects under the /keys folder? If so, what do I extract?

**Comment by tomfanara** [comment]
I am wanting to use JWT Verification on APIM under an inbound policy and it also requires a validation key as in

<validate-jwt header-name="Authorization" failed-validation-httpcode="401" failed-validation-error-message="Not authorized">
            <issuer-signing-keys>
                <key>123456781234567812345678</key>
            </issuer-signing-keys>
            <required-claims>
                <claim name="admin" match="any">
                    <value>true</value>
                </claim>
            </required-claims>
        </validate-jwt>

**Comment by brockallen** [comment]
> so I want to let it know the signing keys in JWT.IO

You should check their docs on how to input the keys into their tool. Normally any client gets the [public] key material from the discovery endpoint: https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/discovery/.

**Comment by brockallen** [comment]
> I am wanting to use JWT Verification on APIM under an inbound policy and it also requires a validation key as in

The discovery document is the standard/protocol approach for obtaining keys for validating tokens. Surely APIM has support for that? If not, then you'll need to load them yourself manually from the discovery document and configure them in APIM.
