### ISSUE TITLE
OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null'.

### ISSUE THREAD

**Issue by water-cmyk** [DuendeSoftware/Support#345]
I have an external client, that is configured like this:

.AddOpenIdConnect("oidc", "Demo FAS", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                options.Authority = "xxx";
                options.ClientId = "xxx";
                options.ClientSecret = "xxx";
                // Set response type to code
                options.ResponseType = "code";
                options.GetClaimsFromUserInfoEndpoint = true;
               // Configure the scope
                options.Scope.Clear();
                options.Scope.Add("openid");
                options.Scope.Add("profile");
                options.Scope.Add("egovnrn");
                options.Events = new OpenIdConnectEvents()
                {
                    OnRedirectToIdentityProvider = ctx =>
                    {

                        ctx.ProtocolMessage.AcrValues = "urn:be:fedict:iam:fas:Level500";
                        return Task.CompletedTask;
                    }
                };
                options.RequireHttpsMetadata = true;
        });

The identity server, goes correctly to the external provider, but after succesfull login with the external provider, when it comes back to the identity server I get the following error:
(raw exception details)
System.Exception: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Contacting the external provider, the request is send correctly and comes back correctly, anything I can do to resolve this?

**Comment by water-cmyk** [comment]
At the moment there are 2 different apps that are configured to login with the idp, they have their own redirect uri's. The redirect uri for the external provider is at the moment something in the line of https://URLOFIDP/signin-oidc. Is that incorrect. Should the redirect uri for the external provider be one of the uri's of the apps that are configured?

**Comment by josephdecock** [comment]
The /signin-oidc path looks right to me - that's the default path for the oidc handler, and you aren't changing it. As long as you only have 1 oidc handler registered, you should be fine. It really looks like something is going wrong at the external provider (despite them saying everything is correct).

**Comment by water-cmyk** [comment]
I enabled logging and discovered the following:

2022-11-28 11:30:02.628 +01:00 [DBG] Start authorize request protocol validation
2022-11-28 11:30:02.628 +01:00 [DBG] client configuration validation for client eVigilis.Admin succeeded.
2022-11-28 11:30:02.628 +01:00 [DBG] Checking for PKCE parameters
2022-11-28 11:30:02.629 +01:00 [DBG] Calling into custom validator: Duende.IdentityServer.Validation.DefaultCustomAuthorizeRequestValidator
2022-11-28 11:30:02.629 +01:00 [DBG] client configuration validation for client eVigilis.Admin succeeded.
2022-11-28 11:30:04.263 +01:00 [INF] AuthenticationScheme: oidc was challenged.
**2022-11-28 11:30:25.573 +01:00 [DBG] CORS request made for path: /signin-oidc from origin: https://idp.iamfas.int.belgium.be but was ignored because path was not for an allowed IdentityServer CORS endpoint**
2022-11-28 11:30:25.629 +01:00 [ERR] Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null', status code '400'.
2022-11-28 11:30:25.630 +01:00 [ERR] Exception occurred while processing message.

Is there a problem with the CORS request?

**Comment by josephdecock** [comment]
Yes, that's what that error means. We have docs on CORS [here](https://docs.duendesoftware.com/identityserver/v6/tokens/cors/). The simplest fix is to set the `AllowedCorsOrigins` on your client configuration.

**Comment by josephdecock** [comment]
However, it is strange to see that error at all! It seems like maybe you have an ajax call that is triggering an OIDC redirect unexpectedly. I would check into that as well.

**Comment by brockallen** [comment]
I think the CORS error is a red-herring. 

I'd suggest setting up your external handler and the resultant session cookie handler in a stand-alone ASP.NET Core project so you know that piece is working, then incorporate that into your IdentityServer host.

**Comment by josephdecock** [comment]
Any update on this issue? Are we good to close?

**Comment by water-cmyk** [comment]
Not yet, working on it. Waiting for an internal test url,

Van: Joe DeCock ***@***.***>
Verzonden: zaterdag 10 december 2022 7:13
Aan: DuendeSoftware/Support ***@***.***>
CC: Lobsien-Baumgart Nadine ***@***.***>; Author ***@***.***>
Onderwerp: /!\:Re: [DuendeSoftware/Support] OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null'. (Issue #345)


Any update on this issue? Are we good to close?

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDuendeSoftware%2FSupport%2Fissues%2F345%23issuecomment-1345151899&data=05%7C01%7Cnadine.lobsien-baumgart%40ibz.be%7Cb87c7c9a332b4ff5f33108dada759ffa%7C383c9b0036474e3dbd2cc97e4d780acd%7C0%7C0%7C638062496014160541%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vOd%2BIHubS3w1YgAxTpOaexPDWU8Vuu374l%2FZZg6hg5Q%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANDGOPNJVWKLWP37H7HI3MTWMQNPTANCNFSM6AAAAAASGQ6LU4&data=05%7C01%7Cnadine.lobsien-baumgart%40ibz.be%7Cb87c7c9a332b4ff5f33108dada759ffa%7C383c9b0036474e3dbd2cc97e4d780acd%7C0%7C0%7C638062496014160541%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BQ%2BLc%2FkbZzhHVn8ZNyhmkXhu39sz9LQ5Nswh%2FYbUx%2Fo%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>


⚠ CAUTION : Deze e-mail is afkomstig van buiten het IBZ-netwerk. Klik niet op links of open geen bijlagen tenzij u de afzender herkent en weet dat de inhoud veilig is.
Cet e-mail provient de l'extérieur du réseau IBZ. Ne cliquez pas sur les liens et n'ouvrez pas les pièces jointes à moins que vous ne reconnaissiez l'expéditeur et que vous sachiez que le contenu est sûr.

**Comment by josephdecock** [comment]
Closing this issue for now. Feel free to reopen if necessary.
