### ISSUE TITLE
 How do I know if the license is working?

### ISSUE THREAD

**Issue by fdagdagan** [DuendeSoftware/Support#347]
**Which version of Duende IdentityServer are you using?** 
6.1.7

**Which version of .NET are you using?**
6

Our company just bought a license, I upgraded to Duende and testing to our non-production environment. How do I know if the license is working?

Thanks!

**Comment by brockallen** [comment]
> How do I know if the license is working?

You should see a DEBUG log entry in summarizing the valid license information.

**Comment by fdagdagan** [comment]
I copied the Duende_License.key to the applications folder, but still the debug message is not logged. Do I need to enable Debug?

**Comment by brockallen** [comment]
All set on this issue -- can we close?
