### ISSUE TITLE
A way to circumvent Correlation failed exceptions when users navigates back after login?

### ISSUE THREAD

**Issue by jenspettersson** [DuendeSoftware/Support#348]
Reproducing with https://demo.duendesoftware.com/ for this question

**Which version of Duende IdentityServer are you using?**
6.1.2

**Which version of .NET are you using?**
Whatever https://demo.duendesoftware.com is using

**Describe the bug**
_Not a bug, but a question about how to perhaps prevent the error after certain user behaviors._ 

We're seeing a lot of users that uses the browser Back button after a successful authentication (with a remote idp like google). This causes the Duende Identity Server to try to re-authorize the request causing a `Correlation Failed` exception. The users are often navigating from an older on-prem intranet via a link to our new site (which needs its own authentication, it's not shared with the authentication of the intranet) and hence thinks the "back button" will take them back to the intranet. Now they see our custom error page saying something went wrong with the login and our logs shows the `Correlation failed` exception. A bit confusing as they just logged in and hit "Back".

We would like to know if there's a recommended way of trying to prevent the error from occuring (i.e. try to see if there's already an active login session and not try to re-authorize again or something like that).

**To Reproduce**
It's easy to reproduce with the Duande Identity Server online demo

1. Go to https://demo.duendesoftware.com/
2. Make sure you're logged out.
3. `Click [here] to see the claims for your current session.`  or something else that will trigger a login on the demo page.
4. Log in using Google and select the account to log in with.
5. Hit the Back button when you're back on the Duande Demo.
6. You're now back at the page at step 4. Select google account again.
7. `Correlation failed`

**Expected behavior**

A way to distinguish a proper `Correlation failed` with the one described above... Perhaps not the easiest?

**Log output/exception with stacktrace**

```
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in AuthenticationRequestHandlerWrapper.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in DynamicSchemeAuthenticationMiddleware.cs
Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in BaseUrlMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by josephdecock** [comment]
The best that you can do is to handle the error in the client application so that the user doesn't get presented with the error. 

You can't prevent the browser from having the authorize call in its history, so the back button is going to take the user back through the flow. And the correlation cookie will be destroyed during the original login, so correlation will always fail.

To handle the error, add something like this to the oidc options inf your client app:

You could also look at the exception message for "Correlation failed.", but I prefer this style because I don't like to rely on a string in an exception that I don't control. Unfortunately, the correlation failure exception is not a specific type of exception that you can handle either.

```c#
options.Events.OnRemoteFailure = async ctx =>
{
    if(ctx.Request.Path == options.CallbackPath)
    {
        var authResult = await ctx.HttpContext.AuthenticateAsync(IdentityServerConstants.DefaultCookieAuthenticationScheme);
        if(authResult.Succeeded)
        {
            ctx.HandleResponse();
            ctx.Response.Redirect("/");
        }
    }
};
```

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by jenspettersson** [comment]
Sorry for late reply. Yes, this can be closed and thanks for the input!
