### ISSUE TITLE
Identity Server w/Entity Framework: How to add a custom claim having a value that comes from an API call

### ISSUE THREAD

**Issue by ttoups** [DuendeSoftware/Support#35]
**Background:**
We have an identity server configured to work with entity framework. We need to include a custom identity resource scope that contains two claims, and each claim contains a value.  The values for those claims comes from an API call to a separate, internal API.

**Current way we are doing this:**
Without using entity framework, it's pretty straightforward and trivial to accomplish this. But with it integrating into entity framework, I am a bit confused as to how to accomplish it.
The current way I am trying to accomplish this is by creating a custom profile service, which examines the context to see which scopes are requested, and if the custom scope we created is requested, then the profile service appends the custom claims and their values retrieved from invoking our API 

**Question:**
Is the above solution the "correct" or preferred way to do this?

Thanks in advance! 🙂

**Comment by brockallen** [comment]
Using EntityFramework for the config and operational data shouldn't change how to add claims in the profile service. So yes, if adding the claims in the profile service works for you, then keep doing it. 

https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

**Comment by ttoups** [comment]
@brockallen  - Thank you!

**Comment by ttoups** [comment]
Got the answer I'm looking for. Thank you
