### ISSUE TITLE
Building 6.1.7 for .NET6 and Automapper 11.0.0

### ISSUE THREAD

**Issue by gatecrasher63** [DuendeSoftware/Support#350]
I am using IS 6.1.7 from NuGet. I have updated .NET to 6.0.11 in my solution

I can build locally but it is failing on our Azure Devops Build Server

It is complaining Automapper 11.0.0 not compatible with .NET 6

I have drilled into Duende.IdentityServer.EntityFramework.Storage 6.1.7 and can see an Automapper 11.0.0 reference

So is my problem that my Devops Server can't reach the internet (maybe) and do some form of NuGet update to 12.0.0. or is that reference wrong?

**Comment by gatecrasher63** [comment]
When I check the build folder on my local machine it is also pulling in version 11 not 12 of Automapper.dll

is this really needed for .NET6 or is Devops running checks not normally done

**Comment by brockallen** [comment]
We released v6.2.0 today that updates to that version of AutoMapper.
