### ISSUE TITLE
Incident during upgrade from v4.1 to v6

### ISSUE THREAD

**Issue by auslavs** [DuendeSoftware/Support#352]
**Which version of Duende IdentityServer are you using?**
6.1.2

**Which version of .NET are you using?**
.NET 6

We are sharing an incident we experienced while deploying our IdentityServer instance to production yesterday with the hope that it might help others.

## Background
This week we deployed our Identity Server to production after upgrading from v4.1 to v6.

We have some non-prod environments where we ran IdentityServer v6 for a couple of weeks and performed a suite of manual and automated tests, observing no issues we deployed it to production.

After deploying to our production environment - where we run two instances of Identity behind a load balancer - a number of support requests came through with users reporting that they could not log in to some services. This did not seem isolated to any particular service, web browser or device type.

There were a number of exceptions present in the logs, the most frequent of which had the problemId:
` System.Security.Cryptography.CryptographicException at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize`;

With an outer message of:
`The key {0e4ffda4-183f-4865-a4e9-f45f533734a8} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning`

This led us to the GitHub issue DuendeSoftware/IdentityServer#706.

## Problem Description
On reading the issue and linked documentation the issue became apparent.
* IdentityServer takes a dependency on the built-in [data protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/) feature of ASP.NET.
* The default settings are only appropriate for apps running on a single machine.
* Data protection keys, by default are generated per machine.
* In our production environment we have two IdentityServers instances with Azure Traffic Manager sitting in front.
In summary, some of our traffic had persisted grants encrypted by one machine but when the user was directed to another machine decryption and deserialization of the grant failed. This resulted in the affected users being unable to access our systems.

## Fix
We are testing the recommended solution where we store the data protection keys in a common secure storage.
Furthermore, we are also looking at ways we can replicate the load in our test environment so that we can test the fix.

## Suggestions going forward
1.	Appreciating that this dependency on ASP.NET Core Data Protection is mentioned in the docs [here](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/),  but as this is a change in behaviour between v4.1 and v6, we think it would be beneficial to include this in the [upgrade docs](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v4_to_dis_v6/).

2.	In the `PersistentGrantSerializer.Deserialize<T>` method we could log if `_provider.Unprotect` ([code here](https://github.com/DuendeSoftware/IdentityServer/blob/18fd065fb0491a15d077827df244a590d1615769/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs#L114)) returns null before passing it to the serializer. This may help identify the issue as a data protection issue rather than a serializer issue.

**Comment by josephdecock** [comment]
Thanks for some great feedback! DataProtection problems are one of the most common issues we get, and I'm in the process of updating our upgrade docs to help people with this common problem.

**Comment by josephdecock** [comment]
We also have an issue on our backlog to improve the logging around data protection failures. Thanks again!
