### ISSUE TITLE
Provisioning SessionDbContext

### ISSUE THREAD

**Issue by eugene-rebedailo** [DuendeSoftware/Support#355]
**Which version of Duende BFF are you using?**
v2.0 (Duende.Bff.EntityFramework package)

**Which version of .NET are you using?**
.NET6

**Describe the issue**
It is unclear how the SessionDbContext is meant to be provisioned. There is no setup scripts/EF migrations or any mentioning of the database management in the docs or in the samples.

Ideally, I would like to create the schema in a CI/CD process since I don't want my runtime connection string to have any schema administration permissions, but I can't create my own migrations based on the SessionDbContext since I don't actually own the class.

I have tried the following approaches:
- Using a custom built CLI app to run ```context.Database.MigrateAsync()``` from my CD process.
- Using ```context.Database.EnsureCreatedAsync()``` but it only works in case the database doesn't exist - doesn't actually ensure the schema in case database already exists
- Trying to subclass from the SessionDbContext and creating migrations for it doesn't seem to work, ```dotnet ef ``` can't seem to create an instance of my context at design time since CLI can't create an instance of this context through DI, can only do so in runtime due to dependency on CLI arguments.

**Additional context**
- I have to use a custom built CLI for this, since we are using azure managed identities to sign into the DB - so Db connection process has to be decorated with an interceptor providing the accessToken. This doesn't seem to be possible with ```dotnet ef database update``` which only takes a connection string.
- Ideally, I would not want to have any migrations related to this DbContext since I don't own the schema of it.
- It has to be done in the CD pipeline for security reasons.

Is there any relevant documentation or samples that I could use?

**Comment by josephdecock** [comment]
In general, we take a very abstracted view of the data stores. This allows for a great deal of customization, but it also means that we're expecting our users to manage their own databases. That said, we also provide EntityFramework based implementations of our stores for the case where customization isn't needed. Then upgrading just requires that you generate EF migrations for your database and apply them. Our [upgrade docs](https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.0_to_v6.1/) describe that process in more detail.

**Comment by brockallen** [comment]
@eugene-rebedailo We plan to add some more docs on generating the DB for the BFF's EF layer. It's certainly an area for improvement, but it's very similar to what you'd have to do with IdentityServer's EF layer.
