### ISSUE TITLE
Is IUserAccessTokenStore no longer injectable?

### ISSUE THREAD

**Issue by eugene-rebedailo** [DuendeSoftware/Support#356]
**Which version of Duende BFF are you using?**
v2.0.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
Since the update to v2.0.0 of the package, It seems to be impossible to inject ```IUserAccessTokenStore``` to access the user token, it seems that starting v2.0.0 the ```.AddBff()``` extension method no longer registers the store. Are we expected to switch to injecting ```IClientCredentialsTokenManagementService``` instead? We would rather avoid it seeing how it introduces a dependency on ```Duende.Bff```

**Additional context**

Access to user token is required to setup a token delegation chain when calling remote APIs

**Comment by leastprivilege** [comment]
Duende BFF switched to Duende.AccessTokenManagement for token management

https://github.com/DuendeSoftware/Duende.AccessTokenManagement

The class is now called `IUserTokenStore`.
