### ISSUE TITLE
Should I not be including claims by resource_ids in my authorization token?

### ISSUE THREAD

**Issue by Tyler-V** [DuendeSoftware/Support#359]
Looking for some feedback on design,

![image](https://user-images.githubusercontent.com/3893234/204026394-f43fcadf-4056-430c-9fa0-75cead831212.png)

I am using IdentityServer 6.1.1 with ASP.NET Core Identity

In this flow, I can programmatically add claims to the access token in the ProfileService based on the client's request of the resource api scope of "api1"

```
    public async Task GetProfileDataAsync(ProfileDataRequestContext context)
    {
        if (context.Caller == IdentityServerConstants.ProfileDataCallers.ClaimsProviderAccessToken)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            if (user is not null)
            {
                var roles = await _userManager.GetRolesAsync(user);
                if (roles.Any())
                {
                    context.IssuedClaims.Add(new Claim("role", roles.FirstOrDefault()!));
                }

                var claims = await _userManager.GetClaimsAsync(user);

                if (context.RequestedResources.Resources.ApiScopes.Any(s => s.Name == ApiScopes.Api1.Name))
                {
                    foreach (var claim in claims)
                    {
                        context.IssuedClaims.Add(claim);
                    }
                }
            }
        }
```

Over time, I have concerns about the JWT growing in size based on the complexity, requested resources, etc. 

What is the preferred approach to handling authorization at the API, using IdentityServer, where I need to protect individual resources by id that would live in the claims table of ASP.NET Core Identity 

Should I be injecting ApplicationDbContext in "api1" and accessing claims, roles, and policies at request runtime to evaluate which resources should be returned to the user instead of populating them in the access token?

Thanks!

**Comment by josephdecock** [comment]
The way that you draw boundaries around the components of your system is an interesting architectural question, and not one with a single right answer every time. That said, I can give some general guidance.

> Over time, I have concerns about the JWT growing in size based on the complexity, requested resources, etc.
Yes, this is exactly the problem. You shouldn't treat tokens as a dumping ground for all permissions data. Claims in a token should be as neutral and non-specific to an api or application as possible. Permissions are application or api specific (you could very well have admin rights in one tool but not others). Resource Ids are even more specific to the application or api. I would try to keep both out of tokens. The token can just convey some small amount of data that identities and describes the user. Then you can take additional steps at the api or application to make authorization decisions and to gather data that you might need to make those decisions (e.g., the identity system says this is Joe, let's go look up if Joe is allowed access to my resource 1234 the API's database).

**Comment by Tyler-V** [comment]
Thanks for the insight @josephdecock 

I think there have been some blurred lines in the history/solutions offered by OAuth 2.0 evident across stackoverflow posts, medium articles, etc. and I have built API's in the past that have probably taken too many liberties in stuffing the authorization token like a thanksgiving turkey and can see the adverse effects down the road that brings especially now as I am setting up IdentityServer as a federation gateway now for multiple API's across the same identity store so I wanted to confirm architecture here before putting pen to paper

With your comments and doing some more digging, this is what I am aiming for now

![Identity Server](https://user-images.githubusercontent.com/3893234/204371064-508462b5-176d-4a50-bf8d-bfc690e874ec.png)

With the authorization token being more lightweight now I will have to retrieve claims from the AspNetIdentity context in my API now and would like to eliminate as many round trips as possible between requests, what is the preferred approach to handle this that you would recommend?

**Comment by josephdecock** [comment]
I'm sorry, but we're not really able to do the kind of architectural analysis that you're looking for over github support issues. Authorization is just such a complex topic with so many possibilities that we can't really give it the proper amount of attention on our support forum, which is intended for solving product issues and smaller questions.

That said, I don't think permissions belong as claims in Asp.NET Identity like this. Dominick gave a great conference talk a few years back discussing how you might think about authorization which you might find very helpful: https://www.youtube.com/watch?v=Dlrf85NTuAU

We do offer remote consulting services if you want to go into real depth on this one on one. Let us know if you're interested.

**Comment by josephdecock** [comment]
I recommend that you try removing IIS Express and running directly in kestrel. If that works, then you know that the problem is related to the way that IIS Express handles the HTTPS connection - I suspect that somehow IIS Express isn't passing along the right information to kestrel for it to know that the request is using HTTPS.

**Comment by Tyler-V** [comment]
No worries @josephdecock I understand

According to Dominick I'm in the business logic layer now (retrieving store_ids) and will handle it on the .Net Web API side this is helpful, thanks for the resource
