### ISSUE TITLE
Blazor  WASM with BFF + .NET Core API --> deployment advice

### ISSUE THREAD

**Issue by karanlik** [DuendeSoftware/Support#36]
Hi,

We're struggling with deployment of our project to Azure WebApp environment.
We have successfully run the application which was guided by the tutorial at https://docs.duendesoftware.com/identityserver/v6/quickstarts/7_blazor/ and https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/BlazorWasm

We have a .NET Core REST API and a Blazor WebAssembly (hosted) project. In our local environment we're able to run the application, authenticate, filter our records etc. Now, we're trying to deploy this application to Azure WebApps using Azure DevOps pipelines. We tried to different approaches;
1) The "hosted" model as described in the Sample projects & quickstarts. In this approach we deploy our Server app to a WebApp. After pipeline's successfull execution, the client (wasm) project is loaded from our app URL. Say https://my-app.azurewebsites.net. But whenever we try to access our API like https://my-app.azurewebsites.net/api/v1/books we get the following error:
HTTP Error 500.35 - ANCM Multiple In-Process Applications in same Process

2) WebAssembly and API is deployed to different WebApps. like https://my-app-client.azurewebsites.net for WASM and https://my-app.azurewebsites.net for API. In this setup, we failed to successfully get BFF functionality running. We believe this is due to the fact that BFF Local API is providing a cookie based approach but API is asking for an authenticated user (a valid access token).

So here the questions are;
* Do you have a sample project for Blazor WASM and API deployed to different domains?
* Any advice/guide on successfully deploying such application to Azure WebApps ?

Thanks for your time..

**Comment by leastprivilege** [comment]
Both scenarios / questions actually raise a lot more questions on my side... Are you an existing customer with a support contract?

**Comment by karanlik** [comment]
Hi,
Currently we're not a customer but we're eligible for Community Edition. By the way we've found and resolved the issue regarding "HTTP Error 500.35 - ANCM Multiple In-Process Applications in same Process" error. We were trying different deployment approaches (virtual directories for API and WASM, only API deployment to the root etc.). Probably this Http 500 problem was about some previous deployment packages that were left there. Deleting the WebApp instance and creating a new one and deploying in "hosted" model fixed our problem. 

But I believe, a guide about handling deployment WASM and API to two different WebApps would help the community.
thanks..
