### ISSUE TITLE
In-memory signing key store when running in Docker

### ISSUE THREAD

**Issue by benfoster** [DuendeSoftware/Support#362]
**Which version of Duende IdentityServer are you using?**

6.2.0

**Which version of .NET are you using?**

7.0

**Describe the bug**

More of a question than a bug. We're running Identity Server in Docker in our integrations tests. By default it attempts to store signing keys on the file system. Is there an in-memory version for cases where we don't want to persist keys otherwise what is the recommended approach for a completely ephemeral instance?

Secondly, more out of curiousity, when making a request to Identity Server for the first time, the following exception is logged though it doesn't seem to impact the outcome of the request:

```
gateway-simulator | fail: Duende.IdentityServer.Services.KeyManagement.KeyManager[0]
gateway-simulator |       Error unprotecting key with kid F22F5E697844E421A1CF572E31449D97.
gateway-simulator |       System.Security.Cryptography.CryptographicException: The key {479e6269-e6b2-4803-b5ab-a7698676b932} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
gateway-simulator |          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
gateway-simulator |          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
gateway-simulator |          at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
gateway-simulator |          at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
gateway-simulator |          at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```

**To Reproduce**

Running stateless identity server in Docker

**Comment by josephdecock** [comment]
I think the easiest thing to do is to allow the IdentityServer container to write the signing keys to the file system within the container. Every time you get a new ephemeral copy of the container, you'll be starting fresh.  If you absolutely have to store the keys in memory, you could accomplish that by creating an in memory implementation of the ISigningKeyStore, but I don't really understand why you'd bother.

**Comment by josephdecock** [comment]
My guess for your second issue is that you may be accidentally adding a signing key into the container. The container would then have no way to decrypt the signing key because it doesn't have the data protection key that was used to sign it. Perhaps the docker build process is adding a signing key that it shouldn't, or maybe the key was added to source to source control accidentally.

**Comment by benfoster** [comment]
Thanks @josephdecock, you're right that I had forgotten to add the `keys` directory to `.dockerignore`. Thanks for your help. I'm fine with persisting the keys to the container as per your description.
