### ISSUE TITLE
License Key

### ISSUE THREAD

**Issue by SriramaDanturthi** [DuendeSoftware/Support#369]
**Which version of Duende IdentityServer are you using?**
6.1.5
**Which version of .NET are you using?**
6.0
**Describe the bug**

How do you read license key from database? 

I have a valid license key in db and trying to do db call during the configure services method and its not accepting the license key and logging like you do not have valid license key
 ```
public static WebApplication ConfigureServices(this WebApplicationBuilder builder)
    {
        WebApplication application = null;
builder.Services
            .AddIdentityServer(options =>
            {
                options.LicenseKey = application.Services.GetLicenseKey();
                --------
            });
 application = builder.Build();
        return application;
}
```
 ```
private static string GetLicenseKey(this IServiceProvider serviceProvider)
    {
     //return license key from db
    }
```

**Comment by SriramaDanturthi** [comment]
You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us

**Comment by brockallen** [comment]
Can you email us the license key at contact@duendesoftware.com so we can have a look at it? Or email us the license serial number you received?

**Comment by SriramaDanturthi** [comment]
ok
