### ISSUE TITLE
How to refresh the cookie session to get additional claims

### ISSUE THREAD

**Issue by xabikos** [DuendeSoftware/Support#371]
**Which version of Duende BFF are you using?**
2.0.0

**Which version of .NET are you using?**
7.0

**Describe the Question**
We have the set up based on the samples. We have a asp.net core app that acts as the BFF and backs up a React.js app. All the apps are in .net 7.0. 

When the user signs in then we get back the expected response from Identity Server and the Microsoft cookie handler creates a cookie and send it to the browser. The session that is fully controlled by ASP.NET Identity system if not mistaken includes the Claims that have returned from Identity Server. And those claims are returned when we hit the [user endpoint.](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/#user).

Let's say now that our user entity that is managed by the project that hosts the identity server has a property like `BirthDate` which and we provide an API to update it. Once this is updated then we included in the user claims. 

The problem is that the BFF doesn't know about the updated value. Is there a way to somehow enforce the ASP Identity system to kinda repeat the process that happens during sign in and issue a new cookie/session that will include the new claims? 

In the answer [here](https://github.com/DuendeSoftware/Support/issues/243#issuecomment-1267007393) I see that the BFF framework might request the cookie to be updated and I would like to find out if and how we can force it as well.

Just to make clear if the user signs out manually and then sign in again he gets the new claims. 

I hope it's a valid scenario what I am trying to achieve.

**Comment by josephdecock** [comment]
There isn't a mechanism built in to OIDC to communicate this kind of information from the OIDC Provider to the client application. 

If your bff can somehow know that it needs to update a user, the bff could call the user info endpoint to get the updated claims. Then you could create a new identity based on the current identity but with the updated claims, and call SignInAsync, passing that updated identity. There will be some tricky timing problems to solve here, because the notification to the bff is going to come separately from when you can update the user session (need to wait for the user to make a request).

Another option is to not include this claim in the user info, but instead make it available over some new api. If you don't actually need the birthday on every request, you could retrieve it only when necessary. If you do need it all the time and want it to continue to be a claim on your user, your BFF cookie handler could add the birthdate claim by calling the birthday api in a claims transformation. That would obviously put a lot of load on the birthday api, but maybe you can work around that with caching.

**Comment by xabikos** [comment]
Thanks for the quick response @josephdecock It is very helpful. 

I would be surprised if there was such a mechanism in the OIDC (Identity Server part). So that's fine. But I am glad to hear there is a solution on the BFF part.

So this is my code right now in a controller in the BFF part. Here we are executing an API request to a controller living in the project that hosts the identity server as well and we update user first name, last name and date of birth (`PersonalInfoModel`).

```
[HttpPut("updatepersonalinfo/{id}")]
public async Task<IActionResult> Put(string id, [FromBody] PersonalInfoModel personlaInfo)
 {
            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient();
                // get current user access token and set it on HttpClient
                var token = await HttpContext.GetUserAccessTokenAsync();
                client.SetBearerToken(token.AccessToken);

                try
                {
                    var response = await client.PutAsJsonAsync($"api/users/updatepersonalinfo/{id}", personlaInfo);
                    response.EnsureSuccessStatusCode();
                    return Ok(new { });
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            return BadRequest(ModelState);
}
```

I would prefer to go with your first suggestion which if I get it right should change the code to something like the following.

```
public async Task<IActionResult> Put(string id, [FromBody] PersonalInfoModel personlaInfo)
        {
            if (ModelState.IsValid)
            {
                var client = _httpClientFactory.CreateClient();
                // get current user access token and set it on HttpClient
                var token = await HttpContext.GetUserAccessTokenAsync();
                client.SetBearerToken(token.AccessToken);

                try
                {
                    var response = await client.PutAsJsonAsync($"api/users/updatepersonalinfo/{id}", personlaInfo);
                    response.EnsureSuccessStatusCode();

                    // In case of success we need to get a fresh shet of data from Identity server
                    var userInfoResponse = await client.GetAsync("identityServerURL/connect/userinfo,");
                    userInfoResponse.EnsureSuccessStatusCode();
                    // Then based on the response we need to create a claims identity
                    // and use the SignInManager to sign in the user again

                    return Ok(new { });
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            return BadRequest(ModelState);
        }
```

What I am not sure about is for the process of signing in the user in the BFF part. Is it enough to generate a new cookie with the updated values? I guess this is what it happens initially too, when the user signs in manually. 
And also I guess in this case, after signing in the user again the `/bff/user` endpoint it will include the updates values.

**Comment by josephdecock** [comment]
> Is it enough to generate a new cookie with the updated values? I guess this is what it happens initially too, when the user signs in manually.

Correct

> And also I guess in this case, after signing in the user again the /bff/user endpoint it will include the updates values.

Also correct
