### ISSUE TITLE
Query regarding configuring license key.

### ISSUE THREAD

**Issue by irien-kerishya** [DuendeSoftware/Support#372]
What happens on license renewal? Does the key remains the same?
We are currently loading the license key in startup.cs, If there is change in license key then we would to rebuild and do package..

**Comment by leastprivilege** [comment]
Hi, 

yes you will get a new license key at each renewal.

**Comment by irien-kerishya** [comment]
So it is best to follow the file system way of configuring the license key right?
https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key

**Comment by leastprivilege** [comment]
I don't know your deployment process. Loading from a database / environment variable would be possible too.

**Comment by irien-kerishya** [comment]
Thanks @leastprivilege

**Comment by irien-kerishya** [comment]
Hi @leastprivilege ,
Few more clarifications required from your end.
1. What happens when we renewed license, but still some of the sites uses the old license and haven't updated to new key?
2. If we renew the license prior to expiry for ex: expiry date is 02/12/2023, but we have renewed the license on 01/11/2023,
Can we use the new license key from 01/11/2023?

**Comment by josephdecock** [comment]
In production with a redistribution license, any license problems are logged at the trace level only. This way, your customers will likely not ever see any messages about Duende licensing that aren't relevant to them.

https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key/ lists all the licensing log message levels for the various scenarios we distinguish.

**Comment by josephdecock** [comment]
And to expand on the scenario where your customers haven't updated, their IdentityServer would continue to function. We understand that you could have customers that are hard to update, so the license system is designed to not cause a disruption.
