### ISSUE TITLE
The key {c999396a-dd30-4495-a43c-75aee91bbe80} was not found in the key ring

### ISSUE THREAD

**Issue by fdagdagan** [DuendeSoftware/Support#373]
Hi,

Good Morning! Any idea why this is happening? Thanks!

**Which version of Duende IdentityServer are you using?**  
6.1.7

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

System.Security.Cryptography.CryptographicException: The key {c999396a-dd30-4495-a43c-75aee91bbe80} was not found in the key ring

{
  "TimeStamp": "2022-12-02T07:14:05.5056348",
  "Level": "Error",
  "Message": "Error unprotecting key with kid \"1FF2F3006DFCC5B3ED5E71D669C6FF6F\".",
  "MessageTemplate": "Error unprotecting key with kid {kid}.",
  "Exception": "System.Security.Cryptography.CryptographicException: The key {c999396a-dd30-4495-a43c-75aee91bbe80} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning\r\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)\r\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)\r\n   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)\r\n   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56\r\n   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435",
  "Properties": {
    "kid": "1FF2F3006DFCC5B3ED5E71D669C6FF6F",
    "SourceContext": "Duende.IdentityServer.Services.KeyManagement.KeyManager"
  }
}

**Comment by josephdecock** [comment]
IdentityServer's signing keys get encrypted and decrypted using Microsoft's data protection feature. Data protection manages its own encryption keys separately from the signing keys that IdentityServer uses. The data protection keys can cause problems if you have a signing key stored in your signing key store, but try to decrypt it without the data protection key that encrypted it.

There are several ways that this can occur:

1. In load balanced environments, every instance of IdentityServer needs to share signing keys, and you need to configure data protection to do so. Microsoft has extensive docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview).
2. Signing keys could be generated in a (local) development environment and then accidentally included into the build output.
3. Data protection creates keys isolated by application name automatically. If you don't specify a name, the content root path of the application will be used. But, beginning in .NET 6.0 Microsoft changed how they handle the path, which can cause data protection keys to break. Their docs on the problem are [here](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview#setapplicationname), including a work-around where you de-normalize the path.

**Comment by Umar-Mukhtar** [comment]
No matter what you do the issue persists. Been stuck to get identity server run on azure app service. The local copy eorks flawlessly, also tried hosting on local iis with no issues. The self signed cert i tried never works. Used all 3 makecert, openssl and powershell. The duende UI loads, token also gets exchanged via api but duende openid discovery fails to load, and none of the api endpoints work. Duende throws ring not found and the api says failed to load discovery doc.

**Comment by josephdecock** [comment]
@Umar-Mukhtar , the behavior you're describing indicates that the signing key is working, but that there are additional validation keys that identity server is failing to unprotect. It sounds like you have automatic key management enabled (possibly unintentionally) and are also setting a signing key explicitly. If you're not planning to transition to automatic key management in the future, I would disable automatic key management. That will stop this particular data protection failure. However, there are other places where IdentityServer uses DataProtection to encrypt data at rest, so you will ultimately need to resolve any data protection problems as well. Please do look at the microsoft docs on data protection that I've linked above. You may also find the [key management section of our docs](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/) useful.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
