### ISSUE TITLE
Add Prometheus IHttpClientFactory metrics to RemoteApis with simple HTTP forwarder

### ISSUE THREAD

**Issue by mike-henders** [DuendeSoftware/Support#374]
**Which version of Duende BFF are you using?**

2.0.0-preview.5

**Which version of .NET are you using?**

.NET Core 6.0

**Describe the question**

We use the [prometheus-net](https://github.com/prometheus-net/prometheus-net) project to instrument applications using Duende BFF. The Prometheus project includes a convenient extension method [UseHttpMetrics](https://github.com/prometheus-net/prometheus-net#ihttpclientfactory-metrics) on IHttpClientBuilder to instrument service-to-service calls. We are investigating ways to get similar behavior from Remote APIs using the built-in simple HTTP forwarder.

The Prometheus extension uses IHttpClientBuilder's ability to create a pipeline of HttpMessageHandler. Much of the implementation of both the ASP.NET Core and Prometheus extension is sealed or internal, so we can't reuse their code directly. We are considering writing our own pipeline of HttpMessageHandler and then subclassing DefaultHttpMessageInvokerFactory to return the pipeline in CreateHandler.

Are you aware of an easier solution than the one proposed above? Since Duende.Bff.Yarp uses HttpMessageInvoker instead of HttpClient, we are assuming the answer is no.

Do you have any concerns with this approach from either a correctness standpoint or compatibility with future versions of Duende.Bff and Duende.Bff.Yarp?

**Comment by josephdecock** [comment]
@leastprivilege, can you comment on this?

**Comment by leastprivilege** [comment]
> We are considering writing our own pipeline of HttpMessageHandler and then subclassing DefaultHttpMessageInvokerFactory to return the pipeline in CreateHandler.

Internally YARP uses HttpMessageInvoker. So regardless how you do it (and if you extend our simple forwarder or do it at the YARP level), you need to make this work somehow.

**Comment by mike-henders** [comment]
This answers my question about whether there is an easier solution. I appreciate the additional information that YARP uses HttpMessageInvoker too.

Since subclassing DefaultHttpMessageInvokerFactory is mentioned in the documentation for BFF under extensibility and you didn't say anything negative about the approach, I'll assume you don't have any concerns about future compatibility at this time.

**Comment by leastprivilege** [comment]
> I'll assume you don't have any concerns about future compatibility at this time.

I have no concerns and I do not see an easier way of doing it.
