### ISSUE TITLE
SameSiteMode.Strict causes Correlation Failed or Too Many Redirects

### ISSUE THREAD

**Issue by nikriaz** [DuendeSoftware/Support#376]
**Which version of Duende IdentityServer are you using?**
6.0
**Which version of .NET are you using?**
6.0
**Describe the bug**

Your [ v6 manual ](https://docs.duendesoftware.com/identityserver/v6/bff/session/handlers/) advises to use `SameSiteMode.Strict` for clients. This is in the BFF part but I believe it's applicable to any interactive ASP.NET-based OIDC clients (maybe even wider).

However, If I try to run your own [sample ](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/tree/main/samples/Web) which is I believe the most basic ASP,NET client implementation possible, I'm getting an error. The error depends on where I put the `SameSiteMode.Strict` option. It is _Correlation Error_ if I put it on the site level, and it's _Too Many Redirects_ if I put in the auth cookie handler options. The client, in fact, becomes authenticated, just fails to redirect normally, meaning to open a page is supposed to be redirected to. Manual re-opening the same page works. 

It's unclear to where you advise to put this setting because in the text you says _"use the highest available SameSite mode that is compatible with **your application**"_ and in the code sample below you show just auth cookie options. Anyway, neither of these setting locations work. My own experiments lead to the same results as with your example.

I certainly do not fully understand the whole picture of the entire workflow. StackOverflow is full of the questions for this matter with most accepting answers is to change the setting to `SameSiteMode.Lax`. [This ](https://stackoverflow.com/questions/50262561/correlation-failed-in-net-core-asp-net-identity-openid-connect)is the most popular thread. Microsoft [says ](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-7.0) _"...SameSiteMode.Strict... this setting breaks OAuth2 and other cross-origin authentication schemes"._ This is partially wrong because a client gets authenticated but also partially true because the whole process does not work normally.

Can you please shed light on this issue?

**Comment by josephdecock** [comment]
What the docs are saying is that you need to pick between same site lax or strict as appropriate. The way to pick is, if the application and identity server are not cross site, you can strict and if they are not, you probably need lax.

However, it is possible to work around some of the issues and use strict even cross site. Brock wrote a great blog post on this here: https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/

**Comment by nikriaz** [comment]
This is fantastic article, it explains exactly the issue. Thank you!

Just to summarize: 

An app issues a cookie that should be sent to IdP along with authentication request (that I didn't know). `SameSiteMode.Strict` prevents this and broke the flow, even though the the app does receive a response. App's middleware then cannot redirect from the callback endpoint to the original requested redirect page and instead sends request back to the IdP. From the server standpoint, it's the same request as it was before, so it redirects back. That is the reason for the redirect loop. When user refreshes page manually, it finally sends cookie to IdP because a manual refresh is not cross-site request (this I didn't know too), so at this point authentication is finalized, even though it looks like user was authenticated before refresh. 

I think it would be wise to catch such looping requests in the Identity Server. In my case, they, in fact, are caught by throttling control but I guess it should be possible to detect such "incomplete" repetitive requests more knowingly.
