### ISSUE TITLE
Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. 

### ISSUE THREAD

**Issue by DSagare** [DuendeSoftware/Support#377]
**Which version of Duende IdentityServer are you using?**
5.2.0
**Which version of .NET are you using?**
netcoreapp3.1
**Describe the bug**

We recently migrated our identity sever from V 3.1.4 to licensed Duende IdentityServer V 5.2.0.  We are using load balancer for our IdentityServer website, when user try to access our website the DNS will hit the load balancer( we have total 3 servers on LB) and the LB will call individual sever with IP address.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: 

**Additional context**

**Comment by josephdecock** [comment]
@DSagare are we good to close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen or create a new issue as needed.
