### ISSUE TITLE
Question re: Persisted UserSession store and the SessionId column.

### ISSUE THREAD

**Issue by StuFrankish** [DuendeSoftware/Support#379]
**Which version of Duende IdentityServer are you using?**
Duende.BFF (2.0.0)
Duende.BFF.EntityFramework (2.0.0)
Duende.IdentityServer (6.2.0)
Duende.IdentityServer.AspNetIdentity (6.2.0)
Duende.IdentityServer.EntityFramework (6.2.0)
Duende.IdentityServer.Storage (6.2.0)

**Which version of .NET are you using?**
.Net 7

**Describe the bug**
Not a bug perse', but a question about the use of SQL Server and persisted `UserSession`.
We had previously (in Identity Server 4.x) been able to use Redis caching for persisted session data. Since moving to the latest version of Identity Server with Duende, we have had to use SQL storage for this persisted data.

My question is, now that we have easier visibility of the persisted data, we have noticed that the `SessionId` column of `dbo.UserSessions` is always `NULL`. Is this typical and when should this value be present?

**To Reproduce**
Implemented using BFF with SQL Server;
```c#
services.AddBff()
    .AddEntityFrameworkServerSideSessions(options =>
    {
        options.UseSqlServer(DbConnectionString);
    });
```

I've tried reading through the documentation, but there are lots of gaps that don't explain what certain things are or where they come into play, so it would be useful for us to understand fully exactly how this works and if it's required to support session checks by client apps and the use of back-channel logout on those client apps.

**Comment by josephdecock** [comment]
The BFF's UserSessions.SessionId column should be set to the value of your session id, which you should see as the sid claim in id tokens and as the session id authentication property at identity server. It is definitely not normal for this to be null.  BFF's backchannel logout relies on the session id - when it revokes the session, it filters by session id.

Can you verify that you're properly getting a session id in identity server and that it is coming to the bff as the sid claim in the id token?

**Comment by Saldash** [comment]
I'm a bit confused then, if it's abnormal for the SessionId column to be null, why make it nullable in the table?
I've copied our `Startup.cs` configure services portion below, it doesn't appear to be out the ordinary as far as I can tell based on the documentation.

Things otherwise appear to be working generally - Identity Server is authenticating users, client apps are issuing challenges and (if the user is already signed in) being redirected back to the client app with a session.
Logging out of one client app doesn't log the user out of others though, which is what we would like to implement across our variety of SPA's and Asp.Net Core MVC apps.

Observing the `dbo.UserSessions` table, an entry is added for a user when they sign into the first client application.
When accessing a second client application, they are automatically authenticated but no additional records are added in the `dbo.UserSessions` table.

```c#
services.AddIdentityServer(options =>
{
    var identityServerLicenseKey = Configuration.GetValue<string>(key: "Duende.IdentityServer:licenseKey");

    if (!String.IsNullOrWhiteSpace(identityServerLicenseKey))
        options.LicenseKey = identityServerLicenseKey;

    options.ServerSideSessions.RemoveExpiredSessionsFrequency = TimeSpan.FromSeconds(value: 60);
    options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;

    options.KeyManagement.Enabled = false;

})
.AddSigningCredential(certificate: new X509Certificate2(Path.Combine(HostingEnvironment.WebRootPath, "AuthCertExample.pfx"), password: signingCredentialPassword))
.AddSentinelStore()
.AddClientStore<AppClientStore>()
.AddOperationalStore(options => {
    int tokenCleanupIntervalSeconds = 3600; // (1 Hour)
    options.ConfigureDbContext = builder => builder.UseSqlServer(DbConnectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
    options.EnableTokenCleanup = true;
    options.TokenCleanupInterval = tokenCleanupIntervalSeconds;
})
.AddResourceStore<AppResourceStore>();

services.AddBff()
    .AddEntityFrameworkServerSideSessions(options =>
    {
        options.UseSqlServer(DbConnectionString);
    });
```

I'm not sure where to look to verify in Identity Server where the `sid` is being sent back but the client application does have one in the logged in identity's claims - I assume this is somewhat positive.

Example:
```
User.Claims.First(c => c.Type == "sid")
{sid: 0C260ED29F1B661A6707FAB914448BE3}
    CustomSerializationData: null
    Issuer: "https://localhost:44330"
    OriginalIssuer: "https://localhost:44330"
    Properties: Count = 0
    Subject: {System.Security.Claims.ClaimsIdentity}
    Type: "sid"
    Value: "0C260ED29F1B661A6707FAB914448BE3"
    ValueType: "http://www.w3.org/2001/XMLSchema#string"
```

Is there something I can check in the Login action in the AccountController?
It would be really useful if I could see a golden sample implementation to compare against as our version of IdentityServer 6, was upgraded in-place from the last-but-one major release of Identity Server 4.

**Comment by StuFrankish** [comment]
I've done a bit more digging to check - it does appear that both the Identity Server and the client application are aligned.
If I access the `/Diagnostics/Index` route on our Identity Server, I'm presented with claims information that matches the client app.

**From Identity Server**
Key | Value
-- | --
.issued | Wed, 07 Dec 2022 13:23:58 GMT
.expires | Fri, 06 Jan 2023 13:23:58 GMT
session_id | 1E65AB7B265041EA5F4C9096FFA64F3E
.persistent |  

**From Client Application**
```
User.Claims.First(c => c.Type == "sid")
{sid: 1E65AB7B265041EA5F4C9096FFA64F3E}
    CustomSerializationData: null
    Issuer: "https://localhost:44330"
    OriginalIssuer: "https://localhost:44330"
    Properties: Count = 0
    Subject: {System.Security.Claims.ClaimsIdentity}
    Type: "sid"
    Value: "1E65AB7B265041EA5F4C9096FFA64F3E"
    ValueType: "http://www.w3.org/2001/XMLSchema#string"
```

So at some level, the Identity Server is aware of the `session_id`, it's just not storing it in the `UserSessions` table.
What could be causing this behaviour?

**Comment by josephdecock** [comment]
Thanks for all the investigation you've done so far. One more piece of information that might be valuable would be capturing logs in the client application with the verbosity turned all the way up. There are places where the server side session code will log what it is doing, including the session id, so perhaps that will show us where in the process the sid is being lost.

**Comment by StuFrankish** [comment]
Hi @josephdecock,

I've provided the trace from our Identity Server instead as I presumed it's what you meant - if not, my apologies I can provide client instead. Please let me know.

I've spotted these in a few places as I've been debugging;
```
Duende.Bff.EntityFramework.UserSessionStore: Debug: Creating user session record in store for sub 4ecde97a-02c1-4e66-a90f-b26c1cfae802 sid (null)
```
Though there doesn't appear to be anything surrounding it that indicates an issue getting the `sid`.

The trace is quite extensive, even for just capture the authentication.
Hopefully you'll be able to spot something helpful.

[IdentityServerTrace.txt](https://github.com/DuendeSoftware/Support/files/10212894/IdentityServerTrace.txt)

**Comment by josephdecock** [comment]
I think I made a bad assumption about how you're using the BFF. I assumed this snippet was from a separate BFF host:
```
services.AddBff()
    .AddEntityFrameworkServerSideSessions(options =>
    {
        options.UseSqlServer(DbConnectionString);
    });
```
It sounds like that's actually in your IdentityServer host, but it should not be. There's actually 2 different server side sessions that are possible - one at [IdentityServer](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/) and one at the [client application](https://docs.duendesoftware.com/identityserver/v6/bff/session/server_side_sessions/). I would make sure you understand which server side sessions you have/want, and then also make sure you're not adding the bff to the identity server host.

**Comment by StuFrankish** [comment]
Hi @josephdecock 

I think this is where our knowledge gap with Identity Server sits.
Our intention is to be able to hold and manage user sessions within and from our Identity Server.

Previous versions of Identity Server made use of Redis for the operational data stores which we assumed would also include user sessions.
As version 6+ no longer has any support for Redis, my research lead to UserSession in BFF which we have written into our developement Identity Server, admittedly without a full understanding and hence the queries while we're still working on it.

**Comment by StuFrankish** [comment]
A quick bit of re-working and I've got ServerSideSessions working (I think).
I've removed the BFF implementation and updated the `services.AddIdentityServer()` portion of code as below.

I can see we're now getting data in `dbo.ServerSideSessions` rather than the `dbo.UserSessions` table.
Including the session_id column.

```c#
services.AddIdentityServer(options =>
{
    var identityServerLicenseKey = Configuration.GetValue<string>(key: "Duende.IdentityServer:licenseKey");

    if (!String.IsNullOrWhiteSpace(identityServerLicenseKey))
        options.LicenseKey = identityServerLicenseKey;

    options.ServerSideSessions.UserDisplayNameClaimType = "name";
    options.ServerSideSessions.RemoveExpiredSessionsFrequency = TimeSpan.FromSeconds(value: 60);
    options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;

    options.KeyManagement.Enabled = false;

})
.AddServerSideSessions()
.AddSigningCredential(certificate: new X509Certificate2(Path.Combine(HostingEnvironment.WebRootPath, "SignedCert.pfx"), password: signingCredentialPassword))
.AddSentinelStore()
.AddClientStore<SentinelClientStore>()
.AddOperationalStore(options =>
{
    int tokenCleanupIntervalSeconds = 3600; // (1 Hour)
    options.ConfigureDbContext = builder => builder.UseSqlServer(DbConnectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
    options.EnableTokenCleanup = true;
    options.TokenCleanupInterval = tokenCleanupIntervalSeconds;
})
.AddResourceStore<SentinelResourceStore>();
```

**Comment by josephdecock** [comment]
Fantastic - I'll go ahead and close this issue then. Feel free to reopen/open a new one if needed.
