### ISSUE TITLE
Why make a database query to IdentityResources in the client credentials?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#38]
**Which version of Duende IdentityServer are you using?**
v6.0.4

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

We have observed that in the client credentials grant, it's making calls to the IdentityResources tables. Though, there is no relationship between Identity Resources and client credentials as there is no user involved.

We came to know this while implementing caching for configurations(IResourceStore and IClientStore). 

**To Reproduce**

Enable debug logs for EF and generate tokens using client credentials grant.

**Expected behavior**

It should not make a database call to IdentityResources tables for the client credentials flow.

**Log output/exception with stacktrace**

Query
```
SELECT [i].[Id], [i].[Created], [i].[Description], [i].[DisplayName], [i].[Emphasize], [i].[Enabled], [i].[Name], [i].[NonEditable], [i].[Required], [i].[ShowInDiscoveryDocument], [i].[Updated], [i0].[Id], [i0].[IdentityResourceId], [i0].[Type], [i1].[Id], [i1].[IdentityResourceId], [i1].[Key], [i1].[Value]
FROM [IdentityResources] AS [i]
LEFT JOIN [IdentityResourceClaims] AS [i0] ON [i].[Id] = [i0].[IdentityResourceId]
LEFT JOIN [IdentityResourceProperties] AS [i1] ON [i].[Id] = [i1].[IdentityResourceId]
WHERE [i].[Name] IN (N?, N?, N?)
ORDER BY [i].[Id], [i0].[Id]
```

**Comment by brockallen** [comment]
That's just due to how the code (and code reuse) is implemented, the the abstraction model around how the stores are implemented, and the fact that the token endpoint processes many types of requests.
