### ISSUE TITLE
SSL Issue on Azure 

### ISSUE THREAD

**Issue by Umar-Mukhtar** [DuendeSoftware/Support#386]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
.NET 6
**Describe the bug**
Unable to 
We hosted duende to azure for testing from local development, this url is secured by azure powered ssl. The duende UI loads using the url but the discovery document fails to load, the token also gets exchanged with the api hosted on azure within the same account subscription. None of the api endpoints work. The logs for appservice for Duende show ring not found error and the api throws error saying  Unable to obtain configuration from: 'https://xyz.azurewebsites.net/.well-known/openid-configuration'.

To tackle this i also used self signed certificates and tried to add the thumbprint in the code to be loaded when the identity duende server loads up but it also  fails to find the thumbprint. I also used the thumbprint of the current certificate provided by azure and still the error is same.

Code to load thumbprint is as under:
 public static X509Certificate2 LoadSigningCertificate(IWebHostEnvironment environment)
        {
            X509Certificate2 cert = null;
           
                string certThumbprint = "E44530E8C9AD621C2D500CEF536BA77BB9D9DDD";
                bool validOnly = false;

            using (X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
            {
                certStore.Open(OpenFlags.ReadOnly);

                X509Certificate2Collection certCollection = certStore.Certificates.Find(
                                            X509FindType.FindByThumbprint,
                                            // Replace below with your certificate's thumbprint
                                            certThumbprint,
                                            validOnly);

                // Get the first cert with the thumbprint
                if (certCollection.Count > 0)
                {
                    cert = certCollection[0];
                    //  Log.Logger.Information($"Successfully loaded cert from registry: {cert.Thumbprint}");
                }

                // Fallback to local file for development
                if (cert == null)
                {
                   throw new Exception($"failed to find certificated with thumbprint: {certThumbprint}");
         
                }
            }
            
            return cert;

        }
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**
Load the discovery url flawlessly
We expected to have the duende server load up on azure just like it was running on local IIS using dev cert provided by .net core template. 
**Log output/exception with stacktrace**
Category: Duende.IdentityServer.Services.KeyManagement.KeyManager
EventId: 0
SpanId: c91661b9fc2df7cf
TraceId: 6346df418b49fcbd94e21115a0599e4b
ParentId: 0000000000000000
RequestId: 80001c43-0000-f300-b63f-84710c7967bb
RequestPath: /.well-known/openid-configuration

Error unprotecting key with kid 67D5A52A4219385011409AD160B64ADF.

Exception: 
System.Security.Cryptography.CryptographicException: The key {392a443a-dbc5-4bbb-aa45-02f03af9b827} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435

```
data
```

**Additional context**
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://xyz.azurewebsites.net/.well-known/openid-configuration'.
 ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'https://xyz.azurewebsites.net/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 403, ReasonPhrase: 'Site Disabled', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: close
  Date: Thu, 08 Dec 2022 17:53:30 GMT
  Content-Length: 2342
  Content-Type: text/html
}'
What is the correct way to attach an ssl for duende identity on azure app service to be able to load the discovery document url and signing token flawlessly.

**Comment by josephdecock** [comment]
The exception you're getting indicates a DataProtection failure, not an SSL problem. There are a lot of ideas and links to documentation about data protection keys in the other issue we're you've commented about this problem. Can you take a look at those please?

**Comment by josephdecock** [comment]
Related: https://github.com/DuendeSoftware/Support/issues/373

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by Umar-Mukhtar** [comment]
Yes the issue was resolved by turning off auto key management and utilize
the app service managed certificate on azure by passing the thumbprint
value using code.

You can close this issue but send some references to understand automatic
key management.

Thanks.

**Comment by josephdecock** [comment]
Great, please see our docs on key management [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/).
