### ISSUE TITLE
IdentityServer Upgrade from 6.0 to 6.2

### ISSUE THREAD

**Issue by amrmelsayed** [DuendeSoftware/Support#388]
**Which version of Duende IdentityServer are you using?**
6.0

**Which version of .NET are you using?**
.NET 6

We are trying to upgrade our Identity Server installation from 6.0 to the latest version 6.2, the upgrade guide on the website only covers 6.1, can we upgrade directly to 6.2 or are there additional steps that we need to consider? Apologies, if that question is already covered in the documentation as I couldn't find it.

**Comment by josephdecock** [comment]
Thanks for raising that we need docs for this. Yes it is fine to upgrade directly to 6.2. There are no database schema changes needed between 6.1 and 6.2.

**Comment by amrmelsayed** [comment]
Got it, thank you.
