### ISSUE TITLE
ApiResourcesScopes - Upgrade from v3.1 to v6

### ISSUE THREAD

**Issue by gz-pcg** [DuendeSoftware/Support#390]
I have a question related to introduction of database table `ApiResourcesScopes`

In your article about `upgrading from IdentityServer4 v3.1 to v6` there is a briew paragraph about this new table:

"_In short, in IdentityServer4 v3 there was a parent-child relationship between the ApiResources and the ApiScopes. Then in IdentityServer4 v4 the ApiScopes was promoted to be its own top-level configuration. This meant that the child collection under the ApiResources was renamed to ApiResourcesScopes and it contained a reference to the new top-level ApiScopes."_  [link](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v3_to_dis_v6/)

The provided SQL migration script creates this table as follows
```
CREATE TABLE ApiResourceScopes (
    Id             INT            IDENTITY (1, 1) NOT NULL,
    Scope          NVARCHAR (200) NOT NULL,
    ApiResourceId  INT            NOT NULL,
    CONSTRAINT PK_ApiResourceScopes PRIMARY KEY CLUSTERED (Id ASC),
    CONSTRAINT FK_ApiResourceScopes_ApiResources_ApiResourceId FOREIGN KEY (ApiResourceId) REFERENCES ApiResources (Id) ON DELETE CASCADE
);
```
We dont have clear indication about second table.column this relates to.
I'm assuming its:
```
ApiResourceScopes.Scope == ApiScope.Name
```
as both of theese columns are nvarchar(200).

Is my assumption right? If so, this implicates that we need to ensure that rows in `ApiScopes` are unique, right?

**Comment by brockallen** [comment]
Have you looked through the upgrade guides?

https://docs.duendesoftware.com/identityserver/v6/upgrades/

**Comment by brockallen** [comment]
> If so, this implicates that we need to ensure that rows in ApiScopes are unique, right?

All scope names across both ApiScopes and IdentityResources need to be unique, yes.

**Comment by gz-pcg** [comment]
> > If so, this implicates that we need to ensure that rows in ApiScopes are unique, right?
> 
> All scope names across both ApiScopes and IdentityResources need to be unique, yes.

Ok, so the only part im uncertain is the linkage between `ApiResourceScopes and ApiScope`
But it seems like the way I've deduced

**Comment by brockallen** [comment]
Yes, the ApiResource has a string collection is ApiScope names that are associated.
