### ISSUE TITLE
Server-side sessions lifetime logic

### ISSUE THREAD

**Issue by nikriaz** [DuendeSoftware/Support#391]
I test Duende 6.2 with Asp.Net Core 7 with Identity.

The docs says: _As the client uses the refresh token at IdentityServer, the user’s session expiration will be extended. Be sure to configure the access token lifetime to be less than the server-side session lifetime at IdentityServer_

My initial reading of the docs was like the settings should be:

- RefreshTokenExpiration = Sliding
- RefreshTokenUsage = OneTime
- CoordinateClientLifetimesWithUserSession = true

Then, with every request of a new refresh token (=gets access token), user gets its session updated on the time specified in _SlidingRefreshTokenLifetime_. So "coordination" occurs **from lifetimes, specified for refresh token to session**.

However, apparently it's not true. The actual logic is the session is **always** extended with every access token request by the time, specified in _AccessTokenLifetime_, and ignores any refresh token settings. So, the "coordination" occurs in the direction **from session to refresh token.** Is this expected? 

This implies two important things:

- It's not possible to set absolute expiration time for the session
- All refresh token lifetimes become ineffective, if _CoordinateClientLifetimesWithUserSession_ is enabled

Maybe I missed something, or need to restart IdS every time as I change settings for clients? I just change values in DB and do login/logout for clients for experiments.

**Comment by josephdecock** [comment]
When you enable coordination, the following things happen:

- Expired sessions cause refreshing a token to fail
- Non expired sessions are extended when refresh tokens are used
  - The session is extended by the _cookie_'s lifetime 
- When server side sessions expire, the cleanup job (when it runs next, if it is enabled) will revoke refresh tokens obtained with that session 
- When users log out, all persisted grants (including refresh tokens) associated with the session are purged

> It's not possible to set absolute expiration time for the session

There's not a simple way to do this, but you could extend `DefaultSessionCoordinationService`, and add custom logic to `ValidateSessionAsync`. Something like this:

```
public override async Task<bool> ValidateSessionAsync(SessionValidationRequest request)
{
    if(CustomCodeHereThatChecksIfAbsoluteExpirationIsExpired)
    {
          return false;
    }
    return await base.ValidateSessionAsync(request);
}
```

> All refresh token lifetimes become ineffective, if CoordinateClientLifetimesWithUserSession is enabled
The refresh token lifetimes will still be used, but in some sense the user's session takes precedence - if you don't have a session anymore, your refresh token won't be usable.

**Comment by nikriaz** [comment]
Super, thanks! All these details are very good to know.

**Comment by nikriaz** [comment]
> * The session is extended by the _cookie_'s lifetime

I'm not sure, what you meant but cookie's lifetime is certainly not what set in user's session cookie `ExpireTimeSpan  ` setting or IdS cookie `Authentication.CookieLifetime` setting. It looks like the user's cookie lifetime is extended with every successful access token request by time which is set in its _AccessTokenLifetime_ So, actually, session is extended by this time. I'm not sure whether something else can change user's cookie's lifetime, which, in turn, set server side session lifetime.
