### ISSUE TITLE
How to check Identity Server Session from client side?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#392]
**Which version of Duende IdentityServer are you using?**
v6.1.5

**Which version of .NET are you using?**
v6.0.0

**Describe the question**

How to check whether the Identity Server Session is alive or not from the client side?

**Additional context**

We have two different clients Site A and Site B. A user can interact with both sites and redirect from one site to another. Both sites have different clients and can be accessed with/without authentication. 

Everything is working as accepted but the problem arises when the user login to one site(A) and now redirects to another site(B) then the site B still shows the login option to the user even though the user already logged into the IdentitySerever from Site A.

Now, some may say that just initiating the code flow will log the user in without credentials since the user is already logged in to IS. But We can not initiate the Code flow every time as this site can be accessed without login too. Therefore, the question is how to check whether the IdentityServere session is alive or not. If it is alive then the Sites initiates the Code Flow and generates the token.

Also, any chances to use the check-session endpoint here? Or any other options?

Thanks!

**Comment by josephdecock** [comment]
check-session isn't normally used like this, and it has some issues with browsers that block 3rd party cookies. An alternative is to have an intermediate page that initiates code flow by requiring authorization. Then that intermediate page forwards the user along to a final url, which you could pass as a query parameter. Make sure to validate that the parameter is a local url to prevent open redirector attacks.

**Comment by josephdecock** [comment]
Closing this issue, but feel free to reopen if necessary.
