### ISSUE TITLE
`EmitIssuerIdentificationResponseParameter` not affecting discovery document 

### ISSUE THREAD

**Issue by saevarma** [DuendeSoftware/Support#395]
**Which version of Duende IdentityServer are you using?**

6.1.2

**Which version of .NET are you using?**

6.0

**Describe the bug**

We have disabled the `iss` parameter to be emitted in authorization responses in our IDS setup. using the `EmitIssuerIdentificationResponseParameter` options on `AddIdentityServer`. This option does not seem to change the `authorization_response_iss_parameter_supported` property in the discovery document (`.well-known/openid-configuration`).

This is not according to [RFC 9207](https://www.rfc-editor.org/rfc/rfc9207#section-2.3-3.2.1) that states that server must indicate its support with the `authorization_response_iss_parameter_supported`.

**To Reproduce**

Here is link to a repo with the quickstart app that demonstrates this issue:

https://github.com/saevarma/duende-ids-repro

**Expected behavior**

The value of `EmitIssuerIdentificationResponseParameter` is reflected in the `authorization_response_iss_parameter_supported` property in the discovery document.

**Comment by josephdecock** [comment]
Thanks for this report @saevarma. We'll consider making this change, and I've created an issue in the main repo: https://github.com/DuendeSoftware/IdentityServer/issues/1113

**Comment by josephdecock** [comment]
This is now merged and released in 6.2.1!
