### ISSUE TITLE
How to properly redirect to Account Register Page (React SPA, BFF, IdenityServer Arch)

### ISSUE THREAD

**Issue by tomKrueger** [DuendeSoftware/Support#40]
**Which version of Duende BFF are you using?**
6.01

**Which version of .NET are you using?**
net6.0

**Describe the questoin**

I have BFF setup with React JS SPA.  

React SPA -> BFF Service -> IdentityServer Service

It is working for login and logout.  I am trying to get to the Account/Register page that I have in my IdentityServer.

For Login: This works!!
const onLoginClick = () => {
        window.location = "/bff/login";
    };

For Register: I would like this to work but not sure how to configure.
const onRegisterClick = () => {
        window.location = "/bff/register";
    };
    
I assume the BFF Service will need to redirect to IdentityServer Service.  I would prefer it is handled in the BFF setup so that I don't have to know the IdentityServer domain in two spots.

Thanks!
Tom

**Comment by leastprivilege** [comment]
Right now there is no built-in server side register endpoint - but we could think about making that extensible in the future.

But the easiest way to solve this would be to provide a simple server side endpoint yourself to do the right redirect.

**Comment by brockallen** [comment]
Also, I'd almost expect your ~/register endpoint would want to add custom values to the OIDC request (e.g. acr_values) so you'd almost always need to have a custom endpoint to coordinate that.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
