### ISSUE TITLE
ID4 to ID6

### ISSUE THREAD

**Issue by JulBen96** [DuendeSoftware/Support#402]
**Which version of Duende IdentityServer are you using?** trying to migrate from 4 to 6

**Which version of .NET are you using?** 6

on version ID4 we used the IdentityServer4.AccessTokenValidation. IS there something that is replacing it in ID6?
 services.AddAuthentication(**IdentityServerAuthenticationDefaults**.AuthenticationScheme)

**Comment by josephdecock** [comment]
IdentityServer4.AccessTokenValidation is deprecated and not being maintained anymore. Read this blog post about the reasoning and recommedations for a superior and more flexible approach: https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/

**Comment by JulBen96** [comment]
Yeah I saw it yesterday late in evening, and fix it vor version 6. thanks for the info.

**Comment by JulBen96** [comment]
I have another problem with this... , when I run the following command, I receive an error. How to fix it?

`dotnet ef migrations add UpdateToDuende_v6_0 -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb`

An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Value cannot be null. (Parameter 'Certificate  not found.')
Unable to create an object of type 'PersistedGrantDbContext'

**Comment by josephdecock** [comment]
You might need to install or update Microsoft.EntityFrameworkCore.Tools.

**Comment by JulBen96** [comment]
Finally found the problem was missing certificat file locally
