### ISSUE TITLE
How to remove unnecessary claims added with CreateAsync(TUser user) to avoid http 431

### ISSUE THREAD

**Issue by buddhikaw** [DuendeSoftware/Support#405]
**Which version of Duende IdentityServer are you using?**
6.0.0
**Which version of .NET are you using?**
.Net Core 6.0
**Describe the Situation**
I'm trying identity server to sign in user. In implicit flow, at PasswordSignInAsync() it creates header cookies and these are very large due to lot of role claims in asp.net identity storage. These claims are not required in my case.
Then due to large size of the header, when callback goes to Authorize endpoint it fails with HTTP 431.  

I found that [Duende.IdentityServer.AspNetIdentity , Task<ClaimsPrincipal> CreateAsync(TUser user)](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/AspNetIdentity/UserClaimsFactory.cs#L26) method overrides the default AspNetCore.Identity CreateAsync(TUser user).

I would like to know any guidance on How to access claim principal and remove these claims before it return the result.

**Comment by damikun** [comment]
Try this:

```
 serviceCollection.AddIdentity<ApplicationUser, IdentityRole>(options =>
  {
   // Identityserver cfg
  }).AddClaimsPrincipalFactory<ClaimsPrincipalFactory>()  // <- Register Factory behind identityserver...
```

```
public sealed class ClaimsPrincipalFactory : UserClaimsPrincipalFactory<ApplicationUser,IdentityRole>
{
    public ClaimsPrincipalFactory(
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
        IOptions<IdentityOptions> optionsAccessor
    )
            : base(userManager, roleManager,optionsAccessor)
    {

    }

    protected override async Task<ClaimsIdentity> GenerateClaimsAsync(ApplicationUser user)
    {
        var identity = await base.GenerateClaimsAsync(user).ConfigureAwait(false);

        identity.RemoveClaim(....)
       
        return identity;
    }
}
````

**Comment by buddhikaw** [comment]
I think this is perfect solution for asp.net identity with + duende. Filtering with this factory method applies to everywhere like Asp.net cookies and tokens.
Thank you very much !
