### ISSUE TITLE
Upgrade to ID6 default page problem

### ISSUE THREAD

**Issue by JulBen96** [DuendeSoftware/Support#407]
**Which version of Duende IdentityServer are you using?** 6

**Which version of .NET are you using?** 6

We migrate from ID4 to ID6. now when I ran the identity server it didnt default to custom login url. we have this set but it didnt redirect to it options.UserInteraction.LoginUrl

**Comment by josephdecock** [comment]
What is happening at the network level when you authenticate? Is the authorize endpoint redirecting somewhere? If so, where? Can you share your startup configuration that configures IdentityServer and the Authentication service?

**Comment by JulBen96** [comment]
Finally, the problem was this

 services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                **options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;**
            })
            
            I've remove it and it work
