### ISSUE TITLE
How to create/apply BFF EF Serverside Session Migration?

### ISSUE THREAD

**Issue by zarinbal** [DuendeSoftware/Support#408]
**Which version of Duende BFF are you using?**
2.0

**Which version of .NET are you using?**
6.0
**Describe the bug**
I am trying to use the Entity Framework for the Server-side Session Store. However, the following document does not provide how to create/apply the required migrations for the SessionDBContext. 

[https://docs.duendesoftware.com/identityserver/v6/bff/session/server_side_sessions/](https://docs.duendesoftware.com/identityserver/v6/bff/session/server_side_sessions/)

Here is my implementation, and I wanted to ensure this is a good way. 

   ```
 public class DbContextFactory : IDesignTimeDbContextFactory<SessionDbContext>
    {
        public SessionDbContext CreateDbContext(string[] args)
        {
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();


            var dbContextBuilder = new DbContextOptionsBuilder<SessionDbContext>();

            var connectionString = configuration.GetConnectionString("SessionConnection");

            dbContextBuilder.UseNpgsql(connectionString, b => b.MigrationsAssembly(Assembly.GetExecutingAssembly().FullName));

            return new SessionDbContext(dbContextBuilder.Options)
            {
                StoreOptions = new SessionStoreOptions()
            };
        }
        public static void MigrateDatabase(string connectionString)
        {
            var dbContextBuilder = new DbContextOptionsBuilder<SessionDbContext>();
            dbContextBuilder.UseNpgsql(connectionString, b => b.MigrationsAssembly(Assembly.GetExecutingAssembly().FullName));
            using (var context = new SessionDbContext(dbContextBuilder.Options)
            {
                StoreOptions = new SessionStoreOptions()
            })
            {
                context.Database.Migrate();
            }
        }
    }

```

And Here is the migration command
`add-migration InitialSessionDbMigration -c SessionDbContext -o Data/Migrations/IdentityServer/SessionDb`

Here is the code for  Program.cs
```
string strSessionConnectionStrting = builder.Configuration.GetConnectionString("SessionConnection");
DbContextFactory.MigrateDatabase(strSessionConnectionStrting);
builder.Services.AddBff(options =>
                        {
                            options.ManagementBasePath = "/bff";
                            options.EnableSessionCleanup = true;
                        })
                .AddRemoteApis()
                .AddEntityFrameworkServerSideSessions(options =>
                {
                    options.UseNpgsql(strSessionConnectionStrting);
                });
```

If this is good, it would be beneficial to add it to the documentation or the sample. It took me some time to figure it out especially with StoreOptions  and different assembly names. I had to read the source codes to get the right pieces.

**Comment by josephdecock** [comment]
Thanks for bringing this to our attention - we are definitely going to add this to our docs. Your implementation looks fine. For another example, take a look at this: https://github.com/DuendeSoftware/BFF/tree/main/migrations/UserSessionDb.
