### ISSUE TITLE
Integrating with API for user credential validation and claims

### ISSUE THREAD

**Issue by tibiiorcdw** [DuendeSoftware/Support#41]
**Which version of Duende IdentityServer are you using?**
Version 6

**Which version of .NET are you using?**
.NET 6

We would like to integrate the user credentials validation using APIs (validate user credentials, retrieve user, retrieve user cliams) and initially we thought we can create a custom user store and implement our APIs in it. But we don't see an interface for a custom user store. What would be the best approach for us to integrate with APIs.

**Comment by leastprivilege** [comment]
For authentication, you would call your APIs on the login page.

For retrieving user claims, you would implement the `IProfileService`
https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/
