### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by olsh** [DuendeSoftware/Support#411]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
6.0

IdentityServer4 + [the package](https://github.com/alexvaluyskiy/prometheus-net-contrib#identity-server) exposed some useful prometheus metrics like
idsrv_client_authentication_success_total
idsrv_client_authentication_failure_total

Does the new Duende server have something similar?

**Comment by leastprivilege** [comment]
We do support open telemetry tracing.
https://docs.duendesoftware.com/identityserver/v6/diagnostics/otel/

We are waiting for the finalization of OTEL metrics, but if you want something more specific, you could instrument the various events yourself for the time being.

**Comment by olsh** [comment]
Yes, we've already set up the OTel tracing.

> We are waiting for the finalization of OTEL metrics, but if you want something more specific, you could instrument the various events yourself for the time being.

Yes, we've thought about the custom instrumentation. But wanted to ensure that you don't provide the metrics out of the box.

**Comment by leastprivilege** [comment]
Nothing right now.
