### ISSUE TITLE
/connect/token endpoint response for Client_credentials include scope property which is not in the standard

### ISSUE THREAD

**Issue by nvhoanganh** [DuendeSoftware/Support#412]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0

**Describe the bug**
/connect/token endpoint response for Client_credentials include scope property which is not in the standard. For example Auth0, Azure AD does not return this property

**To Reproduce**

Call it like this:

POST https://demo.duendesoftware.com/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=api&client_id=m2m&client_secret=secret

**Expected behavior**

Response should not include "scope" property

**Log output/exception with stacktrace**

NA

**Additional context**

NA

**Comment by leastprivilege** [comment]
Maybe AAD and Auth0 got it wrong... ;)

https://www.rfc-editor.org/rfc/rfc6749#section-5.1
