### ISSUE TITLE
UsePkce = false does not disable PKCE

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#413]
Duende v6.1.1
.NET 6.0

If I attempt to disable PKCE, the code_challenge parameter is still required in the URL (and the code_challenge_method). Are there additional steps needed to remove this requirement?

**Comment by StuFrankish** [comment]
Have you checked your `ClientEntity` configuration to see if the `RequirePkce` property is set to `false`?

**Comment by billcunnien** [comment]
Perfect! Somehow I missed that in the docs. Much appreciated!!
