### ISSUE TITLE
Audience missing from JWT when Require resource indicator set on resource

### ISSUE THREAD

**Issue by andrewclymer** [DuendeSoftware/Support#414]
**Which version of Duende IdentityServer are you using?**
6.1.5
**Which version of .NET are you using?**
.NET 6
**Describe the bug**
When the resource indicator is set and the resource has require resource indicator property set to true. Generated JWT does not have an audience property.

**To Reproduce**

scope.325908 is a shared scope
Two resources have the scope
urn:repro/325908 and urn:repro/325908-2

Make a request with a resource indicator
Resource is not configured to Require Resource Indicator 

resource : urn:repro/325908
scopes : openid profile scope.325908

Produces a JWT

{
  "iss": "https://localhost:63024",
  "nbf": 1671706766,
  "iat": 1671706766,
  "exp": 1671710366,
  "aud": "urn:repro/325908",
  "scope": "openid profile scope.325908",
  "amr": [
    "external"
  ],
  "client_id": "demo-client",
  "sub": "600808ab-8a13-41ae-b1a2-6ee4cd95aa2d",
  "auth_time": 1671706550,
  "idp": "okta",
  "sid": "B8CBC639AB773B93E943601333DB6C71",
  "jti": "39C722A0E702893F22AF0261F7802CA3"
}

The audience has been set correctly, as expected.

Set Require Resource Indicator on the urn: repro/325908 resource and repeat the same request.

Return JWT is

{
  "iss": "https://localhost:63024",
  "nbf": 1671707180,
  "iat": 1671707180,
  "exp": 1671710780,
  "scope": "openid profile scope.325908",
  "amr": [
    "external"
  ],
  "client_id": "demo-client",
  "sub": "600808ab-8a13-41ae-b1a2-6ee4cd95aa2d",
  "auth_time": 1671707175,
  "idp": "okta",
  "sid": "4AEB28E180ACCC0C8D576A7CE961A060",
  "jti": "3E5633071AB539323E5F7F6724208C6C"
}

**Expected behaviour**

I was expecting an audience, as per the request without Require resource indicator set to true

**Comment by josephdecock** [comment]
Thanks for this bug report. So far, I haven't been able to reproduce it unfortunately. If you are seeing this with in-memory configuration, could you share the client, resource, and scope configuration code please?

**Comment by brockallen** [comment]
We have merged the PR with the offline_access issue. Can this issue also be closed?
