### ISSUE TITLE
OAuth code flow using Popup

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#418]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the question**
We are using an OAuth Code flow to log in users for multiple clients which is working fine. As per the standard OAuth Code flow, it redirects the user to the Identity Server login page. Although it is a standard approach, the users are feeling that they are login to external sites.

To improve the UX, we are thinking to complete the OAuth code flow using a popup instead of a redirection similar to [google](https://developers.google.com/identity/oauth2/web/guides/use-code-model). Is there any client library of the Identity Server default feature available to achieve this?

**Comment by josephdecock** [comment]
IdentityServer supports the standard DisplayMode parameter, which allows you to indicate in your authorization request that you would like a popup. Your login page can check the DisplayMode to render differently in a popup.

**Comment by StuFrankish** [comment]
> IdentityServer supports the standard DisplayMode parameter, which allows you to indicate in your authorization request that you would like a popup. Your login page can check the DisplayMode to render differently in a popup.

Have you got an example of this please? This is something I'd like to experiment with as well.

**Comment by PratikPatel-Mtech** [comment]
@josephdecock Thanks! But I do not find anything regarding the DisplayMode=popup in the Duende document. Could you please share a sample or document link? 

I have followed this [link](https://github.com/arye321/nextauth-google-popup-login) and it seems to work fine without using any DisplayMode.  

What is the role of DisplayMode in the Identity Server?

**Comment by josephdecock** [comment]
Display mode is a part of the OIDC specification, which is set with the display parameter in the authorization request. The OIDC spec defines it:

>display
>OPTIONAL. ASCII string value that specifies how the Authorization Server displays the authentication and consent user interface pages to the End-User. The defined values are:
> 
>page
>The Authorization Server SHOULD display the authentication and consent UI consistent with a full User Agent page view. If the display parameter is not specified, this is the default display mode. 
>
>popup
>The Authorization Server SHOULD display the authentication and consent UI consistent with a popup User Agent window. The popup User Agent window should be of an appropriate size for a login-focused dialog and should not obscure the entire window that it is popping up over.

IdentityServer supports this parameter by parsing it and including it in the `AuthorizationRequest` [model returned by the Interaction Service](https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/#authorizationrequest). Your login page can use that value to render a different layout or user experience appropriate for a popup window.

**Comment by josephdecock** [comment]
Communication between the main application window and the popup window will also be a challenge. You have to coordinate state so that when the signup is done the popup, the main application knows that you are now authenticated. What exactly that coordination looks like depends on your front end architecture.

**Comment by josephdecock** [comment]
I'm also curious to know what about the user experience is suggesting to your users that they are logging in to an external site. Is the problem branding?

**Comment by PratikPatel-Mtech** [comment]
@josephdecock Thanks for the details regarding the DisplayMode. What I understood from it is that, the Identity Server implicitly does nothing with the DisplayMode except binding it to `AuthorizationRequest`, but we can constomize the login UI based on the received DisplayMode values in the /authorize request.

**Comment by PratikPatel-Mtech** [comment]
> I'm also curious to know what about the user experience is suggesting to your users that they are logging in to an external site. Is the problem branding?

That is the stackholders perspectives. Basically, they are comparing it with the legacy authentication(without the Identity Server authentication where login was done within the same site via model), on contrary the Identity Server uses a different login page and domain. As a standard OAuth code flow redirects user from Site A(a.site.com) to Identity Server(id.site.com. That's how they called it external.

**Comment by StuFrankish** [comment]
> > I'm also curious to know what about the user experience is suggesting to your users that they are logging in to an external site. Is the problem branding?
> 
> That is the stackholders perspectives. Basically, they are comparing it with the legacy authentication(without the Identity Server authentication where login was done within the same site via model), on contrary the Identity Server uses a different login page and domain. As a standard OAuth code flow redirects user from Site A(a.site.com) to Identity Server(id.site.com. That's how they called it external.

You can always customise the login experience to better suite company branding.
For example, in my company's instance of Identity Server, the user interface has been heavily modified so that there is a corporate background image and above the username/password input is the logo of the application the user is about to sign into.

Ours is similar to this, but flipped to the left.
![image](https://user-images.githubusercontent.com/5624629/209926380-468479dd-f0dc-4f99-ac9b-0d1b3b64fde4.png)

**Comment by josephdecock** [comment]
> Identity Server implicitly does nothing with the DisplayMode except binding it to AuthorizationRequest, but we can constomize the login UI based on the received DisplayMode values in the /authorize request.

Correct

>That is the stackholders perspectives. ... As a standard OAuth code flow redirects user from Site A(a.site.com) to Identity Server(id.site.com. That's how they called it external.

Again, that's correct. You can probably recreate the old experience using a popup, but you might also consider if you can helpthe stakeholders to understand that their login experience is in line with modern standards, and should be familiar to users who login with other external IdPs all the time (google, microsoft, etc).

Good luck, and feel free to reopen this thread if you need more help!
