### ISSUE TITLE
BFF License key required

### ISSUE THREAD

**Issue by ITSTord** [DuendeSoftware/Support#419]
**Which version of Duende BFF are you using?**
7
**Which version of .NET are you using?**
7
**Describe the bug**
Not a bug just a general question related to documentation that states license key is only needed for production. But we get an error in dev for missing licensekey in our frontend using the BFF package. Should we then just use production licensekey in dev and test?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
I'm assuming that by an error you mean a warning message in your logs. That can be ignored in your non-production environments. The license validation should not cause a run time error - is it?

**Comment by josephdecock** [comment]
Also, it is fine to use the license in your non-production environments to remove the warning.
