### ISSUE TITLE
Nice to have: Expose license status

### ISSUE THREAD

**Issue by EliaSaSe** [DuendeSoftware/Support#42]
**Which version of Duende IdentityServer are you using?**

6.0.4

**Which version of .NET are you using?**

.NET 6.0

**Describe the bug**

Hi

To ensure we are always running with a valid license, I want expose the license status to a monitoring endpoint.

Currently ``Duende.IdentityServer.Validation.LicenseValidator`` is internal and the license status is only reported to a logger implementation.

**To Reproduce**

No simple way to access the validation result of ``LicenseValidator``.

**Expected behavior**

Nice to have: A simple way to ask the IdentityServer Framework if the license is good.
* A boolean to indicate if the license is valid
* Optional: A message indicating the issue with the license
* Optional: A accessible data structure like ``Duende.IdentityServer.Validation.License``

**Log output/exception with stacktrace**

NA

**Additional context**

Workaround: I could copy the class ``LicenseValidator`` to my user code and modify the outputs for my needs. Then I can run my own license check. But if your license validation details changes, I will get wrong results.

Workaround: I could monitor the log stream of ``Duende.IdentityServer.Validation``, but it would be easier if I can ask the service directly.

**Comment by brockallen** [comment]
Would you want this just at startup, or would you want this to trigger if something at runtime detected a violation (e.g. client count was exceeded the allowed limit)?

**Comment by EliaSaSe** [comment]
Our monitoring is calling the health endpoint periodically (polling). So if IdentityServer can give us runtime data on request, we can degrade the service health during runtime.

In our use case a trigger/event/callback is not needed, we don't push state.

But this feature is nice to have to help us to detect issues. If it's complicated to get runtime data, just a startup validation would also help.

**Comment by EliaSaSe** [comment]
Ah... maybe a simple solution for the runtime data: a (resettable?) violation counter. We can degrade health if `counter > 0`

**Comment by brockallen** [comment]
Since I opened an issue to track, I'll close this one. Thanks!
