### ISSUE TITLE
Reference token and Blazor web assembly

### ISSUE THREAD

**Issue by louisbouchard** [DuendeSoftware/Support#422]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by louisbouchard** [comment]
Hello.
IDP and API side are configured to support reference token (like secret, etc).  But something should probably change app side.  Any idea?

Thank you

**Comment by leastprivilege** [comment]
From a client point of view, JWTs and reference tokens behave exactly the same.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
