### ISSUE TITLE
Accessing different Tenants in different browser tabs

### ISSUE THREAD

**Issue by apoutney** [DuendeSoftware/Support#426]
Using Identity Server 6 and .Net 6 for the ID server and React Client

I have a multi tenant system using IdentityServer for authentication. 

Users access the system via a single client application built in React and the users tenancy is determined by the subdomain they navigate to

There are no cross tenant users however a person may have a individual user accounts on multiple tenancies(subdomains).

This all works fine when a user is logging in, access is rejected if a user tries to log on via the wrong subdomain.  

However I have an issue where a user can log on to the correct subdomain, open a new browser tab and navigate to a different subdomain and because they already have a valid token in the browser cache they are automatically logged in.

I need to be able make it so that when they navigate to a different subdomain in a new tab it takes them to the login screen for that subdomain so that they can log in with a different user.  And hopefully be able to switch between the tabs and perform actions as the correct user for each subdomain.

Hopefully this makes sense and someone can point me in the right direction to achieve this if it is at all possible?

Any advice would be greatly appreciated

**Comment by josephdecock** [comment]
OIDC doesn't include the notion of tenancy in a standard way. IdentityServer adds support for tenancy by using the standard acr_values parameter. When you initiate a login, you can include in the acr_values a string in the form "tenant:some-example-tenant". If you do, IdentityServer will parse that acr_value and use it to set the tenant property on the AuthorizationRequest model. Your login page can use that property to customize the user experience based on tenant. Furthermore, the tenant is then included in the user's session as the tenant claim. 

These two values can be used to compare the tenant used in the current session (if it exists) with the tenant used in the current request. IdentityServer has an option to do so:

ValidateTenantOnAuthorization. 
>Specifies if a user's *tenant* claim is compared to the tenant *acr_values* parameter value to determine if the login page is displayed

A few more references on this material can be found here:
- https://docs.duendesoftware.com/identityserver/v6/ui/login/session/#well-known-claims-issued-from-the-login-page
- https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/#authorizationrequest

**Comment by josephdecock** [comment]
One other thing to think about is that, if your requirement is to actually have two distinct concurrent sessions at these two applications across tenants, then you actually need to have separate instances of identity server that will issue distinct authentication cookies. The method I'm describing above ends the session of the first tenant when you sign in to the second.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
