### ISSUE TITLE
Is there any way to change path of CheckSessionCookie?

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#427]
**Which version of Duende IdentityServer are you using?**
v6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the question**
We have a requirement to access the check session cookie in a different subdomain. As it is possible to update the domain using the configuration `options.Authentication.CheckSessionCookieDomain`. But it is still not accessible because of the cookie path. Our Identity Server has a base path like `/idp`. So, the check session cookie path is `/idp` which is not accessible on other sites because it does not have similar paths.

I have checked the configuration and looks like no configuration to change the path. 

Could you please suggest a way to update the check session cookie path to `/`?

**Comment by josephdecock** [comment]
You can control the session cookie's path (and all its other cookie options) by extending `DefaultUserSession` and overriding its `CreateSessionIdCookieOptions`.

The default implementation does this:
```cs
    /// <summary>
    /// Creates the options for the session cookie.
    /// </summary>
    public virtual CookieOptions CreateSessionIdCookieOptions()
    {
        var secure = HttpContext.Request.IsHttps;
        var path = Urls.BasePath.CleanUrlPath();

        var options = new CookieOptions
        {
            HttpOnly = false,
            Secure = secure,
            Path = path,
            IsEssential = true,
            Domain = CheckSessionCookieDomain,
            SameSite = CheckSessionCookieSameSiteMode
        };

        return options;
    }
```
Yours could set the path differently if desired.

**Comment by PratikPatel-Mtech** [comment]
@josephdecock thanks! We'll try out this. Do you think the path parameter be part of the configuration?

**Comment by josephdecock** [comment]
We can consider adding a check session cookie path option. @brockallen, @leastprivilege - thoughts?

**Comment by josephdecock** [comment]
We've decided to continue to rely on our existing extensibility point and not add more options. Thanks for the idea though.
