### ISSUE TITLE
Getting SessionId after calling HttpContext.SignInAsync(...)

### ISSUE THREAD

**Issue by StuFrankish** [DuendeSoftware/Support#428]
**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer (6.2.0)
Duende.IdentityServer.AspNetIdentity (6.2.0)
Duende.IdentityServer.EntityFramework (6.2.0)
Duende.IdentityServer.Storage (6.2.0)

**Which version of .NET are you using?**
.Net 7.0.1

**Describe the bug**
I'm unable to get the `SessionId` value that is stored in `dbo.ServerSideSessions` when a user logs in.

**To Reproduce**
As part of our login process, we create a `LoginHistory` record that includes information about the client browser and user.
I want to be able to map this data with the `ServerSideSessions` data stored by IdentityServer.

Our AccountController calls `HttpContext.SignInAsync(...)` then checks the `HttpContext.Session.Id` value.
But the value stored by Identity Server does not match against the value shown in `HttpContext.Session.Id`

Is there a way to get the server side session data out when `HttpContext.SignInAsync(...)` is called so I can then use the `SessionId`?

**Comment by josephdecock** [comment]
I think what you're looking for is the sid (session id) claim in the User object. 

There are two different but related concepts that are both referred to as sessions: there's a general purpose http session that tracks state over multiple http requests. This is what you're getting when you refer to HttpConext.Session. This session data can be tracked even if the user is anonymous (e.g., putting things in your shopping cart before you log in).

Separately from that, there's the notion of an authentication session. An authentication session is again tracking state over a sequence of http requests, but in an authentication session, there is an authenticated user associated with that state. By default in ASP.NET, authentication sessions are stored entirely within a data protected cookie. Whenever an http request comes in with such a cookie, the user can be authenticated based on that. There are pros and cons to this design, but notably, there is no way to interact with the authentication session state unless the user makes an http request and presents their session cookie to your application. Server side sessions change that by moving the session data into a server side data store. Regardless of where the authentication session is stored, there will be a claim within the session called sid, which is the session id.

One other thing to note is that calling SignInAsync will issue a session cookie, but it does not change HttpContext.User.

**Comment by StuFrankish** [comment]
Hi @josephdecock thanks for the quick reply.
I think I might be missing something then, I'm not sure how to get hold of that SID claim from within Identity Server at the point the SignInAsync method is called.

As an oversimplified example, this snippet demonstrates what I'm trying to do during the login process;
```c#
var user = _userRepository.GetUserByUsername(model.Username);
<validation logic snipped>

var idsUser = new(user.SubjectId) { DisplayName = user.FullName };
await HttpContext.SignInAsync(user: idsUser, GetAuthenticationProperties());

await ServiceFactory.SecurityServices.AddUserLoginHistoryAsync(login: new()
{
    Intent = Intent.SignIn,
    SubjectId = user.SubjectId,
    SessionId = "<sessionid>",
    LoginDate = DateTime.Now,
    IPAddress = RemoteIPAddress,
    UserAgent = Request.Headers[key: "User-Agent"].ToString()
});
```
I had hoped that when you said that the SID claim would be available in the user object, that you meant the `IdentityServerUser` object that I passed into the SignInAsync method.
However, after calling SignInAsync as above, the `idsUser` object doesn't appear to change, but a record has been added to the ServerSideSessions table.

My intention is to bolster as much as possible any and all auditable info we can get our hands on, so being able to attribute a specific session with a login event containing browser & IP address information, is highly desirable for us.

**Comment by brockallen** [comment]
@StuFrankish This might be the API you're looking for: https://github.com/DuendeSoftware/IdentityServer/blob/ffa4da997b44dcb32103bb26a919fb14cd1cf0f5/src/IdentityServer/Services/IUserSession.cs#L31

@josephdecock I guess we don't have formal docs for the `IUserSession` service. Perhaps we should add this to the backlog.

**Comment by josephdecock** [comment]
@brockallen: sounds good

@StuFrankish: I should clarify that the sid is a claim in the tokens produced by IdentityServer, but in the session of IdentityServer itself it is actually stored as an authentication property. The API that Brock linked to above is probably the easiest way to get at it, but there's a little bit of a wrinkle. 

The session id is created when you call `SignInAsync` and then two relevant things happen:
1. The session is written to the `ServerSideSessionStore`. This includes all your claims as well as authentication properties (notably the authentication property of the session id)
2. A corresponding auth cookie is added to the http response

The authentication of the current http request is not affected by calling `SignInAsync`. `HttpContext.User` is set by the auth middleware to be the identity associated with the current http request. The request didn't send an auth cookie, so the request is actually anonymous, and it remains anonymous, even though you've been sent credentials, validated those credentials, and are now calling sign in. Throughout the lifetime of the entire http request, `HttpContext.User` remains the same. This means that, immediately after you've called `SignInAsync`, you don't have access to the new session in the `HttpContext` or really anywhere else that is convenient. The new session is now in the store and a reference to it is in a data protected cookie header in the response. But the actual session is not easy to get at. `SignInAsync` just returns a task, so you can't use its results meaningfully here either. 

One imperfect option would be to call `IServerSideSessionStore.GetSessionsAsync` filtering on the just signed in user's subject id. This would return all of the user's sessions (maybe they also have a session on their phone or other device) and you want just the one that they are creating now. Presumably the most recent session is the one that was just created, so you could sort the results by creation time and take the most recent one. As I say, this is an imperfect solution - it involves extra database lookups just to enrich a log, and we're using a heuristic to get the session id to log. 

Now, in subsequent http requests, the auth cookie should be sent. That cookie will then be used to authenticate those subsequent requests, and so you would have the ability to get at the session id using `IUserSession.GetSessionIdAsync`, as Brock suggested. 

Given that, I would consider moving the logging somewhere else that will be invoked on a subsequent http request. One such place would be into an `AuthorizeInteractionResponseGenerator`. The idea would be that, after the user logs in, you always redirect them back to the /connect/authorize endpoint. At that endpoint, IdentityServer resumes the OIDC flow back to the application. When the browser follows that redirect, you'll get the session cookie back, and then have easy access to the session id. You could insert your logging logic into the flow with something like this:

```csharp
public class LoggingAuthIntRespGen : AuthorizeInteractionResponseGenerator
{
    public override async Task<InteractionResponse> ProcessInteractionAsync(
        ValidatedAuthorizeRequest request, ConsentResponse consent = null)
    {
        var result = await base.ProcessInteractionAsync(request, consent);

        // Check if the authorize endpoint was going to send you to an error
        // page, the login page, the consent page, or another custom page. If
        // none of those are happening, then we know the user is about to be
        // redirected back to the client application, so we want to insert our 
        // logging. 
        if(!(result.IsError || result.IsLogin || result.IsConsent || result.IsRedirect))
        {
            // Logging here
        }

        return result;
    }
}
```

To be clear, this isn't the same thing as logging when a session starts - this logging will also happen during single sign on scenarios. The user isn't necessarily starting their session here, they might be using their existing session to log into another application. But, if you logged the session ids here, presumably in an audit you'd be able to reconstruct exactly what happened anyway.

**Comment by StuFrankish** [comment]
Thank you both - I think I'll take a step back on this and re-assess what I think we need going forward in terms of audit enrichment. I definitely don't want to enrich logs based on incorrect data if there's a possibility that the last created server side session could be someone else's login.

It's a shame that `SignInAsync(..)` doesn't return some model that can be made additional use of, that would be too convenient!

It sounds like logging via an `AuthorizeInteractionResponseGenerator` is the way we want to go as I was wondering next on how to capture those events.

For now, I'll close the issue and open a new one if I need to.
Thanks again!

**Comment by StuFrankish** [comment]
Thanks @josephdecock 
Initially I assumed I could get the from the `ControllerBase.HttpContext` that `SignInAsync()` was being run on but I got nothing back.

I'll pull in IUserSession and give that a go now.

**Comment by StuFrankish** [comment]
That's got it, that's exactly what I needed!
```c#
await HttpContext.SignInAsync(user: new IdentityServerUser(user.SubjectId) { DisplayName = user.FullName }, GetAuthenticationProperties());
var sessionId = await _userSession.GetSessionIdAsync();
```

Thank you very much :)
