### ISSUE TITLE
/bff/user endpoint is not returning custom claim

### ISSUE THREAD

**Issue by michelletimmons** [DuendeSoftware/Support#429]
**Which version of Duende BFF are you using?**
1.2.3

**Which version of .NET are you using?**
5.0

**Describe the bug**

Our Identity Server is set up to return a custom identity claim. This custom claim can be requested by any of our 3 clients (a web app that uses BFF, a mobile app, and a simple JavaScript SPA we sometimes use for testing).

The mobile app and JavaScript SPA are able to retrieve this custom claim via the id token or the /connect/userinfo endpoint, but the BFF web app is not able to retrieve it. I would expect it to be available via the /bff/user endpoint, but it's not included there.

**To Reproduce**

In IdentityServer, I have added the custom claim as an IdentityResource in Config.cs:

`new IdentityResource("myCustomClaim", userClaims: new[] { "myCustomClaim" })`

and I've added it as an allowed scope for all 3 clients in appsettings.json:

`"AllowedScopes": [ "MyAPI", "openid", "myCustomClaim" ],`

and I've overridden UserClaimsPrincipalFactory.cs to actually generate the value for the claim.

In the BFF web app, I've got this in ConfigureServices:

```
            .AddOpenIdConnect("oidc", options =>
            {
                // confidential client using code flow + PKCE + query response mode
                options.Authority = Configuration.GetValue<string>("OpenId:Authority");
                options.ClientId = "MyWebApp";
                options.ClientSecret = Configuration.GetValue<string>("OpenId:ClientSecret");
                options.ResponseType = "code";
                options.ResponseMode = "query";
                options.UsePkce = true;                              
                options.SaveTokens = true;

                // request scopes
                options.Scope.Clear();
                options.Scope.Add("MyAPI");
                options.Scope.Add("openid");
                options.Scope.Add("myCustomClaim");
                options.Scope.Add("offline_access");

                // do I need any of the following? if so, what are the correct values?

                //options.GetClaimsFromUserInfoEndpoint = true;
                //options.MapInboundClaims = false;  
                //options.ClaimActions.Clear();
                //options.ClaimActions.MapJsonKey("myCustomClaim", "myCustomClaim");                
            });
```

The response from /bff/user looks like this:

![image](https://user-images.githubusercontent.com/10196642/211073125-6403ae21-6557-4894-972c-50829cb50f77.png)

**Expected behavior**

I would expect the response from /bff/user to include myCustomClaim.

I think this must be a problem with my BFF setup as the other clients are able to retrieve the claim, so Identity Server is definitely returning it. The commented out settings in ConfigureServices are things I have tried based on reading similar support issues, but I can't find a combination that works.

**Comment by josephdecock** [comment]
Hi @michelletimmons, you have great timing - we just updated our docs on the user endpoint today, and they now discuss this very thing: https://docs.duendesoftware.com/identityserver/v6/bff/session/management/user/#user-claims

The reason you're not seeing the new claim is because the user endpoint returns the claims that are in the session. ASP.NET doesn't get claims from the user endpoint by default, and it doesn't add custom claims from the user endpoint to the session by default either, so the custom claim isn't in your session.

You are on the right track with the commented out part of your configuration. Here's what you need:

```cs

// Do this so that the oidc handler will make a userinfo call                
options.GetClaimsFromUserInfoEndpoint = true;

// Do this to tell the oidc handler not to change the types 
// of the claims (the default is to use some ancient xml 
// namespace junk from the days of wcf)
options.MapInboundClaims = false;  

// The claim actions describe how claims in the userinfo 
// endpoint get turned into claims in the session
// I would not clear the default claim actions, because 
// standard profile claims are already mapped for you, 
// and that is usually useful
//options.ClaimActions.Clear(); // Probably leave this commented out

// You need this so that your custom claim gets mapped to a claim in the session
options.ClaimActions.MapJsonKey("myCustomClaim", "myCustomClaim");     

```

**Comment by michelletimmons** [comment]
Hi @josephdecock, thank you very much for your quick response. Using those settings has indeed got it working!
