### ISSUE TITLE
How to migrate openid providers configuration from IdentityServer4 to Duende?

### ISSUE THREAD

**Issue by oleksandr-slys** [DuendeSoftware/Support#43]
**Which version of Duende IdentityServer are you using?**
6

**Which version of .NET are you using?**
6

**Describe the question**

Hi! 
I am migrating from IdentityServer4 to Duende v6.
I have a code that adds openid providers during application startup.
```cs
async Task Configure()
{
  var providers = await db.GetAllEnabledProvidersAsync();
  var handler = scope.ServiceProvider.GetRequiredService<OidcConfigurationHandler>();
  foreach (var p in providers)
  {
      await handler.AddProviderAsync(p);
  }
}

class OidcConfigurationHandler
{
  private IAuthenticationSchemeProvider _schemeProvider;
  private IOptionsFactory<OpenIdConnectOptions> _factory;

  public async Task AddProviderAsync(provider)
  {
    if (!provider.Authority.Contains("http")) return Task.CompletedTask;
    if (await _schemeProvider.GetSchemeAsync(provider.Scheme) != null) throw new Exception($"already exists");

    var options = _factory.Create(provider.Scheme); // IT FAILS THERE !!!

    options = FillOidcOptions(options, provider); // fill in Authority, ClientId, etc
    if (options.ConfigurationManager == null)
    {
      if (options.Configuration != null)
        options.ConfigurationManager = new StaticConfigurationManager<OpenIdConnectConfiguration>(options.Configuration);
      else
        options.ConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(options);
    }
    _schemeProvider.AddScheme(new AuthenticationScheme(provider.Scheme, provider.Name, typeof(OpenIdConnectHandler)));
  }
}
```

I have compared `IOptionsFactory` in IndentityServer4 and Duende. There is one extra in the Duende `https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs`
So `_factory.Create(provider.Scheme)` calls https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs#L37 where `_httpContextAccessor.HttpContext` is null.
Could you advice me how properly migrate openid providers configuration or point to the right direction?

**Log output/exception with stacktrace**

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

   at Duende.IdentityServer.Hosting.DynamicProviders.ConfigureAuthenticationOptions`2.Configure(String name, TAuthenticationOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at IdentityServer.Configuration.OidcConfigurationHandler.<AddProviderAsync>d__6.MoveNext() in OidcConfigurationHandler.cs:line
```

**Additional context**

Looks like trivial solution is using `IConfigureOptions<OpenIdConnectOptions>` and `IPostConfigureOptions<OpenIdConnectOptions>` instead of `IOptionsFactory<OpenIdConnectOptions>` to avoid calling `Duende.IdentityServer.Hosting.DynamicProviders.OpenIdConnectOptions.Configure` method, but I am not sure is it right way to go.

```cs
class OidcConfigurationHandler
{
  private IAuthenticationSchemeProvider _schemeProvider;
  private readonly IConfigureOptions<OpenIdConnectOptions> _configureOptions;
  private readonly IPostConfigureOptions<OpenIdConnectOptions> _postConfigureOption;

  public async Task AddProviderAsync(provider)
  {
    if (!provider.Authority.Contains("http")) return Task.CompletedTask;
    if (await _schemeProvider.GetSchemeAsync(provider.Scheme) != null) throw new Exception($"already exists");

    var options = new OpenIdConnectOptions();
    _configureOptions.Configure(options);
    _postConfigureOption.PostConfigure(scheme, options);

    // ...same code as before
}
```

**Comment by brockallen** [comment]
You could always invoke your code prior to adding IdentityServer to the DI system in startup, no?

**Comment by oleksandr-slys** [comment]
Hi @brockallen! Thank you for the answer.
I have tried your approach and moved my code from `public void Configure(IApplicationBuilder app)` to `public void ConfigureServices(IServiceCollection services)` to call it before `services.AddIdentityServer` and now I have found that  `ConfigurationManager`  is dependent on `HttpClient` that is null at that time.

```
options.ConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
  options.MetadataAddress,
  new OpenIdConnectConfigurationRetriever(),
  new HttpDocumentRetriever(options.Backchannel) { RequireHttps = options.RequireHttpsMetadata }
);
```

```
System.ArgumentNullException: 'IDX10000: The parameter 'httpClient' cannot be a 'null' or an empty object. (Parameter 'httpClient')'
```

**Comment by brockallen** [comment]
I think you can assign that, no?

**Comment by oleksandr-slys** [comment]
Yes, but now I am not sure what is the proper place to do it. I guess I need to rethink how I add AuthenticationScheme.

But there is another question that came to my mind while investigating it. Duende IdentityServer has a new feature now called Dynamic Identity Providers. Is it something that can help to add custom AuthenticationSchemes from DB to the application during the application startup, or it is for other purposes?

**Comment by brockallen** [comment]
> Duende IdentityServer has a new feature now called Dynamic Identity Providers. Is it something that can help to add custom AuthenticationSchemes from DB to the application during the application startup

Is so you can store the all of your external identity providers in a database, we we will load them at runtime. Here are the docs for it: https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders/

**Comment by oleksandr-slys** [comment]
I have filled in `ConfigurationDbContext.IdentityProviders` with my providers and now it is available via `IIdentityProviderStore`, but `IAuthenticationSchemeProvider` is not automatically populated with the dynamic identity providers, right?

Because right now I get `InvalidOperationException: No authentication handler is registered for the scheme 'foo'. The registered schemes are: idsrv, idsrv.external, bar. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("foo",...)?` exception.

So I should have the next logic (see below) on application start somewhere, right?
```
async Task RegisterIdentityProviders(IIdentityProviderStore store, IAuthenticationSchemeProvider authSchemeProvider) {
  var schemes = await store.GetAllSchemeNamesAsync();
  foreach (var s in schemes) {
    authSchemeProvider.AddScheme(new AuthenticationScheme(s.Scheme, s.DisplayName, typeof(OpenIdConnectHandler)));
  }
}
```

**Comment by brockallen** [comment]
> So I should have the next logic (see below) on application start somewhere, right?

No, we put a decorator on the IAuthenticationSchemeProvider to load from our IIdentityProviderStore, but we only do this for the one API: GetSchemeAsync. If you want the list, then you should load from the IIdentityProviderStore.

> Because right now I get InvalidOperationException: No authentication handler is registered for the scheme 'foo'

Hmm, I'm not sure. Can you call IAuthenticationSchemeProvider.GetSchemeAsync for that scheme to test of the dynamic provider is being loaded?

**Comment by oleksandr-slys** [comment]
Thank you for your advice. I did some progress.
I have set `IdentityProvider`s types to `oidc`, but there is an issue with validation now.

There is a callstack:
```cs
IAuthenticationSchemeProvider.GetSchemeAsync(name)
DynamicAuthenticationSchemeProvider.GetSchemeAsync(name) -> GetDynamicSchemeAsync(name)
CachingIdentityProviderStore.GetBySchemeAsync(name)
DefaultCache.GetOrAddAsync(name)
ValidatingIdentityProviderStore<EntityFramework.Stores.IdentityProviderStore>.GetBySchemeAsync(name)
  var idp = EntityFramework.Stores.IdentityProviderStore.GetBySchemeAsync(name)
  var result = MapIdp(idp)
  // Authority, ClientId, ClientSecret are NULL 
  // and this is make sence for me as there are no such the columns in DB
DefaultIdentityProviderConfigurationValidator.ValidateAsync
  ValidateOidcProviderAsync // context.SetError for Authority and ClientId
```

**Comment by brockallen** [comment]
You will need to update the redirect URI in the Azure config for your client to match the convention.

**Comment by oleksandr-slys** [comment]
I did some progress. After update of the redirect URI I can select account and login or start login process. Still have a few things to fix.

1) I have noticed in Duende logs that it shows me next warning:
```
Duende.IdentityServer.Hosting.CorsPolicyProvider CORS request made for path:
    /federation/foo/signin from origin: https://login.microsoftonline.com 
    but was ignored because path was not for an allowed IdentityServer CORS endpoint
```
When I debug `CorsPolicyProvider` I see that it contains only next allowed URLs:
```
    {/.well-known/openid-configuration}
    {/.well-known/openid-configuration/jwks}
    {/connect/token}
    {/connect/userinfo}
    {/connect/revocation}
```
Do you think it is critical issue?

2) Getting error during Issuer validation. Call stack looks like this:
```cs
DynamicSchemeAuthenticationMiddleware ->
AuthenticationRequestHandlerWrapper ->
OpenIdConnectHandler ->
Options.SecurityTokenValidator.ValidateToken ->
JwtSecurityTokenHandler ->
ValidateJWS ->
ValidateTokenPayload ->
ValidateIssuer
```
```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidIssuerException: 'IDX10205: Issuer validation failed.
Issuer: 'https://sts.windows.net/{some-guid}>/'. 
Did not match: validationParameters.ValidIssuer: 'null' 
or validationParameters.ValidIssuers: 'https://sts.windows.net/{tenantid}/'. 
For more details, see https://aka.ms/IdentityModel/issuer-validation. '
```
Do `ValidIssuer` and `ValidIssuers` also should be set inside `dbo.IdentityProviders.Properties` column?

**Comment by brockallen** [comment]
> Do you think it is critical issue?

No, it's a red herring due to something odd in Chrome. You can ignore it.

> Getting error during Issuer validation

That's likely due to you using AAD's common endpoint, which is not spec compliant. They have docs somewhere on how to deal with it.

**Comment by oleksandr-slys** [comment]
Managed to fix it with additional configuration trick I have seen in your documentation.
```cs
public class ConfigureOpenIdConnectOptions : ConfigureAuthenticationOptions<OpenIdConnectOptions, OidcProvider>
    {
        protected override void Configure(ConfigureAuthenticationContext<OpenIdConnectOptions, OidcProvider> context)
        {
            context.AuthenticationOptions.TokenValidationParameters.ValidIssuer = $"https://sts.windows.net/{context.IdentityProvider.Properties["tenantId"]}/";
        }
    }
```

I have also had to change claims mapping
```
http://schemas.microsoft.com/identity/claims/objectidentifier -> oid
http://schemas.microsoft.com/identity/claims/tenantid -> tid
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name -> unique_name
```
there 
```cs
Task ExternalController.Callback() {
  var x = await HttpContext.AuthenticateAsync("idsrv.external");
  var z = Map(result.Principal);
}
```
Do you have an idea why claims mapping is different now?

**Comment by oleksandr-slys** [comment]
Migration is finished. Thank you @brockallen for support!

P.S. I has also done a final change to make it work with Auth0:
* added `email` and `profile` scopes to `ConfigureOpenIdConnectOptions` because it has `openid` scope only
