### ISSUE TITLE
CookieEventHandler cancels the refresh token.

### ISSUE THREAD

**Issue by qq1176914912** [DuendeSoftware/Support#430]
Sorry, I have some questions. In the ValidatePrincipal method under the path xxx, there is such a sentence written:' If we have a refresh token, it should be revoked here'. How to write it? I can't find the relevant writing.
![image](https://user-images.githubusercontent.com/79817742/211146515-a882124e-ac63-4422-a43a-c9b33b7ffe3b.png)

**Comment by josephdecock** [comment]
Refresh tokens are revoked by using the revocation endpoint. See our docs [here](https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/revocation/). We actually have a new library for token management as well, Duende.AccessTokenManagement, which has a simpler API than the IdentityModel library shown in those docs. If you use the AccessTokenManagement library, there is [an extension method for token revocation](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/web-applications#http-context-extension-methods).

**Comment by qq1176914912** [comment]
> Refresh tokens are revoked by using the revocation endpoint. See our docs [here](https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/revocation/). We actually have a new library for token management as well, Duende.AccessTokenManagement, which has a simpler API than the IdentityModel library shown in those docs. If you use the AccessTokenManagement library, there is [an extension method for token revocation](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/web-applications#http-context-extension-methods).

Thank you for your reply. I will try it when I have time.
