### ISSUE TITLE
.net 7 sample for MAUI App 

### ISSUE THREAD

**Issue by darena-pjindal** [DuendeSoftware/Support#431]
Are there any plans to update the MAUI sample to .net7? I might be missing something, but I can't get the current sample to build.

**Comment by josephdecock** [comment]
What build issues are you getting?

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by darena-pjindal** [comment]
Hello @josephdecock - apologies for missing the previous message. I downloaded the latest updates on the main branch from yesterday and am having the following issues. I can't find a global file in the solution. Please advise. 
![image](https://user-images.githubusercontent.com/45796558/214559042-ca0ed832-e19c-44ce-a640-796a3198ef42.png)

**Comment by josephdecock** [comment]
No problem - the global.json file in the repo defines which version of the .net sdk the project uses. You need to install the version specified there (and note that side by side installs of multiple sdks with just fine).

**Comment by darena-pjindal** [comment]
Thanks. Is the windows version supported or is it just Android and iOS currently? 
![image](https://user-images.githubusercontent.com/45796558/214563473-1af4dd78-82e4-4beb-9bfe-906732ce9bbe.png)

**Comment by leastprivilege** [comment]
This specific sample was created on the Mac. So no Windows support. 

But this only really exists to make sure the the `IdentityModel.OidcClient` client library works with MAUI. Feel free to use the library directly in your own project.
