### ISSUE TITLE
Issue with TokenRefresh during multiple parallel requests

### ISSUE THREAD

**Issue by Yirica** [DuendeSoftware/Support#434]
I am currently trying to fix an error we encounter when our token expires and is refreshed in the GetUserAccessTokenAsync() method.
We are running multiple requests from the frontend to the backend in parallel.
If I let the token expire, the first request will work, but the second one will try to use the same refresh token, which results in a validation failure at the IdentityServer because the token has already been consumed.
I tried to lock the call to GetUserAccesTokenAsync() with a Semaphore, but it still uses the consumed access token on the second request.
I also tried switching the Session store to EntityFramework, but this did not fix our issue.

I could really use some support on this as I am not sure about a good solution. Making the RefreshToken reuseable does not seem like the best idea to me.

**Comment by josephdecock** [comment]
Depending on your scenario, reusable tokens may actually be appropriate. If you read the OAuth best current practice spec, one time use tokens are really only required if you have a public client. Private clients bind the refresh token to the client and authenticate the client through the use of the client's secret, so it is safe to use Reusable tokens.

Another option is to add a customization to make the one time use of refresh tokens "fuzzy", in the sense that tokens that have been used can be used again for a short duration of time. We discuss this in our docs here: https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/#one-time-refresh-tokens

**Comment by Yirica** [comment]
Thank you very much, this was very helpful input, I was able to fix the bug already.
I chose to go with the "fuzzy" solution for now, but it is also good to know that ReUse would be fine as well.

Thanks again for the quick help, have a great start into 2023.
