### ISSUE TITLE
Not able to access BFF Local endpoint via postman

### ISSUE THREAD

**Issue by YLiuEvolentHealth** [DuendeSoftware/Support#439]
I am having trouble in testing BFF local endpoint /bff/login via postman. 
Basically, I cloned the repository of Samples/IdentityServer/v6/BFF/JsBffYarpSample and setup local environment with PKCE client and pointing to our IDP server. I am able to login via UI asset loaded from BFF host dynamically. But, I am not able to test it via postman. I am just wondering is there any way we could access bff local endpoint, such as login, logout, get user info via postman or other front end client other than the bff host? Could you please advise?

1. Login via front end asset of bff host successfully:
![image](https://user-images.githubusercontent.com/95240622/211468504-7a447991-447f-4f3a-bb31-4f2f9bfc9584.png)

2. Failed to access login endpoint of bff host via postman:
![image](https://user-images.githubusercontent.com/95240622/211468615-75a97e51-af10-4a83-89c2-fc69e4695eb4.png)

**Comment by josephdecock** [comment]
The bff management endpoints are really just http endpoints, and you should be able to invoke them however you like. Some of the endpoints require an authentication cookie so you will have to get that into postman. 

This connection refused error looks like some kind of network issue that is preventing your request from ever reaching IdentityServer.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by YLiuEvolentHealth** [comment]
Thanks @josephdecock and feel free to close this issue now. Just want to confirm that is the case and we will figure it out how to set authentication cookie via postman to send a request to BFF host.
