### ISSUE TITLE
Token Management Question - what is the latest recommendation

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [DuendeSoftware/Support#440]
version of Duende IdentityServer = 6.2, version of .NET = .Net7

I've recently watched the Pluralsight course "[Securing ASP.NET Core 6 with OAuth2 and OpenID Connect](https://pluralsight.com/courses/asp-dot-net-core-6-securing-oauth-2-openid-connect)" by Kevin Dockx.

While upgrading my Blazor Server application with the course content, I'm trying to make sense of the right way to implement AddUserAccessTokenHandler() on the services.AddHttpClient declarations in Program.cs.

I've watched the YouTube video posted by Dominick Duende a month ago - "Automated OAuth Access Token Management for .NET Workers and ASP.NET Web Applications" ([https://www.youtube.com/wat...](https://disq.us/url?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dzr-LAYg5BCE%29%3ArGxoZxK8O7fCf7E7kqJ8qosMDMM&cuid=5011031) which has an accompanying wiki - [https://github.com/DuendeSo...](https://disq.us/url?url=https%3A%2F%2Fgithub.com%2FDuendeSoftware%2FDuende.AccessTokenManagement%2Fwiki%2Fblazor-server%3Ayz7EaFM1npThXqvRrFjPBLLT57w&cuid=5011031).

My first question is: which version of the AddUserAccesssTokenHandler() should I be using?
- IdentityModel.AspNetCore.AccessTokenManagement.UserAccessTokenParameters method or
- Duende.AccessTokenManagement.OpenIdConnect.UserTokenRequestParameters

The wiki also states (at the top):
"Blazor Server applications have the same token management requirements like a regular ASP.NET Core web application. Due to the fact that Blazor puts an abstraction layer between the Blazor application and the hosting/rendering engine, you cannot use HttpContext."
This Asp.NetCore 6 course states that we no longer need the TokenProvider class and TokenManager refresh token method created in an earlier version of a previous Pluralsight course by Kevin Dockx (the ASP.Net Core 3 version I think). However the Duende wiki article shows a method to attach the AccessToken to each http data call (similar to your TokenManager method without the refresh bit).

I'm trying to piece it all together but am getting a bit confused.

Can someone please advise:
1. if the AccessTokens need to be attached to Blazor Server applications or is the "Blazor Server" referred to in the wiki article just the server component of a Blazor WASM application (I'm reading it as a full Blazor Server application). 
2. do I use a pattern similar to the following for my declarations of data services in Program.cs?:

```
services.AddHttpClient<idataservice, dataservice="">(client =>
{
client.BaseAddress = new Uri(configuration["DataApiUriAddressConfiguration:DataApi"]);
client.DefaultRequestHeaders.Clear();
client.DefaultRequestHeaders.Add(HeaderNames.Accept, "application/json");
}).AddUserAccessTokenHandler();
```
and then send the data call with an attached AccessToken similar to the SendRequestAsync method in the Duende wiki:
request.SetBearerToken(token.AccessToken);

I currently store the access tokens in an IDP SQL Server database (PersistedGrants table - the standard Duende table) so I'm assuming I'll need a TokenProvider class to define the token object properties.

In addition to all the above, my Api currently isn't getting user name, roles, country, etc. of the current user even though it is showing that the user is authenticated. The sid value and others come through ok but I get "openId", "profile", "role", "country", etc. for values in stead of the actual values. Would this be to do with not passing the AccessToken with each http data call?
Thanks in advance for your help and apologies for the long comment - trying to understand all the working parts while the working parts are evolving can be a challenge some days!

Thanks in advance!

Sandy

**Comment by josephdecock** [comment]
In general, we recommend you use Duende.AccessTokenManagement. It is the successor to IdentityModel.AspNetCore. Our blog describes things in more detail [here](https://blog.duendesoftware.com/posts/20220804_datm/).

The wiki article you're linking to is describing a Blazor Server application.

You can't use the AddUserAccessTokenHandler in a Blazor Server application, because it depends on HttpContext, which is unavailable in Blazor Server. That's what the wiki page's sample code is addressing.

For another sample, take a look [here](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/tree/main/samples/BlazorServer).

> I currently store the access tokens in an IDP SQL Server database (PersistedGrants table - the standard Duende table) so I'm assuming I'll need a TokenProvider class to define the token object properties.

I'm not sure what you mean by this exactly. Typically access tokens are not stored in the Persisted Grants table, unless you're using reference tokens. If your access tokens are JWTs (which is the default and most common by a fair margin), they will not be in Persisted Grants.

>n addition to all the above, my Api currently isn't getting user name, roles, country, etc. of the current user even though it is showing that the user is authenticated. The sid value and others come through ok but I get "openId", "profile", "role", "country", etc. for values in stead of the actual values. Would this be to do with not passing the AccessToken with each http data call?

If you're not passing a token, then how are you authenticating the API call at all?

**Comment by rasaconsulting-sandy** [comment]
Hi Joe,

Thanks for your response.  It's making more sense to me now, especially with the location of the correct Blazor server sample - I was trying to find it within the Duende website samples (https://docs.duendesoftware.com/identityserver/v6/samples/) instead of looking at the code base where the wiki was (insert eye roll here). 

It is refresh and reference tokens that are getting stored in the Persisted Grants table - I wrote the wrong token type in my initial question (sorry - still learning all the pieces).

Good point on the API - it's definitely authenticating so something in my code isn't right.  I'll investigate again once I've implemented the access token management code correctly. 

Is there a way I can subscribe to the Duende Blog to make sure I don't miss any future updates?  

Lastly - a big THANKS to the team for providing this access token management!!  It's great!

Sandy

**Comment by josephdecock** [comment]
Glad to hear things are making more sense and that you're happy with IdentityServer!

The best way to get updates is to follow @DuendeIdentity on Twitter: https://twitter.com/duendeidentity?s=21&t=_dK_Hc17F5FON5jZwmtdzQ

In addition to blog posts, we tweet announcements about releases, upcoming training that we are delivering, and occasional other news in the identity space.

**Comment by rasaconsulting-sandy** [comment]
Thanks for your help and response Joe - sorry I forgot to respond sooner.

**Comment by josephdecock** [comment]
No problem, I'm happy to help!
