### ISSUE TITLE
How can I interact with the AuthorizeInteractionResponseGenerator from a controller?

### ISSUE THREAD

**Issue by FalkWinkler** [DuendeSoftware/Support#441]
For example, how can I set a value in the AccountController that I can use in an AuthorizeInteractionResponseGenerator?

**Comment by josephdecock** [comment]
The `AuthorizeInteractionResponseGenerator`'s methods are passed a `ValidatedAuthorizeRequest` object, which includes the current user as the `Subject` property. You could store a small value as a claim in the current user and read it back there. Storing large amounts of data in claims can cause problems with cookie size though, so it is best to use this technique sparingly. You could really store the data anywhere you like, build a mechanism to access that data and inject that into your generator.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
