### ISSUE TITLE
Connect Token 503

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#444]
Duende v6.1.1
.NET 6

Problem: when an entity redirects a post to connect/token after having successfully logged in, the entity is receiving an error - "Request  error: tunneling socket could not be established, statusCode=503 {}".

I have checked their request and it appears to be properly formed.

What can I look at in our IS to see what might be causing this?

Thanks!

**Comment by leastprivilege** [comment]
That looks like an infrastructure error that happens long before the request reaches the app layer and thus IS.

I would look at reverse proxies, firewalls, gateways etc to see if there are more errors.

**Comment by billcunnien** [comment]
Getting a network engineer involved to follow the request through the pipeline and determine where the error is getting generated. Once we find something, I will update here and close the issue (in case another poor soul runs into this same error along the way). Thanks a lot for the quick response!

**Comment by josephdecock** [comment]
I'm going to go ahead and close this issue for now, but feel free to add any follow-up details if you like.
