### ISSUE TITLE
Can you manage users with a machine client via an API?

### ISSUE THREAD

**Issue by amthejohnson** [DuendeSoftware/Support#446]
**Which version of Duende IdentityServer are you using?**
6.1.0
**Which version of .NET are you using?**
6.0
**Question**
I am using Duende Identity server with entity framework to manage users and authenticate. A request from the customer of my project is to be able to manage users with machine clients via an API. Getting information seems straightforward enough, either using the UserInfo endpoint or manually querying the database. However, I haven't seen anything in the Duende documentation describing how one would interact with the identity server via an API. (Specifically how one would add/modify/delete users with this API)

Is it recommended to manage users with a machine client via an API? Or should user management be kept in the UI? If Duende user management is supposed to be kept in the UI, then I can probably get around this issue by using SSO through Google.

**Comment by josephdecock** [comment]
IdentityServer doesn't impose any requirements on how users are stored or managed. APIs, UIs, or both for user management are all reasonable alternatives.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by amthejohnson** [comment]
Yes I was able to do what I wanted with an API
