### ISSUE TITLE
Database timeouts during index rebuilding of PersistedGrants table

### ISSUE THREAD

**Issue by PratikPatel-Mtech** [DuendeSoftware/Support#448]
**Which version of Duende IdentityServer are you using?**
V6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug/question**
We are seeing database timeouts during the rebuilding index of table `PersistedGrants`. It was not happening initially but it was started when we majorly started usage of `reference` tokens for clients. Now, It has been creating more records(around 1 Lac) in the PersistedGrants table on a daily basis which may increase the fragmentation of the database. So, rebuilding the indexes cost more than usual and leads to database timeouts on the select queries.

Additionally, we have configured a job to delete the expired tokens from this table and it executes before the execution of the index rebuilding job.

Might be it is taking more time because of the size of the data which we are storing in the `Data` column.

Could you please suggest a solution to this problem? 

**To Reproduce**

1. Generate around 3 Lac records(2 Lac refresh token valid for 30 days, 1 Lac reference token valid for 1 Hour) in the `PersistedGrants` table
2. Remove expired tokens. After that, still, 2 Lac records remain in the database 
3. Rebuild the index
4. During rebuilding continue execution of the `/introspect` or `/userinfo` endpoint with 200 RPM
5. You can observe database timeout errors

**Expected behaviour**

There should not be any timeout error. Requests should execute successfully.

**Log output/exception with stack trace**

```
Failed executing DbCommand ("30,002"ms) [Parameters=["@__key_0='?' (Size = 200)"], CommandType='Text', CommandTimeout='30']"
""SELECT [p].[Id], [p].[ClientId], [p].[ConsumedTime], [p].[CreationTime], [p].[Data], [p].[Description], [p].[Expiration], [p].[Key], [p].[SessionId], [p].[SubjectId], [p].[Type]
FROM [PersistedGrants] AS [p]
WHERE [p].[Key] = @__key_0"
```

**Additional context**

Database: SQL Server Standard edition

**Comment by josephdecock** [comment]
Unfortunately, there isn't a magic bullet here. Reference tokens store data that is not stored for JWTs access tokens. That necessarily causes many more reads and writes in your database. 

A few options include:
1. Don't use reference tokens
2. Use reference tokens only were absolutely needed - maybe on a client by client basis, you can decide if reference tokens are actually needed. Perhaps you're able to mostly not use reference tokens, but in certain relatively rare circumstances you decide to use them
3. Scale up your database server
4. Rebuild indexes less often, and more strategically. Perhaps there is a time of day or day of the week when usage is very low when you could rebuild indexes

**Comment by PratikPatel-Mtech** [comment]
@josephdecock Thanks. 

1 & 2. We are using a reference tokens for selected clients only, most of are the frontend clients where we have requirements to immediately remove the access. So, we do not have other option here.

3. We can discuss it with stakeholders

4. We are already rebuilding index when we have less traffic on our server

**Comment by josephdecock** [comment]
Another way you could fulfill the requirement to immediately remove access at client applications is through the use of server side sessions at the client, along with back-channel logout notifications to those clients.

Our general docs on this pattern are [here](https://docs.duendesoftware.com/identityserver/v6/ui/logout/notification/#back-channel-server-side-clients), and support in the BFF framework is documented [here](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/back-channel-logout/).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by PratikPatel-Mtech** [comment]
> Another way you could fulfill the requirement to immediately remove access at client applications is through the use of server side sessions at the client, along with back-channel logout notifications to those clients.
> 
> Our general docs on this pattern are [here](https://docs.duendesoftware.com/identityserver/v6/ui/logout/notification/#back-channel-server-side-clients), and support in the BFF framework is documented [here](https://docs.duendesoftware.com/identityserver/v6/bff/session/management/back-channel-logout/).

@josephdecock Thanks! But we can not use this ATM as all our clients do not have server-side session management.

**Comment by josephdecock** [comment]
I'm closing this issue, but feel free to reopen if necessary.
