### ISSUE TITLE
Properties and Claims

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#45]
Dear Duende Team,

I am having a bit of trouble understanding the purpose and difference between Claims and Properties for all entities. 
I was not able to find this explanation in your documentation.

Claims and properties exists in your model for the following entities: ApiResource, ApiScope, Client and IdentityResource. 

Please allow me to ask you some questions:
1. If I take a look at the model, properties for all entities are taking the same form, simply keys and values. My understanding is that the properties are simply an additional information about given entity, but should never endup in token. Is this true? Can you give me pratical examples where I would use properties? 
2. Looking at the claims, I can see that for Client those are simply key value pairs, which I know from previous versions of IdentityServer. On the other hand, for ApiResource, ApiScope and IdentityResource, claims are not modeled in the same way, they just have Type. Why is that?

Thank you and best regards,
Novak

**Comment by brockallen** [comment]
Claims indicate what additional user claims to include when that scope or resource is requested. The Properties dictionary on each of those object models are for you to put custom config data associated with each entity for your own processing logic purposes. Think of it as custom metadata.

**Comment by No1e** [comment]
@brockallen Thanks!
