### ISSUE TITLE
More error details from /connect/token

### ISSUE THREAD

**Issue by lnaie** [DuendeSoftware/Support#450]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
net6.0

**Describe the bug**
I'm debugging and I need more details about why the API call is failing.

**To Reproduce**
I'm making a call to the /connect/token endpoint to get a token for a user based on its password. What I get back it's a 400 with no details about what was wrong. The logging is not showing anything although I add this to it:

```
{
    "@timestamp": "2023-01-13T16:55:41.5724740+01:00",
    "level": "Warning",
    "message": "Invalid HTTP request for token endpoint",
    "sourceContext": "Duende.IdentityServer.Endpoints.TokenEndpoint",
    "business-process-id": "4f980ea0-3529-460d-81c4-76cdd77d727d",
    "requestPath": "/iam/connect/token",
    "connectionId": "0HMNLFQDN9B47",
    "application-name": "local_dev",
    "originIp": null,
    "userAgent": "ABC TV, 0.9.2, iOS, 8",
    "clientName": "abc_tv",
    "clientVersion": "0.9.2",
    "osName": "ios",
    "osVersion": "8"
}
{
    "@timestamp": "2023-01-13T16:55:41.5823170+01:00",
    "level": "Information",
    "message": "HTTP \"POST\" \"/iam/connect/token\" responded 400 in 228.1912 ms",
    "requestMethod": "POST",
    "requestPath": "/iam/connect/token",
    "statusCode": 400,
    "elapsed": 228.1912,
    "sourceContext": "Serilog.AspNetCore.RequestLoggingMiddleware",
    "application-name": "local_dev",
    "business-process-id": "4f980ea0-3529-460d-81c4-76cdd77d727d",
    "connectionId": "0HMNLFQDN9B47",
    "originIp": null,
    "userAgent": "ABC TV, 0.9.2, iOS, 8",
    "clientName": "abc_tv",
    "clientVersion": "0.9.2",
    "osName": "ios",
    "osVersion": "8"
}
```
I'm even using this:

```
            services.AddLogging(options =>
            {
                options.AddFilter("Duende", LogLevel.Debug);
            });
```
What am I doing wrong?

**Comment by josephdecock** [comment]
The particular error that you're getting usually means that you made a request to the token endpoint either without using the POST http method or without using the application/x-www-form-urlencoded content-type.

Configuring logging in aspnet core is a [pretty big topic](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0). Most of our samples and templates use the serilog package, with pretty good results. For more example code on how to use serilog, see our docs [here](https://docs.duendesoftware.com/identityserver/v6/diagnostics/logging/).

If you have logging set up correctly for IdentityServer, you should see it print diagnostic output on startup. And if IdentityServer is returning errors, it usually logs additional information.
