### ISSUE TITLE
Access Denied when adding a custom profile service

### ISSUE THREAD

**Issue by apetrut** [DuendeSoftware/Support#454]
I am using Duende 6.0.2 with  .NET 6.

I created a custom ProfileService that adds a list of tenants ids in the JWT token (see below):

![image](https://user-images.githubusercontent.com/13006228/213122106-50feb755-411f-4274-9b59-cba02e2f9237.png)

After I log in and try to load the IdentityServer Admininstration page I get this error:

![image](https://user-images.githubusercontent.com/13006228/213122135-ad4b8030-f16e-4746-9bde-987607bcb47f.png)

If I remove the custom profile service the page loads fine.

I suspect it is related to adding claims in the context:

public virtual async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var user = context.Subject;
            var tenantIds = await GetTenantsAsync(user);
            var claims = GetRequestedClaims(tenantIds);
            context.IssuedClaims.AddRange(claims);
        }

Can you confirm if that's the case and what can be done to avoid this error?

Thanks.

**Comment by josephdecock** [comment]
That administrative site is not part of IdentityServer itself - is that maybe the RSK AdminUI product?

**Comment by apetrut** [comment]
Hi @josephdecock I am using Duende Admin UI with the Skoruba version.

**Comment by josephdecock** [comment]
Okay, well IdentityServer seems to be producing tokens correctly and as far as I can tell, this is an issue with skoruba. The issue that [you've opened at its repo ](https://github.com/skoruba/Duende.IdentityServer.Admin/issues/116) seems like the best place to get support for skoruba's package, so I'll close this one.
