### ISSUE TITLE
Upgrade Database from version 6.0 to 6.1 problems

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#455]
Hi all,
 I'm trying to update Identity Server from version 6.0 to 6.1, performing the migrations as shown in the documentation.
On the dev and stage environments everything works correctly, given that there are few data on the PersistedGrants table, but in production where I have millions of rows the following migration fails and times out:

> dotnet ef migrations add Update_DuendeIdentityServer_v6_1 -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb
> 
> dotnet ef database update -c PersistedGrantDbContext

I tried to create an implementation of IDesignTimeDbContextFactory in the Startup project in order to increase the CommandTimeout of the migration:

```
public class PersistedGrantContextFactory : IDesignTimeDbContextFactory<PersistedGrantDbContext>
{
    public PersistedGrantDbContext CreateDbContext(string[] args)
    {
        var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

        var configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json")
            .AddJsonFile($"appsettings.{environment}.json")
            .Build();

        var builder = new DbContextOptionsBuilder<PersistedGrantDbContext>();
        builder.UseSqlServer(configuration.GetConnectionString("AuthZDatabase"),
            optionsBuilder => optionsBuilder.CommandTimeout(600));

        return new PersistedGrantDbContext(builder.Options);

    }
}
```

But unfortunately I get this exception:

> System.InvalidOperationException: Unable to resolve service for type 'Duende.IdentityServer.EntityFramework.Options.OperationalStoreOptions'. This is often because no database provider has been configured for this DbContext. A provi
> der can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions
> <TContext> object in its constructor and passes it to the base constructor for DbContext.
>    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Duende.IdentityServer.EntityFramework.DbContexts.PersistedGrantDbContext`1.OnModelCreating(ModelBuilder modelBuilder) in /_/src/EntityFramework.Storage/DbContexts/PersistedGrantDbContext.cs:line 73
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
> )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
> )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
> )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
> )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
> )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType
> )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
>    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Unable to resolve service for type 'Duende.IdentityServer.EntityFramework.Options.OperationalStoreOptions'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overridin
> g the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its construct
> or and passes it to the base constructor for DbContext.

So right now I'm stuck and don't know how to fix it.
Can you help me please?

**Comment by pampua84** [comment]
Sorry I add another question, how come on the db I see many rows that have the same ClientId and SubjectId still not expired?
For same client and subject shouldn't I have only one row, so only the last released RefreshToken?

**Comment by josephdecock** [comment]
> how come on the db I see many rows that have the same ClientId and SubjectId still not expired?

You might have multiple sessions for the same user. You might also have your refresh tokens configured for one time use. If you do, every time you use the refresh token, a new refresh token is issued and the old one is marked as consumed by setting is consumedTime in the database.

You can probably reduce the amount of records in your table by quite a lot by enabling automatic token cleanup and allowing it to these remove consumed tokens (or by deleting the consumed tokens yourself).

The options to enable token cleanup and remove consumed refresh tokens are in the operational store configuration:

`EnableTokenCleanup`
`RemoveConsumedTokens`

See also: https://docs.duendesoftware.com/identityserver/v6/reference/efoptions/operational/#persisted-grants-cleanup

You also might be able to switch to Reusable refresh tokens. OneTimeUse refresh tokens are only needed for public clients (e.g., SPAs). If you have a traditional website that is rendered server side, it is safe to switch to reusable refresh tokens.

Hopefully this will allow you to bring the size of your persisted grants table down so much that you're able to cleanly migrate. I would give that a try first and let us know if you need more help.

**Comment by pampua84** [comment]
First of all thanks for the advice. If I enable PersistedToken table cleanup every hour, can't I run into locks since the table is used constantly? Could changing the RefreshToken from OneTimeUse to reusable refresh tokens cause problems for applications or is it completely transparent on their side? Thanks

**Comment by josephdecock** [comment]
> can't I run into locks since the table is used constantly

It is possible - our cleanup job is built with EF without knowing even which database vendor it is talking to, so it fundamentally doesn't know anything about the locking semantics of the database. We always recommend that if you're going to use it, you load test things, and if it turns out that you need something more nuanced, then cleaning up expired or consumed grants with your own tools is fine to do.

What you might consider is manually cleaning up the table once, without using the cleanup job. Then you can write the sql and completely control the cleanup process. 

> Could changing the RefreshToken from OneTimeUse to reusable refresh tokens cause problems for applications or is it completely transparent on their side

Switching will change the behavior of the refresh process -instead of getting a new refresh token each time, you'll only get the access token. Theoretically, that could break a client that expected the one time use behavior. Many tools for token management would support both though - e..g, if you're using Duende.AccessTokenManagement or IdentityModel.AspNetCore, they both would have no problem with the switch.

**Comment by pampua84** [comment]
Hi John, as you wrote, I should have consumed Tokens:

> You might have multiple sessions for the same user. You might also have your refresh tokens configured for one time use. If you do, every time you use the refresh token, a new refresh token is issued and the old one is marked as consumed by setting is consumedTime in the database.

the problem is that I see many rows with the same ClientId and SubjectId but with neither consumed nor expired token. For example I have same ClientId and SubjectId with 3947 rows.
In your opinion, is this because the integrated client has a wrong behavior? Couldn't I, for example, remove the rows with a shorter deadline and leave only the one with a higher deadline?

**Comment by dobestar** [comment]
The thread seems to have been hijacked by the secondary question - can you stick to one question per thread?

**Comment by pampua84** [comment]
Excuse me, if you tell me what to do, I'll edit the thread right away.

**Comment by josephdecock** [comment]
I generally do appreciate efforts to keep threads focused, but the number of records in the persistent grants table is directly related to the performance of indexing it, so I don't think there's a need to edit this thread.

Having 3k+ refresh tokens that aren't consumed or expired for a single subject does seem excessive - I would be surprised if someone actually was using thousands of refresh tokens. Most likely, a client application is requesting them and then not revoking them on sign out. Assuming that's the case, there probably are many refresh tokens in the table that the client no longer has and are no longer usable. Unfortunately, it is impossible to know which ones are still needed, because you fundamentally don't know if the client app is storing the token until you see it in a request. 

If you did delete tokens that clients still had, those clients would end up not being able to use their current refresh token, so the users would have to log in again.

**Comment by pampua84** [comment]
Hi,
I'm trying to use the RefreshtToken in a reusable way but a new RefreshToken is still detached at each login for the same client and the same user, instead of returning the previous one. Is this the correct behavior? I would have expected a single RefreshToken.
Thanks

**Comment by josephdecock** [comment]
Did you configure the client's RefreshTokenUsage for ReUse?

**Comment by josephdecock** [comment]
Also, reusable tokens means that when you use the refresh token to obtain a new access token, that refresh token continues to be useable in the future. If you start a new session and request a refresh token, that always produces a new refresh token, even you have an existing refresh token.

**Comment by pampua84** [comment]
Ok, Thanks a lot for the clarification

**Comment by pampua84** [comment]
Hi Joseph, sorry if I ask you more questions, but I'm trying to solve and better understand the flow to follow in order to clean the db and not have more of these problems in the future. 
If I understand correctly, the client in the logout phase should call the revocation endpoint in addition to the endsession endpoint (for user logout) in order to eliminate the unused refresh tokens. Correct?

**Comment by josephdecock** [comment]
> the client in the logout phase should call the revocation endpoint in addition to the endsession endpoint 

Yes, that's traditionally how it is done unless you are using IdentityServer's server side session feature.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by pampua84** [comment]
Hi Joseph, 
to complete the upgrade I finally opted for the drop of the table and then the execution of the related migrations. For the future I have implemented a cleanup job in such a way as not to keep all the detached refresh tokens for the same client and user, but to keep only the last 3. Thanks a lot for your help, you can close the issue
