### ISSUE TITLE
Is SaveTokens option necessary for Blazor Server app?

### ISSUE THREAD

**Issue by yodasad** [DuendeSoftware/Support#456]
BFF Version: 2.0.0
.NET Version: 6

I have a theoretical question.

In a sample for a Blazor Server App `SaveTokens` option in an OIDC configuration is set to `true`, so tokens are saved in `AuthenticationProperties` and then these properties are saved in cookies.

Is it really needed for a Blazor Server App to store tokens in cookies?

**Comment by leastprivilege** [comment]
Blazor Server cannot use the HttpContext and thus not cookies in application code. You need to find different ways to store tokens there (e.g. in a cache or database).

**Comment by yodasad** [comment]
I'm very sorry for my English)
My question was: why do you set `SaveTokens` to `true` in your [sample](https://github.com/DuendeSoftware/BFF/blob/789638a84ebf39b50bd5aad064b53aa7418734fb/samples/Blazor6/Server/Program.cs#L55) ?

**Comment by josephdecock** [comment]
That sample is of a Blazor web assembly app, which does not have the same restrictions on HttpContext. It can therefore use the standard architecture for BFF applications, just the same as a spa built with react, angular, etc.

**Comment by yodasad** [comment]
Thank you, @josephdecock !

This [sample](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/blob/dffdd48f0c532a9db237d069f329ffb3c274a99f/samples/BlazorServer/HostingExtensions.cs#L37) is for BlazorServer but `SaveTokens` is set to `true` there too.

**Comment by leastprivilege** [comment]
This might be an oversight. Just try it.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
