### ISSUE TITLE
How to fail the auth code request if the GetProfileDataAsync of ProfileService fails?

### ISSUE THREAD

**Issue by VijayKaravadra** [DuendeSoftware/Support#457]
**Which version of Duende IdentityServer are you using?**
V6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

We are using some external APIs to get user details in the GetProfileDataAsync method of the ProfileService. So, if that fails then how do we fail the authentication and not generate a token? Because I don't want to complete the token generation without populating identity claims in it.

Right now, we're thinking to throw a custom exception to fail the token generation and "userinfo" API calls. Please let me know if there is any standard way of doing it.

**Comment by josephdecock** [comment]
There isn't really a standard way of dealing with this, but throwing an exception seems reasonable. From the client application's perspective, they'll get a 500 error and you'll have figure out what you want to do next from there.

**Comment by VijayKaravadra** [comment]
Thanks, @josephdecock! Going forward with this.
