### ISSUE TITLE
Multiple or Context-Aware `IssuerUri`s?

### ISSUE THREAD

**Issue by darena-patrick** [DuendeSoftware/Support#458]
**Which version of Duende IdentityServer are you using?**
6.2.0+d923c6c10f11013223f6998059c20f2ac26ba44a

**Which version of .NET are you using?**
.NET 7.0.2

**Describe the bug**
I am running IdentityServer in a docker container. The `IssuerUri` that I have configured in my .NET application is accessible via my web browser, but it isn't resolvable from the docker container network.

**To Reproduce**

- Set `IssuerUri` in authentication service registration.
- Run app in docker container.
- Have another container that uses authentication service pointing to the original `IssuerUri`.

**Expected behavior**

I would like if there was a way to potentially set multiple `IssuerUri` so that my web browser and the docker container can both resolve appropriately.

**Log output/exception with stacktrace**

Note - I am setting `IssuerUri` to `https://iam.docker.localhost`

```
2023-01-18 21:08:20 System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2023-01-18 21:08:20  ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
2023-01-18 21:08:20  ---> System.Net.Http.HttpRequestException: Name or service not known (iam.docker.localhost:443)
```

**Additional context**

I've tried meddling with the docker network, but I can't find a way to resolve to the same Uri internally and externally.

**Comment by josephdecock** [comment]
Normally the issuer is inferred based on the host of the request. That's actually what the spec mandates, and it makes verifying the issuer convenient for the client.

The issuerUri option is an optional override of that, intended for unusual situations where you can't follow the spec (maybe during a migration). You're probably better off unsetting it.

Multiple issuer Uri values in the options would be problematic because IdentityServer would have to have some mechanism to choose which one to use.

**Comment by darena-patrick** [comment]
The main reason we set it manually is that in our production environment, our apps are behind Azure Front Door.

The server URL may be like iam.website.azurewebsites.net, but everyone accesses it through iam.website.com. 

I'll see what I can do on the docker side itself. Probably setting an alias for the container would do the trick.

**Comment by josephdecock** [comment]
If you're behind a proxy, you may also need the asp.net forwarded headers middleware. See this doc: https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/
