### ISSUE TITLE
"client.xyz" tries to refresh token belonging to null

### ISSUE THREAD

**Issue by skatanski** [DuendeSoftware/Support#459]
**Which version of Duende IdentityServer are you using?**
6.0.0

**Which version of .NET are you using?**
NET 6

**Describe the bug**

After migrating to IS6 in our Staging environment, suddenly we've had a huge spike of following messages:
"client.xyz tries to refresh token belonging to null"

After initial spike these messages still pop up ~6 times every 24hours. As this initial spike happened users got logged out of their application.
We've never had these messages in our logs prior the migration, on IS4.1

**To Reproduce**

Unsure how to reproduce, logging out has not repeated since, for anyone aware of the issue.

**Expected behavior**

Our expectation would be for users not to be logged out - that was the behaviour with IS4.1. We can't have this happen in our production environment, where users have sessions open.

**Log output/exception with stacktrace**

```
Jan 17, 2023 @ 14:59:21.957 "POST" "https://stage.abc.com/connect/token" 400
Jan 17, 2023 @ 14:59:21.956 "client.xyz" tries to refresh token belonging to null
Jan 17, 2023 @ 14:59:21.956 Refresh token validation failed. aborting, TokenRequestValidationLog { ClientId: "client.xyz", ClientName: "abc Client", GrantType: "refresh_token", Scopes: null, AuthorizationCode: "********", RefreshToken: "********", UserName: null, AuthenticationContextReferenceClasses: null, Tenant: null, IdP: null, Raw: [("grant_type": "refresh_token"), ("refresh_token": "***REDACTED***"), ("client_id": "client.abc")] }
Jan 17, 2023 @ 14:59:21.949 Invoking IdentityServer endpoint: "Duende.IdentityServer.Endpoints.TokenEndpoint" for "/connect/token"
```

**Additional context**

From analysing the sources it seems that:
`await RefreshTokenStore.GetRefreshTokenAsync(tokenHandle);`
Somehow returns a non-null refresh token with clientId set to null.
We thought that maybe persistedgrants getting removed due to TTL on expiration/consumedTime causes this, but after dropping the TTL same validation errors still happen.
What we are currently investigating are the changes in serializer between 4.1 and 6

**Comment by skatanski** [comment]
> What implementation of the persisted grant store are you using?

We use MongoDB, so our PersistedGrantStore uses queries/commands, which wrap MongoDB driver in some way. These operations are pretty simple. 
- StoreAsync upserts (insert or update) persisted grant by key
- GetAsync retrieves persisted grant by key
- RemoveAsync hard-deletes persisted grant by key or a combination of clientid, subjectid, type and session id.
So DefaultGrantStore calls PersistedGrantStore and retrieves the Data field from it, Data field gets deserialized and the clientId from inside that Data field is used for the validation - am I correct?


> Are you able to query the store and see that you have refresh tokens with no client id set?

ClientId is taken out of the json *data* column/field of the persistedgrants collection for all documents of *type* refresh_token.
There are 2 forms of data for type of refresh_token:
1. Has multiple fields such us:
a. CreationTime
b. Lifetime
c. ConsumedTime
d. AccessToken (contains many fields)
e. Version 
2. Has 3 fields and is protected:
a. PersistentGrantDataContainerVersion
b. DataProtected
c. Payload

I was able to query all unprotected entries and ClientId is defined in all grants unprotected grants. I wasn't able to query the protected data - there's a chance that protected doesn't have ClientId field correctly set.
Is it possible to disable DataProtection for refresh_tokens as part of the investigation? (or check if its causing this issue?)
I suppose I could use the old serializer, but that would mean I'd need to deal somehow with the existing protected grants.

**Comment by skatanski** [comment]
I've created a small command line app, which reads PersistedGrants and deserializes Data using the Duende PersistentGrantSerializer. I can see that for some, even though the ClientId is inside the AccessToken object. ClientId still comes null after deserializing, as if somehow PostProcess within the Serializer doesn't work correctly.

![image](https://user-images.githubusercontent.com/45935324/213695845-a4a89741-abe6-4fa3-981f-f05798c21fe6.png)
 
Here's an example of a valid persisted grant entry in our DB (I've removed most of the properties of AccessToken). When the DefaultGrantStore deserializes data into RefreshToken type, clientId on the serialized object is still null.

```
{
    "_id" : ObjectId("MONGODB_HASH_HERE"),
    "key" : "KEY_HERE",
    "clientId" : "client.xyz",
    "consumedTime" : null,
    "creationTime" : ISODate("2022-03-23T17:42:46.000+0000"),
    "data" : "{\"CreationTime\":\"2022-03-23T17:42:46Z\",\"Lifetime\":28445667,\"ConsumedTime\":null,\"AccessToken\":{\"ClientId\":\"client.xyz\",\"Version\":4},\"Version\":4}",
    "description" : null,
    "expiration" : ISODate("2023-02-15T23:17:13.000+0000"),
    "sessionId" : "SESSION_ID_HERE",
    "subjectId" : "SUBJECT_ID_HERE",
    "type" : "refresh_token"
}
```

While investigating, I've noticed I can disable data protection using `DataProtectData` flag in options. Its on by default. However judging from the code base - it shouldn't be affecting ClietnId not being deserialized/assigned correctly.

**Comment by skatanski** [comment]
Ok I've found it by copy-pasting latest Duende Serializer code from github - and making it work locally. In my API the Duende Serializer from version 6.0.0 doesn't have the `PostProcess(item as RefreshToken);` method called. So the data from AccessToken is never assigned to the Serialized RefreshToken :/
Duende.IdentityServer 6.0.0 version uses Serializer from before this fix:

![image](https://user-images.githubusercontent.com/45935324/213700061-db2d1c1c-1ff8-439c-8da7-c23e67ffd72f.png)

**Comment by skatanski** [comment]
I think now my question boils down to:

Can I use a custom serializer as a temporary workaround until I move to a newer version of Duende.IdentityServer. Since the serializer is using data protection, I'd like to be sure I'll be able to un-protect anything that was protected with the original dataProtectionProvider?.CreateProtector(nameof(PersistentGrantSerializer)); as long as the purpose param of the protector is same between these serializer?

A list of steps would be:
- implement CustomPersistentGrantSerializer
- override GetItemByHashedKeyAsync
- use the "other" serializer within this method

**Comment by brockallen** [comment]
I'll let Joe reply to your other questions, but you can also disable the data protection, if you don't need it.

https://docs.duendesoftware.com/identityserver/v6/reference/options/#persistentgrants

**Comment by skatanski** [comment]
Thanks. Hopefully I can make it work without disabling data protection. We are really happy that it's been introduced - we've had a ticket in our queue to introduce some sort of encryption to persisted grants ourselves.

Actually I think I don't have to introduce a copy of the serializer, I think all we need to do is copy the method:

```
        private void PostProcess(RefreshToken refreshToken)
        {
            if (refreshToken != null && refreshToken.Version < 5)
            {
#pragma warning disable CS0618 // Type or member is obsolete
                var user = new IdentityServerUser(refreshToken.AccessToken.SubjectId);
                if (refreshToken.AccessToken.Claims != null)
                {
                    foreach (var claim in refreshToken.AccessToken.Claims)
                    {
                        user.AdditionalClaims.Add(claim);
                    }
                }

                refreshToken.Subject = user.CreatePrincipal();
                refreshToken.ClientId = refreshToken.AccessToken.ClientId;
                refreshToken.Description = refreshToken.AccessToken.Description;
                refreshToken.AuthorizedScopes = refreshToken.AccessToken.Scopes;
                refreshToken.SetAccessToken(refreshToken.AccessToken);
                refreshToken.AccessToken = null;
                refreshToken.Version = 5;
#pragma warning restore CS0618 // Type or member is obsolete
            }
        }
```
To our own RefreshTokenStore class and call it after the token has been serialized, until we are on version > Duende.IdentityServer 6.0.0

**Comment by josephdecock** [comment]
I think adding this post processing to your own class is a good idea, and so it sounds like you don't need the serializer. Just in case you do, you're correct that you should be able to unprotect by keeping the purpose string the same. Is there any thing else we can help with here?

**Comment by skatanski** [comment]
thanks @josephdecock 
I think to summarize, the issue with refresh token being null stems from:
- updating IS4 to IS6.0.0
- overwriting RefreshTokenStore and missing on the token post processing logic, which was moved
And above are some ways to fix it
