### ISSUE TITLE
Identityserver release in IIS Authorize error

### ISSUE THREAD

**Issue by YangYueWeiQing** [DuendeSoftware/Support#46]
**Which version of Duende IdentityServer are you using?**
6.0.4
**Which version of .NET are you using?**
.net 6
debug in vs is success but release in IIS throw exception

in controller

            [Authorize(AuthenticationSchemes = "JTBearer", Roles = "SYSADMIN")]
            public class MenuController : ControllerBase

in AuthenticationSettings

          .AddJwtBearer("JTBearer", options => {
            options.Authority = "https://localhost:8888";
           #if DEBUG
            options.Authority = "https://localhost:1668";
           #endif
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateAudience = false,
                ValidateLifetime = true,
                RequireExpirationTime = true,
            };
            
            //options.RequireHttpsMetadata = false;
        });

throw exception
<img width="736" alt="error" src="https://user-images.githubusercontent.com/32123609/166187214-f805c8e2-09ee-41be-8d51-6f5b291e94a0.png">
Please help me, thank you very much.

**Comment by brockallen** [comment]
Sounds like a TLS and certificate trust issue for the server being connected to.

**Comment by leastprivilege** [comment]
> .AddJwtBearer("JTBearer", options => {
        options.Authority = "https://localhost:8888";

Seems to be your production setting - I don't think this would work - use the fqdn instead.

Or use the local API feature to not having to deal with these nuances
https://docs.duendesoftware.com/identityserver/v6/apis/add_apis/

**Comment by leastprivilege** [comment]
any update?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
