### ISSUE TITLE
Keys for JWT and Load Balanced Servers

### ISSUE THREAD

**Issue by glenndorr-ntracts** [DuendeSoftware/Support#462]
We are using the automatic keys. In production our auth services are load balanced and hosted in App Services in Azure.

Is there an article we can still use keys on rotation by Duende in this type of environment?

We get different kid claims depending on which service the load balancer points to, which of course, is a problem.

**Comment by josephdecock** [comment]
Which implementation of the ISigningKeyStore are you using? Are all the instances sharing data protection keys? Are you getting exceptions?

Some material you may find helpful from our docs:
- https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/
- https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/
- https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by josephdecock** [comment]
We publish implementations of ISigningKeyStore that use the filesystem (this is the default), or that use EntityFramework to write to a database - this is built in to the the EF operational stores. We don't maintain an azure key vault implementation, but it seems like it would be straightforward for you to implement - the [store interface](https://docs.duendesoftware.com/identityserver/v6/reference/stores/signing_key_store/) is just 3 methods - create, read, and delete.

I'm assuming that right now you're using the file system based implementation? If you want to keep using that, you need to configure it to read and write keys to a file system location shared by all the instances. With an azure app service, that's usually pretty easy to set up. See Microsoft's docs for more info: https://learn.microsoft.com/en-us/azure/app-service/operating-system-functionality#file-access

**Comment by glenndorr-ntracts** [comment]
Thank you

**Comment by josephdecock** [comment]
You're welcome! I'll close the issue then, but feel free to follow up as needed.
