### ISSUE TITLE
Refresh Token Not Received

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#464]
Duende 6.1.1
.NET 6

When a token exchange is attempted (POST to /connect/token), the access token is received but not the refresh token. The client configuration explicitly allows the OfflineAccess scope. What else do I need to do to make this work properly?

Thanks,
Bill

**Comment by josephdecock** [comment]
Double check that the authorize request included the offline_access scope, and then check the IdentityServer logs to see if there was a validation warning or error.

**Comment by billcunnien** [comment]
I am checking with the vendor regarding the inclusion of that scope in the initial authorization request.

Is there some log that the IS writes for warnings or errors? Not sure I see that anywhere.

**Comment by brockallen** [comment]
> Is there some log that the IS writes for warnings or errors

It's not an error to not request offline_access, thus there's nothing to log.

**Comment by billcunnien** [comment]
No problem. Thanks!

**Comment by brockallen** [comment]
Sorry -- we do emit logs, though. We doc that here: https://docs.duendesoftware.com/identityserver/v6/diagnostics/logging/

**Comment by billcunnien** [comment]
If the vendor adds the scope, they are getting an invalid_scope error. The scope has been allowed for the client. If the vendor removes the scope then they get a valid response with only the access token and no refresh token. Any other thoughts?

**Comment by josephdecock** [comment]
The IdentityServer logs from when a request returns invalid_scope should include more details about why that error response was given.

**Comment by billcunnien** [comment]
Ok, I have adjusted logging. We will try some tests again tomorrow and see if anything pops up. Thanks!
