### ISSUE TITLE
Not able to get the Profile claims

### ISSUE THREAD

**Issue by pan15jain** [DuendeSoftware/Support#465]
We had implemented Identity server 6 and using it for our blazer application. while configuring the identity server we had profile.
new IdentityResources.Profile() and users table has family_name and gender as column.
![image](https://user-images.githubusercontent.com/68628199/214450430-4c1b0316-cd26-4a82-9748-9427544ed846.png).
we have scope defined in our web application 
"Scope": [ "openid", "profile", "email", "offline_access" ],

We are not greeting the Gender and family name in the claims. we are expecting if we define profile on identity server and web application then given_name, family_name, gender must be there in claims if they exist in identity database.
Please let me know what we are missing so we can fill our gaps.

Thanks
Pankaj

**Comment by pan15jain** [comment]
Yes.. client application is requesting the user info endpoint.
![image](https://user-images.githubusercontent.com/68628199/214473334-49916a2b-4e79-451d-a2fe-fc4144a0428d.png)
![image](https://user-images.githubusercontent.com/68628199/214473381-e243028a-be17-497b-99c9-7d59527000f4.png)
We are getting 9 claims but not getting any claims related to profile.
scope define in identity server.
![image](https://user-images.githubusercontent.com/68628199/214473626-57e4d341-1a26-4f17-a715-516a64e00f15.png)

Thanks
Pankaj

**Comment by josephdecock** [comment]
Can you show how you've configured the openId connect authentication handler in the bff?

**Comment by pan15jain** [comment]
![image](https://user-images.githubusercontent.com/68628199/214476610-a0a2811f-b6ec-4650-b871-ba54d4c34488.png)
![image](https://user-images.githubusercontent.com/68628199/214476667-69ee3d1d-e58c-4763-bab0-f3253994d8aa.png)

**Comment by josephdecock** [comment]
Thanks - can you also share the app settings that configuration code relies on?

**Comment by pan15jain** [comment]
![image](https://user-images.githubusercontent.com/68628199/214480701-75ed2fad-f849-4041-8fd9-0d78bd9c0f71.png)

**Comment by josephdecock** [comment]
For the gender claim, you need to add a claim action to the OIDC scheme so that it will map the claim from the json into the session. 

`ClaimActions.MapUniqueJsonKey("gender", "gender")`

For given name and family name, the default claim actions should already include them, if they are included in the userinfo output. I notice that the column name of given_name appears to be giver instead of given so you probably need to correct column names. Are you using aspnet identity to store users?

**Comment by pan15jain** [comment]
yes I am using aspnet identity to store users.

**Comment by josephdecock** [comment]
Okay, then you need to add GivenName, FamilyName, and Gender to your ApplicationUser. We have a [tutorial](https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/) on how to use ASP.NET Identity with IdentityServer that includes a [section](https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/#adding-custom-profile-data) on adding custom properties.

**Comment by pan15jain** [comment]
Thanks Joe.
I had those column in my users entity.
![image](https://user-images.githubusercontent.com/68628199/214630874-e36e0b4b-400e-4175-aaa8-05afc29dc46f.png)
![image](https://user-images.githubusercontent.com/68628199/214631122-bfa974e6-61c4-4626-80ea-463b8d05ffff.png)
Maybe I might be missing something else also. will review again and will connect with you.

Thanks for quick responses. I will go through the tutorial toughly.

**Comment by pan15jain** [comment]
Hi Joe,

My userClaim table has no row and I show the code snippet from the tutorial you provided and it seems that we need to add claims as below code.
![image](https://user-images.githubusercontent.com/68628199/214647255-3cf36666-df14-4385-8e12-0b7bf8d17dc5.png)
I was in the impression that if we had define profile scope it will pick corresponding column like family_name, given_name default and will return as claims. I think I understanding was incorrect. We had to insert claims in userClaim table. 
Please correct me and your thought.

Thanks
Pankaj

**Comment by pan15jain** [comment]
Thanks Joe for sharing me the link.
Adding Highlighted code work as expected.
![image](https://user-images.githubusercontent.com/68628199/214685519-00ceef08-423a-4ae3-b0ff-cdbe079ddaba.png)

Just one more clarification is requested.
Based on document its state that profile scope can access below claims but I was able to access family_name and given_name for website I had to use ClaimActions.MapUniqueJsonKey as suggested by you. It is bit confusing. Though Please
This scope value requests access to the End-User's default profile Claims, which are: <c>name</c>, <c>family_name</c>, <c>given_name</c>, <c>middle_name</c>, <c>nickname</c>, <c>preferred_username</c>, <c>profile</c>, <c>picture</c>, <c>website</c>, <c>gender</c>, <c>birthdate</c>, <c>zoneinfo</c>, <c>locale</c>, and <c>updated_at</c>.</summary>
![image](https://user-images.githubusercontent.com/68628199/214685320-0d6e2239-2894-464a-a346-ee812a9e006f.png)

**Comment by josephdecock** [comment]
The ClaimActions are part of the design of the OIDC Authentication Handler. Even though IdentityServer is putting the claims you've requested into the token and/or userinfo response, the OIDC Handler doesn't copy those claims into the application's session. It only will copy claims that it has a ClaimAction for. By doing it this way, some claims that you probably don't want in your session are filtered out (e.g., the exp claim says that the ID Token expires at a certain time, which is not applicable to the user's session). The downside is that claims that were included because of scopes that were explicitly requested are also excluded.

**Comment by pan15jain** [comment]
Thanks Joe.. That was a great learning for me. I am closing it as It answer all the questions.
