### ISSUE TITLE
Issue migrating from v5.2.4 to v6.2.1 using sqlite

### ISSUE THREAD

**Issue by Rainnwind** [DuendeSoftware/Support#466]
Hi, I'm seeing an issue when trying to upgrade my identity server from v5.2.4 to v6.2.1.

**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer and Duende.IdentityServer.EntityFramework v6.2.1

**Which version of .NET are you using?**
.net6.0

**Describe the bug**
In the attempt to upgrade Duende.IdentityServer from v5.2.4 to v6.2.1 from netcoreapp3.1 to net6.0 I'm seeing a migration issue:
`Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 19: 'UNIQUE constraint failed: ef_temp_PersistedGrants.Id'.'`

The query that failed was:
```
INSERT INTO 
	"ef_temp_PersistedGrants" 
	(
		"Id",
		"ClientId",
		"ConsumedTime",
		"CreationTime",
		"Data",
		"Description",
		"Expiration",
		"Key",
		"SessionId",
		"SubjectId",
		"Type"
	)
SELECT
	"Id",
	"ClientId",
	"ConsumedTime",
	"CreationTime",
	"Data",
	"Description",
	"Expiration",
	"Key",
	"SessionId",
	"SubjectId",
	"Type"
FROM
	"PersistedGrants;
```

**To Reproduce**
The database used is sqlite.

1. Setup an identity server with Duende.IdentityServer and Duende.IdentityServer.EntityFramework v5.2.4 and fill up PersistedGrants with data.

2. Follow the guide [Duende IdentityServer v6.0 to v6.1](https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.0_to_v6.1/)

**Expected behavior**

The migration should not fail due to a unique constraint.

**Log output/exception with stacktrace**
`Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 19: 'UNIQUE constraint failed: ef_temp_PersistedGrants.Id'.'`

**Comment by Rainnwind** [comment]
Hi Joseph, thanks for getting back.

I have tested this behaviour with the following project: https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/Quickstarts/4_EntityFramework

Setting up this project generates the following schema in sqlite.

```
CREATE TABLE IF NOT EXISTS "PersistedGrants" (
    "Key" TEXT NOT NULL CONSTRAINT "PK_PersistedGrants" PRIMARY KEY,
    "Type" TEXT NOT NULL,
    "SubjectId" TEXT NULL,
    "SessionId" TEXT NULL,
    "ClientId" TEXT NOT NULL,
    "Description" TEXT NULL,
    "CreationTime" TEXT NOT NULL,
    "Expiration" TEXT NULL,
    "ConsumedTime" TEXT NULL,
    "Data" TEXT NOT NULL
);
CREATE INDEX "IX_PersistedGrants_Expiration" ON "PersistedGrants" ("Expiration");
CREATE INDEX "IX_PersistedGrants_SubjectId_ClientId_Type" ON "PersistedGrants" ("SubjectId", "ClientId", "Type");
CREATE INDEX "IX_PersistedGrants_SubjectId_SessionId_Type" ON "PersistedGrants" ("SubjectId", "SessionId", "Type");
```

I set the AllowOfflineAccess to `true` and started signing in as Alice and Bob several times over to fill up the database.

I then upgraded to the latest IdentityServer 6.2.1, added the new migrations and tried updating the database.
This is when it failed.

From what I can tell from the migration it's adding a new column: `Id` which has to be unique.
And while the migration also states that this value should auto increment it doesn't seem to do so when updating the database.
At least it fails on a unique constraint.

This is the expected updated schema for `PersistedGrants` for v6.2.1
```
CREATE TABLE IF NOT EXISTS "PersistedGrants" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PersistedGrants" PRIMARY KEY AUTOINCREMENT,
    "ClientId" TEXT NOT NULL,
    "ConsumedTime" TEXT NULL,
    "CreationTime" TEXT NOT NULL,
    "Data" TEXT NOT NULL,
    "Description" TEXT NULL,
    "Expiration" TEXT NULL,
    "Key" TEXT NULL,
    "SessionId" TEXT NULL,
    "SubjectId" TEXT NULL,
    "Type" TEXT NOT NULL
);
CREATE INDEX "IX_PersistedGrants_ConsumedTime" ON "PersistedGrants" ("ConsumedTime");
CREATE INDEX "IX_PersistedGrants_Expiration" ON "PersistedGrants" ("Expiration");
CREATE UNIQUE INDEX "IX_PersistedGrants_Key" ON "PersistedGrants" ("Key");
CREATE INDEX "IX_PersistedGrants_SubjectId_ClientId_Type" ON "PersistedGrants" ("SubjectId", "ClientId", "Type");
CREATE INDEX "IX_PersistedGrants_SubjectId_SessionId_Type" ON "PersistedGrants" ("SubjectId", "SessionId", "Type");
```

**Comment by Rainnwind** [comment]
I forgot to mention.
I tried creating a backup of the database from v5.2.4 and started the IdentityServer to create the database with the latest migrations and no data at all.
This worked fine. I then copied data from the backup into the new database with the latest migrations and this worked well also.

**Comment by josephdecock** [comment]
Okay, I'm glad things are working for you. It sounds like the EF sqlite provider doesn't safely generate migrations that add a unique constraint to a table. If that's the case, then there isn't much the we can do from IdentityServer - it really sounds like an EF bug to me. Might be good to raise with the EF folks: https://github.com/dotnet/efcore. But if after some manual wrangling, you've got your IdentityServer database in a good state, I think we can close this issue.

**Comment by Rainnwind** [comment]
Yes. I think you might be right that this issue belongs to EF.
I will look into creating an issue with their support instead.

Thank you for your time!
