### ISSUE TITLE
Getting updated claim values from the /bff/user endpoint

### ISSUE THREAD

**Issue by michelletimmons** [DuendeSoftware/Support#467]
**Which version of Duende BFF are you using?**
1.2.3

**Which version of .NET are you using?**
5.0

**Describe the bug**
This is a follow-up to my previous question #429, where with help from @josephdecock I was able to get my custom claim to appear at the /bff/user endpoint. My next problem is that the value of this claim may change, and subsequent calls to /bff/user do not reflect the updated value, even after a token refresh has been triggered.

I have a feeling this is because the claims are stored in the session data, is that right? In my case that would be the UserSessions table in the database. I assume that the session data is set when the user logs in, and is never updated.

**To Reproduce**

My code is as per #429. After logging in, my custom claim appears at the /bff/user endpoint.

I then change the value of this claim in the back end.

At the appropriate time, a token refresh occurs. My version of UserClaimsPrincipalFactory is called and the new claim value is read from the back end.

After a period of time, the web app makes another call to /bff/user. Even though a token refresh has occurred, the response to /bff/user still contains the old claim value.

**Expected behavior**

I would like to see the updated claim value. Am I right in thinking that the claims are loaded at log in, stored in the session data and never updated? If so, what is the recommended way of achieving this?

I read this issue which seems similar #371, but in that case it sounds like their session data was stored within the cookie rather than in the UserSessions table.

**Comment by brockallen** [comment]
Hi @michelletimmons. What you describe is a general issue with OIDC, and beyond what the BFF framework is meant to handle and supports.

As for a solution, it's more up to you how you'd decide to achieve this. You could write code to re-invokes the userinfo endpoint, and then re-create the local session using ASP.NET Core's authentication APIs. Or you could just re-trigger Challenge making the full OIDC round trip workflow. 

But there's a general problem -- when would your app know to do these things? Only you based on your architecture would know those things.

**Comment by josephdecock** [comment]
Also, we have docs specifically on customizing the user endpoint [here](https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/management/user/).

**Comment by michelletimmons** [comment]
Hi @josephdecock thanks for the explanation, that's really helpful. It sounds like I have 2 options:

- Make my own call to the Identity Server's userinfo endpoint as this always returns the updated claims
- Override GetUserClaims in the /bff/user endpoint to generate the updated claims

**Comment by josephdecock** [comment]
I think you're the right track, just keep in mind that the userinfo endpoint is a protected resource that you'll need an access token to get at. The access token you need is stored in the bff's session, so you're very likely going to be going through the bff in some capacity.

**Comment by josephdecock** [comment]
It looks like this issue can be closed, but feel free to reopen if necessary.
