### ISSUE TITLE
Client cannot request OpenID scopes in client credentials flow

### ISSUE THREAD

**Issue by DANDINARDO** [DuendeSoftware/Support#469]
Duende IdentityServer  v6.2.1
.NET 6.0

When trying to secure a token using a client credentials grant we get the following error.  "Client cannot request OpenID scopes in client credentials flow".  Below is the request.  

POST /connect/token HTTP/1.1
Host: localhost:5000
Content-Type: application/x-www-form-urlencoded
Content-Length: 108
client_id=XTSite_ClientFlow&client_secret=***************&grant_type=client_credentials&scope=admin

As you can see, we are not passing openid as a scope.  "admin" is defined in our IdentityResources table, and the relationship between the scope and the client is defined in the ClientScopes table.  

We are able to secure tokens from other flows.  Is it potentially some value that we have configured on the client record?  We had no issues acquiring a token with this flow in IdentityServer3 or IdentityServer4

Thanks for any input

**Comment by josephdecock** [comment]
IdentityServer models scopes as either ApiScopes or IdentityResources. By defining admin as an IdentityResource, you are telling IdentityServer that admin is a scope that produces claims about a user. That only makes sense in a flow that includes an interactive user, so it is an error to request an ApiResource scope in the client credentials flow. You probably need to change this scope into an ApiScope.

For more details, see [this chapter](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/) in our docs.

**Comment by DANDINARDO** [comment]
@josephdecock  ... thank you very much.  That was exactly the piece I was missing.  I just needed to define the APIScope instead of the ClientScope and everything worked as expected.  Thank you for your help!
