### ISSUE TITLE
How to use signing keys stored in Azure (e.g. Azure Key Vault)?

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#47]
Dear Duende Team,

is there posibility use signing keys stored in Azure? 

If yes, is automatic key management supported in this case? Could you please point me to an example?

Thank you and best regards,
Novak

**Comment by brockallen** [comment]
> is there posibility use signing keys stored in Azure?

Depends what you mean. If you want KeyVault to create the signing key, then yes, you'd implement the ISigningCredentialStore, and the IValidationKeysStore, but you would not be getting our automatic key management.

If no and you just want azure to store the keys created from the automatic key management then you'd implement the signing key store: https://docs.duendesoftware.com/identityserver/v6/reference/stores/signing_key_store/. 

We don't have samples for key vault, sorry.

**Comment by No1e** [comment]
Well, I wanted to find out what is supported.

The option with using automatic key management and custom SigningKeyStore sounds pretty good.

Thank you very much!
