### ISSUE TITLE
Looking for guidance on how to implement a "manager's authorization" flow

### ISSUE THREAD

**Issue by scottbrentsansom** [DuendeSoftware/Support#470]
**Which version of Duende IdentityServer are you using?**
6.1.1

**Which version of .NET are you using?**
6.0.402

**Describe the question**

We are currently working to integrate IdentityServer into our technology stack (ASPNet Core REST services backend and Typescript/React front end) and have thus far been successful at securing the UI/API using a duende based identity server. Our problem now is that we need to support the concept of "supervisor's authorization" to perform a sensitive operation. From my reading I don't see any oidc flows that match this type of use case. I did run across this discussion which suggested either step up authentication or CIBA, neither of which seems to be a fitting solution in this case: 
https://stackoverflow.com/questions/72445780/oidc-client-sign-in-as-different-user

Any suggestions or pointers would be greatly appreciated.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
Can you describe in more detail what requirements you have for how manager approval can be given? It seems like a tricky user experience.

One way you might model this: users that want to perform a sensitive action can put in a request for that action to be performed. Managers can see those requests and approve or deny them.

**Comment by scottbrentsansom** [comment]
We have a telco retail store clerk who is logged in to a point-of-sale front end (Typescript/React)
 that uses a REST services backend, both of which have been secured with identity server. A customer enters the store who would like to return a recently purchased iPhone. In order to do so the clerk needs their manager to authorize the return by providing their credentials from the same device the clerk is using to authorize the return. I was thinking this could perhaps be done by loading the login page in an iframe on the return authorization page, but this is as far as I've gotten with that thought.

Thank you kindly for the assistance.

**Comment by josephdecock** [comment]
There isn't really a way built in to OAuth or OpenIDConnect to support your requirements, so I don't have a standard answer or sample to share here, unfortunately. There's a good amount of design that will have to be done to support this. Some of the big issues are session coordination (multiple user sessions on one device is tricky), the user experience, where does the approval occur, and how do you associate the elevated permissions with the action the user is taking (how long do the elevated permissions last?) 

We can't do all of that design and software architecture over standard support, but we do offer consulting services - please [get in touch](https://duendesoftware.com/contact) if you are interested.

**Comment by scottbrentsansom** [comment]
Thank you for clarifying - this was what I suspected but I wanted to make sure I wasn't missing a simpler way of doing this.

Much appreciated.
