### ISSUE TITLE
Unable to host DuendeSoftware/Samples/IdentityServer/v6/mtls (https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/MTLS) on IIS

### ISSUE THREAD

**Issue by clajay** [DuendeSoftware/Support#472]
**Which version of Duende IdentityServer are you using?**
6.0.0
**Which version of .NET are you using?**
.NET 6
**Describe the bug**
Unable to host DuendeSoftware/Samples/IdentityServer/v6/mtls (https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/MTLS) on IIS

- Identity Server hosted properly
![image](https://user-images.githubusercontent.com/110338735/215677294-cb50ea29-5678-47a1-9ab6-c21afbd4ee72.png)
- Discovery document 
![image](https://user-images.githubusercontent.com/110338735/215677442-07cc3098-5adb-4df6-87f0-975638290fd9.png)
- Console App raise exception 
![image](https://user-images.githubusercontent.com/110338735/216038633-d977214d-4be2-4804-8279-12cea554acc1.png)

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

NOTE: It is working well with Kestral.

**Comment by josephdecock** [comment]
Running mTLS in IIS is a fairly complex topic, and unfortunately beyond the scope of what we can cover in our support forums for IdentityServer. I'd recommend that you simplify and start out by getting mTLS working in IIS without IdentityServer at all. You might need support from Microsoft to get that working, but once you do have the mTLS configuration in place and working, only then add IdentityServer. I'm closing this issue for now, but if you get mTLS working in a standalone fashion and need help with IdentityServer specifically, feel free to reopen this or start a new issue.
