### ISSUE TITLE
Session Spelled wrong

### ISSUE THREAD

**Issue by SriramaDanturthi** [DuendeSoftware/Support#473]
There is spelling mistake to to the word session in the code base
https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/EndpointServices/Logout/DefaultLogoutService.cs#L72
sesison is not correct it should be session

**Comment by StuFrankish** [comment]
I've raised a PR under https://github.com/DuendeSoftware/BFF/pull/159 for this.

**Comment by brockallen** [comment]
Thank you both! PR is merged.
