### ISSUE TITLE
nbf and exp

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#476]
Using DIS v6 with .NET 6, our server time is set to EST (default for our servers), but the nbf and exp are expected to be in UTC. They appear to be taking the server time in EST. What is the easiest way to set these values to UTC?

Thanks!

**Comment by billcunnien** [comment]
Quick update - I am already setting the expiration explicitly:

new(ClaimTypes.Expiration, DateTime.UtcNow.AddMinutes(15).ToString(CultureInfo.InvariantCulture)),

That is definitely UTC. :) I do not see any ClaimType for nbf.

**Comment by josephdecock** [comment]
You shouldn't need to set the expiration like that - IdentityServer should be setting the nbf and exp claims in your tokens automatically. Also, the specifications require that timestamps are represented as unix timestamps. IdentityServer should be following that - if not, there could be a bug (or perhaps you have more customizations?)

This IdentityServer code sets the timestamps
```cs
            // set times (nbf, exp, iat)
            var now = clock.UtcNow.ToUnixTimeSeconds();
            var exp = now + token.Lifetime;
                
            payload.Add(JwtClaimTypes.NotBefore, now);
            payload.Add(JwtClaimTypes.IssuedAt, now);
            payload.Add(JwtClaimTypes.Expiration, exp);
```

**Comment by billcunnien** [comment]
I see a setting in the client configuration called AccessTokenLifetime. I set that to 900 (15 minutes). I am hoping that is the proper way to handle the expiration.

I am also trying to set certain custom claims after a user logs in, like this:

`            // values necessary for token generation
            customUser.Claims = new List<Claim>
            {
                new("unique_name", customUser.Username),
                new(ClaimTypes.UserData, customUser.ANumber.ToString()),
                new("role", "VendorClient"),
                new("ACustomClaim", customUser.ABool.ToString()),
                new("BCustomClaim", customUser.AString),
                new(ClaimTypes.System, customUser.System)
            };`

This is passed back to the AdditionalClaims property of the IdentityServerUser. This does produce an access token that works. But, if there is a better way to handle this, then please let me know. 

I removed the expiration setting.

**Comment by josephdecock** [comment]
Yes, use AccessTokenLifetime, and yes, passing claims into the IdentityServerUser is a fine way to add claims like this. _If_ you need more control or logic when producing, you could also consider using the ProfileService, but it doesn't sound like you need that right now. See [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/).
