### ISSUE TITLE
AUTO LOGIN EXTERNAL APP (WINDOWS FORMS .net), redirect web page with autentification.

### ISSUE THREAD

**Issue by PaulMora93** [DuendeSoftware/Support#478]
Good afternoon, I want to know if there is a way to authenticate a web page that has its login at the time of entering, it asks for a username and password when it is typed, now what I need is that it does not ask for the login but authenticates itself from the C# code, you They have an example of the api where the credentials are sent and I get the token and I can access the data, I want that but with a web page

**Comment by josephdecock** [comment]
I'm not sure if I'm following you. Since you're talking about a web page, there must be an interactive user making requests for that page. Is the identity of that user important to your application? If you want to authenticate that user, in the sense of determining if it is Joe or Paul or whoever else that is sending requests to your site then you need some sort of interactive flow where you get input from the user.

**Comment by PaulMora93** [comment]
A user logs in with another authentication system on web page A, immediately permission must be generated to web page B that uses Identityserver4, and on Web page B the role of the user who authenticated on web page A must be known.

**Comment by josephdecock** [comment]
It sounds like you're more or less describing a Single Sign On scenario, which is very easy to implement with OIDC and IdentityServer.

If both sites A and B have IdentityServer as their OIDC authority, whichever of the two sites is used first will initiate an OIDC flow to log in. Identity Server will prompt the user to enter their credentials, and then IdentityServer creates its own session, stored in a cookie. The user will then be sent back to the site that initiated the flow, which will complete the flow and start its own session.

Then, when the other site is used, it also will start an OIDC flow. This time, IdentityServer will see its session cookie and therefore not need to prompt the user to login. The user won't need to do anything, and they'll end up logged in on the second site.

One final note is that IdentityServer4 has reached its end of life, and is no longer receiving support. It also can't be run on a version of .NET that is supported by Microsoft either, so we do recommend that you upgrade to Duende.IdentityServer.

**Comment by PaulMora93** [comment]
Well, thanks for the information, if I have to migrate, regarding the problem, web page A does not use identityServer4, it uses the CAS protocol, that is, it has its own authentication.

**Comment by josephdecock** [comment]
It sounds like you're going to need to make some architectural changes to support single sign on across these applications.

Considerations for you to think about:
- What authentication protocol do you want to use?
   - If you're going to standardize on OpenIdConnect, then application A will need to be updated
   - If you're going to standardize on CAS, then application B will need to be updated, and basically at this point you'd be choosing not to use IdentityServer
   - If you want to interoperate between OpenIdConnect and CAS, that is probably a pretty challenging undertaking. You can build an IdentityServer that can federate with other authentication protocols - for example, we commonly see this with SAML. But support for CAS is not something that we build in to IdentityServer and is beyond the scope of what we can directly support on these forums.
- For your application B that is using identity server, is IdentityServer built in to application B or do you have an external host for IdentityServer.
  - You need an external host to achieve single on with IdentityServer, but some templates mix the client application and identity provider together into one host. If application b is like that, you'll have to divide it into separate hosts. We document that process [here](https://docs.duendesoftware.com/identityserver/v6/upgrades/spa_to_duende/)

**Comment by PaulMora93** [comment]
Application B is not integrated with the IdentityServer server, this server is in another application, that is, if we have separated it, for example our web page B, it is from the address https://pruebas.ec:800 and the authority is in https //:pruebas.ec:443, now a question in the C# code of application A, is there how to configure something so that it calls application B and no longer shows the login? For example, for the API we call from application A like this

var tokenResponse = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
             {
                 Address = disk.TokenEndpoint,
                 ClientId = "client",
                 ClientSecret = "secret",
                 Scope="api1"
             });
            
             if (tokenResponse.IsError)
             {
                 Console.WriteLine(tokenResponse.Error);
                 return;
             }

             Console.WriteLine(tokenResponse.Json);
             Console.WriteLine("\n\n");

             // call api
             var apiClient = new HttpClient();
             apiClient.SetBearerToken(tokenResponse.AccessToken);

             var response = await apiClient.GetAsync("https://localhost:6001/identity");
             if (!response.IsSuccessStatusCode)
             {
                 Console.WriteLine(response.StatusCode);
             }
             else
             {
                 var content = await response.Content.ReadAsStringAsync();
                 Console.WriteLine(JArray.Parse(content));
             }
         }



As you can see, we only send the access token to the API and the data can now be accessed. Can't we do something like this with the problem we have?

**Comment by josephdecock** [comment]
The Open ID Connect single sign on flow that I described above is the most similar thing to what you're showing. In the API example, both the API and the application use the Authorization Service (Identity Server) as their authority. That allows the api to authorize requests using tokens. Similarly, for applications to authenticate using tokens, all the applications must trust the same OpenIdConnect Provider (Identity Server).

**Comment by PaulMora93** [comment]
Could you send us an example where from a windows forms application you call the web page and it is already authorized without the need to log in, in the API model that was sent as an example

**Comment by josephdecock** [comment]
Here are a couple of winforms samples:
- https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/main/WinFormsWebView
- https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/main/WinFormsWebView2

**Comment by PaulMora93** [comment]
In these applications it is shown to enter username and password, what I want is that it does not show that screen that the login is carried out automatically in the windows forms code

**Comment by josephdecock** [comment]
If you want to establish the identity of the interactive user, there's going to have to be some user interaction. But again, if you have multiple applications sharing an authority, you get single sign in automatically.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
