### ISSUE TITLE
TokenRequests with an empty Resource field are rejected by /identity/connect/token

### ISSUE THREAD

**Issue by krosn** [DuendeSoftware/Support#48]
**Which version of Duende IdentityServer are you using?**
version 5.2.4

**Which version of .NET are you using?**
net 5.0

**Describe the bug**

Not sure if this is actually a bug, but we're running into an issue integrating with Azure Synapse due to this behavior. When Azure Synapse sends a token request to the /identity/connect/token endpoint,  they always send a "Resource" field in the token request. Even when the corresponding field in the Synapse connector field is left blank, they still send a "Resource" field with an empty value. This is causing an issue because we don't use resource isolation, so we leave that field blank, so Azure Synapse sends a "Resource" field with an empty value, and it is ultimately rejected by the token endpoint (see [TokenRequestValidator](https://github.com/DuendeSoftware/IdentityServer/blob/50e71c72eb3905acc9fda4e0fa86c2510db665ea/src/IdentityServer/Validation/Default/TokenRequestValidator.cs#L150)) for not being a valid uri.

**To Reproduce**

Test an Azure Synapse connector with a blank resource field against an IdentityServer token endpoint or send a request like this to an IdentityServer token endpoint:

![image](https://user-images.githubusercontent.com/24685086/166269131-d3a7f450-5fed-4357-b27f-dadb85cd4b0c.png)

Observe that this is the response:

![image](https://user-images.githubusercontent.com/24685086/166269200-a6dfc901-d692-4796-888a-446ef0fac1fe.png)

**Expected behavior**

Either the resource field is ignored when null/whitespace, or confirmation that this is standard-compliant behavior, so we can re-raise this issue with Azure support.

**Log output/exception with stacktrace**

```
{
	"error": "invalid_target",
	"error_description": "Invalid resource indicator format"
}
```

**Additional context**

We tried raising this issue with Azure Synapse support first to see if they could not send the form field when it is empty, but they were confident that the connector is behaving as intended when it sends an empty resource field in the token request. If this is something that IdentityServer wants to support, I can make a PR, otherwise we can go back to Azure support with confirmation that they are not behaving in a specification-compliant manner.

**Comment by brockallen** [comment]
We accept the resource parameter according to [RFC8707](https://datatracker.ietf.org/doc/html/rfc8707). I suspect that's being passed internally that Azure product because of AAD's custom resource parameter (unrelated to RFC8707), but that's really just a guess (no idea why/where they are using it).

I'd ask them to not do that, as it conflicts with the published RFC. If they won't/can't then the only thing I can think of is to write middleware in front of IdentityServer to remove that param from the request.

**Comment by krosn** [comment]
Thanks Brock. 

The resource field is exposed in their UI for the connector. I'm not familiar with their AAD parameter, but it seems like the intention here is to support resource isolation like in RFC8707, so it does seem odd that when the field is left blank they still send it.

Here is a picture of their UI:
![image](https://user-images.githubusercontent.com/24685086/166300075-2a11c0e7-6bf3-4277-8f7c-2decc1aba084.png)

I will try following up with them again and letting them know that this won't be addressed in IdentityServer because Synapse is the one not complying with the RFC. In the meantime I'll start planning to add middleware as a workaround like you suggested. Even if Azure comes around, I suspect it would take quite some time for this to be resolved.

**Comment by brockallen** [comment]
Looking at that UI, it sort of seems like it is trying to follow the RFC (I don't know enough about that product). It's just that the value is sent even if blank.

**Comment by krosn** [comment]
Honestly, I don't know a ton about the product either. I'm helping another developer who isn't familiar with the identity side of things try to get Azure Synapse working. 

What's really odd is that I can see in the network requests that when we edit the connection settings, if we leave the resource blank, the call back to Azure (to their API, not the token request) to update the settings omits the resource field as we would expect. It's later when they send the token request that this empty resource field shows up.

Considering that the only valid value for a resource is an absolute URI, it seems reasonable to treat null/empty/whitespace as not specifying a resource. I can create a PR later to address this if that helps.

**Comment by brockallen** [comment]
> I can create a PR later to address this if that helps.

Nah, that's ok -- we have to think about that internally first. Thanks tho.

**Comment by brockallen** [comment]
Submitted a PR with a couple of proposals for fixing. We'll track there and I'll close this. Thx.
