### ISSUE TITLE
Can Duende IdentityServer v6 be used in a .Net Framework Application?

### ISSUE THREAD

**Issue by KvnSearle** [DuendeSoftware/Support#480]
Hi All,

We are reviewing our our applications which use IdentityServer now it has rebranded to Duende become a subscription model and have come across a forgotten application which consists of a number of .Net Framework projects, one of which references the dll's IdentityServer3 and IdentityServer3.WsFederation.

If we want to be using a supportable we need to upgrade to IdentityServer v6 but given that this is a .Net 6 application, the only route I can see to this is to upgrade all the projects in the solution to be .Net 6 also.

Is there a supported .Net Framework compatible version of IdentityServer?

If not is there a trick I am missing which means I don't have to upgrade the entire solution to .Net Core and maybe limit it to just the one project that references these two dll's?

Thanks in advance

**Comment by leastprivilege** [comment]
Hi, 

IdentityServer v6 requires .NET 6. You need to upgrade the code base.

**Comment by josephdecock** [comment]
One thing I would add is, you absolutely can continue to use .NET framework for your _Clients_. You should really only need to update the token server itself.

**Comment by KvnSearle** [comment]
Apologies for not responding earlier.
Thanks for the feedback.
For now I am attempting to upgrade the application to .Net 6 and there fore Identity Server from IdentityServer3 to Duende.IdentityServer v6.
I
