### ISSUE TITLE
Questions about login flow

### ISSUE THREAD

**Issue by beyondnagatani** [DuendeSoftware/Support#481]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
.NET 6

**Question**
Is there a connection made to another server (such as Duende's server) outside of the ASP.NET Application during the login workflow?
or is it completed within the ASP.NET Application?

**Comment by josephdecock** [comment]
I'm not sure what you mean by this, so I'll answer two different ways.

First, there's no communication with Duende required to use Identity Server. It doesn't "phone home" or collect metrics or anything like that.

Second, the whole point of using OAuth and OpenId Connect is to move authentication and authorization into an external process. So in that sense, yes the login process does involve leaving the client application and going to an external identity provider. The purpose of identity server is to be a framework that helps you build that identity provider.

If you need more introductory material about how the protocols and authentication in asp.net works, I recommend the video series on our YouTube channel: https://youtube.com/@duendesoftware.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
