### ISSUE TITLE
Where to store license keys

### ISSUE THREAD

**Issue by IchiroDXC** [DuendeSoftware/Support#485]
The other day I received a license key from your company.
The storage location is described on the website as "Duende IdentityServer will look for a file called Duende_License.key in the same directory as your hosting application".

Is the storage location okay in the same directory as "Startup.cs"? or as the dll file(～.dll)?

**Comment by josephdecock** [comment]
After you build, the license file should be in the same directory as the dlls. Startup.cs wouldn't normally be included in what is deployed and run. I'd expect your build or publish process would result in dlls and static content, but not the original source code.

**Comment by IchiroDXC** [comment]
I appreciate your answer.
