### ISSUE TITLE
Token access Mgt -machine -to-machine communication

### ISSUE THREAD

**Issue by gmakinwa** [DuendeSoftware/Support#487]
**Which version of Duende BFF are you using?**
Duende.BFF 2.0.0 and Token access Mgt 1.0.0
**Which version of .NET are you using?**
.NET 7
**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

Please I need your help
We are using Duende identity Server for our app development using OpenId Connect standard for users authentication.

Our app uses HTTP to call a remote API (SAP ERP Api endpoints), in this case we are using client credentials (machine-to-machine) protocol. I have watched your videos https://www.youtube.com/watch?v=zr-LAYg5BCE&t=809s
But our challenge here is that our API require a user name and password to allow access to the API
like this 
Http method: POST
{
   "UserName": "",
   "Password" : "",
  "CompanyDb": ""
}
 this is quite different from the use cases in the YouTube video which require client Id and secret to be passed like this:

services.AddClientCredentialsTokenManagement()
        
        .AddClient("sapb1", client =>
        {
            client.TokenEndpoint = "";
            client.ClientId = "";
            client.ClientSecret = "ON9IwCX4NAv7C9C1IAUJv5IlSEGff2J0";
            client.Scope = "offline_access";
        });
I have spent months trying to find a solution but still not able and I’m quite new to the topic.

**Comment by leastprivilege** [comment]
Our library implements the OAuth client credentials flow. If your API does not implement this, this is the wrong library to use.

**Comment by leastprivilege** [comment]
It is using the Apache 2 license - feel free to clone and enhance in any way you see fit.

Our focus is OAuth and OpenID Connect.
