### ISSUE TITLE
Using Multiple Authentication Cookies with BFF

### ISSUE THREAD

**Issue by amthejohnson** [DuendeSoftware/Support#488]
**Which version of Duende BFF are you using?**
6.1.0

**Which version of .NET are you using?**
.net 6

**Question**
I have created a BFF project where the back-end acts as a proxy to two different remote APIs, API1 and API2. API1 does not need to be that closely guarded (but I still want it protected), where API2 holds more sensitive information. Because of these differences I want the authentication timeout for API1 to be much longer than that of API2. The simplest way to implement this would be to have two different authentication cookies, one for each API. However, this doesn't appear possible since the BFF framework always uses the default cookie scheme when authenticating.

1. Is it possible to use two different authentication cookies? If so, how do you specify which scheme to use when interacting with the login endpoint?
2. If it is not possible to use multiple authentication cookies, is there a way to mimic the behavior I want with another method? (sessions?) Could I force the user to re-login when navigating to a page, even if their current authentication cookie has not expired?

**Comment by josephdecock** [comment]
The BFF is built with the assumption of a single default cookie authentication scheme, and while you might in theory be able to replace the parts of the BFF that make that assumption, it is not at all clear to me how you would know which cookie you should be interacting with at any given time. 

An alternative architecture that you might consider is to use a single auth cookie at the bff, and implement step up.
Step up is a mechanism for your apis to be able to describe their requirements for authentication and allow that to be conveyed back to the token server to get a new token if necessary. For example, your api2 could require tokens to be much more recently issued, and if an old token is sent, it can respond in a way that indicates that a fresher token is needed. Then the bff client can see that step up is required and send a new authorization request to identity server, along with a parameter saying that step up was required. IdentityServer can see this and force the user to authenticate again before ultimately sending a new token. 

Sample code: https://docs.duendesoftware.com/identityserver/v6/samples/ui/#step-up
Latest Draft of spec: https://datatracker.ietf.org/doc/draft-ietf-oauth-step-up-authn-challenge/

**Comment by amthejohnson** [comment]
Step up sounds like it should work. I will try to implement it and get back to you with the results.

**Comment by amthejohnson** [comment]
I was able to get the timeout to work, but I'm having trouble forcing a re-login on the client side. Since I am using Blazor for my front end, I can't use the same StepUpHandler that you used in your sample code.
In the sample code, the StepUpHandler calls a challenge using the HttpContext:
```
            var httpContext = _contextAccessor.HttpContext;
            if (props.Items.Any())
            {
                await httpContext!.ChallengeAsync("oidc", props);
            }
```
But my client doesn't have access to this context, it is calling the appropriate endpoints to do what it needs (ex: `bff/login`).
What I believe I need to do is navigate to the challenge endpoint manually on an 401 Unauthorized. I tried to navigate to `bff/login`, but since my cookie is still technically authenticated during a step up, I just get re-directed back to my homepage.
What is the appropriate endpoint to call to force an authentication challenge? Do I need to create this endpoint?

**Comment by josephdecock** [comment]
Yes, the BFF does have a few different wrinkles. What you'll need to do here is:

1. In the client application, look for www-authenticate headers that indicate that step up is requested. 
2. Take the max-age and/or acr_values that you want to support from that header
3. Pass them as query parameters to /bff/login
4. In the bff, customize the OnRedirectToIdentityProvider event of the OIDC handler so that it looks for the max age and/or acr query parameters that you're passing in to the login endpoint, and append those as parameters to the challenge.
