### ISSUE TITLE
Keys location

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#49]
Dear Duende Team,

I am getting strage behavior. When I start your examples, keys directory will be crated in the root, together with key (is-signing-key...).

But when I run my example that I have implemented from the scratch, I cant see keys directory, but everything seems to look fine.

So, where is my key directory?

Best regards,
Novak

**Comment by brockallen** [comment]
> But when I run my example that I have implemented from the scratch, I cant see keys directory, but everything seems to look fine.

Possibly in the EF operational DB?

https://docs.duendesoftware.com/identityserver/v6/data/operational/

**Comment by No1e** [comment]
Thank you!
