### ISSUE TITLE
Duende IdentityServer 6.1.6 - Not able to Single Signout between implicit vs authorization_code grant type

### ISSUE THREAD

**Issue by gshukla3155** [DuendeSoftware/Support#490]
Hi Team,
Please help us on below issues-

We are not able to perform Sigle Signout between our apps - 

- Angular 13 application (implicit flow) [angular-oauth2-oidc package]
- Dot Net Framework Asp.Net MVC application (authorization_code) [Frontend Channel Logout package]

**Issue 1:**
When **sessionChecksEnabled set to true** facing continuous **session_changed** events even no session is changed. 
![image](https://user-images.githubusercontent.com/70849493/217238558-5970d2e3-93e9-4fba-ad1d-54b0100f9b5e.png)

**Issue 2**
After Logout from angular application, the MVC Frontend Channel Logout URI get Hit and but it is not logging out the application. The session remain valid
![image](https://user-images.githubusercontent.com/70849493/217239608-420944d6-ce64-4b2c-87e9-a593272c5707.png)

**Identity Server Startup.cs**
![image](https://user-images.githubusercontent.com/70849493/217247229-3cf9ae07-f05f-41ca-8fde-543a4850bae8.png)
![image](https://user-images.githubusercontent.com/70849493/217247423-690f3dbf-3433-41a3-bb56-26322eadafc9.png)

Please let me know, if anything else required from my side.

**Comment by brockallen** [comment]
> Please let me know, if anything else required from my side.

What URLs do all of these apps (including your IdentityServer) run on?

**Comment by gshukla3155** [comment]
@brockallen 
Identity Server Url - https://{sitename}/identity
Angular application - https://{sitename}/dashboard
MVC application = https://{sitename}/Dashboard/Index

**Comment by brockallen** [comment]
So those are all on the same {sitename}?

**Comment by gshukla3155** [comment]
All those are on same server and same domain like
Identity Server Url - https://secure.samedomain.com/identity
Angular application - https://app.samedomain.com/dashboard
MVC application = https://mvc.samedomain.com/Dashboard/Index

I am using localhost for development

**Comment by brockallen** [comment]
Ok, I was checking to see if it was cross-site issues with third party cookies, but given what you said that doesn't seem to be the case.

**Comment by brockallen** [comment]
>  After Logout from angular application, the MVC Frontend Channel Logout URI get Hit and but it is not logging out the application. The session remain valid

I would debug this more -- look at your browser's network traffic to see the HTTP response from this to ensure the cookie is really being removed.

**Comment by gshukla3155** [comment]
Here is the network traffic of Angular application from Login to Logout (with sessionChecksEnabled set to false)
![image](https://user-images.githubusercontent.com/70849493/217274556-6bfaced7-54ad-4886-9a4f-734b00ccd410.png)

When I made "sessionChecksEnabled" set to true, then its continuously raising "session_changed" event and do not perform any operation on Logout click.
![image](https://user-images.githubusercontent.com/70849493/217276292-c862ae44-38a1-4977-ad3c-5a15946b2d3a.png)
**Console**
![image](https://user-images.githubusercontent.com/70849493/217276618-ba280eaa-7e3d-4456-9110-0431b684c637.png)

This is my AuthConfig for Angular application [using angular-oauth2-oidc package]
![image](https://user-images.githubusercontent.com/70849493/217275276-579b2747-23fb-47c8-aa0c-5d10857c526c.png)

**Comment by brockallen** [comment]
Well, I suggested you look into the HTTP requests in the iframe from the token server to the client app whose cookie does not get cleaned up. This means looking for that front channel logout request and look at the request/response that should be clearing the cookie. Once you look into that you might have more info as to what's not working.

**Comment by gshukla3155** [comment]
@brockallen  - I looked as suggested but not able to get the issue. It would be great if you provide any working model or code base example, to set up the Single Signout for my problem. I looked at the Duende Identity Server samples but didn't get any exact solution.

**Comment by brockallen** [comment]
Our sample here shows how that works: https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/#adding-sign-out

And the grant types don't really matter. It's the mechanics of how the client maintains its session. If it's using a cookie, then the front channel logout is the way. If it's a session in-memory in the browser with a SPA then use check session. If the token server runs on a different site then the clients, then you will have problems.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by gshukla3155** [comment]
We have MVC Owin Client Manual
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/MvcCodeFlowClientManual 
I have applied FrontChannelLogout there and is working now

For Angular 13 app Implicit flow, we are still getting below issue - session_check_enabled=true
We are using angular-oauth2-oidc package  https://www.npmjs.com/package/angular-oauth2-oidc 
![image](https://user-images.githubusercontent.com/70849493/219751814-146fa82a-8822-4ae0-8bdc-35c7e484e594.png)

Do you have any Single Signout sample/working example for Angular Apps Implicit flow?

**Comment by brockallen** [comment]
> Do you have any Single Signout sample/working example for Angular Apps Implicit flow?

Our quickstart should be working: https://docs.duendesoftware.com/identityserver/v6/quickstarts/js_clients/js_without_backend/

**Comment by gshukla3155** [comment]
@brockallen - Angular app Single Signout also started working now. Thanks

Just last thing, how can we redirect to any desired url after FrontChannelLogout in Asp.Net MVC app?
Here is the code for MVC:
![image](https://user-images.githubusercontent.com/70849493/220593841-036cebe8-a26e-4df8-997c-602914c3c751.png)

**Comment by brockallen** [comment]
> Just last thing, how can we redirect to any desired url after FrontChannelLogout in Asp.Net MVC app?

That's a feature of the Microsoft OIDC handler. Set the return url on the AuthenticationProperties you pass to ChallengeAsync.

**Comment by gshukla3155** [comment]
Hi @brockallen - Thanks for your support. Appreciate it. 
Closing this issue now.
