### ISSUE TITLE
Dear friends, did IdentityServer include role-based access control functionality? how to handle access control audit? 

### ISSUE THREAD

**Issue by liang423js** [DuendeSoftware/Support#495]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
IdentityServer is a framework for building OAuth and OIDC identity providers. RBAC isn't part of what Identity Server provides, though I imagine any RBAC system would need an identity provider, such as what can be built with IdentityServer.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
