### ISSUE TITLE
Email claim removed from ProfileService in Duende.IdentityServer.AspNetIdentity

### ISSUE THREAD

**Issue by jonasroslin** [DuendeSoftware/Support#496]
**Which version of Duende IdentityServer are you using?**
v6.2.3

**Which version of .NET are you using?**
dotnet 7

**Describe the bug**
In this commit (adjust ASP.NET Identity integration to use EmailClaimType option):
https://github.com/DuendeSoftware/IdentityServer/commit/eb742bd136edf6c8250b6c4ca475801907779f4e#diff-3853c4e7acbecc2105c6c1f73e9cb4260f150c012dd5629a296c99191959875a

The email claim is removed and therefore not added to the list. Is there any reason for this? or is it just a bug?

**Comment by josephdecock** [comment]
Microsoft updated their UserClaimsPrincipalFactory to automatically populate the email claim. Our factory decorates theirs, so it no longer needs to separately handle the email claim.

Here's the asp.net source that does the email claim handling:
https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/UserClaimsPrincipalFactory.cs#L79-L86

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by jonasroslin** [comment]
@josephdecock thanks for the clarification
