### ISSUE TITLE
Breaking change in Client Id when upgrading from version 3.X to 6.2

### ISSUE THREAD

**Issue by CasperSkydt** [DuendeSoftware/Support#497]
**Which version of Duende IdentityServer are you using?**
6.2
**Which version of .NET are you using?**
Net 6
**Describe the bug**

When upgrading from version 3 to 6 of identity server, we have clients that has begun failing. 
The reason is, that Client Id was case insensitive in the old version.

Is is possible to have the same behaviour in the new version? 
We have A LOT of connecting clients, and a potential big problem, when we upgrade production?

I would assume, it is related to this issue: https://github.com/DuendeSoftware/IdentityServer/issues/450

**Comment by josephdecock** [comment]
As the linked issue discusses, client ids have been case sensitive for many years now, and any case insensitivity that used to be present was nonstandard behavior that we regard as a bug. 


I just did a very quick search of references to the ClientId property in the IdentityServer code base, and there are >500 of them. We're just using it so much, that it is really hard to say for sure that you could make IdentityServer be case insensitive and not introduce other bugs.

Probably you're going to need to update your clients to consistently pass a case sensitive client id, as per spec.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
