### ISSUE TITLE
How to get a PAT? 

### ISSUE THREAD

**Issue by astuparek** [DuendeSoftware/Support#5]
Hello,

I'm a newbie with identity server and stuggling a bit with the PAT generation and I feel like I'm missing something.
In your sample "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/PAT", how can I create a PAT for a user using their username and password?

**Comment by leastprivilege** [comment]
Do you want to create a token for the currently logged on user - or rather some admin can create tokens for arbitrary users?

**Comment by astuparek** [comment]
Hello @leastprivilege 

I'd like to give the users the possibility to access the APIs from outside. Therefore they should be able to get an access token using their username and password (for example using a post to login.example.com/login).
As the users should be able to integrate the APIs into their own scripts/systems the client credential flow falls away.

Additionally there will be UI from us where they can call the APIs too. There we will also have to know which user is contacting the APIs (because we will have dedicated databases for users).

So I guess both - logged in and abritrary users.

**Comment by astuparek** [comment]
Another thought of mine was to create a "client id and client secret" for each user's organization and then multiple users per organization to use it for the flow.. but there I see 2 points I'm not sure if it's possible or suitable

- how could we then link the client id / client secrets (so the organization) to the users
- we would have to restart identity-service everytime when there's a new organization

or am I heading into the complete wrong direction?

**Comment by leastprivilege** [comment]
The normal approach would be 

* make the user go to a web site that requires authentication (that could be on IdentityServer itself - just like the sample), 
* present them some sort of UI to select what they want to have access to
* use our internal APIs to create the PAT
* make that PAT available to the user (e.g. for copy/paste)

Exposing an API that takes username/password and returns a token is not recommended - there might be even situations (maybe not today but in the future) where this user logs in via an external provider. In that case you could not even verify the password.

**Comment by astuparek** [comment]
I know that it's not recommended, but what if the user needs to access the API automatically (so without user interaction using a web site oder browser) from a script like his own software to get data from our API to work with. For example: daily or hourly stock updates, where we provide stocks and the user should be able to call the api for stock using an access token - but without calling a web site first to get the token.
I guess the way to provide it like you said would need the user to obtain a token everytime the old one has become invalid - so the automatic process wouldn't be automatic anymore.

Isn't there a way to get this working? :/

**Comment by leastprivilege** [comment]
Now I am confused - if you need an automatic way to get a token - there's a protocol for that - it is called *OAuth* ;)

maybe you are looking for this:
https://datatracker.ietf.org/doc/html/rfc6749#section-4.3

**Comment by astuparek** [comment]
Am I wrong or would we need a client id and secret for each of the users then or one for all of them?

**Comment by michaeldimoudis** [comment]
I'm struggling to find the exact code in the sample where it creates a PAT via the internal APIs. Can you point me to the exact file in https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/PAT where that is?

**Comment by leastprivilege** [comment]
Sorry - it seems that got accidentally deleted. That's why you couldn't find it ;)

It's here now
https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/PAT/src/IdentityServer/Pages/PAT

**Comment by astuparek** [comment]
OK now it makes much more sense to me too 👍
