### ISSUE TITLE
Mvc session stay old when angular client impersonate

### ISSUE THREAD

**Issue by adamtang79** [DuendeSoftware/Support#502]
**Which version of Duende IdentityServer are you using?**
6.1

**Which version of .NET are you using?**
adonet boilerplate .net 4

**Describe the bug**
We use mvc on adonet boilerplate years ago with IdentityServer 4 and then we produce a new angular client to login and impersonate and called mvc project using API way. But some of the pages still stay at mvc and we are using direct url eg. https://mvc.mycomp.com/Print/MotorSalesAnalysis?limit=100&customerId=10000

And we have upgrade our IdentityServer4 into DuendeIdentityServer 6.1 on a different server eg. https://id.mycomp.com

Our client is https://app.mycomp.com

The issue is with impersonation.

Said I impersonate our sass client eg. motor workshop owner A using angular client (using oidc-ts github proj) and I clicked to view direct url https://mvc.mycomp.com/Print/MotorSalesAnalysis?limit=100&customerId=10000 using window.open

The new tab will have prelogin, authorize and then show me the report. Next I will close the tab. Come back to client, exit impersonation and back to Host. Finally I will impersonate our sass client eg. motor workshop owner B and I clicked to view direct url https://mvc.mycomp.com/Print/MotorSalesAnalysis?limit=100&customerId=100012 (this time, a new tab will open but no prelogin and authorize) but this time, the sales is showing for customerId 100000 instead of current impersonated customerId 100012.

How do I make my mvc sync with my angular client current tenant impersonation? This is the same for our motor workshop owner. Some owner has more than 1 workshops eg. in 2 accounts but their staff login into 2 accounts and working simultaneously. I've tested that login (no impersonation) into acc 101, view the sales report, logout, login again into acc 125, view the sales report but the sales report is showing for acc 101 instead of acc 125.

The workaround now is to close all the same kind of browser in that pc to make the sessions goes away and then login into acc 125 to see the sales report (with completely new set of prelogin and authorize redirection) but we are losing customers.

Mvc pages (direct url) did not have same tenantId with angular spa client (impersonate).

**To Reproduce**

1. browse angular spa client
2. login into host
3. impersonate tenant A
4. click direct url to view page from mvc project
5. exit impersonation
6. impersonate tenant B
7. click direct url to view page from mvc project
8. the page is showing data from tenant A instead of tenant B

**Expected behavior**

>> 8. the page should show data from tenant B

**Log output/exception with stacktrace**

none.

**Additional context**

none.

**Comment by brockallen** [comment]
> The issue is with impersonation.

Impersonation is not a built-in feature to IdentityServer, so it woulds like you or someone else had added that as a custom feature. I can't speak to how that was done, so it might exhibit the behavior you describe above.

If you want your impersonation feature to do what you describe above, you'd need to design it to properly coordinate with all the clients, but that's up to you do design and implement it, and that's beyond what our support can assist with.  If you need help with that, then we do offer professional services. Feel free to [contact us](https://duendesoftware.com/contact) if you are interested.
