### ISSUE TITLE
How to access `IdentityResource`, `ApiScope`, and `Client` from persistence storage?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#503]
**Which version of Duende IdentityServer are you using?**
I see these tables in my SQL database. How to access them? What's the schema of the entity models?

**Which version of .NET are you using?**
Community
**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by 4865783a5d** [comment]
Check the documentation about stores: https://docs.duendesoftware.com/identityserver/v6/reference/stores/

Resource Store: https://docs.duendesoftware.com/identityserver/v6/reference/stores/resource_store/
Client Store: https://docs.duendesoftware.com/identityserver/v6/reference/stores/client_store/

These services have a cache / ef core implementation where you can retrieve them. 

As for the models: https://docs.duendesoftware.com/identityserver/v6/reference/models/

**Comment by khteh** [comment]
Are these constructor injectable through DI?
I assume `IClientStore.FindClientByIdAsync` returns https://docs.duendesoftware.com/identityserver/v6/reference/models/client/ However, I don't see the entity model definition of `Client` in the page?

**Comment by brockallen** [comment]
All of the config stores are designed to be read only. If you wish to do updates to those DB tables, then you can inject the DbContext for them and manipulate them directly. And you could do this from whichever app you need to (which might not be the IdentityServer host).

**Comment by khteh** [comment]
How would I know what properties the models have for reading without the model definition?

**Comment by brockallen** [comment]
We document those: https://docs.duendesoftware.com/identityserver/v6/reference/models/ and they are a direct mapping to the EF entities. There are also helper methods to map back and forth.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
