### ISSUE TITLE
How to retrieve the configured `RedirectUris` for redirection after login/out?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#504]
**Which version of Duende BFF are you using?**
How / where do I get the configured `RedirectUris` in order to return to the client application after login / out? I am using SQL.

I see `public async Task<IActionResult> OnGet(string returnUrl)` in https://github.com/DuendeSoftware/BFF/blob/main/samples/IdentityServer/Pages/Account/Login/Index.cshtml.cs Does the client need to send a request with `?returnUrl=http://localhost:3000` for that to work?

**Which version of .NET are you using?**
Community
**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
We document the design of the login workflow here: https://docs.duendesoftware.com/identityserver/v6/ui/login/redirect/

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by khteh** [comment]
I see this code sample of yours on a Razor page:
```
    public async Task<IActionResult> OnGet(string returnUrl)
    {
        await BuildModelAsync(returnUrl);
```
How does the client pass the `returnUrl` as query string to the server? How does this relate to `Client.RedirectUris` configuration?

**Comment by brockallen** [comment]
> How does the client pass the returnUrl as query string to the server?

It doesn't. It makes requests to the OIDC authorize endpoint with the redirect_uri. IdentityServer takes all of this as the returnUrl and passes that over to the login page. The login page uses the interaction service to ask IdentityServer to decode and validate it so the login page can use it. Once the login page is done, it uses the returnUrl to return back into the IdentityServer endpoint so it can complete the workflow. 

I think we try to describe this in our docs here:

https://docs.duendesoftware.com/identityserver/v6/fundamentals/users/#authorization-endpoint-and-login-page-workflow

Is there something lacking in the docs that could have made it easier to understand?
