### ISSUE TITLE
Resource Isolation and OIDC Scopes

### ISSUE THREAD

**Issue by 4865783a5d** [DuendeSoftware/Support#506]
**Which version of Duende IdentityServer are you using?**
6.1.7
**Which version of .NET are you using?**
.net6.0
**Describe the bug**

All our API's require resource isolation, enforced on the ApiResource definition. When a user requests a token per authorize code flow (Eg.: openid email profile offline_access api_scope1 api_scope2), we noticed that `ResourceValidationResult.FilterByResourceIndicator` removes OIDC scopes from the `ParsedScopes` property. They remain in the `Resources.IdentityResources` as expected. Since we require the access token to contain the requested OIDC scopes in the `scope` claim when retrieving the respective identity claims through the `userInfo` endpoint, we currently have to re-add them at some point after the filtering happens. 

Is there a way to keep OIDC scopes in the ParsedScope list to match the corresponding `Resources.IdentityResources` entry, similar to offline_access?

```csharp
 if (Resources.OfflineAccess)
            {
                parsedScopesToKeepList.Add(new ParsedScopeValue(IdentityServerConstants.StandardScopes.OfflineAccess));
            }
```

Thanks for any suggestions.

**Comment by brockallen** [comment]
The userinfo endpoint is not designed for APIs

https://brockallen.com/2017/11/07/the-userinfo-endpoint-is-not-designed-for-apis/

**Comment by 4865783a5d** [comment]
Thanks for your reply and pointing us in the right direction.  Now that I've re-read the post, it makes total sense.
