### ISSUE TITLE
LicenseKey Update

### ISSUE THREAD

**Issue by IchiroDXC** [DuendeSoftware/Support#510]
**Which version of Duende IdentityServer are you using?**
6.1.7
**Which version of .NET are you using?**
Yes
**Describe the bug**

I want to teach me about "LicenseKey".
My client got a LicenseKey the other day.
My client will renew it next year,
Will the value be different from the current key?

**Comment by brockallen** [comment]
Docs on the license key are here: https://docs.duendesoftware.com/identityserver/v6/fundamentals/license_key/

And each term the customer will receive a new license key and the software should get updated at the soonest convenient time.

**Comment by IchiroDXC** [comment]
I understood that the license key would be a different key every year.

**Comment by brockallen** [comment]
> I understood that the license key would be a different key every year.

Yes, that is what I mean by "each term" above.

**Comment by IchiroDXC** [comment]
Thank you for your reply.
