### ISSUE TITLE
CryptographicException spam when automatic key management with key protection is on

### ISSUE THREAD

**Issue by volo-t** [DuendeSoftware/Support#512]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
6

**Describe the bug**
When automatic key management with key protection is turn on it starts throwing CryptographicException for each key in operational DB apart for the most recent one trying to unprotect a key. Manual key management with key protection and automatic key management with no key protection work fine.

**To Reproduce**
1. Add data protection with all default settings: services.AddDataProtection();
2. Add identity server with all default settings and automatic key management enabled by default;
3. Add operation store as recommended: https://docs.duendesoftware.com/identityserver/v6/data/ef/#operational-store
4. Deploy and run the server

**Expected behavior**
Automatic key management with no CryptographicException is expected

**Log output/exception with stacktrace**
|ERROR|Duende.IdentityServer.Services.KeyManagement.KeyManager|Duende.IdentityServer.Services.KeyManagement.KeyManager.GetAllKeysFromStoreAsync|||Error unprotecting key with kid 2DDF99844950C1CEAFD72EF1299BED3A.
*** CryptographicException The key {7b8c5471-fd9d-4ab0-a8c6-9b0731842bfa} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetAllKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435

**Additional context**
It reads all the keys from operational DB, trying to unprotect them and throws CryptographicException for each key. Then it creates a new key and puts it into DB. After server restart situation repeats with n+1 exception.
I was trying different settings for both IdentityServer and DataProtection (including storing keys to the file system) but result was the same.
Please let me know what exactly IdentytyServer/Dataprotection settings should be added to get rid of CryptographicException spam.

**Comment by brockallen** [comment]
> CryptographicException The key {7b8c5471-fd9d-4ab0-a8c6-9b0731842bfa} was not found in the key ring. 

This means that the record in the keys table (from automatic key management) was protected with a data protection key that the current host does not have access to. So either the data was carried over from a different environment (from different data protection keys), or different servers are not synching their data protection keys.

This should get sorted out, and once you have then you can delete any of those old records in the keys table that are failing.

https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by Krangth** [comment]
I was about to post this same issue. I'm running the server in IIS. Every time IIS restarts the site (and then a request is made), all existing keys create an exception message, and a new key is created. There are no other environments or servers. I only just started trying duende identity server around three weeks ago and I already have twelve thousand of these errors in the logs. If I truncate the [Keys] table, it just fills up with keys that produce exceptions.

**Comment by volo-t** [comment]
> This means that the record in the keys table (from automatic key management) was protected with a data protection key that the current host does not have access to. So either the data was carried over from a different environment (from different data protection keys), or different servers are not synching their data protection keys.
All is happening in my local environment so it's not about synchronization and no data form a different environment was carried over. I also deleted previously generated keys from Keys table but new keys keep generating exceptions.

**Comment by brockallen** [comment]
> Every time IIS restarts the site (and then a request is made), all existing keys create an exception message, and a new key is created. 

I'd suggest setting a consistent ApplicationName when you configure your data protection keys. Beyond that idea, this then start to sounds like a question/issue for Microsoft since it woul[d affect your user's login cookies as well (not just things from IdentityServer).

**Comment by Krangth** [comment]
>  I'd suggest setting a consistent ApplicationName when you configure your data protection keys
Where would one even set that and why would it be changing?
I went through the quick start section of the documentation. I haven't done any data protection key configuration. This is a strange default experience.

**Comment by brockallen** [comment]
> This is a strange default experience.

That's a pretty fundamental feature of ASP.NET Core, and we're using it because it's part of the platform. We do document that this is needed (as linked above). I wish Microsoft did a better job of raising awareness of it.

Here are their docs on it:

https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0

**Comment by josephdecock** [comment]
Also, IIS configuration for data protection is further documented here: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced#data-protection

It sounds like IIS IS not be persisting your data protection keys, and you need one of the approaches in that article: either add Data Protection registry keys or configure the app pool to load a user profile.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by volo-t** [comment]
Yes. Thank you for responses.
