### ISSUE TITLE
Consent Not Redirected

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#513]
Duende.IdentityServer 6.2.3
net6.0

Our one and only client is setup to require [consent](https://docs.duendesoftware.com/identityserver/v6/ui/consent/):

RequireConsent = true,
AllowRememberConsent = false

We are using the default path to the consent page (using the consent template).

The user logs in (username and password are validated) but is never redirected to the consent page.

Thanks in advance for your help,
Bill

**Comment by billcunnien** [comment]
If I comment out our custom interaction generator:

//.AddAuthorizeInteractionResponseGenerator<CustomAuthorizeInteractionResponseGenerator>();

... then the consent works. I must have something going wrong within the custom generator.  I will troubleshoot that piece.

My understanding is that the user interaction will be login, then custom interactions (one or more than one), then consent - is that correct?

**Comment by brockallen** [comment]
Make sure your custom authorize interaction response generator is deriving from our default one and calling the base class first.

**Comment by billcunnien** [comment]
I have confirmed that the custom interactions occur after login validation and before the consent. There was an error I made within the custom authorize interaction response generator, but once I cleared that up, the flow is working as expected. Thanks for your help and patience!
