### ISSUE TITLE
Select claim value at login

### ISSUE THREAD

**Issue by btwyford** [DuendeSoftware/Support#514]
Hi,

I have a scenario where I want a user to select a specific value for a claim at login time, this value would then be used for the life of the authorisation. The user may choose to log into the same url twice at the same time using 2 browser (concurrent sessions) and use different values for the same claim. A simple example would be: a required claim is called SiteColour, for session 1 the user chooses "Blue", and for session 2 they choose "Red". I'm sure this should be possible (maybe using grants) but I cannot work it out! any help would be greatly appreciated. Regards, Barnaby

**Comment by brockallen** [comment]
> I have a scenario where I want a user to select a specific value for a claim at login time, this value would then be used for the life of the authorisation.

This would commonly be done by adding a claim to the user session on the login page as one of the claims you pass when you call SignInAsync.

**Comment by btwyford** [comment]
Thanks for that, but I cannot see how to integrate that logic with my ASPNet Identity model, this is the code that I use to login:

var result = await _signInManager.PasswordSignInAsync(user, password, false, lockoutOnFailure: true);

would I use the await HttpContext.SignInAsync(user); as well as this?

Any help or guidance would be awesome!

**Comment by brockallen** [comment]
Something like this: https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Core/src/SignInManager.cs#L216

**Comment by btwyford** [comment]
That is perfect and so easy! thanks :)
