### ISSUE TITLE
Migrating to ServerSideSessions

### ISSUE THREAD

**Issue by Rainnwind** [DuendeSoftware/Support#515]
**Which version of Duende IdentityServer are you using?**
5.2.4, upgrading to 6.2.1

**Which version of .NET are you using?**
.NET Core 3.1, upgrading to .NET 6

**Describe the bug**

I am trying to migrate from Duende.IdentityServer 5.2.4 to 6.2.1 to achieve ServerSideSessions.
The question I have is: How do we actually do it?
We want to take full use of the ServerSideSession features but we also want to ensure that members that are already signed in to our services stay signed in.

Is there any way to migrate our existing PersistentGrants into ServerSideSessions and how?

**Comment by brockallen** [comment]
> We want to take full use of the ServerSideSession features but we also want to ensure that members that are already signed in to our services stay signed in.

Unfortunately that's not something Microsoft's ASP.NET Cookie handler code supports. If you `wanted that, you'd need to code something custom to honor the existing session. This would lily involve adding a new cookie handler for the new server side sessions, and then custom code to detect the old session and create the new one.

**Comment by Rainnwind** [comment]
We had hoped for a more automatic/simple transition transition.
We have enough to make our decision on how to move forward.

Thank you Brock for your fast reply!

**Comment by sevansoft** [comment]
@Rainnwind I know this issue is closed, but what direction did you take? 

I'm about to embark on to preserve logins?
