### ISSUE TITLE
Unable to remove amr claim from access token 

### ISSUE THREAD

**Issue by kkdeveloper7** [DuendeSoftware/Support#517]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
dotnet6

**Describe the bug**
When using custom profile to generate custom claims on access and id token, unable to remove `amr` claims from access token.

**To Reproduce**
Invoke token end point for refresh or first time tokens. 

**Expected behavior**

When creating principal with out authentication method, `amr` claim still been present on refresh token 

```
 var claimsPrincipal = new IdentityServerUser(user.UniqueIdentifier)
            {
                DisplayName = user.EmailAddress,
                AdditionalClaims = new[] { ipClaim, userDataClaim, securityAccountNameClaim, defaultRedirect },
                AuthenticationMethods = new List<string>() <==== set authentication method to nothing 
            }.CreatePrincipal();
```

**Additional context**

I am trying to remove `amr` claim from our access token. When user is authenticated the `amr` claims is always present on the subject and been added to access token.

**Comment by brockallen** [comment]
You'd have to derive from our `DefaultTokenCreationService` and override `CreatePayloadAsync` (or `CreateTokenAsync`) and remove the `amr` claim from the inbound `Token` before calling the base implementation.

**Comment by brockallen** [comment]
That is an extensibility point, but it uncommon enough that it doesn't look like it's in our docs. Here's the default implementation that I suggested you derive from:

https://github.com/DuendeSoftware/IdentityServer/blob/19a3e69917b778f542673b056b1040f52f68a8db/src/IdentityServer/Services/Default/DefaultTokenCreationService.cs

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
