### ISSUE TITLE
BFF ServerSideSessions using Redis

### ISSUE THREAD

**Issue by gilm0079** [DuendeSoftware/Support#52]
currently on version 1.2.1

currently on .NET 6 (6.0.202)

Does a Redis implementation of BFF ServerSideSessions exist or would I need to write one based on the extensibility? I don't see a published NuGet package for this at this moment.
[https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/sessions/#user-session-store](https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/sessions/#user-session-store)

Just checking before I dive into writing my own IUserSessionStore

**Comment by brockallen** [comment]
There was a similar one started here: https://github.com/DuendeSoftware/BFF/pull/31

But given the limitations of key/value semantics, there are some tricky book keeping semantics that are needed, and they never fully got sorted out.
