### ISSUE TITLE
BFF sign-in based on custom grant_type in IdentityServer

### ISSUE THREAD

**Issue by eugene-rebedailo** [DuendeSoftware/Support#520]
**Which version of Duende BFF are you using?**
BFF: v2.0.0
IdentityServer: v6.2.3

**Which version of .NET are you using?**
.net7.0

**Describe the question**
We are trying to implement a custom auth solution revolving around giving users temporary access through magic links.

The envisioned flow is as follows:
1) A user with a certain level of access (signed in using normal authorization_code flow) is issuing a special link via an API call to the identity server
2) A record is created in the IdentityServer's database containing access code, the user that issued that access and some expiration information
3) An anonymous user follows the link pointing at the BFF with the access code.
4) The BFF redeems the access code in the IdentityServer and receives a short-lived access token to have limited access the BFF app and downstream APIs on behalf of the issuing user.
5) The token is stored in the server-side session and BFF signs the user in via a cookie to access the BFF.
6) After a certain period of time, BFF session expires and is cleaned up.
5) Then after more time passes, the access code expires, making it impossible to issue new access_tokens.

Issuing an access token within IdentityServer could be achieved by using a custom grant type (in our scenario, called "magic_link"), but it is not completely clear as to how we could possibly leverage automatic token management functionality in the BFF. 

Currently the solution revolves around using a manual call to "sign-in" with additional auth properties, but this solution seems unintended, as we had to scour through the source code of the BFF to devise it:
```csharp
  var token = "..."; //Get token through calling /connect/token with grant_type=magic_link

  // TODO: Remove manual token validation?
  var principal = await ValidateTokenAndBuildPrincipal(token);
  var authProperties = new AuthenticationProperties
  {
      RedirectUri = "/done",
      // TODO: Replace with automatic token management?
      // this seems way too hacky and requires knowledge of the BFF internals.
      Items =
      {
          [".Token.access_token"] = token,
          [".Token.token_type"] = "Bearer",
          [".TokenNames" ] = "access_token"
      }
  };

  await _httpContextAccessor.HttpContext!.SignInAsync("cookie", principal, authProperties);
```

What would be the best way to achieve the same result but
1) Avoiding manual token validation
2) Avoiding having to manually populate the AuthenticationProperties when signing-in.

**Comment by brockallen** [comment]
> Issuing an access token within IdentityServer could be achieved by using a custom grant type (in our scenario, called "magic_link"), but it is not completely clear as to how we could possibly leverage automatic token management functionality in the BFF.

Our BFF framework assumes the session has been established via the via the OIDC handler, but you are doing it manually. It's not designed to support other scenarios, but it's possible that if the session you establish looked the same as if the OIDC handler had done it (including all the tokens in the Properties) of the AuthenticationTicket, then you'd still get the benefit of the remote proxy forwarding access tokens, and automatic token renewal with the refresh token. I'd not expect that you'd not get the benefit of the other session management features (like logout, backchannel notification, etc).

**Comment by brockallen** [comment]
I'm not following. Can you elaborate?

**Comment by brockallen** [comment]
A custom grant is a programmatic call to the token server, so you'd not be using the Microsoft OIDC handler at all. I guess you could somehow accept the macig link param in your BFF and send that to the token server as a custom acr_value and use that to establish the session via the OIDC handler, but that's entirely on your own and not something we can advise you on in this support forum.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
