### ISSUE TITLE
Conceptual question: is there a possible way to generate a short-lived link in the backend API that can be opened and authenticate a user on the Web?

### ISSUE THREAD

**Issue by luboid** [DuendeSoftware/Support#522]
We have 3 applications 

1. Web app 
2. Web portal
3. Mobile app (native Android, iOS) 

We are using Identity Server for SSO. The Web app and portal are integrated with Identity Server, but the Mobile app is using a custom schema for authentication and it seems a big task to refactor the mobile to include it in SSO. We have a task to present the clients with different offers on mobile and when they click on them be redirected to the web portal and automatically authenticated, and they see the necessary forms for interactions. 
Is there a possible way to generate a short-lived link in the backend with that client to be authenticated and transferred where they need to be, or something similar?

Thank you in advance.

Some links about the idea:

https://www.scottbrady91.com/aspnet-identity/implementing-mediums-passwordless-authentication-using-aspnet-core-identity
https://andrewlock.net/creating-custom-password-validators-for-asp-net-core-identity-2/

**Comment by josephdecock** [comment]
There isn't an OAuth or OIDC standardized flow nor a built in IdentityServer feature that can directly fulfill your requirements. You can make something work with custom code, but you should be cautious.

The problem with a custom solution is that you don't get the security benefit of using a standardized flow. In a standardized flow, the threat model is extremely well understood and has been vetted by a huge number of people. The same isn't true of a solution you find on a blog (even a blog from someone smart like Scott Brady). One thing that comes to mind is that standardized flows that involve authentication across devices (CIBA and the OAuth device flow) have some very particular attack vectors that [need to be defended against](https://www.ietf.org/archive/id/draft-kasselman-cross-device-security-03.html). My intuition is that similar threats could exist for your custom solution, but of course the specifics will depend on what you actually build.

Depending on your security requirements, risk tolerance, and your own threat modeling, you'll have to decide if you want to implement something custom. If you do, you'll probably need to extend your IdentityServer with custom code that can start a session by calling SignInAsync, and then redirect to the appropriate client. The client can then perform an OIDC handshake and the user will end up logged in, the same as in a single sign on flow.

**Comment by luboid** [comment]
Thank you.
