### ISSUE TITLE
How to return user details to the client?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#526]
**Which version of Duende BFF are you using?**
Community
**Which version of .NET are you using?**
7.0.102
**Describe the bug**
```
    public static IEnumerable<IdentityResource> IdentityResources =>
        new IdentityResource[]
        {
            new IdentityResources.OpenId(),
            new IdentityResources.Profile(),
            new IdentityResources.Email(),
        };
        AllowedScopes = {
            IdentityServerConstants.StandardScopes.Email,
            IdentityServerConstants.StandardScopes.OpenId,
            IdentityServerConstants.StandardScopes.Profile,
        }
```
This is seen at the client console after successful login:
```
session: {
  user: { name: undefined, email: undefined, image: null },
  expires: '2023-03-22T06:31:34.657Z'
}
user: undefined
token: {
  picture: null,
  sub: 'GUID,
  userRole: 'admin',
  iat: 1676874694,
  exp: 1679466694,
  jti: 'GUID'
}
```

How to return the user details to the client?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
To get identity resources, you typically make a request to the userinfo endpoint. The ASP.NET OIDC auth handler will do this for you if you set its [GetClaimsFromUserInfoEndpoint](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectoptions.getclaimsfromuserinfoendpoint?view=aspnetcore-7.0#microsoft-aspnetcore-authentication-openidconnect-openidconnectoptions-getclaimsfromuserinfoendpoint) flag.

**Comment by khteh** [comment]
This is configured and used in ASP.Net Core web client app with `AddOpenIdConnect`. How to obtain the same info using your library and other clients like next-auth?

**Comment by khteh** [comment]
What's the userinfo endpoint?

**Comment by brockallen** [comment]
> What's the userinfo endpoint?

This is a part of the OpenID Connect specification, which is what the IdentityServer framework implements. To best understand IdentityServer (and how your client apps would use it), we'd strongly encourage you to learn as much as you can about OpenID Connect by reviewing the specification here: https://openid.net/specs/openid-connect-core-1_0.html. I really think it will help you understand all of these workflows you're using.

**Comment by khteh** [comment]
I use `.well-known/openid-configuration` and get the following:
```
profile: {
  "iss": "https://iam.kyberlife.io",
  "nbf": 1677030395,
  "iat": 1677030395,
  "exp": 1677033995,
  "aud": "buyerportal",
  "amr": [
    "pwd"
  ],
  "at_hash": "s5PoQoc5ZTzuicvrjFHkGQ",
  "sid": "7ECC95EB4BBAC4B9BFC5C3F979F7771A",
  "sub": "<Guid of the user>",
  "auth_time": 1677030394,
  "idp": "local"
}
```
but the rest of the information is missing according to the URL you shared:
```
{
   "sub": "248289761001",
   "name": "Jane Doe",
   "given_name": "Jane",
   "family_name": "Doe",
   "preferred_username": "j.doe",
   "email": "janedoe@example.com",
   "picture": "http://example.com/janedoe/me.jpg"
  }
```
??

**Comment by brockallen** [comment]
The claims you get in the different tokens depend on the scopes you request, and how you configure/define those scopes in IdentityServer. I refer you to our docs: https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/

**Comment by khteh** [comment]
What does this default initialization list provide and how to extend it?
```
    public static IEnumerable<IdentityResource> IdentityResources =>
        new IdentityResource[]
        {
            new IdentityResources.OpenId(),
            new IdentityResources.Profile(),
            new IdentityResources.Email(),
        };
```

**Comment by khteh** [comment]
Are the `public ICollection<string> UserClaims { get; set; }` case-sensitive?

**Comment by khteh** [comment]
I have these in the scopes `"scope": "openid email profile buyerportal"` but I wonder why `email` is missing.

**Comment by josephdecock** [comment]
> What does this default initialization list provide and how to extend it?

An identity resource is a named group of claims about a user that can be requested using the scope parameter.

The OpenID Connect specification [suggests](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) a couple of standard scope name to claim type mappings that might be useful to you for inspiration, but you can freely design them yourself, by creating instances of the IdentityResource class. See more details in our documentation [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/identity/).

> Are the public ICollection<string> UserClaims { get; set; } case-sensitive?

Yes

> email is missing.

Where are you expecting to see it? User claims are typically not included in the id token, but rather returned from the userinfo endpoint.

**Comment by khteh** [comment]
How / where does `public ICollection<string> UserClaims { get; set; }` get the values from? How does the identity server return these values at `.well-known/openid-configuration` request? How would I know which is the right one to use between:
```
UserClaims = new[] { "UserName", "Email" }
```
and 
```
UserClaims = new[] { "user_name", "email" }
```
?

How can I return misc other properties from the users database table? For example, I would like to return the following properties from the authenticated user:
```
            new ApiScope(name: "sellerportal", displayName: "Seller Identity") {
                UserClaims = new [] { "Title", "Email", "Country", "Type", "AccountName", "AccountNumber", "AccountType", "BusinessNumber", "CommissionType", "WebSite", "TotalProductSales", "TotalProductSalesAmount"}
            },
```

> User claims are typically not included in the id token, but rather returned from the userinfo endpoint.
Yes, but I don't see any of them being returned from `.well-known/openid-configuration` request?

**Comment by brockallen** [comment]
@khteh --

The OpenID Connect spec covers how the protocol endpoints work. I'd suggest reading it, as that will help clarify some of the confusion and help you understand better.

https://openid.net/specs/openid-connect-core-1_0.html

And once you have read that, then our docs on how we enable those protocol mechanics to returns claims to the client app and API:

https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/

**Comment by brockallen** [comment]
Oh also, I forgot we have several learning resources here including videos: https://docs.duendesoftware.com/identityserver/v6/overview/resources/

**Comment by khteh** [comment]
How to register `IProfileService` with the `userinfo` endpoint?

**Comment by khteh** [comment]
Oh also, I forgot to ask where is the path of your identity server `userinfo` endpoint? Is it at `/connect/userinfo`?

**Comment by josephdecock** [comment]
> How to register `IProfileService` with the `userinfo` endpoint?

You don't register it specifically with a particular endpoint, you register it with the DI system.

Our [Quick Start tutorials](https://docs.duendesoftware.com/identityserver/v6/quickstarts/) in the docs show examples of this. I recommend you do the QuickStarts in order, but in part 4 there is an example specifically of the profile service.

**Comment by josephdecock** [comment]
> Oh also, I forgot to ask where is the path of your identity server `userinfo` endpoint? Is it at `/connect/userinfo`?

Yes, `/connect/userinfo` is the userinfo endpoint. Normally the paths to the individual endpoints are not things you need to think about though, because the discovery metadata includes all those paths. Most mature OIDC programming tools will retrieve the disco information for you.

**Comment by khteh** [comment]
Postman GET request to the endpoint `/connect/userinfo?scope="openid email address phone profile buyerportal"` returns only the `sub`:
```
{
    "sub": "<GUID>"
}
```
What do I miss in the server config?

**Comment by josephdecock** [comment]
Scopes should be part of the token, not a separate query parameter to the user info endpoint. 

Add the scopes to the initial authorize request so that you obtain  a token with the score y

You can manually verify that the token has the desired scopes by pasting it into jwt.ms.

**Comment by khteh** [comment]
It works now. Thanks!
