### ISSUE TITLE
Must a CORS origin always be associated with a client, or could there be a method of having "standalone" origins in the future?

### ISSUE THREAD

**Issue by Pilchard123** [DuendeSoftware/Support#527]
**Which version of Duende IdentityServer are you using?**

6.1.3, though the changelogs up to the latest version at the time of writing (6.2.3) don't seem to say anything about this has changed.

**Which version of .NET are you using?**

6, though the question is relevant for 7+ as well

**Describe the bug**

It's not really a bug, per se, more a question/suggestion.

Currently every CORS origin *must* be associated with a client, but there are cases where that might not be necessary. If I have an API using IS for auth and an OpenAPI UI describing it, I may not be able to authenticate before exploring the API because the authorize dialog ([this one](https://user-images.githubusercontent.com/11312118/220121311-b5cd6c8a-7ca2-42ac-93f0-aa9707b75e5d.png), where you enter client details before possibly being sent off to auth as a user) is blank, because it cannot fetch the openid-configuration document if the OpenAPI UI address is not in the list of allowed CORS origins. At this point, the client details haven't been entered, so there's not a lot of meaning to the origin being associated with a client.

I could make a dummy client and use that to hold the origin, but it seems odd to be making a client that will probably never be used just so I can have a UI fetch the openid-configuration document, and risks someone deleting it (it's never used, after all) and breaking the UI. For users with a client-limited license, it also takes up a client slot that they could be using for something else.

I could attach the origin to a client which *is* being used, but then there's an unrelated origin attached to it. There is a risk that someone might see the unrelated origin and "tidy" it - which again breaks the UI. Or the client which it is attached to might be retired and deleted (and then the UI breaks).

Is there any reason why a CORS origin *must* be associated with a client, or would it be feasible in the future to allow origins to be a first-class object with an optional link to a client so in cases where that link is meaningful it can still be maintained?

**Comment by josephdecock** [comment]
If you want to customize the logic for how origins are allowed, you can implement the ICorsPolicyService instead of using associating origins with clients.

**Comment by Pilchard123** [comment]
That would work, but wouldn't that entirely replace the standard method? I suppose it wouldn't be that difficult to get the client-linked origins as well, but it seems like using a sledgehammer to crack a nut.

TBH, this isn't a deal-breaker for me, it's just a minor irritation that I ran into and thought I'd put in writing to see what other people thought.

**Comment by brockallen** [comment]
> Is there any reason why a CORS origin must be associated with a client

This is also just our default implementation in our framework. As Joe linked above, you can always implement the CORS policy service yourself to change that behavior. 

Also, you only need CORS for clients that are making Ajax calls from the browser to IdentityServer. This is only needed for SPAs, generally. And the current recommendation for SPAs is to not do the OIDC protocol from JavaScript in the browser, but instead use the BFF pattern: https://blog.duendesoftware.com/posts/20210326_bff/

**Comment by josephdecock** [comment]
> wouldn't that entirely replace the standard method?

It wouldn't have to - your implementation could derive from the default implementation, and call its base method.

**Comment by Pilchard123** [comment]
> you only need CORS for clients that are making Ajax calls from the browser to IdentityServer

Sure, but in this case the offending code isn't under my control (at least I don't think it is). It's the default UI created by [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) (or possibly [swagger-ui](https://github.com/swagger-api/swagger-ui), I haven't chased it down that far yet) that fetches /.well-known/openid-configuration with an AJAX request to get the various endpoint addresses &c. , but fails because of the missing origin.

> your implementation could derive from the default implementation

*sigh* Of course. I don't know why I didn't think of that. I blame having just got back from a week's holiday?

**Comment by Pilchard123** [comment]
Yeah, sure. Thanks! :)
