### ISSUE TITLE
Users sign out automatically 

### ISSUE THREAD

**Issue by navid60** [DuendeSoftware/Support#529]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
6.0
**Describe the bug**
Recently we have started using Duende as our Identity server, we expected to keep our users logged in for 1 month but our users automatically sign out almost every 1 hour!
we implemented our identity server with Duende documentation, we configured it to generate a refresh token (offline access scope) in order to get an access token,
and also we have set up a specific SQL Server Database to persist account data.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

we excepted to keep users logged in for one month

**Additional context**
our infrastructure is based on k8s

**Comment by delavarkhan-shayan** [comment]
Hello guys,
we have the same problem related to this question. But we are using Nuxt.js as our frontend framework. I would be grateful if you tell me some suggestions related to this special case.
@josephdecock

**Comment by brockallen** [comment]
>  Recently we have started using Duende as our Identity server, we expected to keep our users logged in for 1 month but our users automatically sign out almost every 1 hour!

Is this in the client or in your IdentityServer?

**Comment by josephdecock** [comment]
> Hello guys,
> 
> we have the same problem related to this question. But we are using Nuxt.js as our frontend framework. I would be grateful if you tell me some suggestions related to this special case.
> 
> @josephdecock 

Sorry, I'm not familiar with nuxt.js. The protocols that identity server implements are all standardized, so if you have a spec compliant client implementation, the protocol interactions work with a wide variety of clients. Session management after authentication is platform specific though.

In general, our advice is to avoid software architecture where tokens are accessible from JavaScript. We encourage you to consider a back end for frontend approach instead (and take a look at our [BFF tools](https://docs.duendesoftware.com/identityserver/v6/bff/).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
