### ISSUE TITLE
Class Duende.IdentityServer.Models.IdentityProvider doesn't have a contructor without parameters causing Json deserialization issue when caching

### ISSUE THREAD

**Issue by pitetb** [DuendeSoftware/Support#530]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
Net core 6

**Describe the bug**
I'am using a custom implementation of the Duende.IdentityServer.Services.ICache<T>. My custom implementation is serializing in Json using System.Text.Json (nothing special here).
But when the method "public async Task<IdentityProvider> GetBySchemeAsync(string scheme)" in "CachingIdentityProviderStore" is called, if the data is present in my custom cache, I get a "No parameterless constructor defined" exception when deserializing the IdentityProvider class from the cache.

**To Reproduce**
- Setup a json based cache
- Setup data in external provider
- Call twice "public async Task<IdentityProvider> GetBySchemeAsync(string scheme)". Once to put the result in the cache, once to read it.

**Expected behavior**

Just had a constructor without parameters on the class Duende.IdentityServer.Models.IdentityProvider.

**Additional context**

I was able to bypass the issue using a custom deserialization class  'JsonConverter<IdentityProvider>' but I think adding the constructor on the class should be easier.

**Comment by brockallen** [comment]
IdentityProvider is a base class. You are expected to know which derived class to instantiate (e.g. OidcProvider).

**Comment by pitetb** [comment]
Hello, and thank you for your answer.

I saw it's a base class but in CachingIdentityProviderStore, the "_cache" instance injected is my custom implementation of "ICache<IdentityProvider>", let's say 'MyCacheImplementation<IdentityProvider>'.

This generic cache implementation doesn't known the type "OidcProvider" because it's a 'MyCacheImplementation<IdentityProvider>' and not a 'MyCacheImplementation<OidcProvider>'.

Maybe more a C# problem than a Duende one, but missing default constructor doesn't make it easy...

**Comment by brockallen** [comment]
Yea, I understand. But there is downcasting involved in the implementation, so it's just how it works. I'll close for now, since I think you know what's needed.
