### ISSUE TITLE
IDX20803 - Unable to obtain configuration from 'System.String'

### ISSUE THREAD

**Issue by apetrut** [DuendeSoftware/Support#532]
Hi, I am using Duende v6.0.2 with .NET 6 (the skoruba version) inside K8S cluster hosted in Azure and I am getting the error below:

![image](https://user-images.githubusercontent.com/13006228/220628982-424d0921-225c-4ce4-9b15-d86abf794ee3.png)

On my local machine everything works fine and I have all the configurations setup with docker compose and self-signed certificates created with mkcert.

I suspect this can be related to SSL certificate mismatch or incorrect location for SSL certificates but I am not running with SSL anymore on the dev environment.

The health check for admin service is now passing (I temporarily disabled the AddIdentityServer health check which was failing):

![image](https://user-images.githubusercontent.com/13006228/220634706-81b16ba7-5bf9-491f-810c-4737d5326674.png)

Thanks.

**Comment by brockallen** [comment]
That sounds like the error emitted by the Microsoft OIDC handler when the token server is not available (not running or a typo, perhaps?) at the URL you configured.

**Comment by apetrut** [comment]
@brockallen The STS service is running without a problem.

**Comment by brockallen** [comment]
Not sure what the issue is then. But it's coming from the Microsoft OIDC handler code (not from IdentityServer).

**Comment by josephdecock** [comment]
I would verify that the application pod  is able to make https requests to the identity server pod.

**Comment by josephdecock** [comment]
I think you want to configure everything to use the public dns names, and make dns within the cluster route those public urls to the internal pods, hopefully b bypassing the azure stuff that is blocking your traffic. You also probably need the fitted headers middle ware-see the docs linked in your other use.

**Comment by josephdecock** [comment]
Sorry, that was a typo - I meant to say, see the docs in your [other issue](#549), which links to [this section ](https://docs.duendesoftware.com/identityserver/v6/deployment/) of the docs.

**Comment by apetrut** [comment]
@josephdecock  Thanks, it seems that it calls the ./well-known using the public name, The problem is that the public url is not accessible inside the K8S cluster. Do you have a documentation for K8S setup? Thanks.

![image](https://user-images.githubusercontent.com/13006228/222769429-3c56db43-dedf-42ad-98b0-0d55301194d5.png)

**Comment by josephdecock** [comment]
Sorry, as I said in your other issue, since IdentityServer is a framework that can be hosted anywhere that can host ASP.NET we don't have specific docs for every platform.

**Comment by leastprivilege** [comment]
In OIDC the DNS name of the OIDC provider has a special meaning. It's the identity of the identity provider.

You need to find a way to resolve the right DNS name.

**Comment by apetrut** [comment]
@leastprivilege Even if the identity server base url in appSettings.json is put with the public DNS name, it still doesn't load it. Do you know where the complete url in the picture below is constructed (including the query string parameters)? 

![image](https://user-images.githubusercontent.com/13006228/222825640-752dd48c-cf35-4051-ac47-f8605d22c496.png)

**Comment by apetrut** [comment]
@leastprivilege I've tried in K8S to rewrite DNS names from external to internal and the other way around. It didn't work.
Can you confirm that the DNS name is taken right at the time when the health check is being performed with calls made towards the Identity Server?

**Comment by josephdecock** [comment]
IdentityServer uses the DNS hostname of incoming requests in several ways. IdentityServer uses the `HttpContext.Request.Host` to determine that name when it needs it. 

Your goal should be to configure your network layer such that the hostname will be the same regardless of where the request originated.

Also, its fairly common in a setup like this to need the forwarded headers middleware. The idea here is that if a request comes to your cluster through an ingress which forwards the request, you want IdentityServer to process the request as though it came from where it originally did come from, not from the ingress.

**Comment by apetrut** [comment]
@josephdecock 
I have applied these settings so far:

app.Use((context, next) =>
            {
                context.Request.Scheme = "https";
                context.RequestServices.GetRequiredService<IServerUrls>().Origin = "https://sts.devurl.com";
                context.Request.Host = new Microsoft.AspNetCore.Http.HostString("https://sts.devurl.com");
                return next();
            });

and also have applied ALL headers:

services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.All;
            });

**Comment by josephdecock** [comment]
> app.Use((context, next) =>
> {
> context.Request.Scheme = "https";
> context.RequestServices.GetRequiredService().Origin = "https://sts.devurl.com/";
> context.Request.Host = new Microsoft.AspNetCore.Http.HostString("https://sts.devurl.com/");
> return next();
> });

I would not do this. If you get the configuration at the network level correct, then this won't be necessary. And if you don't have the network level configured correctly, this probably won't help (as requests won't even make it to IdentityServer).
