### ISSUE TITLE
The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

### ISSUE THREAD

**Issue by imharry4u** [DuendeSoftware/Support#533]
we tried to Upgrade IdentityServer4 (version 3.0.1.0) to Duende Identity Server 6.0.
I would really appreciate if you an help us with this.

    1.We created a new IdentityServer6 project with the EntityFramework integration already added by ‘dotnet new isef’
    2.Tested with client and we did got AccessToken. Works Perfectly.
    3.We restore our existing_IdentityServer_DB on DEV server.
    4.Used SQLServer reference, change the connection string to existing_IdentityServer_DB.
    5.Updated the schema changes including the new tables as required for ID6.
    6.Welcome screen and discovery document shows up successfully connecting to existing_IdentityServer_DB.
    7.Successfully Connect Client / postman and return accesstoken and userinfo.
    8.Issue : Self host the identity server at https://localhost:5001 and try to connect my web application it gives me below errors
    The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
   	
![Screenshot 2023-02-22 091552](https://user-images.githubusercontent.com/18617947/220647450-b2dedd69-f9ca-4a71-9ef3-7a7700e1a5bb.png)

I did tried the following:
1. I checked all my localhost certificates and they are also trusted.
![Screenshot 2023-02-22 091935](https://user-images.githubusercontent.com/18617947/220648624-9ee04386-30e6-4329-a36c-5f1387b2cebb.png)

**Comment by brockallen** [comment]
> Self host the identity server at https://localhost:5001 and try to connect my web application it gives me below errors
The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot

This sounds like the TLS cert you have configured for the web app doesn't match the URL you are trying to access it at.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by imharry4u** [comment]
yes, you can close this
--

*Thanks & Regards,*

*Harish Patel*
********************************************************************************************
This e-mail and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom it is addressed.  If
you are not the intended recipient or the person responsible for delivering
the e-mail to the intended recipient, then you are hereby advised that you
have received this e-mail in error and that any use, dissemination,
forwarding, printing or copying of this e-mail is strictly prohibited. If
you have received this e-mail in error please notify me.
