### ISSUE TITLE
Windows Authentication on premises

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [DuendeSoftware/Support#534]
Hi Duende,

I've been using Duende with a community license for a while now in a development / learning space... and loving it!  

I'm also in the process of updating a company's web apps which are only used within the company's network and firewalls.  They use Microsoft Windows authentication with a on-premise Active Directory server.  

My question is, should Duende IdentityServer be used in this scenario to be the bridge between Active Directory and the Blazor server app to identify the current user, or, does Active Directory have their own method of issuing tokens to applications.   

My goal is to achieve a single sign on experience for the users where it automatically identifies the current user. 

This may fall outside the scope of Duende - but that's what I'm trying to answer myself..... I'm just not sure because (in theory) I would expect Active Directory to have it's own Identity Management with potentially a way to register an application for token issuing.  

If Duende is the best way to manage SSO with on-premise AD, can you please provide me with some best practice reasons or point me in the direction of documentation for this.  I will need to sell the idea of purchasing an annual Duende license to the company if this is the case and need clarity and confidence on why before I can do this.

Thanks in advance,
Sandy

**Comment by leastprivilege** [comment]
"Old school" AD does not have those capabilities. It's from a bygone era...

Some people use ADFS on top - or switched to Azure AD altogether.

You can connect IdentityServer to on-prem AD for exactly the purposes you mention
https://docs.duendesoftware.com/identityserver/v6/ui/login/windows/

**Comment by rasaconsulting-sandy** [comment]
ok thanks.  "Old school" is probably why I'm not having much success with Google results!  

Appreciate your help and the documentation link.
