### ISSUE TITLE
Renewed seems to always equal Created in ServerSideSessions table

### ISSUE THREAD

**Issue by Rainnwind** [DuendeSoftware/Support#535]
**Which version of Duende IdentityServer are you using?**
6.2.1

**Which version of .NET are you using?**
net6.0

**Describe the bug**
When I request a new refresh token via `/connect/token` I don't see the `Renewed` being updated in the `ServerSideSessions` table.

**To Reproduce**
Sign in as any user and request a new refresh token via `/connect/token` and investigate the `Renewed` value stays the same for the session where the refresh token is being created anew.

**Expected behavior**

I expect that the `Renewed` value would change and differ from the `Created` value once a new token is created.

**Comment by brockallen** [comment]
This could happen if you have code that is calling SignOut and then calling SignIn in the same HTTP request. Is it possible that is what's happening in your scenario?

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
