### ISSUE TITLE
When authenticating between identity and Owin MVC client, code_challenge in url keeps cycling

### ISSUE THREAD

**Issue by danpcsi** [DuendeSoftware/Support#536]
**Which version of Duende IdentityServer are you using?**
6.2
**Which version of .NET are you using?**
7
**Describe the bug**
When logging in, client url is hit, redirected to login page, user logs in and redirected to client, the url looks like this

https://localhost:5001/connect/authorize?client_id=MCM&redirect_uri=https%3A%2F%2Flocalhost%2Fmcm&response_type=code&scope=openid%20profile%20MCM&code_challenge=_MQsUMd4eu-vooYckkVd_Hyx498bCYBum-KplQ0-evY&code_challenge_method=S256&state=OpenIdConnect.AuthenticationProperties%3DDL9zgFWiHay4kCq7DExXDTt7_9rfPYmaLS3J2e7dPQD9eMdnbCadF7mrxEhsFl3zdV1OxMKbPlHGYUWMmHrzzLKcbf-inoAFlP3jw1EyRbjZklsWragVxy6MLnQDufgH2Mb6xzZz5AtsDC9ft0HOMUB3-jLF4acNxnnoIG73a7CqLUshViXdn_x4XexcrURJ2mXrCYSs1yGPmV-BFVG7OuF2Q1BHdMj8blNb1r0n5xvyB_QQzW4SHI1pfopFRdk_exo2a5BJj5_OhAR1-mnPmA&response_mode=form_post&nonce=638127614660649483.MTJiZjIyZjItMWRiZS00M2Y2LWI3ZmMtMzcyOTZlMjRkZmIxZmM5MTRhNDktNzE2OC00MWNiLWI1NzItMzIyNzdmN2E4OWM0&x-client-SKU=ID_NET472&x-client-ver=6.22.1.0

The code_challenge keeps cycling in the url, the flow is the browser redirects back to the client which gives a 302 back to authorize then back to the client

![image](https://user-images.githubusercontent.com/126179898/220947150-b0485254-b187-4a99-81f5-8619e32b58fb.png)

Clients Startup
![image](https://user-images.githubusercontent.com/126179898/220947581-1a534e1d-6c70-47c8-b400-5455ecd242f8.png)

Identity client config
![image](https://user-images.githubusercontent.com/126179898/220947921-8269721d-9e75-4807-b443-20f0f3c200e9.png)

**Comment by brockallen** [comment]
It's hard to say based on the info you have. My guess is that the OIDC protocol piece is doing the right thing, but it's that your client app is failing to establish a session correctly based on the successful OIDC response. I'd suggest looking into and debugging with your browser developer tools if the MVC app is emitting the session cookie and/if the browser is not keeping it for some reason (for example, same-site settings are a common issue here).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
