### ISSUE TITLE
IdentityResource UserClaims are not being included in the access token

### ISSUE THREAD

**Issue by chrispickford** [DuendeSoftware/Support#537]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
net6.0

I'm seeing behaviour similar to that reported in the following closed as wont-fix issue raised against the archived IdentityServer4 repository: https://github.com/IdentityServer/IdentityServer4/issues/5457

I am attempting to request an access token with the `openid profile` scopes, which _should_ add various claims to the token including `given_name` and `family_name`. I can assert that these claims do exist on the principal as I can see them when debugging. However they are not included in the access token output.

I believe that this is because in the DefaultClaimsService, the IdentityResources aren't being inspected and only the ApiResources and ApiScopes are being used:

https://github.com/DuendeSoftware/IdentityServer/blob/19a3e69917b778f542673b056b1040f52f68a8db/src/IdentityServer/Services/Default/DefaultClaimsService.cs#L160-L218

Should the DefaultClaimsService be updated to include claims as specified by the configured IdentityResources? Or am I missing a piece of configuration that would enable this?

**Config**
```
public static class Config
{
    public static IEnumerable<IdentityResource> IdentityResources =>
        new List<IdentityResource>
        {
            new IdentityResources.OpenId(),
            new IdentityResources.Profile()
        };

    public static IEnumerable<Client> Clients =>
        new List<Client>
        {
            new()
            {
                ClientId = "client-a",
                AllowedGrantTypes = GrantTypes.Code,
                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile
                },
                AllowOfflineAccess = true,
                RedirectUris = { "https://oauth.pstmn.io/v1/callback" },
                RequireClientSecret = false,
                RequirePkce = true
            }
        };
}
```

**Comment by brockallen** [comment]
`IdentityResource` controls what claims the client gets. `ApiScope` (and `ApiResource`) control what claims the API gets.

> I am attempting to request an access token with the openid profile scopes

Those are `IdentityResource`s so that makes sense that the access token does not contain those claims.

**Comment by chrispickford** [comment]
Thanks for the response @brockallen, it does indeed make sense to not include the identity claims in the access token.

That being said, I've also checked the contents of the identity token and the expected profile scope claims don't appear to be included in that either.

I would expect to see the profile claims as defined here:

https://github.com/DuendeSoftware/IdentityServer/blob/19a3e69917b778f542673b056b1040f52f68a8db/src/IdentityServer/Constants.cs#L138-L154

to be included by default when they exist and when the profile scope is requested.

**Comment by brockallen** [comment]
> That being said, I've also checked the contents of the identity token and the expected profile scope claims don't appear to be included in that either.

Is your client a ASP.NET? There's a flag on the OIDC handler which defaults to false which will retrieve those claims from the userinfo endpoint. Additionally, Microsoft filters out claims they don't recognize by default. You might need to configure the Microsoft handler to do what you want: https://docs.duendesoftware.com/identityserver/v6/quickstarts/2_interactive/#getting-claims-from-the-userinfo-endpoint

**Comment by chrispickford** [comment]
Thanks for your help - I found the Client property `AlwaysIncludeUserClaimsInIdToken` which when set does exactly what I was trying to do.
