### ISSUE TITLE
Feature request: add a ConsumedTokensRemovalThreshold option for consumed refresh token cleanup

### ISSUE THREAD

**Issue by mikequ-taggysoft** [DuendeSoftware/Support#54]
The `RemoveConsumedTokens` property was added in https://github.com/DuendeSoftware/IdentityServer/pull/84 which works well. But it does cause a side effect when enabled:

If we had implemented a "grace period" logic via a custom `IRefreshTokenService` to mitigate transient issues related to consumed one-time refresh tokens and public clients with unstable network conditions, the logic would require that the consumed tokens still exist in the datastore for the duration of the grace period. Auto cleanup would remove these tokens on each run.

In this case, it would be nice if we can specify an option to only auto remove consumed tokens older than X (a `TimeSpan`). This will allow auto cleanup to function without affecting the aforementioned custom logic.

Because the token cleanup service is non-extensible, exposing such an option via `OperationStoreOptions` and using it in `RemoveConsumedPersistedGrantsAsync` would be the best way to go.

**Comment by mikequ-taggysoft** [comment]
This would also help those who override the `AcceptConsumedTokenAsync` method to detect refresh token replays. Keeping the consumed tokens in data store for a pre-defined period of time makes such logic more consistent and predictable.

Making the option null/0 by default should be a non-breaking change.

**Comment by brockallen** [comment]
Thanks, we'll have a look and see what we can do.

**Comment by brockallen** [comment]
I opened a new issue to track. Thanks.
