### ISSUE TITLE
The antiforgery token could not be decrypted.

### ISSUE THREAD

**Issue by haris-begluk** [DuendeSoftware/Support#541]
Duende.IdentityServer.AspNetIdentity" Version="6.1.5" 
Duende.IdentityServer.EntityFramework" Version="6.1.5"
.net6

I'm not able to fix the error or sometimes the warning. I have deployed the authentication server on Azure (testing) and I get an error every time the application is deployed and sometimes randomly. Usually, the log message looks like the first example below.

After some research, I found out that I need to configure data protection in the Startup.cs file as described on [MSDN](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-7.0&tabs=visual-studio), and I did that. My configuration from Startup.cs looks like the example below.

``` 
Error - Exception 
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {<GUID>} was not found in the key ring.
```

Startup.cs example of data protection config

```
            var dataProtectionKeysPath = Path.Combine(Environment.ContentRootPath, "DataProtectionKeys");
            
              services.AddDataProtection()
                .SetApplicationName(Environment.ApplicationName)
                .PersistKeysToFileSystem(new DirectoryInfo(dataProtectionKeysPath))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(14))
                .UseCryptographicAlgorithms(
                new AuthenticatedEncryptorConfiguration
                {  
                     EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
                     ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
                });
```
After adding this configuration and running the application locally, I did get an .xml file where I have only one key.

However, in the logs, I started getting more errors for multiple keys (not stored in the .xml file) like the one below.
Doesn't seem like it's fixed?

```
 [09:47:17  ERR] Error unprotecting key with kid <KEY>.
System.Security.Cryptography.CryptographicException: The key {<GUID>} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 435
```

To come to the point, I am pretty unfamiliar with the data protection key store and anti-forgery protection in general. 
I would love to know if my application, configured like this, is considered vulnerable. 
Can someone please share some details on how to configure this to avoid Antiforgery Validation Exceptions (errors and warnings)? 
Do I need to configure something else for Duende Identity to work? 

To reproduce the Issue I have small test application that is using docker (not the same application as described above), 
But Identity server in this case has the same issue and getting the similar warnings (data protection store not configured).  
[Link To App ](https://github.com/haris-begluk/ecommerce-poseidon)

I would love to know how to configure the application to prevent this kind of errors and warnings.
Not sure am I doing right thing?

**Log output/exception with stacktrace**

``` 
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {GUID} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext) 

WARNING
No XML encryptor configured. Key {KeyId:B} may be persisted to storage in unencrypted form.
```

**Comment by josephdecock** [comment]
There are 2 different keys here:
1. IdentityServer has signing keys that it uses to create the cryptographic signatures in JWTs
2. ASP.NET has data protection keys that it uses to encrypt data, such as antiforgery tokens, authentication cookie data, etc

IdentityServer uses data protection to encrypt sensitive values, _including automatically managed signing keys_

Your first exception is coming entirely from ASP.NET, and indicates that you needed to set up data protection. Those data protection keys need to be persisted and shared across load balanced nodes. Your configuration looks okay to me, assuming that the file system location that you are writing data protection keys to is in fact shared across all instances of your identity server.

Your second exception is coming from IdentityServer. It is saying that there is a signing key that cannot be decrypted. Since you just changed you data protection configuration, my bet is that signing key was generated before you changed data protection settings. If so, then deleting the signing key that is giving you errors will solve the problem. 

For more info, take a look at our [docs on key management ](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by haris-begluk** [comment]
Thank you for the quick, precise and detailed answer. 
The solution was exactly as you described. I also had a problem with the instances as you warned me. 
Issue solved.
