### ISSUE TITLE
Build warning after upgrading to .Net7 and AutoMapper 12.0.1

### ISSUE THREAD

**Issue by gopala000** [DuendeSoftware/Support#542]
**Which version of Duende IdentityServer are you using?**

Dende.IdentityServer.AspNetIdentity latest version 6.2.3

**Which version of .NET are you using?**
.Net7

**Describe the bug**
After I upgraded my project to .Net7 and updated dependencies, I get below build warning. Let me know if this is okay or if there is a workaround to get rid of the warning.

`**Detected package version outside of dependency constraint: Duende.IdentityServer.EntityFramework.Storage 6.0.4 requires AutoMapper (>= 11.0.0 && < 12.0.0) but version AutoMapper 12.0.1 was resolved.**`

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
If you have all the IdentityServer nuget packages upgraded, then you should not have a dependency issue. We have however [seen this happen](https://github.com/DuendeSoftware/Support/issues/445) with Microsoft's `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` package. Are you using that?

**Comment by gopala000** [comment]
I'm using Duende.IdentityServer.AspNetIdentity latest version 6.2.3. Are you suggesting to use prerelease? I do have reference to Microsoft.AspNetCore.ApiAuthorization.IdentityServer (version 7.0.3)

**Comment by josephdecock** [comment]
No, you shouldn't need a prerelease build either. 

Where is the dependency on Duende.IdentityServer.EntityFramework.Storage coming from?

**Comment by josephdecock** [comment]
That package is maintained by Microsoft, and we generally discourage its use. It is included in some of Microsoft's templates, but those templates make architectural compromises that we don't recommend. The package also is incompatible with .NET 7. 

We have a [guide in our docs](https://docs.duendesoftware.com/identityserver/v6/upgrades/spa_to_duende/) on how to migrate away from those templates that describes the architectural issues in more detail as well.

**Comment by gopala000** [comment]
Thanks for the guidance. I'll look at migrating away.

**Comment by lnaie** [comment]
Now, if your architecture increases my bills then is not a useful architecture, is it?
