### ISSUE TITLE
`AuthorizationRequest` info missing in login page model

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#543]
**Which version of Duende BFF are you using?**
Community
**Which version of .NET are you using?**
7.0.102
**Describe the bug**
The following log in Login page model shows that the information is missing.
```
_logger.LogInformation($"RedirectUri: {context?.RedirectUri}, ClientId: {context?.Client.ClientId}, ClientName: {context?.Client.ClientName}, ClientUri: {context?.Client.ClientUri}");
```
I need this information to be able to tell which client the login request is sent from in order to validate the request against user roles so as to decide whether or not to authorize the user access.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
What are the steps to reproduce this problem? 
Is this really a BFF issue?

**Comment by khteh** [comment]
Doesn't work:
```
    public async Task<IActionResult> OnPostAsync(string returnUrl = null)
    {
        AuthorizationRequest context = await _interaction.GetAuthorizationContextAsync(Input.ReturnUrl); // Retrieved in GET request
``
Fixe:
```
    public async Task<IActionResult> OnPostAsync(string returnUrl = null)
    {
        AuthorizationRequest context = await _interaction.GetAuthorizationContextAsync(returnUrl); // Retrieved in 
```
I notice that the sample applications in your tutorial doesn't have this input param in the `POST` request. How would that work then?
