### ISSUE TITLE
Provide sample implementation for local development server on different port

### ISSUE THREAD

**Issue by Stra1ghter** [DuendeSoftware/Support#548]
Hi,

We are using BFF for nearly all of our applications and are currently developing it with the SpaServices.

Similar to [this issue](https://github.com/DuendeSoftware/Support/issues/84) we would like to use the local development servers that come with React / Angular etc.
With a BFF setup this isn't possible straightforward as they run on a different port locally.
Could you provide a sample implementation on how to allow such a setup for the local development environment?

Thank you

**Comment by josephdecock** [comment]
This is an area that we are actively working on, and we expect to publish updated documentation soon. The issue where this is tracked is [here](https://github.com/DuendeSoftware/docs.duendesoftware.com/issues/227#issuecomment-1447846968).

**Comment by Stra1ghter** [comment]
Hi @josephdecock,
Thank you for your help!
I just tried to adjust one setup to your provided sample. Unfortunately, I didn't succeed. The CORS check works, the URLValidator works and the cookie is set for the development site, but I still get a 401 for `/api/bff/user`, not sure why.

**Comment by josephdecock** [comment]
When you make the request to /api/bff/user, can you see the bff auth cookie being sent in that request? Is there anything in the bff's logs when it returns 401?

**Comment by brockallen** [comment]
We recently published a sample here: https://docs.duendesoftware.com/identityserver/v6/samples/bff/#separate-host-for-ui

And updated our docs here: https://docs.duendesoftware.com/identityserver/v6/bff/architecture/ui-hosting/

So I think we can close this issue now. Please have a look, and if you still feel there is something missing please re-open or open a new issue. Thanks.
