### ISSUE TITLE
Documentation for Azure K8S deployment

### ISSUE THREAD

**Issue by apetrut** [DuendeSoftware/Support#549]
Hi,

Does Duende software have a documentation for deployment on Azure Kubernetes with Azure App Gateway? I could only find one for deployment as Azure App Services.

**Comment by josephdecock** [comment]
IdentityServer is a framework for building auth services that can be hosted anywhere that can host ASP.NET, so we don't have specific docs for every platform.

Instead, we have platform agnostic hosting docs [here](https://docs.duendesoftware.com/identityserver/v6/deployment/).
