### ISSUE TITLE
Identity claims are not returned in access token even when the profile service is implemented

### ISSUE THREAD

**Issue by SangeetAgarwal** [DuendeSoftware/Support#553]
**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer 6.2.0

**Which version of .NET are you using?**
.NET Core 6

**Describe the bug**
Per [documentation ](https://docs.duendesoftware.com/identityserver/v5/fundamentals/claims/) the extensibility point to emit Identity claims in the access token is profile service. Though I have implemented the profile service, they are not present in the access token.

**To Reproduce**
Clone the repo at https://github.com/SangeetAgarwal/SecuringAppsWithOAuth2AndOIDC-Scratch

Steps to reproduce the behavior.

1. Run the app by selecting multiple startup projects & setting the action for each of the 3 projects to `start` 
2. login with user name of 'Appa' and password of 'Sourdough@0621'
3. Select yes at consent screen.
4. Copy `access token` being logged for `Notes.MvcApp.exe` and inspect at [Jwt.io](https://jwt.io/)

**Expected behavior**
The access token is logged by the Note.MvcApp. On inspecting the access token at [Jwt.io](https://jwt.io/), the identity claims of `role` and `subscriberSInce` should be present in the access token.

**Additional context**

The [sample github app](https://github.com/SangeetAgarwal/SecuringAppsWithOAuth2AndOIDC-Scratch) is a simple MVC app that calls an API. The MakeBitByte.IDP is a Duende IDP

I can see the profile service being called twice at [GetProfileDataAsync](https://github.com/SangeetAgarwal/SecuringAppsWithOAuth2AndOIDC-Scratch/blob/8d8ecc8d5ee915156a4abbb0d1111eb546328226/MakeBitByte.IDP/Services/LocalUserProfileService.cs#L19), once by `context.Caller ClaimsProviderAccessToken` and once by `context.Called  UserInfoEndpoint`.

One would expect the `access token` to contain all the identity claims that were added by `context.AddRequestedClaims(claims)`

I'm not entirely sure what I might be missing and have read the documentation extensively and have also gone through numerous [stackoverflow questions](https://www.google.com/search?q=return+identity+claims+in+access+token+site%3Astackoverflow.com&rlz=1C1CHBF_enUS995US995&sxsrf=AJOqlzXgCpVJfUns5bkBTGMOPXTOJOLyXw%3A1678062774671&ei=tjQFZNTZKJyZptQPvNuT0As&ved=0ahUKEwjUjOH8hsb9AhWcjIkEHbztBLoQ4dUDCBA&uact=5&oq=return+identity+claims+in+access+token+site%3Astackoverflow.com&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQA0oECEEYAVCACVijDWDLEGgBcAB4AIABTogBpAKSAQE0mAEAoAEBwAEB&sclient=gws-wiz-serp) but cannot understand why the `identity claims` are not present in the `access token`

Please note: when I explicitly return `UserClaims`  [as shown here](https://github.com/SangeetAgarwal/SecuringAppsWithOAuth2AndOIDC-Scratch/blob/8d8ecc8d5ee915156a4abbb0d1111eb546328226/MakeBitByte.IDP/Config.cs#L17)  from `ApiResources` then the Identity claims _are_ being returned in the access token so there isn't any issue with say `MapJsonKey` in the client app within `.AddOpenIdConnect`.

I have tried 2 other flows besides the default `auth code with pkce`, `hybrid` and even `implicit` and in each, the `access token` doesn't get the identity claims.

Any help would be much appreciated.

**Comment by josephdecock** [comment]
The profile service's `AddRequestedClaims` method filters the claims that it adds to only include claim types that have been requested by the client. The client requests particular claim types by requesting the scopes of `IdentityResources` that are configured to include those claim types in their `UserClaims` property. 

The intent of the design of `AddRequestedClaims` is to allow clients to request the claims they need, and optionally to give the end user the opportunity to give consent for that data (if you're using consent). The `ProfileService` is then responsible for retrieving claim values, but the requested scopes and their configuration is responsible for which claims actually get sent to the client.

If you have claims that don't need to follow those rules, your `ProfileSerivce` could instead update the [IssuedClaims](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Models/Contexts/ProfileDataRequestContext.cs#L92) in the context in any way you see fit.

**Comment by josephdecock** [comment]
Also, thanks for the really detailed support request! Based on your experience, I'm thinking we should add some description of `AddRequestedClaims` to the docs, possible [here](https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/). There is one line of description about the filtering that happens [here](https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/#duendeidentityservermodelsprofiledatarequestcontext), but I am thinking we should expand on that. If you have any other suggestions, I'd love to hear them.

**Comment by SangeetAgarwal** [comment]
@josephdecock Thank you so much for the quick response, having ` context.IssuedClaims = claims.ToList();` in the ProfileService did the trick. 

Yes, As you suggested if you could add some more documentation about differences between ` context.IssuedClaims` & `AddRequestedClaims`  then that would be helpful. I think your comment above that explains the differences between the two, in the documentation itself should suffice.
I suspect folks might be setting `AlwaysSendClientClaims = true` when they run across this issue with `AddRequestedClaims`.

Incidentally, the documentation is otherwise very helpful.

 And, on a different note thank you (and other folks at Duende) for creating and maintaining such an awesome project.
