### ISSUE TITLE
Silent login isLoggedIn always false with Azure AD

### ISSUE THREAD

**Issue by tylersouthard** [DuendeSoftware/Support#554]
**Which version of Duende BFF are you using?**
2.0.0

**Which version of .NET are you using?**
7

**Describe the bug**

I may be mis-configuring something, but I seem to always get output of 

> Silent login endpoint rendering HTML with JS postMessage to origin https://localhost:5002 with isLoggedIn false

when attempting to have my app perform silent login. Subsequent attempts to log in (non-silently) succeed, but restarting the app and trying silent login again still indicate `isLoggedIn` is false.

**To Reproduce**

I can reproduce this most easily starting with the [Duende.BFF JS6 sample](https://github.com/DuendeSoftware/BFF/tree/main/samples/JS6). I then added a reverse proxy to call a locally running web API and also pointed the authentication to an Azure registered application. Here is the added/modified code.

Startup.cs
```
services.AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"))
    .AddTransforms<AccessTokenTransformProvider>();

---

endpoints.MapBffReverseProxy();
```
Also in Startup.cs, I change the Authority/ClientId/ClientSecret to point to my Azure registered application. E.g., 
```
options.Authority = "https://login.microsoftonline.com/<tenant id from config>/v2.0";
options.ClientId = <client id from config>;
options.ClientSecret = <secret from user secrets/config>;
```

appsettings.json
```
"ReverseProxy": {
    "Routes": {
      "remoteApi": {
        "ClusterId": "remoteApiCluster",
        "Match": {
          "Path": "/api/{**catch-all}"
        },
        "Metadata": {
          "Duende.Bff.Yarp.TokenType": "User"
        }
      }
    },
    "Clusters": {
      "remoteApiCluster": {
        "Destinations": {
          "remoteApiDestination": {
            "Address": "https://localhost:7373/"
          }
        }
      }
    }
```

If I swap out the OpenIdConnect options to use a different Authority/ClientId/ClientSecret (our own SSO server running IdentityServer6), I am able to perform silent login just fine.

**Expected behavior**

`isLoggedIn` would be true if I had successfully logged in previously.

**Log output/exception with stacktrace**

```
[13:08:34 Debug] Duende.Bff.ManagementEndpoints
Processing user request

[13:08:34 Debug] Duende.Bff.ManagementEndpoints
User endpoint indicates the user is not logged in, using status code 401

[13:08:34 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /bff/user responded 401 in 185.4341 ms

[13:08:34 Debug] Duende.Bff.DefaultSilentLoginService
Processing silent login request

[13:08:34 Debug] Duende.Bff.DefaultSilentLoginService
Silent login endpoint triggering Challenge with returnUrl /bff/silent-login-callback

[13:08:35 Debug] Duende.Bff.BffOpenIdConnectEvents
Setting OIDC ProtocolMessage.Prompt to 'none' for BFF silent login

[13:08:35 Information] Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler
AuthenticationScheme: oidc was challenged.

[13:08:35 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /bff/silent-login responded 302 in 1396.5033 ms

[13:08:38 Debug] Duende.Bff.ServerSideTicketStore
Creating entry in store for AuthenticationTicket, key <XXXXX>, with expiration: 03/07/2023 02:08:38

[13:08:38 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: cookie signed in.

[13:08:38 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /signin-oidc responded 302 in 1788.2293 ms

[13:08:38 Debug] Duende.Bff.DefaultSilentLoginCallbackService
Processing silent login callback request

[13:08:38 Debug] Duende.Bff.DefaultSilentLoginCallbackService
Silent login endpoint rendering HTML with JS postMessage to origin https://localhost:5002 with isLoggedIn false

[13:08:38 Information] Serilog.AspNetCore.RequestLoggingMiddleware
HTTP GET /bff/silent-login-callback responded 200 in 74.5634 ms
```

**Additional context**

N/A

**Comment by josephdecock** [comment]
From the logs, we can see that the oidc request succeeded and then the auth cookie was issued. But the subsequent request to the silent login callback endpoint was not authenticated. This indicates a cookie problem. Can you take a look at the network traffic in your browser tools and verify that the auth cookie isn't being sent to the silent login callback? If so, do the browser tools give any indication why?

**Comment by tylersouthard** [comment]
@josephdecock Thanks for the response. 

It appears the issue is that the cookie was not allowed to be set because it thought it was from a response from a different site:
![img](https://user-images.githubusercontent.com/28648423/223465567-af9481a0-c135-49fc-9f96-c83598baa144.png)

What's interesting is that the `set-cookie` is in the response to the `https://localhost:5002/signin-oidc?...` request, which is the same site. Comparing the requests/responses between the Azure AD interaction and the interaction when using our own SSO, the `signin-oidc` responses are both trying to set the cookie, but one succeeds and the other fails, which is confusing to me. The only other difference I can see is that the Azure login flow seems to have two calls to `authorize`, whereas our internal SSO only has one call to `authorize`. Not sure if that matters.

If I change the Duende.BFF sample to use `SameSite = None` and `Secure = Always`, it works to perform the silent login with Azure AD.

I'm guessing this isn't a Duende.BFF issue, so sorry for the bother. I just figured the sample code might work out of the box with Azure AD.

**Comment by josephdecock** [comment]
The request is cross-site because there is a redirect involved starting from azure ad's site and ending at localhost.

You will need to change the SameSite cookie setting, though I believe SameSite = Lax should work here.

**Comment by tylersouthard** [comment]
Unfortunately Lax didn't work either (same error, but indicating Lax instead of Strict). I wonder about the redirect bit, since I thought that's how all other external authentication occurred (e.g., using our internal SSO, which uses IdentityServer6, it redirects out to that server, then back to localhost as well).

**Comment by josephdecock** [comment]
Maybe your internal SSO isn't cross site because the sites because their domains are similar enough - identityserver.yourcompany.com and yourapp.yourcompany.com are all the same site.

**Comment by tylersouthard** [comment]
Thanks again for your help with this.

Maybe it's easier to compare the Azure AD behavior with the test Duende endpoints behavior. `Strict` works fine for the test Duende endpoints (using `interactive.confidential` for this test). Here are the network calls for each, highlighting the `Set-Cookie` call for the `signin-oidc` response.

![duende](https://user-images.githubusercontent.com/28648423/223703658-e925db71-0297-4c52-8243-a0ede448c03f.png)
![azure](https://user-images.githubusercontent.com/28648423/223703694-66383585-178f-46d3-880b-acd0e72977ef.png)

**Comment by josephdecock** [comment]
I'm not sure why you're getting different behavior between demo.duendesoftware.com and azure ad. In general though, the silent login endpoint is not going to be reliable if your identity provider is a 3rd party site, because browsers are gradually moving to block 3rd party cookies. This is done to protect user privacy, and not all browsers are doing so yet, but all major browsers at least say they intend to do so. Unfortunately, as they do, this breaks things like silent login.

You could work around that by using IdentityServer as a federation gateway. Your bff's authority would be your gateway identity server implementation, which would be 1st party to the bff. The gateway can federate with azure ad or whatever other 3rd party identity provider you like. With this gateway in place, the silent login requests are entirely first party.

**Comment by tylersouthard** [comment]
Thanks! That sounds like a route to pursue. Appreciate the help.
