### ISSUE TITLE
Server side sessions don't write on the db

### ISSUE THREAD

**Issue by valse** [DuendeSoftware/Support#555]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
.net core 6.0.14

Hi I'm using Identity Server from version 4 and now I'm migrating it to the latest version.
With this new version I'd like to add the use of the server side sessions and store them in a Sql server Db by the EF.

At the moment I have one ApplicationDbContext that extends the IdentityDbContext, the IConfigurationDbContext and now I added the IPersistedGrantDbContext too.
I created the new migration and the update complete successfully.

I can see, for example, the new keys stored in the Keys table now but even the grants or the sessions still in memory because the corresponding tables are empty.

I can't understand why... I need to add the license in development too?!

Thanks for your help 🙏🏻

**Comment by josephdecock** [comment]
Apart from the DB Context, you also need implementation of the store interfaces. We provide stock implementations of the stores that you can use, or your can implement them yourself if you need to customize the behavior. It sounds like you're using the in memory implementations, which we provide for testing/demos. You probably want to switch to our EntityFramework based implementations of the stores.

Take a look at [this section in the docs ](https://docs.duendesoftware.com/identityserver/v6/data/) that describes how IdentityServer stores data.

Regarding licensing - our licensing system verifies that the correct license is used, and emits log messages if it notices a problem, but it doesn't change or limit any functionality of IdentityServer. Non-production environments do not need a license.

**Comment by valse** [comment]
Hi Joe thanks for your help: I'd like to switch from in-memory to EF implemention without custom behaviors.
I'd already added the 'AddServerSideSessions().AddOperationalStore` commands but only the Keys are written to the database... The session table still empty.
If it's not a license issue there's something else to check?

**Comment by valse** [comment]
Hi, thanks for your suggestions: I checked the logs and I can't never see these entries on mine:

```
[16:31:03 Debug] Duende.IdentityServer.Stores.ServerSideTicketStore
Retrieve AuthenticationTicket for key 4B08C1939DAE9807A0B57EC0CA1F1888A5396566025F580E5521CC70A621416A

[16:31:05 Debug] Duende.IdentityServer.EntityFramework.Stores.ServerSideSessionStore
Found server-side session 4B08C1939DAE9807A0B57EC0CA1F1888A5396566025F580E5521CC70A621416A in database: True

[16:31:05 Debug] Duende.IdentityServer.Stores.ServerSideTicketStore
Ticket loaded for key: 4B08C1939DAE9807A0B57EC0CA1F1888A5396566025F580E5521CC70A621416A, with expiration: 03/22/2023 15:29:16
```

I tried to implement the server side session with EF on all your examples and it work everywhere... even with a unique ApplicationDbContext that implements the two store interfaces.

There is something in our implementation that skips the server side creation because if I try to query them I get an empty response:

```json
{
   "resultsToken": null,
   "hasPrevResults": false,
   "hasNextResults": false,
   "totalCount": 0,
   "totalPages": 0,
   "currentPage": 0,
   "results": []
}
```

Thanks!

**Comment by josephdecock** [comment]
If you have server side sessions working in the EF quickstart, but not in your implementation, I would compare the two and try to find what you've done differently.

**Comment by valse** [comment]
Hi @josephdecock ... I found my issue: we're overwriting too the `IPostConfigureOptions<CookieAuthenticationOptions>` with a custom implementation but we can remove it and achieve the same result with yours... other then persist finally the user session after a service restart 😍

Thanks for your help!
