### ISSUE TITLE
Configuring options for dynamic providers

### ISSUE THREAD

**Issue by GMillerVarian** [DuendeSoftware/Support#556]
Using DIS 6.2.3 with .NET 6.0.14. 

We are converting our implementation to use dynamic providers as per [the docs](https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders). We have implemented a custom IIdentityProviderStore and it seems to be returning our providers as expected. We have also implemented a custom Configure Options class as per [the docs](https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders/#accessing-oidcprovider-data-in-iconfigurenamedoptions), and configured it in DI. During login, after selecting the provider the following error occurs:

`InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.`

We can see that the Configure() method in our custom Configure Options class is never called, which explains the error. The constructor is called, but not the Configure() method.

**Comment by josephdecock** [comment]
One possibility is that the authority is missing or incorrect in your configuration in the database. In your Identity Provider data store, I would expect to see the authority within the json in the Properties column of the IdentityProvider.

Another possibility is that your custom configure options is overriding the authority value incorrectly. What is your configure options code doing? Can you post that code?

**Comment by GMillerVarian** [comment]
We store our Identity Providers in a custom DB table. There is no "Properties" column. Hence the custom IIdentityProviderStore. We set the authority when configuring the options. I can't post the custom configure options here, but could send it to you privately. Note, however, that currently it is not even calling the Configure method, so there is something wrong before even configuring the options.

**Comment by josephdecock** [comment]
If the configure method is never called, that sounds like a problem with the way the options class is registered with the DI system. How are you doing that?

**Comment by GMillerVarian** [comment]
We have the following called from the ConfigureServices method in Startup.cs:

`services.ConfigureOptions<CustomOidcConfigureOptions>();`

This is the class. It does call the constructor, but not the Configure method:

`class CustomOidcConfigureOptions : ConfigureAuthenticationOptions<OpenIdConnectOptions, OidcProvider>
{
    private readonly IdentityServerOptions _identityServerOptions;
    private readonly IServiceProvider _serviceProvider;

    public CustomOidcConfigureOptions(
        IHttpContextAccessor httpContextAccessor,
        IdentityServerOptions identityServerOptions,
        IServiceProvider serviceProvider
        ) : base(httpContextAccessor)
    {
        _identityServerOptions = identityServerOptions;
        _serviceProvider = serviceProvider;
    }

    protected override void Configure(ConfigureAuthenticationContext<OpenIdConnectOptions, OidcProvider> context)
    {
        var provider = context.IdentityProvider;
        var options = context.AuthenticationOptions;

        // options are configured here
    }
}`

**Comment by josephdecock** [comment]
Your options class looks fine to me. I actually tried adding it to our sample, and the configure method does get invoked. I've published that test in a branch so you can compare a working implementation to yours: https://github.com/DuendeSoftware/Samples/tree/joe/support/dynamic-provider-config/IdentityServer/v6/UserInteraction/DynamicProviders

**Comment by GMillerVarian** [comment]
The main difference I see is our custom IIdentityProviderStore. This is our implementation of GetBySchemeAsync, is there anything missing, for example any properties we should be setting? I tried adding "Authority" but that didn't help.

`    public Task<IdentityProvider> GetBySchemeAsync(string scheme)
    {
        var provider = _providerRepository.Get()
            .FirstOrDefault(p => $"{p.TenantId}-{p.AuthenticationScheme}" == scheme);

        if (provider != null)
        {
            // Type must be "oidc" as per the following:
            // https://github.com/DuendeSoftware/Support/issues/43#issuecomment-1116461270
            var identityProvider = new IdentityProvider("oidc")
            {
                DisplayName = provider.DisplayName,
                Scheme = scheme,
                Enabled = provider.Enabled,
            };

            return Task.FromResult(identityProvider);
        }

        return Task.FromResult<IdentityProvider>(null);
    }`

Note that we are always using type "oidc" even though the claim type may be email, upn, etc. Is that correct?

**Comment by josephdecock** [comment]
The type here isn't the claim type, but rather the protocol type, so "oidc" is correct

You do probably need to include the authority of the IdentityProvider. What's going on is, the IdentityProvider is an abstraction that allows dynamic providers to be used with other protocols. There is an OidcProvider that inherits from IdentityProvider and adds all the configuration that is specific to OIDC. The IdentityProvider contains a properties dictionary for all the protocol specific stuff, and the OidcProvider's properties read and write to that dictionary. I would normally expect that you'd store most of those configuration values in the database, and then copy them into an OidcProvider instance here.

**Comment by GMillerVarian** [comment]
I was able to reproduce in your branch by adding the following custom provider:

`public class ExternalIdentityProviderStore : IIdentityProviderStore
{
    private readonly ConfigurationDbContext _context;

    public ExternalIdentityProviderStore(ConfigurationDbContext context)
    {
        _context = context;
    }

    public Task<IEnumerable<IdentityProviderName>> GetAllSchemeNamesAsync()
    {
        var providers = _context.IdentityProviders;

        var schemeNames = providers.Select(p => new IdentityProviderName
        {
            DisplayName = p.DisplayName,
            Scheme = p.Scheme,
            Enabled = p.Enabled
        });

        return Task.FromResult(schemeNames.AsEnumerable());
    }

    public Task<IdentityProvider> GetBySchemeAsync(string scheme)
    {
        var provider = _context.IdentityProviders.FirstOrDefault(idp => idp.Scheme == scheme);

        if (provider != null)
        {
            var idp = new IdentityProvider("oidc")
            {
                DisplayName = provider.DisplayName,
                Scheme = scheme,
                Enabled = provider.Enabled
            };

            return Task.FromResult(idp);
        }

        return Task.FromResult<IdentityProvider>(null);
    }
}
`

and registering it in Startup.cs:

`services.AddTransient<IIdentityProviderStore, ExternalIdentityProviderStore>();`

**Comment by brockallen** [comment]
@GMillerVarian -- you need to return an OidcProvider instance with the Properties properly populated from the store. The Properties contains the OIDC settings needed for the rest of the plumbing to work properly.

**Comment by GMillerVarian** [comment]
I have tried including all properties from our store, including Authority, ClientId and Scope (hard-coded to "openid profile") and it still wasn't working.

**Comment by brockallen** [comment]
I'd suggest in your custom store mimicking how the EF provided implementation works: https://github.com/DuendeSoftware/IdentityServer/blob/main/src/EntityFramework.Storage/Stores/IdentityProviderStore.cs

**Comment by GMillerVarian** [comment]
The problem was that we were returning a provider of type IdentityProvider from our custom store. Once we changed this to return a provider of type OidcProvider (and set the Authority and ClientId) it started working.

Thank you so much for your assistance!

**Comment by brockallen** [comment]
@josephdecock maybe we could do better in the code to detect this type of thing?

**Comment by brockallen** [comment]
> and we also add them to the CorsPaths in IdentityServerOptions.

Not to tangent too much from your question, but it's unclear why you'd need to do that. All of these endpoints in the OIDC protocol are designed to be accessed by browser window requests, not Ajax requests. I do not see why this should be necessary, so it makes me wonder if something else is incorrect elsewhere in your system (either clients or IdPs or something).

**Comment by GMillerVarian** [comment]
Thank you so much again for your assistance with this. We have implemented your 2nd suggestion and so far seems to be working perfectly!
