### ISSUE TITLE
Question on Signed Authorization Requests JWT expires claim

### ISSUE THREAD

**Issue by michaeldimoudis** [DuendeSoftware/Support#557]
**Which version of Duende IdentityServer are you using?** latest

**Which version of .NET are you using?** .NET Framework (client) and .NET 6 (idp)

**Question**

If authorization requests do not complete within a few minutes, this error is raised:

```
IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.

Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Duende.IdentityServer.Validation.JwtRequestValidator.ValidateJwtAsync(JwtRequestValidationContext context, IEnumerable`1 keys) in /_/src/IdentityServer/Validation/Default/JwtRequestValidator.cs:line 189
   at Duende.IdentityServer.Validation.JwtRequestValidator.ValidateAsync(JwtRequestValidationContext context) in /_/src/IdentityServer/Validation/Default/JwtRequestValidator.cs:line 144
```

Using this sample https://github.com/DuendeSoftware/Samples/blob/a74365eac1839a220229c8632ce7ea6ecdf6ddea/IdentityServer/v6/Basics/MvcJarJwt/src/AssertionService.cs#L69 the JWT expires in 1 minute after creation.

I believe the default cookie nonce is 15 minutes. What if the nonce is increased to 60 minutes? Does the JWT expires need to be that short lived to 1 minute or can it be in sync with cookie nonce expiry? Especially if some time consuming activity occurs on the idp like registrations?

Just after some advice and best approach here. Thank you.

**Comment by brockallen** [comment]
> If authorization requests do not complete within a few minutes, this error is raised:

That makes sense because the JAR does get revalidated as part of the user's journey from the authorize endpoint, into the login page, and then back to the authorize endpoint and if that takes too long, then I can see the JAR expiring. 

The JAR expiration is a separate from the nonce in the client. 

Since your client creates the JAR, you can control the exp value when your client creates it, so you should be able to make it as long as you want or need.

**Comment by michaeldimoudis** [comment]
Thanks for your help that makes sense. I wasn't 100% sure if this expires was just for the initial auth request and then some internal state took over. We'll keep the JWT expiry the same length as our cookie nonce.
