### ISSUE TITLE
Missing JWT token with Safari (macOS and iOS)

### ISSUE THREAD

**Issue by erossini** [DuendeSoftware/Support#560]
I'm creating Blazor WebAssembly applications hosted in ASP.NET Core. To authenticate users, I integrate Identity Server. The application calls the API using the user token. The application reads the token after the authentication as expected and calls the API: this behaviour is working only on Microsoft Edge and Chrome.

When I run the applications on macOS or iOS, the token is always null. For this reason, I opened an [issue](https://github.com/dotnet/aspnetcore/issues/45501) on the Microsoft repo. Basically, they said the issue is in my code because Safari, correctly, doesn't allow the application to read the JWT user token.

I tried a lot of things but I can't find a solution that works across the browsers and operating systems.

So, I created this repo [here](https://github.com/erossini/BlazorJWTTest) (sorry the project is very basic without CSS).

When you run the application, click on *Log in*. Then, you will redirect to the Identity Server when you can use the following credentials:

Username: MSTest
Password: MSTest!2023

Then, you can see a new link called *Simulation*. The *Simulation* calls the API using the user token.

For your convenient, I deployed the test website [here](https://azuks-chi-220156-app-wa-d2.azurewebsites.net/) 

When you run the app on Windows with Edge, for example, you can see that the call to the API is working.

![image](https://user-images.githubusercontent.com/9497415/210386441-81c09fdf-5bd2-4b91-a7c0-2c2b10600b93.png)

But when you run the website on an iPhone you get an error.

![image](https://user-images.githubusercontent.com/9497415/210387252-93633ad0-b148-49d4-862c-343127aaaa37.png)

Have you ever faced a similar issue? How can I fix it? What is your recommendation and/or best practice?

**Comment by josephdecock** [comment]
> Basically, they said the issue is in my code because Safari, correctly, doesn't allow the application to read the JWT user token.

This is on the right track, but let me clarify a few details. Safari, and other browsers like Firefox and Brave, block 3rd party cookies by default. Chrome can be configured to block 3rd party cookies, and Google has been saying for years that they intend to make that the default eventually. So, this cookie problem is probably coming to all browsers, eventually. This is being done to protect privacy, but unfortunately for those of us working on identity, an external identity provider that can track a user as they navigate across sites is not really distinguishable from an advertiser that can track a user as they navigate around the web. This means that certain oauth and oidc protocol interactions break in browsers that block 3rd party cookies when the application and identity provider are not 1st party to each other. 

One of the things that breaks in that situation is silent login. The way silent login works is, the client application creates a hidden iframe that makes an oidc authorize request, passing the prompt=none parameter to tell the OIDC Provider that user interaction isn't possible here. If you already have a session at the OP, then it can respond immediately to allow the application to get tokens. If not, the OP will respond with an error, indicating that you have to log in. But the only way that the OP would know if you have a session is if you _send your session cookie_ with the request in the iframe.

That iframe is inside the client application but it is calling the OP. So, if the client and the OP are not on the same site, browsers that don't send 3rd party cookies won't send the cookie in the request to the OP. Without the session cookie, the silent login will always fail.

The `RemoteAuthenticationService` is performing a silent login to request a new token whenever you call `RequestUserToken`, so clearly that will fail on browsers that block 3rd party cookies when your OP is 3rd party to the client application.

Our recommendation is to use the backend for frontend pattern, which pairs your frontend blazor application with a backend service that handles all of the protocol flows and performs token and session management. Our BFF tools can help you build that - see our documentation [here](https://docs.duendesoftware.com/identityserver/v6/bff/).

**Comment by erossini** [comment]
Thank you for your answer!
