### ISSUE TITLE
Logout not retrieving PostLogOutUri

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#561]
**Which version of Duende IdentityServer are you using?**
6.3

**Which version of .NET are you using?**
7.0

**Describe the bug**

I have 4 apps secured by an Identity Server implementation. When the user selects "logout" on them I redirect the user to the /Account/Logout/Index. They then get the page confirming if they want to log out and a button labeled "Yes". Clicking "Yes" takes them to /Account/Logout/LoggedOut. There is code on that final page to display a button that will take them back to the app they logged out of:

    public async Task OnGet(string logoutId)
    {
        // get context information (client name, post logout redirect URI and iframe for federated signout)
        var logout = await _interactionService.GetLogoutContextAsync(logoutId);

        View = new LoggedOutViewModel
        {
            AutomaticRedirectAfterSignOut = LogoutOptions.AutomaticRedirectAfterSignOut,
            PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
            ClientName = String.IsNullOrEmpty(logout?.ClientName) ? logout?.ClientId : logout?.ClientName,
            SignOutIframeUrl = logout?.SignOutIFrameUrl
        };
    }

The PostLogoutRedirectUri property is null, despite my client having this field set in the database. I've checked with a SQL profiler and code debugger and the data is being returned correctly. Can you advise where I need to provide the PostLogoutRedirectUri's data so it gets picked up and this button to navigate back to the client displays? The LogoutRequest object gets all the correct Clients but as you can see the PostLogoutRedirectUri isn't being populated for some reason.

![LogoutRequest](https://user-images.githubusercontent.com/3273917/224091415-a7b3850a-a139-4e72-88b5-7cfee178da75.JPG)

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
Is your request to the end session endpoint including the id_token_hint parameter?

**Comment by nhumby** [comment]
Doesn't look like it:
   https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

That gets 302'd to:
   https://localhost/identity/Account/Logout?logoutId={massive bunch of numbers and letters}

**Comment by nhumby** [comment]
Doesn't look like it:
https://localhost/identity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

That gets 302'd to:
[https://localhost/identity/Account/Logout?logoutId={massive](https://localhost/identity/Account/Logout?logoutId=%7Bmassive) bunch of numbers and letters}

**Comment by josephdecock** [comment]
You need to specify the post logout redirect uri in your endsession request. IdentityServer validates that the requested uri is one that it expects to defend against open redirector attacks, but it does not automatically set one if you don't pass it in.

You also need to pass the id_token that the user originally was issued at login as the id_token_hint. This is used to authenticate the request to the endsession endpoint.

**Comment by nhumby** [comment]
Oops spoke too soon. I'm calling a .NET signout API endpoint on my app. If I simply redirect to the endession endpoint I sign out but it only signs me out of the Identity Server, I can still browse straight back into my secured app without authenticating. However, if I sign out of my app as part of that API call I get 302'd to /connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0. The API signout call is supposed to return the Identity Server endsession url for me to call but I don't get to see that data now due to the redirect, it appears that clearing my auth cookie causes the call to redirect. 

Is there an example you can point me or perhaps even just a diagram of the sequence of steps that need to be taken that'll clear up the process for me? 

This is my signout endpoint code. If I bypass the code between AAA and /AAA then the API call returns a serialised LogOut object and I can follow the Url property on it which takes me to /identity/connect/endsession?id_token_hint=etc and while I'm signed out of the IdentityServer I am not signed out of my app. However if I execute that code between the AAA tags then the response is 302'd to /connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0 and I lose the post logout redirect info.

        [HttpGet]
        [System.Web.Mvc.AllowAnonymous]
        [ActionName("SignOut")]
        public string SignOut()
        {
            var logOut = LogOut();
            return Newtonsoft.Json.JsonConvert.SerializeObject(logOut);
        }

        private LogOut LogOut()
        {
            var currentPrincipal = (ClaimsPrincipal)Thread.CurrentPrincipal;
            var idToken = currentPrincipal.Claims.FirstOrDefault(c => c.Type == Constants.IdToken);
            var id = idToken?.Value;

            // <AAA>
            var accessToken = currentPrincipal.Claims.FirstOrDefault(c => c.Type == Constants.AccessToken);
            var refreshToken = currentPrincipal.Claims.FirstOrDefault(c => c.Type == Constants.RefreshToken);
            
            Revoke(token, Constants.AccessToken);
            Revoke(token, Constants.RefreshToken);

            var owinContext = HttpContext.Current.GetOwinContext();
            var authentication = owinContext.Authentication;
            authentication.SignOut();

            CookieManager.RemoveCookie();
            // </AAA>

            LogOut logOut;

            if (idToken != null)
            {
                var logoutRedirectUrl = ConfigurationManager.AppSettings[Constants.LogoutRedirect];
                var logOutUrl = $"https://localhost/identity/connect/endsession?id_token_hint={idToken.Value}&post_logout_redirect_uri=https%3A%2F%2Flocalhost%2FSite1%2FRender";

                logOut = new LogOut
                {
                    Success = true,
                    Url = logOutUrl
                };
            }
            else
            {
                logOut = new LogOut
                {
                    Success = false
                };
            }

            return logOut;
        }

        private void Revoke(string token, string tokenTypeHint)
        {
            if (string.IsNullOrEmpty(token)) return;

            var authority = OpenIdAuthenticator.Authority;
            var client = OpenIdAuthenticator.ClientId;
            var secret = OpenIdAuthenticator.ClientSecret;

            var httpClient = new HttpClient();
            httpClient.SetBasicAuthentication(client, secret);

            var postBody = new Dictionary<string, string>
            {
                { Constants.Token, token },
                { Constants.TokenTypeHint, tokenTypeHint }
            };

            if (!authority.EndsWith("/")) 
                authority = string.Concat(authority, "/"); 

            var httpResponseMessage = httpClient.PostAsync(new Uri(new Uri(authority), OpenIdAuthenticator.RevocationEndpoint), new FormUrlEncodedContent(postBody)).Result;
            if (httpResponseMessage.IsSuccessStatusCode) return;
            var result = httpResponseMessage.Content.ReadAsStringAsync().Result;
            if (string.IsNullOrEmpty(result))
                throw new Exception(httpResponseMessage.ReasonPhrase);
            throw new Exception(result);
        }

**Comment by josephdecock** [comment]
Sure, we have a sample [here](https://docs.duendesoftware.com/identityserver/v6/samples/clients/#net-48-clients).

The way that logout works is, you need to [call sign out](https://github.com/DuendeSoftware/Samples/blob/a74365eac1839a220229c8632ce7ea6ecdf6ddea/various/clients/Owin/Mvc/Controllers/HomeController.cs#L113) on both the oidc and cookie auth schemes. The goal is to both delete your session cookie at the application and invoke the oidc end session endpoint.

When you call sign out passing the cookie scheme, that sets the appropriate headers to delete your session cookie. And when you pass the oidc scheme, that redirects to the endsession endpoint for you. As you see in the sample, you can pass both in one call.

When you redirect to the end session endpoint, the owin implementation of oidc unfortunately doesn't automatically add the id token hint, so you have to [set that yourself](https://github.com/DuendeSoftware/Samples/blob/a74365eac1839a220229c8632ce7ea6ecdf6ddea/various/clients/Owin/Mvc/Startup.cs#L53).

And you'll have to keep track of the id token as well. In the sample, we do that just by saying SaveTokens = true in the configuration.

**Comment by nhumby** [comment]
Thank you again Joseph, I really appreciate the help. If you don't mind me picking your brain, can you think of any mechanism available where in a scenario of three related apps in a suite all secured by an instance of IdentityServer6 where one of them is able to determine whether a specific user is currently authenticated against either of the other two? Back channel logout is not an option unfortunately as our customers can choose to use other IDP's that don't support it. I've been asked to optimise our single logout so that only those apps the user has a valid cookie for (or a related cookie that they could be silently logged in with) . Cookies are of course shielded from view of other apps, and session variables won't have the same lifespan as cookies. I tried using AJAX calls to the other sites and check for 302 or 401 responses but the browser actually intercepts the 302 and silently signs the user in before returning a 200, d'oh! Is there another way that you know of?

**Comment by josephdecock** [comment]
The optimization that you are after is already built in to IdentityServer. IdentityServer's session ticket maintains the list of client ids that are participating in that session, and uses that list in the end session endpoint to filter where it sends logout requests to only include clients that are part of the session.

**Comment by nhumby** [comment]
Ok great, thanks!
