### ISSUE TITLE
Schema from IdentityServer 4 v3

### ISSUE THREAD

**Issue by imharry4u** [DuendeSoftware/Support#564]
we tried to Upgrade IdentityServer4 (version 3.0.1.0) to Duende Identity Server 6.0.
I would really appreciate if you an help us with this.

    1.We created a new IdentityServer6 project with the EntityFramework integration already added by ‘dotnet new isef’
    2.Tested with client and we did got AccessToken. Works Perfectly.
    3.We restore our existing_IdentityServer_DB on DEV server.
    4.Used SQLServer reference, change the connection string to existing_IdentityServer_DB.
    5.Updated the schema changes including the new tables as required for ID6.
    6.Welcome screen and discovery document shows up successfully connecting to existing_IdentityServer_DB.
    7.Successfully Connect Client / postman and return accesstoken and userinfo.
    8.Question : As we upgrade from Identity Server 4, we have few old tables which are replaced with new tables with duende identity upgrade, so can i delete those old tables, i have attached the sceen shot of the [tables.](url)
    
![Screenshot 2023-03-10 102508](https://user-images.githubusercontent.com/18617947/224367552-237e75f0-4e43-44e5-82e1-e36e3ed8ce7d.png)

**Comment by josephdecock** [comment]
The reason that the table structure is different is that between IdentityServer4 v3 and v4, there was a pretty big change to the way that scopes and resources are modeled - ApiScopes were promoted to be its own top-level configuration. We document those changes [here](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v3_to_dis_v6/). If you've migrated all the old configuration data into the new schema, I don't see any reason to keep the old schema around - certainly IdentityServer doesn't need it anymore.
