### ISSUE TITLE
How to limit user access to different Clients?

### ISSUE THREAD

**Issue by jdaigle** [DuendeSoftware/Support#568]
**Which version of Duende IdentityServer are you using?**

Latest

**Which version of .NET are you using?**

.NET 7

**Describe the bug**

We are designing an application in which only certain users should be able to have access.
The application has its own Client registered with Identity Server, but we want to limit which users are allowed to request authorization for that client.

It doesn't seem like there is any existing service that we can easily hook into as part of the authorization request flow.

**Comment by StuFrankish** [comment]
> Typically, I would implement this as an authorization policy within each client application. The permissions and roles that a user has are typically specific to each application, and so it is usually best for each application to control that data.
> 
> In other words, IdentityServer always tells your applications that a particular user logged in, and then the application can make its own authorization decisions.

This is precisely how we've handled this in our line of business applications.
Identity Server only cares that you are who you say you are - it's the client app that's responsible for acting on that information, which we typically handle by throwing unauthorised users back to the `AccessDeniedPath` set when calling `.AddCookie(...)`
