### ISSUE TITLE
ServerSideSessionCleanupHost throws exception occasionally

### ISSUE THREAD

**Issue by JoyDJ** [DuendeSoftware/Support#569]
Version of Duende IdentityServer : 6.1.2

 .NET : Core6

**Description**
### We noticed now and then that the below exception is getting logged during the server session cleanup time.

`2023-03-03 15:03:13.846 -09:00 [DBG] [Duende.IdentityServer.Services.DefaultSessionCoordinationService] [] Due to expired session, invoking backchannel logout for subject id "bd3016e3-e49a-451c-ac63-7d44abacbc40" and session id "5FDD4A593D8F6F5939F1C54C894BBF1B"`

`2023-03-03 15:03:13.854 -09:00 [DBG] [Duende.IdentityServer.Services.LogoutNotificationService] [] Client back-channel logout URLs: "http://localhost:88/bff/backchannel"` 

`2023-03-03 15:03:13.864 -09:00 [ERR] [Microsoft.Extensions.DependencyInjection.ServerSideSessionCleanupHost] [] Exception removing expired sessions: "Object reference not set to an instance of an object." `

Looking through the source code, it seems the exception is being thrown from **DefaultSessionCoordinationService**

` await BackChannelLogoutService.SendLogoutNotificationsAsync(new LogoutNotificationContext
                {
                    SubjectId = session.SubjectId,
                    SessionId = session.SessionId,
                    Issuer = session.Issuer,
                    ClientIds = clientsToContact,
                });`

### Below are the logs when there are no exception/ clean and notification works as expected

`2023-03-13 13:19:48.220 -08:00 [DBG] [Duende.IdentityServer.Services.DefaultSessionCoordinationService] [] Due to expired session, invoking backchannel logout for subject id "bd3016e3-e49a-451c-ac63-7d44abacbc40" and session id "CD944F67668BEA710B526D532AB92B71"` 

`2023-03-13 13:19:48.224 -08:00 [DBG] [Duende.IdentityServer.Services.LogoutNotificationService] [] Client back-channel logout URLs: "http://localhost:88/bff/backchannel"`

`2023-03-13 13:19:48.274 -08:00 [INF] [Duende.IdentityServer.Services.KeyManagement.KeyManager] [] Active signing key found with kid "XXXX" for alg "XXX". Expires in 15.22:58:33. Retires in 22.22:58:33` 

`2023-03-13 13:19:48.437 -08:00 [DBG] [Duende.IdentityServer.Services.DefaultBackChannelLogoutHttpClient] [] Response from back-channel logout endpoint: "http://localhost:88/bff/backchannel" status code: 200`

**To Reproduce**

Unable to reproduce

Unfortunately, exception stack is not getting logged. Appreciate any guidance

**Comment by josephdecock** [comment]
I believe you are seeing issue #420, which we fixed in the [6.2.2 release.](https://github.com/DuendeSoftware/IdentityServer/milestone/36?closed=1)

Can you try upgrading to the latest version and see if that resolves your issue? As part of that work, we also improved the logging when the cleanup host fails, so if there is some other issue, we'll at least get a proper stack trace.

Release info and upgrade notes for 6.2 are [here](https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.1_to_v6.2/). The good news is, there are no changes in the storage layer/database, so the upgrade from 6.1 is an easy one.

**Comment by JoyDJ** [comment]
Thanks for getting back to me. Will try to upgrade from 6.1

**Comment by josephdecock** [comment]
Okay, I'll close this issue for now then. If upgrading doesn't resolve the problem, please reopen the issue. Thanks!
