### ISSUE TITLE
Changing the base path of identityserver

### ISSUE THREAD

**Issue by Thomas-X** [DuendeSoftware/Support#57]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
.NET 6.x.x

**Describe the question**

We have identityserver3 running and slowly rewriting it to identityserver6, but I can't find an easy way to change the BasePath that IdentityServer runs on. 
I noticed `IServerUrls` / `DefaultServerUrls` but I'm having a tough time setting up something that doesn't feel hacky. Any guidance is much appreciated

**Comment by brockallen** [comment]
Did you look into using MapPath in the pipeline?

**Comment by Thomas-X** [comment]
It seems MapPath is for .NET Framework, but we're running on .NET Core. My usecase is for having the idsrv endpoints running on a different base path. 
e.g: 
`/.well-known/openid-configuration` -> `/idsrv/.well-known/openid-configuration`. 
`/connect/authorize` -> `/idsrv/connect/authorize`
etc..

I got it working using the following 'hack' but I'd really like to implement a proper solution 

```csharp
public class BaseUrlOverrideForIdentityServerHack
{
    private readonly RequestDelegate _next;

    public BaseUrlOverrideForIdentityServerHack(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context, IEnumerable<Endpoint> endpoints)
    {
        foreach (var endpoint in endpoints)
        {
            if (!endpoint.Path.StartsWithSegments("/v2"))
            {
                endpoint.Path = "/v2" + endpoint.Path;
            }
        }
        context.RequestServices.GetRequiredService<IServerUrls>().BasePath = "/v2";
        await _next(context);
    }
}

// Program.cs / Startup.cs

app.UseIdentityServer(new IdentityServerMiddlewareOptions()
{
    AuthenticationMiddleware = x =>
    {
        app.UseAuthentication();
        // extremely hack-y.
        // very important to set it here so that the endpoints are 
        // overwritten BEFORE triggering the identity server middleware.
        app.UseMiddleware<BaseUrlOverrideForIdentityServerHack>();
    }
});
```

Apologies if I'm missing something obvious -- been at this for a few hours now.

**Comment by brockallen** [comment]
Ok, yes -- MapPath was the older API. I think in ASP.NET Core, Map allows you to do the same. Have a look?
