### ISSUE TITLE
Linux client Windows Authentication problem

### ISSUE THREAD

**Issue by evgeny-cbs** [DuendeSoftware/Support#570]
**Which version of Duende IdentityServer are you using?**
v.6.1.7

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
We setup Identity Server to allow windows Authentication. 
In startup we have such code:
`builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();`
Windows client can login without any problem.
When Linux client do login using windows Authentication it always get 401.
Both server and client are connected to the same Active directory domain.

When I run Identity server in debug I see inside ExternalController such problem:
```
var result = await HttpContext.AuthenticateAsync(AccountOptions.WindowsAuthenticationSchemeName);
if (result?.Principal is WindowsPrincipal wp)
{
....
}
```
And result?.Principal is always null for Linux client.

**To Reproduce**
Just try to login using Windows Authentication through Linux client

**Expected behavior**
Client can pass login successfully

**Log output/exception with stacktrace**

```
result?.Principal is null
```

**Comment by josephdecock** [comment]
This sounds like a problem with the way you're using AddNegotiate, not really something that is specific to IdentityServer. Can you start by creating a standalone program that doesn't involve IdentityServer just to prove that you can authenticate with this handler? Once you have that working (we can help you integrate a working authentication scheme with IdentityServer. For example, I notice that you're setting the Negotiate handler as the default scheme - that should actually be a cookie scheme instead. But again, get the negotiate handler working separately from IdentityServer first.

**Comment by brockallen** [comment]
Any update on this issue @evgeny-cbs?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
