### ISSUE TITLE
Custom middleware

### ISSUE THREAD

**Issue by apetrut** [DuendeSoftware/Support#572]
Hi,
I am using Duende V6 with .NET Core 6.

I have created a custom middleware that inspects the request body and replaces this body:

![image](https://user-images.githubusercontent.com/13006228/225333961-2cbd4ad9-725e-4b9e-9951-f1ed51bd4ec7.png)

with this one:

![image](https://user-images.githubusercontent.com/13006228/225334163-4833364b-3123-4fb1-8b23-9890f9ac64f7.png)

However I get the errors below when trying to get a token using Postman:

![image](https://user-images.githubusercontent.com/13006228/225333723-5cc3640c-f5af-4af9-91e6-7dd88f26c5db.png)

Is there a way I can inject this middleware before PostBodySecretParser or ClientSecretValidator? 

My aim is to change the grant type from "client_credentials" to "password" at runtime and get a token after that.

**Comment by apetrut** [comment]
I want to avoid using the client credentials grant and transform these requests to use the password grant so that I don't need to validate any client credentials at all.

**Comment by josephdecock** [comment]
If you're not validating credentials, I don't see how the tokens you're producing could add any value to the system from the point of view of security. But if you really want to do this, like I said, you can run middleware in whatever order you like.
