### ISSUE TITLE
Disposed classes during configure of ConfigureAuthenticationOptions

### ISSUE THREAD

**Issue by f-waffenschmidt** [DuendeSoftware/Support#575]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
.Net 6

**Describe the bug**
During challenge of login the access of an already disposed object fails
![image](https://user-images.githubusercontent.com/100243249/225905926-3603c3e9-b649-4f6b-a4dc-60085354f31a.png)

The Injection of `DynamicProviderOptions` and  `DynamicAuthenticationSchemeCache` will be resolved via `_httpContextAccessor.HttpContext.RequestServices.GetRequiredService<DynamicAuthenticationSchemeCache>();`
refer [here](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Hosting/DynamicProviders/Configuration/ConfigureAuthenticationOptions.cs#L37)

Why is the `IHttpContextAccessor ` used to get the `IServiceProvider`. What happens if there is some configuration running without HTTP Context. Does it make sense to inject the `IServiceProvider` direct to the constructor? As far as I analyzed the code there is no further need of `HttpContext` to configure other things.

What I'm facing here is access to a disposed object. But this happens just because of the usage of  `HttpContext.RequestedServices` (as far as I know). Nevertheless a null pointer is also possible in case HTTP Context is not set.

**To Reproduce**
I think this is not really reproducible in a sandbox.

**Expected behavior**
Challenge works, usage of `IServiceProvider` instead of `RequestedServices` from `HttpContext`

**Log output/exception with stacktrace**

![image](https://user-images.githubusercontent.com/100243249/225909172-c3a6ca2c-c151-479b-af4b-748cb5f60937.png)

**Additional context**
We challenge the login in a prior middleware instead using the challenge from identity provider.

**Comment by josephdecock** [comment]
> Hi, thanks for the bug report. We have been planning to fix this in our upcoming 6.3 release, in late spring/early summer. Do you need this sooner? We could consider back porting a fix to the 6.2 branch.

Work on this issue is tracked in #874.

**Comment by f-waffenschmidt** [comment]
Hi @josephdecock,

would be great, thanks. Because I don't know how many times this error  is thrown, it feels bad to keep the current version running as it could fail every time after reboot or something. A restart helps most of the times to get it running again.

**Comment by brockallen** [comment]
Since we have an existing issue for this problem, can we close this one?
