### ISSUE TITLE
Logout working on Firefox but not Chrome

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#578]
**Which version of Duende IdentityServer are you using?**
6.3

**Which version of .NET are you using?**
7.0

**Describe the bug**

Sorry, it's me again with another logout question. I implemented the suggestions in #561 and it's appeared to work as I was using Firefox to test it with. Testing it out with Chrome it does not appear to work. 

I have four apps secured by Identity Server. One of them (SalesPortalUX) is the main entry point controlling the suite, the others are DocumentGenerator, SalesPortalAdmin, and GuruRuntime. It contains the logout button. When the logout button is clicked the following takes place:

1. JQuery sends a GET request to /DocumentGenerator/SignOut/Index. This returns a 302 in both browsers redirecting to /salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

2. JQuery sends a GET request to /SalesPortalAdmin/SignOut.aspx. This returns a 302 in both browsers redirecting to /salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

3. JQuery sends a GET request to /GuruRuntime/tools/SignOut. This returns a 200 in both browsers.

There is then the following traffic recorded
	
FireFox
	- GET https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This is 302 redirected to 
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6ol5NYbc_g6Eht__PQJhZFixIuOOLN77w5esrNtmRA6ygkbefHLRnKJA7yE6u7sjp5SNHDxR5cNXtkybmriVoOtJgWWucUGErXyi74baHrK8vsLcl-P3XJXf65Q0eshu_UFteHugx9AHQRPJHP9tmt2TRqqjEKaFbTSULCIKkRHQUPI88pYscHpf7mhbpw7SWsGX7-4dXY0Mq3060NObNGuxjQ3bS0C0SoOSJFBGDBrIMnP4MpK-ttuhk3LECA08nzKSWCzszffpvVcRj1ohlrNCHWhkEJNJ5dq4ipYTtoBQg2HRxef8McqmnjWLxcnCvGVwXE7dZQr2L-TZ5dZLwfAbt4vcGp05CXXUYgmS8M4FIwXzNqjswLAHHm_JUZxVUtAFFSIIgnWfkEalhRFH3oxfXX-_jHf18kSaq--Ee3eKrV1PcxRJ6pO6aoBG0tRJ1wBgBubZG4smbNqhFuuGVRX1X7KYmhmh5BiOj-lB4ZSPGhviAzgaatwm227UMNc4TG-Df0CM6q3MDULaMH6bTBz
		This returns 200.
		
	- https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This is 302 redirected to 
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6pX5t9nROU3Y0fv9OZPEIEHjVPuJhu-u_FUizaSTKVn_Y2ndvKonQfJEp8gVFgQusi_7HiyETY15HNaqLOpF2Zk7N8u6e1Rnt9uFCtkRTmkpUCpzUbRqdk9aSjAztQHaqXsgckPejKq5f5_oasn57MY0hCO6uHC8K5SffHoczWap6grEcijtshpUJv4dVpW8sUXZfO_8TUrdaO7ly45AxGnRXrCZLg3Qp3zHteXUcgtKODP-fDCS2-y209cnWW4RYFcnDgSUNU6wnFx_fvWK-W3bvK7dehqM5ASucZoSeZZzCgScl_CWVoALtZVwth1_jR5BRHCuXKlIWoXwxRhn7M709pFcc1XSX8fIyUskZ8cHVZcxgjx1twNIYxyVhf-Ufs_CuilmrR9yaKSzHAQkyNBmjWqKnr4yfsyhK1jn_WI2GazNKvX0gi0ohEbyk47nCXt3WuFo8mEcM21fzCl6oTpHX_KLNmvu7dz9ershM37f7i6skvPF6f5WGaLqeCWIlFi8L7P75_Uu6N6qYAfMIEn
		This returns 200.
		
	- GET https://localhost/SalesPortalUX/api/Application.SalesPortalUX/WebService/LogOut
		This gets 302 redirected to 
		
	- GET https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This gets 302 redirected to 
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6pbEdGYKhtkv4nMZE14PrpTRG0ozKzt5AWo5_iMHGPXBu9pfemTWz-kh-MjmoY3b0DU2BT3pY98a65geILAqCgrmGjTSGLk7xRk3jfhWenPW70t_iaSeNToHhcZ1Zhudni4JE7yLFFqPzydqwW-4lX5nhqOtFiq_4HFGTuf8ml8BpixuF0JU1bORBeyWPBahT2eVGO9MV4pE1nJ1b9Bc8gwxdxUQKlxj3_a9fqQDALPcLFAaq1XewGM4xtGX0NmcAuF8mHoF9t8GQtg7yCHOW4gy1LCpB7hJZlrfwCJzouEnfAwxSJlh83ExXTT7cl2fEZ3G1fxo8TZyG15qrT4VwGMs-X8_zYbH-qGU6NWIQfUanggNxG3Dx40xtDhPPRCcjRHMwA8V2-h99F8iq40VLbU0zup5twNV8jwOwklMptzS0YR4EGXTG8Fye_obPELVuWSXoxPVIJw0jDST1z5Nasnnnrgtm1lCE-2upmEbU8e8rUxjL0OguSwMSkbZxJbfAuNcvvY5zOWLWnm9einZnQJ
		This returns 200 and appears to contain the "Would you like to logout of IdentityServer?" prompt page.
		
	- GET https://localhost/SalesPortalUX/api/Application.SalesPortalUX/WebService/LogOut
		This gets 302 redirected to https://localhost/salesportalidentity/connect/authorize?client_id=CPQ.SalesPortalUX&redirect_uri=https%3A%2F%2Flocalhost%2FSalesPortalUX%2FRender&response_type=code&scope=openid%20profile%20offline_access%20CPQWebServices&code_challenge=WN3yKZpBpHbteJps65lg16HLYluiDYN8EDgLGxfLcBY&code_challenge_method=S256&state=OpenIdConnect.AuthenticationProperties%3D47l3B7XVVYpo3bhqbbLuOsqa8VaRSAcASx8-OFTjPU2gxpRtjQxW9V2eHJosP3lTdVCe040bFozbtLmCmHK1CtzTj6PNCsiNA1fGQXABLXtX-BCwqlfDDjojumVA-bJEnqW-ztclNdDkfixNqKithhQyBspM3FylirpWKp7S8fb527Xhv03r6_wraU8qqMCxWRQBu57MyysAvmARC_2xGiELi-qVK9mm-JzUkI21VyopVQDRD9VC_QKbQ1x3WobLlgf5elTUe8Ac9VMUaDI2WDEsaokoKzFonUZ0j2aecuxi_XF6gzCX1ioEeSDJUvDHum5RyVilpRDC_azasWwr-WI6XCNHnhdls-39aW_sBUNQVbLAaZvdvd086k9g6QxD&response_mode=form_post&nonce=638150123179256882.MGZjM2U4MDUtMTk0Ny00OGE5LWJiNzQtNjMxNWQxYTE2YTJiNzNlYTBjNjgtODMyMi00NjUwLWE3YTItNDY0M2E1MDg2NmNk&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		but what appears in the next browser history entry is
		
	- GET https://localhost/salesportalidentity/connect/authorize?client_id=CPQ.SalesPortalUX&redirect_uri=https://localhost/SalesPortalUX/Render&response_type=code&scope=openid profile offline_access CPQWebServices&code_challenge=WN3yKZpBpHbteJps65lg16HLYluiDYN8EDgLGxfLcBY&code_challenge_method=S256&state=OpenIdConnect.AuthenticationProperties=47l3B7XVVYpo3bhqbbLuOsqa8VaRSAcASx8-OFTjPU2gxpRtjQxW9V2eHJosP3lTdVCe040bFozbtLmCmHK1CtzTj6PNCsiNA1fGQXABLXtX-BCwqlfDDjojumVA-bJEnqW-ztclNdDkfixNqKithhQyBspM3FylirpWKp7S8fb527Xhv03r6_wraU8qqMCxWRQBu57MyysAvmARC_2xGiELi-qVK9mm-JzUkI21VyopVQDRD9VC_QKbQ1x3WobLlgf5elTUe8Ac9VMUaDI2WDEsaokoKzFonUZ0j2aecuxi_XF6gzCX1ioEeSDJUvDHum5RyVilpRDC_azasWwr-WI6XCNHnhdls-39aW_sBUNQVbLAaZvdvd086k9g6QxD&response_mode=form_post&nonce=638150123179256882.MGZjM2U4MDUtMTk0Ny00OGE5LWJiNzQtNjMxNWQxYTE2YTJiNzNlYTBjNjgtODMyMi00NjUwLWE3YTItNDY0M2E1MDg2NmNk&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This returns a 200 response.
		
	- POST https://localhost/SalesPortalUX/Render
		This is 302 redirected to 
	
	- GET https://localhost/SalesPortalUX/api/Application.SalesPortalUX/WebService/LogOut
		This is 302 redirected to
		
	- GET https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This is 302 redirected to
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6qS0lnEyfNTxnUYjVZSPshWzVep_Xf0ziMN4hSInS0EuGvMY6M4ENyJ1Dc1H-VOWvdaQoq36WIT-PKDhBy0hOmLzXB1bnrlXteWJhD1C0I-oO5g-urCZ1iVfjR26pC6HPrPmFFO8-vwocd4EFl2ySFAIY-yYXvCOuzyEsHOnyTnmKCDqXoEyeBUDKkBnyNB6z8GR31goDDDptOZlknvsHAZSR2tTUDuh1UxAjNGoX4ipa7EXD6UuoNlqAdAsRX_FOLytMFXNd4HA5HBos4lGECpv3oXjgcTvFNer36GG1sovq_58DYNmSJjkdjYvhgL8cJ0hIS0sAfy1clPHG8F29JNZJaZhj2kjgs6qC5iKmXtiUL__2xpfexb2s6zy49OyPfqpCcIep4JjhxmAHkSC5XW3NK6E_0wdVWwoaVt48nO4KhZlRyM1b3i1pVfdt5jIGsI8Xg1RVr6luouAGcEkSez70VF8jDB_4WotmicH4OjgG9Fiq2seO-0NfDv4sMZnCTqwjRUohxRvXjbhjDr-5N3
		This returns 200 and appears to contain the "Would you like to logout of IdentityServer?" prompt page.
		

Chrome
	- GET https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This gets 302 redirected to 
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6rVGKdFyKftX4-sykq7WLAwvhl3TgmmESWfcEstyfF_EUQBZEUb8bxJxnoWiz64itqtImW-EkS_CSg_3v09ST9VEZVdwtsqXwGuBqp7zobJUSB2SjTaTvJkdvODjE8o13IBw7MNptrRu36hupSttAih8Lez7ObPWoimKq4-xWiPe79-9yUheSmI2UYoZDqULdUslG7F2I8POvLY7r8o_G3wsDtY46SoCP7dDwS9xIIBEGDpaJhyDHBnwigLsDfIJsKQ7N-zNVmWv5uQoRmsYqzkOFRkUslvlaZfA8lb7queMw6qATwCyi485wvoGIzzpfxQNEuvbKIq5sy6-BuF774TsEwqJ7_LRz124ljTW-80FREysc3_FpcWYL4WvniStAo4t2c3df9t-BN9RbnQj4Rz4s1j1QhmNfhuDPyRKDOrWKop2mSXklLQJed8qN9hOZS7T287lkaB9QpJkXBPt0QJK3WKuK0uvLhkADBj0L83x_oeBwhMgx2BxTehVaJBY7NMviIanrqa1YK1v7LkbAnH
		This returns a 200 response.
		
	- GET https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This gets 302 redirected to 
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6qXctngD4Mf4xlpwJ2vaU5lsxGUAI-9SFwZ6B2JRBWoKTV40VUNZXfhDSpi_pXrwOMDW-r8g_yWbZVODahGGEF6-aFdp9iZP85WNamyOVPocvC5RJO-k2RfrJKq_u2EUBTCCsXkpwEailt7XF1rEH9RIYbiBstC0nahaNVQD6P1rXWZAu1WS-5rN8ygqZow_L11rtk3Y7V_QJZgC32DDfnxLo2nEoL2gKWnJdQp4Qcc0Mqy1DtaJA2wxatvv7Rj12rpsoHuynYq3lkVrg2w-qlRzHF7_tszJBQfFZ5rEsU9wPgcDMYnPRHl0Z-D9VP-6ENmj0Dg9ZwxDS0z5I-wirSpIjL3tZAEh56HnrWFC-CkD11ko1jokqNH1kAx2teKVS1N5WgsNuxybHcXLGXXjzZZ3abrPiSJxPFdUf58ffM4aUp8bJsFtxWYn_DXC1E-i2xhZj3YY-AN6DrviI6QX8HSgpmcqnmbBt1KQyAss0veSY4-CYDaqUex0oXJljFUnnNPtK8tM5ELlHS-hT7zuCzU
		This returns a 200 response.
		
	- GET https://localhost/SalesPortalUX/api/Application.SalesPortalUX/WebService/LogOut
		This gets 302 redirected to 
		
	- GET https://localhost/salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This gets 302 redirected to
		
	- GET https://localhost/salesportalidentity/Account/Logout?logoutId=CfDJ8KfzUXZy14RAlU8p4ZepU6o3jEC22PCI3eC1bHlaReW_aNgSTnjGfYdayWW5tQX5Dh7aFlCaWvGKCJ5Kz9qXysFo08jdKKJA9zikPSo2J_bLYj1W6cV8oFVy8b1mPtA8cfRaEkPHok3S5cPOTTm4uSKKjFk3vbEaN4RQszAs0VM5SSxkKUCP1ncoFU4KrZSyZPrcuAwduTmD-ZZzHef9QfnevfIDBzaTtBWLIzx5ip7OK6zyFZT87cdkd_cZx0midvDjs-6kX_-aUZgpID72jydZZjyfq97m64StYqPzvJpx101onrT0x_HTKaY93fFVEg6ePBg4OIv9KdypH_epVbm6VLoRhp6c97CE4Qt9zXz7n9IUFoUOTZ3ds8HYhbrX4Cil-ZhGoTCbaVq-0m7VVKq8EEzTdMQYKqqyjyYzuvxjt1yWZ0KK4VMCRHtQJ0Be24y_mrieWH0DXD97PHH0bKbByqYBO_-FV_xbMpszvBr8s1seHg009TakICiVuFsjTkBVUt6ui35Vd9F9HOGmZE2l9SO7GBs5XZOm0V8lovOO
		This returns a 200 response.
		
	- GET https://localhost/SalesPortalUX/
		This gets 302 redirected to 
		
	- GET https://localhost/salesportalidentity/connect/authorize?client_id=CPQ.SalesPortalUX&redirect_uri=https%3A%2F%2Flocalhost%2FSalesPortalUX%2FRender&response_type=code&scope=openid%20profile%20offline_access%20CPQWebServices&code_challenge=R0DAZaSHCJEAnZO6MGhgx2iszU3zuCfOyAU1lTJTsTY&code_challenge_method=S256&state=OpenIdConnect.AuthenticationProperties%3DGtTrUd9DcdZYvCNLY1M4k0JuPCdODVthTdRN6dArRM_FEm7mAulT1Y-LTMFMOeBhHRiyvDkpPWJEw9qtY2PmMAUO609zXAkd6zUxMlbcmQi8vrObM0PdZvUnOaKfCpqkKlaVkanrZc3wxz6cZohYtFg0zz5pSEqkqAs3eztCqtHczeVtvu-eTNUL6lCO7qYFkLMTjGM8066sgUSTifdxSRpsCW0bfoDpBpkfhjOLUvDYj_T3Fi2APLou_J-By4htZZRjSGJ3ck_X85UYJ7LfYE2JWkIvFXs4Ediy3THJZGOEXCrXDzJWDNVMm4Ij4H--&response_mode=form_post&nonce=638150116737016936.NGVjODVhMmUtZDk3ZS00MmVjLTlmZDItMGRjNzc1NWNlYzM2MjRjYzZjMzItN2NiNC00ZWUxLWI3NjUtMzYxMmI4NDcyNjc3&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0
		This returns a 200 response.
		
	- GET https://localhost/SalesPortalUX/Render
		This gets 302 redirected to 
		
	- GET https://localhost/SalesPortalUX/
		This returns a 200 response and shows the main landing page for the re-authenticated user.

The logout prompt "Would you like to logout of IdentityServer?" only shows in FireFox, and once the user clicks Yes then they are signed out of all the sites and out of Identity Server. The logout prompt page never shows in Chrome, instead it loops back into the landing page.

It gets weirder, my supervisor has the same code running locally and on a remote server. Using the same web clients to connect the remote server logout works in his local Firefox but not his local Chrome. On his local machine, logout works fine in both.

We're at a bit of a loss as to what's going wrong. The server side code for these endpoints/pages is listed below:

/DocumentGenerator/SignOut/Index
```
        [AllowAnonymous]
        [HttpGet]
        public void Index()
        {
            Session?.Abandon();
            Request?.GetOwinContext().Authentication.SignOut();
        }
```

/SalesPortalAdmin/SignOut.aspx
```
        internal void SignOut(string errorMessage = null)
        {
            if (FederatedAuthentication.SessionAuthenticationModule != null) FederatedAuthentication.SessionAuthenticationModule.DeleteSessionTokenCookie();
            if (FederatedAuthentication.WSFederationAuthenticationModule != null) FederatedAuthentication.WSFederationAuthenticationModule.SignOut(false);
            if (HttpContext.Current.Session != null) HttpContext.Current.Session.Abandon();

            HttpContext.Current.Request?.GetOwinContext().Authentication.SignOut();
            var owinStartup = ConfigurationManager.AppSettings["owin:appStartup"];
            var authority = ConfigurationManager.AppSettings["oauth:Authority"];

            if (!string.IsNullOrWhiteSpace(owinStartup) &&
                owinStartup.Contains("Owin.Security.OAuth.Salesforce") &&
                !string.IsNullOrWhiteSpace(authority))
            {
                authority = authority.EndsWith("/") ? authority : string.Concat(authority, "/");
                var response = HttpContext.Current.Response;
                response.StatusCode = 301;
                response.StatusDescription = "Moved Permanently";
                response.RedirectLocation = string.Concat(authority, "auth/idp/oidc/logout");
                response.Flush();
            }
            else
            {
                HttpContext.Current.Response.Redirect("/");}
            }
        }
```

/GuruRuntime/tools/SignOut
```
        public JsonResult SignOut()
        {
            var success = true;
            try
            {
                Session?.Abandon();
                var cookieName = ConfigurationManager.AppSettings["Security:CookieName"];
                var cookiePath = ConfigurationManager.AppSettings["Security:CookiePath"];
                if (!String.IsNullOrEmpty(cookieName))
                {
                    Response.Cookies.Remove(cookieName);
                    var cookie = Request.Cookies[cookieName];
                    cookie.Path = cookiePath;
                    cookie.Expires = DateTime.Now.AddDays(-10);
                    cookie.Value = null;
                    Response.Cookies.Add(cookie);
                }
                // Clear all server side cookies
                Request.Cookies.Clear();
            }
            catch (Exception exception)
            {
                _logger.Error($"Error logging current user out, Error is: {Environment.NewLine} {exception}");
                success = false;
            }

            return Json(new { success = success }, JsonRequestBehavior.AllowGet);
        }
```

/SalesPortalUX/api/Application.SalesPortalUX/WebService/LogOut
```
        [HttpGet]
        [System.Web.Mvc.AllowAnonymous]
        [ActionName("LogOut")]
        public void LogOut()
        {
            var performanceCounter = PerformanceCounter.Create("WebServiceController.LogOut()");
            try
            {
                var currentPrincipal = (ClaimsPrincipal)Thread.CurrentPrincipal;

                var idToken = currentPrincipal.Claims.FirstOrDefault(c => c.Type == Constants.IdToken);
                var id = idToken?.Value;

                HttpContext.Current.GetOwinContext().Authentication.SignOut("oidc", "cookies");
            }
            catch (UnauthorizedException exception)
            {
                var httpResponseMessage = new HttpResponseMessage(System.Net.HttpStatusCode.Unauthorized)
                {
                    ReasonPhrase = exception.Message
                };
                var httpResponseException = new HttpResponseException(httpResponseMessage);
                Log("Failed to LogOut.", exception);
                throw httpResponseException;
            }
            catch (Exception exception)
            {
                throw LogAndThrow("Failed to log out.", exception);
            }
            finally
            {
                performanceCounter.Finish();
            }
        }
```

Do you have any ideas or tips on how to fix this?

Firefox traffic recorded:
![logoutfirefox](https://user-images.githubusercontent.com/3273917/226696349-101dc877-7947-49ea-a145-20c31902fa70.JPG)

Chrome traffic recorded
![logoutchrome](https://user-images.githubusercontent.com/3273917/226696351-1e41259e-dc42-44d2-84cc-28aaa4d4155c.JPG)

**Comment by brockallen** [comment]
> JQuery sends a GET request to /DocumentGenerator/SignOut/Index. This returns a 302 in both browsers redirecting to /salesportalidentity/connect/endsession?x-client-SKU=ID_NET461&x-client-ver=5.3.0.0

It looks like you're making Ajax requests to trigger signout. This is now how the OIDC signout specs work -- they need to be requested from the top level browser window (e.g. via window.location redirects). Can you try that to see if you get better (and more correct) results?

**Comment by nhumby** [comment]
Thanks for the quick response Brock. Loading the signout endpoints in new tabs/windows has the expected results in early tests so far - thank you for the assist! Just to explain it, on clicking logout on the main app I am launching new windows which hit the signout endpoints of the other secured sites and then close themselves. Once done, the main app does its own signout and traverses via the IdentityServer's /connect/endession with an id_token_hint parameter which all goes very smoothly.

Is there a way for a client relying party to query from the IdentityServer which other clients a user is currently authorised for? It would be great to avoid spinning up a dormant application that hasn't been accessed or accidentally triggering the silent sign-in process just to call the signout endpoint. If we could somehow find a way of avoiding unnecessary signout calls to other clients it would be great. I know the IdentityServer has backchannel logout (which is a great feature!) but unfortunately our clients can choose to secure with other IDP's such as SalesForce or Azure AD and as they don't have that back channel logout feature we can't go with that. 
Also, I really want to get my head around this stuff better - if you can recommend any OIDC courses or certs I can go for more training I'd be very thankful. Unfortunately I missed your course in May 2022, I was living in hospital caring for my newborn daughter (who is now a completely healthy 10 month old).

**Comment by brockallen** [comment]
> Is there a way for a client relying party to query from the IdentityServer which other clients a user is currently authorised for

There's nothing in the spec(s) for this. You could always build something custom to enable this, though.

> It would be great to avoid spinning up a dormant application that hasn't been accessed or accidentally triggering the silent sign-in process just to call the signout endpoint.

I'm not following what you're getting at here.

> If we could somehow find a way of avoiding unnecessary signout calls to other clients it would be great.

IdentityServer already works this way, such that when the user signs out of IdentityServer it only notifies the clients that the user has already logged into during this session. It's done by tracking the list of client ids in the user's session data (in the cookie at IdentityServer) as each client makes an authorization request to IdentityServer.

> if you can recommend any OIDC courses or certs I can go for more training I'd be very thankful

We offer training and list up coming classes here: https://duendesoftware.com/training/iac#register

> Unfortunately I missed your course in May 2022, I was living in hospital caring for my newborn daughter (who is now a completely healthy 10 month old).

Congrats!
