### ISSUE TITLE
Valid refresh_token exchange on /connect/token endpoint returns 400 in 6.2.3 but works fine in 6.1.0

### ISSUE THREAD

**Issue by GirtsZemitis** [DuendeSoftware/Support#582]
**Which version of Duende IdentityServer are you using?**
6.2.3  

**Which version of .NET are you using?**
7.0  

**Describe the bug**
`/connect/token` endpoint returning 400 on existing refresh_token grants
Updated from duende identity server from `6.1.0` to `6.2.3` according to https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.1_to_v6.2/
Tried to use `/connect/token` endpoint with existing refresh token that was created before update, get 400 with stacktrace posted below
Tried to create new refresh token and then using it with `/connect/token` endpoint and everything worked out fine  

**To Reproduce**

1. Create duende identity server with 6.1 version
2. Run it and create persisted grant refresh token
3. Update duende identity server to 6.2.3
4. Try to use refresh token to get access token through  `/connect/token` 
5. Exception  

**Expected behavior**
1. Refresh token is backwards compatible and usable for exchange to access token.

**Log output/exception with stacktrace**

```
System.Security.Cryptography.CryptographicException:
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt (Microsoft.AspNetCore.DataProtection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore (Microsoft.AspNetCore.DataProtection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect (Microsoft.AspNetCore.DataProtection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect (Microsoft.AspNetCore.DataProtection.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Duende.IdentityServer.Stores.Serialization.PersistentGrantSerializer.Deserialize (Duende.IdentityServer.Storage, Version=6.2.3.0, Culture=neutral, PublicKeyToken=null: /_/src/Storage/Stores/Serialization/PersistentGrantSerializer.cs:111)
   at Duende.IdentityServer.Stores.DefaultGrantStore`1+<GetItemByHashedKeyAsync>d__21.MoveNext (Duende.IdentityServer, Version=6.2.3.0, Culture=neutral, PublicKeyToken=null: /_/src/IdentityServer/Stores/Default/DefaultGrantStore.cs:146)
```

**Additional context**

Please let me know if there is anything else I can help with. I am ready to provide more information or do more testing. Hope this is sufficient!

**Comment by brockallen** [comment]
It sounds like the data protection keys that were used to protect those records are no longer available. Do you configure a consistent store for your data protection keys?

https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/

**Comment by GirtsZemitis** [comment]
We are storing keys in Azure as per Microsoft documentation pointed from data_protection page in duende docs. https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0

But thanks for pointer! It is true that I also upgraded DataProtection related dependency!
`Microsoft.AspNetCore.DataProtection.Abstractions` 6.0.5 > 7.0.0

I will look into this more.

But the fact that everything works fine again after downgrading Duende(and DataProtection.Abstractions) would mean that those keys are still available, right?

Also tested that if I create persisted grant on 6.2.3 version and then downgrade to 6.1.0 that grant also has the same problem. Only works in its own version

**Comment by brockallen** [comment]
We do have other customers that upgraded fine with those records. So if you can easily repo it, you might need to debug further into it to find out where/why such a thing is happening.

**Comment by brockallen** [comment]
Also, is there any more detailed error message in your log at the point of the exception?

**Comment by GirtsZemitis** [comment]
Upon further investigations our issue seems to be related to this > https://github.com/dotnet/aspnetcore/issues/43682#issuecomment-1240990143


Thanks for the help and fast replies even if it's not directly related with duende software! I greatly appreciated it! 💯 
Maybe it would be valuable to put this in upgrade docs for the next person.

**Comment by brockallen** [comment]
Ah, I had forgotten about that issue -- sorry for not mentioning it.

@josephdecock Did we ever add anything anywhere to the docs about this issue?

**Comment by josephdecock** [comment]
> @josephdecock Did we ever add anything anywhere to the docs about this issue?

Yes, our upgrade docs have a [section on the data protection key application name issue](https://docs.duendesoftware.com/identityserver/v6/upgrades/is4_v4_to_dis_v6/#step-7-verify-dataprotectionkey-application-name).

**Comment by GirtsZemitis** [comment]
This also happens in .net 6 to 7 upgrade
https://github.com/dotnet/aspnetcore/issues/43682#issuecomment-1240990143
```We changed ContentRoot between 5 and 6 and then again between 6 and 7 to try to "fix" the 5 -> 6 change.```

I was following this upgrade doc > https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.1_to_v6.2/

**Comment by GirtsZemitis** [comment]
https://github.com/DuendeSoftware/docs.duendesoftware.com/pull/268
