### ISSUE TITLE
Is it possible to use OKTA just for MFA

### ISSUE THREAD

**Issue by fdagdagan** [DuendeSoftware/Support#583]
**Which version of Duende IdentityServer are you using? 6.1.7

**Which version of .NET are you using?** .NET 6

Hi,

We have a requirement just to use OKTA as MFA but use Identity Server as our main IDP.

Is it possible to use OKTA just for MFA?

Thanks,

Froilan

**Comment by brockallen** [comment]
How you build the login page is entirely in your control, so I would say it's possible.

**Comment by brockallen** [comment]
No sorry, we deliberately don't provide that sort of UI code, as that is not really our core product.
