### ISSUE TITLE
Duende "ScopesRequested" variable. IdentityServer4 to Duende Upgrade

### ISSUE THREAD

**Issue by lglayat** [DuendeSoftware/Support#585]
**Which version of Duende IdentityServer are you using?**
My org is upgrading from IdentityServer4 to Duende.

**Which version of .NET are you using?**
6.0

**Describe the bug**
Not a bug just a question. Our application references the "ScopesRequested" Variable in the "DeviceFlowAuthorizationRequest" but in the upgrade I cannot find any variable similar to this nor can I see it being moved anywhere.

Is there somewhere in this "DeviceFlowAuthorizationRequest" that I can retrieve the "Scopes Requested" in the request?

**Comment by brockallen** [comment]
This was reworked to now be the *ValidatedResources* property of type *ResourceValidationResult*. This was done to support both parameterized scopes and resource isolation, so an object model was required to hold all of those values.

https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Validation/Models/ResourceValidationResult.cs
