### ISSUE TITLE
Upgrade from 1.2.3 -> 2.0 IdentityModel.AspNetCore.AccessTokenManagement

### ISSUE THREAD

**Issue by chrisrestall** [DuendeSoftware/Support#587]
**Which version of Duende BFF are you using?**
upgrading form 1.2.3 to 2.0

**Which version of .NET are you using?**
.net 6.0

**Describe the bug**
Not a bug so much as a question - On upgrade, noticed that I needed to pull in IdentityModel.AspNetCore for our derived DefaultTokenClientConfigurationService explicitly.  Everything compiles but I found a PR that looks as though IdentityModel.AspNetCore has been replaced with Duende.AccessTokenManagement.OpenIdConnect.  

https://github.com/DuendeSoftware/BFF/pull/116/files/d0fd7ea259b2258b9234fb6f7e51f4b94b430429

Should we be injecting in something from the new token management library instead of IdentityModel.AspNetCore.AccessTokenManagement.ITokenClientConfigurationService for our DefaultTokenClientConfigurationService implementation?

` services.AddTransient<IdentityModel.AspNetCore.AccessTokenManagement.ITokenClientConfigurationService, AssertionConfigurationService>();`

**Comment by leastprivilege** [comment]
It seems you are using this for assertions?

That's documented here:
https://github.com/DuendeSoftware/Duende.AccessTokenManagement/wiki/Client-Assertions

**Comment by leastprivilege** [comment]
No - you need to use the new way. See my link above.
