### ISSUE TITLE
Supporting branded tertiary domains from a single site

### ISSUE THREAD

**Issue by gopala000** [DuendeSoftware/Support#59]
**Which version of Duende IdentityServer are you using?** IDS5

**Which version of .NET are you using?** .Net5

**Describe the bug**

Our service is currently deployed to a single site, https://securesave.app and use IdentityServer5 for authorization. We would like to introduce branded tertiary domain sites like https://bank1.securesave.app, https://bank2.securesave.app etc. while still keeping https://securesave.app functional. We would like to continue with the single website deployment and use the single client setup in IDS5. What are the steps to accomplish this?
 
**To Reproduce**

N/A

**Expected behavior**

N/A

**Log output/exception with stacktrace**

N/A

**Additional context**

N/A

**Comment by brockallen** [comment]
I know this sort of thing is possible, as we have customers doing this. The tricky part of your question is that how you design that really depends on your semantics of multi-tenancy, so I don't have a single "right" answer. We do have an issue where doing something more to make this easier, so perhaps there might be some help there for you:

https://github.com/DuendeSoftware/IdentityServer/issues/31

Keep in mind that your proposal means you will have multiple issuers, so this will require the Enterprise Edition license.

**Comment by JohnYii** [comment]
> Keep in mind that your proposal means you will have multiple issuers, so this will require the Enterprise Edition license.

When you mean multiple issuers, do you mean multiple IDS ?

**Comment by brockallen** [comment]
> When you mean multiple issuers, do you mean multiple IDS ?

https://docs.duendesoftware.com/identityserver/v6/overview/glossary/#multiple-deployment

**Comment by JohnYii** [comment]
We are talking about a single authority of IdentityServer supporting wildcard domain of client1.securesave.app, client2, securesave.app, etc....
Does that require multiple deployments from the enterprise edition?

**Comment by brockallen** [comment]
Yes, as each of those domains makes it a multi-tenant token server, each with it's own issuer.
