### ISSUE TITLE
How to allow a user to sign localy to identity server but prevent access for all clients?

### ISSUE THREAD

**Issue by cliffi30** [DuendeSoftware/Support#591]
We use .net 6 with Duende Identity server v6 and have a handful of .net clients authorizing on the server.

We need to allow the user to sign in on the server so he/she is authorized to complete some information on the users profile before we can allow access from clients. However as soon as we sign in the user on the httpContext.SignInAsync(), clients will be severed successfully by the identity server. Is there a way we can sign the user only locally? What would be the best approach to handle this correctly?

**Comment by josephdecock** [comment]
The typical way to implement a requirement for the user to complete additional information after they log in but before you issue them a token is to use the `AuthorizeInteractionResponseGenerator`.  This is the abstraction that decides if IdentityServer will show the login, consent, or error pages during an authorize request, and it can also decide to show a custom page. For more documentation, see [here](https://docs.duendesoftware.com/identityserver/v6/ui/custom/).
