### ISSUE TITLE
Switch between identities

### ISSUE THREAD

**Issue by merijndejonge** [DuendeSoftware/Support#594]
**Which version of Duende BFF are you using?**
2.0.0

**Which version of .NET are you using?**
net6.0

**Question**
In our client, a user can have multiple identities. Each identity is obtained by signing in under a different user account at our identity server instance. The user can switch between identities in the client. Access to our back-end APIs's is achieved by sending the access token of the active identity in the requests. In our current, non bff, situation selecting the active identity and sending the corresponding access token to the backend API is easy and handled within our client. How should we accomplish this with BFF?

**Comment by josephdecock** [comment]
The BFF is built using the ASP.NET cookie handler to achieve session management, which doesn't readily facilitate multi-user sessions. You might be able to get things to work by maintaining a collection of authentication tickets and swapping the currently selected identity's ticket in to the session, but that's not a scenario that we designed to support in the BFF.

**Comment by merijndejonge** [comment]
Thanks, for the answer. It confirms that I'm on the right track for finding a solution.
Is there a particular reason that BFF is not designed to support this?

**Comment by josephdecock** [comment]
We haven't devoted the time to implementing multi-user sessions because it raises many questions about what the intended behavior should be, both in terms of protocol behaviors as well as user experience. In many cases, you could reasonably make different choices depending on particular requirements.
