### ISSUE TITLE
BFF Sample for .NET MAUI

### ISSUE THREAD

**Issue by markwiliams2018** [DuendeSoftware/Support#598]
Hi 

I do not know if any additional development would be needed but it would be great to sample for .NET MAUI similar to the ones for JS and Blazor.

MW

**Comment by ExtremeSwat** [comment]
I don't think you'll need to use Duende.BFF for MAUI

```The Duende.BFF (Backend for Frontend) security framework packages up guidance and the necessary components to secure browser-based frontends (e.g. SPAs or Blazor WASM applications) with ASP.NET Core backends.```

https://docs.duendesoftware.com/identityserver/v5/bff/

**Comment by leastprivilege** [comment]
Yes the BFF framework is designed for browser based clients only.

**Comment by markwiliams2018** [comment]
Ok. So it is safe to store tokens in the MAUI client then, right?

10x

M Bitran

**Comment by josephdecock** [comment]
In general you should store tokens using a platform specific secure storage mechanism. In MAUI, there is the `ISecureStorage` [interface ](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/secure-storage?view=net-maui-7.0) for such storage.

**Comment by markwiliams2018** [comment]
Hi

Let me explain my concern and, please, take into consideration I am not an expert.

I am using what I consider Best Practices in terms of authentication for mobile, the Code flow. With this approach, in my client I am using the OidcClient and the IBrowser interface. The login and logout are performed using the implementation of the IBrowser for each platform I support. All good here, I get my tokens and ClaimsPrincipal. I already did many tests on storing the tokens, which is also fine, using the ISegureStorage interface or Sqlite. My concern is not there; the thing is, when I perform the login using the IBrowser implementation, the idsvr Cookie is stored in the browser (if I open Chrome, for instance, if this is the underlying browser on the emulator/device), outside the App, the session is there, if I go to the IDP I see the user logged in there.

So, what I understand is that the Cookies are still being used, not only the tokens and, if the Cookies are there we are, potentially, vulnerable to XS type of attack… no? At least to the IDP server… or this threat is related only to the domain app cookies (which, in fact, I do not see there). For me it would be the best I don’t need a BFF, but…

Thanks for the patience and explanations.

All the best

M W

**Comment by josephdecock** [comment]
Having a cookie at the OIDC provider is normal. It establishes your session at the OP, which is what makes single sign on work. As I say, this is expected and normal. A really thorough discussion of the threat model for native apps specifically can be found in [RFC 8252 - OAuth 2.0 For Native Apps](https://datatracker.ietf.org/doc/rfc8252/).

**Comment by leastprivilege** [comment]
The iOS authentication browser APIs also allow you to opt-out of the cookie sharing feature. You will get a private cookie container - but also not SSO across app boundaries of course.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
