### ISSUE TITLE
Which BFF sample would you recommend that I use in Vue.js

### ISSUE THREAD

**Issue by gunnars04** [DuendeSoftware/Support#599]
Hi,

Which sample would you recommend that I use in Vue.js?
https://github.com/DuendeSoftware/BFF/tree/main/samples

This one?
https://github.com/DuendeSoftware/BFF/blob/main/samples/JS6/wwwroot/app.js

Is there any javascript library for this, or not needed?

I guess not when I compare it to the "traditional" example, meaning that is uses no library, just js code:
https://github.com/DuendeSoftware/IdentityServer/blob/main/clients/src/JsOidc/wwwroot/app.js

Thanks!
Gunnar

**Comment by ExtremeSwat** [comment]
Well theoretically you wouldn't need a library, just because most of the token handling is being done at the BFF api level, your browser would only hold a cookie.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
