### ISSUE TITLE
Extending Configuration and PersistedGrant Contexts

### ISSUE THREAD

**Issue by johndcollins** [DuendeSoftware/Support#603]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
7.0

Why can't I extend the Configuration and PersistedGrant Contexts just like the Identity Context? The classes are hardcoded in the interface?
I'd like to add a Tenant Id so I can store these configurations by tenant.

**Comment by johndcollins** [comment]
Ups... accidentally closed it. Sorry

**Comment by josephdecock** [comment]
The contexts are public classes that implement `IPersistedGrantDbContext` and `IConfigurationDbContext`. The implementation of the context interface can be specified as type parameters to `AddPersistedGrantStore` and `AddConfigurationStore`.

For example:

```cs
public class CustomPersistedGrantContext : PersistedGrantDbContext
{
    public CustomPersistedGrantContext(DbContextOptions<PersistedGrantDbContext> options) : base(options)
    {
    }

    // Add to the context however you like 
}
```


And then when you set up the DI system, add it as a type parameter:
```cs
builder.Services.AddIdentityServer(options =>
        {
            // ...
        })
        .AddOperationalStore<CustomPersistedGrantContext>(options => //...
```

**Comment by johndcollins** [comment]
Thanks Joseph, I'm only in the planning stages of this project, trying to find a working design.

I was referring to adding a TenantId field to the existing classes as the tenants will store their own configurations per tenant in the same table as all other tenants. Since the Interfaces have the classes already defined I can't inherit these and use the new classes with the added TenantId right?

**Comment by josephdecock** [comment]
Which interfaces are you referring to?

**Comment by johndcollins** [comment]
I was referring to IConfigurationDbContext and IPersistedGrantDbContext, but I'm looking into shadow properties at the moment.

**Comment by johndcollins** [comment]
Looks like Shadow Properties will work for me.
Thanks!
