### ISSUE TITLE
Hybrid approach: Owin MVC AuthenticationMode set to Passive, not signing in

### ISSUE THREAD

**Issue by danpcsi** [DuendeSoftware/Support#606]
**Which version of Duende IdentityServer are you using?**
Latest
**Which version of .NET are you using?**
Identity Server - 7, Client MVC -.Net Framework 4.7.2
**Describe the bug**
As part of the rollout, we're going to take a hybrid approach to move customers over to using the Identity Server, I've implemented this in the MVC Owin startup

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                AuthenticationMode = AuthenticationMode.Passive,
                RequireHttpsMetadata = false,
                ClientId = "client",
                ClientSecret = "clientsecret",
                Authority = "url"
                RedirectUri = "url",
                ResponseType = "code",
                Scope = "openid profile",
                SignInAsAuthenticationType = "cookies",
                UseTokenLifetime = false,
                RedeemCode = true,
                SaveTokens = true,
                UsePkce = true,
                Notifications = new OpenIdConnectAuthenticationNotifications()
                {

                    AuthenticationFailed = async authFailed =>
                    {
                        if (authFailed.Exception.Message.Contains("IDX21323"))
                        {
                            authFailed.HandleResponse();
                            authFailed.OwinContext.Authentication.Challenge();
                        }

                        await System.Threading.Tasks.Task.FromResult(true);
                    }
                }

            });


            app.UseCookieAuthentication(
      new CookieAuthenticationOptions
      {
          AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
          LoginPath = new PathString("/Account/Login"),
         
      }
  );
```

When logging in with the /Account/Login, the user is authenticated by the original login page

If I navigate to the identity server with the correct ReturnUrl (what the application would return while AuthenticationMode is set to Active), log in, get the identity cookie and then I am redirected back to the login page and the application is not authenticated. 

When I switch the authentication back to Active, the original implementation that I had will send you to the Identity server login page and redirect you back to the application, authenticated.

I'm not really sure whether when the AuthenticationMode is set to passive, its not seeing the Identity server cookie..

Do you have any suggestions or examples of this approach?

**Comment by josephdecock** [comment]
> If I navigate to the identity server with the correct ReturnUrl (what the application would return while AuthenticationMode is set to Active), log in, get the identity cookie and then I am redirected back to the login page and the application is not authenticated.

This doesn't work because the client application won't have a nonce or correlation cookie. You need to initiate login from the client, which you can do with Passive mode by calling Challenge explicitly.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
