### ISSUE TITLE
Per Tenant Well-Known path

### ISSUE THREAD

**Issue by johndcollins** [DuendeSoftware/Support#607]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
7.0

**Question:
I'm building a multi tenant ids server. Is there a way to configure the well-known page to be by tenant? Currently is seems it's hardcoded to ~/
I'd like to have it show for each of the tenants like https://idsserver.com/tenant1/.well-known/openid-configuration

Also, is there any detailed documentation on the ValidateTenantOnAuthorization option?

**Comment by josephdecock** [comment]
ValidateTenantOnAuthorization is used if you specify a tenant using acr_values. Authorize requests can pass a tenant parameter using the acr_values parameter of an authorize request. Include an acr value like tenant:exampleTenant1 or similar, and the value will be extracted from the acr values and made available in the validated request that you can get on your login page etc using the [interaction service](https://docs.duendesoftware.com/identityserver/v6/reference/services/interaction_service/). The idea is that your client application can give a hint to your identity server about which tenant is making the request, and then your login page can have a customized user experience based on that value. We do mention this tenant in several places in the documentation, but I think we should expand our description into more of a narrative, so I have created https://github.com/DuendeSoftware/docs.duendesoftware.com/issues/272 for that.

More generally, on the topic of multitenant identity server, there's been a lot of discussion over the years. See for instance: https://github.com/DuendeSoftware/Support/issues/147 and https://github.com/DuendeSoftware/IdentityServer/issues/31. 

As Brock says:

>In short, I think ... that this concept of multi-tenancy might mean different things to different people or businesses. We don't want to force one approach that precludes someone else's. We are meant to be a framework that supports OIDC/OAuth, and we want to facilitate any requirements around that the best we can.

**Comment by johndcollins** [comment]
Thanks Joseph!
thanks for the details.

I was looking for something like this in regards to the .well-known link:
endpoint.MapWellknownDiscovery("{" + Constants.HttpRouteTenantKey + "}/.well-known/openid-configuration" ...
I already have the database reading the values based on the tenant key.

**Comment by josephdecock** [comment]
No problem - probably you'll need to use a middleware in your pipeline to first handle the tenancy and then somehow invoke the identity server middleware in a nested fashion. Do note that multiple discovery documents implies you'd have multiple issuers, which requires the enterprise license.

**Comment by johndcollins** [comment]
I understand. Once I make over 1M US I'll be happy to pay for an enterprise license.

**Comment by josephdecock** [comment]
Good luck to you! Do you need anything further with this issue, or shall we close it?

**Comment by johndcollins** [comment]
No, you can close it. I still need to figure out how to get the well-known page to show per tenant, but I'll have to dig into that some more.
