### ISSUE TITLE
Access "extra" parameters in CustomTokenRequestValidator

### ISSUE THREAD

**Issue by sipsorcery** [DuendeSoftware/Support#609]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
7

**Additional context**

I have need to get custom client claims into my access token. The ideal approach for me would be to set the data for the claims in the `extra` query string parameters I can set with `CreateAuthorizeUrl`. Is there any option to access the `extra` parameters in `CustomTokenRequestValidator`?

**Comment by josephdecock** [comment]
What do you mean by custom client claims? Do you have entire claims (type and value) that should always be included based on the client? If so, the client model has a claims collection that you can use to customize the claims on a per-client basis.

If you want to run arbitrary code to generate custom claims, then the usual place to do so is the [profile service](https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/). I wouldn't try to use query parameters that were sent to the authorize endpoint from the profile service though, as typically the profile service runs during the separate  token request.

**Comment by sipsorcery** [comment]
Thanks for the response.

> What do you mean by custom client claims? Do you have entire claims (type and value) that should always be included based on the client? 

Yes, to type and value. No, to always included. The need for the custom claims varies depending on applcation logic.

I have looked at the profile service but I'm trying to avoid the need for an extra cahcing mechanism between requests.

My flow is:

1. User initiates operation on my portal web application,
2. User redirected to identity server to approve  the operation. This is a custom controller and UI on the identity server (no authorize end poiunt yet), This step generates a digital signature I'd like to add to the access token as a custom claim.
3. If user approves the controller generates the authorize link and redirects to /connect/authorize to initiate the OAuth code flow,
4. User redirected back to portal using redirect_uri with the code and state,
5. Portal calls /connect/token to get the access token and use it on a separate API server.

The issue is getting the custom data from step 2 into the access toen prodcued in step 5.

I have managed to do it by adding the data as a custom scope in step 3 and then switching the scope for a claim in step 5. But that's bit clunky and requires setting the scope approval up.

**Comment by josephdecock** [comment]
I'm confused by the way you're describing your flow. It sounds like you're talking about a consent page or custom UI page as part of the authorization flow, but you also say "no authorize end point yet". Whatever you're doing, it sounds non-standard in a way that adds complexity to both your client application and identity server, and changes the threat model (a standard flow is sort of a "pre-vetted" threat model). Instead of that, I would simply have your client application express that it needs these claims by including a scope in the authorize request, and then doing whatever lookups or processing is required in the profile service.

**Comment by josephdecock** [comment]
Also, if you want additional user interaction as part of the flow, that should come after the authorize call. IdentityServer's  mechanism for adding additional UI is described in our documentation [here](https://docs.duendesoftware.com/identityserver/v6/ui/custom/).

**Comment by sipsorcery** [comment]
Thanks again.

> Also, if you want additional user interaction as part of the flow, that should come after the authorize call. IdentityServer's mechanism for adding additional UI is described in our documentation [here](https://docs.duendesoftware.com/identityserver/v6/ui/custom/).

We did try that approach in the past. The bti we got stuck on is this line fomr the above docs:

> Once the custom logic is complete on the page, then the URL in the returnUrl query parameter should be used to return the user back into the IdentityServer authorize request workflow.

If our custom UI wants to be able to add a custom claim to the token that gets generated as part of the authorize request workflow`is there a way? The claim data is specific to the action that happens on the custom UI page not specific to the user.

**Comment by josephdecock** [comment]
Yes, in your custom page you should update the identity in your IdentityServer session with your custom claims. If those claims are requested based on the scopes, api resources, and identity resources in your authorize request, you'll get them added to your token automatically. Alternatively, you can customize the profile service to emit those claims - they will be available in the profile service context's subject.

You can see an example of a custom page that adds claims in our step up sample [here](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/UserInteraction/StepUp/IdentityServerHost/Pages/Account/Mfa/Index.cshtml.cs#L32-L38). I don't mean to distract with the details of step up, but the point is, you can add claims to your identity server session just by constructing the claims and calling SignIn.

**Comment by sipsorcery** [comment]
Thanks for the suggestion.

I hadn't thought about persisting claims in the authentication cookie in order to get them into the newly minted access token.

I was able to persist the claims in the cookie and wire up an IProfileService but it seems the authentication cookie and its HTTP context are deliberately unavailable, at least according to ChatGPT:

> The IProfileService in Duende IdentityServer is designed to be decoupled from the HTTP context, as it handles user profile data for tokens independently of the current request context. As a result, the _httpContextAccessor.HttpContext may not be available or may not represent the expected context within the IProfileService.

Is there another trick to get the claims from the authentication cookie to the new token?

**Comment by sipsorcery** [comment]
Finally got it working:

In controller action:

```
var claimsUser = HttpContext.User;
var claimsIdentity = claimsUser.Identity as ClaimsIdentity;
var cleanedClaims = claimsIdentity.Claims.ToList();
cleanedClaims.RemoveAll(x => x.Type == "myclaim");
var newClaim = new Claim("myclaim", Base64UrlEncoder.Encode(data));
cleanedClaims.Add(newClaim);
var updatedClaimsIdentity = new ClaimsIdentity(cleanedClaims, HttpContext.User.Identity.AuthenticationType,
	claimsIdentity.NameClaimType, claimsIdentity.RoleClaimType);
var updatedPrincipal = new ClaimsPrincipal(updatedClaimsIdentity);
await HttpContext.SignInAsync(IdentityConstants.ApplicationScheme, updatedPrincipal);
```

In profile service:

```
public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
	var myClaims = context.Subject.Claims.Where(x => x.Type.StartsWith("myclaim")).ToList();
	if (myClaims.Any())
	{
		context.IssuedClaims.AddRange(myClaims);
	}
	return Task.CompletedTask;
}
```

imho the extra parameters exposed in one of the token issuance middlewares would be a very handy option.

**Comment by josephdecock** [comment]
> the authentication cookie and its HTTP context are deliberately unavailable

As you used in your solution, we put the subject into the ProfileDataRequestContext passed to the profile service.

> As a result, the _httpContextAccessor.HttpContext may not be available or may not represent the expected context within the IProfileService.

I don't know what ChatGPT is driving at here. The profile service gets invoked by the token and userinfo endpoints, which are of course http endpoints. If you use the http context from the profile service, you'll get that http context associated with the http request for tokens or userinfo.

> imho the extra parameters exposed in one of the token issuance middlewares would be a very handy option.

Can you describe this a bit more please?

**Comment by sipsorcery** [comment]
>> imho the extra parameters exposed in one of the token issuance middlewares would be a very handy option.

> Can you describe this a bit more please?

I'll give it a shot but please be a little bit liberal with the interpreation. I've found that when talking tokens and authenitcation with the "professionals" things get interpreted literally (I once had 4 calls trying to determine how to do the equivalent of GitHub Personal Access Tokens with Auth0's service and got nowhere, we just rolled our own JWTs in the end).

The requirement is to get identity server to include some custom claims in an access token issue via the OAuth2 code flow. The info for the custom claims are NOT known at the point of initial authentication. Once authenticated a user is asked to approve an arbitrary operation by signing a WebAuthn challenge. Once the signature has been generated `/connect/authorize` is called to set up the access token. The user is then sent back to the 3rd party app which will use `/connect/token` to get the token and use it to perform a privileged operation on an API.

The steps are outlined in my [previous post](https://github.com/DuendeSoftware/Support/issues/609#issuecomment-1502373860). 

I'm suspect my scenario sounds very specific but it's actually broadly in line with the steps that European Union Financial Institutions need to do for Strong Customer Authentication. As well as authenticating a user there's also a need to get their consent for specific operations, such as making a bank transfer, and the data for that consent somehow needs to be passed from the identity server via the 3rd party app to the API.
