### ISSUE TITLE
How to debug deployment to IIS Windows Server?

### ISSUE THREAD

**Issue by skillmanp** [DuendeSoftware/Support#610]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
net6.0

**Describe the bug**  (This is not a bug)

Identity Server and my asp.net core client application work as expected (wonderfully) on localhost -- however, when the Duende IDP project is deployed to a Windows 2012 Server on IIS  -- basic functions such as retrieving the discovery document - do not work and return "currently unable to handle this request" error message.   How does one go about debugging or addressing issues post-deployment? How do  I determine if this is a server issue versus an application issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
