### ISSUE TITLE
AuthenticationTicketExtensions+ServerSideTicketStore Incompatible with Microsoft.AspNetCore.Antiforgery

### ISSUE THREAD

**Issue by grant-curve** [DuendeSoftware/Support#611]
**Which version of Duende BFF are you using?**
Duende.BFF 2.0.0

**Which version of .NET are you using?**
net6.0

**Describe the bug**

Adding Duende.BFF session ticket store services to an application already using the default implementations of anti-forgery from Microsoft.AspNetCore.Antiforgery causes anti-forgery checks to fail.

Note: the application in question is not _yet_ a BFF, and using all bff features. It is a legacy application that we are moving in the direction of being a BFF, and trying to not write more throwaway code than is necessary.

**To Reproduce**

Configure anti-forgery in an application using services.AddAntiforgery() // from Microsoft.Extensions.DependencyInjection.AntiforgeryServiceCollectionExtensions
```
services
    .AddSingleton<IPostConfigureOptions<CookieAuthenticationOptions>,
        PostConfigureApplicationCookieTicketStore>();
services.AddTransient<IServerTicketStore, ServerSideTicketStore>();
services.AddTransient<ISessionRevocationService, SessionRevocationService>();
services.TryAddSingleton<IUserSessionStore, CustomUserSessionStore>();
// since we're not using the full bff in this app yet, we also needed to have a stub IUserTokenEndpointService
services.AddTransient<IUserTokenEndpointService, StubUserTokenEndpointService>();
```

Then make a POST call, which triggers an anti-forgery check. The check will fail with the error "The provided anti-forgery token was meant for a different claims-based user than the current user."

**Expected behavior**

The ticket claims are deserialized without throwing away the issuer data, and therefore the default anti-forgery implementation works with the bff library. No error is thrown.

**Log output/exception with stacktrace**

```
{"@t":"2023-04-11T21:35:52.1203914Z","@m":"Antiforgery token validation failed. \"The provided antiforgery token was meant for a different claims-based user than the current user.\"","@i":"843d91fe","@x":"Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The provided antiforgery token was meant for a different claims-based user than the current user.\n   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)\n   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)","Message":"The provided antiforgery token was meant for a different claims-based user than the current user.","EventId":{"Id":1,"Name":"AntiforgeryTokenInvalid"},"SourceContext":"Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter","ActionId":"46e412d1-c757-4328-b389-a133c85587f1","ActionName":"Redacted.Controllers.CampaignController.UpdateCampaignDraft (Redacted)","RequestId":"0HMPQQII7KF24:00000002","RequestPath":"/api/redacted/2945774f-a2a0-498c-a1c8-b8459cffd6ff","ConnectionId":"0HMPQQII7KF24"}
```

**Additional context**

We have run into an issue between asp.net anti-forgery libraries and BFF Server Side Sessions.

Background: We have a legacy application in our platform that is not a BFF yet, though future plans are to make that transition. We would like it to be integrated with session management, so we've chosen to take our implementation of ISessionStore from our existing BFF's and drop it into this legacy app.

Problem:
The legacy app is using the ASP.net default implementation of anti-forgery, binds the anti-forgery token to the user by hashing the name claim's Type, Value, and Issuer.

Deserialization of the session from the session store (in Duende.BFF.AuthenticationTicketExtensions) the transformation of the data into the ClaimLite type does not include an issuer field, so that information is dropped. Then the anti-forgery system goes to compare the claim and fails the check 

On creating a session on login, the sub claim looks like:
claim = {
	Type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
	Value = "my_sub_value",
	Issuer = "my.issuer"
};

On deserialization of the session in the BFF ServerSideTicketStore, the result is
claim = {
	Type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
	Value = "my_sub_value",
	Issuer = "LOCAL_AUTHORITY"
};
This looks to be because deserialization process (in Duende.BFF.AuthenticationTicketExtensions) transforms the data into the ClaimLite type which does not include an issuer field, so that information is dropped.

Then we get to the anti-forgery check, where Microsoft.AspNetCore.Antiforgery.DefaultClaimUidExtractor (https://github.com/dotnet/aspnetcore/blob/main/src/Antiforgery/src/Internal/DefaultClaimUidExtractor.cs) hashes the following structure to be compared against the cookie xsrf token value.

new string[]
{
    nameIdentifierClaim.Type,
    nameIdentifierClaim.Value,
    nameIdentifierClaim.Issuer
}

Because the issuer has been dropped and replaced with LOCAL_AUTHORITY, the antiforgery check always fails with the message "The provided antiforgery token was meant for a different claims-based user than the current user."

The interfaces the Microsoft.AspNetCore.Antiforgery namespace driving this processign are all marked internal so there's not an immediate route we see to replace the implementations to ignore the issuer. Do you have any advice for working past this problem, or can ClaimsLite be fixed ClaimLite to include the issuer?

**Comment by josephdecock** [comment]
Sorry for the delay getting back to you @grant-curve. We didn't design the BFF to be used in this partial way that you're describing - though if it is working (apart from this issue), that's great! If you're going to use pieces of the BFF in this way,  Ithink your only option is to replace the BFF's `IServerTicketStore` implementation with your own implementation that will include the issuer for your claims when it serializes tickets.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
