### ISSUE TITLE
Best Practice For A Sign Up + Sign In Flow

### ISSUE THREAD

**Issue by alecrodden** [DuendeSoftware/Support#612]
**Which version of Duende IdentityServer are you using?**

6.2.0

**Which version of .NET are you using?**

net7.0

Users of one of our web apps (which is a client of our sign-in server) can use the app anonymously, but then sign-up from within the app once they're ready. This app is on a different subdomain than our sign-in server. Our sign-up flow is also hosted on our sign-in server. The sign-up flow goes directly into the sign-in flow after the account is created. We added a `ReturnUrl` query string parameter to our sign-up endpoint, so that it can be carried directly to the first endpoint of the sign-in flow, also as a query string parameter. This `ReturnUrl` query string parameter on the first endpoint of the sign-in flow is also how the sign-in server sends its `/connect/authorize/callback` return URL into our sign-in flow as part of an authorize request to the sign-in server. The issue is, we seem to not be able to utilize the `ReturnUrl` query string parameter on the sign-up endpoint to redirect the user back to the app they initiated signing up from, because it ultimately gets validated via `GetAuthorizationContextAsync`, which basically requires the return URL to be local to the sign-in server, and not on the subdomain the client is on.

Steps to help with clarity:

1. User is using client app anonymously.
1. User decides to sign-up and clicks link in client app to `https://sign-in.company.com/sign-up?returnUrl=https://other-app.company.com`.
1. User goes through sign-up flow. The sign-in server is keeping track of the `https://other-app.company.com` return URL with other sign-up session data.
1. After account is created, the sign-in server redirects the user to `https://sign-in.company.com/sign-in?returnUrl=https://other-app.company.com`.
1. At the end of the sign-in flow, before `HttpContext.SignInAsync()` is called, `IIdentityServerInteractionService.GetAuthorizationContextAsync()` is called, passing the return URL in order to validate it.
1. The return URL, `https://other-app.company.com`, ends up failing validation because it's not a local URL.

If sign-in was being initialized by an authorize request, there'd be no issue because `redirectUrl` would be a local callback URL. But in this case, we came into the sign-in flow from a sign-up flow that was *itself* initiated from a client app on another domain that wants to be redirected back to after sign-up + sign-in are complete.

I tried to implement a custom `IReturnUrlParser` but it seems like it would be difficult to implement `IReturnUrlParser.ParseAsync()` because of what it looks like it needs to do in order to create an `AuthorizationRequest`.

I also thought about maybe this is just going about this all wrong. Maybe sign-up and sign-in should be totally separate flows, such that the end of the sign-up flow should redirect back to the BFF login endpoint on client app, triggering an authorize request and a redirect *back* to the sign-in server, but for signing in this time.

The steps would be:

1. User is using client app anonymously.
1. User decides to sign-up and clicks link in client app to `https://sign-in.company.com/sign-up?returnUrl=https://other-app.company.com/bff/login`.
1. User goes through sign-up flow. The sign-in server is keeping track of the `https://other-app.company.com/bff/login` return URL with other sign-up session data.
1. After account is created, the sign-in server redirects the user to `https://other-app.company.com/bff/login`.
1. Client app does an authorize request and redirects the user back to the sign-in server.
1. User goes through the sign-in flow.
1. User is redirected back to the client app (`https://other-app.company.com/signin-oidc`).
1. User is now signed into the client app.

Although, with this idea, I'm not sure how I'd get the email address of the user that they entered when signing up to carry over to sign-in so the user doesn't have to re-enter it. Also, we'd still want to somehow validate the return URLs sent to sign-up, but at least this would be separate from the return URL validation that is done for signing in, which seems cleaner.

**Comment by josephdecock** [comment]
The standards based approach to this problem is the [new spec from open id for prompt=create](https://openid.net/specs/openid-connect-prompt-create-1_0.html). We've just added support of prompt=createto IdentityServer in our upcoming 6.3 release. You can try a preview of the upcoming release [here](https://www.nuget.org/packages/Duende.IdentityServer/6.3.0-preview.1.1#readme-body-tab).

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
