### ISSUE TITLE
Automatic Key is not created in File System

### ISSUE THREAD

**Issue by anjanasagathiya** [DuendeSoftware/Support#615]
**Which version of Duende IdentityServer are you using?**

Duende IdentityServer - v6.2.3

**Which version of .NET are you using?**

.NET 7

**Describe the bug**

Currently, we are using a static key to sign a token. Now, we are going to enable automatic key management. 

For that, we are trying out different storage options and found that the even though we configure a File System path it does not work. It keep storing keys in the database.

We have followed the steps mentioned in this [document](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/automatic_key_management/#key-storage) to configure the FileSystemKeyStore.

Can you please help us in it that why it is created in the database even though configuring the FileSystemKeyStore? 

And also is there any other option available for key stores like AWS SSM?

**Comment by josephdecock** [comment]
When the ISigningKeyStore service is resolved from DI, it needs to resolve to the service that you want to use for your key store. When you call AddIdentityServer, that adds the filesystem key store to DI. Then when you call AddOperationalStore, that adds all the EF based stores, including the EF based signing key store, overriding the file system key store. You should remove the ef based signing key store from your services, like this:

```cs
var efKeyStoreDescriptor = builder.Services.FirstOrDefault(d => d.ImplementationType == typeof(SigningKeyStore));
builder.Services.Remove(efKeyStoreDescriptor);
```

**Comment by aritro60** [comment]
@josephdecock do we need to add this piece of code mentioned by you before AddIdentityServer or after AddIdentityServer

**Comment by josephdecock** [comment]
That goes after AddIdentityServer. Alternatively, you could remove your call to AddOperationalStore and replace it with granular calls adding the stores and services you need.

**Comment by aritro60** [comment]
@josephdecock I am actually trying to write the Keys in a File System Path but even after adding the piece of code mentioned by you, I am unable to see any Key in the path. 
Then I also tried to add this - .AddSigningKeyStore<FileSystemKeyStore>() in .AddIdentityServer but it is showing this error. 
Does this function(AddSigningKeyStore) needs to be added if we are removing EntityFramework storage?
![image](https://user-images.githubusercontent.com/126474470/235689635-9a29905e-b4fb-4ff2-8245-feac53d51a1b.png)

**Comment by josephdecock** [comment]
You don't need to call AddSigningKeyStore. I'm not sure what's going wrong, but a sample that works locally for me is here:
https://github.com/DuendeSoftware/IdentityServer/compare/main...joe/support/ef-with-filesystem-keys.

**Comment by josephdecock** [comment]
Did that sample clear things up for you? Can we close this issue?

**Comment by aritro60** [comment]
No, It is still not storing the certificate in the File System Path even though my code is almost the same as yours

**Comment by josephdecock** [comment]
Here's another thing you can try - the AddOperationalStore method is really just a convenience method for adding the EF related services. Instead of calling it and then removing the signing key store that it adds, you can just add the services that it would add that you _do_ want. 

```cs
// These are essential:
builder.Services.AddOperationalDbContext<PersistedGrantDbContext>(opt => { /* Your db config action here */});
builder.AddPersistedGrantStore<PersistedGrantStore>();

// Don't include this one, that's the whole point:
// builder.AddSigningKeyStore<SigningKeyStore>();

// These are needed if you are using device flow, server side sessions, or have token cleanup enabled respectively:
builder.AddDeviceFlowStore<DeviceFlowStore>();
builder.AddServerSideSessionStore<ServerSideSessionStore>();
builder.Services.AddSingleton<IHostedService, TokenCleanupHost>();

```

**Comment by josephdecock** [comment]
Any update here?

**Comment by brockallen** [comment]
> I tried the piece of code provided by you but still it is not working

Can you elaborate on what's still not working?

> Is there any way by which we can connect for few minutes so that I can show where I am getting stuck

For our standard support, we don't offer one-on-one calls. But we do in our priority support and consulting services. If you're interested in that, please contact us: https://duendesoftware.com/contact

**Comment by aritro60** [comment]
@brockallen I am trying to run the IdentityServer in my local and I am unable to see any file containing information regarding the 'Keys' in this 'options.KeyManagement.KeyPath'
![image](https://github.com/DuendeSoftware/Support/assets/126474470/81d263c0-73d0-4581-b9cd-09ab2e8d4b75)

**Comment by josephdecock** [comment]
Can you try cloning our repo and running the sample code in the branch that I linked to above?

**Comment by aritro60** [comment]
As instructed by @josephdecock , I cloned your repo and run the sample code given by you but I am still not able to see the Keys in the given location
![image](https://github.com/DuendeSoftware/Support/assets/126474470/9ba59cc0-9b9b-46a0-a3de-c7dd3c2edf09)
![image](https://github.com/DuendeSoftware/Support/assets/126474470/f2d08374-7f89-4200-8898-49af2471ff72)

Is there something I am doing wrong?

**Comment by josephdecock** [comment]
IdentityServer doesn't create the keys until some request that needs a key tries to get a key. For example, if you request the keys from discovery by going to https://localhost:5001/.well-known/openid-configuration/jwks after you start up IdentityServer, the keys should get created.

If that doesn't result in the keys being created where you expect them, can you share the response from that request, as well as any logs created by identityserver when you make it?

**Comment by AndersAbel** [comment]
@aritro60 Any update on this?

**Comment by AndersAbel** [comment]
Closing, but feel free to reopen if you need further assistance on the issue.
