### ISSUE TITLE
Signin session exposed between browser windows

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#617]
**Which version of Duende BFF are you using?**
Community
**Which version of .NET are you using?**
7.0.105
**Describe the bug**
Build and start `next-auth-example` (https://github.com/nextauthjs/next-auth-example), signin successfully with a credential. Change `CLIENT_ID` and `CLIENT_SECRET` to different set of valid values, build and start a `next-auth-example` on a different port#. Try to sign in in a separate browser window and it will show `"signed in as"` the credential of the previous signed in user.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

The second signin should start afresh, redirecting to the provider for the user to input credentials instead of showing being "signed in"

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
Can you describe in more detail how you're using the Duende BFF and how you're using nextauthjs with it?

**Comment by khteh** [comment]
I use `DuendeIDS6Provider` library for 2 of my React.JS/Next.JS applications which redirects user to the OAuth server for authentication. These 2 applications have different set of `NEXTAUTH_<foo>`. Open up 2 browser tabs / windows with these 2 different applications, login to one of them, switch to the other one and try to login and it shows user is "logged in" without redirecting to the OAuth for authentication.

**Comment by josephdecock** [comment]
So are you using Duende.BFF at all?

**Comment by khteh** [comment]
Now I realize that Duende.BFF refers to https://www.nuget.org/packages/Duende.BFF/. Not a conceptual idea of "Backend For Frontend architecture. No, I don't use that nuget package.

**Comment by josephdecock** [comment]
Ah I see, sorry for the confusion. I don't know the details of next.js but if you're certain that you're not getting a redirect to identity server, then that sounds like somehow the two next js apps are sharing a session which is being managed by next.js and is outside of IdenityServer's control (and what we can provide support for directly here). I would check with the next.js folks for support questions regarding their tools.

**Comment by khteh** [comment]
Is this affected by `AddServerSideSessions`?

**Comment by josephdecock** [comment]
No, because your client application isn't making any requests to IdentityServer.

**Comment by khteh** [comment]
https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/ReactBffSample/src/FrontendHost/ClientApp may help solve the problem. However, I hit the `Error occured while trying to proxy to: localhost:44447/bff/login` error in the browser.

How do I use only the client library to authenticate with the Duende Identity Server 6 https://iam.kyberlife.io ?

**Comment by josephdecock** [comment]
Sorry, which client library are you referring to?

**Comment by khteh** [comment]
Client library for react.js/next.js applications.
