### ISSUE TITLE
OpenIdConnect - can you change configuration without restarting app?

### ISSUE THREAD

**Issue by kwojcinski** [DuendeSoftware/Support#619]
In our app we configure OpenIdConnect in our Startup.cs with config from appsettings.json. While the application is running, appsettings.json may change, with reloadOnChange set to "true". Can we change configuration of OpenIdConnect on appsettings.json change or do we have to restart app to do it?

**Comment by josephdecock** [comment]
In your client applications, the OpenIdConnect handler won't re-read your appsettings by default. There's an abstraction in ASP.NET authentication called the ISchemeProvider which you theoretically could implement to allow for schemes to change on the fly. In IdentityServer itself, our dynamic providers feature actually does that. If you need IdentityServer to federate with other oidc providers, and want that to change dynamically, then you could consider using the identity server dynamic providers feature to accomplish that.

**Comment by josephdecock** [comment]
Are we good to close this issue?
