### ISSUE TITLE
The BFF forwards tokens provided in the Authorization header

### ISSUE THREAD

**Issue by joseftw** [DuendeSoftware/Support#624]
**Which version of Duende BFF are you using?**
2.0.0
**Which version of .NET are you using?**
7
**Describe the bug**
Calls to the BFF that contains an Authorization header are forwarded to the remote endpoint.

**To Reproduce**
Setup the BFF application by following [the example in the docs](https://docs.duendesoftware.com/identityserver/v6/bff/session/handlers/)

Configure the remote API like this:

```
builder.MapRemoteBffApiEndpoint(
   _config.GetRequiredValue<string>("my-prefix"),
   _config.GetRequiredValue<string>("http://my-api.local"))
.WithOptionalUserAccessToken();
```

- Obtain an access token (we are using IdentityServer).
We are using the authorization code flow via Postman to obtain a token.
- Call the remote API via the BFF. Example:
GET
Authorization: Bearer MyToken
http://mybff.local/my-prefix/some-remote-endpoint
- `MyToken` is forwarded to the remote api endpoint

**Expected behavior**
The token is not forwarded to the remote API and we'll receive a 401 response (from the remote api).

**Additional context**

I was under the impression that the token would not be forwarded. I thought that the token would be obtained from the session storage using the cookie.

Our middleware pipeline looks like this:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseForwardedHeaders();
        app.UseHtmlExceptionHandler();
        app.UseRouting();
        app.UseCors(DefaultCorsPolicy);
        app.UseBff();
        app.UseAuthentication();
        app.UseAuthorization();
        app.UseEndpoints(builder =>
        {
            builder.MapControllers();
            builder.MapBffManagementEndpoints();
            builder.MapRemoteBffApiEndpoint(
                _config.GetRequiredValue<string>("my-prefix"),
               _config.GetRequiredValue<string>("http://my-api.local"))
           .WithOptionalUserAccessToken();
        });
    }
```

Questions:

**Should the BFF forward tokens from the Authorization header?**
**If yes - is that a security issue?**
**If no - how do we prevent the BFF from forwarding the token?**

Let me know if you need anything else!

**Comment by joseftw** [comment]
Hm, the problem seems to be that the BFF now forwards ALL headers to the remote api.
Previously, we had some kind of "opt-in", we implemented the `ITransformProvider` interface and we could explicitly say which headers that should be forwarded.

Now, when debugging, I can see that the custom provider code is not executed at all. Do you know when this logic changed?

**Comment by josephdecock** [comment]
The simpler solution seems to me to be that you should stop obtaining access tokens in the javascript frontend. One of the main security benefits of the BFF is that the access tokens are no longer obtained by or stored in locations accessible to javascript. If your front end is still obtaining access tokens itself, then you lose that benefit.

**Comment by joseftw** [comment]
Absolutely. We are not exposing the token in anyway. We saw that we had a couple of 401's in our logs from the API. Logs showed that tampered requests towards the BFF from bad actors added the Authorization header with some dummy values which the BFF forwarded.

Just wanted to make sure that we hadn't configured anything wrong in the BFF.

Anyway, we will just add a custom transform that strips certain headers.

**Comment by josephdecock** [comment]
@leastprivilege, should we consider adding this kind of transform to the BFF?

**Comment by leastprivilege** [comment]
This would be possible today already

https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/http_forwarder/#custom-transformations
