### ISSUE TITLE
Persisting BFF cookies a security risk?

### ISSUE THREAD

**Issue by janssensjeroen** [DuendeSoftware/Support#629]
Is persisting the BFF authentication cookie in the browser a security risk?

**Comment by josephdecock** [comment]
Using cookies to authenticate an ASP.NET application is a really well-understood threat model. We feel confident in building our BFF using cookies in this way.

The BFF auth cookie by default is:
- Data protected (its contents are encrypted and signed)
- Only ever sent over https connections (the secure cookie attribute is set)
- Inaccessible to javascript (the httponly attribute is set)
- Protected from being abused in a CSRF attack by the BFF framework 
- Never forwarded to apis (if you make an api call through the bff, the auth cookie is sent to the bff but not on to the api)

**Comment by janssensjeroen** [comment]
Hi Joseph, thank you for your response. I am aware of the benefits cookie authentication, that's why we also apply it in our applications. I think my question wasn't clear enough. I was wondering whether it is a security risk to make it a persistent cookie instead of a session cookie (that expires when the browser session ends).

**Comment by leastprivilege** [comment]
It does not make it riskier than any other persisted cookie you might have. But indeed, certain malware these days does target persisted cookies and exfiltrates them.
