### ISSUE TITLE
How to implement custom authentication

### ISSUE THREAD

**Issue by JungleMonkey** [DuendeSoftware/Support#63]
**Which version of Duende IdentityServer are you using?**
6

**Which version of .NET are you using?**
6.0

I am trying to do some custom authentication using user details that we look up from an API.

I have gone through the Quick Starts as well as read through the documentation at:
https://docs.duendesoftware.com/identityserver/v6/ui/login/session/

I can see in the Login page how to do my own lookup, validate the user etc at this point but what I don't understand is how the rest of the claims are being added.

In the QuickStart using the TestUsers the issuer is being created with just the users SubjectId and DisplayName.  

```
// issue authentication cookie with subject ID and username
var isuser = new IdentityServerUser(user.SubjectId)
{
    DisplayName = user.Username,
};

```

Yet somehow the test users given_name, family_name, email, email_verified grants are also returned to the client.

What am I missing?  There's obviously more to this than just what's happening on the login page.

Thanks

**Comment by brockallen** [comment]
I think you're missing the profile service: https://docs.duendesoftware.com/identityserver/v6/fundamentals/claims/
