### ISSUE TITLE
Blazor WASM BFF sample app appears to demonstrate contradictory behavior

### ISSUE THREAD

**Issue by pm64** [DuendeSoftware/Support#631]
I'm a little confused about the Blazor WASM BFF sample app's behavior with respect to unauthenticated users.

Based on the `LoginDisplay` component, the app appears to demonstrate a workflow where unauthenticated users may access the app, with the caveat that in cases where AuthorizeRouteView is used, the rendered content may differ from what is displayed for authenticated users (for example, in the `LoginDisplay` component rendered at the top of the viewport, a "login" link is displayed if the user is not authenticated).

But based on `App.razor`, it seems that unauthenticated visitors should trigger rendering of the `RedirectToLogin` component, immediately navigating such visitors to the login page:

```
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(App).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                    @if (context.User.Identity?.IsAuthenticated != true)
                    {
                        <RedirectToLogin />
                    }
                    else
                    {
                        <p role="alert">You are not authorized to access this resource.</p>
                    }
                </NotAuthorized>
            </AuthorizeRouteView>
            <FocusOnNavigate RouteData="@routeData" Selector="h1" />
        </Found>
        <NotFound>
            <PageTitle>Not found</PageTitle>
            <LayoutView Layout="@typeof(MainLayout)">
                <p role="alert">Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

That doesn't happen -- unauthenticated visitors are not redirected to the login page.

Is there an explanation for this apparent conflict, and for why the redirect doesn't happen?

In my case I actually want the redirect behavior, such that all unauthenticated visitors are redirected to login. But I'm not sure how to make that happen beyond what's already specified in App.razor.

**Comment by brockallen** [comment]
Sorry -- it seems this issue fell thru the cracks. Were you ever able to sort this out?

**Comment by pm64** [comment]
Hi @brockallen, no problem. Sadly, no -- I'm still confused about the presence of the RedirectToLogin component, whether that component is working as intended, and what the demo seeks to demonstrate with regard to unauthenticated users.

**Comment by AndersAbel** [comment]
@pm64 sorry for taking so long to getting back on this.

The `NotAuthorized` section in the `AuthorizeRouteView` will be rendered if the user was not authorized to view the selected page/route. The `Index.razor` page does not contain any `@attribute [Authorize]` statement, so it is accessible anonymously. If you compare that to the `FetchData.razor` page it contains `@attribute [Authorize]`. That applies the default authorization policy, which is to require an authenticated user. If the user is not authenticated, the `AuthorizeRouteView/NotAuthorized` block in `app.razor` is rendered resulting in a redirect to `/bff/login`.

Using an `AuthorizeRouteView` in this way the handling of unauthorized access to pages can be centralized. But the `AuthorizeRouteView` in itself is not an authorization rule.
