### ISSUE TITLE
Match IdentityServer BaseUrl to ngrok/devtunnel Url

### ISSUE THREAD

**Issue by techscgh** [DuendeSoftware/Support#633]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
7.0 

**Describe the bug**
Not a bug.

**Question**
Duende IdentityServer is used to enable external logins for users via Clients (mobile apps) with their Apple, google, etc. accounts.

With Apple ("sign in with Apple"), it is required to have an appropriate discovery document including valid endpoints to reach the IdentityServer from outside.

While developing and debugging locally, a tunnel is setup through Visual Studio devtunnels. The registered tunnel looks like:
https://xxx.euw.devtunnels.ms/.well-known/openid-configuration

But the IdentityServer discovery document is completely built on the real local host:
"{"issuer":"https://localhost:5005","jwks_uri":"https://localhost:5005/.well-known/openid-configuration/jwks","authorization_endpoint" ..."

With google, I can just work with this configuration. With Apple, it is required to have a discovery document pointing to the tunnel baseurl "https://xxx.euw.devtunnels.ms/" and not localhost.

Another problem is the debugging of Mobile Apps hosted in Virtual Machines which want to sign in with the locally debugged IdentityServer. They all need a valid discovery document pointing to the devtunnel for all endpoints.

How can I adjust the building process of all endpoints in the discovery document for debugging?

Do I have to modify all endpoints one by one? Is it possible to modify all endpoints that way or is there a better solution available for local debugging scanarios with external logins?

Thank you

**Comment by josephdecock** [comment]
I'm not familiar with the specifics of devtunnels, but if it is setting http headers like x-forwarded-for, you can fix this by including the asp.net forwarded headers middleware in your identityserver host.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by techscgh** [comment]
Thank you!
My solution looks now like this:
- On a Windows Machine
- Add an own and officialy registered domain to your lmhosts file
- integrate a ssl cert for this domain into iis
- debug duende from visual studio in iis
- duende will then map to a valid domain incl. ssl
