### ISSUE TITLE
Token management: question about the cache key format

### ISSUE THREAD

**Issue by sliekens** [DuendeSoftware/Support#634]
Hello,

I was looking at the implementation of your excellent AccessTokenManagement library and wanted to ask a question.

Specifically, the format of the cache key used for the distributed token cache has caught my attention.
[Duende.AccessTokenManagement/DistributedClientCredentialsTokenCache.cs at 31b9e2841043237996e3bbae4930acf4d09eb56e · DuendeSoftware/Duende.AccessTokenManagement (github.com)](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/blob/31b9e2841043237996e3bbae4930acf4d09eb56e/src/Duende.AccessTokenManagement/DistributedClientCredentialsTokenCache.cs#L110-L118)

I see that the cache key includes the **client name**, **scope** and **resource** parameters, but not any user-provided parameters. Is this correct and why?

My concern is that excluding user parameters from the cache key can lead to unwanted cache hits. In my not-so-hypothetical scenario, one of the parameters is a **tenant** parameter. I believe the following code leads to some surprising behavior where a token is returned from the cache when the user intended to get a fresh token.

``` csharp
var accessTokenTenantA = await _tokenManagementService.GetAccessTokenAsync(
    "my-token-client",
    new TokenRequestParameters()
    {
        Parameters =
        {
            // I believe this parameter is unused when deciding to reuse a cached token?
            { "tenant", "A" }
        }
    },
    cancellationToken
);

var accessTokenTenantB = await _tokenManagementService.GetAccessTokenAsync(
    "my-token-client",
    new TokenRequestParameters()
    {
        Parameters =
        {
            // I believe this parameter is unused when deciding to reuse a cached token?
            { "tenant", "B" }
        }
    },
    cancellationToken
);
```

Is this a problem you have ever encountered?

**Comment by josephdecock** [comment]
You're correct, those parameters aren't included in the cache key by default. We recommend that you customize the generation of cache keys by overriding `GenerateCacheKey`.

**Comment by sliekens** [comment]
Okay, that will work for me. Thanks.

For future reference, how I did it:

``` cs
// Register this class as 'IClientCredentialsTokenCache' BEFORE you do 'AddClientCredentialsTokenManagement'
public class PerTenantClientCredentialsTokenCache : DistributedClientCredentialsTokenCache
{
    public PerTenantClientCredentialsTokenCache(
        IDistributedCache cache,
        IOptions<ClientCredentialsTokenManagementOptions> options,
        ILogger<DistributedClientCredentialsTokenCache> logger
    )
    : base(cache, options, logger)
    {
    }

    // Override the default cache key format to include the Tenant parameter
    // because tokens must not be reused across tenants
    protected override string GenerateCacheKey(
        ClientCredentialsTokenManagementOptions options,
        string clientName,
        TokenRequestParameters? parameters = null
    )
    {
        var suffix = "::t_" + parameters.Parameters["tenant"].Single();
        return base.GenerateCacheKey(options, clientName, parameters) + suffix;
    }
}
```

Then in the application root:

``` cs
services.AddDistributedMemoryCache();

// ** BEFORE AddClientCredentialsTokenManagement **
services.AddTransient<IClientCredentialsTokenCache, PerTenantClientCredentialsTokenCache>();
services.AddClientCredentialsTokenManagement()
    .AddClient(...);
```
