### ISSUE TITLE
Cookie accidentally shared between subdomains of my application?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#640]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
7.0.105
**Describe the bug**
I have 2 React.JS / Next.JS applications running in 2 different subdomains. The apps are using Identity server. It appears that when one of the application logs in the user, the second application automatically logs in with the same user credential in a different browser tab. The browser debugger shows they have different cookies with different `Domain`s. I don't have the chance to capture the cookie of Identity server as it disappears after the login.

Identity server logs shows that the second app running in the second browser tab does make a request back to the server and it immediately, falsely identify with the first login in the first app.

How to fix this?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**
2 different web applications at different subdomains should not share the server cookie.

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by khteh** [comment]
Not single sign-on. These 2 independent applications should not automatically sign in with each other's user credentials although they use the same Identity server.

**Comment by khteh** [comment]
https://github.com/dotnet/aspnetcore/issues/47998

**Comment by brockallen** [comment]
> Not single sign-on. These 2 independent applications should not automatically sign in with each other's user credentials although they use the same Identity server.

This is what you have designed by having the two apps trust the same SSO provider. If you don't want that, then either use different SSO providers or use the OIDC prompt param mentioned above.

**Comment by khteh** [comment]
Does SSO only work on subdomains? How would IdentityServer behave if they are from different domains?

**Comment by josephdecock** [comment]
You can definitely have single sign on regardless of the domains of the applications. 

Another option for you to prevent SSO is to set the SSO lifetime of the IdentityServer client configuration. You can set that lifetime to zero and the effect will be that whenever a user is redirected to IdentityServer as part of an OIDC challenge for that client, they will have to authenticate again. With this configuration you would be controlling the sso behavior from identity server, rather than forcing each client application to set its prompt parameter.

**Comment by khteh** [comment]
How to set that SSO lifetime at the server? Does that mean user has to authenticate again in a different browser tab / window of the same application?

**Comment by josephdecock** [comment]
SSOLifetime is a property of the client configuration model. It controls how long an SSO session will be used before forcing the user to log in again, regardless of tabs.
