### ISSUE TITLE
Use Post instead of redirect (302) to login page.

### ISSUE THREAD

**Issue by JeroenBer** [DuendeSoftware/Support#643]
During penetration testing one of the security issues was that security related information was visisble in the query string.
E.g.

We first go to:
- /connect/authorize

Since we are not logged in we are redirected (302) to:
- https://hostname/identity/Account/Login?ReturnUrl=%2Fidentity%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dblabla-bff%26redirect_uri%3Dhttps%253A%252F%252Fexample.dev.blabla.nl%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520offline_access%2520example%2520authorization%26code_challenge%3DB5ScoS6qOXM0cKQVq0kcFNzgQIIeHHo4pf13QgjraHs%26code_challenge_method%3DS256%26nonce%3D638186240606352364.NTJlNGY1ZjktNmIzMC00NmJmLWE2ODUtMjgxMjg4NmI1Yzk1YWFlYTg4MzAtYjZiNi00OTIyLThhZWEtMGVhNWUyZDY2ODJj%26state%3DCfDJ8Ip2fySxMPhMnqNPW3msCQHL2X8VNZh_QbyNV1sp7v5Cn_V1DdeNjp4SXotE2pLTRgzV0zBveq5xAXkhQwT63o910uNucjGGFCxiXjo674yvLEfHCZsvphq_HxHa4j3dzY--a2-v0Ln1F_C64zwn99pAxwqW1xxvdGor3VKZir5h7DA0kAku4zmsrpzA1nR8zqEyHdYxmcxznJjw1IARNg1qwLJ8W5Y4jPlFhVjwVAtfjKZ2JqKhNl22oL7gJgYEmlhDmeOMfC-8_Yuj1uOBSOZ27fwzGjaqC7TGE2ZKrhjGRMp_bkOrs9_TpaFKjvTc2i3jXWm_8kacvAKxe53R9RANAYmfmlMppRCIwnP9Ol2f5nyYhHl4XV5GYuY7N9JNKQ

Their recommendation is to use POST instead of GET for this call since it contains information like "code_challenge". Their argument is that this is slightly more secure (not sure, maybe because of request logging in proxies/webservers etc and browser history). Do you agree with this ?

So I looked in the source code and I thought may this could be an option to use POST instead of redirects (302). This is also done in OpenIdConnect (Option AuthenticationMethod). So basically I would probably need to be modified here:
https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Endpoints/Results/LoginPageResult.cs

Depending on an option it could do a POST, example code from OpenIdConnect on how to do this:
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs

```
        if (Options.AuthenticationMethod == OpenIdConnectRedirectBehavior.RedirectGet)
        {
            var redirectUri = message.CreateAuthenticationRequestUrl();
            if (!Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute))
            {
                Logger.InvalidAuthenticationRequestUrl(redirectUri);
            }

            Response.Redirect(redirectUri);
            return;
        }
        else if (Options.AuthenticationMethod == OpenIdConnectRedirectBehavior.FormPost)
        {
            var content = message.BuildFormPost();
            var buffer = Encoding.UTF8.GetBytes(content);

            Response.ContentLength = buffer.Length;
            Response.ContentType = "text/html;charset=UTF-8";

            // Emit Cache-Control=no-cache to prevent client caching.
            Response.Headers.CacheControl = "no-cache, no-store";
            Response.Headers.Pragma = "no-cache";
            Response.Headers.Expires = HeaderValueEpocDate;

            await Response.Body.WriteAsync(buffer);
            return;
        }
```

**Comment by JeroenBer** [comment]
Any thoughts on this if it would be a security improvement ?

**Comment by JeroenBer** [comment]
Thanks, I agree. I think PAR would be a great solution for it. We would like to have it in the next release.

**Comment by brockallen** [comment]
Our current plan is to have it for 7.0.0.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
