### ISSUE TITLE
OAuth client library

### ISSUE THREAD

**Issue by apetrut** [DuendeSoftware/Support#644]
Hi,

I am using Duende version 6 with .NET 6. I am looking for an Angular OAuth library that I can use in an Angular project.

Do you recommend any angular OAuth libraries to be used with Duende?

Thanks.

**Comment by josephdecock** [comment]
Our recommendation is to [avoid architectures where tokens are available to javascript](https://docs.duendesoftware.com/identityserver/v6/bff/overview/). Instead, use the BFF pattern. Our BFF tooling can help with that, but even if you're not using our tooling, the pattern is the one that we, and the IETF [recommend.](https://docs.duendesoftware.com/identityserver/v6/bff/overview/)

**Comment by apetrut** [comment]
@josephdecock BFF uses both client and server in the same solution. Our current setup is an Angular app running separately than the back-end app. I believe with our setup we cannot implement BFF unless you have some sample were the client and server sit separately.

**Comment by josephdecock** [comment]
You definitely can split the front and back ends of the bff. The main thing that needs to happen is that browsers need to include cookies in their requests to the bff from the front end. You can make this happen if you arrange for the front and back ends to be on sibling subdomains (e.g., bff.example.com and app.example.com). You'll also need to set a flag in your fetch requests to "include credentials". We have a sample [here](https://github.com/DuendeSoftware/Samples/pull/93) that isn't yet officially released (associated docs need to get updated too).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by apetrut** [comment]
@josephdecock Sure, thanks.
