### ISSUE TITLE
Should security headers be present by default?

### ISSUE THREAD

**Issue by merijndejonge** [DuendeSoftware/Support#646]
I'm in the process of protecting all my endpoints with proper security headers. 
I'm concerned about the missing security headers of duende identity server endpoints.
On securityheaders.com one can see that there are several headers missing:

- https://securityheaders.com/?q=https%3A%2F%2Fdemo.duendesoftware.com

Is there a particular reason that headers like Strict-Transport-Security, Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, or Permissions-Policy headers are not present by default?

Is there a set of security headers with proper values that you can recommend to secure the endpoints of duende identity server?

**Comment by brockallen** [comment]
The UI for IdentityServer is your code, so you would need to add those in your implementation based on your use cases and which of those do and don't make sense for your implementation. We only provide sample UI code for illustrating the core workflows (login, etc).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by merijndejonge** [comment]
Thanks. It can be closed.
