### ISSUE TITLE
Isolating Clients from Single Sign On

### ISSUE THREAD

**Issue by StuFrankish** [DuendeSoftware/Support#649]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
.Net Core 7

**Question**
I have a use case for wanting our Identity Server to **not** automatically pass on a Single Sign On session to a specific client, so that navigating to that client requires the user to sign in.
Is there a way for us to configure, either in the Client Entity configuration or the client itself that would do this?

Initially I thought that changing the `authenticationSchemes` might do this but it doesn't appear to work like that.
```c#
[HttpGet]
public IActionResult SignIn(string origin)
{
    var redirectUrl = string.IsNullOrWhiteSpace(origin) ? Url.Action(action: "Index", controller: "Home") : origin;
    return Challenge(properties: new() { RedirectUri = redirectUrl }, authenticationSchemes: "app-oidc");
}
```
Startup.cs;
```c#
services.AddAuthentication(options => {
    options.DefaultScheme = "Cookies";
    options.DefaultChallengeScheme = "sen-oidc";
})
.AddCookie(authenticationScheme: "Cookies", (options) => {
    options.Events.OnSigningIn = FilterGroupClaimsAsync;
    options.LoginPath = "/Account/SignIn/";
    options.LogoutPath = "/Account/SignOut";
    options.AccessDeniedPath = "/Account/AccessDenied";
    options.SlidingExpiration = true;
    options.ReturnUrlParameter = "origin";
    options.SessionStore = new RedisCacheTicketStore(options: new() {
        Configuration = Configuration.GetValue<string>(key: "Azure:Redis:ConnectionString")
    });
})
.AddOpenIdConnect(authenticationScheme: "sen-oidc", options => {
    Configuration.Bind(key: "Sentinel", options);
    options.SetCustomOidcOptions();
});
```

```c#
public static void SetCustomOidcOptions(this OpenIdConnectOptions options)
{
    options.TokenValidationParameters = new()
    {
        NameClaimType = SentinelClaimType.Name,
        RoleClaimType = SentinelClaimType.Role
    };

    options.SignInScheme = "Cookies";
    options.ResponseType = "code";
    options.UsePkce = true;
    options.Scope.Add(item: "openid");
    options.Scope.Add(item: "profile");
    options.Scope.Add(item: "roles");
    options.Scope.Add(item: "offline_access");
    options.SaveTokens = true;
    options.GetClaimsFromUserInfoEndpoint = true;

    options.SetCustomClaimActions();
}
```
I've also tried changing `options.SignInScheme` from `Cookie` to `Cookie-SEN` but I'm getting an error where the app is failing to find/load a handler for `Cookie` so I've probably missed something.

Ultimately, is what we want to be able to to possible and is there is best option for doing it?

**Comment by StuFrankish** [comment]
To further clarify - we want to be able to have multiple users signed into different applications at the same time.
For example - we have four client applications, signing in triggered challenged by either app 1, 2 or 3 should establish an SSO session that can only be shared with those apps. When the user then navigates to app 4, we would want the user to be prompted to sign in to a new SSO session with new credentials that only that client app has access to, leaving the first SSO session as it was under the first user.

Digging around I see the `options.Prompt` property of `OpenIdConnectOptions` in the client can be set to `login`.
This does appear to have the desired effect but without extensive testing I'm not 100% sure it's the way to go yet.
I'm still reading some documentation here https://auth0.com/docs/authenticate/login/max-age-reauthentication

Does setting this value and re-authenticating over-write the existing SSO session in IDS?

**Comment by josephdecock** [comment]
Preventing a client application from using the single sign on session is straight forward. The client configuration includes a single sign on lifetime and you could set that to zero so that whenever that client initiated a challenge the user would have to enter their credentials again.

Multiple signed on users depending on the client is much more complicated. The asp.net cookie authentication handler that manages the session doesn't include a mechanism to express multiple signed in users. You will have to build code on top of that which will store multiple authentication tickets (one for each sign in) and switch between them. 

More fundamentally, this adds a great deal of complexity to your identity server implementation because you will have to consider the semantics of multiple identities for every protocol interaction. 

A much simpler approach would be to have each group of applications that can perform single sign on within the group connect to a distinct instance of identity server. For example, apps 1, 2, and 3 could use id1.example.com as their authority, while apps 4 and 5 could use id2.example.com as their authority. This would result in distinct sessions for the two sets of applications, with a single sign on within but not between the two groups. (Make sure your license allows multiple deployments of identity server before you start down this road though).

**Comment by josephdecock** [comment]
Oh and yes you could use prompt login to accomplish the same thing as setting a lifetime by zero. The difference is basically where do you control the behavior - identity server config or client parameter. In either case, logging in again replaces the old session.

**Comment by StuFrankish** [comment]
> Multiple signed on users depending on the client is much more complicated. The asp.net cookie authentication handler that manages the session doesn't include a mechanism to express multiple signed in users. You will have to build code on top of that which will store multiple authentication tickets (one for each sign in) and switch between them.

> In either case, logging in again replaces the old session.

Thanks @josephdecock - I just want to make sure that I'm understanding correctly.

We're not looking to handle any single app having multiple signed in users simultaneously, what we're hoping for is to establish multiple SSO sessions for a single user, one of which is reserved for the isolated client app - something I thought the `aud` claim would allow us to do.

Having multiple instances of Identity Server is something I believe our Enterprise License would allow, but it would double the infrastructure cost to host it - not something I think I would get past the guys in FinOps.

**Comment by josephdecock** [comment]
> We're not looking to handle any single app having multiple signed in users simultaneously, what we're hoping for is to establish multiple SSO sessions for a single user, one of which is reserved for the isolated client app - something I thought the `aud` claim would allow us to do.

The `aud` claim sets the intended audience of a token. An id token will set the `aud` claim to the client that requested the oidc login, and access tokens can have their audience set to a particular API where they are intended to be used, using resource indicators. I don't think there's really a way to use this to create SSO separation.

> how does Identity Server know to replace the existing session rather than create a new session for that login event?

IdentityServer normally uses the existing session, but if you set prompt=none or if the sso lifetime has passed, then the Authorization Interaction Response Generator will instead send the user to the login page.

> Having multiple instances of Identity Server is something I believe our Enterprise License would allow, but it would double the infrastructure cost to host it - not something I think I would get past the guys in FinOps.

Not necessarily - the hosting infrastructure could all be the same, with just 2 different dns names for the same IdentityServer host. IdentityServer normally infers the issuer uri that is used in tokens and discovery from the incoming http request.

**Comment by StuFrankish** [comment]
> Not necessarily - the hosting infrastructure could all be the same, with just 2 different dns names for the same IdentityServer host. IdentityServer normally infers the issuer uri that is used in tokens and discovery from the incoming http request.

Thanks @josephdecock, 
I think this is the approach we're going to try and take - is there any other client config that we would need to set other than just pointing the OIDC Authority to the secondary DNS name?

**Comment by josephdecock** [comment]
> is there any other client config that we would need to set other than just pointing the OIDC Authority to the secondary DNS name?

I don't think so - though I admit this is a somewhat uncommon setup. Please do test it out and let us know if you run into any issues!

**Comment by josephdecock** [comment]
I'm going to close this issue, but feel free to reopen if you run into problems.
