### ISSUE TITLE
Cross tenant authentication breach 

### ISSUE THREAD

**Issue by Sasuke-420** [DuendeSoftware/Support#651]
I am using duende identity server 6.2.3 with .net version 6.0

I have two applications both are for different tenants when i logged into one application and then open another app (both are using different client id and different user management) What i want is that i need to check authentication scheme which user has in his host address.

Can you please help me with this?

**Comment by brockallen** [comment]
This sounds like an authorization issue in the app (or API) based on which tenant the user has logged into. I'd suggest adding a tenant claim (if you don't already issue one) to the client app (and possibly in your access tokens), and then in the client app (or API) check the tenant claim against which tenant data is being accessed (however your client app or API knows that).

**Comment by brockallen** [comment]
Also, possibly related, we have a ValidateTenantOnAuthorization [option](https://docs.duendesoftware.com/identityserver/v6/reference/options/#main) to ensure that when a client makes a request with an tenant [acr_values](https://docs.duendesoftware.com/identityserver/v6/reference/endpoints/authorize/#optional-parameters) that the current user must login to the same tenant. This also might help.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
