### ISSUE TITLE
check_session_iframe cannot be used when server side sessions expire at the server level

### ISSUE THREAD

**Issue by acasciani** [DuendeSoftware/Support#652]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
.NET Core 6

**Describe the bug**
When using server-side sessions, clients that use the `check_session_iframe` feature are not notified when the server side session is expired in the database.

**To Reproduce**

We're implementing server side session on the Identity Server using the server side functionality built in. We have a Blazor WASM and a .NET Framework application which are both separate clients in the IDP. When I login through SSO to the WASM application, I can then SSO to the .NET Framework application in the same browser without re-entering my credentials. I also see the shared row in the `ServerSideSessions` database table. Everything works as expected. In the WASM application we are using `check_session_iframe` with the AuthenticationService.js from .NET Core. When the user logs out of our .NET Framework application, it triggers global sign-out and the WASM application is signed out using the `check_session_iframe` functionality. This works as expected because the session cookie is removed from the browser. However, if the session is terminated at the server (e.g. the session becomes inactive due to the `Expired` column), then there is no way for the browser to be notified that session is terminated and the `check_session_iframe` cannot work.

**Expected behavior**

We understand that the [recommendation](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/inactivity_timeout/#clients-with-refresh-tokens) is to either handle this using back-channel notifications or on a refresh token call, however, due to requirements neither is an option at this time for us. 

We've tested a solution where on `Duende.IdentityServer.Endpoints.Results.CheckSessionResult` the generated HTML includes the following tag: `<meta http-equiv="refresh" content="XSeconds" />`
We also added an option on the ServerSideSessions `_options.ServerSideSessions.ReloadCheckSessionIFrameFrequency` which is a nullable TimeSpan. If the value is null, then the meta tag is not included. If the value is not null, then seconds property is used for XSeconds. Doing this allows the browser to refresh the cookies when that endpoint is iFramed.

1. Is there a different way to handle this use case?
2. Is this functionality something Duende would consider adding to the product? We'd be happy to put together a pull request if this would expedite the introduction of this feature?

**Comment by acasciani** [comment]
So it looks like refreshing the checksession on an interval in the iFrame will not work as when the checksession is refreshed when there is half the session lifetime left, it extends the session again. Here are the logs I am seeing

```
[16:05:35 Debug] Duende.IdentityServer.Endpoints.CheckSessionEndpoint
Rendering check session result

[16:05:35 Debug] Duende.IdentityServer.EntityFramework.Stores.ServerSideSessionStore
Found server-side session ***** in database: true

[16:05:35 Debug] Duende.IdentityServer.Stores.ServerSideTicketStore
Renewing AuthenticationTicket for key *****, with expiration: "2023-05-08T20:07:35.0000000Z"

[16:05:35 Debug] Duende.IdentityServer.EntityFramework.Stores.ServerSideSessionStore
Updated server-side session ***** in database
```

Any suggestions to support this?

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by acasciani** [comment]
This issue can be closed. Thank you!
