### ISSUE TITLE
Valid user session but unauthorized calls to remote API

### ISSUE THREAD

**Issue by tom-crayon** [DuendeSoftware/Support#653]
**Which version of Duende BFF are you using?**

Duende.BFF 2.0.0

**Which version of .NET are you using?**

.NET 7

**Describe the bug**

This is our first application of the BFF pattern. We've encountered an issue where BFF endpoints return responses indicating the user is still signed in and their session is valid, however calls to the remote API via BFF result in HTTP 401 Unauthorized responses.

Digging into the issue we could see BFF makes a request to IdentityServer for a new token, but it was not successful as the refresh token had already been used. I found discussion about a similar issue (non-BFF) that pointed to the Duende article [client credentials should not rotate refresh tokens](https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/#confidential-clients-should-not-rotate-refresh-tokens) which seemed relevant since rotation is enabled on the client, but I wanted to get advice on best practice.

What is the *right* way to configure an IdentityServer v6 client when using BFF? What are the important settings, and what is the recommended way to set them? The client is configured for the 'authorization code with PKCE' flow, but I understand requests are being made on the back channel and authenticated using client credentials.

One area that is unclear is the interplay between the ASP.NET session (cookie) lifecycle and the remote API token lifecycle. Do you have recommended settings to keep the two in sync so a user doesn't encounter a situation where they have a valid session but API responses are failing.

**To Reproduce**

It's not straight forward to reproduce. After first signing in, leave the browser until the token would have expired then start interacting with the app so calls are made via BFF to a remote API. Sometimes the issue occurs.

**Expected behavior**

I expect BFF to maintain a valid token for a remote API while the user has a valid session with the ASP.NET BFF web app.

**Log output/exception with stacktrace**

None

**Additional context**

None

**Comment by josephdecock** [comment]
We do [recommend ](https://docs.duendesoftware.com/identityserver/v6/bff/tokens/#reuse-of-refresh-tokens)that you use ReUse refresh tokens with your BFF. Other than that, it sounds like you're configuring things the right way - certainly using auth code + PKCE is a good start.

Normally the BFF should automatically manage the access token. When it would expire, the refresh token is used to obtain a new one automatically. Rotating refresh tokens make this less reliable and can cause the issue that you're having. Switching to ReUse refresh tokens should prevent the problem.

**Comment by tom-crayon** [comment]
Thanks, I missed that when reviewing the docs. The change has been applied to our environments, we'll monitor for issues form here.

**Comment by wantwi** [comment]
hello,
am using Duende.BFF 2.0.0 with .Net 6.0.
I keep getting 401 for the bff/user endpoint even though I have successfully login into my application. This occurs after publishing my app unto a development server. Please is there something am missing out. I want to make a recommendation for my company after a successful implementation.
