### ISSUE TITLE
Re-autthenticate Client when Cookie has expired => Using a Refresh Token???

### ISSUE THREAD

**Issue by cliffi30** [DuendeSoftware/Support#655]
We use the latest version of Duende IdentityServer and .net 6 on idp and mvc clients.

In our environment we don't yet have any API, however we have a number of clients that authenticate using in OpenId connect, receiving the id_token as well ass the access token. These clients don't access any api's.
On the client we use CookieAuthenticationDefaults.AuthenticationScheme to manage the user after he signed in on our idp.
We have been used to use a relatively short Cookie lifetime on our clients. When the cookie has expired the client would then re-authenticate with the id using the standard (code) flow.
Everything works fine, however:

Regularly we have the situation where our users are signed in and then open a view that contains a form. The user takes a while to complete the form and then submits the form. Now, if the cookie has expired in the meantime the client will redirect to the idp, re-authentication happens (without user interaction) and due to the returnUrl in the query, the idp will redirect to the action on the client. => Naturally the form parameters are gone and in worst case there is no Action the meets the GET (return)request from idp.

I have been looking around for a proper solution to re-authenticate the user somewhere in the request pipeline in the backend and  without returning the redirect to the idp to the frontend. This way the post request would not fails. However I am not sure what the recommended and state of the art solution would be?

From what I have seen I could:

1) Extend the cookie lifetime on the client and use sliding cookie lifetime
Yes, that would most likely avoid a large number of failing request. However it would still leave the odd number of cases where the return from the idp would end up in a 404 as the matching GET Action does not exist for all POST Actions.

2) 
Start using Refresh Tokens
Intercept i.e. Cookie Validation on the client and investigate the parameter ".token.expires_at". Bases on that outcome I could manually issue a token refresh with the ipd and update the tokens on the client. I have seen some information that suggests this as solution. However according to some post the access token should only be used to manage access on apis on not on a client. I am also not sure if implementing that custom logic opens up other issues that I am not aware of yet.

```
public override async Task ValidatePrincipal(CookieValidatePrincipalContext context)
        {
            if (context.Properties.Items.ContainsKey(".Token.expires_at"))
            {
                // get the expires_at value & parse it
                var expiresAt = context.Properties.Items[".Token.expires_at"];

                var expiresAtAsDateTimeOffset =
                    DateTimeOffset.Parse(expiresAt, CultureInfo.InvariantCulture);

                if (expiresAtAsDateTimeOffset > DateTime.UtcNow)
                {
                    // Use RefreshToken to gain new access token
                    // update tokens and expires at time
                }
            }
        }
```
3) Different Approach?

I have checked the Duende Documentation as well as the samples. However I was not able to find anything helpful in this direction. Please let me know what you think. I am sure that tweaking solution 1) would give our users a decent work experience and we could mostly avoid that our users uses some of their rather large form input just because the have the take longer than expected to complete a form...

**Comment by josephdecock** [comment]
I think a sliding cookie would accomplish what you're going for in the simplest way. The return from the idp should always go to the same url, so I'm not understanding where the 404s come in. Usually the route within the client is stored within the authentication properties. So the idp redirects back to the endpoint that the OIDC handler is listening on, the handler exchanges codes for tokens, validates the tokens, and starts the session, _and then finally redirects again to the url in the authentication properties._

**Comment by cliffi30** [comment]
ok, so using the sliding cookie and a cookie expiration lifetime of an hour or two will be fine for most cases. However the 404 will still happen if someone is on lets say /Products/Index and posts a form to Products/Create if there is no Products/Create GET action method. Your are right in saying that the authentication properties will keep track of the return url (in that case /Products/Create), however the Action method does not exist and therefore our error handling will display the 404 page in such a case.
I have seen people storing the post request parameters on the client in cache, when the cookie has expired, then going through the code workflow and picking them up on the return request from the idp. However that seems to be an awful lot of work to do just to handle the odd case where the user is to slow completing the form withing cookie lifetime.
I was hoping that the re-authorization could be done somewhere in the backend between the client and the idp (similar to using a refresh-token to get a new accesstoken for an api when the access token has expired). I guess that is not possible... => Kind of using the access token in some way on the client itself?

**Comment by brockallen** [comment]
This is a time old problem even before OIDC existed. Imagine you have your app with a local login page. You have that form, the user waits too long, and then on POST they're not logged in anymore -- they will be redirected to login and lose the form data. 

If they're on that form a long time, then you have to decide for your app architecture does that mean they're still logged in or not. If this is a valid use case, then perhaps your app needs some custom logic in JavaScript to extend the session with its own backend. 

So I don't see this as an IdentityServer specific problem.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by cliffi30** [comment]
Hello Joseph, thanks for asking back. We decided to stick to the sliding cookie and to monitor if and how often one of our customers runs into that issue. Afterwards we will see if we need any further customizing. Feel free to close the issue. Thanks
