### ISSUE TITLE
Reference Tokens when using BFF with YARP

### ISSUE THREAD

**Issue by dolphyns** [DuendeSoftware/Support#656]
Hi

Is there any sample/example on how to use Reference Tokens when using BFF with YARP. Apparently, there is no extension method to be used. When using regular JWT there is an extension method called .WithAccessToken(...) with a parameter to identify the token type but I believe it only works for JWTs, not Reference Tokens.

My end-game goal is to be able to terminate a session in the IDP and that be reflected, immediately, in the client. 

Can somebody help me here?

10x

Dolphyns

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
