### ISSUE TITLE
What is the best way to remove idsrv cookie or set short timeout after login

### ISSUE THREAD

**Issue by ilaneini** [DuendeSoftware/Support#657]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
.NET 7.0

**Describe the bug**
We are having an issue with one of our customers where they need to remove the idsrv cookie right after login. What is the best way to achieve this?

**Comment by JeroenBer** [comment]
I think you want to set the "UserSsoLifetime" property on the Client you define. 

e.g. 
```
client.UserSsoLifetime = 120
```

**Comment by brockallen** [comment]
Another idea is that you could sign the user out when the response to the authorize endpoint is returning results to the client. This would involve writing a custom [Authorize Interaction Response Generator](https://docs.duendesoftware.com/identityserver/v6/reference/response_handling/authorize_interaction_response_generator/). I'd derive from our base and if it's successful then you can call SignOutAsync to have the outbound response remove the user's session cookie.

**Comment by ilaneini** [comment]
Setting UserSsoLifetime seems to have done the trick. Thanks
