### ISSUE TITLE
client_credentials grant type with Roles for API access

### ISSUE THREAD

**Issue by gavinmckay** [DuendeSoftware/Support#658]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

We have the client_credentials API access working and are able to authorize our client access using that. We are expanding the use of Roles via the Authorize decoration on our APIs, but are a bit unclear on the connection between an API gettting authorizing access and requesting the particular Role(s) it needs.

I'm pretty sure it's related to [scopes](https://docs.duendesoftware.com/identityserver/v5/fundamentals/resources/api_scopes/), but how do we map a scope to a Role? Is that the right way to go? We only have a single "api" scope which works for accessing all the methods it is allowed to, but want to apply role-based access to APIs using clientid+secret as well.

**To Reproduce**

_Example code:_

    [Authorize]

        [HttpGet("abc", Name = "ABC")]
        [Authorize(Roles = "Role1,Role2,Role3")]
public class RoleAccessOnly()

**Expected behavior**

Able to authenticate to an API and assign one or more roles for access control.

**Log output/exception with stacktrace**

```
n/a
```

**Additional context**

n/a

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
