### ISSUE TITLE
Disable Https or set base url to an Http url?

### ISSUE THREAD

**Issue by WarcRianMostert** [DuendeSoftware/Support#66]
**Which version of Duende IdentityServer are you using?**
6.0.0

**Which version of .NET are you using?**
net6.0

**Describe the bug**
Is it possible to use IdentityServer over Http only (no Https)?
We use Kubernettes in our Dev/Staging/Prod environments.
Calls to our Load Balancer are Enforced/Redirected to Https but internal traffic between nodes in Kubernettes is Http.

**To Reproduce**
At first I deployed the Identity Server project ( practically a copy of https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Quickstarts/1_ClientCredentials/src/IdentityServer )
Then when I called the IdentityServer Discovery Endpoint I got the following error message: 

> Issuer name does not match authority

So I set the IssuerUri to the Https version of my Identity Server url
`builder.Services.AddIdentityServer(options => 
{     
    options.IssuerUri = "https://MYURL";
 });
`

Now I get a different error when I run `HttpClient.GetDiscoveryDocumentAsync("https://MYURL")`
> Endpoint does not use HTTPS: http://MYURL/.well-known/openid-configuration/jwks

I don't see a way of setting that url specifically, is there a way to set the baseUrl or disable Https?

**Comment by brockallen** [comment]
Have a look at the deployment section of our docs:

https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/
