### ISSUE TITLE
backend to backend communication 

### ISSUE THREAD

**Issue by DevOnBike** [DuendeSoftware/Support#660]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

6

**Describe the question**

i have identity server running and I have extended it to serve additional REST endpoint - like get decription of something.
Now i have other api (microservice) that whats to get data from this identity server endpoint but to be able to authenicate by using httpclient.

it is simple backend to backend communication.
How to authenicate in is4?
can u provide sample of such flow?

**Comment by StuFrankish** [comment]
@DevOnBike - Here's a pointer to the documentation on adding API resources to Identity Server.
https://docs.duendesoftware.com/identityserver/v6/apis/add_apis/

I'm working on protecting some existing API's as well but have taken a different approach which @josephdecock has been super helpful with.
https://github.com/DuendeSoftware/Support/issues/628

**Comment by josephdecock** [comment]
Thanks @StuFrankish - I'll just add that typically authentication and authorization of backend-to-backend communication is handled through the client credentials flow. Our quickstart tutorial series starts off with exactly that scenario in [quickstart 1](https://docs.duendesoftware.com/identityserver/v6/quickstarts/1_client_credentials/).

**Comment by DevOnBike** [comment]
I've managed to setup everything using this page: https://docs.duendesoftware.com/identityserver/v6/tokens/requesting/ and mahcine-to-machine communication section.

Thx
