### ISSUE TITLE
Remember Me not persisting

### ISSUE THREAD

**Issue by Yinamil** [DuendeSoftware/Support#663]
Using v5...
I have a client that is wanting to have a 'remember me' and 'remember device' set to 30 days (for both). I have the client token expiration set to 30 days in the database, and the following code on both the Identity Server login, as well as the webapp that is using identity server for its identity provider. 
When I run the site locally, the logic is working as intended. I have gone 4 days now without having to reauthenticate. In our development environment, even with the cookies still valid, I have to reauthenticate after 30 minutes. 
Below is a screen shot of the cookies that are not expired, but it is prompting me to login again. 
![image](https://github.com/DuendeSoftware/Support/assets/11650534/484c2882-0c82-4dff-8192-a10d3a1f4939)
The cookies with 'GoldenEye' in the name are from the webapp, and the other two are from identity server. 
Here are the settings I have for the identity server, and then the web app. A note... When running the website locally (in visual studio) I have it pointing to the development server Identity Server. The local instance - with the same settings - I haven't had to log in to the site in 4 days. The dev instance, I have to log in again after 30 minutes. As far as I can tell, the settings are correct to set the identity token for 30 days.
**Identity Server**
```
builder.Services.AddIdentityServer(options =>
{
    options.LicenseKey = builder.Configuration.GetValue<string>("DuendeKey");
    options.KeyManagement.Enabled = false;
    options.Authentication.CookieLifetime = TimeSpan.FromDays(30);
    options.UserInteraction.LogoutUrl = "/Logout/Index";
})
    .AddConfigurationStore(options =>
    {
        options.DefaultSchema = "Identity";
        options.ConfigureDbContext = b => b.UseSqlServer(connectionString,
            sql => sql.MigrationsAssembly(migrationsAssembly));
    })
    .AddOperationalStore(options =>
    {
        options.DefaultSchema = "Identity";
        options.ConfigureDbContext = b => b.UseSqlServer(connectionString,
            sql => sql.MigrationsAssembly(migrationsAssembly));
    })
    .AddAspNetIdentity<AOEIdentityUser>()
    .AddProfileService<AOEProfileService>()
    .AddAuthorizeInteractionResponseGenerator<AOEAuthorizeInteractionResponseGenerator>()
    .AddSigningCredential(signingCredential.key, signingCredential.signingAlgorithm);
builder.Services.AddScoped<AOEOAuthEvents>();
var auth = builder.Services.AddAuthentication();

builder.Services.AddScoped<AOECookieAuthenticationEvents>();
builder.Services.ConfigureApplicationCookie(options =>
{
    // Cookie settings
    options.Cookie.HttpOnly = true;
    options.Cookie.Path = @"/";
    options.ExpireTimeSpan = TimeSpan.FromDays(30);
    options.SlidingExpiration = false;
    options.EventsType = typeof(AOECookieAuthenticationEvents);
    options.Cookie.MaxAge = TimeSpan.FromDays(30);
});
builder.Services.Configure<CookieAuthenticationOptions>
(IdentityConstants.TwoFactorRememberMeScheme, options =>
{
    options.ExpireTimeSpan = TimeSpan.FromDays(30);
    options.SlidingExpiration = false;
    options.Cookie.Path = @"/";
});
```
**Web App**
```
builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = "oidc";
})
.AddCookie(options =>
{
    options.Cookie.Name = "AOE.Identity.GoldenEye";
    options.LogoutPath = "/LogOut";
    options.ExpireTimeSpan = TimeSpan.FromDays(30);
    options.Cookie.MaxAge = TimeSpan.FromDays(30);
    options.Cookie.Path = @"/";
})
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = configuration.GetValue<string>("IdentityServer:Authority");

    options.ClientId = configuration.GetValue<string>("IdentityServer:ClientId");
    options.ClientSecret = configuration.GetValue<string>("IdentityServer:ClientSecret");

    // code flow + PKCE (PKCE is turned on by default)
    options.ResponseType = "code";
    options.UsePkce = true;
    options.UseTokenLifetime = true;

    options.Scope.Clear();
    options.Scope.Add("openid");
    options.Scope.Add("profile");
    options.Scope.Add("email");
    options.Scope.Add("phone");
    options.Scope.Add("aoe.api.fullaccess");
    options.Scope.Add("role");

    // not mapped by default
    options.ClaimActions.MapJsonKey("tenantId", "tenantId");
    options.ClaimActions.MapJsonKey("tenantName", "tenantName");
    options.ClaimActions.MapJsonKey("role", "role");

    // keeps id_token smaller
    options.GetClaimsFromUserInfoEndpoint = true;
    options.SaveTokens = true;

    options.TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    };
    options.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
    options.CallbackPath = "/signin-oidc";
});
```

**Comment by Yinamil** [comment]
Sorry for the delayed response.
I have been trying to update settings and get things cleaned up. 
One thing I've noticed, there is nothing being written to the 'PersistedGrants' table. Shouldn't I see something written there when they log in with two factor and select remember me? Below is the code from the login screen, and the 2 factor auth login. It is using the microsoft identity methods
Login
`
var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
`
2fa login
`
var result = await _signInManager.TwoFactorSignInAsync(TokenOptions.DefaultEmailProvider, authenticatorCode, rememberMe, Input.RememberMachine);
`

**Comment by Yinamil** [comment]
So the client I am working with wants their login to persist for 30 days without having to log in again when they select 'remember me'. Same with the 2fa. To accomplish this, is it best to set the Identity Token Lifetime/Authorization Code Lifetime to a smaller value (ex: 1 hour), and then allow sliding refresh, and set the 'SlidingRefreshTokenLifetime' to a larger value?

**Comment by josephdecock** [comment]
ID tokens and authorization codes are both use basically immediately after their issue so they don't generally need a one hour lifetime. You're probably fine to leave them as their default values which are shorter. If you use a sliding expiration on your refresh token, its expiration will keep sliding forward as it is used, which might exceed your 30 day requirement. If you want to force the user to definitely authenticate after 30 days, you should set the absolute expiration instead. One last thing to consider is that a "remember me" box doesn't control the refresh token lifetime, it is used to control the session cookie at Identity server.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
