### ISSUE TITLE
`ClientAuthenticationFailureEvent` has no means to identify error

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/Support#666]
**Which version of Duende IdentityServer are you using?**

6.2.X

**Which version of .NET are you using?**

.NET 7

**Describe the bug**

`ClientAuthenticationFailureEvent` includes an `Id` but that it doesn't allow to identify the failure reason.

When a token is requested for a client that does not exist, the event is the following:

```json
{
  "ClientId": "identityserver4-clientcredentialsX",
  "Category": "Authentication",
  "Name": "Client Authentication Failure",
  "EventType": "Failure",
  "Id": 1011,
  "Message": "Unknown client",
  "TimeStamp": "0001-01-01T00:00:00",
  "ProcessId": 0
}
```

When a token is requested with an invalid secret, the event is the following:

```json
{
  "ClientId": "identityserver4-clientcredentials",
  "Category": "Authentication",
  "Name": "Client Authentication Failure",
  "EventType": "Failure",
  "Id": 1011,
  "Message": "Invalid client secret",
  "TimeStamp": "0001-01-01T00:00:00",
  "ProcessId": 0
}
```

There is now away to distinguish the errors and do something with that, except using the message.

> `Timestamp` and `ProcessId` are also strange.

**To Reproduce**

See above.

**Expected behavior**

It would be very useful if this event - and the others for failures - could include an identifier for the error that caused them.

**Comment by josephdecock** [comment]
Thanks for bringing this up. It seems like there are 2 issues here:

1. It looks like there is a bug where the pid and timestamp of events are not getting set.

2. A feature request to add a way to discriminate different events with the same id.

**Comment by josephdecock** [comment]
Looking at this again, this sounds like you may have implemented the `IEventService`. The default implementation uses its `PrepareEventAsync` method to set the pid and timestamp. Most use cases for customizing events can be accomplished by implementing the `IEventSink` instead.

**Comment by hugoqribeiro** [comment]
Hi. It is true that we've implemented `IEventService`, so the problem with `processId` and `timestamp` is our fault.
The issue of `ClientAuthenticationFailureEvent` having no way (some id) to identify the cause of the error, remains.

**Comment by josephdecock** [comment]
We will consider adding an additional identifier to events in the future. I've added the above issue to track that idea. Thanks for your feedback!
