### ISSUE TITLE
Manually expiring signing keys

### ISSUE THREAD

**Issue by aurecchia** [DuendeSoftware/Support#668]
**Which version of Duende IdentityServer are you using?**

v6.2.3

**Which version of .NET are you using?**

7.0

**Describe the bug**

Hello, this is related to an old issue that a colleague of mine was looking at: https://github.com/DuendeSoftware/Support/issues/255 (I didn't want to necro-bump there).

When I picked up the issue, I went through that thread, and indeed the problem we are facing is what @brockallen described: some of our PROD signing keys ended up being protected by non-PROD data-protection keys. These signing keys cannot be unprotected right now and, as far as I understand, in this case they will not even be used to sign new tokens. Still, we would like to get them out of our system.

From what I understand, after these keys are expired they should disappear automatically. I guess I could force them to be removed by temporarily reducing the retention duration (which is quite long in our current configuration) but that would also expire some signing-keys that have no problems.

Is it possible to manually expire some signing keys? Do you have any other suggestion of how to tackle this problem? 

Thank you for your assistance.

**Comment by josephdecock** [comment]
The easy way to clean up these keys is to simply delete them. If you don't have the data protection key for them, then IdentityServer isn't using them and won't validate tokens that are signed with them anyway. As a precaution, I would back up the files or database before you delete them.

**Comment by aurecchia** [comment]
Thanks for your reply. I'll give that a try and see what happens :slightly_smiling_face:
