### ISSUE TITLE
Upgrade to 6.1.0 Found 0 server-side sessions 

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [DuendeSoftware/Support#67]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
.NET 6.0 (core)

**Describe the bug**
I've just upgraded to IdentityServer 6.1.0 with my database backend (database updated too) and I'm getting the following error after my client goes to the login page, enters credentials then selects 'login':

[07:09:30 Debug] Duende.IdentityServer.EntityFramework.Stores.ClientStore
_[ommitted]_ found in database: True

[07:09:30 Debug] Duende.IdentityServer.Stores.ValidatingClientStore
client configuration validation for client _[ommitted]_ succeeded.

[07:09:30 Debug] Duende.IdentityServer.EntityFramework.Stores.ServerSideSessionStore
Found 0 server-side sessions for {"SubjectId": "f978b7e9-c58e-4b23-adfa-df0861fb37ff", "SessionId": "6F7F3350E66867A02F83EC78187D2AB6", "$type": "SessionFilter"}

[07:09:30 Debug] Duende.IdentityServer.Services.DefaultSessionCoordinationService
Due to missing/expired server-side session, failing token validation for subject id f978b7e9-c58e-4b23-adfa-df0861fb37ff and session id 6F7F3350E66867A02F83EC78187D2AB6

[07:09:30 Error] Duende.IdentityServer.Validation.TokenValidator
Server-side session invalid for subject Id f978b7e9-c58e-4b23-adfa-df0861fb37ff and session Id 6F7F3350E66867A02F83EC78187D2AB6.

**To Reproduce**
Update to IdentityServer 6.1.0
Update database for IdentityServer store

**Expected behavior**
The IdentityServer to behave as per before the upgrade - i.e. authorise the user and client to operate as before

**Log output/exception with stacktrace**

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.GetUserInformationAsync(OpenIdConnectMessage message, JwtSecurityToken jwt, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
```

**Additional context**

I've looked for some information on how to resolve the issue and I've also tried truncating the PersistedGrants table in the database - no success.  

Thanks in advance for pointing me in the right direction to solve this.

**Comment by rasaconsulting-sandy** [comment]
I have downgraded back to Duende.IdentityServer 6.4.0 versions now until I can resolve the issue.  I have checked the quickstart and samples code to troubleshoot my issue but these aren't at the latest version of Duende.IdentityServer.  

Thanks in advance.

**Comment by rasaconsulting-sandy** [comment]
FYI further information.  I'm using AspNetIdentity with an EntityFramework SQL Server database store.  I've read through the following documents implementing what I believe is necessary:
- https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/
- https://docs.duendesoftware.com/identityserver/v6/data/ef/#operational-store
- https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/

I've also looked at the code for the templates and samples and they don't appear to have been upgraded to version 6.1.0 as yet.  

The code snippets in my program.cs / configuration setup for the Identity Server is:

    builder.Services.AddIdentity<_[omitted]_, IdentityRole>()
        .AddEntityFrameworkStores<_[omitted]_>()
        .AddDefaultTokenProviders();

   builder.Services
       .AddIdentityServer(options =>
       {
           options.Events.RaiseErrorEvents = true;
           options.Events.RaiseInformationEvents = true;
           options.Events.RaiseFailureEvents = true;
           options.Events.RaiseSuccessEvents = true;

           // see https://docs.duendesoftware.com/identityserver/v5/fundamentals/resources/
           options.EmitStaticAudienceClaim = true;
       })
       .AddAspNetIdentity<_[omitted]_>()

       // this adds the config data from DB (clients, resources, CORS)
       .AddConfigurationStore(options =>
       {
           options.ConfigureDbContext = b =>
               b.UseSqlServer(connectionString, dbOpts => dbOpts.MigrationsAssembly(typeof(Program).Assembly.FullName));
       })
       // this is something you will want in production to reduce load on and requests to the DB
       .AddConfigurationStoreCache()
       //
       // this adds the operational data from DB (codes, tokens, consents)
       .AddOperationalStore(options =>
       {
           options.ConfigureDbContext = b =>
               b.UseSqlServer(connectionString, dbOpts => dbOpts.MigrationsAssembly(typeof(Program).Assembly.FullName));

           // this enables automatic token cleanup. this is optional.
           options.EnableTokenCleanup = true;
           options.RemoveConsumedTokens = true;
           options.TokenCleanupInterval = 3600;
       });


app.UseIdentityServer();

Things work fine under version 6.4.0 - Duende.IdentityServer.AspNetIdentity and Duende.IdentityServer.EntityFramework.

Please let me know if you need further information and again, I appreciate your help with anything you can do to point me in the right direction to solve this myself (fyi - I'm not expecting you to fix my code).

**Comment by brockallen** [comment]
Hello. I have a few questions:

* Did you enabled server-side sessions with a call to `AddServerSideSessions`? I don't see that above. Also, none of the new server-side session code should be running if you omit the call to `AddServerSideSessions`. Also, this is not something you'd just enable if you already have existing login sessions.
* Did you configure the new `CoordinateLifetimeWithUserSession` setting for your clients to `true` as part of the update? Those should default to NULL in the DB.
* Did you configure the new `CoordinateClientLifetimesWithUserSession` setting on the IdentityServer options to `true` as part of the update? It defaults to `false`.

Thanks

**Comment by rasaconsulting-sandy** [comment]
Hi Brock,

Thanks for responding to my issue above.  

I hadn't set the third setting - CoordinateClientLifetimesWithUserSession on my IdentityServer options.

I've set it now and it's all working once I removed the existing PersistedGrants records from the database (we aren't in production yet so it's not a concern).

Another question - will this be included in the samples and templates at a future date?  Just wondering - don't want to put any pressure on anyone to do it.

Many thanks again,
Sandy

**Comment by brockallen** [comment]
> will this be included in the samples and templates at a future date

What is the "this" that you're referring to? Do you mean a sample? We have this sample:

https://docs.duendesoftware.com/identityserver/v6/samples/misc/#session-management-sample

**Comment by rasaconsulting-sandy** [comment]
Hi Brock,

Thanks for your response above.

For "this" I was referring to a sample that includes the 3 items above:
- AddServerSideSessions
- CoordinateLifetimeWithUserSession (in the client)
- CoordinateClientLifetimesWithUserSession

Along with being at the new version 6.1.0.

I see that the sample you pointed me to does include all of these even though it is at the preview version (6.1.0-preview.3).  Note: I also came across the blog post which is helping a lot too - https://blog.duendesoftware.com/posts/20220406_session_management/. (only included in case someone else reading this also finds it helpful).  

Thanks again for your help.

Sandy
