### ISSUE TITLE
Infinite Auth Loop with the error "no matching state found in storage" - oidc-client.js

### ISSUE THREAD

**Issue by PaulMcCaffery** [DuendeSoftware/Support#671]
**Which version of Duende IdentityServer are you using?**
Version 4

**Which version of .NET are you using?**
.NET core 3.1
With ASP.NET and Angular 10 / OIDC-client.js

Hello, wonder if you can give me any advice with my problem.

A small number of users are having issues getting stuck in an infinite login failed loop.

I am trying to get further details but most report leaving the browser open and returning the next day and getting stuck in a redirect loop.

If I stop the browser loading I can see in the console the error "no matching state found in storage" in the auth callback.

I can't see to simulate the same behaviour.

Other articles appear to suggest it is an issue with cookie permissions but if they have successfully logged in before I doubt that.

I can get it to work in incognito mode for the user but (at least they say) clearing the cache doesn't resolve the issue.

Any ideas why this would happen and if there is anything I can do in development mode to try and simulate this and recreate the issue by forcing an expiry of the token.

**Comment by brockallen** [comment]
> If I stop the browser loading I can see in the console the error "no matching state found in storage" in the auth callback.

I've seen this when the starting page is served over http, but the redirect used for the client is on https. This usually happens when the user enters the starting URL and typos the http. See if this is the issue, then don't allow your app to run from http -- cause it to redirect to https then it can start the OIDC workflow.

**Comment by PaulMcCaffery** [comment]
Thanks for the quick reply. It is hosted as an Azure App Service and I use:

` app.UseHttpsRedirection();`

I will check that next time I get a user that experiences this, but trying to test this I can't replicate your suggestion as I get immediately redirected to HTTPS.

**Comment by brockallen** [comment]
Then it must be something else.

**Comment by PaulMcCaffery** [comment]
Upon further investigation the issue was actually an Azure Load Balancing / Scaling issue.

The application had been scaled out to use multiple instance of my web app which houses identity server in the same web project.

Because there were two instance and Server Affinity cookie was shorter than the auth token when the user was directed to a different server, the auth code in session state didn't match what the client had stored in session storage in the browser.

I need to make session state less server sticky and this should not happen by using SQL Server Session store I suspect.

Scaling down to one instance and increasing my pricing tier solves the problem temporarily until I can implement session state differently.

Hope this helps anyone who experiences the same issue.
