### ISSUE TITLE
BFF Server Side Session (Blazor wasm hosted)

### ISSUE THREAD

**Issue by georgait** [DuendeSoftware/Support#672]
i am trying to understand what is the intended behavior of server side sessions when are enabled both into identity server and bff.
Here is ids DI configuration:
```
builder.Services.AddIdentityServer(options =>
{
        options.ServerSideSessions.UserDisplayNameClaimType = "name";            
        options.Events.RaiseErrorEvents = true;
        options.Events.RaiseInformationEvents = true;
        options.Events.RaiseFailureEvents = true;
        options.Events.RaiseSuccessEvents = true;
        options.EmitStaticAudienceClaim = true;
        options.ServerSideSessions.UserDisplayNameClaimType = "name";
        options.ServerSideSessions.RemoveExpiredSessions = true;
        options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;
})
        .AddServerSideSessions()
        .AddConfigurationStore(options =>
        {
            options.ConfigureDbContext = builder => 
                builder.UseSqlite(connectionString, dbOptions => dbOptions.MigrationsAssembly(migrationsAssembly));
        })      
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = builder => 
                builder.UseSqlite(connectionString, dbOptions => dbOptions.MigrationsAssembly(migrationsAssembly));

            options.EnableTokenCleanup = true;
            options.RemoveConsumedTokens = true;
        })
        .AddAspNetIdentity<ApplicationUser>()
```
And this is for BFF:
```
builder.Services.AddBff(options =>
{
    options.BackchannelLogoutAllUserSessions = true;
    options.EnableSessionCleanup = true;    
})
.AddEntityFrameworkServerSideSessions(options =>
{
    options.UseSqlite("Data Source=myDb.db");
});
```
Using that and having two browsers opened with same user if i logout from the first one then the second one seems to be logged out as well (after refreshing the homepage) but when i try to navigate to a protected page then re-logs in automatically. Is this intentional or am i missing something in overall configuration, because i thought that setting ` options.BackchannelLogoutAllUserSessions` to true would remove both ServerSideSessions and UserSessions?

**Comment by josephdecock** [comment]
Here's what is happening:

You have two separate browsers, with separate sessions at the bff and IdentityServer

When you logout in browser 1, the bff redirects you to identity server's end session endpoint. That endpoint destroys IdentityServer's cookie in browser 1, and sends a backchannel notification to the bff. The bff sees this and sees that you have the BackchannelLogoutAllUserSessions  flag on, so it destroys the bff server side session used in both browsers.

Now in browser 2, you are no longer authenticated at the bff. However, you still have an IdentityServer session. So the next time the application in browser 2 issues a challenge, you get logged back in.

To get the behavior that you're asking for, you'd need to delete the browser 2 identityserver session on logout from session 1, which you could do with the `ISessionManagementService.RemoveSessionsAsync` method.

**Comment by georgait** [comment]
Thanks a lot
