### ISSUE TITLE
IdentityServer4 redirection failed for .NET Core2.1

### ISSUE THREAD

**Issue by anoosha503** [DuendeSoftware/Support#673]
**Which version of Duende IdentityServer are you using?** 
IdentityServer4 v2.5.4
**Which version of .NET are you using?**
.NET Core 2.1
**Describe the bug**
1. I created the IdentityServer project, it runs successfully, and I got the /.well-known/openid-configuration data also.
2. And Then I create a client project, In this project when I hit the [Authorize] controller [e.g "https://localhost:6001/weatherforecast"], it will redirect to the IdentityServer for login.
3. After logging in successfully, it will redirect to the client page.
The above three steps are the actual process.
But now the above two steps are working successfully, and after logging in, it will not redirect to the client page it will be on the identity server page only and I am not getting token also.

When I enter my login credentials, on clicking the Log In button, it will redirect to the client page.

<img width="952" alt="image" src="https://github.com/DuendeSoftware/Support/assets/120091131/78b66a0f-bad7-4fd3-8c56-89625c145859">

But it will be on the identity server page only and I am not getting Jwt token 

<img width="926" alt="image" src="https://github.com/DuendeSoftware/Support/assets/120091131/ab1e253a-b5ce-41ed-b0e6-591c870352e6">

**To Reproduce**
Server Side Configuration.

```c#
public class Config
    {
        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource
                {
                    Name = "IS4API",
                    DisplayName = "My API",
                    Scopes = new List<Scope> { new Scope("fullaccess") },
                    UserClaims = { "role" }
                }

            };
        }

        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
            };

        }
        public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "zorro",
                    ClientName = "IdentityServerWebApi",
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    RedirectUris ={"https://localhost:6001/signin-oidc" }, // Add the allowed redirect URIs here
                    PostLogoutRedirectUris ={ "https://localhost:6001/signout-callback-oidc" },
                    AllowedScopes = { IdentityServerConstants.StandardScopes.OpenId,
                                      IdentityServerConstants.StandardScopes.Profile,
                                      "fullaccess" },
                    AllowOfflineAccess = true
                }
            };
        }
        public static IEnumerable<TestUser> GetUsers()
        {
            return new List<TestUser>
            {
                new TestUser
                {
                    SubjectId = "1",
                    Username = "alice",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim("name", "Alice"),
                        new Claim("website", "https://alice.com")
                    }
                },
                new TestUser
                {
                    SubjectId = "2",
                    Username = "bob",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim("name", "Bob"),
                        new Claim("website", "https://bob.com")
                    }
                }
            };
        }
    }
 ```
In Startup.ts file
```c#
public void ConfigureServices(IServiceCollection services)
        {
            var mongoDbSettings = Configuration.GetSection(nameof(MongoDbConfig)).Get<MongoDbConfig>();
            services.AddIdentity<ApplicationUser, ApplicationRole>()
            .AddMongoDbStores<ApplicationUser, ApplicationRole, Guid>
            (
             mongoDbSettings.ConnectionString, mongoDbSettings.Name
            );

            var identityServerSettings = Configuration.GetSection(nameof(IdentityServerSettings)).Get<IdentityServerSettings>();
       
            services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseErrorEvents = true;
                
            })
                .AddAspNetIdentity<ApplicationUser>()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddDeveloperSigningCredential().AddTestUsers(Config.GetUsers().ToList());
            services.AddMvcCore().AddAuthorization();
            services.AddMvc()
           .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        } 
```
And Client Side configuration is

```c#
public void ConfigureServices(IServiceCollection services)
        {
            var bytes = new byte[32];
            using (var rng = RandomNumberGenerator.Create())
            {
                rng.GetBytes(bytes);
            }

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme);
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("Cookies")

            .AddJwtBearer(options =>
            {
                options.Authority = "https://localhost:5001";
                options.Audience = "IS4API";
            })
            .AddOpenIdConnect("oidc", options =>
             {
                 options.SignInScheme = "Cookies";
                 options.Authority = "https://localhost:5001";
                 options.RequireHttpsMetadata = false;
                 options.ClientId = "zorro";
                 options.ClientSecret = "secret";
                 options.ResponseType = "code id_token";
                 options.SaveTokens = true;
                 options.Scope.Add("fullaccess");
                 options.Scope.Add("offline_access");
                 options.ClaimActions.MapJsonKey("website", "website");
                 
             });
            services.AddMvcCore().AddAuthorization();
        }
```

1.IdentityServer project which runs from 5001 port.
2.Client project the Web API and runs from 6001 port.

**Expected behavior**

After logging in successfully, it will redirect to the client page and it will give access token.

**Log output/exception with stacktrace**

**Additional context**

None

**Comment by josephdecock** [comment]
Also, you're free to try IdentityServer for your own education and in your dev and test environments without a license. Take a look at our [quickstart tutorials](https://docs.duendesoftware.com/identityserver/v6/quickstarts/) to get started.

**Comment by anoosha503** [comment]
IdentityServer4 can't be used in Asp.Net Core 2.1? If it can't, then what should be used instead of IdentityServer4 using.net Core v2.1?

**Comment by brockallen** [comment]
> Asp.Net Core 2.1

That version of ASP.NET Core is no longer supported by Microsoft. It's advisable to upgrade to a supported version.

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by anoosha503** [comment]
> 

Our project is developed in.NET Core 2.1, and we can't upgrade to the.NET LTS version.

The question is: can we use Identity Server 4 to authenticate and authorize.NET Core 2.1 applications (apps, web APIs)?

**Comment by josephdecock** [comment]
That might still work, but we don't provide support for IdentityServer4 anymore.  For the past couple of years, new development in IdentityServer has transitioned to Duende, and as of November 2022, we no longer provide support for IdentityServer4.

As we announced on the IdentityServer4 docs:

> As of Oct, 1st 2020, we started a new [company](https://duendesoftware.com/). All new development will happen in our new [organization](https://github.com/duendesoftware). The new Duende IdentityServer is free for dev/testing/personal projects and companies or individuals with less than 1M USD gross annual revenue - for all others we have various commercial licenses that also include support and updates. [Contact](https://duendesoftware.com/contact) us for more information.
> 
> IdentityServer4 will be maintained with security updates until November 2022.

**Comment by anoosha503** [comment]
okay,Thank you @josephdecock
