### ISSUE TITLE
How to pass redirect url from BFF to identityserver

### ISSUE THREAD

**Issue by GIBZ-GIPE** [DuendeSoftware/Support#674]
**Which version of Duende BFF are you using?**
`Duende.BFF 2.0.0`

**Which version of .NET are you using?**
`net7.0`

**Describe the bug**
For my SPA I'm currently developing a solution for auth. The process works like this, *if the user's not already authenticated*:

1. The login endpoint of BFF is called with return url: `https://mydomain/bff/login?redirectUrl=xyz`
2. The BFF triggers the oidc challenge which is configured to be my instance of identityserver (idsrv). The idsrv runs on a subdomain: `https://auth.mydomain`.
3. The idsrv displays a custom login page, developed as SPA in Vue.js at `https://auth.mydomain/login?RedirectUrl=https://auth.mydomain/connect/authorize/callback...`
4. The user clicks on a custom `Signin with M365` button which leads to the execution of the `LoginWithMicrosoft` action in my custom `AccountController`. This method expects the returnUrl to be parsed `[FromQuery]`. Upon verification, the returlUrl in the methods parameter matches the query string parameter `RedirectUrl` from my login page (see step 3).
5. Inside my `LoginWithMicrosoft` method, I prepare an instance of `AuthenticationProperties` where the `RedirectUri` points to another custom method to process microsofts auth result. The `returnUrl` parameters value for the `returnUrl` `Item` of the `AuthenticationProperties` instance seems not to work. If I hardcode a value like `https://example.com`, the redirect after the whole auth process works. The `redirectUrl` value of the initial request towards the BFF (see step 1) is ignored although.

Interestingly, if the user is already authenticated, a request to `https://mydomain/bff/login?redirectUrl=xyz` ends in a successful redirect to tha `/xyz` endpoint. My problem only exists uppon the first authentication covering the whole process with idsrv and external id provider.

**To Reproduce**

Setup BFF and add an instance of identityserver as the BFFs way for authentication (`builder.Services.AddAuthentication(/* ... */).AddOpenIdConnect(/* ... */)`).

Request the `/bff/login` endpoint of your bff while providing a value for the query string parameter `returnUrl`: `https://myBff/bff/login?returnUrl=/xyz`.

**Expected behavior**

The BFF should forward the user to the identityserver, which in turn forwards the user to the external identity provider (in my case: Microsoft). After successful authentication with the external id provider, the user should ultimately be redirected to the `/xyz` endpoint specified in the originating request towards the BFFs login endpoint.

**Code snippets**

**From `AccountController` in identityserver instance**
```c#
    [HttpGet("login/microsoft")]
    public async Task<ChallengeResult> LoginWithMicrosoft([FromQuery] string returnUrl)
    {
        var callbackUrl = Url.Action(nameof(HandleMicrosoftCallback));

        var props = new AuthenticationProperties
        {
            RedirectUri = callbackUrl,
            Items =
            {
                { "LoginProvider", Microsoft.AspNetCore.Authentication.MicrosoftAccount.MicrosoftAccountDefaults.AuthenticationScheme},
                { "returnUrl", returnUrl }, // When replaced with hardcoded value: the user will be redirected there
            }
        };

        return Challenge(props, Microsoft.AspNetCore.Authentication.MicrosoftAccount.MicrosoftAccountDefaults.AuthenticationScheme);
    }

    [HttpGet("microsoft/handleCallback")]
    public async Task<IActionResult> HandleMicrosoftCallback()
    {
        var externalLoginInfo = await _signInManager.GetExternalLoginInfoAsync();

        if (externalLoginInfo is null)
        {
            return BadRequest();
        }

        var signInResult = await _signInManager.ExternalLoginSignInAsync(externalLoginInfo.LoginProvider, externalLoginInfo.ProviderKey, isPersistent: false, bypassTwoFactor: true);

        if (signInResult.Succeeded)
        {
            // Local authentication for externally authenticated user was successful.
            return GetRedirect(externalLoginInfo);
        }

        var user = await _accountService.GetUserForExternalLoginAsync(externalLoginInfo);
        if (user is null)
        {
            // There's no local account for externally authenticated user yet -> let's create one.
            user = await _accountService.CreateAccountForExternalAuthenticatedUserAsync(externalLoginInfo);
            return GetRedirect(externalLoginInfo);
        }

        return BadRequest();
    }

    private IActionResult GetRedirect(ExternalLoginInfo externalLoginInfo)
    {
        string? returnUrl = "";
        externalLoginInfo.AuthenticationProperties?.Items.TryGetValue("returnUrl", out returnUrl);
        return !string.IsNullOrEmpty(returnUrl) ? Redirect(returnUrl) : BadRequest();
    }
```

**Comment by GIBZ-GIPE** [comment]
Thank you for the hint regarding the vulnerability 🙏

In the `HandleMicrosoftCallback` method I get `https://auth.mydomain/connect/authorize/callback?client_id=backendForFrontend` as value for the `returnUrl` (retrieved as mentioned in your answer and as shown in the `GetRedirect` method in my code snipped above).

I suppose, this url is retrieved from the `externalLoginInfo` because this actually ist the value which gets written to the query string parameter in my login page: `https://auth.mydomain/login?ReturnUrl=https%3A%2F%2Fauth.gibz-app.local%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DbackendForFrontend%26redirect_uri%3Dhttps%253A%252F%252Fmydomain%252Fsignin-oidc%26response_type%3Dcode%26scope%3Doffline_access%2520openid%2520profile%2520b.1%26code_challenge%3DoQhBI2lPoefFKOcSqzYJF1Ut_fk9uT1PC1Aulw53aqI%26code_challenge_method%3DS256%26nonce%3D638200324202261212.ZjllZTM3ODgtNzRjNi00YTc4LTkyNzctZTc5ZjgxYTEyOTIxMTFjMmVhY2EtZjI5Ni00MWQzLWJmOWMtOTM0OTQxNDMxMjJi%26state%3DCfDJ8IeKrWBodWlIjxyNnRpCrXh8ggjY332EDD44_YATS1HdV_TpQEQmm7WjaYDr2UQ2Q87tqOmce9DK7aDj5x2LV0K2vY5MgfSTlT65p6HTat13YgM3JUbwW1B_JjtvrObxJHhyedEXw9j3ZExfM2DZBQMwNVVZ-B2hycoO05-8f0N5UulWN79BPTwXoQnpspxpxdtJnwpPaUx8YY-UybVNXhtdSsdLz3OYpY5i9cQAqDSJw3xJ84BWwl6AcuSj-WD2E9H0Vcbb5WygRbl9aYCepDLp1r4D_gWDxrxPWXXsYyiVgYOzCn2rBqJnS3NK8v9AKkCtbeV_E9jT-Q6pPhybZ4eR1_sOZsRs4YiD0kyMzRLy8F_7vEVal_WU_qs6_Kz42A%26x-client-SKU%3DID_NETSTANDARD2_0%26x-client-ver%3D6.15.1.0`.

This return url presumably is defined by my instance of idsrv. The question therefore is: **How do I pass the (TODO: validated) returnUrl from the BFF to the idsrv.** And what measures need to be taken for that returnUrl to survive the redirections to Microsoft, back to idsrv and the bff?

**Comment by GIBZ-GIPE** [comment]
Sorry, I did **not** intend to close this issue since it's not resolved yet (for me) 😞

**Comment by josephdecock** [comment]
The returnUrl that you pass to the bff's login endpoint gets persisted within the authentication properties during the handshake. Those properties are serialized and dataprotected and sent through the protocol as the state parameter. 

When the authorize endpoint implemented in the IdentityServer middleware redirects the user to the login page, it passes a different returnUrl parameter to the UI, which is a url that takes you back to a callback that the middleware will process, and all the original parameters to the authorize call are included in that callback. So, the _bff_ returnUrl is persisted first in the state param, and then within the IdentityServer returnUrl.

Our [samples](https://docs.duendesoftware.com/identityserver/v6/samples/bff/) using the bff are able to login with an external idp and properly persist the returnUrl. Your login code looks very similar to those samples, but I imagine if you debug through the process, with the understanding of the various return urls I'm outlining, you might find something more.

The other thing that might be happening is that when you federate with an external identity provider, you can get problems because each hop in the federation adds more and more state, which is tracked in the url parameters. Some systems impose limits on the size of url parameters and you can get weird behavior when those limits are exceeded. We've built a [caching mechanism that stores the state server side](https://docs.duendesoftware.com/identityserver/v6/ui/login/external/#state-url-length-and-isecuredataformat) instead of in the url parameters that you could try enabling and see if that solves this.

**Comment by josephdecock** [comment]
Any update on this issue?
