### ISSUE TITLE
Duende IdentityServer v6.2 to v6.3

### ISSUE THREAD

**Issue by LouisYNot** [DuendeSoftware/Support#677]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by brockallen** [comment]
Perhaps you were looking for this: https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.2_to_v6.3/
