### ISSUE TITLE
Duende IdentityServer v6.2 to v6.3

### ISSUE THREAD

**Issue by LouisYNot** [DuendeSoftware/Support#678]
Hello,

I just try to update 6.2 -> 6.3 and I have this error

```
PM> Add-Migration Update_DuendeIdentityServer_v6_3 -c ConfigurationDbContext
Multiple startup projects set.
Using project 'En.IDP' as the startup project.
Build started...
Build succeeded.
[22:15:49 INF] Starting up
[22:15:49 Fatal] 
Unhandled exception
Microsoft.Extensions.Hosting.HostAbortedException: The host was aborted.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.ThrowHostAborted()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at En.IDP.HostingExtensions.ConfigureServices(WebApplicationBuilder builder) in C:\Users\Utilisateur\source\repos\SaltedRepo\En.IDP\HostingExtensions.cs:line 128
   at Program.<Main>$(String[] args) in C:\Users\Utilisateur\source\repos\SaltedRepo\En.IDP\Program.cs:line 19

[22:15:49 Information] 
Shut down complete
```

And this in HostingExtensions.cs

```csharp
builder.Services.AddIdentityServer(options =>
{
    options.Events.RaiseErrorEvents = true;
    options.Events.RaiseInformationEvents = true;
    options.Events.RaiseFailureEvents = true;
    options.Events.RaiseSuccessEvents = true;

    // see https://docs.duendesoftware.com/identityserver/v5/fundamentals/resources/
    //options.EmitStaticAudienceClaim = true;
})

    .AddAspNetIdentity<ApplicationUser>()
    // Demande l'installation de Duende.IdentityServer.EntityFramework
    .AddConfigurationStore(options =>
    {
        options.ConfigureDbContext = b => b.UseSqlServer(builder.Configuration.GetConnectionString("UserDbContextConnection"), sql => sql.MigrationsAssembly(migrationsAssembly));
    })
    .AddOperationalStore(options =>
    {
        options.ConfigureDbContext = b => b.UseSqlServer(builder.Configuration.GetConnectionString("UserDbContextConnection"), sql => sql.MigrationsAssembly(migrationsAssembly));
        // this enables automatic token cleanup. this is optional.
        options.EnableTokenCleanup = true;
        options.TokenCleanupInterval = 3600; // interval in seconds (default is 3600)
    });

return builder.Build();
```

Any clue will be very apreciate.

**Comment by josephdecock** [comment]
The EF migrations tool actually starts up your code so that it can interact with the dbcontext, and then when it's done with its work, it throws an exception to shut down the host. So, this exception is actually expected - you can catch that exception and suppress it safely. Depending on the version of .NET that you are using, the best way to catch this exception will vary, as the exception type that is thrown by EF was made into a public type in .NET 7. Here's some sample code that will work in .NET 6 or 7:

```cs
try
{
    // Create and run the application here
    // bunch of config omitted, eventually you call...
    app.Run();
}
catch (Exception ex) when (
    // https://github.com/dotnet/runtime/issues/60600
    ex.GetType().Name is not "StopTheHostException"
    // HostAbortedException was added in .NET 7, but since we target .NET 6 we
    // need to do it this way until we target .NET 8
    && ex.GetType().Name is not "HostAbortedException")
{
    Log.Fatal(ex, "Unhandled exception");
}
finally
{
    Log.Information("Shut down complete");
    Log.CloseAndFlush();
}
```

**Comment by LouisYNot** [comment]
> The EF migrations tool actually starts up your code so that it can interact with the dbcontext, and then when it's done with its work, it throws an exception to shut down the host. So, this exception is actually expected - you can catch that exception and suppress it safely. Depending on the version of .NET that you are using, the best way to catch this exception will vary, as the exception type that is thrown by EF was made into a public type in .NET 7. Here's some sample code that will work in .NET 6 or 7:
> 
> ```cs
> try
> {
>     // Create and run the application here
>     // bunch of config omitted, eventually you call...
>     app.Run();
> }
> catch (Exception ex) when (
>     // https://github.com/dotnet/runtime/issues/60600
>     ex.GetType().Name is not "StopTheHostException"
>     // HostAbortedException was added in .NET 7, but since we target .NET 6 we
>     // need to do it this way until we target .NET 8
>     && ex.GetType().Name is not "HostAbortedException")
> {
>     Log.Fatal(ex, "Unhandled exception");
> }
> finally
> {
>     Log.Information("Shut down complete");
>     Log.CloseAndFlush();
> }
> ```

Excellent!! Thanks a lot for your precious help Joseph.
