### ISSUE TITLE
.net 6.0 AddSigninCredentialFromConfig

### ISSUE THREAD

**Issue by greengumby** [DuendeSoftware/Support#68]
**Which version of Duende IdentityServer are you using?**

6.1

**Which version of .NET are you using?**

6.0

**Describe the bug**

With the change to remove startup.cs how do I setup the SigninCredentials as it requires an Ilogger.

` .AddSigninCredentialFromConfig(builder.Configuration.GetSection("IdentityServer:SigninKeyCredentials"), builder.Logging???)`

 Thankyou in advance

**Comment by brockallen** [comment]
AddSigninCredentialFromConfig is not an API we provide. But in any event, it'd just be a matter of accessing the services during startup, building it, and getting a logger I'd imagine. This is a general ASP.NET Core question, so perhaps that's covered in their docs somewhere?
