### ISSUE TITLE
Provide override for session coordination during access token validation

### ISSUE THREAD

**Issue by dgioulakis** [DuendeSoftware/Support#680]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
6

Previously, we used Microsoft's JwtBearer auth middleware for authenticating access tokens for endpoints hosted within our Duende-based identity solution. I've migrated away from this to our own authentication handler - very similar to Duende's `LocalApiAuthenticationHandler`.

Unfortunately, we've noticed that this breaks our ability to have a "GetSessionTimeRemaining" endpoint (it currently slides the session during request authentication / token validation). It would be nice if the `TokenValidator.ValidateAccessToken()` could provide a parameter to prevent session coordination for this use case.

**Current**:
```csharp
ValidateAccessTokenAsync(string token, string expectedScope = null)
```

**Conceptual:**
```csharp
// coordinateSession defaults to true to preserve current functionality
ValidateAccessTokenAsync(string token, string expectedScope = null, bool coordinateSession = true) {
...
  if (sid != null && coordinateSession)
}
```

On a somewhat related note concerning extensibility ... it feels like the default `TokenValidator` does not provide great customization other than to completely override entire methods - for which implementors might be worried they write insecurely. For instance, it would be nice if we could easily customize the `TokenValidationParameters` in the private `ValidateJwtAsync()`. These validation parameters are created without a factory method available to override.

For both these items described here, it's apparent we might need to write our own TokenValidator, but I believe with a little refactoring, Duende can provide more extensibility points and implementors need not to worry about overriding entire functional blocks

**Comment by dgioulakis** [comment]
We're going to re-think our "GetSessionTimeRemaining" ... most likely make it an anonymous endpoint and pass the jwt or session identifier instead of the authorization header. I don't think changing the Duende interface is a great design idea for this use case.

**Comment by josephdecock** [comment]
Sorry for the delay in responding here. Did you end up finding a good way to solve your problem, or are there hooks you'd find convenient if we added them?

**Comment by dgioulakis** [comment]
No worries. I think most users might not find this to be a much desired feature. For local api authentication of custom endpoints that are hosted within a Duende app, you probably do want your session to slide (if coordination is enabled). I think it's just this unique case in which you want to be able to know how much time is remaining without mutating/sliding it.

For now, we are trialing just leaving this endpoint as anonymous and passing the JWT as part of the request body and manually validating it instead of going through auth middleware + Duende's TokenValidator.

Feel free to close this issue.
