### ISSUE TITLE
Problems with approval of Apple app when using IdentityServer

### ISSUE THREAD

**Issue by john-spain** [DuendeSoftware/Support#685]
Apple keep rejecting our app as the login does not take place in the app. We have tried to argument why we use this approach but it seem they dont even read the information we provide, they check the video of the app and then reject it. Have anyone had the same experience? Any ideas how to get Apple to accept a login that take place outside the app?

**Comment by StuFrankish** [comment]
Apple are famously a pain in the rear when it comes to app reviews - especially when it comes to things like authentication and taking payments for purchases and subscriptions.
Your best bet is to use the in-app browser tab with something like [AppAuth-iOS](https://github.com/openid/AppAuth-iOS).

**Comment by john-spain** [comment]
We are adding Apple authentication, seem like the best way to solve this. Hope to submit the app next week.

**Comment by josephdecock** [comment]
Sounds good - I'll go ahead and close the issue, but feel free to reopen if you need more help.
