### ISSUE TITLE
What to put for the scheme in AuthenticationHttpContextExtensions.AuthenticateAsync()

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#686]
**Which version of Duende IdentityServer are you using?**
IdentityServer 4.

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

In this Duende [example](https://docs.duendesoftware.com/identityserver/v6/ui/login/external) they use:

```
    services.AddAuthentication()
    .AddOpenIdConnect("AAD", "Employee Login", options =>
    {
        options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
        // other options omitted
    });
```

and authenticate using:
`var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);`

However, according to [msdn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationoptions.defaultauthenticatescheme?view=aspnetcore-7.0#microsoft-aspnetcore-authentication-authenticationoptions-defaultauthenticatescheme), `AuthenticationOptions.DefaultAuthenticateScheme` (set in `services.AddAuthentication()`) is:

> used as the default scheme by AuthenticateAsync(HttpContext, String).

If that's the case, why doesn't the example above set the `DefaultAuthenticateScheme` in `services.AddAuthentication()`?
Does `options.SignInScheme` also set `AuthenticationOptions.DefaultAuthenticateScheme` behind the scenes?

**Comment by josephdecock** [comment]
The OIDC handler doesn't have its own mechanism for managing your session within the application. Instead, after the OIDC handshake is complete, the identity produced from that handshake is passed to a cookie authentication scheme. The flow is

1) OIDC Handshake produces an identity -> 2) Identity is captured in an application cookie -> 3) user navigates around the application, authenticating with that cookie.

We have an initial login flow that uses OIDC (and therefore redirects to the identity provider), but after that, we want the user to stay at the application and have a session there, hence the cookie.

The `SignInScheme` of the OIDC handler says which authentication scheme to use in step 2 to start the session.

Behind the scenes, IdentityServer registers a couple of cookie handlers. There is `IdentityServerConstants.DefaultCookieAuthenticationScheme`, which is the main cookie used to establish your session at IdentityServer. IdentityServer sets this cookie scheme as the default authentication scheme. If a user has this cookie, then they'll get single sign on between applications. There is also the `IdentityServerConstants.ExternalCookieAuthenticationScheme` (which you've found in this sample). This is the scheme that is used immediately after the user signs in with an external provider. The example that you're linking from shows how we recommend using that as a temporary credential to handle external logins.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
