### ISSUE TITLE
Consider filtering protocol claims out from client claims

### ISSUE THREAD

**Issue by ahaeber** [DuendeSoftware/Support#689]
**Which version of Duende IdentityServer are you using?**
6.3.0

**Which version of .NET are you using?**
.net 6.0

**Describe the bug**

We have found that we can simply add client claims for protocol claims, like scope, it will be included in the access token for the client. This works different than for users, and a question is whether this is intentional or not?

See https://github.com/DuendeSoftware/IdentityServer/blob/4817335dc544bac32318a25a0434c97b264f3b80/src/IdentityServer/Services/Default/DefaultClaimsService.cs#L198
```csharp
            // filter so we don't ask for claim types that we will eventually filter out
            additionalClaimTypes = FilterRequestedClaimTypes(additionalClaimTypes).ToList();

            var context = new ProfileDataRequestContext(
                subject,
                request.Client,
                IdentityServerConstants.ProfileDataCallers.ClaimsProviderAccessToken,
                additionalClaimTypes.Distinct())
            {
                RequestedResources = resourceResult,
                ValidatedRequest = request
            };

            await Profile.GetProfileDataAsync(context);

            var claims = FilterProtocolClaims(context.IssuedClaims);
```

This makes it easy to let clients override protocol claims that it should not be allowed to. The client prefix claim setting can obviously be used to mitigate issues here, however that requires APIs to check for claims with (client access) and without (users) the prefix which is a bit troubling.

Our implementation of `ICustomTokenRequestValidator` creates some claims that APIs expect for both clients (in client credential flow) and users (e.g., authentication code flow). Currently, for clients, it can only add these to `ClientClaims` and those will get the prefix when `Duende.IdentityServer.Services.DefaultClaimsService.GetAccessTokenClaimsAsync` creates the access token. It would be nice to be able to add client claims that should not be prefixed, thus treated the same as protocol claims. Then we could likely keep the client claims prefix always set to something and it would not be possible to let clients create protocol claims that way.

**To Reproduce**

1. Create a client with client claims prefix set to null/empty string.
2. Add client claims like `("scope", "whatever")`
3. Get access token for the client
4. The access token includes two scope claims.

**Expected behavior**

Two options, which are not mutually exclusive:
A. The custom scope claim should be filtered out.
B. It is possible to create extra claims for clients that will not be prefixed. Then the client claim "scope" will be prefixed like `"client_scope": "whatever"`.

** Extra **
Finally, it would be good to add the claims "entitlements", "groups" and "roles" to the claim types filters. They come from the IETF SCIM WG and were recently registered by IANA: https://www.rfc-editor.org/rfc/rfc9068.html#section-7.2 and https://www.iana.org/assignments/jwt/jwt.xhtml#claims

**Comment by josephdecock** [comment]
> This works different than for users, and a question is whether this is intentional or not?

Yes, this is intentional. We think of IdentityServer as a framework first, so we want to allow people to build and customize, but we also want to have a few guardrails in place that guide people in the right direction. Over time, we've found that we needed different abstractions for user claims (the profile service, which offers the ability to run arbitrary code) and client claims (the `ClientClaims` collection, which does not), and the right balance of customization vs guard rails for those two different abstractions ended up a little different.

> This makes it easy to let clients override protocol claims that it should not be allowed to.

I'm not sure if I'm following you. It sounds like you're saying that the client can make requests that override protocol claims? That doesn't make sense to me, because the `ClientClaims` are entirely controlled by IdentityServer's configuration. Or is the concern that it is possible to configure clients in ways that don't work well for you? It actually is a legitimate use case to say "client foo always gets scope bar, even if they don't ask for it", and you can express that with the `ClientClaims` and `ClientClaimsPrefix` as they currently exist. 

> Finally, it would be good to add the claims "entitlements", "groups" and "roles" to the claim types filters.

We don't filter these claims out because if you're building a identity provider that wants to emit tokens that follow the semantics of RFC9068, you're going to need those claims.

**Comment by ahaeber** [comment]
> > This works different than for users, and a question is whether this is intentional or not?
> 
> Yes, this is intentional. We think of IdentityServer as a framework first, so we want to allow people to build and customize, but we also want to have a few guardrails in place that guide people in the right direction. Over time, we've found that we needed different abstractions for user claims (the profile service, which offers the ability to run arbitrary code) and client claims (the `ClientClaims` collection, which does not), and the right balance of customization vs guard rails for those two different abstractions ended up a little different.

We do appreciate this design of Identity Server :+1: 

> > This makes it easy to let clients override protocol claims that it should not be allowed to.
> 
> I'm not sure if I'm following you. It sounds like you're saying that the client can make requests that override protocol claims? That doesn't make sense to me, because the `ClientClaims` are entirely controlled by IdentityServer's configuration. Or is the concern that it is possible to configure clients in ways that don't work well for you? It actually is a legitimate use case to say "client foo always gets scope bar, even if they don't ask for it", and you can express that with the `ClientClaims` and `ClientClaimsPrefix` as they currently exist.
> 

Right, that also makes sense for such scenarios and I probably think too much at the way we need Identity Server to work. I understand now that for client claims it is up to us to control which claims can be configured for clients.

> > Finally, it would be good to add the claims "entitlements", "groups" and "roles" to the claim types filters.
> 
> We don't filter these claims out because if you're building an identity provider that wants to emit tokens that follow the semantics of RFC9068, you're going to need those claims.

You are right, sorry for my confusion with this.
