### ISSUE TITLE
Automatic activation email on user creation

### ISSUE THREAD

**Issue by mrThirsty** [DuendeSoftware/Support#690]
IdentityServer version: 6.2.3
.Net version: 7

I have 3 separate apps (identity server, Application API, Application SPA) setup that I am using to learn IdentityServer.

In the flow I am trying to create, users don't register but rather admins would create the user in IdentityServer and the user would get an email with an activation link that takes them to a page to confirm their email and set a password. Then can then login as normal to the apps.

I know I can use something like AdminUI to manage the users etc in IdentityServer but what I seem to be missing is the activation email being sent out to the users and the confirmation and password page.

I assume I would do the page as a custom page on my IdentityServer but how do I handle the automatic email of a link? Is that something IdentityServer can do?

**Comment by josephdecock** [comment]
IdentityServer doesn't perform any user management directly. The idea is that you can use IdentityServer with any user store and customize the user experience. Our QuickStart ui and tutorials use an in memory collection of users, with the intent that you would replace that with your real user store.

**Comment by mrThirsty** [comment]
@josephdecock So then I should rather be looking at the AdminUI tool for the activation email, if I am following you.

I have already configured IdentityServer to use SqlServer as the store along with AspNetIdentity for users. 

It just feels like I am missing something to do what I feel should be a relatively simple task.

**Comment by josephdecock** [comment]
I'm not sure which Admin UI you're referring to - there's various open source admin UI's as well as a paid product from Rock Solid Knowledge (see also [our blog on Admin UIs](https://blog.duendesoftware.com/posts/20220204_admin_ui/)). None of those are Duende products that we directly support.

If you're using AspNetIdentity for user management, then you probably can use it to generate the emails that you want. Microsoft has some documentation [here](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-7.0&tabs=visual-studio) on similar workflows that you could probably adapt. For more help using AspNetIdentity, please post questions in their support forum - https://github.com/dotnet/aspnetcore.

**Comment by mrThirsty** [comment]
This can be closed, I managed to get what I needed.
