### ISSUE TITLE
Change logging provider

### ISSUE THREAD

**Issue by nhumby** [DuendeSoftware/Support#692]
**Which version of Duende IdentityServer are you using?**
6.3

**Which version of .NET are you using?**
7.0

**Describe the bug**
Serilog is used to capture logs from the Duende IdentityServer assemblies in use. We have used log4net to capture logging from our own implementation of the Identity Server web app to be consistent with the rest of our product. We would like to harmonise the logging into one provider. We've tried switching the logging for the Duende assemblies but we are missing key log entries from e.g. AuthorizeRequestValidator.cs or AuthorizeEndpoint.cs. We've registered a new instance of the log4net logger as below:

```
        ILog _logger = LogManager.GetLogger(typeof(object));
        builder.Services.AddSingleton(_logger);
```

and added our own middleware extension:

`        app.UseLog4NetRequestLogging();`

which does the following:

```
    public static class Log4NetRequestLoggingExtensions
    {
        public static IApplicationBuilder UseLog4NetRequestLogging(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<Log4NetRequestLogging>();
        }
    }
```

Can you spot what we might have missed or advise on what the Duende assemblies require in order for the logging provider to be substituted from Serilog to something else?

**Comment by josephdecock** [comment]
I think you need to add a call to `builder.Logging.AddLog4Net();` in you startup, so that asp.net will know to use log4net. 

I'm not sure what UseLog4NetRequestLogging does, but the name suggests that it is allowing you to log the requests themselves.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by nhumby** [comment]
Hi Joe. I'm afraid it's not fully working yet. I've added 
```
    public static WebApplication ConfigureServices(this WebApplicationBuilder builder)
    {
        ConnectionStringProvider.ConnectionString = builder.Configuration.GetConnectionString("DefaultConnection");
	builder.Logging.AddLog4Net();
```

to the ConfigureServices() for the web app. In the ConfigurePipeline() there is a call to 
```
    public static WebApplication ConfigurePipeline(this WebApplication app)
    {
	app.UseLog4NetRequestLogging();
```
and the code for that class does the following:
```
        public static IApplicationBuilder UseLog4NetRequestLogging(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<Log4NetRequestLogging>();
        }
```

The code for Log4NetRequestLogging.cs is:
```
public class Log4NetRequestLogging
    {
        private readonly RequestDelegate _next;
	private readonly Microsoft.Extensions.Logging.ILogger _logger;

	public Log4NetRequestLogging(RequestDelegate next, ILoggerProvider log4NetProvider)			
        {
                _next = next;
		_logger = log4NetProvider.CreateLogger(typeof(Log4NetRequestLogging).ToString());
	}

        /// <summary>
        /// The Invoke method intercepts each request, and logs 
        /// the request and response details to the log file 
        /// using the ILogger interface.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public async Task Invoke(HttpContext context)
        {
            var stopwatch = new Stopwatch();
            stopwatch.Start();
            try
            {
                await _next(context);
                stopwatch.Stop();
                _logger.LogDebug($"HTTP {context.Request.Method} " +
                    $"{context.Request.Path} responded " +
                    $"{context.Response.StatusCode} in " +
                    $"{stopwatch.ElapsedMilliseconds} ms");
            }
            catch (Exception ex)
            {
                stopwatch.Stop();
                _logger.LogError($"HTTP {context.Request.Method} " +
                    $"{context.Request.Path} responded " +
                    $"{context.Response.StatusCode} in " +
                    $"{stopwatch.ElapsedMilliseconds} ms", ex);
                throw;
            }
        }
    }
```

However, I'm still not seeing entries I expect, eg from Duende.IdentityServer.Endpoints.AuthorizeEndpoint I should be seeing this entry when trying to authenticate:
   `Logger.LogDebug("Start authorize request");`

I've had a look at the Identity Server source itself and that Logger is declared on AuthorizeEndpointBase.cs as Microsoft.Extensions.Logging.ILogger. The only implementations of it seem to be mockups in the test projects. I've noticed the Log4NetRequestLogging.cs does declare its _logger as type Microsoft.Extensions.Logging.ILogger but I think I'm missing a step somewhere of telling Duende.IdentityServer.dll to use this logger as it's ILogger? The request logging happens but none of the internal Duende logs themselves seem to be showing up there.

**Comment by josephdecock** [comment]
IdentityServer does all of its logging using the ILogger abstraction that you found, which is a part of ASP.NET. You're right, we don't provide any implementations of ILogger. It is designed so that the various logging libraries are responsible for defining those implementations, which can be registered as logging providers. Then ASP.NET will log to any registered provider. Between the built in providers (e.g., the Console provider), the microsoft providers that log to azure services, and 3rd party providers like serilog and log4net, there are at least a dozen different providers in the ecosystem.  IdentityServer just works with the ILogger abstraction, and doesn't get into the details of the particular providers. My guess is that your issue is with log4net itself and that you might need to change your log4net config file, but I don't know log4net well enough to really guide you there. We can't in general support all of the 3rd party logging providers effectively here unfortunately. The log4net community seems pretty active though, so I suggest you look for resources from the log4net community. Also, Microsoft has great docs on the ILogger abstraction [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0).

**Comment by nhumby** [comment]
The config is fine but you may be correct that the issue is with log4net, I'll check that out. Thanks Joe!
