### ISSUE TITLE
Duende.AccessTokenManagement requires to use AddDistributedMemoryCache which is discouraged by MS for production environments

### ISSUE THREAD

**Issue by smkanadl** [DuendeSoftware/Support#695]
**Which version of Duende IdentityServer are you using?**
Duende.AccessTokenManagement package v2.0.1

**Which version of .NET are you using?**
.NET 7

**Describe the bug**
The documentation for worker application mentions to add configure a memory cache by calling `services.AddDistributedMemoryCache();`

However, the official guideline from Microsoft says:

> The [AddDistributedMemoryCache](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.memorycacheservicecollectionextensions.adddistributedmemorycache) should only be used in development and/or testing scenarios, and is not a viable production implementation

https://learn.microsoft.com/en-us/dotnet/core/extensions/caching#distributed-caching

**Additional context**

Is there a way to use the 'standard' memory cache? What is your view on Microsofts advice?

**Comment by josephdecock** [comment]
AccessTokenManagement has a dependency on the IDistributedCache interface. Our sample code in the documentation uses the distributed memory cache, but real implementations will need a different implementation of that cache, in line with Microsoft's documentation.

**Comment by smkanadl** [comment]
Thank you very much for that quick response.

I am moving here from the deprecated [IdentityModel.AspNetCore](https://github.com/IdentityModel/IdentityModel.AspNetCore) project. I found the library very convenient to setup HttpClients.

But: I am working on quite simple application setups with single instances of web servers or worker processes. In this scenario I have no use for a distributed cache. And to be honest, it feels like an overkill to setup additional Redis or SQL resources for that purpose.

I had a quick look at the IdentityModel.AspNetCore and spotted usage of the `IDistributedCache` interface there too. But as I haven't set this up in my applications it looks like it was optional or had some internal fallback.

Is there any chance to bring a similar behavior to this library - to make simple use cases simple?

**Comment by josephdecock** [comment]
For simple applications, the MemoryDistributedCache probably will be fine. Duende.AccessTokenManagment caches the tokens that it obtains (and some DPoP state as well, if you're using that) in the IDistributedCache. If you use the in memory implementation, then your cache will go away whenever the process is restarted and won't be shared between multiple scaled out instances of the application. If you can accept those constraints, then the memory distributed cache is fine.

**Comment by smkanadl** [comment]
@josephdecock Thank you very much for your assessment. Maybe you can add the explanation to the wiki pages.

**Comment by OskarKlintrot** [comment]
I second adding this to the documentation, I was looking for the very same thing. I tried to figure out if we need to setup a persistent implementation of `IDistributedCache` for IdentityServer or not but couldn't find any information in the docs.
