### ISSUE TITLE
Duende.IdentityServer package are not supported in ASP.NET Web Application (.NET Framework) 4.8 

### ISSUE THREAD

**Issue by Ommkwn2001** [DuendeSoftware/Support#696]
Duende.IdentityServer version( 6.3.1,6.3.0,5.0.0,5.1.0 ) are not supported in ASP.NET Web Application (.NET Framework) 4.8

**Comment by josephdecock** [comment]
Yes, that is true. IdentityServer is essentially ASP.NET core middleware and services that are intended to be run in a standalone 3rd host to provide external authentication to your applications. Those applications then use the OAuth and OIDC specs to communicate with the IdentityServer host, and could be implemented with any tech stack. We have a sample showing how to use IdentityServer with client applications that are implemented with .NET Framework [here](https://docs.duendesoftware.com/identityserver/v6/samples/clients/#net-48-clients).
