### ISSUE TITLE
Duplicate Call for some Logins

### ISSUE THREAD

**Issue by ExplPatrick** [DuendeSoftware/Support#697]
**Which version of Duende IdentityServer are you using?**
5.2.4

**Which version of .NET are you using?**
3.1

**Describe the bug**

Some login attempts generate a duplicate call for one user. In our login method, we call a procedure that stores the session in a database. 
For some logins a second nested call for the same user occurs. Thus, the login method for a user is run twice. Mostly only fractions of a second in a row. If the procedure is then called twice at the same time, it sometimes results in an SQL error Primary Key violation: duplicate Keys.
We call our procedure after validating the user credentials. 
We have built a try/catch around the call. If the first try fails, due to a simultaneous call, it is cached and retried after a sleep(50). The second try is always successful, because it happens sporadically. 
We tried to reproduce the error by spamming the login button at logins. However, this did not result in the double pass. However, we still cannot reproduce the behavior. Only single logins are affected and not every duplicate pass results in SQL Error. 
Is our location for the procedure call incorrect? Is something like this known and has it happened before? Why does the duplicate call occur in the first place ?

**Comment by josephdecock** [comment]
This sounds like a bug in the login page of your IdentityServer implementation. IdentityServer is abstracted from the login ui - the basic contract is that the endpoints from the spec are implemented by identity server, while the user interaction is implemented by user code (that is to say, your code). Control is passed between the two using the returnUrl parameter, http redirects, and the auth cookie.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by ExplPatrick** [comment]
We can close this issue. There is a bug on the login page as suggested. I have successfully reproduced it by spamming enter or the button at login. So the form does not block on the first submit.
