### ISSUE TITLE
ServerSideSessionCleanupHost object reference error

### ISSUE THREAD

**Issue by chrisrestall** [DuendeSoftware/Support#698]
**Which version of Duende IdentityServer are you using?**
6.2.3

**Which version of .NET are you using?**
.NET 6.0

**Describe the bug**
Intermittent logging of the following error during scheduled session cleanup:
_Exception: Exception removing expired sessions: Object reference not set to an instance of an object.
SourceContext: Microsoft.Extensions.DependencyInjection.ServerSideSessionCleanupHost_

--Seems to occur sporadically.  We updated to 6.2.3 as we were experiencing a much greater volume of these errors before. There does not appear to an impact other then the exception in the logs.  The volume is much, much less on new version

**Expected behavior**

No error in the logs

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by josephdecock** [comment]
We've fixed many related [issues ](https://github.com/DuendeSoftware/IdentityServer/issues/874)in our most recent release ([6.3](url)). If you still get this error using 6.3, please let us know. A full stack trace if possible can help to track down the cause of the issue too.

**Comment by josephdecock** [comment]
Any update here? Did you try 6.3?

**Comment by chrisrestall** [comment]
We have not - reviewed the 6.3 release notes and some of the breaking changes are applicable to our setup and fall outside of LOE for our monthly patch release.  On our next IS/BFF release, we will address with an update of versions
