### ISSUE TITLE
Send User-Agent Header in JWT

### ISSUE THREAD

**Issue by HStumpf** [DuendeSoftware/Support#706]
Hi,

If an api route is called via the frontend or postman, the URL ".well-known/openid-configuration" is called within the backend API to the identity server. 
For this call we need the header "User-Agent".
How can I add a header to calls to the IdentityServer?

**startup:**
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>

**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
6.0.306

**Comment by josephdecock** [comment]
I'm sorry, I'm not really following. What's the goal here? The discovery endpoint doesn't have any dependencies on the User-Agent string by default. Are you trying to add something?

**Comment by HStumpf** [comment]
Hi,
We have introduced a rule that all accesses require a user agent header.
If a route to the backend is called in the frontend, the backend tries to establish a connection to the IdentityServer. However, this is not possible due to the rule. 
The error:

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://urlIdentityserver/.well-known/openid-configuration'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

This internal call does not send a user agent header and fails with the error message.
Here the question would be how to add a user agent header.

Regards
Horst-Dieter

**Comment by josephdecock** [comment]
The JwtBearerHandler's options includes the [Backchannel property ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions.backchannel?view=aspnetcore-7.0#microsoft-aspnetcore-authentication-jwtbearer-jwtbeareroptions-backchannel) that you can use to control the http client that it uses to make backchannel requests (including the discovery request that is failing). You need to create an http client that will set this header, and pass it to the handler using that option.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
