### ISSUE TITLE
Log valid Duende license details

### ISSUE THREAD

**Issue by doncis** [DuendeSoftware/Support#709]
**Which version of Duende IdentityServer are you using?**
6.3.2

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
Is it possible to log a valid Duende license info? Would like to see in logs such license details:
- valid from...to
- issued for (if existing)
- what is issued (if existing)

__Serilog__ is used for logging.

Currently I see only WARN if license is unavailable:
```
2023-05-31 10:37:57.561 [WRN] (1) Duende.License - You do not have a valid license key for the Duende software. This is allowed for development and testing scenarios. If you are running in production you are required to have a licensed version. Please start a conversation with us: https://duendesoftware.com/contact
```

But if license is valid this WARN disappears and no additional info is logged.

**Comment by brockallen** [comment]
We emit a debug level message with this info here: https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Licensing/LicenseValidator.cs#L88

And a more general info one here: https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Licensing/LicenseValidator.cs#L116

but if you want something more structured then we have an open issue for that: https://github.com/DuendeSoftware/IdentityServer/issues/875
