### ISSUE TITLE
Clarification for Usage of PostLogoutRedirectUris and signout-callback-oidc

### ISSUE THREAD

**Issue by tri97nguyen** [DuendeSoftware/Support#71]
**Which version of Duende IdentityServer are you using?**
IdentityServer4
**Which version of .NET are you using?**
.NET6
**Describe the question**

what is the purpose for PostLogoutRedirectUris = { "http://yourclienthost:port/signout-callback-oidc" } in Client Config please?

When I put it, IdentityServer logout page show confirmed logout message AND shows a link to redirect back to my application. 
![image](https://user-images.githubusercontent.com/34323747/170140487-f4ac853f-2ebe-415c-944f-ce5463131adc.png)

When I omit it, IdentityServer show confirmed logout message BUT NOT shows a link to redirect back to my application
![image](https://user-images.githubusercontent.com/34323747/170140590-b3504a69-9434-418e-b999-a61d1dc15834.png)

Regardless of the options, IdentityServer still logs me out. So I am confused what that config does. Please help clarify. Thank you very much!

**Comment by leastprivilege** [comment]
This support forum is for Duende IdentityServer. Please use a community forum or StackOverflow for IdentityServer4 issues. Or upgrade.
