### ISSUE TITLE
Duende Identity Server in Microservices and its licenses

### ISSUE THREAD

**Issue by sansindia85** [DuendeSoftware/Support#711]
Tech Stack :
Duende Identity Server 6
ASP.Net Core 6 and ASP.Net Core Identity

In a Kubernetes environment, we can have multiple microservices in a namespace.

Let us assume that three microservices uses Duende Library : 

Microservice1 uses Duende Library as Identity Provider 1. This identity provider users will have email address as username and password.
URL : https://identityproviderwithemail.example.com

Microservice2 uses Duende Library as Identity Provider 2. This identity provider users will have normal usernames without email address and password.
URL : https://identityproviderwithoutemail.example.com

Microservice3 uses Duende Library as Identity Server and registers above two identity providers. Depending on the username entered at this microservice, it federates to respective identity provider and provides authentication. On successful authentication, it generates token.
URL : https://login.example.com

All the above three microservices which uses Duende Library are shipped with front-end application (https://app.example.com) and shipped as one product/helm release in single namespace. The front end applications needs to authenticate before user can use it.

From production scenario perspective per customer : 
I have three microservices which use Duende Library. So, I need to use three Starter Edition License or one Starter Edition License is enough?
                                                      or
All the three microservices which uses Duende Library are shipped with front-end application are considered as one product. So, is one Starter Edition License is enough per customer?

**Comment by josephdecock** [comment]
This sounds like a pretty unusual architecture. If you really do need to redistribute 3 different authorities, then you will need the Enterprise Edition of the [Redistribution](https://duendesoftware.com/products/IdentityServerRedist) license.

Typically, I would expect all 3 of those authorities to actually be a single authority. Basically have only service 3 be an authority, and have it perform all of the authentication. Maybe service 1 and 2 can be services that service 3 relies on as a way to interact with the various user stores that you have. This design would simplify the login path and allow you to use the starter edition of the redistribution license.
