### ISSUE TITLE
Upgrade from exisitng ID4 to Duende Identity Server

### ISSUE THREAD

**Issue by gmelanta79** [DuendeSoftware/Support#712]
We have an existing ID4 implementation that connects with multiple external Azure AD's to authenticate our users. 
Currently the Callback path specified is "signin-oidc-{authenticationScheme}" and the Remote SignOut Path is "signout-oidc-{authenticationscheme}"

It looks like with Duende IdentityServer that callback path pattern has shifted and enforced to be "/federation/{authenticationScheme}/signin".

This creates an issue for us as we have multiple clients that have already been configured on their end and we would like to **NOT** have to get them to reconfigure the App Registrations on their end. 

Is there a workaround for this?

Thanks,
Gautham

**Comment by josephdecock** [comment]
The /federation prefix is only used with the dynamic providers feature. The signin-oidc-{scheme} paths will continue to work as normal for authentication schemes that you register in the traditional way as calls chained to AddAuthentication().

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
