### ISSUE TITLE
Deadlock occurs during the clean-up of tokens and sessions when the application is running on multiple instances.

### ISSUE THREAD

**Issue by anjanasagathiya** [DuendeSoftware/Support#713]
**Which version of Duende IdentityServer are you using?**
- 6.2.3

**Which version of .NET are you using?**
- .Net 7

**Describe the bug**

We have received the deadlocks while cleaning up the sessions and tokens. And it is due to the application running on multiple instances.

Here, we are using the **ServerSideSessionCleanupHost** and **TokenCleanupHost** to clean up the sessions and tokens which are the hosted service. And our application is running in Kubernetes which has multiple pods.

So while these hosted services try to remove the sessions or tokens then select and delete queries are executed in different pods in Kubernetes at the same time and due to this delete query blocks the select query and deadlock occurs.

Just to inform you that it doesn't happen every time but it creates noise in our system. We can define our custom process to delete the sessions and tokens from our end but it would be great if you will provide us a possible solution to resolve it as we are the enterprise customers of the duende identity server.

**Comment by josephdecock** [comment]
Thanks for the feedback! I'll create an issue for us to consider ways to improve this situation and prevent deadlocks.

**Comment by josephdecock** [comment]
For now, I'm going to close this issue, since in the short term I think you're implementing your own cleanup job, and we have the issue in IdentityServer to track further development on our end. Thanks again!
