### ISSUE TITLE
Implementation of Identity provider feature (OIDC & SAML providers)

### ISSUE THREAD

**Issue by Mgs25** [DuendeSoftware/Support#714]
**Which version of Duende IdentityServer are you using?**
6.3.0

**Which version of .NET are you using?**
6.0

We are upgrading from identity server 4 on which, we have implemented custom logic to manage schemes for OIDC and SAML providers, and handled authentication using Saml2p component. How do I go about implementing the new Dynamic provider feature for both SAML and OIDC.

**Comment by josephdecock** [comment]
Since you closed this, I'm not sure if you still need anything here, but you might take a look at this sample from SustainSys: https://github.com/Sustainsys/Saml2.Samples/tree/main/v2/DuendeDynamicProviders
