### ISSUE TITLE
"Remember me"  Identity server 6

### ISSUE THREAD

**Issue by dineshmanglaaris** [DuendeSoftware/Support#719]
IdentityServer 6

Net 4.0 or above

how can we achieve Remember me functionality in ids6 for pre-populate username in login window.

**Comment by dineshmanglaaris** [comment]
can you please provide the reference of   remember me button that keeps the user signed in even when they close and reopen the browser ? I saw the [UI documentation ](https://docs.duendesoftware.com/identityserver/v6/ui/). but not found it.

**Comment by josephdecock** [comment]
You can find the remember me feature in the quickstart ui [here](https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI/blob/main/Pages/Account/Login/Index.cshtml.cs#L98-L108).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
