### ISSUE TITLE
Adding Google into Identity Provider Store

### ISSUE THREAD

**Issue by MVanderkley** [DuendeSoftware/Support#72]
I have successfully followed the DynamicProviders sample to have several external providers read from the Identity Provider Store. I have also got Google Auth working as per the example as a static Identity Provider. 

I'm now looking at trying to move the Google Auth and have it configure from data stored in the Identity Provider store as well with all identity providers loaded from the database rather than statically assigned. I've added an entry into SeedData.cs to populate it as an OidcProvider, however when I run the sample and try to authenticate using Google, I get an error ( IDX20803: Unable to obtain configuration from: 'System.String'.) about being unable to obtain  configuration. I suspect that Google doesn't strictly use Oidc as it is statically loaded using a special .AddGoogle() call rather than .AddOpenIdConnect().

So, I'm just wondering what I'm missing. I've had a look at the WSFederationDynamicProviders sample and wondering if I need to go down this path and implement a Google provider based along these lines or its something else.

Any advice would be appreciated.

**Comment by brockallen** [comment]
If you set the settings like this, then it should work:

https://github.com/DuendeSoftware/IdentityServer/blob/main/hosts/main/HostingExtensions.cs#L87

**Comment by MVanderkley** [comment]
Thanks for the help. Got it working and logging in without any problems. Works like a treat. Just need to resolve an issue with the logout and I'm all set I think.

When I attempt to logout after logging in to Google via the External Identity Provider store I get the following message:

InvalidOperationException: Cannot redirect to the end session endpoint, the configuration may be missing or invalid.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.SignOutAsync(AuthenticationProperties properties)

I did have to adjust the Authorised Redirect Urls in Google API console to allow https://localhost:5001/federation/GoogleAuth/signin in order to get a successful login due to the federation path added so I'm just wondering if I need to do something similar for the signout or if this error is a missing property I'm not including when loading the provider into the store.

Using the static registration of the google provider works without issue, both logging in and logging out, its just something I'm missing with the provider loaded from the database.

Any advice?

**Comment by brockallen** [comment]
>  Just need to resolve an issue with the logout and I'm all set I think.

Keep in mind that Google doesn't support logout. That exception is when the Microsoft code fails on the absence of an OIDC end session endpoint. Your logout page needs to detect that scenario and not try to trigger SignOut for it.

**Comment by MVanderkley** [comment]
Thanks for pointing that out. All working as expected now. Thanks for the help.
