### ISSUE TITLE
How to return custom `User.Id` as subject claim instead of `AspNetUser.Id`?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#721]
**Which version of Duende IdentityServer are you using?**
Community

**Which version of .NET are you using?**
7.0.107

**Describe the bug**
Is there any natural way of using `User.Id` as `sub` claim instead of `AspNetUser.Id`?

**Comment by josephdecock** [comment]
This is really more of an ASP.NET Identity issue than IdentityServer. Changing ASP.NET identity's understanding of the user id is what you really need to do, and then IdentityServer will respect that. The way to make that change is to override the UserManager's GetUserIdAsync method. There's also a FindByIdAsync method that ASP.NET Identity uses, and I imagine you will need to change its semantics to match GetUserIdAsync.
