### ISSUE TITLE
Hide certain claims on /bff/user

### ISSUE THREAD

**Issue by daver77** [DuendeSoftware/Support#723]
Hi, I'm using Duende.BFF 2.0

When the /bff/user endpoint is called from the client it includes all my custom Claims. Some of those Claims I don't want to be visible to the client, is it possible to hide or only show certain Claims?

**Comment by josephdecock** [comment]
To customize the behavior of the user endpoint, you need to register a custom implementation of the IUserService in DI, which can be easily done by extending the default implementation. We document the process [here](https://docs.duendesoftware.com/identityserver/v6/bff/extensibility/management/user/). In our example there, we show how to add claims to the results, but you could also manipulate the collection of claims by removing claims you don't want to emit.

**Comment by daver77** [comment]
Great thanks, that worked.

**Comment by josephdecock** [comment]
Thanks for sharing that sample
