### ISSUE TITLE
Refresh claims for an already authenticated user

### ISSUE THREAD

**Issue by jasonliao-cb** [DuendeSoftware/Support#729]
**Which version of Duende IdentityServer are you using?**
6.1.7

**Which version of .NET are you using?**
6

**Describe the bug**
We store a account_id claim in the access_token claims after the user login to the system. A user can be associated with multiple companies, and sometimes he switches the account from different applications. we have some client-side js to detect if the user is login or not through the checksession endpoint. in the checksession endpoint, we can know the current account id from the HTTP context, after comparing with the activated account he switched to, we know the account was changed after the last login, so we would like to notify client applications the user has to re-authenticated silently. as the checksession endpoint would only check the idsrv.session cookie value and return "changed" or "unchanged", we tried to update the account id claim in the current user context. but we are not able to make it work and issue a new token to him.

**We want**
there should be a way to proceed with this, we have seen the issue in ids3 https://github.com/IdentityServer/IdentityServer3/issues/2783, but could not find a clean way to do it without forcing the user the sign-off and sign in again with the user credentials 

**My code**
```cs
public async Task ExecuteAsync(HttpContext context)
{
    var options = context.RequestServices.GetRequiredService<IdentityServerOptions>();
    var accountChanged = await CheckAccountChanged(context);
    var (html, csp) = GetHtmlAndCsp(options, accountChanged);
    context.Response.AddScriptCspHeaders(options.Csp, csp);
    await context.Response.WriteHtmlAsync(html);
}

private (string html, string csp) GetHtmlAndCsp(IdentityServerOptions options, bool accountChanged)
{
    if (options.Authentication.CheckSessionCookieName != LastCheckSessionCookieName || accountChanged)
    {
        lock (Lock)
        {
            if (options.Authentication.CheckSessionCookieName != LastCheckSessionCookieName || accountChanged)
            {
                var template = RemoveIndentation(HtmlTemplate);
                var cookieName = options.Authentication.CheckSessionCookieName;
                var mainScript = ResetIndentation(MainScript, indentation: 8, leadingLineBreak: true,
                    tailingLineBreak: true, lastLineIndentation: 4);

                FormattedHtml = template.Replace("{cookieName}", cookieName)
                                        .Replace("{mainScript}", mainScript)
                                        .Replace("{accountChanged}", accountChanged ? "1" : "0");

                CspHeader = $"sha256-{Base64Sha256(mainScript)}";
                LastCheckSessionCookieName = cookieName;
            }
        }
    }
    return (FormattedHtml, CspHeader);
}

private static async Task<bool> CheckAccountChanged(HttpContext context)
{
    var currentUser = context.User;
    if (currentUser.IsAuthenticated() && currentUser.IsEmployer())
    {
        var contextAccountDID = currentUser.FindFirstValue(OneIAMClaimTypes.CurrentAccountDID);
        var userDid = currentUser.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;
        var userPreferenceManager = context.RequestServices.GetRequiredService<IUserPreferenceManager>();
        var userPreference = await userPreferenceManager.FindAsync(userDid);
        if (userPreference != null && userPreference.CurrentAccount != contextAccountDID)
        {
            var signInManager = context.RequestServices.GetRequiredService<ISignInManager<ApplicationUser>>();
            var userManager = context.RequestServices.GetRequiredService<OneIAMUserManager>();
            var user = await userManager.GetUserAsync(context.User);
            await signInManager.RefreshSignInAsync(user);
            return true;
        }
    }
    return false;
}
```
please provide some solution to this.

**Comment by jasonliao-cb** [comment]
we can't ask the user to reauthenticate with user credentials that would break some of the in-progress sessions on client applications. we managed to make it work with the RefreshSignInAsync and the claims were updated also, the client application would do a silent authentication with no promotion.

**Comment by josephdecock** [comment]
Ok, well glad you managed to make it work. Can we close this issue then?

**Comment by jasonliao-cb** [comment]
@josephdecock I'm sorry to tell that we are having an issue here when we test it. to make the above code work, especially the await signInManager.RefreshSignInAsync(user); we have to make the below change first:
<img width="1394" alt="image" src="https://github.com/DuendeSoftware/Support/assets/85977888/a253e2cb-fc03-40aa-8927-625e25adaed5">
then after the user login and redirect to the application, the check session do the authentication for the client application but then connect/authorize endpoint returns an error to the callback page:
`callback.aspx?error=login_required&state=%2B3CR1YgVwrh3W%2FigmBSyDH0%3D&session_state=ypmO_N-qFZ6ZhWVIOFFBEySE-ERfCpMWFUkKZskTP_c.A02172AE1C838B6EC0E1AADA498BDAF6`
so the user has to login again
<img width="1088" alt="image" src="https://github.com/DuendeSoftware/Support/assets/85977888/5a19df24-dd82-49bf-98f4-234437e95253">

what is wrong here? this happened even when the user didn't switch the account.
thanks.

**Comment by josephdecock** [comment]
Sorry for the delay getting back to you @jasonliao-cb. Are you still having this problem? The error that is being returned to the login page is the expected response for a silent login attempt (prompt=none) when there is no session at the identity provider. So it's basically identity server saying "you tried to do the silent login, but I can't silently log you in because you're not already logged in".

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by jasonliao-cb** [comment]
@josephdecock We now use the sessionStorage to handle this and it works. I just think in the document there should be some related document for this case.

**Comment by josephdecock** [comment]
You're so welcome - glad you got it working!
