### ISSUE TITLE
How to set identity token and access token timeout in run time

### ISSUE THREAD

**Issue by vrrenga123** [DuendeSoftware/Support#731]
**Which version of Duende IdentityServer are you using?** 
Duende Identity Server 6.1.6

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
I am using Identity Server 6.0 with my ASP.NET Core. It is working fine. I tried to set the Access Token lifetime based on the roles in run time but it always takes database configure value, it's not overwriting the run time value

I tried to set in both places Login and GetProfileDataAsync but its not working as expected.

```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginInputModel model, string button, bool isCACLogin = false)
        {
            // check if we are in the context of an authorization request
            var context = await _interaction.GetAuthorizationContextAsync(model.ReturnUrl);
            
            context.Client.AccessTokenLifetime  = (int)new TimeSpan(0, 8, 0).TotalSeconds;
            context.Client.IdentityTokenLifetime  = (int)new TimeSpan(0, 8, 0).TotalSeconds;
```

```
        public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            string sub = context.Subject.GetSubjectId();
            AspNetUser user = await _userMgr.FindByIdAsync(sub);


            context.Client.AccessTokenLifetime = (int)new TimeSpan(0, 8, 0).TotalSeconds;
            context.Client.IdentityTokenLifetime = (int)new TimeSpan(0, 8, 0).TotalSeconds;

```

**Comment by josephdecock** [comment]
You can't change the client configuration in this way. Instead, I would create a custom `ITokenResponseGenerator`. You could extend from the default implementation (`TokenResponseGenerator`), and override ProcessTokenRequestAsync. In your override, call the base method to get the default behavior, and then change the resulting `TokenResponse.AccessTokenLifetime` with your custom logic.

**Comment by vrrenga123** [comment]
Thank you! That helps a lot
