### ISSUE TITLE
Session management in MFE architecture

### ISSUE THREAD

**Issue by fultke01** [DuendeSoftware/Support#735]
**Which version of Duende BFF are you using?**
2.0

**Which version of .NET are you using?**
net6.0

**Question**
I'm looking at creating a Micro Front End web app where each MFE participating in the SPA has its own BFF. That means each MFE is independently runnable and has full control over its remote API mappings. The MFEs are intended to share a login and session. 

A specific design goal is to not have to coordinate deployment for any MFE dependency upgrades, including the BFFs' AspNetCore and Duende.BFF versions.

What is your opinion on how to implement session management in this situation?

Does it make sense to simply configure each BFF's server side session using the same SQL or Redis (custom) connection string? Or is it more advisable to create a Session Management API as a compatibility layer to smooth out upgrades?

I noticed that your SQL implementation has an app discriminator and comments about supporting multiple apps using the same session table. Is it your vision that all participating apps are the same Duende.BFF version? Or is the expected stability of the session schema and behavior just that high?

**Comment by josephdecock** [comment]
The application discriminator is intended to be used if all the applications are on the same version of the BFF. We might make schema changes in a future version, so if you need independent deployment of your frontends, I would not share a database between them.

**Comment by fultke01** [comment]
Got it, thanks for the advice.
