### ISSUE TITLE
Communication with domain controller

### ISSUE THREAD

**Issue by ExplPatrick** [DuendeSoftware/Support#739]
**Which version of Duende IdentityServer are you using?**
5.2.4

**Which version of .NET are you using?**
3.1

Question:
We use identityserver with a deposited ldapserver. We have seen via logs that there is a communication directly with the domain controllers (SASL , KEBEROS). Is it that identityServer detects them and communicates directly with them?

**Comment by josephdecock** [comment]
No, IdentityServer doesn't have any built in communication with ldap.
