### ISSUE TITLE
Model Extensibility

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#74]
**Which version of Duende IdentityServer are you using?**
6.1

**Which version of .NET are you using?**
6
**Describe the bug**
Unable to extend model with additional properties. 

**To Reproduce**

N/A

**Expected behavior**

It would be nicht if the stores would be implemented as generics, for example IClientStore<Client>, ClientStore<Client>.
Than we could define ExtendedClient class that derives from Client, and defines additional properties, and you that class when registering ClientStore in DI.

Is there any other way to achieve this? I know that I could use client properties. But, than I would need to perform join when executing queries. And I want to avoid that.

Is this maybe planned for future releases? 

Best regards,
Novak

**Comment by brockallen** [comment]
Do you need to perform joins when loading the config data under normal workflows in IdentityServer? Also, what prevents your own DbContext (or whatever ORM/DB system) from just being used to fetch the additional data?

Doing this might be a lot of work for dubious benefits (with likely breaking changes and upgrade work) given that there are reasonable workarounds... and I'm sure we'd not make it work like everyone would want ideally. Given that there's only so much time in the day, my preference would be that our focus is more on the protocol work, and not so much on general purpose, yet extensible, configuration systems.

If we were starting from scratch, then perhaps. I'm not adverse to considering something like this for this effort: https://github.com/DuendeSoftware/IdentityServer/issues/655, but again not sure how high of a priority it would be compared to the other features.

Sorry -- I know this is probably not the answer you wanted to hear.

**Comment by No1e** [comment]
Yes, that was my third option with my own DbContext, but I didn't mentioned it becase of effort required. It seems that I need to go down that road anyway :-). 

Cheers,
Novak
