### ISSUE TITLE
i am using Identity Server 6. The Problem is How to API Authorize in Asp.net(.Net Framework 4.8)?

### ISSUE THREAD

**Issue by Ommkwn2001** [DuendeSoftware/Support#741]
My IdentityServer 6 version is in .NET Core and My Web API and Web MVC is in the (.Net Framework 4.8).

The Error is when I call Web API through the Web MVC the Web API KeySet is null There are not show any key in the Key Set.

The WebAPI startup code is below.

```
public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseJwtBearerAuthentication(new JwtBearerAuthenticationOptions
            {
                AuthenticationType = "jwt",
                AuthenticationMode = AuthenticationMode.Active,
                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = Urls.IdentityServer,
                    ValidAudience = Urls.IdentityServer + "/resources",
                    IssuerSigningKeyResolver = LoadKeys,
                    NameClaimType = "name",
                    RoleClaimType = "role"
                },
            });

            HttpConfiguration config = new HttpConfiguration();
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
            app.UseWebApi(config);
        }

        internal static DiscoveryCache _discoveryCache = new DiscoveryCache(Urls.IdentityServer);

        private IEnumerable<SecurityKey> LoadKeys(string token, SecurityToken securityToken, string kid, TokenValidationParameters validationParameters)
        {
            var disco = _discoveryCache.GetAsync().ConfigureAwait(false).GetAwaiter().GetResult();

            var keys = disco.KeySet.Keys
                .Where(x => x.N != null && x.E != null)
                .Select(x => {
                    var rsa = new RSAParameters
                    {
                        Exponent = Base64UrlEncoder.DecodeBytes(x.E),
                        Modulus = Base64UrlEncoder.DecodeBytes(x.N),
                    };

                    return new RsaSecurityKey(rsa)
                    {
                        KeyId = x.Kid
                    };
                });

            return keys;
        }
    }
```

My IdentityServer6 startup code is blow 

```
public class Startup
    {
        public IWebHostEnvironment Environment { get; }
        public IConfiguration Configuration { get; }

        public Startup(IWebHostEnvironment environment, IConfiguration configuration)
        {
            Environment = environment;
            Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            

            var connectionString = Configuration.GetConnectionString("WebApplication1ContextConnection") ?? throw new InvalidOperationException("Connection string 'WebApplication1ContextConnection' not found.");

            services.AddDbContext<WebApplication1Context>(options => options.UseSqlServer(connectionString));

            services.AddDefaultIdentity<WebApplication1User>(options => options.SignIn.RequireConfirmedAccount = true).AddEntityFrameworkStores<WebApplication1Context>();


            services.AddRazorPages();


            var builder = services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
                options.EmitStaticAudienceClaim = true;
                options.UserInteraction.LoginUrl = "/identity/account/login";

            });
             
            services.AddScoped<IProfileService, AspNetProfileService>();
            services.AddScoped<LoginValidationService>();
            services.AddScoped<AspNetProfileService>();
            builder.AddInMemoryIdentityResources(Resources.Identity);
            builder.AddInMemoryApiResources(Resources.ApiResources);
            builder.AddInMemoryApiScopes(Resources.ApiScopes);
            builder.AddInMemoryClients(Clients.List);
            builder.AddJwtBearerClientAuthentication();
          
            services.AddAuthentication()
                .AddOpenIdConnect("Google", "Sign-in with Google", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.ForwardSignOut = IdentityServerConstants.DefaultCookieAuthenticationScheme;
                    
                    options.Authority = "https://accounts.google.com/";
                    options.ClientId = "708778530804-rhu8gc4kged3he14tbmonhmhe7a43hlp.apps.googleusercontent.com";
                    //options.SignInScheme = "/Account/Login";
                    options.CallbackPath = "/signin-google";
                    options.Scope.Add("email");
                   
                });

        public void Configure(IApplicationBuilder app)
        {
            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();
            app.UseAuthentication();
           

            app.UseRouting();
            app.UseIdentityServer();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }
    }
```

**Comment by josephdecock** [comment]
I would check a few things:

Are you able to load the discovery document and the jwks discovery outside of your api? On our demo server, the urls are https://demo.duendesoftware.com/.well-known/openid-configuration and https://demo.duendesoftware.com/.well-known/openid-configuration/jwks. Change the base url to match your identity server host.

Within your application, is discovery failing, or is it only the jwks endpoint? You can add error handling code around your request for the disco document:

```
var disco = _discoveryCache.GetAsync().ConfigureAwait(false).GetAwaiter().GetResult();
if (disco.IsError) throw new Exception(disco.Error);
```

**Comment by Ommkwn2001** [comment]
[https://[localhost:7030/.well-known/openid-configuration](https://localhost:7030/.well-known/openid-configuration)](url)
when i search this url the output is...

{
    "issuer": "https://localhost:7030",
    "jwks_uri": "https://localhost:7030/.well-known/openid-configuration/jwks",
    "authorization_endpoint": "https://localhost:7030/connect/authorize",
    "token_endpoint": "https://localhost:7030/connect/token",
    "userinfo_endpoint": "https://localhost:7030/connect/userinfo",
    "end_session_endpoint": "https://localhost:7030/connect/endsession",
    "check_session_iframe": "https://localhost:7030/connect/checksession",
    "revocation_endpoint": "https://localhost:7030/connect/revocation",
    "introspection_endpoint": "https://localhost:7030/connect/introspect",
    "device_authorization_endpoint": "https://localhost:7030/connect/deviceauthorization",
    "backchannel_authentication_endpoint": "https://localhost:7030/connect/ciba",
    "frontchannel_logout_supported": true,
    "frontchannel_logout_session_supported": true,
    "backchannel_logout_supported": true,
    "backchannel_logout_session_supported": true,
    "scopes_supported": [
        "openid",
        "profile",
        "scope1",
        "offline_access"
    ],
    "claims_supported": [
        "sub",
        "name",
        "family_name",
        "given_name",
        "middle_name",
        "nickname",
        "preferred_username",
        "profile",
        "picture",
        "website",
        "gender",
        "birthdate",
        "zoneinfo",
        "locale",
        "updated_at"
    ],
    "grant_types_supported": [
        "authorization_code",
        "client_credentials",
        "refresh_token",
        "implicit",
        "urn:ietf:params:oauth:grant-type:device_code",
        "urn:openid:params:grant-type:ciba"
    ],
    "response_types_supported": [
        "code",
        "token",
        "id_token",
        "id_token token",
        "code id_token",
        "code token",
        "code id_token token"
    ],
    "response_modes_supported": [
        "form_post",
        "query",
        "fragment"
    ],
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "private_key_jwt"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "subject_types_supported": [
        "public"
    ],
    "code_challenge_methods_supported": [
        "plain",
        "S256"
    ],
    "request_parameter_supported": true,
    "request_object_signing_alg_values_supported": [
        "RS256",
        "RS384",
        "RS512",
        "PS256",
        "PS384",
        "PS512",
        "ES256",
        "ES384",
        "ES512",
        "HS256",
        "HS384",
        "HS512"
    ],
    "prompt_values_supported": [
        "none",
        "login",
        "consent",
        "select_account"
    ],
    "authorization_response_iss_parameter_supported": true,
    "backchannel_token_delivery_modes_supported": [
        "poll"
    ],
    "backchannel_user_code_parameter_supported": true,
    "dpop_signing_alg_values_supported": [
        "RS256",
        "RS384",
        "RS512",
        "PS256",
        "PS384",
        "PS512",
        "ES256",
        "ES384",
        "ES512"
    ]
}

and when is run this [https://[localhost:7030/.well-known/openid-configuration/jwks](url) the output is ...

{
    "keys": [
        {
            "kty": "RSA",
            "use": "sig",
            "kid": "F10C21D538E62AADCF5E7C6BB2451D15",
            "e": "AQAB",
            "n": "zCOBOg_SZPQ-fCEfvkLcKVx2mIjIAV6sShk-1sYQo47fuaXspw0TN0JDF90MRcPr26etK0jQTHghkk6J4G6qhWEcejsPRQ-Wr74C5M2Ue0VEo6GURSNo6c_RHfq5XKUklQZH8XKO-td-rlFID-_X11YvTn8Sk-jbFLD5ELjTB9ODFJKa00p3KlrCBUjunqIz8H0TcAqKUEL3OZneXAueWnWEzh83lSlGme4DUifbAAP3NB_D9bpIRdJ-BmuxmMKlK67ef2hJRKKqw_2gUmhQvwq1tiJRhTHjwLdQd3td3fo6IYih1RJfA8yqPETFxoYhvs-QBTBsM5ViYfMYXrvgaQ",
            "alg": "RS256"
        },
        {
            "kty": "RSA",
            "use": "sig",
            "kid": "0FEFA380510753761A38C64C524B2A08",
            "e": "AQAB",
            "n": "veqhoSyYyO5Do59CONIIGjbG3bhHCwhtEiu4WUhT954qAq0nJc8B6LcqXiFPZP6_9JGO5dFXvOYqZwB3zHV35utDw3JMa-dyZ5KWkJO0CUVf3AJDaOcRUGg_TzwYmXL3cY_RLXdkhFx7i1yDPsKCH--z-_sNr_Zj1H5aUxMg-f2XY40F3HyVHNX-iyOHLsW0vIxCNHM47iXy2DP2gWmQ-_8vngYMt6NmjZzMBRbrRnwAPIwaneghyhbxiQC8Eg5T0IJitxR2Z5Vy9x4zZgNCtopUcEYSXmLOWVqX6X1iUdrvxo8iWojmTRuDNfsfItcuGcbsJ1o_44o1g1hTlSeKlQ",
            "alg": "RS256"
        }
    ]
}

and i try add if (disco.IsError) throw new Exception(disco.Error); this line in my code the error is ....

"Issuer name is missing."

**Comment by brockallen** [comment]
Also, we have a sample for this scenario: https://docs.duendesoftware.com/identityserver/v6/samples/clients/#net-48-clients

Please try it and see if it works for you.

**Comment by Ommkwn2001** [comment]
Ok, i have an answer to this question. KeySet is null in my Web API startup. I did include one method for this solution. and I solved my problem with this method. The method is...

`{
public class OpenIdConnectSigningKeyResolver
{
    private readonly OpenIdConnectConfiguration openIdConfig;

    public OpenIdConnectSigningKeyResolver(string authority)
    {
        var cm = new ConfigurationManager<OpenIdConnectConfiguration>($"{authority.TrimEnd('/')}/.well-known/openid-configuration", new OpenIdConnectConfigurationRetriever());
        openIdConfig = AsyncHelper.RunSync(async () => await cm.GetConfigurationAsync());
    }

    public SecurityKey[] GetSigningKey(string kid)
    {
        return new[] { openIdConfig.JsonWebKeySet.GetSigningKeys().FirstOrDefault(t => t.KeyId == kid) };
    }
}`

And my Web API Startup is...

`public class Startup
{
    public void Configuration(IAppBuilder app)
    {
        var Domain = Urls.IdentityServer;
        var KeyResolver = new OpenIdConnectSigningKeyResolver(Domain);

        app.UseJwtBearerAuthentication(new JwtBearerAuthenticationOptions
        {
            AuthenticationType = "jwt",
            AuthenticationMode = AuthenticationMode.Active,
            TokenValidationParameters = new TokenValidationParameters
            {
                ValidIssuer = Domain,
                ValidAudience = "APICore",
                IssuerSigningKeyResolver = (token, securityToken, kid, parameters) => KeyResolver.GetSigningKey(kid)
            }
        });

        HttpConfiguration config = new HttpConfiguration();
        config.Routes.MapHttpRoute(
        name: "DefaultApi",
        routeTemplate: "{controller}/{id}",
            defaults: new { id = RouteParameter.Optional });
        app.UseWebApi(config);
    }
}`

**Comment by josephdecock** [comment]
Okay great - I'll close this issue since you have things working.
