### ISSUE TITLE
Question on refresh token lifetime

### ISSUE THREAD

**Issue by eithe** [DuendeSoftware/Support#743]
**Which version of Duende IdentityServer are you using?**
Latest as of writing (6.3.2)

**Which version of .NET are you using?**
.NET7

**Describe the question**

Hi, I have a question on refresh tokens.

We want:
-	Access tokens that only last 1 hour
-	Refresh token setup in such a way that a user can only stay logged in for a maximum of 10 hours.
-	Refresh tokens usage: One time only

With the setup below when a refresh is executed (let’s say after 1 hour), will the new refresh token (due to TokenUsage.OneTimeOnly) last another 10 hours, or will it honor the AbsoluteRefreshTokenLifetime and make sure the refresh token is only valid for an additional (10-1) 9 hours?

```
new Client
    {
        AbsoluteRefreshTokenLifetime = 36000, // 10 hours
        AccessTokenLifetime = 3600, // 1 hour
        AllowAccessTokensViaBrowser = true,
        AllowedCorsOrigins = _uriOptions.AllowedCorsOriginsFormatted,
        AllowedGrantTypes = GrantTypes.Code,
        AllowOfflineAccess = true,
        ClientId = AuthenticationConstants.ClientIds.WebApp,
        ClientName = "Some name",
        PostLogoutRedirectUris = _uriOptions.PostLogoutRedirectUrisFormatted,
        RedirectUris = _uriOptions.RedirectUrisFormatted,
        RefreshTokenUsage = TokenUsage.OneTimeOnly,
        RefreshTokenExpiration = TokenExpiration.Absolute,
        RequireClientSecret = false,
        RequirePkce = true,
        AllowedScopes =
        {
            IdentityServerConstants.StandardScopes.OfflineAccess,
            IdentityServerConstants.StandardScopes.OpenId,
            IdentityServerConstants.StandardScopes.Profile,
            ...
        }
    },
```

**Comment by eithe** [comment]
Ok, thanks @brockallen. I believe as you said that the one-time use is irrelevant to what I am seeing.

Looking a bit further, and outside the field of refresh tokens, I discovered UserSsoLifetime which perhaps gives me what I am after if I understand it correctly. If I set that to 10 hours I will force the user to provide credentials again to stay logged in, right?

Cause what I am seeing now (without that) is:

If I adjust to the following (so I don't have to wait so long):
```
AbsoluteRefreshTokenLifetime = 1200, // 20 mins
AccessTokenLifetime = 360, // 6 mins
...
```
I can silently renew (/connect/token with `grant_type=refresh_token`) 3 times (just before 6 mins, 12 mins, and 18 mins). The refresh after 18 mins gives me an access token with `expires_in: 360` so I get access for a total of ~24 mins. This is as expected.

When I (specifically oidc-client-ts) then try a refresh after 24 mins (AbsoluteRefreshTokenLifetime has now expired) I get a 400 from the /connect/token request, and a new authorize-request is made:

https://localhost:44300/connect/authorize?client_id=some-web-app&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2F&response_type=code&scope=openid+profile+api+user-profile+offline_access&state=ff23e5ead0884499a82fff17a03374b9&code_challenge=H9yPzP...3D2M&code_challenge_method=S256&response_mode=query

Which responds with 302 and location: http://localhost:5000/?code=CE2....6F-1&scope=openid%20profile%20api%20user-profile%20offline_access&state=ff23e5ead0884499a82fff17a03374b9&session_state=xFs7t...2DA&iss=https%3A%2F%2Flocalhost%3A44300

Which is then loaded, and finally there is a new token request:
/connect/token with grant_type: authorization_code

And then I get a new refresh+access token, and can continue from the top again, silently refreshing 3 times, and so it continues, keeping the user logged in forever from what I have seen so far.

**Comment by brockallen** [comment]
>  I discovered UserSsoLifetime which perhaps gives me what I am after if I understand it correctly. If I set that to 10 hours I will force the user to provide credentials again to stay logged in, right?

Yes, but this is a per-client setting. If you want a more "global" setting, then consider setting the user's session expiration on the login page to be the limit you want via the AuthenticationProperties setting on the SignInAsync method from Microsoft. 

A different way would be to also just configure the session expiration values on the cookie options or with ours if you use our cookie handler:

https://docs.duendesoftware.com/identityserver/v6/ui/login/session/

As for your SPA that has the token directly, we don't recommend using refresh tokens. There is quite a bit of guidance here:

https://www.youtube.com/watch?v=xzRhabmlc8M

And the recommendation is to use a BFF pattern:

https://docs.duendesoftware.com/identityserver/v6/bff/
