### ISSUE TITLE
Receving "Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2." for issuers that er technically the same

### ISSUE THREAD

**Issue by pallesaphe** [DuendeSoftware/Support#747]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
7.0
**Describe the bug**
We are receiving the following error message :
"Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: https://example.com:443, https://example.com."

Both hostnames are exactly same (example.com are only a placeholder) the only difference is that port 443 are added. And since the default port for https is 443 they are infact the same.

We do have a load balancer in front of several instances of the Duende IdentityServer, but only serves one domain.

On a related note we have tried turning on HttpLogging of the https requests (since we would except all http interaction with Duende IdentityServer would also be logged), but I can't find any cases there the "host" part indicates any thing about port 443 is explicit set when accessing the service via the domain name:

"info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1] Request: Protocol: HTTP/2 Method: POST Scheme: https PathBase:  Path: /connect/token Accept: */* Host: example.com User-Agent: XX/3320 CFNetwork/1408.0.4 Darwin/22.5.0 Accept-Encoding: gzip, deflate, br Accept-Language: da-DK,da;q=0.9 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Content-Length: 119"

As a result we haven't been able to identity which client adds the additional and unnecessary port 443.

**To Reproduce**

**Expected behavior**

We would not get a license error as the domains are techically the same and running on the same ports.

**Log output/exception with stacktrace**

"Your license for Duende IdentityServer only permits 1 number of issuers. You have processed requests for 2. The issuers used were: https://example.com:443, https://example.com."

"info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1] Request: Protocol: HTTP/2 Method: POST Scheme: https PathBase:  Path: /connect/token Accept: */* Host: example.com User-Agent: Saphe%20Link/3320 CFNetwork/1408.0.4 Darwin/22.5.0 Accept-Encoding: gzip, deflate, br Accept-Language: da-DK,da;q=0.9 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Content-Length: 119"

**Additional context**

**Comment by brockallen** [comment]
We'll have a look. In the meantime if you can do some more diffing, that might help as well. Thanks.

**Comment by pallesaphe** [comment]
The middleware could be a solution, but then we would have expected that the HttpLoggingMiddleware Request logging would have shown it int the "Host: " part as "Host: example.com:443". Which we don't see for any of the requests that goes to IdentityServer. 

In fact we do have some like the above, but they are for our liveness probes which uses a direct ip address and not the domain. Which further confirms we should have seen it for requests for IdentityServer.
Below is an example of how they look in regards to our liveness probes.

"info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1] Request: Protocol: HTTP/2 Method: GET Scheme: https PathBase:  Path: /health/liveness Accept: */* Host: 10.8.0.18:443 User-Agent: kube-probe/1.24"

**Comment by pallesaphe** [comment]
Also is there any relation between the amount of license errors and a given type(s) of requests to IdentityServer. Because that might help us narrow it down :-)

**Comment by brockallen** [comment]
> In fact we do have some like the above, but they are for our liveness probes which uses a direct ip address and not the domain. Which further confirms we should have seen it for requests for IdentityServer.

Ah is different then. In this case, why not just set the IssuerUri property? This is what we recommend in these scenarios:

https://docs.duendesoftware.com/identityserver/v6/reference/options/#main

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
