### ISSUE TITLE
Users first login attempt fails, second works

### ISSUE THREAD

**Issue by ExplPatrick** [DuendeSoftware/Support#748]
**Which version of Duende IdentityServer are you using?**
5.2.4
**Which version of .NET are you using?**
3.1
**Describe the bug**

We have a user who can't get in on the first login attempt. The message "No User present in authorize request" appears in the logs. The second login attempt is always successful. What could it be that his first attempt always fails but the second one works?

**Comment by brockallen** [comment]
This sounds like the user's authentication cookie issued on the login page is not making it in the redirect from the login page back to the returnIUrl (which should be back to the authorize endpoint). That's what I'd suggest looking into.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?
