### ISSUE TITLE
/connect/authorize OPTIONS is not supported?

### ISSUE THREAD

**Issue by gslulu** [DuendeSoftware/Support#75]
Need help with overcoming "has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource"

Is the OPTIONS not supported on /connect/authorize?
What can be done for /connect/authorize to return Access-Control-Allow-Origin in the header.

Since I'm using SPA application with Spring OAuth security, the /connect/authorize is redirect from API server address and hence resulting in CORS error.

Access to XMLHttpRequest at 'https://.../connect/authorize?response_type=code&client_id=....&scope=.......' (redirected from 'http://localhost:8081/oauth2/authorization/...') from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by gslulu** [comment]
I already had Origin of the Client and API server under AllowedCorsOrigins

But, this is exactly what I was doing 'getting redirected from my API app on an Ajax call'. 
But, what is the reason that it is the wrong way to initiate that request?

**Comment by brockallen** [comment]
The result of authorize is to render HTML. That just doesn't make sense if you're making Ajax calls. Instead redirect the main window to the endpoint in your app, and let that response redirect the window to the ~/authorize. That's how OIDC/OAuth is expected to work.

**Comment by gslulu** [comment]
I'm not handling the response of the AJAX call on my API.
The 302 is sent back to frontend.
This is the flow in my application:
![image](https://user-images.githubusercontent.com/33190467/172309650-3e4c0671-3ce4-42cc-b786-78a67167ad66.png)

The below is the CORS error pattern
Access to XMLHttpRequest at 'https://my-duende.com/connect/authorize?......' (redirected from 'http://my-api/oauth2/authorization/myapp') from origin 'http://my-ui.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Also, I noticed that the logs on the auth server show it received and processed the request successfully. 
It is just the browser not letting me go further from CORS detection.

@brockallen your comments are really appreciated

**Comment by leastprivilege** [comment]
It seems the 302 is happening in the context of the XHR request.

The redirect to the authorize endpoint must be top level standard redirect like using `window.location`.

**Comment by gslulu** [comment]
Thank You for the feedback. I guess I have to capture the 302 response from my AXIOS GET request and spawn a new XHR or window.location.
