### ISSUE TITLE
`CorsPolicyService` does not consider the client

### ISSUE THREAD

**Issue by hugoqribeiro** [DuendeSoftware/Support#754]
**Which version of Duende IdentityServer are you using?**

6.3.2

**Which version of .NET are you using?**

.NET 7

**Describe the bug**

`CorsPolicyService` checks the CORS origin without considering the client. This means that if, for example, you remove `https://localhost:44300` from the allowed CORS origins for client X, requests from that address for client X will still be allowed if there is another client Y that has `https://localhost:44300` in the allowed CORS origins list.

**To Reproduce**

1. Edit client Y and add `https://localhost:44300` in the allowed CORS origins.
2. Edit client X and make sure there are no allowed CORS origins.
3. Make requests from client X with a front-end client running on `https://localhost:44300`.
4. The CORS origin is allowed even though it is not allowed for client X.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen or follow up as needed.
