### ISSUE TITLE
Multiple ValidIssuers for jwt tokens

### ISSUE THREAD

**Issue by raffsokolowski** [DuendeSoftware/Support#756]
**Which version of Duende IdentityServer are you using?**
6.3.2

**Which version of .NET are you using?**
.NET 7

**Describe the bug**
I require the need to be able to set multiple ValidIssuers for jwt tokens
Cannot find anywhere to change the setting.
This is a common setting available to other jwt token providers.

**Expected behavior**
I would expect to be able to set multiple valid issuer settings like the following:

services.AddIdentityServer(options =>
{
    // Option 1 (preferable): Provide multiple valid issuers
    options.TokenValidationParameters.ValidIssuers = new List<string>
    {
        "http://localhost:5000",
        "http://127.0.0.1:5000"
    };

    // Option 2: turn off issuer validation all together
    options.TokenValidationParameters.ValidateIssuer = false;
});

**Comment by josephdecock** [comment]
In the IdentityServer options, the IssuerUri sets the name of the token server, used in the discovery document as the issuer claim and in JWT tokens and introspection responses as the iss claim.

However, it is not recommended to set this option. If it is not set (the default), the issuer is inferred from the URL used by clients. This better conforms to the OpenID Connect specification, which requires that issuer values be “identical to the Issuer URL that was directly used to retrieve the configuration information”. It is also more convenient for clients to validate the issuer of tokens, because they will not need additional configuration or customization to know the expected issuer.

It's not clear to me how IdentityServer could usefully set multiple IssuerUris as a configuration option. If it were possible to configure multiple issuers, IdentityServer would have to pick one of the issuer values whenever it actually created a token, and there's no obvious way to make that choice (there's certainly no protocol parameter for this purpose).

You can have multiple issuers, simply by not setting the option and having multiple dns addresses for your IdentityServer instance. Then, whichever one is used by the client will be the one used by IdentityServer when it issues a token. But do note that multiple instances like that is an enterprise feature.

**Comment by raffsokolowski** [comment]
Hi Joseph,

Thank you for your response.

Let me run through a scenario for multiple ValidIssuers...

A client application authenticates against "primary.somewhere.com" and retrieves a jwt token, this token by default will have an IssuerUri of "primary.somewhere.com".

The client was determined they belong to a certain region like "region1.somewhere.com" which is geographically located closer to their location for latency purposes.

The token only works against "primary.somewhere.com" and will fail if attempted to be used against "region1.somewhere.com".

Assume there is a communication requirement for the client to send/receive some data from "primary.somewhere.com" but the bulk of the data would be against "region1.somewhere.com".

If Issuer validation settings could be set to allow both "primary.somewhere.com" and "region1.somewhere.com" then the token could be used for both connections.

This is the error I get from IdentityServer which shows it should have the capability for setting the ValidIssuers option but doesn't

JWT token validation error: "IDX10205: Issuer validation failed. Issuer: 'https://region1.somewhere.com'. Did not match: validationParameters.ValidIssuer: 'https://primary.somewhere.com' or validationParameters.ValidIssuers: 'null' or validationParameters.ConfigurationManager.CurrentConfiguration.Issuer: 'Null'. For more details, see https://aka.ms/IdentityModel/issuer-validation. "

note the: " validationParameters.ValidIssuers: 'null' "
Reding more information from the above link provided by this error "https://aka.ms/IdentityModel/issuer-validation" shows:

To resolve the issue, make sure the correct issuer is specified in the ValidIssuer or ValidIssuers or IssuerValidator property of TokenValidationParameters. The issuer is checked based on one value coming from the OIDC document, based on the provided authority in the configuration, and the other value is coming from the token.

This tells me that its a valid OpenID Connect option and should be allowed by IdentityServer also.

**Comment by josephdecock** [comment]
I think you are conflating the semantics of the issuer claim and the valid issuers. The issuer of the token uniquely describes where the token was created. It is a statement made by a token server about a token. Clearly any token has to have been issued by some particular issuer, so it isn't accurate to claim that a token has multiple issuers. 

The allowed issuers of the token validation parameters used in the APIs and client applications say which issuers are valid, that is, which issuers can be in a token in order for it to be accepted. 

I recommend that you bind your identity server to respond to requests to both of the urls that you want as issuers and not configure it with an explicit issuerUri, arrange for your client applications to use one of the issuers to get tokens, and for your APIs to allow either issuerUri.

**Comment by raffsokolowski** [comment]
I understand what you mean about the issuer of the token describing where it was created.

Since my identity server doesn't set an explicit IssuerUri, it will use the Uri which requested the token.
If the client application uses either 'https://primary.somewhere.com/' or 'https://region1.somewhere.com/' to request the token, how do I allow either of those IssuerUri's access to the API?

The API is in the same project as identity server and uses the following attributes on the controller:
[ApiController]
[Authorize(LocalApi.PolicyName)]

**Comment by josephdecock** [comment]
In your API, set the valid issuers in the token validation parameters of the Jwt Bearer Authentication handler to include both issuers.

**Comment by josephdecock** [comment]
@raffsokolowski Did setting two valid issuers work for you? Are we good to close this issue?

**Comment by raffsokolowski** [comment]
Hi Joe,

Setting two or multiple valid issuers is what I was originally asking for in the first post to this issue.
I cannot find a way to set this option when my API is part of the same same project and I need to use [Authorize(LocalApi.PolicyName)] attribute on my api controller.

when using builder.Services.AddIdentityServer(options =>...
it uses the DefaultTokenService with Duende.IdentityServer.Models.Token which doesn't have any of the TokenValidationParameters available.

**Comment by josephdecock** [comment]
Oh, I'm so sorry - I overlooked your statement that the apis are in the same project as IdentityServer and using the LocalApi infrastructure.

To make those work with multiple issuers, you'll need to stop using the `LocalApi.PolicyName` authorization policy. When you use that policy along with `AddLocalApiAuthentication`, IdentityServer will use an authentication scheme that validates its own tokens using the same infrastructure that it uses to validate tokens in other contexts such as the user info or introspection endpoints. That validation logic is not easily extendible, and we don't generally recommend that you make changes to it.

However, you can change your APIs to use your own authorization policy and authentication scheme that will validate tokens from multiple issuers.

You can use the `Microsoft.AspNetCore.Authentication.JwtBearer` package to get an authentication handler that will validate JWTs:

```
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.9" />
```

And then configure it to accept JWTs from multiple issuers:

```
        IdentityModelEventSource.ShowPII = true; // This is just for debugging
        builder.Services.AddAuthentication()
            .AddJwtBearer("jwt-bearer-allowing-multiple-issuers", opt =>
            {
                opt.Authority = "https://localhost:5001"; // Either url to identity server works as the authority
                opt.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false,
                    ValidIssuers = new[] { "https://localhost:5001", "http://127.0.0.1:5000" },
                };
            });
```

And then create an authorization policy that will use this scheme:

```
builder.Services.AddAuthorization(opt =>
        {
            opt.AddPolicy("AllowMultipleIssuers", p =>
            {
                p.AddAuthenticationSchemes("jwt-bearer-allowing-multiple-issuers");
                p.RequireAuthenticatedUser();
            });
        });
```

And finally, secure your controllers with that policy:

```
       app.MapControllers()
            .RequireAuthorization("AllowMultipleIssuers");
```

**Comment by raffsokolowski** [comment]
Thank you, I will give this a try.

**Comment by josephdecock** [comment]
Ok, please let us know how it goes.

**Comment by raffsokolowski** [comment]
Hi Joe,

I got this to work, although I had to make an adjustment to the JwtBearer options as the claims weren't being filled correctly, so I ended up with the following:

        builder.Services.AddAuthentication()
            .AddJwtBearer("jwt-bearer-allowing-multiple-issuers", opt =>
            {
                opt.Authority = "https://localhost:5001"; // Either url to identity server works as the authority
                opt.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false,
                    ValidIssuers = new[] { "https://localhost:5001", "http://127.0.0.1:5000" },
                };
                opt.SecurityTokenValidators.Clear();
                opt.SecurityTokenValidators.Add(new JwtSecurityTokenHandler
                {
                    MapInboundClaims = false
                });
            });
            
Thanks for pointing me in the right direction.

**Comment by josephdecock** [comment]
Glad you got this working. I'll close this issue, but feel free to reopen or follow up with a new one if you need anything else!
