### ISSUE TITLE
How to use IUserStore to find user based on custom column

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#757]
I'm using IdentityServer4 and .NET 6.

I have a class I'm using to get user info from the DB:

```
    public class MyUserStore : IUserStore<MyUser>
    {
        async Task<MyUser> IUserStore<MyUser>.FindByIdAsync(string userId, CancellationToken cancellationToken)
        {...}
    }
```

Here's my DI setup:

`.AddScoped<IUserStore<MyUser>, MyUserStore>();`

I'd like to create a similar method called `FindByIdentityProviderIdAsync()` in order to find a user based on a different column.

Is this impossible because I'm limited to what is available in `IUserStore`, if not, how do you go about doing it?

**Comment by josephdecock** [comment]
IdentityServer doesn't place any constraints on the way that the user store is implemented. The user store is (from the perspective of IdwntotyServer) an implementation detail of your login page. Identity server relies on your login page calling SignInAsync. Very often you would use some sort of user store abstraction to retrieve the principle that you pass to that method, but that isn't directly part of identity server.

Also, and this is really a side note, but the combination of IdentityServer and dotnet versions that you say you're using is not supported. My main answer above has been true all the way back to IdentityServer4, but IdentityServer4 is not developed or maintained anymore, and there never was a build of it that targeted dotnet 6. The older versions of dotnet that it did target are not supported by Microsoft anymore either, so we'd really encourage you to update to Duende.IdentityServer 6.3 and dotnet 6.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by DavidKlempfner** [comment]
You can close it.
