### ISSUE TITLE
SignalR Support for BFF

### ISSUE THREAD

**Issue by joelcoxokc** [DuendeSoftware/Support#762]
**Which version of Duende BFF are you using?**
Duende.IdentityServer:  Version="6.2.1"
Duende.BFF: Version=2.0.0

**Which version of .NET are you using?**
net6

**Describe the bug**

We are using duendes BFF. 
We have several processes that require real-time updates. However, the BFF implementation will not allow us to map signalR hub endpoints. 

I have found some partial solutions with no additional context, like this one [https://github.com/DuendeSoftware/Support/issues/551](https://github.com/DuendeSoftware/Support/issues/551)
Which I have been unsuccessful at implementing. 

Do you all have any signalR support coming in the future?

**Expected behavior**

I expect to simply use SignalR's MapHub method to map endpoints to our API. 
I also expect that SingalR requests will not move the sliding token on requests...
Something like this would be nice 

```C#
endpoints
            .MapRemoteBffHub("local/endpoint", "api/endpoint")
            .RequireAccessToken(Duende.Bff.TokenType.User);
```

Without signalR support we are having to do some very strange workaround that is not scalable... using redis caches and building controllers on our BFF that subscribe to redis.. 
And our client side angular code is having to poll every 5 seconds... Which is not ideal for modern SPAs to be this chatty.

**Comment by josephdecock** [comment]
Hi @joelcoxokc - we have at least one issue on our backlog to create more samples of signalr and the bff.  We don't have a committed date on when we'd release that, but hearing from folks like you definitely helps us as we prioritize our backlog. Sorry we can't give you a firmer commitment on this one.

**Comment by gryffs** [comment]
Would love to see this as well. Thank you!

**Comment by josephdecock** [comment]
Thanks for the feedback everyone. I'm closing this issue for now since we have issues on our backlog to consider this in the future.

**Comment by joelcoxokc** [comment]
Any updates on this @josephdecock

**Comment by AndersAbel** [comment]
Closing this issue as this is on our roadmap for the BFF. The high level issue that we are tracking this in is https://github.com/DuendeSoftware/BFF/issues/190
