### ISSUE TITLE
Revoke refresh reference token will remove all sessions tokens

### ISSUE THREAD

**Issue by evoronkin** [DuendeSoftware/Support#77]
**Which version of Duende IdentityServer are you using?**
Old IdentityServer4 and the issue apply for the latest Duende IdentitySever too

**Which version of .NET are you using?**
Latest .NET 6

**Describe the bug**

Revoking the refresh token will revoke also related reference tokens from ALL sessions.

**To Reproduce**

Create two sessions from two browsers for example.
Then revoke the refresh token for one of the browser session.
It will influence all other sessions, so not just the session of the above refresh token.

**Expected behavior**

To clear only related to the refresh token session, so not all session reference tokens.
Plus, do some clean up of of the reference tokens of the sessions which are expired or not valid anymore.

**Log output/exception with stacktrace**
None

**Additional context**
The fix, we did is to add to the 
https://github.com/DuendeSoftware/IdentityServer/blob/6.1.0/src/IdentityServer/ResponseHandling/Default/TokenRevocationResponseGenerator.cs#139
 protected virtual async Task<bool> RevokeRefreshTokenAsync(TokenRevocationRequestValidationResult validationResult)

				if (token.ClientId == validationResult.Client.ClientId) {
					Logger.LogDebug("Refresh token revoked");
					await RefreshTokenStore.RemoveRefreshTokenAsync(
						validationResult.Token);

					// Fixes the IdentityServer4 bug,
					// do not remove all reference tokens of the user's client,
					// but remove tokens for the specific session.
					await RemoveReferenceTokensAsync(
						token.SubjectId,
						token.ClientId,
						token.SessionId);

		private async Task RemoveReferenceTokensAsync(
			string subjectId,
			string clientId,
			string sessionId)
		{
			var filter = new PersistedGrantFilter {
				SubjectId = subjectId,
				ClientId  = clientId,
				SessionId = sessionId,
				Type      = PersistedGrantTypes.ReferenceToken,
			};

			await grantStore.RemoveAllAsync(filter);
		}

The one thing we missing though to clean up the expired or not valid reference tokens of other sessions, maybe you can suggest here something. So this kind of the db maintenance job at the moment.

**Comment by brockallen** [comment]
>  Then revoke the refresh token for one of the browser session.

What mechanism are you using to revoke the refresh token?

**Comment by evoronkin** [comment]
We use IdentityModel and call HttpContext.RevokeUserRefreshTokenAsync 
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/7a5c695fab848dcfffc790d57abd03eb9c254a93/src/AccessTokenManagement/UserAccessToken/UserAccessTokenManagementService.cs#L114

which goes to the token endpoint. 
Is that what you asking by saying "mechanism"?

**Comment by brockallen** [comment]
I was able to reproduce this. Not sure why we did that, but I can look more into it. Also, to be honest, this is a minor issue -- the revocation does not affect other refresh tokens, so a new reference access token can always be obtained. And client apps should always be coded to handle 401s from the API and do the renewal (but maybe all don't :)).

Anyway, I'll dig more into why we did that and see what we can do.

**Comment by brockallen** [comment]
Ok, yea -- I see the issue and you're right -- using some of our newer APIs that track the sid for token management would work better. I guess when we first developed this implementation however long ago, we weren't tracking sid like we do now... so this is a good chance to update. Thanks!

**Comment by brockallen** [comment]
I opened an issue to track and get into a fix/release, so I will close this issue. Thanks for reporting!
