### ISSUE TITLE
Getting scopes assosciated with resources is unwieldy and potentially unreliable/misleading

### ISSUE THREAD

**Issue by Pilchard123** [DuendeSoftware/Support#772]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

6

**Describe the bug**

`IResourceStore` has no way to get specific `ApiScope`s associated a given `ApiResource`. In most cases that won't be a problem, and it will be possible to filter a collection of `ApiScope`s based on `ApiResource.Scopes`, but in case there are multiple scopes having the same name but being part of different resources there is no way to tell which scope is under which resource. Even in the ideal case, it is still unwieldy having to manually filter scopes.

**To Reproduce**

Call any method on `IResourceStore` (including those in `IResourceStoreExtensions`) that returns one or more `ApiResource`s, or objects containing `ApiResource`s.

**Expected behavior**

Given an `ApiResource` from an `IResourceStore`, it should be possible to get its associated `ApiScope`s without having to rely on string comparisons.

**Additional context**

This isn't a bug _per se_, more a feature request. I suggest something like `IResourceStore.GetApiScopesByResourceName` (which would only require extending the interface and not require changes to any other existing types), or including the `ApiScope`s themselves in any returned `ApiResource`s (which would perhaps be more straightforward to use, but would require changing existing types outside of the interface).

**Comment by josephdecock** [comment]
We could potentially add a convenience method to filter a collection of scopes to only `ApiScope`s and/or `IdentityResource`s, but I don't think some of the premise of your request is accurate. `ApiScope`s and `IdentityResource`s are just a configuration abstraction added by IdentityServer to describe the underlying values in the scope parameter that you want to support. The scopes in the scope parameter don't have any identity apart from their string values, and they're sent as nothing more than a flat list of space delimited strings; `ApiScope`s and `IdentityResource`s within your configuration should have distinct names. So, I don't think it makes sense to have "multiple scopes having the same name but being part of different resources".

**Comment by Pilchard123** [comment]
I was thinking of the situation in the docs pages for [API Resources](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_resources/) (where there are scopes named "enumerate" and "manage" in each resource) and [Resource Isolation](https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/isolation/) (where there are two scopes named "read" and "write" in each resource).

On re-reading the docs, I think I've misunderstood the situations there - I was thinking that there would be a concept of a scope named "manage" that was part of the resource "invoice" and a *different* scope named "manage" that was part of "customer". But actually - if I've understood it correctly - the scope "manage" in each resource is the *same* scope, it just happens to be relevant for both resources.

I think this can be closed as "didn't read the docs properly", unless I've still got totally got the wrong end of the stick.

**Comment by josephdecock** [comment]
> But actually - if I've understood it correctly - the scope "manage" in each resource is the *same* scope, it just happens to be relevant for both resources.

That's exactly right. Feel free to reach out with more questions and/or suggestions for the docs.
