### ISSUE TITLE
Method 'get_ServerSideSessions' in type 'xyx.ApplicationDBContext' does not have implementation

### ISSUE THREAD

**Issue by ImranJaved** [DuendeSoftware/Support#773]
Migrating Duende IdentityServer 6.0.4 to 6.1

.NET 6

We are trying to migrate from 6.0.4 to 6.1.0 version and we got following issue:
Method 'get_ServerSideSessions' in type 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ApiAuthorizationDbContext`1' from assembly 'Microsoft.AspNetCore.ApiAuthorization.IdentityServer, Version=6.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

We updated related packages to 6.0.20.0 and also implemented IPersistedGrantDbContext for ApplicationDbContext. But now we are getting following error at runtime:

Method 'get_ServerSideSessions' in type 'xyz.ApplicationDbContext' from assembly 'xyz, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Is there any knowledge base to address related issue?

**Comment by josephdecock** [comment]
This error is coming from the nuget package Microsoft.AspNetCore.ApiAuthorization.IdentityServer. That package is maintained by Microsoft, and we generally discourage its use. It is included in some of Microsoft's templates, but those templates make architectural compromises that we don't recommend. We've seen the same error that you're getting from this  package when folks upgraded to .NET 7.

We have a [guide in our docs](https://docs.duendesoftware.com/identityserver/v6/upgrades/spa_to_duende/) on how to migrate away from those templates that describes the architectural issues in more detail as well.

**Comment by ImranJaved** [comment]
Hi @josephdecock,

Thanks a lot for documentation, Is there any sample code for this implementation?

**Comment by josephdecock** [comment]
Our recommendation is to go through the QuickStart tutorial series to see examples and create your own implementation of our recommended architecture in a new solution, and then migrate your code into the new solution.

**Comment by AndersAbel** [comment]
@ImranJaved did you have any success based on the samples Joe referred you to? Do you need any more information here or can we close the issue as resolved?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
