### ISSUE TITLE
Session Management and Back Channel Logout Samples are confusing

### ISSUE THREAD

**Issue by MH61Aus** [DuendeSoftware/Support#778]
I'm trying to get Session Management working with the understanding (as per the docs) that back channel logout is required. 
I've got a series of questions/concerns going through the sample, and haven't yet figured this all out myself, so I'm just going to fire away in no particular order.

1. The sample Identity Server project sets everything up in Startup.cs, and while it is first place most people are going to look, all of the quickstarts wrap up the ConfigureServices code in a HostingExtensions.cs. For the sake of consistency it sould be good if tghese samples were configured in the same way as the quickstarts. I typically see most of these samples as "Quickstart 3 with a feature added", and i feel the code in each sample should reflect that.
2. I set my client app as a razor pages only project. I setup a signout page that had a post method with a logout_token in its model, and set this as the BackChannelLogoutUri, but had no luck. After inspecting the source code, I found that the back channel call uses an API client, so I assume this means it must be a controller endpoint. I fixed this by adding MVC to my project and converting it to a controller - but just noting that there was nothing mentioned in the docs or sample stating that this uri had to be a controller action. 
3. I'm a bit confused about combining backchannel logout with session management. The sample code for the BackChannelLogoutUri validates the backchannel logout token, and then adds the signout request to a list of LogoutSessions. There's a note that this would need to be thread safe as this list is picked up by ValidatePrincipal. The thing i'm confused about - I'm using the EFcore store, so I was thinking that ValidatePrincipal could just hit an endpoint that would just check if the current session exists in the DB, and just revoke it if it doesn't. Such an endpoint doesn't exist - so I'm curious how I'd do this? Or is the intention here that each client is specifically supposed to be tracking the sessions in its own store too? Because if I'm just quesying the Identity store for the session, what's the point of the BackChannelLogoutUri? Because if the session has already been deleted form the DB, and ValidatePrincipal is just going to check the DB, then any token validation in the BackChannelLogoutUri doesn't seem like its achieving anything.

**Comment by josephdecock** [comment]
> I'm trying to get Session Management working with the understanding (as per the docs) that back channel logout is required. 

This isn't quite right. If you use back channel logout, then you need some server side data to record that logout has occurred, and server side sessions are one good way to do that, but not the only way.


> For the sake of consistency it sould be good if tghese samples were configured in the same way as the quickstarts. 

I agree that consistency here would be good. I'm not sure where it lands on our backlog in terms of priority, but thanks for the feedback.

> I found that the back channel call uses an API client, so I assume this means it must be a controller endpoint. I fixed this by adding MVC to my project and converting it to a controller - but just noting that there was nothing mentioned in the docs or sample stating that this uri had to be a controller action. 

There isn't a requirement that the back channel logout uri be handled with an MVC controller. Backchannel logout requests are just http requests from the Identity Provider to the Client application, so this sounds like a routing or model binding problem.

**Comment by josephdecock** [comment]
> Or is the intention here that each client is specifically supposed to be tracking the sessions in its own store too? 

The clients and the identity provider are typically decoupled as independent applications that don't directly share state and have their own distinct sessions.

For each client, you can decide if you want to store the session information entirely in a cookie or on the server side. Cookie based sessions are built in to asp.net, and are the easiest to implement, but you can only interact with the session data when an http request sends you the cookie. Out of band management of the sessions, such as in response to a back channel logout request won't have access to the session data unless you use a server side session in the client. Another advantage of using server side sessions is that the session data doesn't need to round trip through the browser in a cookie, which reduces the size of the http headers, which can save on bandwidth and solve problems where a large session is too big to be serialized into a cookie (most browsers have cookie size limits). The downside is that server side sessions aren't built in to asp.net and require some sort of data store, so they require more complex implementation. 

Separately from the client applications, you also have the choice at the identity provider to use server side sessions. Server side sessions at identity server can limit cookie size in the same way as at the clients. 

Combining a server side session at identity server with server side sessions at the client applications allows you to do lots of interesting things, such as inactivity timeouts across applications, or centralized session management.

**Comment by josephdecock** [comment]
For more details, see the chapter on server side sessions in our docs, starting here: https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/

**Comment by MH61Aus** [comment]
Thanks for the responses. I have read the chapter you linked - multiple times in fact which is why I came asking questions as I felt the docs and samples still leave a lot of grey area.

> This isn't quite right. If you use back channel logout, then you need some server side data to record that logout has occurred, and server side sessions are one good way to do that, but not the only way.

My question was the other way around - you appear to be answering that back channel logout is possible without server side sessions. I had stated that my understanding was that to implement server side sessions you must also implement back channel logout. Regardless, I'm keen to have both.

> There isn't a requirement that the back channel logout uri be handled with an MVC controller. Backchannel logout requests are just http requests from the Identity Provider to the Client application, so this sounds like a routing or model binding problem.

I will investigate this further and post a solution once I find it for anyone else that needs it. However short term I've just switched signout to a controller action.

> The clients and the identity provider are typically decoupled as independent applications that don't directly share state and have their own distinct sessions.
>For each client, you can decide if you want to store the session information entirely in a cookie or on the server side. Cookie based sessions are built in to asp.net, and are the easiest to implement, but you can only interact with the session data when an http request sends you the cookie. Out of band management of the sessions, such as in response to a back channel logout request won't have access to the session data unless you use a server side session in the client. Another advantage of using server side sessions is that the session data doesn't need to round trip through the browser in a cookie, which reduces the size of the http headers, which can save on bandwidth and solve problems where a large session is too big to be serialized into a cookie (most browsers have cookie size limits). The downside is that server side sessions aren't built in to asp.net and require some sort of data store, so they require more complex implementation.
>Separately from the client applications, you also have the choice at the identity provider to use server side sessions. Server side sessions at identity server can limit cookie size in the same way as at the clients.
>Combining a server side session at identity server with server side sessions at the client applications allows you to do lots of interesting things, such as inactivity timeouts across applications, or centralized session management.

I'm still a little confused about part of this response. You talk about choosing whether to do server side sessions in each client, however the docs and samples present server sidce sessions as a single configuration for the entire identity server:
`    services.AddIdentityServer()
        .AddServerSideSessions();`
        
The demo client doesn't have anything in its setup to say that it is opting-in to server side sessions:
```            
services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = "oidc";
            })
                .AddCookie(options =>
                {
                    options.EventsType = typeof(CookieEventHandler);
                })
                .AddOpenIdConnect("oidc", options =>
                {
                    options.Authority = "https://localhost:5001";
                    options.RequireHttpsMetadata = false;
                    options.ClientId = "mvc.backchannel.sample";
                    options.ClientSecret = "secret";

                    options.ResponseType = "code";
                    
                    options.Scope.Clear();
                    options.Scope.Add("openid");
                    options.Scope.Add("profile");
                    options.Scope.Add("scope1");
                    options.Scope.Add("offline_access");

                    // not mapped by default
                    options.ClaimActions.MapJsonKey("website", "website");

                    // keeps id_token smaller
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.SaveTokens = true;

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                });
        }
```

Either way, given that: I'm optimn in to Server Side Sessions, Back Channel Logout, and the EF Core database (Sql Server), I should have a session ID stored in the cookie, and the Identity DB will be able to tell me all the active sessions. 

so based off what you've said, I still would expect that I could have some sort of code like this in the CookieEventHandler of the client:

```
        public override async Task ValidatePrincipal(CookieValidatePrincipalContext context)
        {
            if (context.Principal.Identity.IsAuthenticated)
            {
                var sub = context.Principal.FindFirst("sub")?.Value;
                var sid = context.Principal.FindFirst("sid")?.Value;

                //find token in Identity server db
                if (!IdentityDBService.FindSession(sub,sid))
                {
                    //If session was not found then their session must
                    //have terminated, so log them out
                    context.RejectPrincipal();
                    await context.HttpContext.SignOutAsync();
                }

                //OnSigningOut event is using DuendeAccessTokenManagement to revoke refresh tokens
            }
        }
```

In this case I have not implemented IdentityDBService as I'm still unsure if it is ok for the client to be hitting such a service, or if it is expected that every client would be managing its own sessions within its own DB (but this seems counter intuitive to the whole server side sessions feature).

**Comment by josephdecock** [comment]
> Thanks for the responses. I have read the chapter you linked - multiple times in fact which is why I came asking questions as I felt the docs and samples still leave a lot of grey area.

I really appreciate you taking the time to read our docs, ask questions and give feedback. Based on this conversation, I already have ideas of how I want to improve the docs, so thank you very much!

> My question was the other way around - you appear to be answering that back channel logout is possible without server side sessions. I had stated that my understanding was that to implement server side sessions you must also implement back channel logout. Regardless, I'm keen to have both.

Sure, I just mean that server side sessions don't _require_ back channel logout. The two features work well together, and you want them both anyway, so I won't belabor the point.

> I'm still a little confused about part of this response. You talk about choosing whether to do server side sessions in each client, however the docs and samples present server sidce sessions as a single configuration for the entire identity server

The choice of whether to use server side sessions at the clients is made within each client application, not within the client configuration of IdentityServer. If your client applications are ASP.NET applications, then they're using its cookie authentication handler to store their authentication tickets - session data that is specific to each client application. The authentication ticket includes an identity made up of claims (which each client application independently can customize through claims transformation, etc) and metadata, such as when the user logged in, and their tokens (which are also specific to each application). Some of this data will be similar if a user uses single sign in to go to another client application, but fundamentally each application is managing its own session state.

That session state could be stored entirely within the cookie, which is the default, or you could implement the `ITicketStore` to store the session data on the server side (in redis, etc). Microsoft has an example that stores the data in memory (obviously not suitable for production) [here](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Security/Authentication/Cookies/samples/CookieSessionSample/MemoryCacheTicketStore.cs). But each application has its own authentication ticket, and its own ticket store.

Similarly, your IdentityServer implementation is a .NET application using the cookie handler to track its own session. The Server-Side Session feature in IdentityServer is basically an implementation of the `ITicketStore` _for use within IdentityServer itself_,  along with integration and services within IdentityServer that make use of the tickets. This is an implementation of the `ITicketStore` just IdentityServer. Client applications that want an `ITicketStore` have to build that themselves (or you might have clients built with any other technology stack, and the implementation details of those client's sessions will vary).  

> Either way, given that: I'm optimn in to Server Side Sessions, Back Channel Logout, and the EF Core database (Sql Server), I should have a session ID stored in the cookie, and the Identity DB will be able to tell me all the active sessions.

IdentityServer's server side sessions are not designed with the intent that they'd be consumed outside of IdentityServer itself. Our design of server side sessions has to account for the possibility that some client applications might be 3rd party/not trusted to access the session store. We think of the session store as an implementation detail of IdentityServer, and don't try to expose that data to client applications.

> so based off what you've said, I still would expect that I could have some sort of code like this in the CookieEventHandler of the client:
> [omitted for brevity] 

> In this case I have not implemented IdentityDBService as I'm still unsure if it is ok for the client to be hitting such a service, or if it is expected that every client would be managing its own sessions within its own DB (but this seems counter intuitive to the whole server side sessions feature).

Yes, every client is managing its own session data. Server side sessions don't mean centralized control of all session data, it just means that the session data _of identity server itself_ is stored in a database. The other applications remain de-coupled from IdentityServer and its data stores. This allows the client applications to be deployed independently, allows server side sessions to be used with external clients, and keeps your identity data stores isolated.

**Comment by MH61Aus** [comment]
Thanks for the respones - I'll keep poking around at it and let you know what other questions I have, but it certianly seems like there's more involved than I anticipated.

On another note, you mentioned that it was ok for the BackChannelLogoutUri to be a razor page. I did get this working, however the complication in getting this working over the MVC route is that Posts to Razor Pages require an Antiforgery Token, and your backchannel post does not send one.  I'm can bnow get the backchannel request to hit the post, but it means disabling anitiforgery on the entire signout page, and allowing annonymous. See code below - but I'm wondering if these compromises means its more safe to just use the controller endpoint instead.


```
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    [AllowAnonymous]
    [IgnoreAntiforgeryToken]
    public class SignoutModel : PageModel
    {
        private readonly ILogger<SignoutModel> _logger;

        public SignoutModel(ILogger<SignoutModel> logger)
        {
            _logger = logger;
        }

        [BindProperty]
        public string logout_token { get; set; }

        public IActionResult OnGet()
        {
            return SignOut(CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            _logger.LogInformation(logout_token);

            //Implement back channel logout code here

            return RedirectToPage("./Index");
        }
    }
}
```

**Comment by josephdecock** [comment]
Okay, sounds good. The anti-forgery token is there to prevent a cross site request forgery. For example, a bank could have a form that transfers funds, and a malicious site could post to that form. The browser will implicitly include your auth cookie, and thus you have cross site request forgery. The anti-forgery token proves that the request came from your own site and not some third party.

Backchannel logout is a rare case where we actually want a cross site request to be allowed, because the client application and oidc provider aren't constrained to be on the same site.

The implication of this is that the client application needs some other method of establishing that it should trust the request for logout. The backchannel logout spec takes that into account by requiring that the client application validate the logout token that it receives at the backchannel logout uri. The details are in the spec [here](https://openid.net/specs/openid-connect-backchannel-1_0.html#Validation), but the gist of it is that your application is receiving a cryptographically signed message saying that it should end its session, so if that signature is valid, and the content of the message is sensible, then it is safe to trust the request.

**Comment by MH61Aus** [comment]
This makes sense. I think this is worth pointing out in the docs, as I'm sure others will run into the same issue.

**Comment by josephdecock** [comment]
I've created an item on our doc backlog to make sure we remember to use this conversation to improve the docs - thanks again for a good conversation!
