### ISSUE TITLE
How to use step-up authentication with Identity Server 4 and Okta.

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#780]
I'm using Identity Server 4 and .NET 6.

I'd like to use step-up authentication using Okta:
https://developer.okta.com/docs/guides/step-up-authentication/main/

Are there any tutorials on how to implement step up authentication using Identity Server?

If not, could someone explain how I can get my app to call IDS, which should then redirect my browser to Okta where I would be prompted for 2FA?

**Comment by josephdecock** [comment]
We have a sample of step up here: https://docs.duendesoftware.com/identityserver/v6/samples/ui/#step-up.

**Comment by DavidKlempfner** [comment]
@josephdecock I had a look at the example, unfortunately my version of the API and Client apps are both using .NET Framework 4.8. Are there any examples for a client/api on .NET Framework and Identity Server 4 on .NET 6?

**Comment by josephdecock** [comment]
We do have an example of how to do a basic OIDC handshake with a .NET framework client application and validate JWTs from a .NET framework API [here](https://docs.duendesoftware.com/identityserver/v6/samples/clients/#net-48-clients). The sample doesn't include step up. You'll have to add the necessary protocol parameters for step up yourself, probably in the `OpenIdConnectAuthenticationNotifications.RedirectToIdentityProvider` event.
