### ISSUE TITLE
CreateUser is not defined project does not build

### ISSUE THREAD

**Issue by kazeens** [DuendeSoftware/Support#784]
https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI/blob/4f633f662f6262f28b4921fcb9291bda7295a93b/Pages/Account/Create/Index.cshtml.cs#L79

https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI/assets/31125887/6b7aeef2-05eb-4d8d-b34f-999ba699fb59

cc @damianh @brockallen

**Comment by brockallen** [comment]
Hi @kazeens. The code in that quickstart repo is just loose static files that you might load into an existing project that uses IdentityServer. The way we recommend using them is according to our quickstart tutorials here:

https://docs.duendesoftware.com/identityserver/v6/quickstarts/

Perhaps try those and see if you have better results?

**Comment by AndersAbel** [comment]
Any updates on this @kazeens?

**Comment by kazeens** [comment]
Everything is fine.
Just substituted for my personal solution
