### ISSUE TITLE
Receiving 400 when refreshing token

### ISSUE THREAD

**Issue by ExplPatrick** [DuendeSoftware/Support#790]
**Which version of Duende IdentityServer are you using?**
5.2.4

**Which version of .NET are you using?**
3.1

**Describe the bug**

We have a problem refreshing the token. It happens that a request to refresh the token gets a 400 back from the IdentityServer, although the parameters we send along have not changed. This causes the user to be kicked out of the application. Sometimes not at all and sometimes after a few minutes. The route that sporadically sends a 400 back to the frontend is the /endsession route.

**Comment by josephdecock** [comment]
IdentityServer should be logging details about why a request failed whenever you get an error. We're logging using Microsoft's ILogger abstractions, so any log provider that works with that should get you the logs you need. Our samples often use Serilog as the log provider, but that is not required - we just like that log provider. An example of the necessary serilog configuration is [here](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/Basics/IdentityServer/src/Program.cs#L18-L33).

In the case of refresh tokens failing, especially if you are sending the same parameters and getting a failure the second and subsequent times, I suspect your refresh tokens are configured to be one time use only. We discuss the rotation semantics in our docs [here](https://docs.duendesoftware.com/identityserver/v6/tokens/refresh/#rotation).

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
