### ISSUE TITLE
Why doe the OIDC redriectURI get set to the ReturnURL

### ISSUE THREAD

**Issue by sipsorcery** [DuendeSoftware/Support#791]
**Which version of Duende BFF are you using?**
2.1.0

**Which version of .NET are you using?**
7

**Question**

Thanks for the BFF server, it's a great help. Hopefully a quick question to help understand the login mechanism we are currently encountering some issues on with a React client.

Why does the BFF login use the ReturnURL as the OIDC redirectURI at this point https://github.com/DuendeSoftware/BFF/blob/0b88db58218906ea97e5e117ea39354c827fbdae/src/Duende.Bff/EndpointServices/Login/DefaultLoginService.cs#L78?

Why would an SPA app ever what the OIDC redirect to go anywhere other than the standard /signin-oidc on the BFF server?

**Comment by josephdecock** [comment]
Did you mean to close this issue? Of anything actually needed here?

**Comment by sipsorcery** [comment]
Yes, I meant to close the issue.

Turns out the RedirectURL was a red herring, There was a nodejs proxy running in between React and the BFF server and it causes ASP.NET to set the wrong OIDC redirectURI.
