### ISSUE TITLE
Is it possible to use internally-issued IdentityServer JWTs rather than having to go through the token-request flow?

### ISSUE THREAD

**Issue by Pilchard123** [DuendeSoftware/Support#792]
This is related to Duende.AccessTokenManagement and not IdentityServer or BFF directly, though it does refer to features in IdentityServer.

Is there any way to customise the way that tokens are renewed, other than by registering a different `HttpClient`? I'm wanting to use this to manage tokens to access an API protected by an instance of IdentityServer within the IdentityServer application itself. Given that IdentityServer can [self-issue tokens](https://docs.duendesoftware.com/identityserver/v6/tokens/internal/), it would be useful to be able to use that functionality to get tokens rather than having the application make requests to itself.

I suppose I could do some hackery with a Frankesteined `HttpClient`, but that seems like a suboptimal solution.

I don't know what a potential API for modifying the behaviour could look like offhand - I'd have to study the code a bit more to be able to give a half-decent opinion on that.

**Comment by Pilchard123** [comment]
Now I think about it, the same question applies to IdentityModel.AspNetCore.

**Comment by josephdecock** [comment]
Duende.AccessTokenManagement is not really designed to be used in this way. You might be able to replace the [IUserTokenManagementService](https://github.com/DuendeSoftware/Duende.AccessTokenManagement/blob/main/src/Duende.AccessTokenManagement.OpenIdConnect/Interfaces/IUserTokenManagementService.cs) with your own implementation that would use the self-issued tokens, but there's not a lot of benefit to using the AccessTokenManagement library if you're ripping out so much of what it does.

**Comment by Pilchard123** [comment]
No, that's fair enough. I only want client credentials tokens anyway, so it's not too much extra stuff to write - I just thought I'd use something that was already solid if it existed.
