### ISSUE TITLE
How to get extraTokenParams in GetProfileDataAsync method ?

### ISSUE THREAD

**Issue by vrrenga123** [DuendeSoftware/Support#793]
**Identity Server 6.0**

**.NET Core 6**

 We have multiple user role support in SSO, where user can belong to more than one type and each type he may have with different roles, client application uses extraTokenParams to pass the type of user to server. Based on this information a role claim need to be added in IProfileService. I can get the extraTokenParams values in GetProfileDataAsync method. But this method is called twice with a different context.

1. For the access token Context.Caller = ClaimsProviderAccessToken.
2. For the identity token Context.Caller = UserInfoEndpoint.

In first time call (when Context.Caller = ClaimsProviderAccessToken) I can get the extraTokenParams value in below code

context.ValidatedRequest.Raw.Get("userType") 

But in second time I couldn't get the value (when Context.Caller = UserInfoEndpoint), context.ValidatedRequest is always null.

please suggest how I can do that.

**Comment by josephdecock** [comment]
The `ValidatedRequest` is set when the profile service is invoked to produce tokens, but it is not set when you make a userinfo call. The `ValidatedRequest` represents the protocol parameters in the incoming http request for tokens that identity server has validated, which only makes sense when you're requesting tokens. When you're making a userinfo call, there's no relevant request parameters to validate (and you probably aren't sending your role as an extra parameter there, I would guess).

One option to solve this would be to move the role claims into the id token. You could set `AlwaysIncludeUserClaimsInIdToken` on the client configuration, and that will tell IdentityServer to invoke the profile service when it creates your Id Token (so you'll see another call to the profile service with Caller = ClaimsProviderIdToken). The downside to this is that it increases the size of the id tokens, which most clients carry around until logout time to send as the id token hint to the logout endpoint. If you have a lot of user info claims, that might be bad, but you could check the Caller and only include the role in the id token, not all the additional profile data - keep that in the userinfo call.

An alternative that will be available in the upcoming IdentityServer 7 (no official release date announced yet, but we hope to have previews come out around the same time as .NET 8, in November), is to persist the roles as a claim in the user's session, and store the session server side. We have a change coming in IdentityServer 7 that will make the profile service use the server side session for userinfo calls, if server side sessions are enabled. See [here](https://github.com/DuendeSoftware/IdentityServer/issues/1254).

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
