### ISSUE TITLE
Server-Side-Sessions for ExternalCookieAuthenticationScheme

### ISSUE THREAD

**Issue by Tobias-08** [DuendeSoftware/Support#796]
**Which version of Duende IdentityServer are you using?**

6.3.3

**Which version of .NET are you using?**

.NET 6

**Question**

Is it possible to configure the Server-Side-Sessions-feature not only for the idsrv-identity but also for the (temporal) external identity (`ExternalCookieAuthenticationScheme`)?

My use case: We are getting many (needed) claims from an external identity provider so that the external cookies get too large (for the one hop to the `/ExternalLogin/Callback`). Using the Server-Side-Sessions could solve this.

If it's not possible: Would be configuring a custom `ITicketStore` for the external cookie scheme the right path? Or do you have other ideas?

Thanks!

**Comment by josephdecock** [comment]
I would implement an `ITicketStore` for the external cookie scheme.

I don't think there is a way to make server side sessions do this, but my advice would be to keep the real sessions separate from the temporary sessions anyway. The idea of having two different cookies is that you never want to mistakenly use the identity given to you by a third party, you always want to go through a process of mapping that identity onto your own representation, possibly provisioning a user you haven't seen before or enforcing authorization or other business logic. If you store all the sessions together, that seems hard to do. There's also a lot of extra logic and code paths that we are doing on the server side sessions that you wouldn't want to do for the temporary sessions.

**Comment by Tobias-08** [comment]
@josephdecock Thanks! `ITicketStore` works fine for the external cookie scheme.
