### ISSUE TITLE
Access ExpiresInTime from BFF Controller Endpoint

### ISSUE THREAD

**Issue by joelcoxokc** [DuendeSoftware/Support#798]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
net7

Hello, I am trying to implement an endpoint on the BFF Api that handles some other things based on their session expires_in_time. 

Is there a way for me to gain access to the session_expires_in cookie claims from a controller endpoint on BFF?

**Comment by brockallen** [comment]
Have a look at the `GetUserAccessTokenAsync` extension method on the `HttpContext`. It returns a `UserToken` with the expiration.

**Comment by joelcoxokc** [comment]
Amazing, Thank you!

**Comment by joelcoxokc** [comment]
Hello @brockallen 

The toke returns the Expiration time. 
Which I don't believe is the same essions_expires_in time for the BFF session. How can I gain access to the bff expires in value
