### ISSUE TITLE
BFF YARP not working

### ISSUE THREAD

**Issue by IliyanAng** [DuendeSoftware/Support#8]
version 1.1.3 of Duende and Duende.BFF.Yarp

version .NET 6 

Following the tutorial to add Yarp to BFF, after installing the Yarp  BFF package I'm unable to load the .AddBffExtensions() extension method

Here is a screenshot: 

![image](https://user-images.githubusercontent.com/51085480/159731945-bc2fb83c-c6c2-4644-81f4-50a0b5549555.png)

I've also tried to access the namespaces directly which does not seem to exists. 
Not sure why that is. 

Any help on the matter will be greatly appreciated!

**Comment by leastprivilege** [comment]
`AddBffExtensions` was added in 1.2.0 - which is currently in preview

https://www.nuget.org/packages/Duende.BFF.Yarp/1.2.0-preview.1

sorry for the confusion

**Comment by IliyanAng** [comment]
Thank you @leastprivilege !
I'll go with the automatic http forwarding _(for now)_

Preesh
