### ISSUE TITLE
No FK between ApiResourceScope and ApiScope

### ISSUE THREAD

**Issue by No1e** [DuendeSoftware/Support#80]
**Which version of Duende IdentityServer are you using?**
6.1

**Which version of .NET are you using?**
6
**Describe the bug**

Dear Duende Team,

why there is no FK in ApiResourceScopes on ApiScopes.Name or ApiScopes.Id?

Best regards,
Novak

**Comment by brockallen** [comment]
No, we deliberately don't do that since often only some of those tables are used and others come from hard-coded values in the system.
