### ISSUE TITLE
Support for read replication in IdentityServer operational stores

### ISSUE THREAD

**Issue by acasciani** [DuendeSoftware/Support#801]
**Which version of Duende IdentityServer are you using?**
6.3.2

**Which version of .NET are you using?**
.NET Core 7

**Describe the bug**

N/A

**Additional context**

We're using AWS Aurora for our database and this service provides read/write database nodes and read only database nodes. The two are distinguished by different servers which results in different connection strings. Aurora indicates that replication lag is present, but usually no more than 100 ms. We'd like to make use of the read replica for read only operations in IdentityServer. We are also using the Entity Framework IdentityServer implementation. 

We have updated the Configuration context to use the read only connection string completely, since all those operations in the Configuration store are reads. We'd like to also update the Operational stores. We currently use authorization codes and server side session functionality and are aware of the write-read-delete requests that can happen very quickly. We've assumed the risk of stale or non-existent data and feel this is mitigated given our database provider's low replication lag. There currently is no way to use the read only connection string with the Operational store for the read requests as part of the write-read-delete. We've duplicated the Duende EF store implementation and added a second DB Context which we pass in the read only connection string to get around this limitation.

It would be very helpful if something like this was included in Duende's IdentityServer EF store implementation where we could specify a read only connection string for the operational store, in addition to the write connection string. I understand not everyone would be able to use this given different replication lags, so maybe if this connection string is not provided, then the store defaults to the writer connection string.

**Comment by AndersAbel** [comment]
We have reviewed this and looked at what possibilities the current implementation offers as well as what possibilities we have to add more flexibility and how that would affect readability/maintainability of the current code. It is already possible to move the reads to a different DbContext through a couple of options:
* You can implement your own custom IPersistedGrantStore or even each of the individual stores built on top of that (IAuthorizationCodeStore etc.).
* It is also possible to derive from our EF implementation and override/replace the implementation of e.g. `GetAsync`.

Altering the EF code further would make it easier, but at the cost of adding more complexity to the code.
For now, we have decided that we will not add any further support for separate read replicas in our implementation. We think that the extension possibilities already present offers full flexibility in how the stores are implemented, including possibilities to separate read and write operations.
