### ISSUE TITLE
Automatic Login After Registration from SPA

### ISSUE THREAD

**Issue by vibranttheme** [DuendeSoftware/Support#803]
**Which version of Duende IdentityServer are you using?**
We are using IdentityServer4
**Which version of .NET are you using?**
.NET6

**Automatic Login After Registration from SPA**

We are currently using IdentityServer4 with Angular client applications, leveraging Angular-Oauth2-OIDC for our authentication needs. We have encountered an issue related to automatic login after user registration from the Angular client.

Here's a breakdown of the problem and the steps we've taken so far:

1) We have a registration form in our Angular client application where users can register by providing their details.

2) Upon submitting the registration form, we make an HTTP POST request to the API endpoint in our IdentityServer4 application to register the user.

3) On the IdentityServer4 side, we handle the registration request, validate the user data, create the user account in the user store, and generate the necessary user claims.

4) The issue lies in automatically signing in the newly registered user and returning to the Angular client application with an authentication cookie. Currently, the user is not automatically signed in after registration.

We would greatly appreciate your guidance on how to achieve automatic login for the newly registered user using IdentityServer4 and Angular-Oauth2-OIDC. We would like the user to be seamlessly logged in after completing the registration process, and return to the Angular client application with the appropriate authentication cookie.

If you could provide us with a step-by-step guide or any code examples on how to implement this functionality, it would be immensely helpful. Additionally, any best practices or security considerations related to this process would be highly appreciated.

Thank you for your support and assistance. Please let us know if you need any further information from our end to address this issue.

Looking forward to your prompt response.

Best regards,

Ajay Mathasuriya
Project Manager
[Evision IT Solutions]

**Comment by josephdecock** [comment]
IdentityServer4 is [no longer supported](https://github.com/IdentityServer/IdentityServer4/#important-update). 

We'd love to work with you and help you solve your identity related problems, but this issue tracker is for licensed users of Duende.IdentityServer. Please [get in touch ](https://duendesoftware.com/products/identityserver) to get a license.

For now, I'll close this issue. Feel free to reopen when you are licensed.
