### ISSUE TITLE
What should I set for OpenIdConnectOptions.SignOutScheme?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#807]
I'm using .NET 6 and Identity Server 4.

What should I set for `OpenIdConnectOptions.SignOutScheme`?

This is what I have in `Startup.ConfigureServices()`:

```
                .AddOpenIdConnect("oidc", "OpenIdConnect", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme; // "idsrv.external"
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme; // "idsrv"
                    options.Authority = "https://saas.oktapreview.com";
                    options.ClientId = "someId";
                    options.ClientSecret = "someSecret";
                    options.ResponseType = "code";
                    options.Events = new MriOpenIdConnectEvents();
               }
```

I've chosen `IdentityServerConstants.SignoutScheme` purely because it has "signout" in the name. But can you use the same value as for `SignInScheme`? How does this value affect OIDC?

**Comment by leastprivilege** [comment]
IdentityServer4 is not supported anymore - especially on NET6. Please update to a supported version.

**Comment by DavidKlempfner** [comment]
> IdentityServer4 is not supported anymore - especially on NET6. Please update to a supported version.

My company is not willing to upgrade, so I'm stuck with 4.

**Comment by leastprivilege** [comment]
OK- sorry to hear that. Then please use one of the community forums like StackOverflow for help.
