### ISSUE TITLE
What is the difference between Identity object in Request/Response and Principal?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#808]
I'm using .NET 6 and Identity Server 4.

What is the difference between these three Identities (this is a class derived from OpenIdConnectEvents)?
Why are there claims in the Principal but not in the Request/Response?

```
        private Task OnTicketReceivedImpl(TicketReceivedContext context)
        {
            var requestIdentity = context.Request.HttpContext.User.Identity;
            var responseIdentity = context.Response.HttpContext.User.Identity;
            var principalIdentity = context.Principal?.Identity;
            ...
        }
```

![image](https://github.com/DuendeSoftware/Support/assets/13111539/797daefb-1d88-4d6b-b1ea-cc5a2379ffc1)

**Comment by josephdecock** [comment]
Again, closing for lack of license.
