### ISSUE TITLE
New refresh token is created with the same CreationTime And Expiration as the one that was consumed

### ISSUE THREAD

**Issue by fivigh** [DuendeSoftware/Support#81]
**Which version of Duende IdentityServer are you using?**
Old IdentityServer4, but after checking the code of the new Duende IdentityServer I noticed that the issue is still there.

**Which version of .NET are you using?**
.Net Core 3.1

**Describe the bug**

When setting the refresh token to one-time use only, when a new refresh token needs to be created because the old one was consumed, the newly created refresh token has the same CreationTime and Expiration that the one that was just consumed.

**To Reproduce**

Create a client and configure the refresh token usage to one time only.
Log in using this client.
Wait for the access token to expire.
Let the client request a new access token using the refresh token.
After using the refresh token, check in the database that a new refresh token was created.

**Expected behavior**

When creating a new refresh token after the actual one was consumed, the newly created one should have the correct CreationTime and Expiration.

**Log output/exception with stacktrace**

None

**Additional context**

In order to fix this issue, we created a custom refresh token service that inherits from `DefaultRefreshTokenService`.
In the custom refresh token service, we have overridden the `UpdateRefreshTokenAsync` method. The new implementation looks like the following:

`{
            Logger.LogDebug("Updating refresh token");

            bool needsCreate = false;
            bool needsUpdate = false;

            if (client.RefreshTokenUsage == TokenUsage.OneTimeOnly)
            {
                Logger.LogDebug("Token usage is one-time only. Setting current handle as consumed, and generating new handle");

                // flag as consumed
                if (refreshToken.ConsumedTime == null)
                {
                    refreshToken.ConsumedTime = Clock.UtcNow.UtcDateTime;
                    await RefreshTokenStore.UpdateRefreshTokenAsync(handle, refreshToken);
                }

                // create new one
                needsCreate = true;
            }

            if (client.RefreshTokenExpiration == TokenExpiration.Sliding)
            {
                Logger.LogDebug("Refresh token expiration is sliding - extending lifetime");

                // if absolute exp > 0, make sure we don't exceed absolute exp
                // if absolute exp = 0, allow indefinite slide
                var currentLifetime = GetLifetimeInSeconds(refreshToken.CreationTime);
                Logger.LogDebug("Current lifetime: {currentLifetime}", currentLifetime.ToString());

                var newLifetime = currentLifetime + client.SlidingRefreshTokenLifetime;
                Logger.LogDebug("New lifetime: {slidingLifetime}", newLifetime.ToString());

                // zero absolute refresh token lifetime represents unbounded absolute lifetime
                // if absolute lifetime > 0, cap at absolute lifetime
                if (client.AbsoluteRefreshTokenLifetime > 0 && newLifetime > client.AbsoluteRefreshTokenLifetime)
                {
                    newLifetime = client.AbsoluteRefreshTokenLifetime;
                    Logger.LogDebug("New lifetime exceeds absolute lifetime, capping it to {newLifetime}", newLifetime.ToString());
                }

                refreshToken.Lifetime = newLifetime;
                needsUpdate = true;
            }

            if (needsUpdate)
            {
                await RefreshTokenStore.UpdateRefreshTokenAsync(handle, refreshToken);
                Logger.LogDebug("Updated refresh token in store");
            }

            if (needsCreate)
            {
                var newHandle = await CreateRefreshTokenAsync(refreshToken.Subject, refreshToken.AccessToken, client);
                Logger.LogDebug("Created new refresh token");

                return newHandle;
            }

            if (!needsCreate && !needsUpdate)
            {
                Logger.LogDebug("No updates to refresh token done");
            }

            return handle;
        }`

If you accept contributions, I'm more than happy to create a PR.

**Comment by leastprivilege** [comment]
thanks! we will have a look

**Comment by josephdecock** [comment]
@fivigh, I really appreciate you sharing your code. I'm interested to know what your Client config is here - in particular, what are the Client's SlidingRefreshTokenLifetime, AbsoluteRefreshTokenLifetime, and RefreshTokenExpiration? Also, how do you expect the refresh token lifetime to behave? You say that it should be "correct" - but what actually is correct? You seem to be expecting that you'll get a token with a fresh lifetime. I'm not sure that's what actually makes sense though. The lifetime configuration options should apply to an entire "chain" of one time only refresh tokens.

**Comment by fivigh** [comment]
@josephdecock, sure. This is what my client config looks like (the access token lifetime is set to 30 seconds only for testing purposes, it will be increased in production):

![image](https://user-images.githubusercontent.com/106251081/174232955-29de5efc-6cf0-4a1a-93f1-a1e59959a544.png)

I would expect the CreationTime to be the actual creation time of the current refresh token, not the creation time of the first refresh token in the chain. Also, the Expiration should be recalculated for every newly created refresh token, in my case, it needs to be CreationTime + 1 year. Otherwise, after a certain time period (in my case, 1 year), the system will fail to generate a new access token using the current refresh token (even if the user is actively using the client) because the Expiration will be passed by. This will force a logout that shouldn't happen.

**Comment by josephdecock** [comment]
We aren’t recalculating the lifetime with each consumption because lifetimes and one time only usage are configured separately. One time only doesn’t force sliding behavior, but you can still get sliding by setting the sliding expiration.

Note that if there is both an absolute and a sliding expiration value configured, the absolute expiration serves as a cap to the amount of sliding you get. To get sliding tokens that can slide indefinitely, set the absolute refresh expiration to 0, and the sliding expiration to the amount of time you’d like to add to the token when it is used. 

I can see why the creation time not being the time at which the latest refresh token handler was created is a bit surprising, but this is the simplest way to do lifetime bookkeeping.

**Comment by fivigh** [comment]
I see, thanks for the detailed clarification.
