### ISSUE TITLE
IOException: IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden.

### ISSUE THREAD

**Issue by AndersBoegHolm** [DuendeSoftware/Support#811]
Duende.IdentityServer.AspNetIdentity V 6.3.2

.Net 6

When redirecting and requesting the Duende Identity Server we get this return from the exception cast:
IOException: IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.

Im not able to see the details and the problem is only in one og our test environments. Production and Staging environment are working correctly. Configuration in all three environments are the same. 

Any ideas how to get further in debugging this problem?

When the Duende service is called I except to be able to proceed with login. 

Could it be that out test environment is not setup correctly at Duende?
The problem started after updating the licens key.

**Comment by josephdecock** [comment]
Your client application is trying to start an OAuth flow but failing, and its log is redacted by default to hide PII. You can get more details in your log with code like this:
```
if (env.IsDevelopment())
{
     IdentityModelEventSource.ShowPII = true; 
}
```

Usually this kind of issue indicates that your client app isn't using the right url for your identity server as its authority, or that your identity server isn't properly started.

**Comment by AndersBoegHolm** [comment]
We have activated the ShowPII = true;

The information we get back is very unusefull.

**Comment by josephdecock** [comment]
A few more things that you can check:

- Are you able to make http requests to your identity server implementation? The discovery endpoint is a good way to test (the path is /.well-known/openid-configuration). 
- Is the client application able to resolve the identity server's host via dns? 
- Is there a firewall between the client and the identity server?

**Comment by AndersBoegHolm** [comment]
Thanks I will try it on Monday 👍 

I took over the platform for another team without a proper handover, so I'm facing significant challenges with this part of the platform. I'm trying to gain control over the codebase and understand its many intricacies.
There is no firewall between the client and server. It works fine on our other two Azure web apps, which is why I'm puzzled by the error on this test web app.
Could you please explain how I can easily perform these two tests, considering that I'm not very familiar with the code and what has been developed? (And yes, it's my problem and challenge. Any help will be greatly appreciated.)

- Is the client application able to resolve the identity server's host via dns?
- Is there a firewall between the client and the identity server?

**Comment by josephdecock** [comment]
To give you a bit more context, the client application is trying to make an http request to your IdentityServer to get metadata. This process is called discovery, and you can see an example of the discovery document at our public demo of IdentityServer here: https://demo.duendesoftware.com/.well-known/openid-configuration. The discovery document contains information like the urls to the various endpoints that the server supports, information about the cryptographic algorithms the server supports, etc. 

The error that you're getting means that the http request for the discovery document failed. This indicates that either:
1. The client is misconfigured and tried to get the discovery document from the wrong url,
2. IdentityServer isn't actually running, or
3. Some sort of network problem prevents the client from making http requests to IdentityServer.

So, I would diagnose this by verifying that the client app's configuration is correct (check for typos in the url to IdentityServer, especially http vs https), checking that IdentityServer is actually running and responding to requests for the discovery document, and finally that there isn't something specific to the client application's networking that is preventing it from making the request.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
