### ISSUE TITLE
Mvc IntegrationTests fails with statuscode 401 when .AsBffApiEndpoint() extensionmethod is enabled

### ISSUE THREAD

**Issue by marcelbeeker** [DuendeSoftware/Support#814]
**Which version of Duende BFF are you using?**
Version 2.1.1

**Which version of .NET are you using?**
.NET7

**Describe the bug**
Integration Tests fail with HttpStatusCode 401 when  these lines is used
endpoints.MapControllers()
                .RequireAuthorization();
                .AsBffApiEndpoint();

Please, can you give me an example how to setup a Mvc.AspNetCore.Mvc.Testing Integration Test?

My WebApplication for testing looks like this
services.Configure<TestAuthHandlerOptions>(options => options.DefaultUser = DefaultUser);

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = "Test";
                options.DefaultChallengeScheme = "Test";
            })
            .AddScheme<TestAuthHandlerOptions, TestAuthHandler>(TestAuthHandler.AuthenticationScheme, options => { });

My TestAuthHandler looks like this
 public class TestAuthHandlerOptions : AuthenticationSchemeOptions
    {
        public SecondMobileAppUser DefaultUser { get; set; } = new SecondMobileAppUser("testbla@hotmail.com", "marcel");
    }

    public class TestAuthHandler : AuthenticationHandler<TestAuthHandlerOptions>
    {
        public const string UserName = "UserName";

        public const string AuthenticationScheme = "Test";
        private readonly SecondMobileAppUser _defaultUser;

        public TestAuthHandler(
            IOptionsMonitor<TestAuthHandlerOptions> options,
            ILoggerFactory logger,
            UrlEncoder encoder,
            ISystemClock clock) : base(options, logger, encoder, clock)
        {
            _defaultUser = options.CurrentValue.DefaultUser;
        }

        protected override Task<AuthenticateResult> HandleAuthenticateAsync()
        {
            var claims = new List<Claim> { new Claim(ClaimTypes.Name, "Test user") };

            // Extract User ID from the request headers if it exists,
            // otherwise use the default User ID from the options.
            if (Context.Request.Headers.TryGetValue(UserName, out var userName))
            {
                //claims.Add(new Claim(ClaimTypes.NameIdentifier, userName[0]));
            }
            else
            {
                claims.Add(new Claim(ClaimTypes.NameIdentifier, _defaultUser.UserName));
            }

            // TODO: Add as many claims as you need here

            var identity = new ClaimsIdentity(claims, AuthenticationScheme);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, AuthenticationScheme);

            var result = AuthenticateResult.Success(ticket);

            return Task.FromResult(result);
        }

I create a httpclient like this:
 _client = fixture.CreateClient(new WebApplicationFactoryClientOptions
            {
                AllowAutoRedirect = false
            });
            _client.BaseAddress = new Uri("https://localhost/");
            // Use our mock Auth scheme 
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Test");

The test is implemented as described here:
//_client.DefaultRequestHeaders.Add(TestAuthHandler.UserName, "bla@hotmail.com");

            var insertResponse = await _client.PostAsync("user1", content);
            try
            {
                insertResponse.EnsureSuccessStatusCode();
            }
            catch (Exception ex)
            {
                throw;
            }

Unfortunately I can't find out what I'm doing wrong

**Expected behavior**
A working example

**Comment by AndersAbel** [comment]
When calling `.AsBffApiEndpoint()` on an API, the BFFs CSRF protection is added to the endpoint. It requires all requests to have a custom header `x-csrf: 1`, see https://docs.duendesoftware.com/identityserver/v6/bff/apis/local/#anti-forgery-header.

If that header is not present, the BFF framework will return a 401, which is totally independent to the user authentication. In the sample code you shared, I do not see that you add that header. Could it be that the header is what is missing?

**Comment by marcelbeeker** [comment]
Adding this line _client.DefaultRequestHeaders.Add("X-CSRF", "1"); Solved the problem for me. Thanks for pointing me in the right direction
