### ISSUE TITLE
No user present in authorize request

### ISSUE THREAD

**Issue by ExplPatrick** [DuendeSoftware/Support#816]
**Which version of Duende IdentityServer are you using?**
5.2.4
**Which version of .NET are you using?**
3.1
**Describe the bug**
Wir haben einige Logins bei denen in den Logs die Meldung "no user present in authorize request" gelogged wird. Woher kommt die und womit hängt die zusammen?

**Comment by AndersAbel** [comment]
I'm running this through Google translate:

> We have some logins where the message "no user present in authorize request" is logged in the logs. Where does it come from and what is it related to?

It looks like a reasonable translation, so I'll answer that question. If something was lost in translation, please comment!

This is a debug level log, it is only informational and does not indicate that there is an error.

The log message `No user present in authorize request` indicates that there is no IdentityServer user session when the request is made to the authorize endpoint. This is expected to happen and the result is that the user is redirected to the login page to sign on. On subsequent requests to the authorize endpoint, for example if single sign on is used across applications, the next application would instead log the message `User in authorize request: xyz123`.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
