### ISSUE TITLE
How to integrate MAUI client with BFF security framework?

### ISSUE THREAD

**Issue by kovvasill** [DuendeSoftware/Support#819]
Here we have different samples clients using BFF security framework:
https://docs.duendesoftware.com/identityserver/v6/samples/bff/

What we are missing it's sample for MAUI.

Could you give as sample for MAUI as well? Do we have any constraints for implementing it or know issues?

**Comment by josephdecock** [comment]
I'm not sure that using the BFF with a MAUI application makes sense. With the BFF, the client application authenticates to the BFF by sending an auth cookie. Native apps typically obtain tokens directly, and store them using some sort of secure storage that is specific to the platform.

We do have a sample MAUI application [here ](https://docs.duendesoftware.com/identityserver/v6/samples/clients/#net-maui-client) though.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
