### ISSUE TITLE
Claims with ClaimValueTypes.Double are not serialized as Number types

### ISSUE THREAD

**Issue by rubo** [DuendeSoftware/Support#82]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
Claims with `ClaimValueTypes.Double` serialized to JSON as `String` instead of `Number` when being added to `context` in the `IProfileService.GetProfileDataAsync(ProfileDataRequestContext context)` method.

**To Reproduce**
Add a `Claim` with value type of `ClaimValueTypes.Double` using `context.AddRequestedClaims()` method in the `IProfileService.GetProfileDataAsync(ProfileDataRequestContext context)` implementation.

**Expected behavior**
The claim value in the JSON retrieved from the `userinfo` endpoint must be of type `Number` instead of `String`.

I presume the problem is in [ClaimsExtensions.cs](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/ClaimsExtensions.cs) and/or [TokenExtensions.cs](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/TokenExtensions.cs).

**Comment by leastprivilege** [comment]
Thanks for reporting. We will look into it.

**Comment by leastprivilege** [comment]
You can use `ClaimValueTypes.Integer64` instead. Can you give that a try?

**Comment by leastprivilege** [comment]
Actually - the real question would be - is `long.Parse()` good enough for you?

I added explicit double support in this PR
https://github.com/DuendeSoftware/IdentityServer/pull/911

**Comment by rubo** [comment]
@leastprivilege `long.Parse()` (`ClaimValueTypes.Integer64`) is not enough as I need to parse floating point numbers.

Regarding the PR: Why no changes in [ClaimsExtensions.cs](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Extensions/ClaimsExtensions.cs)? I'm not sure where those extension methods are actually used but wouldn't it be consistent to have the same claim parsing logic everywhere?

**Comment by leastprivilege** [comment]
Good point - that might be an oversight. 

The code I changed so far is def the place where you run into your problem

**Comment by leastprivilege** [comment]
tracked here:

https://github.com/DuendeSoftware/IdentityServer/pull/914

**Comment by leastprivilege** [comment]
Hey, 

could you try the preview to see if it works as expected?

See here to setup the dev feed:
https://docs.duendesoftware.com/identityserver/v6/overview/packaging/#dev-builds

**Comment by rubo** [comment]
@leastprivilege I don't see the v6.1.1, only a handful of v6.2.0. So I tried with the v6.2.0-alpha.0.5 and it doesn't work as expected. It still returns a `string`.

**Comment by leastprivilege** [comment]
I cleaned the feed. The preview is now available.

**Comment by rubo** [comment]
In v6.1.1-preview.1, it works as expected. Thank you.

**Comment by leastprivilege** [comment]
OK - thanks!
