### ISSUE TITLE
Forcefully logout all users

### ISSUE THREAD

**Issue by crh225** [DuendeSoftware/Support#822]
**Which version of Duende IdentityServer are you using?** 
6

**Which version of .NET are you using?** 
core 6
**Describe the Question**
Is it possible to auto logout all users based on a schedule? For instance if an employee works 8 hour shift, and the shifts are configurable via some database, how can I access all the stored cookies on the server, loop through them all and log every user out forcefully. I'm generally looking for high level guidance on which classes/functions to use or if there any examples.

**Comment by josephdecock** [comment]
IdentityServer uses ASP.NET's cookie authentication handler to create a session. By default, those sessions entirely in the browsers of the users, not on the server. Session data is only available to you when a user makes an http request including a session cookie.

To do the kind of session management that you're describing, you need the session data to be stored server-side. This is possible in IdentityServer using our [Server Side Sessions](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/) feature. With server side sessions, the session data is stored in database that you can query and interact with, and the user's session cookie just contains the id of the session. IdentityServer's implementation of server-side sessions includes both the extension to the cookie handler that stores the data, as well as integration with the rest of identity server to perform session management (for example, when a user's session ends in IdentityServer, you can send clients back-channel notifications that their session has ended).

We have documentation [here](https://docs.duendesoftware.com/identityserver/v6/ui/server_side_sessions/session_management/) showing how you could have a UI that allows an admin to forcibly end user's sessions.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
