### ISSUE TITLE
Error after upgrading BFF

### ISSUE THREAD

**Issue by krispenner** [DuendeSoftware/Support#826]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
6.0

**Describe the issue**

We are a paying customer with a license for BFF. Since we upgraded to your latest version we now get an error with the bearer token in [AccessTokenRequestTransform](https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff.Yarp/AccessTokenRequestTransform.cs). I'm looking at code changes in GitHub and I see a lot of changes with added support for DPoP and how the token is now passed around (no longer a simple string). However, from digging through my logs and your code I can't see why my requests are failing now.

```
Access token is missing. token type: 'Unknown token type', local path: 'Unknown Route', detail: 'Missing access token type - should be one of 'DPoP' or 'Bearer''
```

There were [8 commits](https://github.com/DuendeSoftware/BFF/commits/main/src/Duende.Bff.Yarp/AccessTokenRequestTransform.cs) between June 8th and 14th that drastically changed how the AccessTokenRequestTransform uses the bearer token.

Just hoping you can tell me anything obvious (configuration maybe) that I may need to change to make my code work again as everything worked prior to this upgrade.

**Comment by josephdecock** [comment]
I suspect that this might be a bug related to sessions obtaining access tokens before any of the dpop support existed, and so not reporting a token type at all (bearer vs dpop). Do you get this error for existing users with existing sessions only? Or do you also get it for new sessions?

**Comment by krispenner** [comment]
@josephdecock I have now changed my code to the following and it seems to be working again. Maybe you can direct me to a better way to add a token to the authentication properties?

```cs
            await context.HttpContext.SignInAsync(AuthenticationSchemes.FrontendUserSession, principal, new()
            {
                AllowRefresh = true,
                IsPersistent = false,
                IssuedUtc = validatedToken.ValidFrom,
                ExpiresUtc = validatedToken.ValidTo,
                // TODO: Shouldn't be hacking this in, there must be a cleaner way to store it. 
                Items =
                {
                    { $".Token.{OpenIdConnectParameterNames.AccessToken}", accessToken },
                    { $".Token.{OpenIdConnectParameterNames.TokenType}", OidcConstants.AuthenticationSchemes.AuthorizationHeaderBearer },
                    { $".Token.{OpenIdConnectParameterNames.ExpiresIn}", validatedToken.ValidTo.ToString("o", CultureInfo.InvariantCulture) },
                }
            }).ConfigureAwait(false);
```

**Comment by josephdecock** [comment]
Under the hood, the BFF manages tokens using the Duende.AccessTokenManagement library. That includes a service which can store tokens for you.

From Duende.AccessTokenManagement.OpenIdConnect, inject a IUserTokenStore, and then call its StoreTokenAsync method.

**Comment by josephdecock** [comment]
I'm closing this issue, and we'll track further developments in https://github.com/DuendeSoftware/BFF/issues/182
