### ISSUE TITLE
DefaultUserService async flow support for GetUserClaims

### ISSUE THREAD

**Issue by kresimirlesic** [DuendeSoftware/Support#828]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
.NET 7

**Feature request**
Make GetUserClaims (and maybe GetManagementClaims as well?) in the DefaultUserService support async flow.

**Additional context**
It would be great if the GetUserClaims method supports the async flow so we could override it and e.g. hit the database (in an async manner) to append any extra claims.  The only way to solve this in the 2.1.1 version is to override the ProcessRequestAsync, which is basically opting out of the built-in behavior.

**Comment by kresimirlesic** [comment]
Yes, duplicating the logic of ProcessRequestAsync works for now.

Thank you!

**Comment by josephdecock** [comment]
Okay, great. I'll close this issue then, and track future developments on adding this feature in the new issue in the BFF repo.
