### ISSUE TITLE
TokenType is not set in JWT bearer auth handler

### ISSUE THREAD

**Issue by krilek** [DuendeSoftware/Support#829]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
6.0

**Describe the bug**

After update to new BFF / AccessTokenManagement library there is a problem with JWT bearer authentication flow.
Our setup allows for BFF together with support for JWT (token obtained elsewhere)

In case proxy User token is extracted and passed further. 
Flow uses AuthenticationSessionUserAccessTokenStore.GetTokenAsync.
This method reads OpenIdConnectParameterNames.TokenType which is only set during OpenIdConnect flow.
https://github.com/dotnet/aspnetcore/blob/324a3768366d83418058de773188166029327734/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1020

This doesn't happen in Jwt Bearer handler:
https://github.com/dotnet/aspnetcore/blob/324a3768366d83418058de773188166029327734/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L172C27-L172C27

**To Reproduce**

Setup dotnet JWT bearer authentication 
Send request with Authentication Bearer token header.
BFF request is stuck and result is HTTP code is 401

**Expected behavior**

Valid JWT request should proxied. TokenType in case of JwtBearerHandler by default should be "Bearer".

**Log output/exception with stacktrace**

```
info [Microsoft.AspNetCore.Hosting.Diagnostics] Request starting HTTP/1.1 GET http://localhost/service/test - -
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware] Wildcard detected, all requests with hosts will be allowed.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
trce [Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware] All hosts are allowed.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] 1 candidate(s) found for the request path '/service/test'
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] Endpoint 'service' with route pattern '/service/{**remainder}' is valid for the request path '/service/test'
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] Request matched endpoint 'service'
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware] The request is insecure. Skipping HSTS header.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
warn [Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware] Failed to determine the https port for redirect.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
 dbug [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] Successfully validated the token.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] AuthenticationScheme: Bearer was successfully authenticated.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
info [Microsoft.AspNetCore.Routing.EndpointMiddleware] Executing endpoint 'service'
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
trce [Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService] Starting user token acquisition
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] AuthenticationScheme: Bearer was successfully authenticated.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
dbug [Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService] No refresh token found in user token store for user unknown / resource default. Returning current access token.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
warn [Duende.Bff.Yarp.AccessTokenRequestTransform] Access token is missing. token type: 'User', local path: 'service', detail: 'Missing access token type - should be one of 'DPoP' or 'Bearer''
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
info [Yarp.ReverseProxy.Forwarder.HttpForwarder] Not Proxying, a 401 response was set by the transforms.
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
info [Microsoft.AspNetCore.Routing.EndpointMiddleware] Executed endpoint 'service'
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
info [Microsoft.AspNetCore.Hosting.Diagnostics] Request finished HTTP/1.1 GET http://localhost/service/test - - - 401 - - 198.4381ms
 => RequestPath:/service/test RequestId:0HMSU65MO0NUV
```

**Additional context**

**Comment by josephdecock** [comment]
I think your work-around is reasonable, but you might want to use the IUserTokenStore's StoreTokenAsync method instead, because that will match the logic of how the tokens are retrieved exactly. Your workaround is usually the same, but resource indicators are also included in the property name when they are present.

We've seen several related support issues since the new version of the BFF released where the dependency on the token type caused problems in unusual cases where it isn't available. We'll consider relaxing that requirement/defaulting to bearer tokens when no token type is present to be more robust in a future update.

**Comment by krilek** [comment]
I would need to verify it but calling StoreTokenAsync (from event of JWT) doesn't sound good as it tries to call AuthenticateAsync and SignInAsync (which expects cookie when server-side session is not used)

**Comment by josephdecock** [comment]
Yeah, you're probably right - you don't want all of the logic of StoreTokenAsync in your event. For now, this workaround seems okay, and hopefully we can relax the validation in the BFF to allow this situation more gracefully soon. Is it okay if we close this issue and track further discussion on the BFF issue above?

**Comment by krilek** [comment]
Yea, you can close this issue.
