### ISSUE TITLE
Exception when calling /bff/logout with Azure B2C 

### ISSUE THREAD

**Issue by tgermain-impirica** [DuendeSoftware/Support#83]
**Which version of Duende BFF are you using?**
1.2.1

**Which version of .NET are you using?**
6

**Describe the bug**
I am using the generic Cookie + OpenIdConnect authentication system. Our app is a React app served by a .Net 6 backend configured for BFF. Log in, get user info (/bff/user), local api is working.  I haven't tried remote Api just yet, but suspect that will be ok. However, when I set window.location.href to /bff/logout, I get the following exception:
KeyNotFoundException: The given key 'revocation_endpoint' was not present in the dictionary.

KeyNotFoundException: The given key 'revocation_endpoint' was not present in the dictionary.
System.Collections.Generic.Dictionary<TKey, TValue>.get_Item(TKey key)
IdentityModel.AspNetCore.AccessTokenManagement.DefaultTokenClientConfigurationService.GetTokenRevocationRequestAsync(UserAccessTokenParameters parameters) in DefaultTokenClientConfigurationService.cs
IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService.RevokeRefreshTokenAsync(string refreshToken, UserAccessTokenParameters parameters, CancellationToken cancellationToken) in TokenEndpointService.cs
IdentityModel.AspNetCore.AccessTokenManagement.UserAccessAccessTokenManagementService.RevokeRefreshTokenAsync(ClaimsPrincipal user, UserAccessTokenParameters parameters, CancellationToken cancellationToken) in UserAccessTokenManagementService.cs
Microsoft.AspNetCore.Authentication.TokenManagementHttpContextExtensions.RevokeUserRefreshTokenAsync(HttpContext httpContext, UserAccessTokenParameters parameters, CancellationToken cancellationToken) in TokenManagementHttpContextExtensions.cs
Duende.Bff.PostConfigureApplicationCookieRevokeRefreshToken+<>c__DisplayClass5_0+<<CreateCallback>g__Callback|0>d.MoveNext() in PostConfigureApplicationCookieRevokeRefreshToken.cs
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignOutAsync(AuthenticationProperties properties)
Microsoft.AspNetCore.Authentication.AuthenticationService.SignOutAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Duende.Bff.DefaultLogoutService.ProcessRequestAsync(HttpContext context) in DefaultLogoutService.cs
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
ServiceStack.AppHostBase.ProcessRequest(HttpContext context, Func<Task> next) in AppHostBase.NetCore.cs
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Duende.Bff.Endpoints.BffMiddleware.Invoke(HttpContext context) in BffMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by tgermain-impirica** [comment]
As it turns out, Azure AD B2C does not currently support revoking refresh token on logout. In order to suppress the error, I had to set the RevokeRefreshTokenOnLogout property to false on setup.
`services.AddBff(options =>
{
	options.RevokeRefreshTokenOnLogout = false;
}).AddRemoteApis();`

**Comment by leastprivilege** [comment]
Hey, 

yes - B2C is lacking in many areas.

Glad you figured it out!
