### ISSUE TITLE
session_state parameter on redirect can have request blocked by WAF OWASP CRS 3.x rules

### ISSUE THREAD

**Issue by sagenschneider** [DuendeSoftware/Support#832]
Which version of Duende IdentityServer are you using? 6.2.1
Which version of .NET are you using? 6.x

**Describe the bug**

The Base64Url encoding of the session_state parameter can on occasion fail the OWASP CRS 3.x rules for SQL Injection when encoding results in consecutive hyphens (--).   In particular, failing rule 942440 - REQUEST-942-APPLICATION-ATTACK-SQLI

Unfortunately, when using a cloud WAF following OWASP CSR 3.x rules ( https://owasp.org/www-project-modsecurity-core-rule-set/ ) there is a somewhat blanket disallow of two consecutive hyphens (--).  This on occasion disallows redirect back to the client, as the WAF blocks the session_state parameter when encoding results in consecutive hyphens (--).

Note that this does not occur on every login.  However, it is occurring frequently enough.  Users are then required to reattempt login.  This starts a new session with a new session_state value generated that hopefully does not have consecutive hyphens.  It is not a good experience for the user.

A few suggested solutions come to mind:
 - work with OWASP to relax rules (possibly not the best and less secure)
 - further encode the session_state to replace hyphens (-) with another character (such as one of `$+!*'(),` and possibly `*` as closest to original `+`)
 - consider using Base32Url encoding to avoid the hyphens (however does increase parameter value size by potentially 20%)

**To Reproduce**

1) Have a client application running behind a cloud WAF implementing the CRS 3.x rules
2) Undertake authentication_code login flow that results in session_state parameter containing consecutive hyphens (--)
3) Notice the redirect URL back to the client application is blocked by CRS rule 942440 - REQUEST-942-APPLICATION-ATTACK-SQLI

**Expected behavior**

Redirect back to client application is successful and login continues to obtain tokens.

**Comment by josephdecock** [comment]
Unfortunately, this is a known issue in ASP.NET's OIDC implementation, Microsoft/the ASP.NET team don't intend to change their implementation to address it, and there isn't a good way for us (IdentityServer) to mitigate the problem either. The only thing to do is to change the configuration of the WAF to allow the state parameter to have --. Customers using Azure's WAF have encountered this in the past and added the necessary exceptions. 

For more info from the ASP.NET team, see their issue here: https://github.com/dotnet/aspnetcore/issues/4589.

**Comment by sagenschneider** [comment]
Thanks @josephdecock   Yes, we are adding the WAF exception also.  Many thanks for the links and further information to clarify the issue.
