### ISSUE TITLE
Consider allowing creation of ClientCredentialsTokenRequest to be overridden 

### ISSUE THREAD

**Issue by espenekvang** [DuendeSoftware/Support#833]
In some situations we see that it is useful for us to be able to append httpcontext-dependent information as parameters on the ClientCredentialsTokenRequest before a token is requested in Duende.AccessTokenManagement.

A pull request is already added for this https://github.com/DuendeSoftware/Duende.AccessTokenManagement/pull/40

**Comment by josephdecock** [comment]
Hi, thanks for taking the time to create a pull request!

In some cases, it is possible to customize the parameters of the request by adding parameters to the TokenRequestParameters argument. 

Something, very roughly, like this:

```cs
public override async Task<ClientCredentialsToken> RequestToken(
        string clientName,
        TokenRequestParameters? parameters = null,
        CancellationToken cancellationToken = default
)
{
        parameters ?== new TokenRequestParameters();
        var customParam = RetrieveYourAdditionalContextSpecificParameters();
        parameters.Add(customParam.Key, customParam.Value);
        return base(clientName, parameters, cancellationToken);
}
```

Would that accomplish your goals as well?

**Comment by espenekvang** [comment]
Off course - thank you for pointing it out. It does the job for us.
