### ISSUE TITLE
Question about InMemoryCorsPolicyService

### ISSUE THREAD

**Issue by stjepan** [DuendeSoftware/Support#834]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
.NET 6

From time to time, I'm getting NullReferenceException on Duende.IdentityServer.Services.InMemoryCorsPolicyService.IsOriginAllowedAsync (which stack shows are in that query.Contains-call, so query seems to be null). InMemoryCorsPolicyService I do remember from old versions of [IdentityServer3](https://identityserver.github.io/Documentation/docsv2/configuration/cors.html) but I don't find it mentioned in the docs of 4 and later Duende versions. Since I'm using in-memory clients, I do see it being registered in that extensions method (AddInMemoryClients).

I'm trying to figure out if my configuration is correct. Docs of the InMemoryCorsPolicyService says _CORS policy service that configures the allowed origins from a list of clients' **redirect URLs**._ but on the lines 49-52, query is obviously reading from client.AllowedCorsOrigins and not client.RedirectUris. Which one is it?

FYI, I also do register custom client store, but NO custom CORS policy service, even thou that seems to be needed (a must), according the [docs](https://docs.duendesoftware.com/identityserver/v6/tokens/cors/#client-based-cors-configuration). Maybe that isn't fully accurate for all cases, as InMemoryCorsPolicyService is registered, but I'm probably wrong here.

**Comment by josephdecock** [comment]
The InMemoryCorsPolicyService is intended to be used when client configuration is store in memory, with AddInMemoryClients. If you're registering a custom client store then you do need a custom cors policy service as well, and I'm surprised that the `InMemoryCorsPolicyService` is able to be resolved from DI at all. Are you manually adding it to DI, or calling AddInMemoryClients in addition to your custom client config?

>Docs of the InMemoryCorsPolicyService says CORS policy service that configures the allowed origins from a list of clients' redirect URLs. but on the lines 49-52, query is obviously reading from client.AllowedCorsOrigins and not client.RedirectUris. Which one is it?

The InMemoryCorsPolicyService is using the AllowedCorsOrigins not the RedirectUris. Do you mind sending me a link to the documentation you are looking at? I don't see it in the Duende docs, but if I'm missing something I'd like to fix it.

**Comment by stjepan** [comment]
Thanks for the quick response!

Yeah, I'm both calling AddInMemoryClients and AddClientStore, so this might be problematic.
The registring code looks something along:
```
services
	.AddIdentityServer(options =>
	{
		options.KeyManagement.Enabled = false;

		options.LicenseKey = appSettings.IdentityProviderSettings.LicenseKey;

		options.Events.RaiseSuccessEvents = true;
		options.Events.RaiseFailureEvents = true;
		options.Events.RaiseErrorEvents = true;

		options.Logging.UnhandledExceptionLoggingFilter = (_, exception) => exception is not TaskCanceledException;
	})
	.AddServerSideSessions()
	.AddInMemoryIdentityResources(Config.GetIdentityResources())
	.AddInMemoryApiResources(Config.GetApiResources())
	.AddInMemoryApiScopes(Config.GetApiScopes())
	.AddInMemoryClients(Config.GetClients(appSettings.ClientSettings, appSettings.ClientSecretSetting))
	.AddClientStore<CustomClientStore>()
	.AddOperationalStore(options =>
	{
		options.ConfigureDbContext = config =>
			config.UseSqlServer(appSettings.ConnectionStrings.IdentityProviderDb);

		options.EnableTokenCleanup = true;
	})
	.AddAspNetIdentity<User>()
	.AddExtensionGrantValidator<DelegationGrantValidator>();
```

Regarding docs, I was meaning XML comments. Sorry for confusion.
Check https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Services/InMemory/InMemoryCorsPolicyService.cs#L16

**Comment by josephdecock** [comment]
No problem - thanks so much. I went ahead and corrected the xmldoc. 

You can only have one client store, so you'll need to pick between `AddInMemoryClients` and `AddClientStore<CustomClientStore>`. Of course, your custom store could combine in memory configuration with additional clients from another data store.

**Comment by stjepan** [comment]
Nice one!
That will be the way forward.
Thanks a lot for taking your time!
