### ISSUE TITLE
how to setup Multi-Tenant supported application with different signing credentials per tenant.

### ISSUE THREAD

**Issue by funkel1989** [DuendeSoftware/Support#835]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
Dotnet 7

**Describe the question**

Building an authentication/authorization system that supports multiple applications and tenants for each application. Upon creating a application and default tenant i'm generating RSA keys for each created tenant. It looks like the option to add signing credentials doesn't support a lambda expression. How would i set up IdentityServer to support a different signing credentials per each incoming authorization request?

```csharp
services.AddIdentityServer(options =>
    {
    })
    .AddSigningCredential(async provider =>
    {
        var httpContextAccessor = provider.GetRequiredService<IHttpContextAccessor>();
        var tenantSigningCredentialProvider = provider.GetRequiredService<ITenantSigningCredentialProvider>();

        var tenantId = httpContextAccessor.HttpContext.GetTenantId();
        return await tenantSigningCredentialProvider.GetSigningCredentialsAsync(tenantId);
    })
    .AddConfigurationStore<ConfigurationContext>()
    .AddOperationalStore<PersistedGrantContext>();
```

**Comment by josephdecock** [comment]
IdentityServer doesn't have multi-tenancy built in because there are actually a great many subtly different requirements that all go under the name "multi-tenancy". That said, you could customize the signing keys by providing your own implementation of the IKeyMaterialService. That service is responsible for providing the keys to the discovery endpoint and when signing tokens.

**Comment by funkel1989** [comment]
@josephdecock I looked at IKeyMaterialService and think this fits my needs perfectly. The one question I have now, When i create a tenant, if i store the key object in the database, i believe in the PersistedGrantDbContext, if i enable keymanagement will IdentityServer still manage the rotation of these keys for me? I'm guessing no but figured i'd ask just in case!

**Comment by funkel1989** [comment]
Thank you!

**Comment by funkel1989** [comment]
@josephdecock So I've looked at IKeyMaterialService which allows me to load keys based on tenant implementation which is helpful. I've also looked at ISigningKeyStore which allows me to store the keys how I want but I'm looking for the ability to control how keys are created.

When someone stored a new tenant entity in my database my code is going to automatically generate a specific signing key for that tenant. I understand that at some point I'm going to want to rotate these keys and IdentityServer key management normally takes care of this for you but it seems only when it manages the keys. If I create a key for X tenant what, if anything, can I implement to tell identity server this is a new RSA key for you to manage which IdentityServer will store via ISIgningKeyStore and utilize via IKeyMaterialService?

**Comment by josephdecock** [comment]
The key material service is a pretty high level abstraction that relies on lower levels to accomplish its work. It sounds like you need to go lower level, and customize the ISigningKeyStore. Your signing key store could add tenant information to the store, and when retrieving keys, only retrieve the keys relevant for the current tenant (assuming you can inject a service into your implementation that tells you which tenant is making the request). 

When your code provisions a tenant and creates a signing key, it would call your implementation of the ISigningKeyStore.StoreKeyAsync to persist the key in the database. And that implementation would need to add the extra data to the database to describe keys. The signing keys persisted using our EF based implementation don't know about the tenant, so you'd create your own entity that did, and take the SerializedKey model that we're passing around in identity server, convert that to your entity, and add the tenant information to the entity (again, from some sort of injectible service whose job it is to say which tenant invoked you).

**Comment by funkel1989** [comment]
Thanks. I think this has directed me to the things i need. I ended up taking a different approach with multiple databases + automatic key management. I think this will also solve my problem for now.
