### ISSUE TITLE
How to configure .well-known/openid-configuration links

### ISSUE THREAD

**Issue by Mothaimm** [DuendeSoftware/Support#839]
We need to use custom URLs in the response of the following call.
http://localhost:8091/.well-known/openid-configuration

![0AA2802D-FEF0-4D00-8EF2-DB799EABC21F](https://github.com/DuendeSoftware/Support/assets/142671282/58ba84f1-ebfc-4096-8aa9-dc985e6234e6)

Kindly support in providing the solution for it.

**Comment by josephdecock** [comment]
Can you describe your goals a little bit more? Which part of the url are you trying to change, and why?

**Comment by josephdecock** [comment]
@Mothaimm, just wanted to check in because I hadn't heard back from you. If you no longer need help, we can close this issue.

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
