### ISSUE TITLE
[Question] Discovery Endpoint Caching Workaround

### ISSUE THREAD

**Issue by faridfpul** [DuendeSoftware/Support#840]
Hi, so I have an issue where my Custom IDP that using Duende.IdentityServer is failed generating client credentials token due to  intermittent database issue like "**MySqlConnector.MySqlException (0x80004005): Connect Timeout expired. All pooled connections are in use.**" when accessing the discovery endpoint and token endpoint. My initial guess for root cause of the issue is because every time discovery endpoint called, it would do complex query to client and resource related table and cost a lot for the database connection. 
Then I found "**IdentityServerOptions.Discovery.ResponseCacheInterval**" options which would cache the discovery endpoint response and already proved it reduce the database call significantly on testing on our development environment. But in our QA and production environment, **Cache-Control no-store** is enabled that causing this caching feature to not work on those environments. the **Cache-Control no-store** config is also required in those environments due to our security team recommendation to mitigate vulnerabilities.
My question is, is there any other workaround to implement caching for discovery endpoint? Is there any interface to intercept the discovery endpoint call on service level?

**Comment by josephdecock** [comment]
Instead of using http headers to communicate your caching needs, you could also add caching to your configuration data store.

We have docs on how to cache the database requests for your config data [here](https://docs.duendesoftware.com/identityserver/v6/data/configuration/#caching-configuration-data).

**Comment by faridfpul** [comment]
hi @josephdecock, is there any working sample for using the caching configuration data?
previously I have tried to cache the client and resource data using the AddClientStoreCache<CustomClientStore> and ResourceStoreCache<CustomResourceStore> while research for some other issues, but I failed to make it works, for example like when I run my IDP, the custom store that I created is never called when I add breakpoint. Database call also still occurred when I check the log.

**Comment by josephdecock** [comment]
I don't think we have a full sample outside the sample code in the documentation, but we can try and help get it working for you.

The main thing to be aware of is, you need to register a store, and ICache, and the cache for the store.


So in our docs, that corresponds to

```
AddClientStore<YourCustomClientStore>()

AddInMemoryCaching()

AddClientStoreCache<YourCustomClientStore>()
```

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by faridfpul** [comment]
hi @josephdecock 
Currently we already implement the configuration caching, can close this thread.
Thank you
