### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by DinTri** [DuendeSoftware/Support#842]
**Which version of Duende IdentityServer are you using?**

**Which version of .NET are you using?**

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by DinTri** [comment]
Hi,
I use the latest version of Duende IdentityServer and .NET 7

Would you please check this code and show me where I made a mistake? When I remove the [Authorize] attribute of my WEB-API, it works correctly, but if I add [Authorize]
I have the error below:

{Method: GET, RequestUri: 'https://localhost:7075/api/weatherforecast?city=London', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY4RjA1NUYyNEI3NTlCMEZGMkYwOENCQjZEMTM0QzcxIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjkyNjIwMzMwLCJpYXQiOjE2OTI2MjAzMzAsImV4cCI6MTY5MjYyMzkzMCwiYXVkIjpbIndlYXRoZXJmb3JlY2FzdGFwaSIsImh0dHBzOi8vbG9jYWxob3N0OjUwMDEvcmVzb3VyY2VzIl0sInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJyb2xlcyIsIndlYXRoZXJmb3JlY2FzdGFwaS5mdWxsYWNjZXNzIl0sImFtciI6WyJwd2QiXSwiY2xpZW50X2lkIjoid2VhdGhlcmNsaWVudCIsInN1YiI6IjE0YzRjMGE3LTcxM2QtNGZkNC05ZjAxLWNhYmJhZGY4MmEyMSIsImF1dGhfdGltZSI6MTY5MjYyMDMyOCwiaWRwIjoibG9jYWwiLCJyb2xlIjoiUGF5aW5nVXNlciIsInNpZCI6IjQ0RDZEOENDM0IyMTcxQTI1MEI2ODU2ODA1Qjc0QjRDIiwianRpIjoiMTAwMkU0OUY5ODI2Njg1NkJGOURBMjNCQzNFNzkwQTYifQ.kChGS4hNO46r1rGUAa4Cd1XUNrecEKYUJdAxw4SpNQlrjONMjrskrf__03oyt8VfHt9ouuX4MrlVoCEGDXuDb9-ePQX7acHX5nRbc1VrFGEkKfQHoe-94shshq8nVbueA6wSDafaZMvZCls4xgzY2jxgCBIzN3AHNBpoS0T7-0Wew1d8pclq36MzSfILnMxhjZu2x4NgfAJbmJHZL2mURiqYyCChE_1EZ9xQE5oc5U8GzMShfZABR0rInk4my_b3F61phRIi4mhQBjONiO6Y4uqifrLuwsT_-Ehw83cBpWdvez_1U4dXLd8rFhZM9WcN623K8SmfM9bHZE6l1G3CHg
  Accept: application/json
  traceparent: 00-fa72bb51bcd53ab7561fae47210c129a-7642ec106643ef2b-00
}}

AccessToken:

eyJhbGciOiJSUzI1NiIsImtpZCI6IjY4RjA1NUYyNEI3NTlCMEZGMkYwOENCQjZEMTM0QzcxIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjkyNjIwMzMwLCJpYXQiOjE2OTI2MjAzMzAsImV4cCI6MTY5MjYyMzkzMCwiYXVkIjpbIndlYXRoZXJmb3JlY2FzdGFwaSIsImh0dHBzOi8vbG9jYWxob3N0OjUwMDEvcmVzb3VyY2VzIl0sInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJyb2xlcyIsIndlYXRoZXJmb3JlY2FzdGFwaS5mdWxsYWNjZXNzIl0sImFtciI6WyJwd2QiXSwiY2xpZW50X2lkIjoid2VhdGhlcmNsaWVudCIsInN1YiI6IjE0YzRjMGE3LTcxM2QtNGZkNC05ZjAxLWNhYmJhZGY4MmEyMSIsImF1dGhfdGltZSI6MTY5MjYyMDMyOCwiaWRwIjoibG9jYWwiLCJyb2xlIjoiUGF5aW5nVXNlciIsInNpZCI6IjQ0RDZEOENDM0IyMTcxQTI1MEI2ODU2ODA1Qjc0QjRDIiwianRpIjoiMTAwMkU0OUY5ODI2Njg1NkJGOURBMjNCQzNFNzkwQTYifQ.kChGS4hNO46r1rGUAa4Cd1XUNrecEKYUJdAxw4SpNQlrjONMjrskrf__03oyt8VfHt9ouuX4MrlVoCEGDXuDb9-ePQX7acHX5nRbc1VrFGEkKfQHoe-94shshq8nVbueA6wSDafaZMvZCls4xgzY2jxgCBIzN3AHNBpoS0T7-0Wew1d8pclq36MzSfILnMxhjZu2x4NgfAJbmJHZL2mURiqYyCChE_1EZ9xQE5oc5U8GzMShfZABR0rInk4my_b3F61phRIi4mhQBjONiO6Y4uqifrLuwsT_-Ehw83cBpWdvez_1U4dXLd8rFhZM9WcN623K8SmfM9bHZE6l1G3CHg

IdentityToken:

eyJhbGciOiJSUzI1NiIsImtpZCI6IjY4RjA1NUYyNEI3NTlCMEZGMkYwOENCQjZEMTM0QzcxIiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjkyNjIwMzMwLCJpYXQiOjE2OTI2MjAzMzAsImV4cCI6MTY5MjYyMDYzMCwiYXVkIjoid2VhdGhlcmNsaWVudCIsImFtciI6WyJwd2QiXSwibm9uY2UiOiI2MzgyODIxNzEyNjQyOTkwMzQuWm1Wa01qaGxORFV0T0dWaU5TMDBNalE1TFRnelpqa3ROV1k0TkRjME5EQXlZVFl6TjJJNU4yWmlPVFV0TUdVNFpTMDBZVGcxTFdJMk5EZ3RNMkV3T0dGbVkySmxZMlkwIiwiYXRfaGFzaCI6ImtBZGZyemJrRnlnLWpJVjBxUHRwZFEiLCJzaWQiOiI0NEQ2RDhDQzNCMjE3MUEyNTBCNjg1NjgwNUI3NEI0QyIsInN1YiI6IjE0YzRjMGE3LTcxM2QtNGZkNC05ZjAxLWNhYmJhZGY4MmEyMSIsImF1dGhfdGltZSI6MTY5MjYyMDMyOCwiaWRwIjoibG9jYWwifQ.oLbkZkwgQsrPtDgvSVZ6KEZYfbaTNRn8ENG4oD4doYB1fF_9vnK8kKYwYilM2sTklBcw5kplWjly6hxw7s21NAQ5UdpPP5uDrl7wR1tlIc-OtTBXObYzNwDAyZM22HmfCFoXK-EprCnc-xb4UmhqwXQvOdD979UkdREPdtRvCn1NgkpGlk2-8HLLYzFkuAMxx0ssdafR6_bp81NFx8ovGbaTwPQBTvrgc9dgrIgCnbMeVLNWjH9bWGVhBs3gq94nOsafRWATGjVtjQNYtWKVqrTCokbNyDEJWIoloHwa05bIILN276WfkYhLPgU-5hvMFVBw8bx24AC1f8TQQcrD7w


controller from the web application

private async Task<List<WeatherResponse?>?> CallWeatherServiceAsync(string city)
        {
            try
            {
                if (string.IsNullOrEmpty(city))
                {
                    ModelState.AddModelError("", "Please enter a valid city.");
                }

                var encodedCity = WebUtility.UrlEncode(city);
                var httpClient = _httpClientFactory.CreateClient("APIClient");
                var requestUrl = $"/api/weatherforecast?city={encodedCity}";
                var request = new HttpRequestMessage(HttpMethod.Get, requestUrl);
                var identityToken = await HttpContext
                    .GetTokenAsync(OpenIdConnectParameterNames.IdToken);
                var accessToken = await HttpContext
                    .GetTokenAsync(OpenIdConnectParameterNames.AccessToken);
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
                response.EnsureSuccessStatusCode();

                await using var responseStream = await response.Content.ReadAsStreamAsync();
                List<WeatherResponse>? weather = await JsonSerializer.DeserializeAsync<List<WeatherResponse>>(responseStream);
                TempData["WeatherData"] = JsonConvert.SerializeObject(weather);

                return weather;
            }
            catch (Exception ex)
            {
                // Log the exception for debugging
                _logger.LogError(ex, "Unhandled exception occurred");

                ModelState.AddModelError("An error occurred.", ex.Message);
            }

            return null;
        }

Program for the web application:

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews().AddJsonOptions(configure =>
    configure.JsonSerializerOptions.PropertyNamingPolicy = null);
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
builder.Services.AddAccessTokenManagement();
// create an HttpClient used for accessing the API
builder.Services.AddHttpClient("APIClient", client =>
{
    client.BaseAddress = new Uri(builder.Configuration["WeatherForecastAPIRoot"] ?? throw new InvalidOperationException());
    client.DefaultRequestHeaders.Clear();
    client.DefaultRequestHeaders.Add(HeaderNames.Accept, "application/json");
}).AddUserAccessTokenHandler();

builder.Services.AddAuthentication(options =>
    {
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    }).AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
    {
        options.AccessDeniedPath = "/Authentication/AccessDenied";
    })
    .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
    {
        options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.Authority = "https://localhost:5001/";
        options.ClientId = "weatherclient";
        options.ClientSecret = "secret";
        options.ResponseType = "code";
        //options.Scope.Add("openid");
        //options.Scope.Add("profile");
        //options.CallbackPath = new PathString("signin-oidc");
        // SignedOutCallbackPath: default = host:port/signout-callback-oidc.
        // Must match with the post logout redirect URI at IDP client config if
        // you want to automatically return to the application after logging out
        // of IdentityServer.
        // To change, set SignedOutCallbackPath
        // eg: options.SignedOutCallbackPath = new PathString("pathaftersignout");
        options.SaveTokens = true;
        options.GetClaimsFromUserInfoEndpoint = true;
        options.ClaimActions.Remove("aud");
        options.ClaimActions.DeleteClaim("sid");
        options.ClaimActions.DeleteClaim("idp");
        options.Scope.Add("roles");
        options.Scope.Add("weatherforecastapi.fullaccess");
        options.ClaimActions.MapJsonKey("role", "role");
        options.TokenValidationParameters = new TokenValidationParameters
        {
            NameClaimType = "given_name",
            RoleClaimType = "role"
        };
    });

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler();
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Weather}/{action=Index}/{id?}");

app.Run();

controller from the Web-API:

[Authorize]
    [ApiController]
    [Route("api/[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private readonly IMediator _mediator;

        public WeatherForecastController(IMediator mediator)
        {
            _mediator = mediator;
        }


        // [HttpGet("{city}", Name = "GetWeatherForecasts")]
        //[Authorize(Roles = "PayingUser")]
        [HttpGet]
        public async Task<IActionResult> GetWeatherForecasts(string city)
        {
            var user = HttpContext.User;

            // Access token claims can be retrieved from the User object
            var accessTokenClaims = user.Claims;
            var query = new GetWeatherForecastsQuery(city); // Pass the city parameter here

            var weatherForecasts = await _mediator.Send(query);

            return Ok(weatherForecasts);
        }
    }

{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Mon, 21 Aug 2023 12:28:08 GMT
  Server: Kestrel
  WWW-Authenticate: Bearer error="invalid_token"
  Content-Length: 0
}}

program for the Web-API:

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers()
    .AddJsonOptions(configure => configure.JsonSerializerOptions.PropertyNamingPolicy = null);
// Add services to the container.
builder.Configuration.AddJsonFile("appsettings.json");
builder.Services.AddHttpClient<IWeatherForecastService, WeatherForecastService>();
builder.Services.AddSingleton<IWeatherForecastService, WeatherForecastService>();
builder.Services.AddSingleton(WeatherMapperProfile.CreateMapper());
builder.Services.Configure<WeatherApiSettings>(builder.Configuration.GetSection("WeatherApiSettings"));
builder.Services.AddMediatR(cfg => cfg.RegisterServicesFromAssemblies(Assembly.GetExecutingAssembly()));
builder.Services.AddScoped(typeof(IRepository<>), typeof(Repository<>));
builder.Services.AddSingleton<IWeatherForecastService, WeatherForecastService>();
builder.Services.AddTransient<IRequestHandler<GetWeatherForecastsQuery, List<WeatherResponseDto>>, GetWeatherForecastsQueryHandler>();
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = "https://localhost:5001/";
        options.Audience = "weatherforecastapi";
        options.TokenValidationParameters = new()
        {
            NameClaimType = "given_name",
            RoleClaimType = "role",
            ValidTypes = new[] { "at+jwt" }
        };
    });
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
//builder.Services.AddEndpointsApiExplorer();
//builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
//if (app.Environment.IsDevelopment())
//{
//    app.UseSwagger();
//    app.UseSwaggerUI();
//}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseAuthentication();

app.UseAuthorization();

app.MapControllers();

app.Run();


Here is IdentityServer Config file:

using Duende.IdentityServer;
using Duende.IdentityServer.Models;

namespace IdentityServer;

public static class Config
{
    public static IEnumerable<IdentityResource> IdentityResources =>
        new IdentityResource[]
        {
            new IdentityResources.OpenId(),
            new IdentityResources.Profile(),
            new("roles", "Your role(s)", new [] {"role"})
        };

    public static IEnumerable<ApiResource> ApiResources =>
        new[]
        {
            new ApiResource("weatherforecastapi", "WeatherForecast Api",
            new [] { "role" })
            {
                Scopes = { "weatherforecastapi.fullaccess", "weatherforecastapi.read", "weatherforecastapi.write" }
            }
        };
    public static IEnumerable<ApiScope> ApiScopes =>
        new[]
        {
            new ApiScope("weatherforecastapi.fullaccess"),
            new ApiScope("weatherforecastapi.read"),
            new ApiScope("weatherforecastapi.write")
        };

    public static IEnumerable<Client> Clients =>
        new[]
        {
            new Client()
            {
                ClientName = "Weather",
                ClientId = "weatherclient",
                AllowedGrantTypes = GrantTypes.Code,
                RedirectUris =
                {
                    "https://localhost:7184/signin-oidc"
                },
                PostLogoutRedirectUris =
                {
                    "https://localhost:7184/signout-callback-oidc"
                },
                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    "roles",
                    "weatherforecastapi.fullaccess",
                    "weatherforecastapi.read",
                    "weatherforecastapi.write"
                },
                ClientSecrets =
                {
                    new Secret("secret".Sha256())
                },
                RequireConsent = true
            }
        };
}


Kind regards,

Trifon

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by DinTri** [comment]
I found the problem. It was with wrong link to the WEB-API controller.
Thank you.
