### ISSUE TITLE
Best way to set up discovery doc when hosting in https-terminated environment?

### ISSUE THREAD

**Issue by bn-dkuang** [DuendeSoftware/Support#844]
**Which version of Duende IdentityServer are you using?**

6.3.3

**Which version of .NET are you using?**

.NET 7.0

**Describe the bug**

My IdentityServer instance is hosted in EKS behind an https-terminated ingress (so the requests between the ingress and the actual service pods are in plain http), so with the default behavior of the library all the links in the discovery doc will be set as plain http, which causes a lot of issues with clients using the parsed document to make requests.

Currently, I use this "hack" to get around the problem:
```
app.Use((context, next) =>
{
    context.SetIdentityServerOrigin("ACTUAL_HTTPS_URL_HERE");
    return next();
});
```
However, I'm wondering whether there's any better way to configure this with my hosting setup?

**Comment by josephdecock** [comment]
The better way to do this is with the x-forwarded-proto header. In many case, your ingress should be setting this header already, and you can tell asp.net to respect that by using the ForwardedHeadersMiddleware. See https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/ for our docs on this.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by bn-dkuang** [comment]
Yes this can be closed. I looked around some more about the x-forwarded-for header (it wasn't working for the longest time) and it turned out the trick in my case was adding
```
fordwardedHeaderOptions.KnownNetworks.Clear();
fordwardedHeaderOptions.KnownProxies.Clear();
```
After creating the options object. Everything is working as intended now
