### ISSUE TITLE
How to deploy IdentityServer to azure container app properly?

### ISSUE THREAD

**Issue by ffurkans** [DuendeSoftware/Support#846]
I deployed the IdentityServer to azure container app.

.well-known/openid-configuration generates different schema for issuer (https) and jwks_uri (http).

It is because jwks_uri is based on host url which is port 80 for docker container.

So the issuer url is:
https://identity.ambitiousriver-asdada.uksouth.azurecontainerapps.io

jwks_uri is:
http://identity.ambitiousriver-asdada.uksouth.azurecontainerapps.io/.well-known/openid-configuration/jwks

so I am having following error (it checks the authority by checking if it starts with the issuer):
Endpoint belongs to different authority: http://identity.ambitiousriver-asdada.uksouth.azurecontainerapps.io/.well-known/openid-configuration/jwks

I couldn't find a proper solution to this issue.

Is there any example how to deploy identityserver to azure container app?

My workaround is as follow:
```
var disco = client.GetDiscoveryDocumentAsync(
                    new DiscoveryDocumentRequest
                    {
                        Address = identityURL,
                        Policy =
                        {
                            RequireHttps = false,
                            AuthorityValidationStrategy = new CustomAuthorityUrlValidation() // returns success
                        },
                    }
```

```
var tokenResponse = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
                {
                    Address = disco.TokenEndpoint.Replace("http:","https:"),
.....
}
```

```
 _configurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
                 _wellKnownEndpoint, new OpenIdConnectConfigurationRetriever(), 
new HttpDocumentRetriever() { **RequireHttps = false**});

var oidcWellknownEndpoints = await _configurationManager.GetConfigurationAsync();
```

Is there a way to generate the jwks_uri as https even the container is exposed from http port?

Thanks

**Comment by josephdecock** [comment]
It sounds like your container is behind a reverse proxy or load balancer and the tls connection terminates at the proxy. Almost all such proxies set the X-Forwarded-Proto and X-Forwarded-For http headers to describe the original request before proxying. You can tell ASP.NET to respect those headers by [adding the forwarded headers middleware](https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/).

**Comment by ffurkans** [comment]
I already have the ForwardedHeadersOptions middleware. That didn't help. But the following code that is recommended in the same page did the trick.

```
app.Use((context, next) =>
            {
                context.Request.Scheme = "https";
                return next(context);
            });
```

Thanks a lot.
