### ISSUE TITLE
Disabled user in external identity provider (federation) - Check if an external user is still active when an access token is renewed

### ISSUE THREAD

**Issue by martinrulf** [DuendeSoftware/Support#847]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

6.0

**The question**

Currently we use federation for both external and internal logins.
Currently for both cases AAD is used as the federated provider (External Identity Server).

The issue we are facing is when the user has been disabled in the federated provider. (E.g. termination of employment)

When there is an active session (cookie) that can be used for silent renew or there is a valid refresh token and a new access token is requested then there is called IProfileService.IsActiveAsync method to check if the user is still eligible to log-in. 

This is completely fine for internal accounts (even those in AAD as this status is synced). We can check if the user is still active or not in our system and we can react accordingly.

But when an external federation provider is used and the account has been disabled since the latest successful log-in (in federated provider, not at our side) we are not able to check this as this state is not synced.

Is there any mechanism or something how we could check if the user is still valid and active in the federated provider originally used to log-in for the external user?

E.g. 
* Redirect the access token renewal to the external identity server
* Call some standard endpoint exposed by the external identity server (which one can be inferred from value of idp claim) from IsActiveAsync to check if the user is still valid there?
* Any other possible solution to this?

I tried to search for some standard solution but I'm running out of ideas.

Any help would be appreciated

THX

Martin

**Comment by josephdecock** [comment]
Exactly how you would determine if a user is disabled in the external provider isn't going to be totally consistent across external providers. You might need to call the userinfo endpoint or you might need to call an endpoint that they define. You'll have to consult the external idp's to find out how to do that. Once you have that, the right place to put the logic in IdentityServer is in a customized [ProfileService](https://docs.duendesoftware.com/identityserver/v6/reference/services/profile_service/)'s IsActiveAsync method.

**Comment by martinrulf** [comment]
@josephdecock thx for the clarification

`Exactly how you would determine if a user is disabled in the external provider isn't going to be totally consistent across external providers.`

Well, I understand what you mean, this is generally a valid concern, but in our case we can guarantee that external user can log-in into our system only via given federated provider (via given Authentication scheme)

There is basically 1:1 mapping between External Provider and specific (external) user in our system (The user is created the first time they log in via configured federated provider, and matched via email for each consecutive log-in)

Moreover we can control this logic (if the (remote) IsActive should or not be triggered) for given user and given authentication schema as we can extract the authentication schema from "idp" claim we have available in IProfileService.IsActiveAsync. And vice versa we are able to not trigger this logic in case of our internal users.

Anyway, a less invasive way to accomplish this could be to issue short-living refresh tokens (eg. 24h) and disable sliding expiration + adjust [authentication session cookie](https://docs.duendesoftware.com/identityserver/v6/ui/login/session/#authentication-session) in the same way **but only for specific federated providers**, currently I'm aware of global config for this, and not sure if this can be controlled for specific External Identity Servers.

Is it possible to apply what I'm proposing in the previous paragraph? 

BTW we are using [dynamic providers](https://docs.duendesoftware.com/identityserver/v6/ui/login/dynamicproviders/) if this matters

**Comment by josephdecock** [comment]
We only have built in the ability to customize refresh token lifetime on a per-client basis, not on a per-identity provider basis. To do that, you'd need to customize the refresh token service. You could start by inheriting from DefaultRefreshTokenService, and overriding UpdateRefreshTokenAsync. The default implementation of that method handles both token rotation and sliding. You could replace the sliding logic with your own per-client sliding logic. 

The thing that you'll need to solve to do that is, from that service, how do you know which external idp was used? Typically (our default UI does this), when you log in externally, there is a claim set named idp with the value of the scheme name used to authenticate. So I would make sure that your UI is setting the idp claim (it might be using the constant IdentityModel.ClaimTypes.ExternalProvider).

Then you can get at that claim from the refresh token service through its request parameter, with something like this:

```
var idp = request.RefreshToken.Subject.FindFirst(IdentityModel.JwtClaimTypes.IdentityProvider)?.Value;
```

**Comment by martinrulf** [comment]
@josephdecock Thank you for pointing me in the right direction, I'll give a try.

**Comment by josephdecock** [comment]
No problem - let us know how it goes!

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by martinrulf** [comment]
Hi @josephdecock , 

We put this issue into our backlog as our priorities had changed.

I hope I will get to this in the near feature.
Anyway, I'm closing this for now and will reopen it when needed.

THX 
M.
