### ISSUE TITLE
Forwarded headers do not work behind a load balancer 

### ISSUE THREAD

**Issue by dclayton77** [DuendeSoftware/Support#849]
**Which version of Duende BFF are you using?**
2.0.0

**Which version of .NET are you using?**
.NET 7

**Describe the bug**
When hosting BFF behind a load balancer where HTTPS traffic is terminated, the communication between BFF and IdentityServer does not work as expected.  In my setup I have a React application that is hosted by the BFF service.  The BFF service has the following settings defined in its pipeline:

```
....
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.All;
});
....
app.UseForwardedHeaders();
....
```

I have validated that when the React application is rendered by the browser that the relevant settings are provided using the proxy protocol on the load balancer.  The client IP address is preserved and all relevant information is present in the headers of the request.  The following shows the log output of the headers received (IP and domain are obscured but are correct values):

![image](https://github.com/DuendeSoftware/Support/assets/28646129/42a67c3e-18e3-4e3c-bc97-b2413a96a953)

When the redirect is made to IdentityServer, the redirect URI is sent as http rather than https.  This leads to the following error in the logs of the BFF service.

![image](https://github.com/DuendeSoftware/Support/assets/28646129/15ffe771-6f21-4504-88ac-2fb0a1e9b07c)

Other factors that may be a part of the problem, although I don't know if this is the case, is that my BFF framework is hosted on a different sub domain to IdentityServer.  E.g. www.dev.mydomain.co.uk and auth.dev.mydomain.co.uk.  Please let me know if this is a factor and how I should configure my setup to mitigate it.

**Comment by dclayton77** [comment]
Nailed it!

Thanks to [this](https://github.com/DuendeSoftware/Support/issues/12) thread I found the answer.  They key is to combine the forwarded headers configuration so that it is set as follows:

```
var forwardedHeadersOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.All,
    ForwardLimit = 1
};
forwardedHeadersOptions.KnownNetworks.Clear();
forwardedHeadersOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeadersOptions);
```

**Comment by josephdecock** [comment]
Thanks for updating us @dclayton77! Appreciate the help for others as well.
