### ISSUE TITLE
BffServiceCollectionExtensions.AddBff does not allow me to add an AccessTokenManagementConfigureAction with a service provider.

### ISSUE THREAD

**Issue by rth001** [DuendeSoftware/Support#85]
**Which version of Duende BFF are you using?**
Duende.Bff 1.21

**Which version of .NET are you using?**
.net 6.0.105

**Describe the bug**
I would like access to the service provider when calling AddBff with an AccessTokenManagementConfigureAction

Below is the overload with Action<IServiceProvider, AccessTokenManagementOptions> configureAction
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/main/src/AccessTokenManagement/TokenManagementServiceCollectionExtensions.cs#L74

**Comment by leastprivilege** [comment]
This is currently not possible - what are you trying to achieve?

**Comment by rth001** [comment]
I was attempting to pull a value from a legacy session cookie via httpcontextaccessor to use it in my client credentials token request. I was actually able to work around the problem so I do not need a solution to the above question.

But, thank you for the quick response!
