### ISSUE TITLE
How to split-up IdentityServer into tiers

### ISSUE THREAD

**Issue by albert0ly** [DuendeSoftware/Support#851]
Not a bug. A question.

According to security policy in our organization (and the best practices) we cannot have direct access to database from a computer opened to the internet. It means we need Front-End Web (in DMZ) that connected via REST (or Web Service or just any HTTPS) to App Layer (in LAN). Only App Layer has direct connection to DB.

How can we do it?

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
