### ISSUE TITLE
"Specified cast is not valid" when BffAuthenticationStateProvider is registered

### ISSUE THREAD

**Issue by paulguz-datapa** [DuendeSoftware/Support#852]
**Which version of Duende BFF are you using?**

2.1.1 (Duende 6.3.3)

**Which version of .NET are you using?**

6.0.21

**Describe the bug**

In a Blazor WASM project, registering BffAuthenticationStateProvider renders it impossible to request other authentication services from the DI container.  Attempts produce "Specified cast is not valid." errors.

For example, an attempt to request the IAcessTokenProvider service produces the above error emanating from AddRemoteAuthentication.

Similarly, any attempt to configure an HttpClient by requesting AuthorizationMessageHandler in AddHttpMessageHandler produces the same error.

In searching for a solution, I found [this post](https://github.com/dotnet/aspnetcore/issues/29487#issuecomment-764594303), with Javier in the ASP.Net team indicating that a custom implementation of AuthenticationStateProvider requires other classes to also be implemented.

What do you suggest?

**To Reproduce**

Register BffAuthenticationStateProvider, then attempt to request either the AuthorizationMessageHandler, or IAccessTokenProvider services.

**Expected behavior**

Can access requested services

**Log output/exception with stacktrace**

```
`

> System.AggregateException: One or more errors occurred. (Specified cast is not valid.)
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Extensions.DependencyInjection.WebAssemblyAuthenticationServiceCollectionExtensions.<>c__0`3[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.OidcProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].<AddRemoteAuthentication>b__0_0(IServiceProvider sp)

`
```

**Additional context**

**Comment by josephdecock** [comment]
With the BFF architecture, access tokens are _by design_ not available to the front end. Instead, the frontend authenticates all of its requests using an auth cookie for the backend. The backend session contains the access token, and the BFF retrieves the token from that session and can attach it to external api requests that are proxied through the BFF.

So, I don't think you need to use these abstractions when you're using the BFF - it looks like everything you're resolving is to do with retrieving access tokens and attaching them to outbound http requests. Take a look at our docs on how to use BFF remote endpoints [here](https://docs.duendesoftware.com/identityserver/v6/bff/apis/).

**Comment by paulguz-datapa** [comment]
@josephdecock You are right, it makes no sense to attempt to access IAcessTokenProvider in a BFF scenario. 

However, what if you need AuthorizationMessageHandler?  That has nothing to do with BFF, it is simply part of the configuration of an HTTP client.

**Comment by josephdecock** [comment]
So far in our experience, the `AuthorizationMessageHandler` hasn't been necessary, since a typical Blazor with the BFF makes all its http requests proxied through the BFF, and the authorization of those requests is done by the implicit credential of the auth cookie - in other words the browser attaches the auth cookie for you. If you've got a use case for the `AuthorizationMessageHandler`, can you tell us a bit more about it?

**Comment by paulguz-datapa** [comment]
We make use of the authorizedUrls property of the AuthorizationMessageHandler.  However, as that ultimately relates to the attachment of an access token to the request, I suppose that also now needs to go server-side.

I don't think BFF is for us at the moment as it'll require quite a lot of changes.  Thanks anyway.

**Comment by RichardCain** [comment]
Hi,
 I have a use case for needing the access token.. The telerik reportviewer Blasor WASM component needs is to pass authenticated requests for reports. It needs code like this:

` var accessTokenResult = await TokenProvider.RequestAccessToken();
 AccessToken = string.Empty;

 if (accessTokenResult.TryGetToken(out var token))
 {
     AccessToken = token.Value;
     await rv1!.SetAuthenticationTokenAsync(AccessToken);
     await rv1!.SetReportSourceAsync(new ReportSourceOptions()
         {
             Report = $"{reportPath}"
         });
 }`

Is there no way of getting the token so I can attach it?

Cheers

Rich

**Comment by AndersAbel** [comment]
@RichardCain Please open a new issue. While your requirements may be similar to the original request, they might require a different discussion/solution so it is better to have them in a separate issue.
