### ISSUE TITLE
Question: Converting MVC example into Web API  + SPA

### ISSUE THREAD

**Issue by funkel1989** [DuendeSoftware/Support#857]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
7.x

Question:
I'm having some trouble understanding how to handle user authentication with AspNetCore Identity is mixed with Identity Server. 
I'm making a WebApi application that will not sport a front end of its own. and then a separate vuejs 3 application to act as the current frontend for the Identity Server web authentication framework. 
I know how to use Identity UserManager and Role Manager to authenticate my user and I know how to build a JWT from scratch but isn't Identity Server supposed to handle created the JWT/Cookie based on the Client i've created for User login?

Does anyone have an example of how Identity Server works with AspnetCore Identity for user authorization that isn't concealed into MVC or able to point me to where in the docs this is talked about if at all?

sorry ahead of time for dumb question.

**Comment by josephdecock** [comment]
We have a sample of ASP.NET Identity integration here: https://docs.duendesoftware.com/identityserver/v6/samples/aspid/

We also have a section of our quickstart series on the topic here: https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/

Our general documentation on the subject is here: https://docs.duendesoftware.com/identityserver/v6/aspnet_identity/

I also highly recommend our series of videos on our youtube channel: https://www.youtube.com/@duendesoftware. These cover the fundamentals of how the ASP.NET authentication system works with the OIDC and OAuth protocols that IdentityServer is implementing.

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by josephdecock** [comment]
Closing, but feel free to reopen if necessary.
