### ISSUE TITLE
Getting status code 302 on mobile device 

### ISSUE THREAD

**Issue by Talal0** [DuendeSoftware/Support#860]
**Which version of Duende IdentityServer are you using?**
Identity Server V6 

**Which version of .NET are you using?**
.NET version is 7

**Describe the bug**
When calling the login method in the identity server, the user is first signed in through signInManager object and then is redirected to **/connect/authorize?client_id** which would then redirect to a callbackURL with an authorization code which is then used to generate a token. This implementation works when a login call is made from Postman or a web application but when it is consumed from a Flutter/Native Android mobile application with the same request, a 302 error code is received.

<img width="455" alt="Screenshot 2023-08-29 at 1 34 19 PM" src="https://github.com/DuendeSoftware/Support/assets/32738473/36c5b492-69d4-4f07-89b0-f5ac4087823b">
<img width="561" alt="Screenshot 2023-08-29 at 1 33 58 PM" src="https://github.com/DuendeSoftware/Support/assets/32738473/88f2abde-6ef7-4995-a1cb-2c1b9d3ca46b">

**Comment by josephdecock** [comment]
Http 302 [isn't an error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302), it's a redirect. This is expected behavior from IdentityServer. What other symptoms are you seeing on your end? It sounds like it might be an issue with your client library?

**Comment by Talal0** [comment]
> Http 302 [isn't an error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302), it's a redirect. This is expected behavior from IdentityServer. What other symptoms are you seeing on your end? It sounds like it might be an issue with your client library?

Below attached logs screenshot is from Postman console. 

Postman:
1. When I hit my login call which is a POST request it gives 302 with redirection URL in response. 
2. Then I consume the URL I get in location in header of post request as GET request from Postman that gives another 302, which then contains my callback url that has code and scopes and states.
3. Then a GET call to that callback redirects to my callback endpoint on which, I use the code to generate token. 

Flutter:
First 2 steps I am able to perform same as the postman behaviour but in step 2 response, instead of a 302 and the callback url in header, I get a 200 which contains identity server login html.
<img width="1727" alt="Screenshot 2023-08-31 at 12 01 08 PM" src="https://github.com/DuendeSoftware/Support/assets/32738473/cb3b7b43-76d9-4f63-ae2e-558c64d37dfa">

**Comment by josephdecock** [comment]
So you're seeing the login page, entering credentials, and getting redirected back to the login page? That sounds like the auth cookie that is set by the login page isn't being sent in subsequent requests. Can you debug that in your flutter app? You should see the login page's response be a redirect that also sets your auth cookie, and then each subsequent request to IdentityServer should include it.

**Comment by Talal0** [comment]
Thanks for letting me know the issue was in the cookie I didn't add it to the GET authorization request (2nd step) headers after adding it I'm getting the required results.
