### ISSUE TITLE
Why is this request to /connect/authorize invalid?

### ISSUE THREAD

**Issue by hypernova-za** [DuendeSoftware/Support#861]
I'm busy testing Duende Identity Server and ran into an issue that I do not know how to resolve.

When pasting this link into a browser:

https://demo.duendesoftware.com/connect/authorize?client_id=interactive.public&scope=openid&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A5000

an error is returned:
```
Sorry, there was an error : invalid_request
```

I checked and confirmed the client ID, scope and response type values and all of them are correct according to the detail provided here https://demo.duendesoftware.com

I also tried different values for redirect_uri but that did not make any difference.

**Comment by josephdecock** [comment]
Your authorize request requires [PKCE](https://datatracker.ietf.org/doc/html/rfc7636), so you need to pass the code_challenge and code_challenge_method parameters.

**Comment by josephdecock** [comment]
Most of our error messages are mandated by specs, and sometimes that isn't the most helpful for debugging from the point of view of the client - the specs are trying to not leak information to attackers.

But, if you start up your own identity server locally, the logs created by IdentityServer itself include many more details whenever an error occurs. So, it might be worth [spinning up your own IdentityServer locally](https://docs.duendesoftware.com/identityserver/v6/quickstarts/).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?

**Comment by hypernova-za** [comment]
Thank you for the response, sorted now.
