### ISSUE TITLE
Default Client Secret Validator when Validating PreHash or PostHash Secret is both Valid.

### ISSUE THREAD

**Issue by faridfpul** [DuendeSoftware/Support#864]
**Which version of Duende IdentityServer are you using?**
6.1.1

**Which version of .NET are you using?**
6.0

**Describe the bug**

I'm not sure whether this is bug or expected behavior, but on Client Secret validation, If I generate the client secret string "ABC" for example, then Hash256 or Hash512 the string and store it into Client Secret table. when I use both pre hashed or post hashed string is valid when I try to generate client credentials token for example.

**To Reproduce**

 Generate client credentials token using pre hashed or post hashed string, token success generated using both.

**Expected behavior**

only the pre hashed string should successfully validated when generating the client credentials token.

Whether I add .AddDefaultSecretValidator() in the AddIdentityServer or not, the result still same as described. Is this intended that the default secret validator for IdentityServer work this way and I have to create custom secret validator to only allow pre hashed string?

**Comment by josephdecock** [comment]
You should not be able to send a hash of a secret instead of the secret and have the validate. So far I'm not able to reproduce this issue in my own tests.

It is possible to have multiple secrets for a client (to facilitate rotation, etc). Maybe you have both "ABC" and its hash in the table of secrets? _Only hashes, not the plaintexts belong in the configuration._ Another possibility is that you have a custom secret validator.

**Comment by faridfpul** [comment]
is it because I set the secret type as SharedSecret?

**Comment by josephdecock** [comment]
No, that's the default, which means that you should have a hash in your database, and your client will authenticate with the plaintext of that hash.

**Comment by josephdecock** [comment]
Any update here? Can we close this issue?

**Comment by faridfpul** [comment]
hi @josephdecock, I found the rootcause which is as you suggested, there is custom secret validator used causing this issue.
I will close this ticket.
Thank you
