### ISSUE TITLE
How to properly configure operational store with signing keys in DB?

### ISSUE THREAD

**Issue by Toste591** [DuendeSoftware/Support#87]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0

**Describe the bug**
This is a question.

I've followed [the docs](https://docs.duendesoftware.com/identityserver/v5/data/ef/) to use the EF integration to store operational data in a database. It seemed to work fine, there are some keys in my database. However, there are still lots of keys that are old enough to be retired. When I try to connect to the Identity Server from a Client, I get exceptions like below. It seems to be unable to unprotect the old keys. I've provided the code I use to configure the operational data store in the additional context section.

The Identity Server also creates a folder "/Keys" with an IS Signing Key upon startup. This key is not in the database. This confuses me: I thought the local file system would no longer be used since I've configured a database as the operational store. Is this normal?

**To Reproduce**
* Use services.AddIdentityServer(...).AddOperationalStore(...) to configure a database as your operational data store
* Have keys in your database which are due to be unprotected
* Try to connect a client to your identity server

**Expected behavior**

I thought that calling AddOperationalStore and providing it with a database would be sufficient configuration to cause the app to store signing keys without relying on the local file system. I expected the old keys to automatically be unprotected successfully.

**Log output/exception with stacktrace**

```
[identity-server]Error unprotecting key with kid 035004ECFE1D4DEBD74F79348C82AD3D.
[identity-server]System.Security.Cryptography.CryptographicException: The key {10b72189-79f6-4327-b6e6-507d205a6026} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
[identity-server]   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
[identity-server]   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
[identity-server]   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
[identity-server]   at Duende.IdentityServer.Services.KeyManagement.DataProtectionKeyProtector.Unprotect(SerializedKey key) in /_/src/IdentityServer/Services/Default/KeyManagement/DataProtectionKeyProtector.cs:line 56
[identity-server]   at Duende.IdentityServer.Services.KeyManagement.KeyManager.<GetKeysFromStoreAsync>b__20_0(SerializedKey x) in /_/src/IdentityServer/Services/Default/KeyManagement/KeyManager.cs:line 426

```

**Additional context**

```
    public Startup(IWebHostEnvironment environment, IConfiguration configuration)
    {
        ...
        PersitedGrantDbBuilder =
            b => b.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
    }

    private void AddIdentityServer(IServiceCollection services, AppSettings appSettings)
    {
            ...
            services.AddIdentityServer(...)
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = PersitedGrantDbBuilder;
                options.EnableTokenCleanup = true;
            })
    }
```

**Comment by leastprivilege** [comment]
Hi 

IdentityServer v5 is not supported on .NET 6. Please upgrade before we can discuss any issues

https://duendesoftware.com/products/support

**Comment by Toste591** [comment]
I've updated to 6.1.0. Behavior is unchanged.

**Comment by leastprivilege** [comment]
Have you configured data protection?

**Comment by Toste591** [comment]
No, I thought setting up the persisted grant store would be enough. But I think I get it now: ASP.Net Core Data Protection is used by to protect IdentityServer's signing keys (using the data protection keys), correct? So my issues are coming from the lack of configuration there.

Thanks as usual for the quick replies, and sorry to bother you.

**Comment by leastprivilege** [comment]
> ASP.Net Core Data Protection is used to protect IdentityServer's signing keys

it is used to protect ASP.NET Core itself and is always required. We just happen to use it as well.
