### ISSUE TITLE
Change timezone for server-side sessions

### ISSUE THREAD

**Issue by baouchemaya** [DuendeSoftware/Support#874]
Hi ! :) 

I am currently using BFF and Server-side sessions. As I can store my session in my custom storage, I see that the timestamp for the created session is not accurate, as it is not the correct timezone (for me).

I cannot seem to find anything in the documentation about that. How could I customize the timezone, please ?

Thank you in advance

**Comment by josephdecock** [comment]
All of our timestamps are stored as UTC values, and our logic for handling times relies on that. For formatting and display of those times, you can use standard .NET facilities, such as [ConvertTimeFromUtc](https://learn.microsoft.com/en-us/dotnet/api/system.timezoneinfo.converttimefromutc?view=net-7.0).

**Comment by josephdecock** [comment]
Is anything further needed on this issue, or should we close it?
