### ISSUE TITLE
Question on logging

### ISSUE THREAD

**Issue by sudipster** [DuendeSoftware/Support#876]
**Which version of Duende IdentityServer are you using?**
6.2.3
**Which version of .NET are you using?**
6.0
**Describe the question**
I am using Azure AppInsights for logging at the moment. Is this recommended or anyone else using AppInsights for Ids? I have set RaiseInformationEvents & RaiseSuccessEvents to false and set Default LogLevel to Warning in order to reduce the volume of logging as Ids does log quite a bit. Please advise besides these are there any other steps that should be taken to reduce the volume of logging to AppInsights for Prod environment. Thanks.

**Comment by josephdecock** [comment]
We don't have a particular recommendation or requirement for how you consume and monitor your logs, but lots of our customers do use Azure AppInsights with IdentityServer.

Enabling only the events that are of interest, and setting the log level to warning sounds pretty typical of a production deployment. Our intent is to make the information in the more verbose log levels both to developers, and only log what is necessary in production. Please do let us know if some log messages are unclear or logged at an inconvenient level -thanks!

**Comment by sudipster** [comment]
Ok. Thanks Joseph!
