### ISSUE TITLE
Pass multiple query string parameters to return url during login workflow

### ISSUE THREAD

**Issue by xabikos** [DuendeSoftware/Support#882]
**Which version of Duende BFF are you using?**
2.0.0
**Which version of .NET are you using?**
7.0

**Describe the bug**

It's not a bug but rather a question about an approach and a possible change to how log in flow behaves. 

I am using the BFF approach with great success so far. We have an asp.net core that acts as the BFF and we are using next.js to create a static version of the website that is served from the asp.net application. As usual in the public web app we need to protect some routes, so the user needs to be authenticated before accessing them.

To make it concrete let's say we are visiting page `account/profile`.

Right now it's client-side responsibility to check if we have a session when visiting a protected route and if not to update browser's location with `bff/login` accoring to the [docs](https://docs.duendesoftware.com/identityserver/v5/bff/session/management/#login). 

Of course, once the user authenticates then we want to return to the page tried to access in this case `account/profile`. We can use the `returnUrl` query string parameter for this without a problem. 

The problem arises if we have multiple query string parameters when visiting this page. For example if for any reason we visit the url `account/profile?showdetails=true&promptToUpdatePersonalInfo=true&showWelcomeMessage=true` then after a successful login we end up in the following URL once redirect back `account/profile?showdetails=true` which means only the first query string parameter has been preserved.

After looking the code I found that [DefaultLoginService](https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/EndpointServices/Login/DefaultLoginService.cs) is responsible for that and most precisely this pice of [code ](https://github.com/DuendeSoftware/BFF/blob/main/src/Duende.Bff/EndpointServices/Login/DefaultLoginService.cs#L54)

```csharp
 var returnUrl = context.Request.Query[Constants.RequestParameters.ReturnUrl].FirstOrDefault();
```

Where we just retrieve the first query string parameter.

I produced a solution to this one by implementing a custom login service that only adds some functionality around this and solves the problem.

The code I added is 

```csharp
var returnUrl = context.Request.Query[Constants.RequestParameters.ReturnUrl].FirstOrDefault();

var additionalQueryParameters = context.Request.Query.Where(q => q.Key != Constants.RequestParameters.ReturnUrl);
if (!string.IsNullOrWhiteSpace(returnUrl) && additionalQueryParameters.Any())
{
    // create a query string with the additional parameters
    returnUrl = QueryHelpers.AddQueryString(returnUrl, additionalQueryParameters.ToDictionary(q => q.Key, q => q.Value.ToString()));
}
```

Here we retrieve the additional query string parameters if any, and if we have then we append them to the existing `returnUrl`.

It looks like this does the trick and produces a return URL like `account/profile?showdetails=true&promptToUpdatePersonalInfo=true&showWelcomeMessage=true` which is the desired.

**Additional context**

My main question now is whether there is a security risk around this I am missing or any other securitu concern. 

Then if we think this could be useful, I would be glad to open a PR to include in the next release.

**Comment by AndersAbel** [comment]
This works if you URL escape the return url parameter.

A request to `/bff/login?returnUrl=/page?p1=1&p2=2` will be treated as the `bff/login` endpoint getting two query string parameters, the first one, `returnUrl`, has the value of `/page?p1=1`. The `&` is treated as a delimiter for the next parameter, `p2`, with a value of `2`. The `/bff/login` only processes the first parameter.

You should Url escape the Url to make it be treated as one parameter: `/bff/login?returnUrl=%2Fpage%3Fp1%3D1%26p2%3D2`

**Comment by xabikos** [comment]
@AndersAbel thanks so much for the reply.

After I posted the question and made some more reading, I found out the solution you are suggesting but omitted to come here and add an additional comment. 

I won't delete the issue but rather close it in case someone else has the same question.
