### ISSUE TITLE
Prevent previous page navigation 

### ISSUE THREAD

**Issue by baouchemaya** [DuendeSoftware/Support#884]
Hi, 

I have a question on the sample provided for remote API call with BFF and I have noticed that when a user is logged in, he can go back to the login page. I am facing the same issue in my angular app and was wondering if there was a way of preventing previous page navigation if user was logged-in already. For instance, 

1. The user is not logged-in. 
![image](https://github.com/DuendeSoftware/Support/assets/118121801/9d9a4cbc-7bd3-42b7-a47c-90c188cecfc0)

2. User has clicked on login, then sets its credentials. 
![image](https://github.com/DuendeSoftware/Support/assets/118121801/e71a3e6c-ecb6-43a0-820f-3eba2f8a0611)

4. All good, logged-in. 
![image](https://github.com/DuendeSoftware/Support/assets/118121801/79b8ce0b-9930-4d9b-ad1a-1650cb9f2d2d)

5. I misclicked and came on the login page again. 
![image](https://github.com/DuendeSoftware/Support/assets/118121801/2ac08e91-bf6c-4cd7-bf99-503fc7ab183b)

so, my question is : how to prevent user to come back to login page and be redirected if authentified in general ? as the SPA is on localhost:7082 and Identity Server on demo.duendesoftware.com. It is the same for logout. 

Thank you in advance

**Comment by baouchemaya** [comment]
In the same context, I do have this error also while going back and authentified : 
![image](https://github.com/DuendeSoftware/Support/assets/118121801/c06ecd49-97fb-4428-9969-02c83a17872b)

**Comment by baouchemaya** [comment]
@AndersAbel do you have any clue, please ?

**Comment by josephdecock** [comment]
Sorry for the delay getting back to you @baouchemaya! 

In the most general case, there can be edge cases where the user might use their back button, or bookmark a page, and ultimately you might not be able to completely prevent the user from coming back to the login page. That said, you can make a best effort on your UI to prevent this sort of thing from happening. Your application can call the /bff/user endpoint when it starts up to get the current authentication status, and if the user is authenticated, hide the login buttons.

**Comment by baouchemaya** [comment]
Thank you very much for your answer @josephdecock ! I will try to implement a UI that prevent this from happenning. 

I have another question and I can create a new issue/question if needed : 

Continuing the workflow above (steps 1-4), I misclicked and came on the login page again, I enter (for a second time) my credentials and log-in. At this point, I was already logged-in and for the second login, I get this error  : 

![image](https://github.com/DuendeSoftware/Support/assets/118121801/b4bc1aab-c023-477c-8655-1c1631cccd67)

Any clue on this error, please ? or some explanation ? 

Thank you in advance

**Comment by AndersAbel** [comment]
The "correlation failed" error is raised by the OpenIdConnect handler in the client application. When an OIDC authentication is initiated, the client handler creates a cookie with some state. This cookie is then read and removed when the response from the OIDC provider is processed. This provides two security features. First it validates that the received response is from a valid request by using the information in the cookie. Second, the removal of the cookie prevents replay/reuse of the same state.

When you press back to get to the login page, the login page is based on the old state from the history. When an answer is posted using that state, the state cookie is already gone and "correlation failed".

You can catch this error and handle/suppress it in the `OnRemoteFailure` event.

**Comment by baouchemaya** [comment]
thanks for you answer ! 

I've tried this code to handle the event :        
         
```
options.Events = new OpenIdConnectEvents()
{
    OnRemoteFailure = async context =>
    {
        if (context.Failure?.Message == "Correlation failed")
        {
            if (context.HttpContext.User.Identity.IsAuthenticated)
            {
                var result = await context.HttpContext.AuthenticateAsync();
                var sessionId = result.Principal?.FindFirst(JwtClaimTypes.SessionId)?.Value;

                if (!string.IsNullOrWhiteSpace(sessionId))
                {
                    var encodedSessionId = UrlEncoder.Default.Encode(sessionId);
                    context.Response.Redirect($"/bff/logout?sid={encodedSessionId}");
                    context.HandleResponse();
                }
            }
            else
            {
                ...
            }
        }
        return;
    }
};
```
but the `sessionId `is null. Do you have any idea, as the ` result.Succedeed` is false ? Moreover, I feel like redirecting to the logout page is not the most user-friendly workflow. Do you have any other indications on this topic, maybe ? 

Thank you in advance

**Comment by AndersAbel** [comment]
I would guess that `context.HttpContext.User.Identity.IsAuthenticated` returns `false`. The reason is that the authentication middleware processes the callback to `/signing-oidc` before it populates the `HttpContext.User` property.

Please try rearranging the code to call `context.HttpContext.AuthenticateAsync()` first and use `result.Succeeded` instead of `context.HttpContext.User.Identity.IsAuthenticated`.

Redirecting to the logout endpoint is not the most user friendly, no. The case to consider from a security point of view is if a user tries to switch accounts by using the back button to go back to the login page. If they do that, they would have replaced their session on IdentityServer with the new user. When they get to the client application the change of users will fail due to correlation failure. The redirect to login is the smart thing to do then, because it causes another SSO roundtrip with the IdentityServer which picks up the current user identity from the new session on IdentityServer.

**Comment by AndersAbel** [comment]
Are there any more questions on this or can we go ahead and close the isseu?
