### ISSUE TITLE
How to Store Asp.Net Core Identity User Sessions in Redis

### ISSUE THREAD

**Issue by Jincoco88912** [DuendeSoftware/Support#885]
Starting Duende IdentityServer version 6.2.3+84bc142f65e28cf26ac3f96a70fe4722647acbc0 (.NET 6.0.16)

My application is already connected to Redis
and now I need to store the session state of users logged in through Asp.Net Core Identity in Redis.
Since we have two separate machines that may switch
we want to use Redis to ensure that users do not need to log in again.

![image](https://github.com/DuendeSoftware/Support/assets/62653054/df9efa0a-b901-4cb4-a869-d30eb6de843d)
![image](https://github.com/DuendeSoftware/Support/assets/62653054/0f8c05ad-41a6-493e-b92b-5616158ced8f)

**Comment by sudipster** [comment]
You can implement a DistributedCacheTicketStore that implements Microsoft.AspNetCore.Authentication.Cookies.ITicketStore. This would be a better abstraction that directly dealing with RedisCache. Then you can inject this ticketStore into CookieAuthenticationOptions.SessionStore.

**Comment by Jincoco88912** [comment]
@sudipster 

![image](https://github.com/DuendeSoftware/Support/assets/62653054/46885587-e16f-4966-9f9d-11fb690bdbc8)

Hi, after testing, my Redis connection appears to be working correctly. When I manually add a session, data is also being stored in Redis. However, I still can't see any signs of it being saved when an Identity User logs in. What else do I need to change? I'm still relatively new to this, so thank you for your help.

**Comment by sudipster** [comment]
Can you post/upload your code so I can see the issue in further detail?

**Comment by Jincoco88912** [comment]
Hi! @sudipster , I have already invited you to collaborate on my GitHub repository. I kindly request you to take some time to help me review the issues. Many thanks!

**Comment by AndersAbel** [comment]
Can we please take a step back here? I would like to understand what it is that you want to achieve.

The default in Asp.Net Core is to use an encrypted cookie to persist user sessions. In that model there is no server side storage at all. If you have multiple servers in a cluster, they must share the encryption keys to be able to read cookies regardless of which node in the cluster issued the cookie. This is done by [setting up data protection](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0) properly in your environment. If this is properly setup, there is no need to use server side storage even if you have multiple nodes in your cluster.

It is also possible to use a custom ticket store to store the session information. But it is not needed for session to work across clusters with multiple nodes. Using a custom ticket store will move the actual information into the custom store and the cookie will just contain an ID which references the row in the store. That smaller cookie is still encrypted using data protection, so data protection keys must still be properly configured.

Looking at the code shared, I see another issue with the configuration. The custom ticket store is configured for `CookieAuthenticationDefaults.AuthenticationScheme`. However, when using Asp.Net Identity that scheme is not what is used. There is a convenience extension method [`ConfigureApplicationCookie`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.identityservicecollectionextensions.configureapplicationcookie?view=aspnetcore-7.0) that you can use to configure the application cookie scheme used by Asp.Net Identity.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
