### ISSUE TITLE
Consider removing all query parameters during Authentication Code Flow redirection to Login Page or any page

### ISSUE THREAD

**Issue by cmyhill-justeat** [DuendeSoftware/Support#886]
During the Authentication Code Flow the IdentityServer framework directs requests to the customized login logic created by the host service using query parameters that are used to hold the return url or an authcode id either one can be used to get the authentication context.

This feature request is to remove all query parameters from the request between IdentityServer and the customized login logic or other custom pages and put an authorization token into a cookie secured by ASP Identity (or this could also be a plain cookie) which is used by the customized logic pages to return the authorization context for the current request removing the need for query parameters.

This feature enhancement would be intended more for use when the SPA Login pattern is being used to provide one of the two layers of security when using a BFF with IdentityServer, the other solution would be to use the Duende.BFF Middleware to check for Anti-forgery header in SPA requests.

Keen to get thoughts on this feature enhancement

**Comment by AndersAbel** [comment]
Before going into possible solutions, I would like to understand why the query string param with the return url is a problem? Why do you want it removed?

**Comment by cmyhill-justeat** [comment]
There is no problem in having the return url in the query string.  However when using a SPA interface for the Login pages and looking at ways to secure communication between the frontend to backend cookies have been a way to do this.  So I wondered if we had a cookie created at the start of the Authentication Code Flow the backend service could validate its existence and if we had a cookie it seems we could put the return url into that cookie and remove all query parameters.  So really there is no technical reason to move it more of an additional layer.  Which is why I was keen to see what other people thought to if this ideas was technically wrong or more unnecessary for most people and a nice to have?

**Comment by AndersAbel** [comment]
Moving the return url to a cookie has multiple implications. One is that it would create mixups/overwrites if a user would have multiple windows/tabs open on the same time. Another is that if a user could be tricked into opening the login page, that would pick up values from the cookie that could have been created on another request.

Moving the state/return url to a cookie would have to be carefully evaluated from a security and usability perspective. As long as it isn't a concrete problem to have the return url as a query string parameter it's easiest to keep it that way.

**Comment by cmyhill-justeat** [comment]
Thanks for the information, there are definitely some scenarios I had not thought about

**Comment by brockallen** [comment]
Additionally, if the client is a native/mobile app, then when using the AppAuth workflow the user might request launching the browser in the full browser and then the cookie would not survive across that browsing context. IdentityServer3 used to use a cookie as the OP has requested, and that prevented the native/mobile login workflow, as well as the many issues that @AndersAbel mentions. This is why we reworked all the state from the request to be maintained in the URL (rather than an ambient cookie). 

HTH
