### ISSUE TITLE
Invalid_client error after callback from external oauth provider

### ISSUE THREAD

**Issue by danpette** [DuendeSoftware/Support#889]
**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer 6.3.4
Duende.IdentityServer.EntityFramework 6.3.4

The client is using bff: Duende.BFF 2.1.1, Duende.BFF.EntityFramework 2.1.1 and Duende.BFF.Yarp 2.1.1 (but have "confirmed" by doing HttpLogging on the lowest level possible that the client is never hit, so i would assume the problem occurs in identityserver and not against any calls to the client)

**Which version of .NET are you using?**
6.0

**Describe the bug**

I'm trying to setup auth against a external oauth provider (an example is norwegian government login: id-porten)

using this guide: https://docs.duendesoftware.com/identityserver/v6/ui/login/external/

In identityserver i have added: services.AddAuthentication().AddOpenIdConnect("oidc", "ID-porten") with these options:
SignInScheme: IdentityServerConstants.ExternalCookieAuthenticationScheme
ResponseType: code
ResponseMode: query
UsePkce: true
CallbackPath: "/signin-oidc-idporten";
SignedOutCallbackPath: "/signout-callback-idporten";
RemoteSignOutPath: "/logout-idporten";

UsePkce is required by the target oauth provider.

Everything works until idporten redirects back to my identityserver:

```
Error Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler Message contains error: '"invalid_client"', error_description: '"Invalid client: Possible causes may be 1) missing / invalid client_id; 2) missing client authentication; 3) invalid or expired client secret; 4) invalid or expired JWT authentication; 5) invalid or expired client X.509 certificate; 6) an unexpected client authentication method"', error_uri: '"error_uri is null"', status code '401'.
--
12/9/2023 08:31:16 | 2023-09-12 06:31:15 Error Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler Exception occurred while processing message. Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid client: Possible causes may be 1) missing / invalid client_id; 2) missing client authentication; 3) invalid or expired client secret; 4) invalid or expired JWT authentication; 5) invalid or expired client X.509 certificate; 6) an unexpected client authentication method', error_uri: 'error_uri is null'.
```

And it fires on the On RemoteFailure event (i have logging on all available OpenIdConnectEvents):

`options.Events = new OpenIdConnectEvents {
                    OnRemoteFailure = context => { /* Console.WriteLine Exception, Request and Response */ }};`

And the events http context has this info:

```
12/9/2023 08:31:16 |  FAILURE
12/9/2023 09:31:55 | Message contains error: 'invalid_client', error_description: 'Invalid client: Possible causes may be 1) missing / invalid client_id; 2) missing client authentication; 3) invalid or expired client secret; 4) invalid or expired JWT authentication; 5) invalid or expired client X.509 certificate; 6) an unexpected client authentication method', error_uri: 'error_uri is null'.
12/9/2023 09:31:55 | Microsoft.AspNetCore.Authentication.OpenIdConnect

12/9/2023 08:31:16 |  REQUEST
12/9/2023 08:31:16 | GET
12/9/2023 08:31:16 | https
12/9/2023 08:31:16 | oauth.mydomain.no
12/9/2023 08:31:16 | /signin-oidc-idporten
12/9/2023 08:31:16 | {"code":["xxx"],"iss":["https://test.idporten.no"],"state":["xxxxxxxx"]}
12/9/2023 08:31:16 | Body is empty
12/9/2023 08:31:16 |  
12/9/2023 08:31:16 | RESPONSE:
12/9/2023 08:31:16 | 200 (HttpStatusCode)
12/9/2023 08:31:16 | Body is empty
12/9/2023 08:31:16 | {"Set-Cookie":[".AspNetCore.Correlation.AA-XXXX_YYYY_BBB=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/signin-oidc-idporten; secure; samesite=none; httponly"],"X-XSS-Protection":["1; mode=block"]}>
```

So i tried to keep this simple, as it's a lot of config values and so one, please tell me what more info needed and i will provide.
Would be very grateful for any info om how i can continue investigate and get more information. Can i get any more info then invalid_client and status code '401' in the first error message (from dudende, not the exception object in the event)?

Se also section Log output/exception with stacktrace aboy source "FederatedSignOut", im i getting a 401 from the "remote logout (https://docs.duendesoftware.com/identityserver/v6/ui/login/external/#establish-session-clean-up-and-resume-workflow)?

**To Reproduce**

n/a

**Expected behavior**

Any of the other successful events should be called.

**Log output/exception with stacktrace**

```
2023-09-12 08:19:45 Error Microsoft.AspNetCore.Server.Kestrel Connection id ""0HMTJD3OUFB3E"", Request id ""0HMTJD3OUFB3E:00000002"": An unhandled exception was thrown by the application. Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid client: Possible causes may be 1) missing / invalid client_id; 2) missing client authentication; 3) invalid or expired client secret; 4) invalid or expired JWT authentication; 5) invalid or expired client X.509 certificate; 6) an unexpected client authentication method', error_uri: 'error_uri is null'.
--
12/9/2023 10:19:45 | at Global.IdentityServer.Startup.<>c.<<ConfigureServices>b__4_19>d.MoveNext()
12/9/2023 10:19:45 | --- End of stack trace from previous location ---
12/9/2023 10:19:45 | at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
12/9/2023 10:19:45 | at Duende.IdentityServer.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() in /_/src/IdentityServer/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs:line 38
12/9/2023 10:19:45 | at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
12/9/2023 10:19:45 | at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 50
12/9/2023 10:19:45 | at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 27
12/9/2023 10:19:45 | at Global.IdentityServer.Startup.<>c.<<Configure>b__5_1>d.MoveNext()
12/9/2023 10:19:45 | --- End of stack trace from previous location ---
12/9/2023 10:19:45 | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Additional context**

n/a

**Comment by AndersAbel** [comment]
The request is successfully sent to the provider, which then rejects it. OpenID Connect Providers usually do not provide details of the error in the response. The error description just sends a list of possible errors, the exact reason is probably logged on the provider side. To validate the configuration required, you need to contact the provider (Id-Porten) and ask about the correct parameters to use, as well as more information from their logs on why the request is rejected.

The `FederatedSignout` authentication request wrapper is part of the IdentityServer infrastructure for federated sign out. It is a wrapper that forwards the requests to the actual handler, in this case the OpenIdConnectHandler (which is dervied from RemoteAuthenticationHandler, hence `RemoteAuthenticationHAndler`1.HandleRequestAsync()` in the trace). The presens of that handler in the stack trace is not related to the error returned from the OIDC Provider.

**Comment by danpette** [comment]
Thanks for the reply, after some back and forth we figured out that they only check for the auth type defined in their gui.

som changing it from client_secret_basic  to client_secret_post fixed the issue.

I also found a solution/fix/hack when using client_secret_basic  in idporten:

```
options.Events.OnAuthorizationCodeReceived = context =>
{
    context.Backchannel.SetBasicAuthenticationOAuth(context.TokenEndpointRequest.ClientId, context.TokenEndpointRequest.ClientSecret);
    return Task.CompletedTask;
};
```
