### ISSUE TITLE
Redirect to /bff/login results in to a 404 page

### ISSUE THREAD

**Issue by danielpastoor** [DuendeSoftware/Support#89]
When I use the Bff package on multiple  azure App services with a diffrent subdomain but the same domein. Then there seems to be a error when starting up BFF resolving to the redirect of a 404 page.

<img width="125" alt="image" src="https://user-images.githubusercontent.com/28786031/173370360-77192d8e-3549-4f3a-8aed-1f7585a36f0d.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/28786031/173370752-df47d326-4f3f-4f84-befa-f398fd70bb9b.png">

I'm using Bff in a Wasm project with Identityserver
Bff: 1.2.1
IdentityServer: 6.1.0

**Comment by brockallen** [comment]
Any update @danielpastoor?

**Comment by danielpastoor** [comment]
I have tested the project for the last couple of days and the update was indeed the fix for the bug.

**Comment by brockallen** [comment]
Excellent news. Thanks for following up.
