### ISSUE TITLE
Integration Tests for authenticated user.

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#890]
Hi, 
I'm trying to run some integration tests for my app (RazorPages) that uses Duende.IndentityServer. What I would like to be able to test is accessing protected pages and seeing if the features within them work correctly. In my tests I'm trying to use a fake AuthenticationHandler that simulates a logged user, the problem is that I always get this message and therefore I can't proceed with the test:

> Authentication scheme Test is configured for IdentityServer, but it is not a scheme that supports signin (like cookies). If you support interactive logins via the browser, then a cookie-based scheme should be used.

My test configuration is:

```
[Collection("IAM")]
public class ProfileTests
{
    private readonly HttpClient _client;

    public ProfileTests(CustomWebApplicationFactory<Program> factory)
    {
        _client = factory.WithWebHostBuilder(builder =>
            {
                builder.ConfigureTestServices(services =>
                {
                    services.AddAuthentication(options =>
                        {
                            options.DefaultScheme = FakeAuthenticationHandler.AuthenticationSchema;
                            options.DefaultSignInScheme = FakeAuthenticationHandler.AuthenticationSchema;
                            options.DefaultAuthenticateScheme = FakeAuthenticationHandler.AuthenticationSchema;
                        })
                        .AddScheme<FakeAuthenticationSchemaOptions, FakeAuthenticationHandler>(FakeAuthenticationHandler.AuthenticationSchema,
                            options =>
                            {
                                options.User = Users.Default();
                            });

                });
            })
            .CreateClient();

        _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(FakeAuthenticationHandler.AuthenticationSchema);
    }
}
```

Is there a way to fix this?

> For testing I'm using:
> XUnit
> Microsoft.AspNetCore.Mvc.Testing
> AngleSharp

**Comment by pampua84** [comment]
Hi, thanks for reply. 
This suggestion remove the WRN log i mentioned above, but it seems like IdentityServer uses always CookieAuthenticationHandler with the Identity,Application schema instead of mine. So i have always this log:

> [11:16:45 INF] Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user. <s1:Microsoft.AspNetCore.Authorization.DefaultAuthorizationService> 0HMTL0D7525Q5
[11:16:45 INF] AuthenticationScheme: Identity.Application was forbidden. <s1:Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler>

I don't know how to solve this situation. Please healp me. Thansk

**Comment by AndersAbel** [comment]
What endpoint was invoked when you got that error?

**Comment by pampua84** [comment]
I'm simply trying to enter a protected page of my application, the profile page, no OpenId/Oauth2 flow is involved for this thing

**Comment by AndersAbel** [comment]
So it's your own page, not an IdentityServer endpoint?
What does the authorization configuration look like for that endpoint? It looks like it references the Identity.Application scheme instead of the configured default scheme.

**Comment by pampua84** [comment]
The problem is that this code is used within IdentityServer:

```
public static IIdentityServerBuilder AddDefaultCookieHandlers(this IIdentityServerBuilder builder)
{
    builder.Services.AddAuthentication(IdentityServerConstants.DefaultCookieAuthenticationScheme)
        .AddCookie(IdentityServerConstants.DefaultCookieAuthenticationScheme)
        .AddCookie(IdentityServerConstants.ExternalCookieAuthenticationScheme);
    builder.Services.AddSingleton<IConfigureOptions<CookieAuthenticationOptions>, ConfigureInternalCookieOptions>();

    return builder;
}

/// <summary>
/// Adds the necessary decorators for cookie authentication required by IdentityServer
/// </summary>
/// <param name="builder">The builder.</param>
/// <returns></returns>
public static IIdentityServerBuilder AddCookieAuthenticationExtensions(this IIdentityServerBuilder builder)
{
    builder.Services.AddSingleton<IPostConfigureOptions<CookieAuthenticationOptions>, PostConfigureInternalCookieOptions>();
    builder.Services.AddTransientDecorator<IAuthenticationService, IdentityServerAuthenticationService>();
    builder.Services.AddTransientDecorator<IAuthenticationHandlerProvider, FederatedSignoutAuthenticationHandlerProvider>();

    return builder;
}
```

and therefore that schema is used.

**Comment by pampua84** [comment]
Sorry, in the end I managed to solve the problem which was caused by the fact that I had not specified the AuthenticationType when creating the ClaimsIdentity object. Sorry again

**Comment by AndersAbel** [comment]
Happy to hear you solved it. Not specifying any `AuthenticationType` on `ClaimsIdentity` causes `IsAuthenticated` to return false. It's not an obvious behaviour and you are definitely not the first (nor the last) to be surprised by it.
