### ISSUE TITLE
`GetErrorContextAsync`: How to pass that "errorId" to the error page?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#891]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
.Net Core 7
**Describe the bug**
https://docs.duendesoftware.com/identityserver/v5/reference/services/interaction_service/
```
GetErrorContextAsync
Returns the ErrorMessage based on the errorId passed to the error page.
```
(1) How to pass that "errorId" to the error page?
(2) Is the errorId fixed somewhere? Where to look it up? Any possibility of customizing it?

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AndersAbel** [comment]
The error Id is a reference to a stored ErrorMessage. When an error occurs in IdentityServer that should result in an error message being displayed to the user, the error message is created and saved to `IMessageStore<ErrorMessage>`. The resulting handle is the error id. IdentityServer then redirects to the configured error page and attaches the error id. The error page can use the interaction service to get the error message back for display.

The default implementation of the `IMessageStore<ErrorMessage>` stores the entire message within the id itself - that is why the Id gets so large.

If you want to redirect to the error page from your own code and attach an error message, you can create the errorid by calling `IMessageStore<ErrorMessage>.WriteAsync()`.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
