### ISSUE TITLE
IDX10503: Signature validation failed. Token does not have a kid

### ISSUE THREAD

**Issue by HStumpf** [DuendeSoftware/Support#894]
**Which version of Duende IdentityServer are you using?**
6.2.0
**Which version of .NET are you using?**
.net 6
**Describe the bug**
The error occurs during API runtime - as described below.
The server has been running for 4 weeks, the IIS App Pool is restarted every 4 hours
- There were no Windows updates during the time
- There were no network interruptions (e.g. to the database) during this time.
- The certificate has not expired

After a restart of the server, the token validation works again.

**Log output/exception with stacktrace**

{
    "Timestamp": "2023-09-13T08:01:40.5991873+00:00",
    "Level": "Error",
    "MessageTemplate": "JWT token validation error: {exception}",
    "Exception": "Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10503: Signature validation failed. Token does not have a kid. Keys tried: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Number of keys in TokenValidationParameters: '2'. \nNumber of keys in Configuration: '0'. \nExceptions caught:\n '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.\ntoken: '[PII of type 'Microsoft.IdentityModel.JsonWebTokens.JsonWebToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10503 for details.\r\n   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignature(JsonWebToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)\r\n   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateSignatureAndIssuerSecurityKey(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)\r\n   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateJWSAsync(JsonWebToken jsonWebToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)",
    "Properties": {
        "exception": "IDX10503: Signature validation failed. Token does not have a kid. Keys tried: '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. Number of keys in TokenValidationParameters: '2'. \nNumber of keys in Configuration: '0'. \nExceptions caught:\n '[PII of type 'System.Text.StringBuilder' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.\ntoken: '[PII of type 'Microsoft.IdentityModel.JsonWebTokens.JsonWebToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. See https://aka.ms/IDX10503 for details.",
        "SourceContext": "Duende.IdentityServer.Validation.TokenValidator",
        "RequestId": "80000f32-0002-e500-b63f-84710c7967bb",
        "RequestPath": "/connect/userinfo",
        "EC2-Instance": "i-xyz"
    }
}

**Comment by josephdecock** [comment]
This error means that when the API tried to validate a JWT access token, it failed to do so, because the API didn't know about the key that was used to sign the JWT.

APIs will periodically (on the order of daily) retrieve the signing keys that identity server is signing tokens with and cache them. So this error means that that cached data didn't contain your signing key.

The most common way for that to happen is if you have a data protection problem in your identity server. We've recently updated our docs on signing keys and data protection keys [here](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/). Since you mention that you are restarting your IIS frequently, I recommend that you take a look at your data protection configuration, specifically with how it relates to IIS configuration. As we say in the docs I just linked to:

> If your IdentityServer is hosted by IIS, special configuration is needed for data protection. In most default deployments, IIS lacks the permissions required to persist data protection keys, and falls back to using an ephemeral key generated every time the site starts up. Microsoft’s docs on this issue are [here](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0#data-protection).

**Comment by HStumpf** [comment]
Hello,

i check our data protrection and and write the results here

Regards
Horst-Dieter

**Comment by HStumpf** [comment]
Hello,

i check the links and change the source to get the token signing key.

Regards
Horst-Dieter

**Comment by qadeemExelia** [comment]
I am facing the same issue, it solved for some time when I restart my azure app service but then It comes back from no where.
`IDX10517: Signature validation failed. The token's kid is missing. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: `
can you please tell mw how  you got this fixed ?

**Comment by AndersAbel** [comment]
@qadeemExelia This is an old issue and although the issue looks the same it might be something completely different on current versions of Asp.NET Core and .NET. Please open a new issue.
