### ISSUE TITLE
Run Duende identity server using docker

### ISSUE THREAD

**Issue by sheenamnagarro** [DuendeSoftware/Support#896]
**Which version of .NET are you using?**
6.0
**Describe the bug**
I am able to build docker image of duende identity server successfully. When i run the container, using the image, in logs i can see that app is listening on port 80 but  I am not able to see this from my localhost 

Here is my docker file :
# Use the official ASP.NET Core runtime as a parent image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
 

# Use the official ASP.NET Core SDK as a parent image for building
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["YourProject/YourProject.csproj", "YourProject/"]
RUN dotnet restore "YourProject/YourProject.csproj"
COPY . .
WORKDIR "/src/YourProject"
RUN dotnet build "YourProject.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "YourProject.csproj" -c Release -o /app/publish

# Set up the final image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "YourProject.dll"]

In identity server's code, in launch setttings, i have given the port 80 only.
Kindly help if I am missing something

**Comment by josephdecock** [comment]
@sheenamnagarro did you mean to close this issue? Do you still need anything?

**Comment by IKoshelev** [comment]
I seem to have the same problem, but with port 5001 - when I run Duende identity server in container, container listens, but I can't access it from host.
