### ISSUE TITLE
Unable to signout of both the external provider and local idp

### ISSUE THREAD

**Issue by forrestab** [DuendeSoftware/Support#900]
**Which version of Duende IdentityServer are you using?**
6.1.5

**Which version of .NET are you using?**
net6

**Question**

Im running into and issue dealing with signout and I feel its a configuration problem, but Im not sure. Im able to either logout of Okta or the local idp, but not both.

I found this [issue](https://github.com/DuendeSoftware/Support/issues/836) and looked it over, but I wasnt able to make heads or tails of what Im doing wrong.

In case it helps I believe we based our idp off of this [IdentityServer template](https://github.com/DuendeSoftware/IdentityServer.Templates/tree/main/src/IdentityServerInMem), but replaced the in memory code with our db implementations.

Below is how Im configuring Okta (Im using their [Okta.AspNetCore](https://github.com/okta/okta-aspnet/tree/master/Okta.AspNetCore) package):

```csharp
builder.Services
    .AddAuthentication()
    .AddOktaMvc("Okta", new OktaMvcOptions
    {
        OktaDomain = "https://<...>.okta.com",
	ClientId = "<id>",
	ClientSecret = "<secret>",
	CallbackPath = "/signin-okta"
    });
```

The extension provided by Okta does not provide access to the `OpenIdConnectionOptions.*Scheme` properties, so Ive tried the following ways of configuring them:

#### 1. Setting them globally via as defaults.

```csharp
builder.Services
    .AddAuthentication(options =>
    {
        options.DefaultSignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
	options.DefaultSignOutScheme = "Okta";
    })
    // <snip>
```

With this option, it logs the user out of Okta, but not the local idp. I see the redirect to **LoggedOut.cshtml** and it auto-redirects to the app as the authenticated user. Ive verified the log out from Okta by trying to access Okta directly and it requires a login.

#### 2. Setting them via the `PostConfigure` targetting the named options.

```csharp
builder.Services.PostConfigure<OpenIdConnectOptions>("Okta", options =>
{
    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    options.SignOutScheme = "Okta";
});

// <snip>
```

With this option, it logs the user out of the local idp, but not Okta. The user is redirected to the login page of the app, but clicking on the Okta external provider button automatically logs the user back in.

Ive not used either of these options together.

**Comment by josephdecock** [comment]
It sounds like you need to pass both the "Okta" and the `IdentityServerConstants.DefaultCookieAuthenticationScheme` schemes when you call SignOut.

**Comment by forrestab** [comment]
Earlier today I was finally able to get both the local idp and okta logged out and it was thanks to this [github issue](https://github.com/IdentityServer/IdentityServer4/issues/2283#issuecomment-386413273). Though Im not sure its the most appropriate way to go about it, I still feel like Im doing something wrong.

It looks like the reason okta doesn't sign the user out is because the `id_token_hint` isn't passed when trying to end its session. After adding the query parameter via the `OpenIdConnectEvents.OnRedirectToIdentityProviderForSignOut` everything worked as expected.

I did try out your suggestion of passing both schemes to `SignOut` and none of the ways I tried seemed to work for okta (in each scenario okta returned a 400, unfortunately there were no logs, but I noticed the `id_token_hint` was not found in the request url again). Below are the different ways I tried:

### Pass 1

In `Logout.Index.OnPost`,

```csharp
// snip
await HttpContext.SignOutAsync(IdentityServerConstants.DefaultCookieAuthenticationScheme);
// snip -> forward signout to external provider
```

### Pass 2

Again in `Logout.Index.OnPost` (without the changes from Pass 1),

```csharp
// snip
if (await HttpContext.GetSchemeSupportsSignOutAsync(idp))
{
    // snip
    return SignOut(new AuthenticationProperties { RedirectUri = url }, idp, IdentityServerConstants.DefaultCookieAuthenticationScheme);
}
```

### Pass 3

Lastly, excluding the changes above I just set the `DefaultSignOutScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme` in the `AddAuthentication` extension method.

Just to note, everything was tested in our identity server project.

**Comment by josephdecock** [comment]
If you call sign out with both schemes as you do in pass 2, that should both clear your cookie and send the end session request to okta.

But, when the oidc handler tries to send the id token as part, it will look for it in the session specified by the SignOutScheme you have configured on your Okta handler. You need that scheme to be the main cookie authentication scheme, because that is where the id token is stored.

```
builder.Services.PostConfigure<OpenIdConnectOptions>("Okta", options =>
{
    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    options.SignOutScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme; // <--- This is the change you need
});
```

**Comment by forrestab** [comment]
It worked, thank you and Im sorry, I definitely read the [Ending the Session](https://docs.duendesoftware.com/identityserver/v6/ui/logout/session_cleanup/#external-logins) doc, but it didn't click that I needed to specify both schemes in the `SignOut`.

Just so I understand, since Im using the signin callback method, I would more than likely always set `IdentityServerConstants.DefaultCookieAuthenticationScheme` for an external provider (assuming they support logout). Does it make sense to set the `DefaultSignOutScheme` to the above scheme? This way other external provider configuration only has to be configured for signin.

**Comment by josephdecock** [comment]
Yeah, there's more than one way to do it, because there are progressively granular options controlling which scheme is used.

When you sign out of the "okta" scheme it will use its SignOutScheme to find your id token hint, and also automatically sign out of that scheme. The sign out scheme of the handler defaults to using the same scheme as the sign in scheme of the handler, which falls back to using the authentication service's DefaultSignInScheme, which can ultimately fall back to the service's DefaultScheme. Phew!

**Comment by forrestab** [comment]
Thank you for explaining that and really appreciate all of the help you all provide!
