### ISSUE TITLE
MFA Support using Identity Server

### ISSUE THREAD

**Issue by Sdumaniya** [DuendeSoftware/Support#904]
**Which version of Duende IdentityServer are you using?**
Iderntity Server 6

**Which version of .NET are you using?**
.NET 6

**Describe the bug**
Can you please provide the documentation for how to support MFA using Identity server and can you please provide sample project for it and also Please share below information? 

1) how to redirect when MFA needed
2) how to generate OTP using Identity server.

**Comment by josephdecock** [comment]
IdentityServer doesn't implement MFA. When we detect that the user needs to be shown an interactive page, we redirect to your customizable UI page, which is responsible for authenticating the user and starting a session, however you see fit. One approach that you might take is to use use ASP.NET Identity to implement MFA, and use that in your IdentityServer implementation. See microsoft's docs [here](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-7.0) for more details.
