### ISSUE TITLE
Data protection certificate rotation

### ISSUE THREAD

**Issue by haris-begluk** [DuendeSoftware/Support#906]
**Which version of Duende IdentityServer are you using?**
Duende.IdentityServer.AspNetIdentity" Version="6.1.5"
Duende.IdentityServer.EntityFramework" Version="6.1.5"
.net6

At the moment, I have data protection configured and protected with a certificate, using it as shown in the example below. 
Assuming that the rest of the configuration is set to default values.
```
services.AddDataProtection()
  .SetApplicationName(Environment.ApplicationName)
  .SetDefaultKeyLifetime(TimeSpan.FromDays(DataProtectionKeyLifetimeDays))
  .PersistKeysToDbContext<DataProtectionDbContext>()
  .ProtectKeysWithCertificate(cert)
  .UseCryptographicAlgorithms(
        new AuthenticatedEncryptorConfiguration 
        {
            EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
            ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
        });
```

I want to configure automatic certificate rotation, but I am not sure about the potential impact on the existing protected data.
I kindly ask if you can explain the best practices for rotating a certificate used for data protection. 
Is there any documentation that explains this use case?

 I want to avoid errors like the ones below.

```
Failed to deserialize JSON from grant store.
System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
Duende.IdentityServer.Stores.DefaultGrantStore`1.GetItemByHashedKeyAsync(String hashedKey) 

An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
```
Thank you in advance for the response and the time spent.

**To Reproduce**

1. Use data protection configured like in example (certificate A)
2. Than rotate certificate to (certificate B is used) 
3. New data protection key should be generated. (guess this will cause some issues) 

**Expected behavior**
Smooth certificate rotation without a huge impact on the current sessions and protected values.

**Additional context**
The errors in the example are from my test environment. 
Endpoints
 /Account/Login
/connect/token

**Comment by josephdecock** [comment]
You can use the UnprotectKeysWithAnyCertificate method to tell data protection about old certificates after you rotate.

**Comment by josephdecock** [comment]
So, to rotate, you move the current certificate from the ProtectKeysWithCertificate to the collection passed to UnprotectKeysWithAnyCertificate, and add a new cert to ProtectKeysWithCertificate.

**Comment by haris-begluk** [comment]
I assume I need to perform a redeploy because I currently don't have 'UnprotectKeysWithAnyCertificate' configured? 

I'm interested in what happens when we initially configure the identity server and add configuration for 'UnprotectKeysWithAnyCertificate,' but in this case, we don't have a certificate, i.e., there hasn't been any rotation. Is this expected behavior? 
Thanks for the quick response.
