### ISSUE TITLE
auth_req_id length doesn't conform to spec requirements?

### ISSUE THREAD

**Issue by FinHorsley** [DuendeSoftware/Support#91]
**Which version of Duende IdentityServer are you using?**
6.1.0

**Which version of .NET are you using?**
6.0.300

**Describe the bug**
Reading through the ciba openid spec ([here](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html)), it looks like the auth_req_id is required to be a minimum of 120 characters, with 160 being recommended. However the auth_req_id generated by identityServer is 66 characters (e.g. `35FE09C54B5D29B230B1705AE9CA5235EF02786D81B4258B6697ECD87D17306C-1`).

Bit of an aside too, does duende idsrv do anything special with the auth_req_id (e.g. 'binding' the token to the idsrv private key), or is it just a string comparison (trusting that the id has sufficient entropy not to be bruteforced)?

Apologies in advance if i've missed something here!

> It MUST contain sufficient entropy (a minimum of 128 bits while 160 bits is recommended) to make brute force guessing or forgery of a valid auth_req_id computationally infeasible - the means of achieving this are implementation-specific, with possible approaches including secure pseudorandom number generation or cryptographically secured self-contained tokens.

**Comment by leastprivilege** [comment]
The number of characters and the bytes are two different things.

We use 32 bytes for the handle (256 bits).

https://youtu.be/S9JGmA5_unY ;)

**Comment by FinHorsley** [comment]
Ah! thanks, seems obvious now :)
