### ISSUE TITLE
PAT: Scopes based on user

### ISSUE THREAD

**Issue by pampua84** [DuendeSoftware/Support#910]
Hi, 
I have a question about PAT, I would like to get a PAT with scopes based on the logged-in user, rather than on the client; do you think it is possible to use custom tables on the db to associate the user with the scopes, and then filter the client’s scopes based on the user? 
I ask you this because I would like to give my users the possibility to obtain access tokens to be able to call APIs, and therefore depending on the user who logs in, show in the PAT page (as in your example) the scopes for which they can request the token.
I hope I was clear.

**Comment by AndersAbel** [comment]
Yes, that is possible. The PAT generation in our [sample](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/PAT) is a custom page and the scopes that are made available to the PAT are handled by the code in that page. You could use any business logic you have, including database access, to decide what scopes should be available for the PAT.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?

**Comment by pampua84** [comment]
No not at the moment. He apologizes for the delay and thank you very much.
