### ISSUE TITLE
/bff/user Endpoint Returning 401 When Calling From Client App

### ISSUE THREAD

**Issue by mitchescapeplan** [DuendeSoftware/Support#911]
Duende.BFF 2.1.1
Duende.BFF.Yarp 2.1.1
.NET 6.0

I'm adding BFF into an existing project that's already utilizing Identity Server that we've set up as an identity provider.  Our React client app, APIs, and Identity Server are hosted on sub sites of the same domain. So I've spun up the BFF app on its own, following how the Split Hosts sample from that Github repository is set up.

Hosts in development:
Client App: https://localhost:3000
BFF App: https://localhost:7050

For the time being I just have a static page in my client app with a "login" and "user" button to call the `/bff/login` and `/bff/user` endpoints on the BFF App. The login works fine, and I'm providing a returnUrl in the call (`https://localhost:7050/bff/login?returnUrl=https://localhost:3000/login`), and the BFF cookies are being returned to the client app. But when the user endpoint is initiated from the client app, it's returning with a 401 response. If I navigate to it directly in the browser, it displays all of the user information.

Nothing seems to be happening in the BFF console logs. Is there something that I'm missing with my setup? Please let me know if there's anything else I can provide to help diagnose where I'm going wrong with the setup.

IS client:
```
{
    ClientId = "testBff",
    ClientName = "Test BFF",
    ProtocolType = "oidc",
    RequireClientSecret = true,
    AllowRememberConsent = true,
    AlwaysIncludeUserClaimsInIdToken = true,
    RequirePkce = true,
    AllowAccessTokensViaBrowser = true,
    FrontChannelLogoutSessionRequired = true,
    AllowOfflineAccess = true,
    AllowedGrantTypes = GrantTypes.Code,
    ClientSecrets = { new Secret("testbff".Sha256()) },
    RedirectUris = { "http://localhost:3000/signin-oidc", "https://localhost:7050/signin-oidc" },
    AllowedCorsOrigins = { "http://localhost:3000", "https://localhost:7050" },
    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        IdentityServerConstants.StandardScopes.OfflineAccess,
        "employeemaster_api",
        "clientmaster_api",
    }
}
```
BFF Program.cs
```
using Duende.Bff;
using Duende.Bff.Yarp;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddBff().AddRemoteApis();

builder.Services.AddAuthentication(options =>
{
    options.DefaultScheme = "cookie";
    options.DefaultChallengeScheme = "oidc";
    options.DefaultSignOutScheme = "oidc";
})
.AddCookie("cookie", options =>
{
    options.Cookie.Name = "__Host-bff";
    options.Cookie.SameSite = SameSiteMode.Strict;
})
.AddOpenIdConnect("oidc", options =>
{
    options.Authority = config.Authority;
    options.ClientId = config.ClientId;
    options.ClientSecret = config.ClientSecret;

    options.ResponseType = "code";
    options.ResponseMode = "query";

    options.GetClaimsFromUserInfoEndpoint = true;
    options.MapInboundClaims = false;
    options.SaveTokens = true;

    options.Scope.Clear();
    foreach (var scope in config.Scopes)
    {
        options.Scope.Add(scope);
    }

    options.TokenValidationParameters = new()
    {
        NameClaimType = "name",
        RoleClaimType = "role"
    };
});

var app = builder.Build();

app.UseDefaultFiles();
app.UseStaticFiles();

app.UseAuthentication();
app.UseBff();

app.MapBffManagementEndpoints();

if (config.Apis.Any())
{
    foreach (var api in config.Apis)
    {
        app.MapRemoteBffApiEndpoint(api.LocalPath, api.RemoteUrl!)
            .RequireAccessToken(api.RequiredToken);
    }
}

app.Run();
```
BFF appsettings.json
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "BFF": {
    "Authority": "https://auth.companyname.com",
    "ClientId": "testBff",
    "ClientSecret": "testSecret",

    "Scopes": [ "openid", "profile", "employeemaster_api", "clientmaster_api", "offline_access" ],

    "Apis": [
      {
        "LocalPath": "/API-CM",
        "RemoteUrl": "http://localhost:5001/API-CM/,
        "RequiredToken": "User"
      },
      {
        "LocalPath": "/API-EM",
        "RemoteUrl": "http://localhost:6001/API-EM",
        "RequiredToken": "User"
      }
    ]
  }
}
```
Client App:
```
const Config = {
  headers: {
     'Access-Control-Allow-Origin': '*',
     'Access-Control-Allow-Credentials': 'true',
     'x-csrf': '1',
  },
};

public getUser = async () => {
  const user = axios.create({ baseURL: "https://localhost:7050/" })
                       .get<any>("bff/user", Config);
  return user;
}
```

**Comment by AndersAbel** [comment]
Looking through the code and config provided I don't spot the problem immediately.

Can you please provide a screen dump of the headers from the browser dev tools where the failed request to /bff/user is shown?

**Comment by AndersAbel** [comment]
Thank you for the screen shot.

Even though the cookie is set in the browser, it is not included in the GET request. On a plain `XmlHttpRequest` cookies are not sent by default. To enable cookies, the `withCredentials` flag must be set to `true`. There should be some possibility to set that on the `axios` library.

**Comment by mitchescapeplan** [comment]
Must have had some major tunnel vision to miss that. Pretty sure I added that during my testing but confused the CORS error that resulted in it with the 401 I had been getting prior.

Sending the request with that `withCredentials` flag set to `true` worked. I was missing `.AllowCredentials()` when specifying the CORS origins allowed in the BFF server, so adding that fixed the CORS error I was experiencing and resulted in me getting data from the `/bff/user` endpoint. Thanks for your help.
