### ISSUE TITLE
Manually ending sessions

### ISSUE THREAD

**Issue by baouchemaya** [DuendeSoftware/Support#914]
Hi, 

I'm currently thinking to let user ending sessions of others via UI (which is a SPA with BFF). 
The sessions are server-side, stored in a table. 
Is it a proper way to perform a simple delete on this table (removing the session) and then, the session would be ended (implementing a notification mechanism to inform the discarded user) or should I implement a back-channel logout ? 
How to handle manually ended sessions ? 

Thank you in advance

**Comment by AndersAbel** [comment]
The right way to end server side sessions on the BFF is to use the `SessionRevocationService`. It will remove the session in the database, but also revoke any refresh tokens associated with the session.

However, when using OpenID Connect to sign the user in, you need to consider what session you are ending. A user that logs in to a n OIDC client will create two sessions, one at the OIDC Provider and one at the client application. The BFF-based application is the client and IdentityServer will be your OIDC Provider.

If you end the session on the client application, it will probably try to log in again. The login redirects to the OIDC provider IdentityServer where there is still a session and the user will be automatically signed in back to the client application again.

To end the session, you should end the server side session on the OIDC provider, including letting the OIDC provider issue a back channel logout to the client. This would let the OIDC provider own the session lifetime and use the normal notification processes to end the session on any active clients. On IdentityServer, the API to use is `ISessionManagementService.RemoveSessionsAsync()`.

**Comment by AndersAbel** [comment]
It appears that something is mixed up here. You state that you have a custom implementation of `IServerSideSessionStore`, but then there is an error thrown from `Duende.IdentityServer.Stores.ServerSideTicketStore` which is the Duende Implementation. If you are intending to use your own store, it looks like it is not properly registered.

When using the Duende implementation for the server side ticket store, the authentication tickets are encrypted in the database using the Asp.Net Core data protection. The `Failed to unprotect AuthenticationTicket payload for key XXXXXX` indicates the data protection is not properly setup causing the decryption to fail.

Please see [our guidelines](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/) and make sure that data protection is properly setup. Data protection is a critical tool used throughout IdentityServer and if it doesn't work many flows/components will fail. It is critical to have it properly setup for an IdentityServer deployment.

**Comment by baouchemaya** [comment]
thank you for the quick reply !

this is how I registered `ServerSideSessionsStore `: 

`builder.Services.AddTransient<IServerSideSessionStore, ServerSideSessionStore>();`
and 
```
builder.Services
        .AddIdentityServer(options =>
        {...})

        .AddAspNetIdentity<ApplicationUser>()
        .AddServerSideSessions<ServerSideSessionStore>();
```

is it the good way, please ? I have seen that there is another AddServerSideSessionsStore method, what is the difference between both of them ? 

For DataProtection, I have tried this for testing (I am using .NET 6.0) :    

```
builder.Services.AddDataProtection()
        .PersistKeysToFileSystem(new DirectoryInfo(@"keys/"))
        .SetApplicationName("IdentityServer")
        ; 
```

but it does not work, since now I have this message : `System.Security.Cryptography.CryptographicException: The key {XXXXX} was not found in the key ring.`
Do you have any clue, please ?

**Comment by AndersAbel** [comment]
I'm sorry, it is me who was misreading. The `IServersideTicketStore` and `IServerSideSessionStore` are two different services. When implementing a custom store, it is usually the `IServerSideSessionStore` that is override. Its responsibility is the actual storage. The `IServersideTicketStore` handles the encryption/formatting of the data to be stored.

This leads us back to data protection as the main candidate for the root cause of the issue.

When a new configuration for data protection is added, that location is empty to start with. At startup, new keys are automatically generated. This means that any data that was previously created, using the default key storage location will no longer be possible to read as those keys are no longer available.

**Comment by baouchemaya** [comment]
Hi, 

thanks for your reply 

The DataProtection issue seems to be "solved" by storing Identity Server sessions in a different table than BFF's : in my solution, they were both stored in the same collection (custom store). 

Here is the output now and nothing is happening on UI side : 
![image](https://github.com/DuendeSoftware/Support/assets/118121801/c66f7423-a71e-49ec-8360-305e79e601af)

Do you have any clue on what is going on here, please ?

Thank you in advance

**Comment by AndersAbel** [comment]
Storing sessions from different applications in the same store is ok to do, as long as there is some kind of application segregator/marker that ensures that an application can filter out and only read its own records. If that wasn't the case in the previous setup, it is logical that their would be data protection errors. If IdentityServer tries to read a record written by the BFF, it would not have access to the keys required to decrypt.

The `ClientIds` property is used as a filter. If it is left as `null` all clients that are active in the session will receive a logout notification. If there's a value in there, only the listed clients will be notified. It is usually better to leave it without value.

**Comment by baouchemaya** [comment]
okay, it is more clear now, thanks. I have remaining questions : 

- What about the BackChannelLogoutUri ? How is it defined ? 

- Also, according to my understing, the UI will be redirected to this BackChannelLogoutUri after RemoveSessionsAsync was triggered on IdentityServer. Am I wrong ? 

Thank you for your time

**Comment by AndersAbel** [comment]
I'll answer your questions with the second one first.

In OIDC there are two logout mechanisms. The most widely used is the Front Channel logout where the logged in user's browser interacts with both the OIDC provider and all client applications during logout. This is done by the OIDC Provider rendering a page that contains hidden iframes that makes requests to the client applications. Having the user's browser perform requests to all involved applications make it possible to clear cookies.

There are some drawbacks though with the front channel logout. The third party cookie blocking in browsers results in the iframe approach no longer being reliable across browsers in cross site scenarios. Also this restricts the logout to have to happen when the logged in user's browser is performing a request. In the scenario here where one user should be able to terminate the session of another "target" user there is no interaction between the target user's browser and the IdentityServer. That is why back channel logout is needed. Back channel logout is handled entirely outside of the browser, it's based purely on direct API calls between the OIDC provider and the client applications. Thus when using back channel logout, the answer to your question "Am I wrong?" is "yes", there is no UI redirect.

The `BackChannelLogoutUri` is configured on each client application definition in IdentityServer. It should be an endpoint of the client application that can receive OIDC back channel notifications. There is a built in backchannel logout feature in the BFF that you can use.

**Comment by baouchemaya** [comment]
Okay, so just a quick recap : 

- the app with BFF and Identity Server create 2 sessions in the store (two different tables). 
- when I am ending target user session, I end both of them (BFF + Identity Server, removing them from the store).

How to handle the OIDC backchannel notification in the client app ? I mean, how does the client tells it has received this notification and notify the target user by a "your session has been discarded by other user" message ?

**Comment by AndersAbel** [comment]
There is no built in way to notify the client application why the session has ended. The javascript client need to detect that. The most obvious thing for the javascript is to notice when API calls start returning 401. Another way is for the JS to actively query /bff/user.

To get direct notifications, some push technology is needed to be able to push information from the backend to the frontend. To do that in the BFF, a custom `ISessionRevocationService` implementation can be used to issue a push notification to the client.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
