### ISSUE TITLE
Allow only one active session per user

### ISSUE THREAD

**Issue by baouchemaya** [DuendeSoftware/Support#917]
Hi, 

I am using IdentityServer and BFF (with SPA).

In my app, I want users to be logged in from only one browser at a time (having one and only session). 

When user logs in then server should check his current active sessions. If there is then log out from everywhere and keep only newest session.

Is it possible to configure IdentityServer + BFF ? I was thinking about a backchannel logout mechanism. Do you have any clue ? 

Thank you in advance

**Comment by AndersAbel** [comment]
There is no built in feature to limit the number of sessions for a user, but it can be done through customization if server side sessions are used on IdentityServer.

A custom `IServerSideTicketStore` implementation could check for existing sessions when a new is created. It can then call `ISessionManagementServer.RemoveSessionsAsync` to remove the existing sessions before the new one is created.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
