### ISSUE TITLE
GetLogoutContextAsync via GetSubjectId throws InvalidOperationException

### ISSUE THREAD

**Issue by lawrencek76** [DuendeSoftware/Support#918]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
7.x

**Describe the bug**
System.InvalidOperationException is thrown when calling _interactionService.GetLogoutContextAsync(logoutId);

**To Reproduce**
This is generated during pen testing when cookies and parameters are being altered. the logoutId and or cookies can be in an invalid state. 

**Expected behavior**
GetLogoutContextAsync should return null and a log message is generated.

**Log output/exception with stacktrace**

```
{"Type":"System.InvalidOperationException","HResult":-2146233079,"Message":"sub claim is missing","Source":"Duende.IdentityServer","TargetSite":"System.String GetSubjectId(System.Security.Principal.IIdentity)"}
System.InvalidOperationException:
   at Duende.IdentityServer.Extensions.PrincipalExtensions.GetSubjectId (Duende.IdentityServer, Version=6.3.3.0, Culture=neutral, PublicKeyToken=null: /_/src/IdentityServer/Extensions/PrincipalExtensions.cs:80)
```

**Comment by josephdecock** [comment]
If the parameters are being manipulated to no longer be valid, that seems like a valid reason to throw an exception to me. Why would you want to continue processing if you got bogus cookies or parameters?

**Comment by lawrencek76** [comment]
You are correct that there is nothing inherently wrong about throwing in this situation, but for just for self-consistency mainly and we are not really saving on processing by throwing, it was unexpected.

Based on the sample code and documentation it looks like a null object result is expected.

for example
https://github.com/DuendeSoftware/BFF/blob/main/samples/IdentityServer/Pages/Account/Logout/LoggedOut.cshtml.cs

It appears that a null value will be returned if anything is wrong, and a "generic" logedout page / result would be returned.
That feels like the pattern identityserver generally takes and feels right here also.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
