### ISSUE TITLE
sub claim is missing when using DefaultAuthenticateScheme

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#919]
I'm using Identity Server 6 and ASP.NET 6.

I have this code that is executed after I've authenticated with Okta:
```
  [HttpGet]
  public async Task<IActionResult> Callback()
  {
      // Was using this:
      //var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);

      // Now using this:
      var result = await HttpContext.AuthenticateAsync();
      ...
  }
```
This is in my `Startup` class:
```
services.AddAuthentication(o =>
    {
	o.DefaultAuthenticateScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    })
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddOpenIdConnect(options =>
    {        
        options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
        options.SignOutScheme = IdentityServerConstants.SignoutScheme;
        options.ResponseType = OidcConstants.TokenRequest.Code;
        ...
    }
```
I have been using `var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme)`, however was just looking at the documentation for `HttpContext.AuthenticateAsync()` and can see it uses `AuthenticationOptions.DefaultAuthenticateScheme` as the default scheme.

As a test, I used `HttpContext.AuthenticateAsync()` to use the default scheme, and set the default value of `DefaultAuthenticateScheme` to the scheme I was originally passing to `HttpContext.AuthenticateAsync()` (ie. `IdentityServerConstants.ExternalCookieAuthenticationScheme`).

I thought this would have no effect since the scheme will still be `IdentityServerConstants.ExternalCookieAuthenticationScheme`, however when the browser navigates to `https://localhost:44349/signin-oidc`, it shows `InvalidOperationException: sub claim is missing`
![image](https://github.com/DuendeSoftware/Support/assets/13111539/6c00aa11-770c-4b88-a062-c13303f63fa5)

Why is the sub claim missing if it's still authenticating like it was before with the `IdentityServerConstants.ExternalCookieAuthenticationScheme` scheme?

**Comment by josephdecock** [comment]
Setting the default scheme both sets a default for explicit calls to SignInAsync, and sets the the  default for the authentication middleware that runs on every request. As part of that, IdentityServer verifies that basic claims that it issues are present. That's where the failure is coming from, not this call to authenticate. You're right about how the defaults work though, and if were using only asp.net authentication (without identity server), you could replace the explicit name of the scheme with a default.
