### ISSUE TITLE
IResourceOwnerPasswordValidator not being called

### ISSUE THREAD

**Issue by mtinnes** [DuendeSoftware/Support#920]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
7.0

**Describe the bug**
Custom IResourceOwnerPasswordValidator implementation is no longer being called during authentication.

We are using a custom ResourceOwnerPasswordValidator and have added the object using the AddResourceOwnerValidator extension method. The object is being created evidenced by a breakpoint in the constructor, however the ValidateAsync() method is not being called at any point.

**To Reproduce*
Add a custom resource owner validator:
```
        builder.Services
            .AddIdentityServer(options =>
            {
            })
            .AddResourceOwnerValidator<IdentityResourceOwnerPasswordValidator>()
```
Add breakpoint in the ValidateAsync() method of the custom validator to determine if validator is being utilized.

**Expected behavior**
We have custom logic used in validation of a user. Our custom resource owner validator should be called during authentication.

**Log output/exception with stacktrace**
No errors or logs indicate an issue, the validator is simply not getting called.

**Additional context**
The standard lockout logic as described in the default asp.net authentication also does not seem to be working. Flagging the user as locked out in the DB does not prevent successful login.

**Comment by AndersAbel** [comment]
I'm not sure I entirely understand what it is you are trying to achieve. The `IResourceOwnerPasswordValidator` is only used when making requests directly to the token endpoint using the resource owner password grant. Usage of that grant is not recommended as it requires password handling on the client.

If you want to add extra validation of the users at authentication time, that can be added in the UI. The UI is typically created using one of our quick starts, but after that it's meant to be adapted and extended according to the needs of each organisation. It is possible to add extra validation of the user to the login page.

**Comment by mtinnes** [comment]
Thanks Anders. I guess there is some obvious confusion as to the delegation of responsibilities. We do have logic in the UI for auth, but it does not seem to take into consideration some of the AspNet mechanics for Lockout. I was assuming that the IResourceOwnerPasswordValidator was called regardless of grant type. I'll take another look at the quick starts, thanks.

**Comment by AndersAbel** [comment]
Do you have any more questions on this or can we go ahead and close the issue?
