### ISSUE TITLE
AspNetUserClaims in JWT token

### ISSUE THREAD

**Issue by stzach** [DuendeSoftware/Support#921]
Duende Identity 6.3.5

dotnet6.0

We are using AspNetUsers to save user, but due to the fact that users are created from another system they have an int userID. We are saving as AspNetUserClaims that userid.

We are trying to retrieve that as part of the token using the legacy password flow or credentials flow. In both cases they just provide an access token, without any extra user claims. 

Trying to request for an idtoken we add openid scope for these flows, but we get an invalid_scope error. It seems that we have no way to retrieve an idtoken using these flows? 

Should we override ProfileService to manually add user claims to accesstoken? Is there any other way to retrieve idtoken using either password or credentials flow?

**Comment by AndersAbel** [comment]
I am going to answer this under the assumption that our Asp.Net Identity integration package is used based on our [documentation](https://docs.duendesoftware.com/identityserver/v6/aspnet_identity/).

The Duende Asp.Net Identity integration contains a `IProfileService` implementation that works with Asp.Net Identity to retrieve claims, using the Asp.Net Identity `UserClaimsPrincipalFactory`. The factory by default reads the `AspNetUserClaims` table.

To have these claims turn up in the access token, there needs to be an ApiScope that has these claims and the client needs to be allowed to use that scope and the client needs to request that scope.

Please verify that:
* The client requests an API scope.
* The client configuration in IdentityServer lists that API scope as allowed for the client.
* The API scope is defined and has the claim listed.

**Comment by stzach** [comment]
Great Anders!! 

Your assumption is correct, we use AspNetIdentity integration. After proper configuration works fine.

Thank you for your help.

**Comment by stzach** [comment]
One more thing related to that. When a user is assigned to roles, i see that there are roleClaims on the AspNet implementation.

Isn't it supposed that for password flow roles, role claims would be part of the access token as well? Is that something that should be handled by the Profile Service?

**Comment by AndersAbel** [comment]
The roles are handled automatically with the same rules as above.

To enable Asp.Net Identity's role management, make user the call to `AddIdentity` is the version with two generic parameters: `builder.Services.AddIdentity<ApplicationUser, IdentityRole>()`

Then make sure that the role claim is configured with your API scope in the same way as the other claims.

**Comment by stzach** [comment]
Clear. Thank you very much
