### ISSUE TITLE
How does Identity Server set the sub claim based on a strongly typed user object?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#923]
I'm using Identity Server 6 and ASP.NET 6 with Okta as the external IdP.

In the example in https://docs.duendesoftware.com/identityserver/v6/ui/login/session/, it shows how to create the cookie using `SignInAsync()`:
```
var claims = new Claim[] {
    new Claim("sub", "unique_id_for_your_user")
};
var identity = new ClaimsIdentity(claims, "pwd");
var user = new ClaimsPrincipal(identity);

await HttpContext.SignInAsync(user);
```

In the above code, it's explicitly setting the `sub` claim.

How does the `sub` claim get set if you're using a strongly typed user object to sign in?

Here's my callback after the user signs in with Okta:

```
[HttpGet]
public async Task<IActionResult> Callback()
{
    var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
    var returnUrl = result.Properties?.Items["returnUrl"] ?? "~/";

    var context = await _interaction.GetAuthorizationContextAsync(returnUrl);
    _clientIDResolver.SetClientId(context?.Client.ClientId);

    if (result.Succeeded)
    {
        var claims = result.Principal.Claims.ToList();
        var user = await FindByIdentityProviderUserIdAsync(claims);
        if (IsApproved(user))
        {
            var externalUserDetails = GetExternalUserDetails(claims);
            if (HaveUserDetailsChanged(user, externalUserDetails))
            {
                await UpdateUserDetails(user, externalUserDetails);
            }
            
            var additionalLocalClaims = new List<Claim>();
            CaptureExternalLoginContext(result, additionalLocalClaims);

            await _signInManager.SignInWithClaimsAsync(user, result.Properties, additionalLocalClaims);
        }
        else
        {
            return await RedirectToErrorPage(claims, returnUrl, context);
        }
        
        await HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
        
        return Redirect(returnUrl);
    }

    throw new Exception("External authentication error");
}
```

In the above, the `user` object has a `UserId` property which is a `Guid`, and I noticed in my client app, once it has received the access and identity tokens, they both have that `Guid` as the `sub` claim.

There is no sub claim in the `additionalLocalClaims` object passed to `SignInWithClaimsAsync()`.

How does it know to use that property as the `sub` claim?

I found this method in my custom user store class, and I'm wondering if this is called behind the scenes to create the `sub` claim?

```
Task<string> IUserStore<BedrockUser>.GetUserIdAsync(BedrockUser user, CancellationToken cancellationToken)
            => Task.FromResult(user.UserId.ToString());
```

**Comment by AndersAbel** [comment]
This is not really Identity server specific. The claims creation is handled by the Asp.Net Identity `UserClaimsPrincipalFactory` which is used by the Asp.Net Identity `SignInManager` to create the claims from the user object.

The `UserClaimsPrincipalFactory` extracts the user id from the user object and creates a claim with the type configured on `IdentityOptions.ClaimsIdentity.UserNameClaimType`. IdentityServer configures that property to be `sub`.
