### ISSUE TITLE
Can I use the SAME `ClientId` and `ClientSecrets` for different deployments?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#924]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
7.0.111
**Describe the bug**
Can I use the SAME `ClientId` and `ClientSecrets` for different deployments, Production and Staging, which are different only by their URL?

Client applications would use different "issuer":
```
        issuer: process.env.DUENDE_IDS6_ISSUER || config.get('DUENDE_IDS6_ISSUER'),
        clientId: process.env.DUENDE_IDS6_CLIENT_ID || config.get('DUENDE_IDS6_CLIENT_ID'),
        clientSecret: process.env.DUENDE_IDS6_CLIENT_SECRET || config.get('DUENDE_IDS6_CLIENT_SECRET'),
```
This will simplify our application configuration for these 2 different environments. Thanks.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AndersAbel** [comment]
Yes, you can, but we recommend using different client secrets for different environments.

Using the same client id usually makes things easier. I often use descriptive client Ids like "PublicWeb" or "BatchJob" when there are only a few clients. The client id's are hard coded both in IdentityServer and on the client. This essentially gives "configuration as code" with the entire configuration being version by the normal source control.

The redirect urls has to be different between the environments. It is not a good idea to add all urls for all environments as hard coded config, it's better to read the right ones from config files. The client secrets should also be different for security purposes.
