### ISSUE TITLE
What is `options.Authentication.CookieAuthenticationScheme` used for?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#926]
I'm using Identity Server 6 and ASP.NET 6 with Okta.

When are you meant to set the value for `options.Authentication.CookieAuthenticationScheme` (`options` is the param in `services.AddIdentityServer()`)?

I'm calling `_signInManager.SignInWithClaimsAsync()`, which uses the `Identity.Application` scheme behind the scenes.

I noticed the default value for `options.Authentication.CookieAuthenticationScheme` is `null`. Is there somewhere behind the scenes where it's declared that `Identity.Application` is to be used as the application cookie?

Is `options.Authentication.CookieAuthenticationScheme` similar to `options.SignInScheme` (in `services.AddAuthentication()`) in that they both declare the scheme that is to be used?
ie. `_signInManager.SignInAsync()` uses `options.Authentication.CookieAuthenticationScheme` (if it has a value set), and `HttpContext.AuthenticateAsync()` uses `options.SignInScheme`?

**Comment by DavidKlempfner** [comment]
It doesn't mention what "the host’s default authentication scheme" actually is.
Is it referring to one of the following defaults in the `AuthenticationOptions` set in `services.AddAuthentication()`?
There's `DefaultAuthenticateScheme = Identity.Application`, `DefaultSignInScheme = "Identity.External"` and `DefaultScheme = "idsrv"`.

**Comment by AndersAbel** [comment]
The "default authentication scheme" is the scheme returned by `AuthenticationOptions.DefaultAuthenticateScheme`.
