### ISSUE TITLE
Switch from implicit to code grant type

### ISSUE THREAD

**Issue by valse** [DuendeSoftware/Support#927]
**Which version of Duende IdentityServer are you using?**

6.2.3

**Which version of .NET are you using?**

core 2.1

Hi, in our application we upgraded one of our client to the code flow from the implicit one but after that logins with the old `ReturnUrl` with inside the old `response_type` query parameter, hangs with the "invalid grant type" error.

This might happen when, for example, a user has bookmarked the login page url even with the RedirectUrl parameter and tries to login but with the wrong response_type parameter.

What do you suggest to support the change of grant type for an existing client?
Thanks

**Comment by AndersAbel** [comment]
Great that you are changing from the outdated implicit flow to currently recommended code flow.

The only thing that can be done is to change the config on IdentityServer and in the client application on the same time. That will make sure that all new login attempts are using the new flow.

The login page is often bookmarked by users, but unfortunately it won't work. As you've found out, the login page URL contains state that is unique to each login attempt. There should also be validation on the client side that ensures that any incoming login response is from a freshly issued login request. With the implicit flow that is done through the `nonce` parameter that should be unique to each login attempt. With code flow, the PKCE extension should be used which also requires per-login-attempt state to be maintained on the client.
