### ISSUE TITLE
User-Centric Token for Downstream API Call

### ISSUE THREAD

**Issue by cxc256** [DuendeSoftware/Support#928]
I would like to use the latest of Duende.AccessTokenManagement. My question how would you use it to have one api call another api downstream with a user-centric token?

My specific issue is: a user logs into the website. A call to an API is made with the user-centric token. That api has to call another api keeping the sub claim intact.

**Comment by AndersAbel** [comment]
The easiest way is to let the first API forward the access token it received to the next API. While being simple, this has drawbacks: The second API needs to be configured to accept the same scope as the first API. With the access token being valid at the second API, it means that a client can bypass the first API and call directly into the second.

To avoid that, delegation can be used. It allows the first API to retrieve an access token that is valid for the second API, keeping the original `sub` and other claims: https://docs.duendesoftware.com/identityserver/v6/tokens/extension_grants/token_exchange/

**Comment by cxc256** [comment]
I actually have implemented the Token Exchange in my IdentityServer. Right now, ClientCredential tokens are automatically renewed in client app using the IdentityModel.Aspnetcore... however, for user-centric tokens, I have to do a bit of manipulation and manually call the token exchange.

I was wondering if the Duende.AccessManegement can now do the same automation for user-centric token exchanges?

**Comment by AndersAbel** [comment]
No, there is no built in support for token exchange in Duende.AccessTokenManagement.

The client credentials case you refer to is not token exchange, it's simply a matter of keeping track of the lifetime of the token and requesting a new whenever the previous has expired. If you need to do token exchange you need to set that up yourself with a request to the token endpoint. IdentityModel contains suitable helper methods that makes it simple.

**Comment by cxc256** [comment]
Thank you!
