### ISSUE TITLE
Adding license to file system

### ISSUE THREAD

**Issue by edleatherbury** [DuendeSoftware/Support#93]
**Which version of Duende IdentityServer are you using?**
5.2.4

**Which version of .NET are you using?**
5.0.2

License is not recognized when adding the Duende_License.key file to the project directory. We added the file to the project root of an MVC app, set the file properties to always copy to output directory, confirmed the file is in the bin directory post-build, but get "Duende.IdentityServer: Warning: You do not have a valid license key for Duende IdentityServer." on startup. We tried various build actions for the file (content, embedded resource), none work.

If we add the license key to Startup.cs (`options.LicenseKey = "your_license_key";`) the key is recognized and the app starts without warnings. Any suggestions on where/how to add the file?

**Comment by brockallen** [comment]
For v5.x it needs to be called `Duende_IdentityServer_License.key`

https://docs.duendesoftware.com/identityserver/v5/fundamentals/license_key/#file-system

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
