### ISSUE TITLE
invalid_client not logged

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#930]
Duende 6.1.1
.NET 6

A vendor who has been successfully using the identity server is now running into occasional errors. They are getting the response "invalid_client" back. This error is not being logged on any of the servers. This is making it difficult for me to track down the issue. Is there a reason why this error would not be logged?

Thanks,
Bill

**Comment by AndersAbel** [comment]
There should be logs written any time an `invalid_client` response is returned. Can you please share your logging/log level configuration?

Also, to get some context, do you know what operation they are trying when they receive that error? What endpoint are they calling?

**Comment by billcunnien** [comment]
Hello Anders,

Thanks for the reply. Here is our logging configuration:

builder.Host.UseSerilog((ctx, lc) => lc
    .MinimumLevel.Debug()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
    .MinimumLevel.Override("Microsoft.Hosting.Lifetime", LogEventLevel.Information)
    .MinimumLevel.Override("System", LogEventLevel.Warning)
    .MinimumLevel.Override("Microsoft.AspNetCore.Authentication", LogEventLevel.Information)
    .Enrich.FromLogContext()
    .WriteTo.File(@"C:\Logs\log.txt")
    .ReadFrom.Configuration(ctx.Configuration));

Nothing much to write home about there. Each server with this configuration logs locally. None of the servers have recorded the invalid_client error. There are times when an invalid_grant error is recorded because we recently made changes to how our grants and keys are persisted. I am expecting those errors.

In almost all of these cases the refresh key is being submitted to the connect/token endpoint. There was also a case in which the account/login caused the same error - this may be isolated, though.

I will be jumping back into the logs this morning and reviewing them for any unusual behaviors. I cannot imagine why the invalid_client error is not being recorded, but if you have any insight, just let me know.

Thanks,
Bill

**Comment by billcunnien** [comment]
On a side note, I was following up on the log entries for invalid_grant and saw this entry in the log:

2023-10-05 07:09:53.408 -04:00 [ERR] Failed to deserialize JSON from grant store.

This suggests that a specific decryption key is missing or invalid when the system tries to unpack the results. Is this correct? If so, what should a client application do to handle this kind of problem? My thinking is that the app logout the user and restart the auth process over using a new, valid key.

Also, I noticed that the InMemoryPersistedGrantStore returns a null value for GetAsync if the retrieval fails for whatever reason. Is this the expected value in this case? I have a custom store and was not returning a null value but an empty object - this was causing a few problems.

**Comment by AndersAbel** [comment]
To follow up on the `invalid_client` issue it would be great to other log entries from that request to be able to follow what's happening up to the point of the error being returned.

The records in the persisted grant store are encrypted using Asp.Net Core Data Protection. Please see [our documentation](https://docs.duendesoftware.com/identityserver/v6/deployment/data_protection/) for information on configuration.

Yes, `IPersistedGrantStore.GetAsync()` is expected to return `null` if the key was not found.

**Comment by billcunnien** [comment]
Thanks for confirming the return value for GetAsync().

I will continue to monitor the logs and try to catch the invalid_client entry. So far, it has not been there and determining the actual set of entries around the failed request is a bit difficult (not sure which entries belong to which request most of the time). If I stumble upon more data, I will re-open this issue or start another.

Appreciate the help!
Bill
