### ISSUE TITLE
Forcing re-authentication

### ISSUE THREAD

**Issue by GMillerVarian** [DuendeSoftware/Support#931]
**Which version of Duende IdentityServer are you using?**
6.3.3

**Which version of .NET are you using?**
.NET 6.0.21

**Describe the question**
We want to support clients forcing re-authentication via the prompt=login or max_age=0 authorization parameters, as per the following:
- https://auth0.com/docs/authenticate/login/max-age-reauthentication
- https://identityserver4.readthedocs.io/en/latest/endpoints/authorize.html

We have observed that neither of these parameters are forwarded to the external providers, so although our login code is triggered, the providers are not prompting for credentials.

Based on [this StackOverflow answer](https://stackoverflow.com/a/48685072), we have implemented the following:
- in our ExternalController's Challenge method, if present, we add these params to the AuthenticationProperties "Items" bucket
- in our custom OnRedirectToIdentityProvider event, we grab these from the AuthenticationProperties and set them into context.ProtocolMessage

This works for prompt=login, the external provider prompts for credentials as expected. However, with max_age=0 it does prompt for password as expected, but then after redirecting back it gets stuck in an infinite loop of retriggering the login and redirecting to the provider.

Setting max_age to some small value (ex. 15) does work as expected if you complete the login within that time.

So a couple of questions:
- is it expected that we should have to explicitly set these options into the ProtocolMessage in order for them to be passed on to the external provider? Or is this supposed to just work "out of the box"? We had to do this for ui_locales, login_hint, acr_values, prompt and max_age.
- how can we prevent the loop and force the re-authentication only once?

**Log output**
```
[14:12:10 INF] Showing login: Requested MaxAge exceeded.
[14:12:38 INF] Showing login: Requested MaxAge exceeded.
[14:14:00 INF] Showing login: Requested MaxAge exceeded.
[14:14:24 INF] Showing login: Requested MaxAge exceeded.
```

**Comment by AndersAbel** [comment]
This might look like a fairly simple and straight forward question, but the answer is unfortunately quite complex. (This is also why we've taken some time to answer this).

While `prompt=login` and `max_age=0` might look like they would mean the same thing, they do, as you've found out, not. `max_age` works best when setting values to require authentication within the last 5+ minutes. Lower than that, and there is a risk of redirect loops and repeated authentication prompts if the whole flow is not completed in time.

If you want to force a re-authentication, the right way with IdentityServer is to set `prompt=login` in the request to IdentityServer. The prompt parameter is sent in the unprotected query string in the redirect from the client to IdentityServer. A malicious user could simply remove it to not have to re-authenticate. The be sure that re-authentication happened, the client must validate the `auth_time` of the received id_token. The client should save the time of the challenge (e.g. in the authentication properties) to be able to validate that auth_time is indeed after the challenge time. That both allows users to take their time while preventing a quick user to do multiple operations without re-authenticating.

The default IdentityServer login page always shows the login page for `prompt=login`. It can be adjusted to instead do reauthentication using the provider for the current user. 

The exact behaviour for `prompt=login` and `max_age` might differ between providers. For example, the `auth_time` is only mandatory to include in the id_token if `max_age` was set. So for some providers it might not be possible to validate `auth_time` if only `prompt=login` was set. A workaround is to set `prompt=login` and `max_age=999999999`  (or another large value) to force the upstream OP to include `auth_time`. As the redirect to upstream providers is part of the hosting project/UI code and not of IdentityServer you need to set the relevant flags yourself. The method you found with AuthenticationProperties+events is probably the easiest.

The final thing to do is to carry over the actual authentication time from the upstream provider into the IdentityServer `auth_time`. That can be done in the external login callback. If that time is not carried over, a malicious user could drop the `prompt=login` paramter in the redirect to the upstream provider without being detected.

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this isseu?

**Comment by GMillerVarian** [comment]
Thank you for providing this information. I will close this issue and re-open if anything further is needed.
