### ISSUE TITLE
Possibility to set issuer dynamically

### ISSUE THREAD

**Issue by marcinkowal2015** [DuendeSoftware/Support#934]
**Which version of Duende IdentityServer are you using?**
v6

**Which version of .NET are you using?**
.NET 6

**Describe the bug**

We are currently in migration from Identity Server v3 to Duende Identity Server v6. Simultaneously we are migrating from old runtime on .NET Framework to .NET 6 using Strangler Fig pattern.

We have multi tenant application, where tenant id is provided in first URL segment: e.g: www.mywebsite.com/tenant1

We configured identity server v3 in a way that it returns issuer in token as: www.mywebsite.com/tenantid/api, as we start services separately for each tenant. In .NET 6 however we don't do that, still behavior is correct(for handling tenant part) as middleware for handling tenant is executed before IdentityServer, so we end up with issuer: www.mywebsite.com/tenantid

Problematic part is that if we would like to customize issuerUri we don't have access to http context, using IssuerUri in options. Is there a way to set issuer dynamically basing on HttpContext somehow?

**To Reproduce**

Described in bug description, not differ from setup in guides.

**Expected behavior**

Be able to set issuer basing on information in http context.

**Log output/exception with stacktrace**

-

**Additional context**

-

**Comment by AndersAbel** [comment]
The issuer name is created by the `IIUserNameService`. By default (and when mTLS is not used) the current request is used. A custom `IIssuerNameService` has full access to the DI system and can return a custom value.

Please note that OpenID Connect requires the OIDC Provider to present the discovery document at issuer + `.well-known/openid-configuration`. Any custom issuer would also require a custom discovery document to be created and made available.

**Comment by marcinkowal2015** [comment]
I have created implementation:

```
    public class MyTest : IIssuerNameService
    {
        public Task<string> GetCurrentAsync()
        {
            return Task.FromResult("http://my-custom-issuer.com");
        }
    }
```

And registered it:

`            .AddTransient<IIssuerNameService, MyTest>()
`

Should I do anything else, as I still get autogenerated issuer name? :(

Also due to fact that I will need to adjust discovery document, what is best way to do it dynamically (to have DI system available, in similar way as for the issuer case)

**Comment by AndersAbel** [comment]
Please note that you need to register your custom implementation *after* the call to `AddIdentityServer` as it's the last registration that will be used. If you want to do a proper cleanup it can be done with `builder.Services.RemoveAll<IIssuerNameService>()`.

Once it's properly registered the discovery document will automatically pick up the value from your `IIssuerNameService`.

**Comment by marcinkowal2015** [comment]
Registering it after the call to `AddIdentityServer` was a bit which I was missing. Works like a charm, thank you!
