### ISSUE TITLE
[QUESTION] sid without server sessions or origin_jti

### ISSUE THREAD

**Issue by miquelvir** [DuendeSoftware/Support#935]
**Which version of Duende IdentityServer are you using?**
6.3.0

**Which version of .NET are you using?**
net6.0

**Describe the questions**
How to get sid without server sessions or origin_jti claim in Duende

**To Reproduce**
NA

**Expected behavior**

We need an id that is associated to the user's refresh token. In other words:
- 1/ the original token and all refreshed tokens would have the same id. 
- 2/ a token from the same user that was obtained separately has a different id.

Because of 1 we cannot use the jti claim. Because of 2 we cannot use sub claim. 

**Log output/exception with stacktrace**

NA

**Additional context**

The reason we need such an id is because we have a legacy double Authentication mechanism, where after obtaining the token, the client must log in against an external system, and we preserve the external authentication in a stateful session. We cannot preserve or do all the Auth in the server hosting Duende because the external Authentication and session keeping is owned by a different service.

We need something similar to origin_jti in AWS Cognito (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-id-token.html).

**Comment by AndersAbel** [comment]
There is already a `sid` claim in all access tokens. It is not dependent on server side sessions being used. A refresh token is associated with the `sid` from the session that created the refresh token. Any access tokens generated based on the refresh token will have the same `sid`.

To me it looks like that would fulfil your needs. Or am I missing anything here?

**Comment by miquelvir** [comment]
@AndersAbel thanks for your answer. 

Yes, that would solve it. However, our access tokens do not have a sid. What can be going wrong?

Version 6.3.0

The tokens I get:
```
{
  "iss": "https://my-host.domain/IDP",
  "nbf": 1696609682,
  "iat": 1696609682,
  "exp": 1696613282,
  "aud": [
    "https://my-host.domain/IDP/resources"
  ],
  "scope": [
    "openid",
    "profile",
    "offline_access"
  ],
  "amr": [
    "pwd"
  ],
  "client_id": "MyClient",
  "sub": "9DE4A61C-2D84-4578-8E50-DA862905FEA0",
  "auth_time": 1696609682,
  "idp": "local",
  "name": "basic",
  "updated_at": "1696249530",
  "jti": "3BF458A81CC18BCC09C2FD805CFADC51"
}
```

This is how I get the token:

```
def get_token(session: requests.Session, username: str, password: str, serverUrl: str) -> str:
    url = f"{serverUrl}/IDP/connect/token"
    payload = f"grant_type=password&username={username}&password={password}&client_id=MyClient&scope=openid profile offline_access"
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded'
        }
    return session.request("POST", url, headers=headers, data=payload, verify=False)
```

This is how the startup file looks:
```
services
               .AddIdentityServer(options =>
               {
                   options.Logging = new LoggingOptions
                   {
                       UnhandledExceptionLoggingFilter = (context, exception) => !(context.RequestAborted.IsCancellationRequested && exception is OperationCanceledException)
                   };
                   options.IssuerUri = Configuration.Get<IdentityServerConfiguration>().IdentityProviderSettings.Authority;
                   options.InputLengthRestrictions.ClientSecret = 200;
                   options.AccessTokenJwtType = "JWT";
                   options.EmitStaticAudienceClaim = true;
                   options.Events.RaiseSuccessEvents = true;
                   options.Events.RaiseFailureEvents = true;
                   options.Events.RaiseErrorEvents = true;
                   options.Discovery.CustomEntries.Add("external_providers_uri", "~/.well-known/openid-configuration/externalproviders");
                   options.Discovery.CustomEntries.Add("server_version", $"{BuildMetadata.VersionMajor}.{BuildMetadata.VersionMinor}.{BuildMetadata.VersionRevision}");
                   options.LicenseKey = "...";
                   options.KeyManagement.RotationInterval = TimeSpan.FromDays(
                       Configuration.Get<IdentityServerConfiguration>().KeyManagementSettings.RotationIntervalInDays);
                   options.KeyManagement.PropagationTime = TimeSpan.FromDays(
                       Configuration.Get<IdentityServerConfiguration>().KeyManagementSettings.PropagationTimeInDays);
                   options.KeyManagement.RetentionDuration = TimeSpan.FromDays(
                       Configuration.Get<IdentityServerConfiguration>().KeyManagementSettings.RetentionDurationInDays);
               })
               .AddConfigurationStore(options =>
               {
                   options.ConfigureDbContext = builderConfigure.ContextOptionsBuilder;
                   options.DefaultSchema = "dbo";
               })
               .AddOperationalStore(options =>
               {
                   options.ConfigureDbContext = builderConfigure.ContextOptionsBuilder;
                   options.EnableTokenCleanup = true;
                   options.TokenCleanupInterval = 30;
                   options.DefaultSchema = "dbo";
               })
               .AddAspNetIdentity<VmsUser>()
               .AddExtensionGrantValidator<WinAuthGrantValidator>()
               .AddExtensionGrantValidator<WindowsCredentialsGrantValidator>()
               .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
               .AddProfileService<ProfileService>()
               .AddAppAuthRedirectUriValidator();
```

**Comment by AndersAbel** [comment]
Oh, you are using the resource owner password credentials (RPOC) grant. I just assumed that you would be using the authorization code grant for an interactive client.

When using the RPOC grant, there is no `sid` because there is no session created on the IdentityServer. It would be possible to extend IdentityServer to create/return a `sid` even for the RPOC grant.

But, I would also suggest that you revisit the decision to use the RPOC grant. It is generally recommended that interactive applications use the authorization code flow and not RPOC. Using RPOC gives the client application access to the end user's password. When using the authorization code flow, the password is directly transferred from the client's browser to the IdentityServer.

**Comment by miquelvir** [comment]
As far as I know, we cannot stop using RPOC. We are migrating an existing system and two identity servers coexist at the minute, as we migrate all the APIs to accept the new ones from Duende IDP.

**Comment by AndersAbel** [comment]
If you need to use RPOC you need to extend IdentityServer to include a custom claim with a session id that is generated when running the RPOC validation.

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this issue?
