### ISSUE TITLE
Support for geolocation statistics in order to notify users when their credentials are used for logging in from unknown or risky locations

### ISSUE THREAD

**Issue by sydseter** [DuendeSoftware/Support#936]
Question:

I wonder whether you have any advice on implementing functionality for collecting geolocation statistics in order to notify users when their credentials are used for logging in from unknown or risky locations. Do you know of any provider of geolocation services that could be integrated with IdentityServer and that would work in business to consumer scenarios?
What we are looking for is something similar to [WSO2 IS Analytics Server](https://is.docs.wso2.com/en/5.10.0/learn/enabling-geolocation-based-statistics/) that could be used in order to satisfy [OWASP ASVS 2.2.3](https://github.com/OWASP/ASVS/blob/master/4.0/en/0x11-V2-Authentication.md#v22-general-authenticator-security).

Is there any advice you can give here that could work in a business to consumer scenario? 

Does IdentityServer have something similar to [WSO2 IS Analytics Server](https://is.docs.wso2.com/en/5.10.0/learn/enabling-geolocation-based-statistics/) on the roadmap?

**Comment by AndersAbel** [comment]
The login UI and related logic is part of the hosting project and not the core IdentityServer. While we do provider quickstarts to get a working solution up and running, we anticipate our customers to customize the UI with their design and business rules in the backend code. Geolocation would fit into the customization category. So while it can certainly be done, it is not a core part of IdentityServer and not anything we are planning.
