### ISSUE TITLE
Access to BFF feature in community edition?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#938]
**Which version of Duende BFF are you using?**
I have 2 line-of-business applications which are developed using React.JS / Next.Js with Node.JS server. Currently I am using IdentityServer for the security needs of my applications. I keep tokens in the frontend javascript code.
However, I just finished reading https://andrewlock.net/should-you-use-the-dotnet-8-identity-api-endpoints/ and learnt that keeping tokens in the browser is a bad idea and is not future-proof. So I am evaluating BFF. However according to https://docs.duendesoftware.com/identityserver/v6/bff/ this feature is only available for Business license or higher. If it is not available in Community edition, how would I be able to test and evaluate before making the decision to adopt this?

**Which version of .NET are you using?**
Community

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AndersAbel** [comment]
All versions of Duende IdentityServer, including the BFF framework, are free to use for for development and testing.

On https://docs.duendesoftware.com/identityserver/v6/bff/ it is stated that "Duende.BFF is included in [IdentityServer](https://duendesoftware.com/products/identityserver) Business Edition or higher. The same [license](https://duendesoftware.com/products/identityserver#pricing) and [special offers](https://duendesoftware.com/specialoffers) apply.". The special offers link leads to our community edition page which states that  "Our Community Edition license is feature equivalent to our Enterprise Edition".

**Comment by khteh** [comment]
Do you have any sample without using ASP.Net Core as the backend?
I clone your sample and it's not able build / run with the latest version of Node.JS. After making it buildable and runnable, it hits the following error:

```
<snip>
Compiled successfully!

You can now view cra_latest in the browser.

  Local:            https://localhost:44447
  On Your Network:  https://192.168.1.82:44447

Note that the development build is not optimized.
To create a production build, use npm run build.

[HPM] Error occurred while trying to proxy request /bff/user from localhost:44447 to http://localhost:18084 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /todos from localhost:44447 to http://localhost:18084 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /bff/login from localhost:44447 to http://localhost:18084 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
it's not clear to me from the README in FrontendHost/ClientApp how to set things up and see it works.

**Comment by AndersAbel** [comment]
> Do you have any sample without using ASP.Net Core as the backend?

I don't understand what you are trying to do. Our BFF component is based on Asp.Net Core and requires Asp.Net Core as the backend to run. If you want to use the BFF pattern on another platform, such as Node.Js, you will need an implementation in that platform.

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this issue?
