### ISSUE TITLE
BFF with Blazor Web App (dotnet 8)

### ISSUE THREAD

**Issue by b1tzer0** [DuendeSoftware/Support#940]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
dotnet 8 RC 1

**Describe the bug**
I understand that dotnet 8 is still a moving target when related to identity and the new format is quite interesting bouncing from SSR to Client Side and such.  But when working with BFF, I have been trying to get this to work properly and ran into what might be an issue.  

When you call bff/login with enhanced navigation turned off, I get redirected to the login page where I can login.  However, when I get redirected back to the page with the authorize attribute a call to bff/user?slide=false returns back that the user is not currently logged in.

See screen shot of logs:
<img width="854" alt="image" src="https://github.com/DuendeSoftware/Support/assets/20190154/528f8874-0eb1-46c1-af97-029a81d8b63a">

You can pull some sample code I had started from here: https://github.com/b1tzer0/BlazorWebApp_DuendeIdentityServer
the Bff stuff has been commented out, just go back into program.cs and re-enabled it.  Of course, you will need to set the connection to identity server as well.

Can someone please assist?  Thanks

**Comment by AndersAbel** [comment]
I think you described it fairly well yourself:
> I understand that dotnet 8 is still a moving target when related to identity and the new format is quite interesting bouncing from SSR to Client Side and such.

We are looking into Blazor for .NET 8 and how to best support it with the BFF, including documentation, but it is still work in progress.

**Comment by pm64** [comment]
Just checking to see if this issue should still be open following the release of https://github.com/DuendeSoftware/IdentityServer/releases/tag/7.0.0?

Specifically, is BFF now supported and documented for all render modes in .NET 8 (static server, interactive server, interactive WASM, and interactive auto)?

**Comment by b1tzer0** [comment]
@pm64, I think that is being targeted for BFF 3.0

**Comment by josephdecock** [comment]
> @pm64, I think that is being targeted for BFF 3.0

Yes, that's correct. See also [my comment here](https://github.com/DuendeSoftware/Support/issues/1048#issuecomment-1887780207).

There's an [open issue in our samples repo](https://github.com/DuendeSoftware/Samples/issues/142) that we'll update as we make progress on this, so I'm closing this one.
