### ISSUE TITLE
bff/login not working after Blazor app deployment to Azure App Services

### ISSUE THREAD

**Issue by nc-digital-au** [DuendeSoftware/Support#941]
Hi I'm at a loss at what to do next and I'm not sure what additional information I need to provide you.

Please let me know what other info I need to provide and maybe where to find it I'm a complete noob when it comes to deployment.
I'm getting the following error when I try to login on my production website

Sorry, there was an error : invalid_request
Request Id: 80001493-0000-d300-b63f-84710c7967bb

Everything is working fine locally on me development machine.

I'm using
Duende version 6.3.5 on my standalone identity provider and
Duede BFF version 2.1.1 in my Blazor application

I'm using .Net  core version7.0.11

It's only happening on my site repathacopay.com.au and I get the error when click the login button that takes me to my IDP

I'm expecting it to go to the login screen but it doesn't.

I know there's probably logs etc that I need to give but I wan't sure where to go of those and what would be need. If you can point me in the direction I'll go hunting.

Any help will be appreciated!

**Comment by oleinselmannhaagensen** [comment]
I think I may have the same problem. I deployed to Azure App Service, but it couldn't find the endpoint when I clicked on login. I have created a new issue. How did you solve it? It works fine locally.
