### ISSUE TITLE
Best practice for sending language selection from Identity Server to client

### ISSUE THREAD

**Issue by antonkallenberg** [DuendeSoftware/Support#943]
**Which version of Duende IdentityServer are you using?**
6.1.5

**Which version of .NET are you using?**
net6.0

**Describe the question**
We have given the user the option to select a language in Identity Server to change the display languages in the views. Now, the question arises about sending the selected language back to the client so that the client can display the application in the language chosen during the login flow. I've been pondering various solutions but can't find a natural way forward.

Ideally, we would like the client to receive the chosen language as early as possible, perhaps as a query string directly on the redirect back. However, I recognize that it's probably unwise to start manipulating the redirect URL.

Is there a recommended method to handle this scenario?

**To Reproduce**
N/A

**Expected behavior**
N/A

**Log output/exception with stacktrace**
N/A

**Additional context**
N/A

**Comment by AndersAbel** [comment]
[OpenID connect defines](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) a standard claim type `locale` that is included in the `profile` scope. The protocol compliant way to handle this is to include the locale (in the right format) in the id_token or UserInfo endpoint response.

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this issue?
