### ISSUE TITLE
ValidatedAuthorizeRequest Value cannot be null. (Parameter 'redirectUrl')

### ISSUE THREAD

**Issue by stzach** [DuendeSoftware/Support#945]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
dotnet 6.0

**Describe the bug**
After upgrading form Identity 4 to 6 we get authentication error. When redirecting to login page using:

https://DOMAIN/connect/authorize?response_type=code&client_id=client&state=cmdSRnJEUXFodmtDcWpSbkhJbjZ1LmhFeTZBY2dxY3FTdGJsbEs3M352SjNF&redirect_uri=https%3A%2F%2Flocalhost%3A43255&scope=openid%20profile%20offline_access&code_challenge=WP_c3yE8oDYlr5r-4nR01Yq3eEUIBhT3VnxzMlFq7Tc&code_challenge_method=S256&nonce=cmdSRnJEUXFodmtDcWpSbkhJbjZ1LmhFeTZBY2dxY3FTdGJsbEs3M352SjNF

we get:

ArgumentNullException: Value cannot be null. (Parameter 'redirectUrl')
Duende.IdentityServer.Endpoints.Results.AuthorizeInteractionPageResult..ctor(ValidatedAuthorizeRequest request, string redirectUrl, string returnUrlParameterName) in AuthorizeInteractionPageResult.cs
Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, bool checkConsentResponse) in AuthorizeEndpointBase.cs
Duende.IdentityServer.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, bool checkConsentResponse) in AuthorizeEndpointBase.cs
Duende.IdentityServer.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context) in AuthorizeEndpoint.cs
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in IdentityServerMiddleware.cs
Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in MutualTlsEndpointMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in DynamicSchemeAuthenticationMiddleware.cs
Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in BaseUrlMiddleware.cs
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by msharp19** [comment]
@stzach What was the solution?
