### ISSUE TITLE
Invalidate Access token upon signing out

### ISSUE THREAD

**Issue by castlepointpv** [DuendeSoftware/Support#946]
**Which version of Duende IdentityServer are you using?**
**6.2**
**Which version of .NET are you using?**
**6.0**
**Describe the bug**
Invalidate Access token upon signing out
 Can  a access token be invalidated upon signing out from a web session. What's the recommended practice with validity of access tokens ?
**To Reproduce**
Steps to reproduce the behavior.
Login into a web session
Get the Access token from the browser
Logout from web 
Use the same Access token to replay the request 

**Expected behavior**
Using the same access token in a API request after logging out from web session should respond 403

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AndersAbel** [comment]
Self-contained JWT tokens cannot be invalidated once issued. That is why the recommendation is to keep them short-lived. The client would then use a refresh token to get new access tokens as needed. The refresh token can be invalidated at logout which makes it impossible for the client to get a new access token once the current expires.

If there is a requirement for immediate token inactivation/revocation on logout it is possible to do that using reference tokens. A reference token cannot be validated directly by an API. The API needs to call the IdentityServer introspection endpoint to get the payload of the token. While this increases security it comes with a performance penalty.
