### ISSUE TITLE
BFF Local APIs Question

### ISSUE THREAD

**Issue by goldytech** [DuendeSoftware/Support#95]
**Which version of Duende BFF are you using?**
Duende BFF 1.2.2
**Which version of .NET are you using?**
6.0.5
**Describe the question**
I'm planning to use BFF along with IDP. In my project, all APIs require JWT for authentication. None of the APIs are anonymous.
The frontend JS App must invoke a few APIs before the user session begins via Authorize Code flow. I've decided to proxy these APIs via BFF local APIs. So the JS App will invoke the BFF local APIs, which will call the Remote APIs after getting token via Client Credentials Grant Type.
My question is, how can I secure these local APIs running in BFF without establishing the user session. (No same site cookie)

**Comment by brockallen** [comment]
The browser redirect is required -- that's how how OIDC and SSO work.

**Comment by goldytech** [comment]
I still feel there should be some way to manage anonymous sessions. The remote APIs may require the Authn, but due to the business requirements, these APIs that are proxied via BFF local APIs should work on the anonymous sessions.

**Comment by leastprivilege** [comment]
> Is there any api available in bff to do back channel login without actually redirecting to IDP login page ?

If you BFF host is allowed to do an OAuth client credentials flow, sure, it can do authenticated server to server calls. But be aware that this call was originally triggered by an anonymous request.

**Comment by leastprivilege** [comment]
That's fine. Now in your BFF local API, you can get the server-server token by calling

`var token = HttpContext.GetClientAccessTokenAsync();`

..and then call the other API.
