### ISSUE TITLE
Token Request Pre-validation

### ISSUE THREAD

**Issue by amiru3f** [DuendeSoftware/Support#951]
**Duende Version:** 6.2.3

**.NET** 6.0

Hello there,

Currently, Duende IdentityServer supports **post-validation** of token requests using the `ICustomTokenRequestValidation` interface. This allows developers to perform additional validation on `TokenRequestValidationResult`. However, there is no 
 mechanism (independent of a specific flow or grant type) in the box for pre-validating token requests before executing checks related to client credentials, resources, scopes, or any other stuff in the pipeline.

**Challenges**

Several challenges are there for customizing pre-validation without changing the core:
* `TokenRequestValidator` is an internal class, making it inaccessible for customization,
* `CustomTokenRequestValidation` is triggered after all default checks have already taken place. 
* `TokenEndpoint` is also internal and not extensible.
* The pre validation logic should not be inside a custom `grant_type` or `CustomClientValidator`, but general.

**Use Case**

Consider a scenario where it is essential to pre-validate a token request. For instance, you may want to check whether the user's device is blocked before any other checks take place (for a sample deviceId). There may be various use cases where pre-validation is necessary to avoid unnecessary overhead caused by default checks in Duende IdentityServer's pipelines.

@brockallen @josephdecock  Your insights and recommendations are highly appreciated.

**Comment by AndersAbel** [comment]
A custom validation step running before the standard validation would only have access to the raw, unvalidated, request parameters. The usefulness of such a validation step would be limited to very specific scenarios.

If the purpose is to block requests early, before incurring the cost of running the standard validation, it would also make sense to do the blocking as early as possible, probably even before the IdentityServer middleware is invoked. Wouldn't it be better to add a custom middleware early in the pipeline and block the request there? Or even add rules to the application firewall to block the request from even reaching IdentityServer?

**Comment by amiru3f** [comment]
Hello,

@AndersAbel Thanks for your response. Back to a specific problem, a combination of a `client`, `device`, and a `user` (or any other specs depending to the `grant_type`) creates kind of a unique key which lets the developer to have a token bucket rate limiter in layer 7 (`application`) before hitting the IdentityServer middlewares. Even before checking the rate, the correlation of these there should be verified. 
If I want to keep it simpler, before any other verification which has already been done and the result was cached somewhere, we might have an option to just check the cache. Could be any kind of verification (Just see it abstract)

I see your suggestion in this two categories:
- Middleware injection
- Doing it at firewall layer 

The middleware injection is good enough for customization but in my case, I don't want the overhead of `path equality check` and `parameter/model rebinding/reparsing`.

Regarding to the firewall, my case is related to layer 7, and maintaining the firewall customized rules is not that easy and flexible for the developers (And not unit testable)

I totally agree that cases might be very specific, but having such kind of layer before starting the main pipelines would increase flexibility and for sure performance (comparing to the middleware)

**Comment by AndersAbel** [comment]
Thank you for the context. This is a highly specialised requirement. Adding an extension point to allow for this use case could unfortunately invite to putting logic in the wrong place, creating vulnerable applications.

I think however that there is a workaround possible. You could add your own `ITokenRequestValidator` that is a decorator of our implementation. We use that pattern extensively internally, so you would be able to create something similar in your code. The idea is to *remove* the current registration of `ITokenRequestValidator` from the service collection and then add it back within a small wrapper class. Then you can add your own registration for `ITokenRequestValidator` that takes in `InnerWrapper<ITokenRequestValidator>` as a parameter.

I think that such a solution would be able to meet both your functionality and performance requirements.

**Comment by amiru3f** [comment]
I appreciate your response and suggested workaround.

> This is a highly specialised requirement,  putting logic in the wrong place

If you look at it just as a `Pre Request Validation Logic` it would be neither a specialised requirement nor invalid logic.

IIUC you are suggesting to decorate the default [TokenRequestValidator](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Validation/Default/TokenRequestValidator.cs#L24) with my own customised version. Actually if I aim to decorate the default version, it needs it to be `public` and currently isn't.

**Comment by AndersAbel** [comment]
You're stripping out part of my quote:
> This is a highly specialised requirement. Adding an extension point to allow for this use case could unfortunately invite to putting logic in the wrong place, creating vulnerable applications.

Every time we offer an extension point, we have to carefully consider if it invites user to doing the right thing or not. In this case I think that the risks are too high if we would offer such an extension point. It would invite people to use it, without understanding the implications of working on un-validated data.

I suggested a workaround for your specific case as we will not implement the extension point you are requesting. 

It is possible to decorate without having access to the default implementation. That can be done by getting the current service registration from the DI system and replace it. You do not even have to know what implementation is registered to decorate it.

**Comment by amiru3f** [comment]
Actually I didn't know that it can be done without having access to the implementation type 

Thanks @AndersAbel
