### ISSUE TITLE
BFF Question Using Remote APIs on localhost

### ISSUE THREAD

**Issue by mitchescapeplan** [DuendeSoftware/Support#953]
Duende BFF v2.1.1
.NET v6.0

I've got two questions, as my coworker and I are experiencing different results with the same setup. Or at least we believe we are.

We currently have three different types of environments right now: Development, QA, and Production. QA and Production are currently working as expected, everything flows through their own BFF server and hits their respective APIs that are built out for that environment. Our issue comes in when we want to use our local APIs for development purposes before we submit anything to QA.

The client app calls our local BFF server on https://localhost:7050, and we map two different local paths to a different remote API
- /API-CM maps to https://localhost:5001
- /API-EM maps to https://localhost:6001

For me, when it's forwarding the request to the remote API it seems like it can't find the server and returns a 502, giving me the stack trace below. It says the request was aborted prior to it finishing, but I don't think the request is even making it out as no breakpoint is hit inside the controller being called.

![image](https://github.com/DuendeSoftware/Support/assets/32110396/cdb009e6-e0a9-4eb2-8a8d-6ffb4ee6a60c)

Whenever my coworker does the same thing, he receives a 431. But this only happens when he calls our APIs on localhost. The three split BFF cookies are only 5,512 bytes in total, and with the rest of the cookies and headers it totals out to be 8,163 bytes that are sent in the header. We've increased the allowed header limit on both the BFF and the API that is being called to 100000 but experience the same result.

![image](https://github.com/DuendeSoftware/Support/assets/32110396/2f6d2ecd-a280-4d23-bcfa-bf4611aad9ba)

It is just specific to having the APIs run on localhost though, as we have different profiles set up in our launch settings to be able to call the different environment's APIs. When our localhost BFF is mapped to forward requests to our QA APIs, it forwards everything properly.

So ultimately my questions are:
1. What could possibly cause the http forwarder on BFF to end forcibly before getting the request out?
2. Is there an underlying problem that is just bubbling to a 431 request when really the header size is well under the limit? Maybe localhost has different rules than when everything is built out to IIS?

Thanks for the pair of eyes, and for the past help as well getting everything set up to this point.

**Comment by AndersAbel** [comment]
It's hard to tell what the problem is based on the information here. Would it be possible to use a traffic inspection tool (Fiddler or similar) to inspect the traffic from the BFF to the APIs?

**Comment by mitchescapeplan** [comment]
Of course. Here's a .zip with two HTTP Archive (.har) files you can import into Fiddler to show the requests that are failing. Fiddler didn't seem to pick up the forwarded request from BFF to the API so this is just the initial call from client app to BFF. Was this what you were looking for, or is there a way for me to get Fiddler to find the forwarded request from BFF to the API?

[LocalAPIErrors.zip](https://github.com/DuendeSoftware/Support/files/13043625/LocalAPIErrors.zip)

**Comment by AndersAbel** [comment]
It's the traffic from the BFF to the API that is interesting to inspect as it appears to be the source of the errors. Fiddler works by acting as a local proxy. This is picked up automatically by web browsers, but not by applications so some configuration is probably needed. There are also other options that work on the network stack level. In any case, to continue troubleshooting we need some more information on the traffic between the BFF and the API.

**Comment by mitchescapeplan** [comment]
Sorry for wasting your time. While trying to figure out the right configuration for Fiddler, my coworker found a place that we didn't realize was overriding the default header size to a smaller size. And whether or not that's what actually was also causing my 502, a fresh pull with those updated header sizes fixed my issues too. Appreciate it.
