### ISSUE TITLE
SAML2P with Identity Server

### ISSUE THREAD

**Issue by nmcmahon01** [DuendeSoftware/Support#954]
**Which version of Duende IdentityServer are you using?**
We are currently using the Standard version of Duende IdentityServer. 

We wanted to implement SAML2P with multiple idps.  Is this available on the Standard licence or do we need to upgrade to the Enterprise version, or is there a plugin we need to buy?
We have reviewed the documents but are confused on what is and isn't supported. 

Thank you

Noreen

**Comment by AndersAbel** [comment]
Duende IdentityServer itself does not support Saml2P. If I understand you right, the question is about using multiple upstream Saml2 IdentityProviders to authenticate users. All client applications would still use OpenID Connect. In that case we recommend the free Sustainsys.Saml2.AspNetCore2 library. It is compatible with IdentityServer and can be used both with configuration at startup and with the dynamic client feature of Duende IdentityServer Enterprise edition.
There's a [sample](https://docs.duendesoftware.com/identityserver/v6/samples/ui/) on how to use Sustainsys.Saml2 with the dynamic providers feature.

If you want IdentityServer to act as a Saml2 IdentityProvider, there is a commercial plugin from Rock Solid Knowledge, please see identityserver.com for information.

**Comment by AndersAbel** [comment]
Do you have any more questions or can we go ahead and close this issue?

**Comment by nmcmahon01** [comment]
HI

Thank you for your help. You can go ahead and close this now.

Thanks
Noreen

Noreen McMahon
Development Manager EST | ESO
***@***.******@***.***>

***@***.***<https://www.eso.com/>

CONFIDENTIALITY NOTICE: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential, proprietary and/or privileged information protected by law. If you are not the intended recipient, you may not use, copy or distribute this e-mail message or its attachments. If you believe you have received this email message in error, please contact the sender by reply email and telephone immediately, and destroy all copies of the original message.
