### ISSUE TITLE
Client Signout is not calling Logout page on IndentityServer

### ISSUE THREAD

**Issue by raffsokolowski** [DuendeSoftware/Support#955]
Duende IdentityServer 6.3.3
.NET 7.0.10

Client Signout is not calling Logout page on IndentityServer

Description:

As per samples provided, I'm using the following code to sign out:
return SignOut("Cookies", "oidc");

I have also tried various other ways trying to find a solution but still get the same result.

The server instead redirects to the Login page and does not call the Logout page and does not return the result to the client.

https://localhost/Account/Login?ReturnUrl=%2FAccount%2FLogout%3FlogoutId%3DCfDJ8PXB-GWk_U1FpAi8-p3CQefITy1O4jwiust5dYhEjVZSpYJ_PjLieKMVn9CP3MIshfupHTPVWlLGpTsOmy6xDzuiP3oxEivAQiDOlgznTk-WpKQ-Rpjbp8rEkd7hCPRVi1K1xKAV-Z_a4jEjKYUv59Grk34RRHsdd5TP58UZLhOj_RoyNFuzbc3p6aQjM9sBBGUESAc2rg9rWno3yBRuAkIH9XtjEZ5qkTF3870AzfARWn0nvY8zZd35lDe7F9iZDA-Z8vvrX9tipSwk355qiDXSLqJTWFAx6U-cpzwvdypmiYrC_Mjkx6kBGTpezYiicR_CJ_38lQmTQDMtnE2RnJ5mz7Op1eybLJT8ZYy50dTE2sG_qlrpDjqPxwI2Z1yjjWOl1Zo-sqol9p_1bQr6SCfRlFunX4l0ROLslPP0GDEJ2hRvxSLQ7lmhvrRKPJo7LtIxquMEDb8YYmTVe64VpaZ_jCPgYtW_HCkYORZltStbTh0R_ViM7-zIewY-TTow71QT-IPBUCsa1rMe91mSlxhov5wcbIihf0VwT-BgnChe0uZsDtyKFMRJoXaM9pfF0T-6LYnKE0dROjNbOMxINK0799jNE3VsAwMci3LJE5shwWn6QzrDp4ycnvLmvdJV_xdT2mjMqgQ55krVbB_AZRW5E0cS77_NdM9n8BNtg7aqM3HiIsXNSt_JMyJp1XrvAg

When I try to login again I get logged out because the return url is set to logout out and I end up back on the login page with the following:

https://localhost/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DMVC_Client%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5000%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520CentreApi%2520offline_access%26code_challenge%3DNI2f5r6sIebQXu6qNP3Fz1FrSfZgkreu7A2xh4gSCbM%26code_challenge_method%3DS256%26response_mode%3Dform_post%26nonce%3D638332949469990156.OGY5MTlmY2UtZGM0YS00ZmQ1LTkxNjYtNGFiNTZjYTRlZTQ0MTI2N2JjMjgtMGFkNi00NmM1LWJjZTktZDBlNTIwMjgxYTYy%26state%3DCfDJ8CFzLVBz451DgKjEdebKQ8RwpOw6JEqAt8oX95Wi4cwQq4uhtX0badzyZoPFUlXwNUmk2zxxrNGJl53Cj9Gs1K4hNkoUiEsJFbSUBL6nQp2VdXspLGajHIQ4KrPDLAAb7eGTwuubkxZvHDm6KyomhDoYG8cljdOAE70eSkCp8tLZaKa3JLOcvrEreniFka3GJuWiEOxUj91onyfOBAXPNTFHQqHglcPaROd_y6BD2posbd10AyJNDVUlsGpdxWzSXCZqiI7rK1C_WOe9jCIlPyT08Hrw_Ho4LNytH-VPtjgTEim_X9GhK72qLi47cDIuU5zYG5gyXdBkRtRdWaXX76gsnB7RPWOsRbw3nu9Ak6CFpec1skWgsSrKkrEWoKmSmA%26x-client-SKU%3DID_NETSTANDARD2_0%26x-client-ver%3D6.10.0.0

Server Code:

	new Client
	{
		ClientId = "MVC_Client",
		ClientSecrets = { new Secret("SOME SECRET".Sha256()) },

		AllowedGrantTypes = GrantTypes.Code,
		RequirePkce = true,
		RequireConsent = false,

		RedirectUris = { "http://localhost:5000/signin-oidc" },
		PostLogoutRedirectUris = { "http://localhost:5000/signout-callback-oidc" },

		AllowOfflineAccess = true,  // Adds offline_access scope for refresh tokens
		RefreshTokenExpiration = TokenExpiration.Sliding,
		SlidingRefreshTokenLifetime = ((int)TimeSpan.FromDays(30).TotalSeconds),
		AbsoluteRefreshTokenLifetime = ((int)TimeSpan.FromDays(60).TotalSeconds),

		AlwaysIncludeUserClaimsInIdToken = true,

		AllowedScopes = { 
			IdentityServerConstants.StandardScopes.OpenId,
			"CentreApi"
		}
	}

    public void ConfigureServices(IServiceCollection services)
    {
		(...... removed)

        // Identity settings
        services.AddIdentity<ApplicationUser, ApplicationRole>(options => options.SignIn.RequireConfirmedAccount = true)
            .AddEntityFrameworkStores<CentreDbContext>()
            .AddClaimsPrincipalFactory<AppClaimsPrincipalFactory>()
            .AddDefaultTokenProviders();

        string connectionString = Configuration.GetConnectionString("CentreConnection");
        var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
        services.AddIdentityServer()
            // this adds the config data from DB (clients, resources, CORS)
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = builder =>
                    builder.UseSqlServer(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
            })
            // this adds the operational data from DB (codes, tokens, consents)
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = builder =>
                    builder.UseSqlServer(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));

                options.EnableTokenCleanup = true;
                options.TokenCleanupInterval = 3600; // interval in seconds (default is 3600)
            })
            .AddAspNetIdentity<ApplicationUser>()
            .AddProfileService<ProfileService>();

        services.AddAuthentication()
            .AddJwtBearer("jwt-bearer-allowing-multiple-issuers", options =>
            {
                options.Authority = Configuration.GetValue<string>("Centre:Authority", "https://localhost");
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false,
                    ValidIssuers = Configuration.GetSection("Centre:ValidIssuers").Get<string[]>(),
                };
                options.SecurityTokenValidators.Clear();
                options.SecurityTokenValidators.Add(new JwtSecurityTokenHandler
                {
                    MapInboundClaims = false
                });
            });

        var cookieDomain = Configuration.GetValue<string>("Centre:CookieDomain", ".localhost");
        services.ConfigureApplicationCookie(options =>
        {
            options.Cookie.Name = "Centre.Auth";
            options.Cookie.Domain = cookieDomain;
            options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.Strict;
            options.SlidingExpiration = true;

            options.LoginPath = "/Account/Login";
            options.LogoutPath = "/Account/Logout";
            options.AccessDeniedPath = "/Account/AccessDenied";
        });
		
		(...... removed)
	}
	
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
	
		(...... removed)

        app.UseHttpsRedirection();
        app.UseStaticFiles();

        app.UseRouting();

        app.UseIdentityServer();    // Includes Authentication
        app.UseAuthorization();
        app.UseCsp();   // Needs to be after IdentityServer

		app.UseEndpoints(endpoints =>
        {
            endpoints.MapRazorPages().RequireAuthorization();
            endpoints.MapControllers().RequireAuthorization();
        });
    }

Client Code:

            services.AddAuthentication(auth =>
            {
                auth.DefaultScheme = "Cookies";
                auth.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("Cookies")
            .AddOpenIdConnect("oidc", options =>
            {
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

                options.Authority = "https://localhost";
                options.ClientId = "MVC_Client";
                options.ClientSecret = "SOME SECRET";
                options.ResponseType = OpenIdConnectResponseType.Code;
                options.Scope.Clear();
                options.Scope.Add("openid");
                options.Scope.Add("CentreApi");
                options.Scope.Add("offline_access");

                options.SaveTokens = true;
                options.GetClaimsFromUserInfoEndpoint = true;

            });

The logout on client is simply:

        [HttpPost]
        public async Task Logout()
        {
		return SignOut("Cookies", "oidc");

/*  Have tried various methods below.....

            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
            //return Redirect("/");
            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");

            //return RedirectToAction("Index", "Home"); 

            try
            {
                await HttpContext.SignOutAsync("Cookies");
                var prop = new AuthenticationProperties()
                {
                    RedirectUri = "/"
                };

                await HttpContext.SignOutAsync("oidc", prop);
                //HttpContext.Session.Clear();
            }
            catch { }

            //return new JsonResult("OK");
*/
        }		

I'm getting the same problem with a different client also from Xamarin with an Android client
The logout page works correctly when running it manually and is exactly as the samples provided with a logout and then loggedout
The only difference is the path to login and logout is as per the cookies configuration above (/Account/Login and /Account/Logout)

**Comment by AndersAbel** [comment]
To initiate SingOut from within a controller it's better to use the `return SignOut(..)` helper method than to call `HttpContext.SignOut(...)` directly. `return SignOut(...)` will create a SignOutResult, that when executed will call `HttpContext.SignOut(...). But returning a result works better with the model of controllers.

**Comment by raffsokolowski** [comment]
I've tried that as per the samples, still doesn't work

return SignOut("Cookies", "oidc");

**Comment by raffsokolowski** [comment]
I found the issue, I had to add the [AllowAnonymous] attribute to the Logout page, I guess the user is logged out before it tries to access this page.
I already had [AllowAnonymous] on the LoggedOut page.
