### ISSUE TITLE
Identity Server as APIs and UI to client to build

### ISSUE THREAD

**Issue by smartouss** [DuendeSoftware/Support#956]
Hello,

Im wondering if i could expose the capabilities of duende as APIs without UI, all samples i see use razor page.

My target is to let my clients build the UI for their identity server and i just expose APIs for them.

Is that possible with duende?

Thanks in advance

**Comment by AndersAbel** [comment]
Yes it is possible. We actually have [a sample using a SPA for the UI](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/UserInteraction/SpaLoginUi). Please note that we [consider the login](https://docs.duendesoftware.com/identityserver/v6/ui/) being part of the UI, which includes establishing a server side session for IdentityServer. Please note that if you intend to run the UI on a separate host than IdentityServer that adds significant challenges from a security perspective.

**Comment by smartouss** [comment]
yes i meant in a separate host, the host of the identity server only expose APIs

**Comment by AndersAbel** [comment]
It is probably possible to host the UI on a separate host, but you need to do a careful investigation of how it affects security.

**Comment by smartouss** [comment]
is there a sample or documentation for that?

**Comment by AndersAbel** [comment]
No. Hosting the UI on a different host than IdentityServer would be an advanced extension/customization and nothing we have out-of-the-box documentation or samples for.

**Comment by smartouss** [comment]
okay thanks for the info, i apricate it
