### ISSUE TITLE
Migrating Blazor WebAssembly App with IdentityServer BFF Feature from .NET 7 to .NET 8

### ISSUE THREAD

**Issue by rahul7720** [DuendeSoftware/Support#957]
**Which version of Duende BFF are you using?**
2.11

**Which version of .NET are you using?**
.NET 8 Preview RC2

1. Are there any breaking changes when moving from .NET 7 to .NET 8 related to Blazor WebAssembly or IdentityServer BFF?
2. Are there any updated guidelines, documentation, or sample projects specifically for this type of migration?
3. How to configure the BFF in a new 'Blazor Web App' template using WebAssembly Interactive | Server Interactive | Auto Interactive Mode?

I would greatly appreciate any pointers, guidance, or resources that can help with this migration. Thank you in advance!

**Comment by AndersAbel** [comment]
We are working on updated documentation for how the Blazor updates affect IdentityServer. We'll let you know when we have something available.

**Comment by gizmohd** [comment]
Do we have any updates on the samples/documentaion for Blazor/IdentityServer for .net 8?

**Comment by leastprivilege** [comment]
see https://github.com/DuendeSoftware/Support/issues/1024#issuecomment-1893198660

**Comment by josephdecock** [comment]
In the interest of keeping things organized, I'm closing this along with some other related issues, but feel free to provide feedback and comments in (https://github.com/DuendeSoftware/Samples/issues/142)
