### ISSUE TITLE
Key Management Between IdentityServer4 and Duende 5.x 

### ISSUE THREAD

**Issue by edleatherbury** [DuendeSoftware/Support#96]
**Which version of Duende IdentityServer are you using?**
5.2.4

**Which version of .NET are you using?**
5.0

We're unclear what we need to change for key management after migrating from IdentityServer4 to Duende 5.2.4 Starter edition. Since we're on Starter, automatic key management is not enabled and we disabled it in Startup. After deploying to test environments everything seems to be working across all apps, but we want to make sure we aren't missing something.

During migration and for initial testing we didn't change anything in Startup except `using` statements and `options.KeyManagement.Enabled = false;`. We also kept `.AddDeveloperSigningCredential()`, although we now see that migration docs say it should be removed. If we don't have automatic key management however, should we keep that in place?

Here is the current code block in Startup.

```
// Identity server
var migrationAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
services.AddTransient<IEventSink, CustomEventsHandler>();
services.AddIdentityServer(options =>
{
    options.Events.RaiseSuccessEvents = true;
    options.KeyManagement.Enabled = false;
})
    .AddDeveloperSigningCredential()
    .AddConfigurationStore(options =>
    {
        options.ConfigureDbContext = builder => builder.UseSqlServer(idpConnection, sql => sql.MigrationsAssembly(migrationAssembly));
    })
    .AddOperationalStore(options =>
    {
        options.ConfigureDbContext = builder =>
            builder.UseSqlServer(idpConnection,
                sql => sql.MigrationsAssembly(migrationAssembly));

        // this enables automatic token cleanup (optional).
        options.EnableTokenCleanup = true;
        options.TokenCleanupInterval = 3600;
    })
    .AddAspNetIdentity<User>();

//Token Generation Helpers
services.AddTransient<ITokenProvider, TokenProvider>();
services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
```

**Comment by brockallen** [comment]
> We also kept .AddDeveloperSigningCredential(), although we now see that migration docs say it should be removed. If we don't have automatic key management however, should we keep that in place?

`AddDeveloperSigningCredential` was only ever intended to be used when doing local/dev testing, and never in production. So its purpose remains the same if you are not using the automatic key management.

**Comment by edleatherbury** [comment]
> `AddDeveloperSigningCredential` was only ever intended to be used when doing local/dev testing, and never in production. So its purpose remains the same if you are not using the automatic key management.

In that case, what should we use for production? `AddSigningCredential`?

**Comment by brockallen** [comment]
> In that case, what should we use for production? AddSigningCredential?

Yes.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by edleatherbury** [comment]
Yes, can close.
