### ISSUE TITLE
KeyManager error

### ISSUE THREAD

**Issue by stzach** [DuendeSoftware/Support#960]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
dotnet6.0

**Describe the bug**
We are using automatic key management services.AddIdentityServer() and persisted grant store. The keys table is successfully created and populated with data

```
Id	Version	Created	Use	Algorithm	IsX509Certificate	DataProtected	Data
FFF35AEC7C5CE7310E42E1650AFD0519	1	2023-08-16 15:47:23.9198004	signing	RS256	0	1	CfDJ8LHAJzm7ov9PlmNhMhnfIyQ0hxZLTRdEaD91Yoat97c-....
```
An error throw and complain about that kid as you see in the log trace.

**Log output/exception with stacktrace**

```
Error unprotecting the IdentityServer signing key with kid FFF35AEC7C5CE7310E42E1650AFD0519. This is likely due to the ASP.NET Core data protection key that was used to protect it is not available. This could occur because data protection has not been configured properly for your load balanced environment, or the IdentityServer signing key store was populated with keys from a different environment with different ASP.NET Core data protection keys. Once you have corrected the problem and if you keep getting this error then it is safe to delete the specific IdentityServer signing key with that kid.
```

**Additional context**

I have also enabled Data Protection to root keys folder that is the default IdentityServer use.
services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(Path.Combine(environment.ContentRootPath, "keys"))).SetApplicationName("Application");

and we now receive errors like:

```
Failed to unprotect AuthenticationTicket payload for key 034C74C17186216FAEFC3314FD04A96D01F3D1EB561C8AC3670FF26625CDC6F5"
```

```
Failed to deserialize JSON from grant store.", "exception": "System.Security.Cryptography.CryptographicException: The key {806d7899-0526-41fb-9fcd-6375f47bf6c9} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning\r\n 
```

Should we clean up DB and keys folder to re-generate keys? Do we miss some configuration? Please note that this is a single identity server instance without any load balancer.

**Comment by AndersAbel** [comment]
Yes, you should clean up the old entries.

Once you configure an explicit location for the Data Protection keys, the default location will no longer be read and any data created using the old key can no longer be decrypted.

**Comment by stzach** [comment]
Hello,

Truncating keys and session tables resolved the issues we had.

Thank you

**Comment by justintoth** [comment]
Big thanks for this tip, I was getting the same error:

`Error unprotecting the IdentityServer signing key with kid ..... This is likely due to the ASP.NET Core data protection key that was used to protect it is not available. This could occur because data protection has not been configured properly for your load balanced environment, or the IdentityServer signing key store was populated with keys from a different environment with different ASP.NET Core data protection keys. Once you have corrected the problem and if you keep getting this error then it is safe to delete the specific IdentityServer signing key with that kid.`

I had tried truncating our DataProtectionStore table but still received the error. The solution was to also truncate the Key table.

**Comment by AndersAbel** [comment]
@justintoth I should have been more clear in my post. It's the Keys table that needs to be truncated after the data protection settings have been updated.

**Comment by adarsh-icis** [comment]
Hello @AndersAbel , we are getting same error :`Failed to unprotect AuthenticationTicket payload for key {key}`,
but we have not done any changes in dataprotection configuration, but we updated to .net8 and Duende7, Can either of these upgrade cause this error? Also, we see this error only in logs, and user login works as expected without any issue.
(also, this error is accuring with .net8_duende 6.2 also)
other configs: 
AutomaticKey Key management,
DataProtection Keys are stored in persistent MongoDB with Dataprotected=true.

Is it get resolved by truncating the SerializedKey collection?

exception details:
`System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Duende.IdentityServer.Extensions.AuthenticationTicketExtensions.Deserialize(ServerSideSession session, IDataProtector protector, ILogger logger) in /_/src/IdentityServer/Extensions/AuthenticationTicketExtensions.cs:line 133`
