### ISSUE TITLE
Clients must not contain duplicate ids

### ISSUE THREAD

**Issue by billcunnien** [DuendeSoftware/Support#961]
Duende 6.3.5
.NET 6

After adding a new client in our settings file, the restart of the application ended up with this error in the event logs:

Clients must not contain duplicate ids

Also, the application is not longer logging anything.

The clients defined each have a unique ID assigned to them.

What can I look for to resolve this problem?

Thanks,
Bill

**Comment by AndersAbel** [comment]
I'm sorry, but if you get that error message there are two clients with the same `ClientId`.

How do you load the configuration from the settings file? Would it be possible to set a breakpoint to inspect the clients collection when it is loaded?

**Comment by billcunnien** [comment]
I had three clients defined in appsettings. Each had a different ID. One of them was marked as disabled. Once I completely removed the disabled client, the error went away. Since I had gotten past the error, I did not dig any further.
