### ISSUE TITLE
BFF with nextjs

### ISSUE THREAD

**Issue by wantwi** [DuendeSoftware/Support#963]
**Which version of Duende BFF are you using?**
2.0
**Which version of .NET are you using?**
dotnet 6

Is it possible to use bff in a nextjs application.

**Comment by AndersAbel** [comment]
If I know the JavaScript landscape right, the `Next.js` library is a server side library/hosting solution. In that case it cannot be used with our BFF component as our BFF component requires the server to run Asp.Net Core.

BFF is not just our implementation, it is a general pattern. We didn't invent the pattern, nor the name. It's perfectly possible to create a BFF implementation in JavaScript.
