### ISSUE TITLE
LDAP for IdentityServer

### ISSUE THREAD

**Issue by boetskevinKTN** [DuendeSoftware/Support#964]
**Which version of Duende IdentityServer are you using?**
 v6.3.5
 
**Which version of .NET are you using?**
.NET 6

We've come across a third party solution for which we would like to use our existing Identity server implementation for the authentication.
Except this solution doesn't yet support openid connect or OAuth, but instead supports LDAP.

At first glance there doesn't seem to be any LDAP support available for Identity Server.
Do you know of any way to add support for this protocol?

**Comment by AndersAbel** [comment]
LDAP is not an single sign on, but a data access protocol. Single Sign On Protocols such as OpenID Connect, Saml2 or WS-Fed all rely on redirecting the user to the provider for authentication. LDAP has no mechanism for that. What you could possibly do is to validate a user's username and password with the LDAP provider. The login would then be on IdentityServer.

As our login UI is [meant to be customised or replaced](https://docs.duendesoftware.com/identityserver/v6/ui/) it is possible to use an LDAP client library to implement the login pages of IdentityServer.

**Comment by AndersAbel** [comment]
Are there any more questions about this or can we go ahead and close the issue?
