### ISSUE TITLE
Concurrent api calls triggers duplicate refresh token process

### ISSUE THREAD

**Issue by ADringer** [DuendeSoftware/Support#966]
**Which version of Duende BFF are you using?**
2.1.1

**Which version of .NET are you using?**
7.0

**Describe the bug**

I have a configured remote endpoint which uses a token from Identity Server. Some of my pages within my Blazor app makes concurrent calls to this remote endpoint.

If these concurrent calls occur after the access token has expired then they all trigger the refresh token process. However they all use the same refresh token and the first one causes a new refresh token to be generated and so the subsequent refreshes will fail as the original refresh token is no longer valid. This then fails the request and it returns a 401 back to the app.

Ideally refreshing a token would be a singleton for each token so that it is 'locked out' and only one refresh occurs at a time.

**To Reproduce**

1. Set up a remote endpoint with user token
2. Create a page that makes multiple calls to the same remote endpoint
3. trigger the calls after the token has expired
4. Some calls will fail

**Expected behavior**

The refresh token process should only run the once and all pending requests should make use of the refreshed token without going to Identity Server

**Log output/exception with stacktrace**

```
dbug: Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService[0]
      Token for user 53a565eb-1129-428c-af1d-2b67ccbeb170 needs refreshing.
dbug: Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService[0]
      Token for user 53a565eb-1129-428c-af1d-2b67ccbeb170 needs refreshing.
dbug: Duende.AccessTokenManagement.OpenIdConnect.UserTokenEndpointService[0]
      refresh token request to: https://xxxx.com/usermanagement-api/connect/token
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[56]
      Received HTTP/2.0 response 200.
dbug: Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService[0]
      Token for user 53a565eb-1129-428c-af1d-2b67ccbeb170 needs refreshing.
fail: Duende.AccessTokenManagement.OpenIdConnect.UserAccessAccessTokenManagementService[0]
      Error refreshing access token. Error = invalid_grant
warn: Duende.Bff.Yarp.AccessTokenRequestTransform[4]
      Access token is missing. token type: 'Unknown token type', local path: 'Unknown Route', detail: 'Missing access token'
warn: Duende.Bff.Yarp.AccessTokenRequestTransform[4]
      Access token is missing. token type: 'Unknown token type', local path: 'Unknown Route', detail: 'Missing access token'
warn: Duende.Bff.Yarp.AccessTokenRequestTransform[4]
      Access token is missing. token type: 'Unknown token type', local path: 'Unknown Route', detail: 'Missing access token'
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[59]
      Not Proxying, a 401 response was set by the transforms.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[59]
      Not Proxying, a 401 response was set by the transforms.
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[59]
      Not Proxying, a 401 response was set by the transforms.
```

Identity Server error:

```
Rejecting refresh token because it has been consumed already
```

**Comment by AndersAbel** [comment]
One-time use refresh-tokens have turned out to be brittle. Our recommendation is to switch the `RefreshTokenUsage` setting on the client in IdentityServer to `ReUse` for all confidential clients. A BFF client is a confidential client as it runs server-side. Just make sure that there is a client secret configured.

**Comment by AndersAbel** [comment]
Are there any more questions about this or can we go ahead and close the issue?
