### ISSUE TITLE
best pratice for using FIDO w/ local user database

### ISSUE THREAD

**Issue by sebuseba** [DuendeSoftware/Support#967]
**Which version of Duende IdentityServer are you using?**
6.0.0

**Which version of .NET are you using?**
.NET 6.0

**question**

We use IdentityServer v6 with a "local" database for username/password credentials, so no external identity provider in that scenario.
We are currently looking into adding FIDO support & I found #779 & #244 were you basically point out that this is part of the hosting application, similar to what is described already for [MFA in your documentation](https://docs.duendesoftware.com/identityserver/v6/ui/login/mfa/).

Though, do you have any resources or best pratices for adding FIDO support in such a scenario? I could not find anything related in your existing [quickstart-samples](https://docs.duendesoftware.com/identityserver/v6/quickstarts/) or in this github-repo. Also the [ASP.NET Core docs](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-6.0#mfa-passkeysfido2-or-passwordless) I found mentions that `At present, ASP.NET Core doesn't support passkeys/FIDO2 directly`. 

Potentially this is something we could discuss in a remote consulting session? We do have a standard enterprise license.

Thanks in advance.

**Comment by AndersAbel** [comment]
Unfortunately we do not have any additional resources on FIDO. As you already know, FIDO authentication is something that would be added to the hosting application. To do that, any Asp.Net Core compatible FIDO library would do.

We know about a couple of options for integrating FIDO in Asp.Net Core:
* https://github.com/passwordless-lib/fido2-net-lib - MIT license.
* https://www.identityserver.com/products/fido2-for-aspnet - Commercial license.

I reached out to my colleagues and they have some experience with the OSS library, but it's been some years. So we do not really have any up to date recommendation.

**Comment by sebuseba** [comment]
Thanks a lot for your reply @AndersAbel.

We will look into those libraries.

The priority support my employer purchased w/ the Duende Enterprise Standard license could be used for integration-support of the OSS library? Or ist that solely for error support?

**Comment by AndersAbel** [comment]
The priority support is for error/troubleshooting. We do offer implementation/integration work as remote consulting services. Please reach out to contect@duendesoftware.com for more information.
