### ISSUE TITLE
IdentityServer WS-Federation Endpoint Issue

### ISSUE THREAD

**Issue by harmenstoopendaal** [DuendeSoftware/Support#968]
**Which version of Duende IdentityServer are you using?**
6
**Which version of .NET are you using?**
7.0
**Describe the bug**
We have a recurring issue with our IdentityServer setup related to the WS-Federation endpoint. This issue has been consistently logged in our database, and it looks like it pertains to the WS-Federation endpoint, which generates a warning: "WS-Federation endpoint only supports GET requests," followed by a status 405 error.

Details of the Issue:
- Frequent occurrence of the warning: "WS-Federation endpoint only supports GET requests."
- Recurring status 405 errors.
- examples 405 error;
- 1. Statuscode 405 forStatusCodeReExecuteFeature{ OriginalPath:"/wsfed",OriginalPathBase:"",OriginalQueryString:"?wa=wsignin1.0&wtrealm=https://tenantname.nl&wctx=rm=0&id=passive&ru=/Form/webMijnMeldingenTerInfo.aspx?KID=b640e175-a444-4b2e-96c3-c1bad45ae65b&MID=c7448e2e-e451-4753-8785-25c38357b6e9&wct=2023-10-31T13:35:06Z&tenantid=b640e175-a444-4b2e-96c3-c1bad45ae65b&enablelocallogin=",Endpoint:null,RouteValues:null}
- 2. Statuscode 405 forStatusCodeReExecuteFeature{ OriginalPath:"/connect/authorize",OriginalPathBase:"",OriginalQueryString:"?client_id=mvc&redirect_uri=https://companyname.nl/signin-oidc&response_type=code&scope=openid profile klant&code_challenge=exiZakvo8vOyNJFMyOmkcC-djYfvanA4hvLoubREjHk&code_challenge_method=S256&response_mode=form_post&nonce=638343560707141239.ODlkYWE2NTMtOGZkYy00MTcwLWE0ZjctZDNhNjY1MmQyZjMzYzAxYTM1MWUtYmRhNy00ZjA4LWExN2YtNGJiNmZkZTg4M2Zi&tenantid=868bba6e-a9ef-436b-b15b-fd6904c61dda&state=CfDJ8JAjuU1FsNtDm5_8HlKJFF8QneM9EVYHVBCNaNkZXjZrTqhbf-SAr430yRK079h5RLfUbwSbGFCP2pzZ5C49uBTTTVKycaCiLVY-ma2ng2xWdL-aaY1B8ERWlrdDfrxOLSNmo9QHIbw5RIyZIrKb_jmHKwLhz04dneo0bp9ZQLGYb4Y8rRb1g4NwGrYQBr_JNI5JLSZLuxm71S1e215zvslfdK4Sm_gpkS8Lcors7nxRLwS_4x29YxuYCXO33zkq6hlAszy6pAPkugMNFxQ7bP28OBXSYkhlz52e5AWSrIKj3eO2Yfrnnp7no4STXC7MLrO-tUS1Wpq90_Y6914a1ufuct0MFQYc_z_z61xwsRxES9_LmcJEQ5uYJWlTGq23riMztsRnF5h1id48Vtw3Aar-rjZP5m6t24yaOx7VlpWGlSh5tI0jv7gighz-zjgF6w&x-client-SKU=ID_NET6_0&x-client-ver=6.21.0.0",Endpoint:null,RouteValues:null}

**To Reproduce**
I can't reproduce it locally

**Comment by AndersAbel** [comment]
Could you please provider a bit more context? Do you have a WS-Fed plugin to IdentityServer to make IdentityServer act as a WS-Fed provider to client applications? Or have you configured IdentityServer to use an upstream WS-Fed provider to authetnicate users?

**Comment by harmenstoopendaal** [comment]
Yes, we use the WS-Fed plugin.

**Comment by harmenstoopendaal** [comment]
Yes, we have the WS-Fed plugin ( UseIdentityServerWsFederationPlugin() )

**Comment by AndersAbel** [comment]
Is it the plugin from Rock Solid Knowledge (identityserver.com)? In that case you need to contact them about support for the plugin they provide.
