### ISSUE TITLE
how to add custom claim to id token?

### ISSUE THREAD

**Issue by qttq23** [DuendeSoftware/Support#969]
**Which version of Duende IdentityServer are you using?**
PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="6.3.2"

**Which version of .NET are you using?**
7.0.402

**Describe the bug**
`ProfileService.GetProfileDataAsync` is never invoked for `id token`.

**To Reproduce**

just follow this tutorial: 
https://docs.duendesoftware.com/identityserver/v6/quickstarts/5_aspnetid/#adding-custom-profile-data

add logging like this:
```
protected override async Task GetProfileDataAsync(ProfileDataRequestContext context, ApplicationUser user)
        {
            Console.WriteLine("context.Caller: " + context.Caller);

            // .....
        }
```

output:
```
Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.TokenEndpoint for /connect/token
...
context.Caller: ClaimsProviderAccessToken
....

Invoking IdentityServer endpoint: Duende.IdentityServer.Endpoints.UserInfoEndpoint for /connect/userinfo
....
context.Caller: UserInfoEndpoint

```

never see `context.Caller: ClaimsProviderIdentityToken`
([reference of IdentityServerConstants.ProfileDataCallers](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/IdentityServerConstants.cs))

**Expected behavior**

the endpoint `/connect/token` should invoke `ProfileService.GetProfileDataAsync` to get claims for id token too. so that I can have a chance to add custom claims to id token.

**Comment by AndersAbel** [comment]
If the flow used supports an access token, the `id_token` is reduced to a bare minimum. This reduces the size of the `id_token`. The client application is expected to call the user info endpoint to get information about the user. All of this is described in the [OpenID Connect Specification](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims).

As long as the claims you want to add are description of the *user* and not something that varies between different sessions for the same user  this works well.

**Comment by qttq23** [comment]
thank you for nice link to specification. 
I tried request the `/connect/authorize` endpoint with `response_type=id_token` and the context is now `context.Caller: ClaimsProviderIdentityToken` and idtoken returned with custom claims inside it.
solved

**Comment by AndersAbel** [comment]
Yes, using a response type of `id_token` causes all the claims to be included in the token itself. However, it is not the recommended way. A response type of `id_token` is used to indicate the implicit flow, which is deprecated. All interactive applications should use the authorization code flow with PKCE (response type `code`).

If the client application/library is not able to use the user info endpoint to receive claims, there is a compatibility flag `AlwaysIncludeUserClaimsInIdToken` that can be set on the client configuration in IdentityServer. When set, that causes all claims to be in the `id_token`.

**Comment by qttq23** [comment]
oh it's nice to know there's an option called `AlwaysIncludeUserClaimsInIdToken`. I just want to include some info inside idtoken without another round trip to userinfo endpoint. I think I should go with this option.
