### ISSUE TITLE
Signout operation does not automatically detected with front-channel logout in case two or more domains

### ISSUE THREAD

**Issue by yartat** [DuendeSoftware/Support#97]
**Which version of Duende IdentityServer are you using?**
The latest Duende IdentitySever 6.1.0

**Which version of .NET are you using?**
Latest .NET 6

**Describe the bug**
The application uses multiply domains. The user tries signout. The operation will completed successfully on the domain where the signout was called, but the operation will not automatically detected on other domains with front-channel logout.

**To Reproduce**

The IdentityServer client is configured like this:
```csharp
{
    RedirectUris = new HashSet<string>
    {
	    "https://auth.xxxx.com/signin-oidc",
	    "https://app.xxxx.com/signin-oidc",
    },
    PostLogoutRedirectUris = new HashSet<string>
    {
	    "https://auth.xxxx.com/signout-callback-oidc",
	    "https://app.xxxx.com/signout-callback-oidc",
    },
    AllowedScopes = new HashSet<string>
    {
        "openid",
        "profile",
        "api"
    },
    UpdateAccessTokenClaimsOnRefresh = true
}
```
The system consists of a SPA application and API services. The SPA application is available on the domains auth.xxxx.com and app.xxxx.com. SPA uses front-channel logout (via call `https://auth.xxxx.com/connect/checksession`. IdentityServer 6 implementation)
The API service that uses IdentityServer is available on the auth.xxxx.com domain.
1. The user is signin on the auth.xxxx.com domain via SPA
2. He will receive an JWT access token. JWT access token contains sid claim. 
3. The user tries access the resource from the app.xxxx.com domain on another tab in the browser. 
4. He receives an error HTTP 401 and login silently by call `https://auth.xxxx.com/connect/authorize` with callback URL as `https://app.xxxx.com/signin-oidc`. 
5. The user will receive JWT access token with sid claim.
6. The user calls signout from auth.xxxx.com domain (on first tab in the browser). The SPA application calls `https://auth.xxxx.com/connect/endsession` and than will redirected to `https://auth.xxxx.com/logout?logoutId=<logout token>`
7. API service with IdentityServer clears cookies and removes server side session
8. SPA application detects session is logged out on the second tab and will call `https://auth.xxxx.com/connect/token`
9. API service with IdentityServer will return HTTP 200 with access JWT token without sid claim to SPA application on second tab.
10. Steps 8-9 repeat until user will try access to resource in the app.xxxx.com domain

**Expected behavior**
API service with IdentityServer should return HTTP 400

**Log output/exception with stacktrace**
None

**Additional context**

**Comment by brockallen** [comment]
>  The application uses multiply domains. The user tries signout. The operation will completed successfully on the domain where the signout was called, but the operation will not automatically detected on other domains with front-channel logout.
>  SPA uses front-channel logout (via call https://auth.xxxx.com/connect/checksession. IdentityServer 6 implementation)

This is expected given all the recent browser changes that block third party cookies. There's not much we can do abut that -- those changes break the OIDC specs that use iframes. The only real solution is back channel logout, which means your apps might need a new architecture:

https://blog.duendesoftware.com/posts/20210929_bff_update/
https://docs.duendesoftware.com/identityserver/v6/bff/overview/

**Comment by yartat** [comment]
Thanks a lot!
