### ISSUE TITLE
504 (Gateway Timeout)

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#970]
**Which version of Duende IdentityServer are you using?**
Community
**Which version of .NET are you using?**
7.0.113
**Describe the bug**
My React.JS / Next.JS application using `next-auth` library is getting 504 (Gateway Timeout) from time to time. Here is the config:
```
providers: [
  DuendeIDS6Provider({
    id: "myapp",
    name: "myapp",
    authorization: {
      params: { scope: "openid email address phone profile", protection: "pkce" },
    },
    issuer: process.env.DUENDE_IDS6_ISSUER || config.get('DUENDE_IDS6_ISSUER'),
    clientId: process.env.DUENDE_IDS6_CLIENT_ID || config.get('DUENDE_IDS6_CLIENT_ID'),
    clientSecret: process.env.DUENDE_IDS6_CLIENT_SECRET || config.get('DUENDE_IDS6_CLIENT_SECRET'),
    wellKnown: `${process.env.DUENDE_IDS6_ISSUER || config.get('DUENDE_IDS6_ISSUER')}/.well-known/openid-configuration`,
    idToken: true,
    httpOptions: {
      timeout: 10000,
    },
    profile (user, tokens) {
      console.log(`profile(): ${JSON.stringify(user, null, 2)}, tokens: ${JSON.stringify(tokens, null, 2)}`)
     }
  }),
],
```
![image](https://github.com/DuendeSoftware/Support/assets/3871483/9c4da953-e3e8-4765-9d1a-ca501df0a301)

Is it something due to the server?
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AndersAbel** [comment]
This looks like a network/hosting problem and not something that is related to IdentityServer itself.

**Comment by OmidID** [comment]
Hello @AndersAbel and @khteh 

We faced a similar issue recently only to the well-known endpoint. the rest of the application responding well.

Microsoft mentioned this issue back to the app itself and they get 504 after 240 seconds. 

I would like to know, how did you solve this problem.

Thanks in advance.

**Comment by AndersAbel** [comment]
@OmidID Please open a new issue as this is already closed.

**Comment by AndersAbel** [comment]
@OmidID Could you please have a look at #1361 to see if that is the reason for your issue. Also, if you have any additional information to share please do so in that thread.
