### ISSUE TITLE
How to retire a signing key when using automatic key rotation?

### ISSUE THREAD

**Issue by vladimir-kazakov** [DuendeSoftware/Support#971]
I use Duende IdentityServer 6.3.5 on .NET 7, and I have the follow setup:
```csharp
options.KeyManagement.SigningAlgorithms = new[]
{
	new SigningAlgorithmOptions(SecurityAlgorithms.RsaSsaPssSha256), // PS256
	new SigningAlgorithmOptions(SecurityAlgorithms.EcdsaSha256), // ES256
	new SigningAlgorithmOptions(SecurityAlgorithms.RsaSha256) // RS256
};
```

If I want to retire the last key (RS256), how should I do it properly?

If I understand correctly, I need:
1. To make the key usable only for validation until its expiration.
2. To tell IdentityServer to stop generating new keys that use this algorithm.

I'm having difficulties with both of these things. I can't find APIs that would allow me to do something like this. Perhaps, it can be achieved in a different way?

I've tried simply removing the key (the algorithm from the options), but then it just disappears from the discovery document. Clients that received security tokens signed with this key won't be able to validate it in this case.

**Comment by AndersAbel** [comment]
If I understand you right, you want to retire a signing algorithm, including preventing any more keys from being generated using that algorithm.

What matters is however not the lifetime of the keys, but the lifetime of any tokens signed with those keys. Once all tokens signed with a specific key/algorithm has expired that key can safely be removed from the system.

If that is not possible, you are right in the basic steps:
1. Make sure the keys stay available for validation.
2. Make sure IdentityServer do not use the keys.

There is unfortunately not any built in feature in IdentityServer to keep all keys for a specific algorithm available in the discovery document, but prevent them from being used. 

IdentityServer by default uses the first algorithm in the list when signing keys. That means that with your setup, the `RsaSsaPssSha256` algorithm should be used by default. As long as no clients are configured to use `RsaSha256` it should already be retired. Once you have validated that no clients are using the `RsaSha256` algorithm any more, it should be safe to remove that algorithm from the settings, even though it causes the key to immediately be removed from the discovery document.

**Comment by AndersAbel** [comment]
Are there any more questions on this issue or can we go ahead and close it?

**Comment by vladimir-kazakov** [comment]
Thanks for your help! I'll close this issue, since it's clear now what to do in this situation.

I think, I was confused by the presence of API that allows adding [validation keys](https://docs.duendesoftware.com/identityserver/v6/fundamentals/keys/static_key_management/#phase-2-start-signing-with-the-new-key). I thought I had to do something similar.

I also wasn't considering that clients can be configured to use a specific algorithm. So, you're right:
> As long as no clients are configured to use RsaSha256 it should already be retired.

Now it's clear that if an algorithm has to be retired, there is a need to reconfigure clients (if needed) to use other algorithms, and then wait for a period of time equal to the longest lifetime of a security token.
