### ISSUE TITLE
Is it possible to use SignalR JS client through BFF to forward the websockets connection to remote API?

### ISSUE THREAD

**Issue by yungeggz** [DuendeSoftware/Support#972]
**Which version of Duende BFF are you using?**

2.0

**Which version of .NET are you using?**

.NET 6

Is it possible to use SignalR JS client through BFF to forward the websockets connection to remote API? 

I have an IdentityServer protected WebAPI using a custom auth policy. One of the client apps is an Angular 15 / .NET 6 BFF setup that uses the forwarder to easily map local API routes to the remote WebAPI and includes the appropriate token for auth, etc.

In trying to setup a demo using SignalR, I haven't been able to get the websockets or server-sent events transports to work via the forwarder extension methods. It does successfully fallback to long-polling but I think the current issue I'm running into is that the BFF is marking my websockets call as invalid because there's no X-CSRF header present coming from the frontend -- this is a bit of an odd situation because the websocket protocol doesn't allow for headers to be used with it

**Comment by yungeggz** [comment]
I fat fingered some key before I got a chance to fill out the details of this -- incase it is seen as empty. Filling out now

**Comment by yungeggz** [comment]
Looking in the BFF source at how the `MapRemoteBffApiEndpoint` extension method works helped me update my local extension method to append the `.SkipAntiforgery()` extension onto the result of `MapRemoteBffApiEndpoint()` however this has caused me to hit a wall - in trying to setup auth on the outgoing request via `RequireAccessToken(TokenType.User)`, realizing that isn't going to work for the websockets type connection. Wondering if it's possible to override the BFF where it removes the browser cookie and applies the bearer token -- so that I can attach that token via HTTPS/TLS & querystring

**Comment by yungeggz** [comment]
Providing another update here as I've gotten further but still running into some issues.

adding `ws: true` to `proxy.conf.js` was needed to get the connection into the BFF host, along with switching from using the remote API extensions to define the endpoint using the more granular YARP config approach.

Put YARP config together using the basic Duende example docs:

```
  "ReverseProxy": {
    "Routes": {
      "todos": {
        "ClusterId": "cluster1",
        "Match": {
          "Path": "/signal/{**catch-all}"
        },
        "Metadata": {
          "Duende.Bff.Yarp.TokenType": "User",
          "Duende.Bff.Yarp.AntiforgeryCheck": "false"
        }
      }
    },

    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "https://localhost:6001"
          }
        }
      }
    }
  }
```

I've added a request transform that pulls the token out of HttpContext and appends it to the outgoing URL querystring.

```
builder.Services.AddReverseProxy()
      //.AddBffExtensions()
      .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"))
      .AddTransforms(builder =>
      {
          builder.AddRequestTransform(async (ctx) =>
          {
              var token = await ctx.HttpContext.GetTokenAsync("access_token");
              if (ctx.ProxyRequest.Headers.Contains("Authorization") == false)
              {
                  ctx.ProxyRequest.Headers.Add("Authorization", $"Bearer {token}");
              }

              ctx.Query.Collection.Add("access_token", token!);
          });
      });

```

and on the receiving API, when we configure JWT Bearer AuthN, we have a hook to pull that value out of the query and assign it to the token

```
  options.Events = new JwtBearerEvents
  {
      OnMessageReceived = context =>
      {
          var accessToken = context.Request.Query["access_token"];

          // If the request is for our hub...
          var path = context.HttpContext.Request.Path;
          if (!string.IsNullOrEmpty(accessToken) && (path.StartsWithSegments("/signal")))
          {
              // Read the token out of the query string
              context.Token = accessToken;
          }
          return Task.CompletedTask;
      }
  };
```

I can get the breakpoint with the access token to hit for websockets and be received on the SignalR hub endpoint but am losing the connection ID in the process generated by the clientside Signal library. YARP supposedly supports websockets OOTB without any additional configuration so my current best guess is that it has something to do with the actual YARP config file I've setup, and how that is not preserving the connection id param when it transforms the request.

**Comment by AndersAbel** [comment]
Thanks for sharing your progress on this. I think that for this kind of scenarios, you're right in that the full-blown yarp configuration is needed, rather than the extension methods we provide for simple cases.

The connection id is something that, as you say, should be handled by Yarp.

There's one more thing/challenge I would like to point out here: expiry of access tokens. The call to `HttpContext.GetTokenAsync("access_token")` gets the *current* access tokens. The transform that we add uses `Duende.AccessTokenManagement.OpenIdConnect.IUserTokenManagementService.GetAccessTokenAsync()` to get the token. It automatically uses the refresh token to get a new access token when needed.

**Comment by Daxton47** [comment]
Yes, is it possible? :) the only solution mentioned here doesn't make it clear that it actually resolved the issue, or perhaps I misunderstood.

**Comment by AndersAbel** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.
