### ISSUE TITLE
Need to log remote ip adress for X-Forwared-For

### ISSUE THREAD

**Issue by henke-d** [DuendeSoftware/Support#973]
**Which version of Duende IdentityServer are you using?**
6.1.3

**Which version of .NET are you using?**
Net 6.0

I am using the logging features to monitor user login/out etc and it is great. But the IP adress for the key="RemoteIpAddress" is our load balancer. Is it possible in some way to instead log the adress from header X-Forwared-For

**Comment by AndersAbel** [comment]
In the Asp.Net Core model, the hosting application should take care of the `X-Forwarded-For` header and update the RemoteIpAddress of the HttpContext connection. Please see [Microsoft's documentation on deploying Asp.Net Core behind load balancers](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0) for more information.

**Comment by henke-d** [comment]
Ahh of course, thanks for the quick response!
