### ISSUE TITLE
Issue in migrating Identity server 4 models to Postgres db from asp.net core MVC

### ISSUE THREAD

**Issue by tejaswi7898** [DuendeSoftware/Support#975]
When migrating Idenityserver 4 models like ApiResource, client and Apiscope collections to postgresql db using the below migration commond(code first approach), all the ICollection<string> tables are not creating as a separate table, few are like creating as a string column. This is causing issue while fetching the data from database saying there is a mismatch between the data types from Icollection<string> to string
**Command used to migrate in Package manager console**
Add-Migration InitialCreate -Context ConfigurationDbContext -Output Migrations/ConfigurationDb

**Error we are getting while fetching the data**
System.InvalidOperationException: 'The property 'ApiResource.AllowedAccessTokenSigningAlgorithms' could not be mapped because it is of type 'ICollection<string>', which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.'

Could anyone suggest to migrate the idnetity server 4 models to postgres db to mitigate the above issue or suggest any other appraoch

**Comment by AndersAbel** [comment]
What version and migrations are you working on? You have an existing IdentityServer4? Do you want to change your IdentityServer4 to use a PostgreSql DB? Or do you have an existing IdentityServer4 using PostgreSql that you know what to migrate to Duende.IdentityServer6 (still using PostgreSql)?

**Comment by AndersAbel** [comment]
Are there any more questions on this issue or can we go ahead and close it?

**Comment by AndersAbel** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.
