### ISSUE TITLE
Duende.AccessTokenManagement .NET framework support

### ISSUE THREAD

**Issue by chunk1ty** [DuendeSoftware/Support#976]
What is the reason for not supporting .NET framework?

What if we change TargetFramework from **net6.0** to **netstandard2.0**?

**Comment by AndersAbel** [comment]
Duende.AccessTokenManagement is built for Asp.Net Core 6 and up, which is not supported on .Net Framework. I don't really see how it would make sense to make it build for .NET framework. What would the use case be?

**Comment by AndersAbel** [comment]
Are there any more questions on this issue or can we go ahead and close it?
