### ISSUE TITLE
BFF AngularJS Sample example

### ISSUE THREAD

**Issue by dhmuralikrishna** [DuendeSoftware/Support#977]
*Duende 6

In BFF AngularJS example how to make todos call the backend host instead of localhost 
https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v6/BFF/AngularBffSample/src/FrontendHost/Program.cs

uncommented these two lines. 

// app.MapRemoteBffApiEndpoint("/todos", "https://localhost:5020/todos")
//     .RequireAccessToken(Duende.Bff.TokenType.User);

Expecting it will call the backend host /todos endpoint instead it always calls local /todos endpoint

Also tried to change /todos to /api/todos. I am getting endpoint not found error.
// app.MapRemoteBffApiEndpoint("/api/todos", "https://localhost:5020/todos")
//     .RequireAccessToken(Duende.Bff.TokenType.User);

**Comment by AndersAbel** [comment]
Did you comment out the `MapControllers()` call? It is before the `MapRemoteBffApiEndpoint()` call in the pipeline. So if both are active, the first one will handle the request.

**Comment by AndersAbel** [comment]
Are there any more questions on this issue or can we go ahead and close it?

**Comment by AndersAbel** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.
