### ISSUE TITLE
Server-Side Sessions not getting cleared/removed 

### ISSUE THREAD

**Issue by navmir-accigo** [DuendeSoftware/Support#978]
**Which version of Duende IdentityServer are you using?**
6.2.0

**Which version of .NET are you using?**
7.0 

**Describe the bug**
After a server-side session has been successfully created and persisted/stored in a DB, it does not get removed even though its expiration time has passed.  

**To Reproduce**
In my Startup.cs, I've injected .AddIdentityServer to my service collection with the following options:

 options.ServerSideSessions.ExpiredSessionsTriggerBackchannelLogout = true;
 options.ServerSideSessions.RemoveExpiredSessions = true;
 options.ServerSideSessions.UserDisplayNameClaimType = JwtRegisteredClaimNames.Name;
 options.ServerSideSessions.RemoveExpiredSessionsFrequency = TimeSpan.FromSeconds(60);

followed by .AddServerSideSessions(), and then setting up both .AddConfigurationStore() and AddOperationalStore() with options connecting to our DB.

**Expected behavior**
That the server-side session should get removed from the DB when expiration time has passed once the clean-up service (ServerSideSessionCleanupHost) have had its run, from which I understand should be injected when calling .AddServerSideSessions().

**Additional context**

I've tried to manually set the expiration time to 2 and 5 minutes from the moment it has been created, but to no avail. This was done in code, where I'm fetching the session for the user and successfully updating it. Also tried updating the expired time directly in the DB, but still doesn't work.

**Comment by AndersAbel** [comment]
It looks like the settings are right. Do you get any information in the logs from the cleanup job?

**Comment by navmir-accigo** [comment]
Hi Anders,

The cleanup job never runs. When checking the logs and waiting for 5 minutes, below is all there is in my logs. Worth noting is that I've set the cleanup timer to every 60 seconds.

```
[11:34:26 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: Identity.Application signed in.

[11:35:04 Debug] Duende.IdentityServer.Stores.ServerSideTicketStore
Retrieve AuthenticationTicket for key 19D2AA...

[11:35:04 Debug] Duende.IdentityServer.EntityFramework.Stores.ServerSideSessionStore
Found server-side session 19D2AA... in database: True

[11:35:04 Debug] Duende.IdentityServer.Stores.ServerSideTicketStore
Ticket loaded for key: 19D2AA..., with expiration: 11/07/2023 11:36:24
```

**Comment by AndersAbel** [comment]
Can you please try increasing the log levels to see if we can get more details?

Could you please use a breakpoint to inspect that the `ServerSideSessionCleanupHost` is correctly present in the service collection at the end of the startup?

**Comment by AndersAbel** [comment]
Are there any more questions on this issue or can we go ahead and close it?

**Comment by AndersAbel** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.
