### ISSUE TITLE
How to configure to return email from /bff/user endpoint?

### ISSUE THREAD

**Issue by Alexandr-Pletnev** [DuendeSoftware/Support#979]
How to configure to return email from /bff/user endpoint?

**Comment by AndersAbel** [comment]
All claims that are available in the BFF session are returned from the `/bff/user` endpoint. To get email included, please make sure that the OpenID Connect configuration includes email. 

* Configure the BFF/client to request the `email` scope.
* Ensure that there is an email claim available on IdentityServer.
* Configure the email IdentityResource.
* Add email to the list of allowed scopes on the client configuration in IdentityServer.
