### ISSUE TITLE
Question about authentication in razor pages after logging in (using the Blazor WASM template)

### ISSUE THREAD

**Issue by joe912** [DuendeSoftware/Support#98]
Duende.IdentityServer 5.2.0

.Net 6

I have created a new Solution using the Blazor WASM template in Visual Studio 2022 verion 17.2.4

I want to use both Blazor and Razor pages in my site.  I want both Blazor and Razor pages to work with the authentication.

After doing File -> New Project, I have added two razor pages in the following paths of the Server project:

- Areas/Identity/Pages/Test1.cshtml
- Pages/Test2.cshtml

Both pages contain the following identical markup:
```
@if (User.Identity.IsAuthenticated)
{
    <span>@User.Identity.Name is authenticated</span>    
}
else {
    <span>Not authenticated</span>
}
```

After starting the site, and logging in, if I navigate to /Identity/Test1 it says 'authenticated' but if I navigate to /Test2 is says 'not authenticated'

I guess that I am missing some configuration to enable authentication to work outside the 'Identity' area?  Please can you point me in the right direction?

Many thanks
Joe

**Comment by brockallen** [comment]
> I have created a new Solution using the Blazor WASM template in Visual Studio 2022 verion 17.2.4

That template is created and maintained by Microsoft, so they would know/understand best how it works. They would be the best ones to ask. 

My guess, though, is that they don't enable the cookie auth scheme as the default (IIRC they configured the JWT bearer for API calls from the JS to API endpoints). You'd need to put an [Authorize(AuthenticationSchemes ="YourCookieScheme")] on those razor pages. and IIRC the scheme used by ASP.NET Identity (by default) is `IdentityConstants.ApplicationScheme`.

**Comment by joe912** [comment]
Thanks for that link @brockallen.  I think we may have to rethink using the MS template.

**Comment by joe912** [comment]
> You'd need to put an [Authorize(AuthenticationSchemes ="YourCookieScheme")] on those razor pages. and IIRC the scheme used by ASP.NET Identity (by default) is `IdentityConstants.ApplicationScheme`.

This worked, thanks.
