### ISSUE TITLE
URL is changing after configuring proxy server on azure using application gateway

### ISSUE THREAD

**Issue by itsutkarshgoyal** [DuendeSoftware/Support#980]
**Which version of Duende Identity Server are you using?**
Identity Server 6
**Which version of .NET are you using?**
.Net 6
**Describe the bug**
I have configured the proxy server using azure gateway and done necessary configuration but URL is getting changed when calling through client app.
I have also checked the well known configuration , in that all URL's are not proxy server URLS but original  URLS . 
I have also configured the forwarded headers and set env variable ASPNETCORE_FORWARDEDHEADERS_ENABLED true in my container app.

**Comment by itsutkarshgoyal** [comment]
Please find the configuration 
![forwardHeader](https://github.com/DuendeSoftware/Support/assets/52861039/079ac04e-426d-4f82-b32f-c93347a1fe2d)
![Uploading issuerUrl.png…]()

**Comment by itsutkarshgoyal** [comment]
yes ,  i have called it before before identity server

**Comment by itsutkarshgoyal** [comment]
@AndersAbel  ?

**Comment by AndersAbel** [comment]
If you access the discovery document (.well-known/openid-configuration) from a browser, does it show the correct URLs?

Can you please describe a bit more what happens when the client connect? Where does the incorrect URL show up?

**Comment by itsutkarshgoyal** [comment]
No , in .well-known/openid-configuration , only IssuerUri is correct which i have manually set , rest all URLS are not correct.
![issuer](https://github.com/DuendeSoftware/Support/assets/52861039/56e39f56-0b8d-4458-8069-22f4905e4a32)

I have client in react , there we are using @axa-fr/oidc-client library to pass configuration of identity like below.
![react](https://github.com/DuendeSoftware/Support/assets/52861039/38fb7fb1-e3e9-42c6-92e3-b50c9cc4d55a)

When client app calls identity , then it gets opens the login page with containers original URL instead of proxy URL which is configured in IssuerUri

**Comment by AndersAbel** [comment]
Setting the `IssuerUri` should not be required in this scenario, it should resolve automatically together with the other URLs. If the discovery document contains the incorrect/internal URLs then the forwarded headers setup is not correct. IdentityServer requires those to be correctly setup on the infrastructure/hosting level.

**Comment by itsutkarshgoyal** [comment]
can you guide or have any  possible steps to debug the issue

**Comment by AndersAbel** [comment]
I'm afraid that is beyond what we can help with. In the Asp.Net Core programming model it is up to the hosting/infrastructure layer to have a proper setup of forwarded headers. Duende.IdentityServer works under the assumption that the `HttpContext.HttpRequest.Host` is set to the correct value as seen by the client browser.
