### ISSUE TITLE
Session ID claim (sid) missing, what are the controlling factors and options?

### ISSUE THREAD

**Issue by devbeard** [DuendeSoftware/Support#981]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
.NET 7

**Describe the bug**
Not a bug, question: We are not getting the sid-claim (session id) in the identity token. What are the controlling options for this in IdentityServer, or what factors and conditions would disable the output of this claim? 

**To Reproduce**

N/A

**Expected behavior**

The `sid` claim appearing in the identity token

**Log output/exception with stacktrace**

```
N/A
```

**Additional context**

N/A

**Comment by AndersAbel** [comment]
What OpenID Connect flow are you using?

**Comment by devbeard** [comment]
Web-app-clients, so Authorization Code with PKCE.

_Just an aside:_ We also have a debug view in the IdSrv host itself, that just enumerates the claims from User.Claims, but since that is local authority, no client, does not trigger the profile service etc. I should not expect that to include the claim?

```
@foreach (var claim in User.Claims)
{
    <tr>
        <td>@claim.Type</td>
        <td>@claim.Value</td>
        <td>@claim.Issuer</td>
    </tr>
}
```

**Comment by AndersAbel** [comment]
Are there any more questions on this issue or can we go ahead and close it?

**Comment by AndersAbel** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.
