### ISSUE TITLE
Azure Front Door issue

### ISSUE THREAD

**Issue by hrjjml** [DuendeSoftware/Support#984]
**Which version of Duende IdentityServer are you using?**
6.3.5

**Which version of .NET are you using?**
7.0

**Describe the bug**
The IDS app cannot resolve the custom domain since it's added to Front Door not directly to the app service.

**Expected behavior**
SAML request validation should pass
Well-known configuration should show the custom domain, not Azure domain

**Log output/exception with stacktrace**

2023-11-07 18:52:29.104 +00:00 [ERR] SamlSingleSignOnRequestValidatorDecorator
SamlSingleSignOnRequestValidatorDecorator.Validate: Invalid SAML Request
Invalid SAMLRequest Destination
Received message destination: 'https://login.membership.qa.nacdonline.org/saml/sso'. Expected: 'https://ids-qa-webapp.azurewebsites.net/saml/sso'

**Comment by hrjjml** [comment]
this link helps: https://docs.duendesoftware.com/identityserver/v6/deployment/proxies/

**Comment by AndersAbel** [comment]
The error indicates that forwarded headers are not correctly setup.

A simple way to validate this is to open the discovery document at /.well-known/openid-configuration using the public address. If the URLs in there are correct, then forwarded headers are correctly setup.
