### ISSUE TITLE
How to update databases when upgrading the packages?

### ISSUE THREAD

**Issue by Jeff-Tian** [DuendeSoftware/Support#985]
**Which version of Duende IdentityServer are you using?**

6.3.6
<img width="654" alt="image" src="https://github.com/DuendeSoftware/Support/assets/3367820/9b005023-8513-4781-b318-d49732b423f9">

**Which version of .NET are you using?**

7.0.402

**Describe the bug**

Not a bug but I need help. I upgrade the nuget packages from 6.0.0 to 6.3.6 to use the `server side sessions`. But after upgraded the packages, now I met these errors:  "relation 'ServerSideSessions' does not exist" .

I use Entitiy Framework but I don't know how to do the proper operations to fix it.

I've done the following when I setup the application with 6.0.0 packages:

    - dotnet ef database update --project src/xxx/xxx.csproj --context ConfigurationDbContext
    - dotnet ef database update --project src/xxx/xxx.csproj --context PersistedGrantDbContext
    - dotnet ef database update --project src/xxx/xxx.csproj --context ApplicationDbContext 

Now I upgraded to 6.3.6, what should I do?

**To Reproduce**

Upgrade duende identityserver from 6.0.0 to 6.3.6 and use the ISessionManagementService.

`private readonly ISessionManagementService _sessionManagementService;`

**Expected behavior**

Documentation on how to run database migrations when upgrading.

**Log output/exception with stacktrace**

```
data
```

**Additional context**

**Comment by AndersAbel** [comment]
The same `dotnet ef database update` commands should be run again to update the database with the new columns.

The upgrade should be validated by running on a non production database first. When running in production, make sure that there is a database backup available if a rollback would be needed.
