### ISSUE TITLE
Session id claim was lost after request refresh token

### ISSUE THREAD

**Issue by yartat** [DuendeSoftware/Support#99]
**Which version of Duende IdentityServer are you using?**
The latest Duende IdentitySever 6.1.1

**Which version of .NET are you using?**
Latest .NET 6

**Describe the bug**
In case client has settings `UpdateAccessTokenClaimsOnRefresh = true` the sid claim will be lost after first refresh token.

**To Reproduce**
The client setup with 
```csharp
{
    UpdateAccessTokenClaimsOnRefresh = true,
    AllowOfflineAccess = true,
}
```
- User successfully authenticates with OIDC Authorization Code Flow
- User retrieves tokens via `/connect/token` with authorization code. JWT access token contains `sid` claim.
- User refreshes tokens via `/connect/token` with refresh token. JWT access token does not contain `sid` claim.

**Expected behavior**
JWT access token should contain `sid` claim.

**Log output/exception with stacktrace**
None

**Additional context**
Please, review the PR https://github.com/DuendeSoftware/IdentityServer/pull/942

**Comment by brockallen** [comment]
PR submitted -- we will track there. Thanks.
