### ISSUE TITLE
Is it necessary to call context.Success()?

### ISSUE THREAD

**Issue by DavidKlempfner** [DuendeSoftware/Support#990]
I'm using Identity Server 6 and .NET 6.

I have a working OIDC solution where my client app calls IDS which uses Okta.

I've implemented a custom `OpenIdConnectEvents` class.

```
    public class MriOpenIdConnectEvents : OpenIdConnectEvents
    {
        
        public MriOpenIdConnectEvents()
        {
            OnTokenValidated = OnTokenValidatedImpl;
        }

        private Task OnTokenValidatedImpl(TokenValidatedContext context)
        {
            context.Success();
            Trace.TraceInformation(string.Concat(nameof(MriOpenIdConnectEvents), ".", nameof(OnTokenValidatedImpl)));
            return Task.CompletedTask;
        }
    }
```
I noticed `context.Success()` results in `context.Result` having a value. I can see the Identity property is populated with the claims from Okta.
However, if I comment out `context.Success();`, everything still works, ie. I the tokens and cookies are still sent.

What is the point in calling `context.Success()`?

**Comment by josephdecock** [comment]
This is part of the ASP.NET OIDC handler, not IdentityServer or our other products that we support here. If you want to get into the details of the eventing within the handler, the Microsoft documentation and asp.net issue tracker are where I would take those questions. I can tell you though, that you probably don't need this event at all. The success method is a low-level api intended for advanced use cases where you are customizing the behavior of the handler. Absent that, you don't need to do this.
