### ISSUE TITLE
.Net 8?

### ISSUE THREAD

**Issue by khteh** [DuendeSoftware/Support#992]
**Which version of Duende IdentityServer are you using?**
Business (Standard)
**Which version of .NET are you using?**
7.0.113
**Describe the bug**
Is your library .Net 8 ready? If not, when?

**Comment by josephdecock** [comment]
Support for .NET 8 is coming in the next major version of IdentityServer. We have a [preview ](https://www.nuget.org/packages/Duende.IdentityServer/7.0.0-preview.1) available now, and we're going to be making another preview build as soon as .NET 8's GA builds go up. That build will be a final preview and our proper 7.0 release will follow early next year. We'll have [blog](https://blog.duendesoftware.com/) posts about the new release and some of the big new features (PAR and OTel Metrics) coming very soon as well.

**Comment by khteh** [comment]
Will it break if I upgrade my applications to .Net 8 before you?

**Comment by josephdecock** [comment]
We had to make some fixes in IdentityServer to support .NET 8, and we won't officially support IdentityServer on .NET 8 until our next major release.

Your client applications can upgrade .NET 8 independently from that though.
