### ISSUE TITLE
Using ClientCorsOrigin to avoid CORS issue

### ISSUE THREAD

**Issue by motakill** [DuendeSoftware/Support#994]
**Which version of Duende IdentityServer are you using?**
6.0.0
**Which version of .NET are you using?**
.net6.0
**Describe the bug**

We are developing in our test environment a new version of our code base to authenticate our clients. We are getting some CORS issues.

For example we allowed for a certain clientID (registered in our DB in Clients Table) certain Origins by inserting this Origins in ClientCorsOrigin table associating to the clientID. But this isn't working.

After that we just tryied to define in Startup of our application this code sample:

app.UseCors(x => x
           .AllowAnyMethod()
           .AllowAnyHeader()
           .AllowCredentials()
        .SetIsOriginAllowed(origin => true));

With this we allowed every Origins to all of our clients, but we don't want that, we want to have the control for every clientId. 

Is there something that we are missing?

**Comment by AndersAbel** [comment]
Can you please describe some more details on the CORS issues? Do you get log entries and in that case what is the message? Are there any user flows that fails in the browser?

**Comment by AndersAbel** [comment]
I'm closing this issue for now due to lack of activity, but please feel free to reopen if needed.
